== Testimony

[.chapter-subtitle--blurb]
A Memorial of the Monthly Meeting of Friends of Philadelphia, for the Southern District,
held Ninth Month 23rd, 1868, concerning William Evans.
Approved by the Yearly Meeting of Friends held in Philadelphia, 1869.

From a belief that much encouragement may be derived by survivors,
from contemplating the consistent example of those who during
a long life have been dedicated to the Lord`'s service,
and enabled, through obedience to his Holy Spirit,
to promote the cause of truth and righteousness in the earth,
we are engaged to preserve a memorial of our beloved friend, William Evans.

He was the son of our late valued friends, Jonathan and Hannah Evans,
and was born in Philadelphia the 5th day of the Tenth month, 1787;
and during his whole life was a member of this Monthly Meeting.
From memoranda which he states he believed it right to
preserve of the Lord`'s dealings with him,
it appears he was of a quick, lively disposition when young,
and disinclined to restraint, which increased as he grew older.
The society of religious people was irksome to him,
and he sought the company of those whose passions and
propensities were unsubjected to the Cross of Christ.
By pursuing this course he remarks: "`Corruption strengthened,
the innocency of childhood was tarnished,
and my carnal appetites began to seek indulgences
totally at variance with purity of heart,
and that life which my parents earnestly labored
to inculcate and keep their children in.`"

While learning the business which he afterwards followed,
he was exposed to many temptations,
being much separated from the care of his anxious and exercised parents,
and subjected to interaction with those who knew
little or nothing of the work of religion.
In this season of danger Divine mercy was extended to him,
and he was kept from falling into the evil habits and
conversation of some of his young companions.

It was the practice in his father`'s family frequently to read
aloud in the Holy Scriptures and the writings of Friends.
On one occasion, when collected for that purpose,
he was brought into much contrition by reading William
Leddra`'s epistle written the day before his execution.
"`It was,`" he says,
"`an extraordinary visitation of heavenly love, the savor of which continued many days,`"
producing a sense of his sinful,
impure condition; and fervent desires were raised after holiness.
"`The Light of Christ shone clearly into my heart,`" he remarks,
"`showing me that many of my habits were contrary to the Divine purity,
and must be abandoned--that many of my words were light and unsavory,
and a guard must be placed at the door of my lips.

Love flowed into my heart toward my gracious, Almighty Parent preeminently,
and then toward all men as brethren and creatures of the same all-powerful Hand.
I desired above all things to be with Jesus, and to know Him to continue with me,
and at that time it seemed as if He did condescend to manifest Himself in a clear manner,
so that his countenance was lovely,
and I walked under his guidance and protection with great delight.
It was the baptism unto repentance, the day of my espousals, the beginning of a new life;
and while favored with these heavenly feelings,
I thought nothing would be too hard to part with in obedience to the will of my Savior.

He was at this period about seventeen years of age,
and although he had set out in earnest to walk in the straight and narrow way,
he found that his evil propensities were still strong,
and his soul`'s enemy unwearied in endeavors to overcome him.

For lack of keeping on the watch, he yielded to temptation,
and was thereby introduced into much conflict and distress,
and made sensible of the Divine displeasure; yet in the midst of judgment,
the Lord remembered mercy, and through the operation of his blessed Spirit,
brought him again to tenderness of heart,
and humbled him under a sense of unworthiness of his condescension and love.

About the twentieth year of his age he appears to have passed
through many baptisms and mortifying dispensations,
doubtless designed for his purification and refinement.
He also experienced seasons of Divine consolation,
wherein he says he was enabled to pour out his soul before the Lord,
and fervently craved to be made one of his children,
and to serve Him all the days of his life.
At one period, when passing through a time of great seeming desertion,
the enemy took advantage of his bereaved condition,
and started the doubt whether Jesus Christ was his Savior,
and insinuated that he had never heard his voice.

Not being able to feel that faith in the Lord
Jesus Christ which he thought he once possessed,
"`great distress and anxiety,`" he says, "`came upon me.
I searched the Holy Scriptures,
and diligently read various religious works which I hoped would restore the lost pearl,
but it was all in vain.
I was utterly unable to regain my faith in Christ,
which had been an anchor to my soul in many tossings and tempests.`"
For a long time he was kept in this condition,
until he ceased searching books or striving to satisfy himself by argument.
"`I looked up to my Heavenly Father,`" he remarks,
"`but all was hid from me, and I wondered how it was that I should be
unable to believe in the Lord Jesus Christ who,
I had been taught, and never had doubted, was the Savior.`"
Through this distressing conflict he was kept steadfast and patient;
and one evening while walking out for meditation, with his mind turned toward the Lord,
he says, "`He whom my soul sought above all things suddenly came to his temple,
and by his Holy Spirit gave me to see that He alone is the author of that
faith which enters within the veil and gives victory over the world,
the flesh, and the devil; and that it is not founded merely on what is read,
but is really of the operation of God on the heart.
I rejoiced exceedingly and gave thanks to Him who is worthy of all praise and honor,
and who will not give his glory to another.
I could now firmly believe in the Lord Jesus as my Savior,
because of the renewed revelation of the Holy Spirit giving me that faith in Him;
and through mercy I have never since been permitted to
feel any doubt respecting his divinity,
his mediation, or any of his offices in the redemption and salvation of man.
I record this under a sense of my own nothingness,
and for the purpose of exalting the glory of his grace,
believing that the foundation of true gospel saving
faith is the immediate manifestation of the Holy Spirit;
and it is this which draws the dedicated soul to Christ,
and enables it to believe in Him savingly,
to rely upon and to follow Him as our Redeemer and the Captain of our salvation.`"

He referred to this dispensation later in life as a peculiar favor and blessing;
and it was no doubt a means of preparing him firmly to defend the
fundamental doctrine of the divinity of our Lord and Savior Jesus Christ,
when in after years it was openly denied by many under our name,
and also to preserve him from the error of regarding the Holy
Scriptures as the origin and ground of that faith which comes
only through the operations of Divine Grace in the heart.
"`The Scriptures,`" he remarks,
"`are an invaluable record of all those things most
surely believed by the faithful followers of Christ,
who have the opportunity of reading them;
but it is God alone who can give true and saving faith
in his beloved Son and in the truths of the Gospel,
and it is by his mercy we are preserved to the end in the possession of that faith.`"

After commencing business on his own account,
he had great fear of bringing a shade or reproach on the profession of the Truth,
or upon our religious Society; and whenever anything presented, however profitable,
which appeared to conflict with either, he felt most easy to decline engaging in it.
His business was small,
and on one occasion he was brought under concern lest
it should not prove adequate to his necessities;
but his gracious Master condescended to show him
that if he was faithful to his requirings,
he should never lack food or raiment.

"`The language and impression were so clear,`" he says, "`humbling my heart before Him,
that I believed his word; and thereby proved that that faith of which He is the author,
is the substance of things hoped for, the evidence of things not seen.
My mind firmly and peacefully rested in it,
as much as it would have done in an independent estate,
although no change in my business very soon occurred.`"

Not long afterwards an opportunity presented for engaging in more extensive business,
and he felt strongly inclined to embrace it,
especially as that which he was then pursuing
had been seriously interfered with by the war,
so that it appeared doubtful whether it would support his family.
A secret uneasiness, however, attended his mind in reference to the change,
and he remarks, "`My doubts increased, and one day, sitting in our religious meeting,
it plainly appeared to me that though the mind may be able to compass much,
yet beyond its capacity it cannot go.
If all its energies are enlisted in the concerns of the world,
and their pressure is as great as it is capable of bearing,
the all-important work of religion must be neglected.`"
These impressions made him afraid to risk his
everlasting salvation for the sake of worldly emolument,
and led him to the conclusion that it would be safer for him to decline the offer;
and when this was done his mind was made easy,
and he was able to repose in humble confidence in Divine Providence;
"`remembering,`" he says, "`that the earth is the Lord`'s,
and the cattle on a thousand hills; and He, in inscrutable wisdom and kindness,
will dispense what He knows we need.`"
Subsequent events showed that if he had followed his own
inclination and judgment on the occasion referred to,
he would probably have become involved in great embarrassment and anxiety,
and perhaps been disqualified for that service in the
Church which his Divine Master designed for him.

In the Twelfth month, 1811, he was married to Deborah,
daughter of Aaron and Abigail Musgrave.
This union did not long continue--his beloved
wife being removed by death in the Sixth month, 1815.

He had very clear openings into the character and qualifications of a minister of
the Gospel several years before he was called to the service himself.
They produced the conviction that all who are rightly placed
in that important office are made ministers by Christ,
and that which they preach should be from the
direct openings and communications of his Spirit.
"`These things,`" he says, "`I was favored to see in the light of the Lord Jesus,
and at times I felt as if I could stand forth as a servant under his authority,
to proclaim the glad tidings of life and salvation, and gather souls in the Gospel net.`"
Again he writes,
"`Neither the most extensively gifted nor those of the largest experience,
have anything of their own to communicate which can really profit the people.
All must reverently wait upon Him, without whom they can do nothing,
and it is only as He opens the spring and causes it to flow afresh, that any,
the least or the greatest,
are authorized and qualified to attempt to minister to others.`"

With these convictions of the solemnity and importance of the work he was called into,
and prepared for by submission to the humbling power of Truth,
he first appeared in the ministry when accompanying his mother and
another female minister on a religious visit to New England,
in the year 1817, in a sitting in a family where they made their home.
His belief of his call to this weighty service was renewed and
much strengthened by the public testimony of a beloved friend,
when not long after he was brought under exercise at his own meeting,
and on which occasion he yielded to the Divine requiring.

In the year 1820 he was attacked with yellow fever,
and such was the violence of the disease that
there appeared little prospect of his recovery.
"`For several days during this sickness,`" he remarks,
"`the beams of the Sun of righteousness were entirely withdrawn,
and the sentence of death seemed to have gone forth.
All my former experiences were perfectly obliterated,
and there appeared nothing left upon which I could ground my hope of happiness.`"
After some time his confidence in Divine mercy was gradually
restored--some passages of Scripture were opened,
and the views he was again favored with of the humility and purity
indispensably necessary for a minister and servant of Christ,
raised the belief that the Divine hand was still at work.

The language that perhaps
"`this sickness was not unto death, but for the glory of God,`"
raised a further hope that he was not cast off,
but that the Lord would again have mercy,
and that it would prove the means of preparing
him more acceptably to come up in his service.

He was acknowledged as a minister in the Second month, 1822;
and being preserved in a humble, watchful state of mind,
depending upon Him who had conferred the gift,
he was enlarged in divine knowledge and utterance.
Being careful to wait for the fresh putting forth of the Good Shepherd,
his words were accompanied with life and power,
rendering his ministry remarkably baptizing and edifying.
He was often led to dwell in his public communications upon the importance
of attention to the guidance and teachings of the Holy Spirit,
exhorting his hearers, with much fervency,
to yield obedience to the Divine will manifested in the secret of the heart,
and showing with clearness that the pathway to peace and
happiness was through the operation of the Cross of Christ.
His appearances in prayer, though not frequent in our religious meetings,
were very weighty and impressive,
and when so engaged he evinced much brokenness of spirit,
manifesting his sense of the awfulness of that solemn engagement.

His first religious visit with a minute,
was to attend the Yearly Meeting held in Baltimore, in the year 1823.
From that time to 1854 he was frequently engaged, with the unity of this Meeting,
in religious service.
During that period he visited all the meetings of Friends in our own Yearly Meeting, and,
with few exceptions, those constituting the other Yearly Meetings in this country,
and some of them several times.
In returning the minutes granted, on the completion of these visits,
he frequently acknowledged with much feeling,
that in the prosecution of them he had mercifully experienced, from season to season,
Divine help,
qualifying him to perform the services to the relief and solid peace of his own mind.
Being much redeemed from the love of the world,
he was enabled to keep temporal things in their proper place,
relying on the faithfulness of Him who had given him in early
life the assurance he should not lack food and raiment.
Although engaged in a business that depended for its success
more than some others on close personal attention,
yet he freely left it when called to go forth in his Master`'s service.

He felt a lively interest in the guarded religious education of the youth of our Society,
and his services in promoting this important concern were very valuable and
highly appreciated by those associated with him in the management of schools.

He was a practical believer in the necessity of waiting
for and relying upon the openings of Truth,
to qualify for right decisions in the Church; and being endued with a sound,
discriminating judgment,
he was much occupied and very useful in attending to the affairs of the Society,
and he filled for a considerable time several important stations.
In reference to the necessity of silent waiting as a qualification for religious service,
he writes: "`There are many lessons to be learned in silence as well as in speaking;
and to be brought into a state of childlike docility
and obedience to the leadings of our heavenly Shepherd,
seems to be the principal end of all the dispensations of his wisdom.
The haughtiness of man must be laid low,
and the Lord alone exalted in that heart which is
prepared to be acceptably engaged in his service.

In a state of deep humility and patient waiting upon Him,
we become prepared to discern the motions of his Spirit,
and in simplicity to yield compliance therewith.
There is as much need to learn to be still and to know the active,
forward disposition of the human mind reduced to subjection,
as there is to experience a willingness wrought
to perform the Lord`'s will when it is manifested.
He is a wise Master Builder, and if we abide under his preparing hand,
He will fashion us into vessels and instruments for his use.`"

Being grounded by heartfelt conviction in a belief of the
authenticity and divine authority of the Holy Scriptures,
the divinity of Christ,
and the efficacy of his propitiatory offering for the sins of the whole world,
he was brought under much concern and exercise,
in consequence of the attempts to invalidate these all-important truths,
and he believed it to be his duty to stand firm in the support of them.
In common with many faithful Friends,
at a later period he was introduced into much sorrow and anxiety,
at the unsettlement manifested by many in profession with the Society,
and viewed with great concern the efforts which the adversary of all
good was insidiously making to introduce new views and practices,
and draw away the members from a consistent
support of our ancient doctrines and testimonies.
He was frequently engaged under deep religious feeling to point out
the consequences which must result from such departures;
and earnest were his exhortations to his fellow-members to uphold the standard of
Truth to which our early Friends were instrumental in gathering so many,
illustrating by their holy lives and peaceful deaths,
that they had not followed cunningly devised fables.

In the Twelfth month, 1824, he was married to Elizabeth Barton,
who was at that time and until the close of her life,
a highly esteemed minister in our Society.
She was a true help meet to him,
and tenderly sympathized with him in his exercises and trials,
strengthened and encouraged him in the performance of his varied duties,
and shared with him in godly concern and care for the
preservation and true welfare of their children.
In the Eleventh month, 1861, his beloved and valuable wife was suddenly removed by death.
This solemn event plunged him into deep affliction,
but an undoubted evidence was mercifully given him soon after his bereavement,
that her redeemed spirit was partaking of the joys of God`'s salvation; which, he writes,
"`raised thanksgiving to the Lord my God, who had been with me all my life long,
fed me and kept me unto this day,
in the hope that He would still condescend to be with me,
sustain my head above the billows, and keep me in the hollow of his Omnipotent Hand,
so that I may be enabled to fill up the measure
of suffering and duty that He may still allot,
and know all my sins to be forgiven,
and my garments washed and made white in the blood of the Lamb,
and be accepted at the last by my gracious Redeemer.`"

The shock given to his nervous system by this sudden and unexpected event,
was great and irreparable.
His sight failed rapidly,
and it was not long before he was unable to see to read or to write.
To one whose mind had always been active,
and who had accustomed himself to employ much time in the use of the pen,
or in the perusal of works congenial with the tone of his thoughts and feelings,
this was a privation keenly felt.
But as he was thus cut off from some outward sources of mental enjoyment,
his attention was more and more withdrawn from external things,
and in reverent retirement centered on the inward manifestations of the Holy Spirit.
In this deep introversion he was often brought
into low places and close searching of heart;
producing very humiliating views of himself, of his attainments in the way of holiness,
and of his faithfulness in occupying the gifts,
and making a right return for the manifold mercies bestowed upon him.
Not, as he said, that he found anything laid to his charge,
or that there was any known duty which he had refused to perform;
but such was his sense of the frailty of human nature, and the awfulness of the soul,
when unclothed of mortality,
being ushered into the immediate presence of infinite and immaculate Purity,
that he felt there could be no hope for him, nor for any,
but as in immeasurable condescension,
an undoubted assurance was granted of acceptance
through that Savior who died for poor lost man,
and whose mercy covers the judgment seat.

Although much restricted by lack of sight,
and the continued though gradual decline of strength, from going far from home,
he frequently attended different meetings in the city,
and occasionally visited one or more in the country, at no great distance.
It was always a source of satisfaction to him thus to mingle with his friends,
to unite with them in waiting on the Lord,
and in seeking for ability to render to Him acceptable worship in spirit and in truth.
He was preserved in watchfulness over himself,
and under an abiding concern that in his declining years he might do nothing
that would bring a shade over the blessed cause he had so long espoused.
His ministry, though not frequent, continued to be lively and weighty;
sometimes inviting the young to take the yoke of Christ upon them,
so that they might secure the proper enjoyment of the things of this world,
and a well grounded hope of admittance into the company of saints and angels hereafter;
and calling on his fellow-members not to rest satisfied
with anything short of complete sanctification;
that, being grafted into Christ, the living Vine,
they might be made fruit-bearing branches, and through the renewings of the Holy Ghost,
bring forth much fruit, to the glory of God the Father.

In the Sowings of gospel love toward his fellow-men,
and especially toward those of the same household of faith,
he often expressed his fervent desire for their
establishment and growth in the unchangeable Truth;
on several occasions remarking he felt that if he had but bodily ability,
and it was his Master`'s will, he could cheerfully go forth once more through the Society,
to preach the glad tidings of salvation.

As disease took stronger hold of his system, his breathing became much affected,
and in the winter of 1866-67,
he was unable for many days together to bear a recumbent position,
so that it was difficult for him to obtain refreshing sleep,
or to procure rest for his weary frame.
His suffering, which was often great, was borne without complaint or murmur,
often remarking that though he found the infirmities of
the flesh as much as he could well endure,
they were doubtless permitted in Divine wisdom,
and were intended for his further refinement.

During his long confinement he continued to maintain a
lively interest in the welfare of our religious Society,
manifesting on different occasions the earnest travail of his soul that
Friends might be drawn more nearly together in the love of the gospel,
and be willing faithfully to support the doctrines and testimonies,
which he believed the great Head of the Church had
raised up the Society to exemplify to the world.
He was frequently visited by many of his beloved fellow-members, ministers and others,
and many precious opportunities were thus afforded for retirement before the Lord,
and not unfrequently he was clothed with ability to minister to those present,
as were others to speak in the language of comfort and encouragement to him.
On more than one occasion he expressed his earnest desire that
nothing might be said by any by way of commendation,
nor, unless they felt divinely authorized, speak as though his salvation was secured,
for he felt that the watch and the warfare must be continued to the end,
if the crown immortal was through mercy obtained.
Notwithstanding these humble views of himself,
and the care manifested not to presume on any past experiences,
he on more than one occasion intimated that his gracious Master had given him an
assurance that when done with time he would be admitted into everlasting rest.

During the time of holding the Yearly Meeting in the Fourth month, 1867,
he was frequently brought under much exercise.
The separation from his friends when thus gathered to transact the affairs of the Church,
a work which had long been dear and deeply interesting to him, was keenly felt;
but was borne with patience and resignation.
At different times his spirit was bowed in sympathy with his brethren,
earnestly desiring that the various important subjects before
the meeting might be resulted under the authority of Truth,
and rejoicing when he heard of seasons of Divine favor being granted to the assembly.

The gradual aggravation of the symptoms of his disease continued,
there being increased feebleness of the circulation and
almost constant difficulty of breathing.
During the last few days of his life, he conversed very little,
not only because the oppression made it difficult for him to speak,
but his mind appeared to be fixed in the contemplation of the change that awaited him,
and in being fervently engaged to be found ready when the summons came.

His decease took place on the morning of the Twelfth of Fifth month, 1867;
his redeemed spirit gently and peacefully leaving its suffering tenement of clay.

[quote.scripture]
____
"`Blessed are the dead which die in the Lord from henceforth; yes, says the Spirit,
that they may rest from their labors, and their works do follow them.`"
____
