== Chapter I

[.chapter-synopsis]
* 1787--1813. Introduction
* Parentage and birth
* School days
* Apprenticeship
* Divine visitation
* Religious exercises
* Notices of eminent ministers
* Views of the Church
* Excursions from the city
* Experience respecting true Faith
* Enters into business
* Scruples respecting extensive trade
* Divine promise of a Sufficiency
* Marriage
* Reflections on visits to Watering Places
* Visit from Susanna Horne and T. Scattergood
* War with Great Britain
* Accompanies his Mother to Salem Quarterly Meeting.

For the purpose of commemorating the mercy and
goodness of God extended to me from early life,
and to encourage others to yield to the visitations and convictions of his Holy Spirit,
that through obedience thereto the kingdom of
our Lord Jesus Christ may spread and prevail,
I have believed it right from time to time,
to preserve memorandums of his dealings with me,
and to leave them as a testimony to his unfailing goodness and
faithfulness to the children of men who love,
serve, honor and put their trust in Him alone.
And especially that my dear children, should they survive me,
may be drawn more and more to dedicate themselves to the God of their fathers,
and walking in the Truth all the days of their lives,
become instrumental in the divine hand,
in holding up to others the purity and spirituality of the religion of the Lord Jesus,
as He, by his Holy Spirit, revealed it to the holy Apostles,
and to those whom He made ministers and promulgators of
it at the rise of our religious Society.
I believe that George Fox, Robert Barclay, Isaac Penington, William Penn,
George Whitehead, and many others, were divinely prepared and anointed by Christ Jesus,
the minister of the sanctuary and true tabernacle which God has pitched and not man,
for reviving and effectually preaching the same gospel of life and salvation,
in its original purity and clearness,
which had been much lost sight of through a long night of apostacy.
And though the spirit of antichrist, and some,
who are more or less darkened and deluded by it,
may seek to obscure the spiritual nature of the gospel,
as professed from the beginning by Friends,
yet a blast will be brought over all such attempts in the Lord`'s time,
and He will raise up from generation to generation,
living witnesses of the power and coming of the Lord Jesus in
his spiritual appearance in the souls of his children--who,
as they are faithful in the day of small things to the unfoldings of his Spirit,
will be qualified in living faith to call Jesus, Lord and Savior,
both from what they have experienced of his redeeming power in their hearts,
and from a true and certain belief of all the doctrines and
precepts of the gospel as recorded in the Holy Scriptures.

My beloved and honored parents, Jonathan and Hannah Evans,
were true believers in these doctrines,
and their lives and conversation were consistent therewith.
Walking in the simplicity and uprightness which the Truth leads into,
they became bright examples in the church of Christ, and growing from stature to stature,
were made pillars in the Lord`'s house, that went no more out.

I was born in Philadelphia, on the 5th of the Tenth month, 1787,
and at a suitable age was placed at a school under the care of
a member of the Monthly Meeting to which I belonged.
I soon contracted a strong fondness for liberty
and play in the streets with my school-fellows,
with some of whom as I grew in years, I was at times involved in childish disputes,
more excited by rude boys, who delighted to urge a Quaker child into broils,
than from any fondness myself for such collision--though I
felt a strong disinclination to submit to imposition.

I underwent much persecution in the street on account of a plain dress,
an aversion to which increased with age.
My mother watched over us with affectionate and religious solicitude,
taking suitable opportunities to induce serious reflection,
telling us that our Heavenly Father saw us wherever we were and knew
all that we did--that He was displeased when we did wrong,
and that there was a place of everlasting punishment if
we died in sin--but on the contrary,
He would continue to love us if we did right,
and receive us into heaven if we thus lived and died in his favor.
But she did not adopt the modern system,
relying entirely upon reasoning with the children to convince their understanding,
but at times resorted to correction to support
authority and procure submission to her dictates.

Keeping to the truth and strict integrity were early inculcated and enforced,
any departure from which brought distress over me.

Disinclination to restraint increased with years,
and condemnation for sin rendered serious things and
the society of religious people irksome to me.
I sought the company of those whose passions and propensities were unsubjected,
and took more satisfaction in their conversation than
in the sobriety and reserve of the lovers of the cross.
By such means corruption strengthened, the innocency of childhood was tarnished,
and my carnal appetites began to seek indulgences
totally at variance with purity of heart,
and that life which my parents earnestly labored to inculcate and keep their children in.

In the year 1798,
one of my brothers and myself were sent to the country for the school vacation,
to board with Philip and Hannah Price, in Kingsessing township,
where we remained till the yellow fever appeared in the city.
Their son`'s family moving out there, we were taken to Darby and placed at school.

This was a sorrowful change to us--among strangers and
in a family which seemed to have little interest in us.
We felt keenly the separation from our parents,
and those Friends in whose house we had enjoyed ourselves,
and to whom we had become much attached, particularly Hannah Price,
who had been very kind and attentive to us.
Those feelings of sadness eventually subsided in a measure,
and some persons coming into the family not very proper for us to associate with,
I sought for gratification in their society,
which was far from contributing to my benefit,
and thereby the way was opened to temptation and increased insensibility.
Being from under the care of my parents, who did not leave the city for several weeks,
and released from the restraint which their example and presence often inspired,
I indulged in light and loose conversation, for which I was brought under condemnation,
and would have been ashamed they should have been apprised of.

It was a time of awful calamity in Philadelphia; many fled to the country,
which made it difficult to procure accommodations,
and as soon as it could be effected our family removed from the city into Upper Darby,
where several of them were taken sick with the fever.
This kept my brother and myself away from them longer than they desired.
It is, however, very important to place children, when sent from home,
with religious caretakers, who feel the obligation to watch over their morals,
and to guard them from the contaminating influence of
depraved domestics or persons hired as laborers,
who have had little care bestowed upon their bringing up,
and are not under the government of religious principles.
We did not return to the city until late in the fall, after frost and snow;
the malignancy of the fever rendering it unsafe for
those who had been inhaling a pure atmosphere,
to return before a thorough change had been effected by frost.

In the Fifth month, 1799, the boarding school at West-town,
instituted by our Yearly Meeting, was opened for the reception of scholars,
and I was one of the first twenty admitted there,
my brother Joseph also remaining a few months.
It was quite a novel scene,
and required time before a proper system of order and government was established.
Everything seemed in a crude state; the yards not laid out and regulated,
shavings and chips from the hewed timber and the shingles,
the woods grown up very thick with bushes, so that it was difficult to get through them,
all contributed to give the whole a rude appearance.
All this made work and amusement for the boys,
who employed themselves under the supervision of the
teachers in burning up the great beds of shavings,
cutting openings for walks through the woods,
and making arbors with seats to recreate themselves in during the warm weather.

The school was frequently visited by the committee of the
Yearly Meeting who had the charge of the institution,
and by ministers traveling through the country.
Under their ministry and sometimes in the silent meetings,
my mind was brought to contemplate the character of the
holy men of old who served God in their generation,
and sincere desires were sometimes felt that I might become like them.
I was full of activity in the amusements and recreations which we were allowed,
keeping pace with most of my schoolmates in the studies
pursued at that early period of the school,
and was quite contented, while some indulged a fault-finding disposition.
Sometimes I took liberties with others in going beyond our prescribed bounds,
but was restrained from any very flagrant violations of order,
or joining the worst boys in bad language,
or a systematic defiance of the authority of the teachers.
On one provocation I used a bad expression resembling swearing,
which struck me with horror.

Our anxious parents frequently wrote us letters containing excellent advice,
showing their religious concern for our welfare; of which the following are extracts:
From my mother, dated Fifth month, 21, 1799:

[.embedded-content-document.letter]
--

I hope my dear children you do not forget our anxious concern
and solicitude for your good when present with us,
and I trust it has not abated,
but desires are raised that the Lord may be pleased to
take you under his peculiar care and notice,
and that you may indeed be afraid to offend Him in word or action.
Be obedient to those who have the care over you, and kindly affectionate one to another.
Endeavor after stillness, and remember the many favors you receive;
and may the reverent inquiry of your minds be,
What shall I render unto the Lord for all his blessings?
Your dear father set off this morning with Ruth A. Rutter and Sarah Cresson to Rhode Island,
and as he had not time to write, desired his love to be remembered to you,
and that you would let us hear from you as often as you can.

With desires for your preservation in the
innocency and simplicity of the Truth I conclude.

[.signed-section-closing]
Your affectionate mother,

[.signed-section-signature]
Hannah Evans.

--

After my beloved father`'s return from his journey with E. A. Rutter and S. Cresson,
he wrote us frequently--from one of his letters the following is taken:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Philadelphia, 19th of Second month, 1800.

[.salutation]
My Dear Children,

I have been much concerned on your account for some time past,
understanding several of the boys had given a great
deal of trouble to those who had the care of them;
and though I could scarcely think either of you were of the number,
yet not hearing anything particular, my mind was made very uneasy,
but I hope better things of you.
And if at any time you feel any disquietude of mind,
be patient and endeavor to bear your trials in meekness,
looking with reverent confidence to your great Creator,
who compassionately regards every sigh and tear of the sincere in heart;
whether they be children or more advanced in years.
But then we must also at all times strive to conduct so
as not to grieve the Holy Spirit in our hearts,
which is a continual witness against every evil thought, word or action.
Let your innocent, circumspect deportment be observed by all;
join not with any in the least evil,
but let the fear of the Lord be ever present with you, and that will keep you harmless,
and make you dear unto him and to all good people.

Your mother joins me in near love to you both, desiring your welfare every way.

[.signed-section-closing]
Your loving father,

[.signed-section-signature]
Jonathan Evans.

--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Philadelphia, 21st of Ninth month, 1800.

[.salutation]
Dear Children,

Feeling desirous at all times you may do well,
I cannot but endeavor to revive in your remembrance the
necessity of attending with all diligence,
to the small,
gentle intimations and reproofs of the Holy Spirit of Truth in your own minds.
Keep near to its blessed instructions at all times,
and it will preserve in every season of trial and difficulty,
and as an inexhaustible fountain,
sustain your little minds when depressed with anxious thoughts or discouraging fears.
This is the alone way to happiness here or blessedness hereafter.
For in obedience to this light in our minds,
we are brought to love the Lord our most gracious Redeemer above all,
and by Him are regarded as his children, which is treasure indeed,
that raises the spirit above earthly pleasures,
to a sense of the unspeakable comforts in the regions of immortal bliss.
Here, in this state the fear of death is taken away,
because we know that in the presence of the Lord there is life,
and as we are kept near him, nothing can hurt us.
Now, my dear children, let me earnestly entreat you,
to mind the reproofs which you feel for doing wrong;
this is the Spirit of Truth I have been speaking of, and as you carefully attend to it,
it will lead into all truth--you will fear to offend by a repetition of those things,
for which you have been reproved.
It penetrates through every covering,
and no dissimulation can possibly escape its all-searching power.
Whenever through unwatchfulness you have given way to temptation,
and by the merciful calls of this holy teacher, you become sensible of it, retire alone,
and endeavor to get your minds drawn from every outward thing,
to a reverential waiting upon your Holy Creator
for a renewal of his light and grace upon you,
that you may be strengthened to resist the enemy of all good in his future attempts;
and be sure to avoid those things that have thus beguiled you,
and brought distress upon the tender mind;
for in this watchful state your minds will often be tendered,
and at times sincere petitions will ascend for preservation,
and support in this world of vanity and trouble.

[.signed-section-closing]
Your affectionate father,

[.signed-section-signature]
Jonathan Evans.

--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Philadelphia, Fifth month 6th, 1801.

[.salutation]
Dear Child,

I received your letter dated 4th inst.,
and was glad to hear of yourself and sister being in health,
which is a blessing among the many received, we ought to be thankful for.

Indeed, many are the obligations we are under to that
bountiful hand from which all our blessings flow.
Let us then evince our gratitude by endeavoring to love Him above all,
and then we shall be afraid to offend Him in thought, word or deed.
My dear child, I feel anxious for your preservation,
and desire you may be careful to associate with such of your school-mates,
as are most seriously inclined; and be sure not to do anything,
in the absence of those who have the care over you,
that you would be afraid they should know,
or that would in any degree wound your own mind.
Learn to love silence; and seek for strength,
that you may be preserved in time of temptation.

With love to yourself and sister, conclude your affectionate mother,

[.signed-section-signature]
Hannah Evans.

--

My brother had been taken from the school at this time on account of his health,
and one of my sisters introduced there--The above letter,
expressive of the best wishes of an anxious and affectionate mother, was addressed to me,
but at that time I was too full of my own plans for recreation and enjoyment,
to give that heed to such solicitude for a wild son, as I ought to have done,
yet I have no doubt these admonitions had a restraining influence,
and at times tended to bring me to some serious reflection.

In the Second month of 1802, being then a little over fourteen years of age,
I was removed from the school, having been there about two years and nine months,
and being rather young to be placed an apprentice,
my father got me into the counting-house of two Friends, in the flour business,
in order to acquire some knowledge of book-keeping.
Their store was on the wharf, and when there was nothing urgent in the business,
my inclination led me into the company of persons in the neighborhood
whose sentiments and habits were not congenial with a religious life;
and thus had it not been for the mercy of my Heavenly Father,
I was in great danger of entering rapidly the broad way to destruction.
The yellow fever again appeared in the city this summer,
and after leaving the store on that account, I did not return to it,
but in the fall of the year 1802, was apprenticed to a Friend to learn the drug business.
Being introduced to a strange family and business, I endured new difficulties.
It was the business of my choice, but after the novelty had in measure subsided,
I began to question whether I had made a proper selection,
and for a while felt unsettled; but reflecting that it was done after some deliberation,
and that if I left it for any other, I might find the same difficulty to contend with,
I concluded to endeavor to make myself satisfied,
hoping that I should find it as suitable as any other I could adopt,
and accordingly applied myself to the business and the interests of my master,
as well as I was capable.

In my new situation I had many temptations to war with from within and without.
The business of a store that was much frequented,
subjected me to interaction with those who knew
little or nothing of the work of religion,
and a volatile, active spirit often led me from under the cross into converse with such,
by which I suffered loss.
I was much separated from the care of anxious and exercised parents,
and though I was afraid of close intimacy with
young persons who were of a libertine class,
yet more or less I was drawn into the company of two of them residing near the store,
but their wicked habits and conversation created a dread in me
of being joined to and carried into their depraved practices.
One fine winter evening, my master`'s sleigh and horses having been out,
he told the apprentices we might take a ride,
and accordingly with one of these young men, we set off,
and rode out a few miles to the bank of the Schuylkill,
where this young man proposed we should go into a tavern and get something to drink.
This was a new proposition to me,
upon which I hesitated--having never been accustomed to go to taverns,
or drink anything like ardent spirits.
We got out of the sleigh, but I did not move from the side of it, and while hesitating,
the countenance of my father presented to my view,
as though he had suddenly appeared before me,
which immediately conveyed the idea of disapprobation,
and I gave my voice against going into the tavern,
and we accordingly resumed our seats and rode home.
This was an evidence of the watchful care of the unslumbering Shepherd of the sheep,
in bringing to my mind the conviction,
that were my father present I would not dare to go into such a place,
and further shows the importance of the circumspect
deportment of parents before their children,
and of the application of salutary restraint towards them.

Notwithstanding I had been thus far carefully educated and watched over by my parents,
attended steadily the meetings for worship to which I belonged,
and had been taught in the principles of the Christian
religion as set forth in the New Testament,
and in the writings and journals of Friends;
believing that Jesus Christ was the Savior of the world, that He died for all mankind,
and would save all who were obedient to Him: that my Heavenly Father who is almighty,
saw me wherever I was and every thought and every action that I did,
and by his Holy Spirit in the heart convicted me for sin,
bringing me under the fear of death and everlasting torment,
but gave peace whenever I resisted temptation and did right;
yet so far as I can remember, I had never yet had a full sense of my lost condition,
and the necessity of an entire change of heart,
in order that I might be brought into his favor,
and sanctified so as to be fitted for spiritual communion with Him.
My father frequently read the Bible to us, as well as other religious books,
particularly on First-day.
One evening when collected for that purpose,
I read to the family William Leddra`'s epistle, written the day before he was executed.
It had a very powerful effect on me, tendering my heart in an unusual degree,
and bringing me to trembling;
under which I was favored with an extraordinary visitation of heavenly love,
producing a sense of my sinful, impure condition,
and fervent desires after holiness--that I might become changed,
and hereafter live a life of acceptance with my Heavenly Father.
I had never had the same view of myself,
nor felt the same willingness and desire to dedicate myself to Him as at that time.
The savor of it continued many days.
The light of Christ shone clearly into my heart,
showing me that many of my habits were contrary to the Divine purity
and must be abandoned--that many of my words were light and unsavory,
and a guard must be placed at the door of my lips.
Love flowed in my heart towards my gracious Almighty Parent preeminently,
and then towards all men as brethren and creatures of the same all-powerful hand.
I desired above all things to be with Jesus, and to know Him to continue with me,
and at that time it seemed as if He did condescend to manifest himself in a clear manner,
so that his countenance was lovely,
and I walked under his guidance and protection with great delight.
It was the baptism unto repentance, the day of my espousals--the beginning of a new life;
and while favored with these heavenly feelings,
I thought nothing would be too hard to part with in obedience to the will of my Savior.

From this time I began to love retirement and serious meditation,
and to present myself in the presence of the Lord to partake of his favor,
and know my strength from time to time renewed.
I felt more than ever bound to be faithful to my master in all things,
both in the performance of the duties of the station,
and in taking care of his property and the interests of the business;
appropriating nothing to my own use that did not belong to me.
To do justly and faithfully in all things as in the Divine sight,
was one of the earliest requisitions.
If I accidentally broke anything of value, I was not easy to conceal it from him,
though sometimes it was a trial to tell him of it,
but when I did inform him under feelings of regret,
it seemed to disarm him from blaming me.

The heavenly visitation which I have described
was like the baptism of love unto repentance,
in which I felt confident, like Peter, of adhering closely to the Master,
though others might forsake Him.
He knew when it was proper to withdraw those sensible manifestations of his
presence and support under which I was forming such conclusions,
and when the dispensation was changed,
and no comeliness could be seen in Him or in myself,
I soon found that my constancy would be easily shaken.

There was a wilderness travel to pass through,
in which I was to feel the strength of my evil propensities,
and the subtlety and power of Satan as I never yet had witnessed.
The change was hard to endure,
and though I strove for a time to maintain the ground I had taken,
yet being assailed again and again with temptation,
and looking at it instead of looking towards Him, who alone could preserve me,
I let go my faith in his unfailing regard,
concluded I might as well gratify myself this once, and when I had yielded,
distress came upon me.
Having cast away my shield, I felt like a poor fallen creature,
unworthy of Divine notice, and not likely to be again favored with it.

Shut up in darkness the tempter vaunted over me,
and suggested that it was not worth while for me to attempt to walk in the narrow way,
that I would not be able to resist and control my passions and inclinations,
and therefore might as well continue to indulge them.

To be thus overcome at the commencement of the warfare,
and so soon deprived of those heavenly sensations which I had enjoyed
in the presence and company of the Deliverer of the captive soul,
filled me with sadness, and I went mourning on my way.
Divine displeasure was administered, but in the midst of judgment,
the Lord remembered mercy, and through the operation of his blessed Spirit,
brought me again into tenderness of heart,
and I was humbled under a sense of my unworthiness of his
condescension and love towards such a poor rebellious creature.

I was educated in the belief that divine worship was performed in spirit and in truth,
and that the qualification for this essential duty was
to be waited for in the silence of all flesh.
When in meeting I endeavored to have my mind gathered from all visible things,
and at times was favored with the presence of the Shepherd and Bishop of souls,
who is in the midst of those who are met together in his name,
sometimes tendering my spirit with his goodness,
and at others instructing me in those things which pertain to salvation;
and I felt it to be a religious duty diligently to attend all
the meetings to which I belonged as they came in course.

My father`'s house was visited by many of the most substantial Friends,
of whose company I was glad,
and was interested and instructed by their solid conversation,
and sometimes by religious opportunities in the family.
Thomas Scattergood, whose first wife was a sister of my mother, frequently visited us,
and having a peculiar gift for entering into the condition of others,
he mostly had a word of counsel or encouragement to the children.

Having never been accustomed to keep much company,
and believing that a retired life was best for me, I contracted very little intimacy,
excepting with one or two persons of a serious character.
Our business required attention until 10 o`'clock in the evening,
and when it was my turn to be at the store at night, if the business admitted of it,
I passed the time in meditation, and reading religious, historical or scientific works.
I had frequent conversation on points of doctrine with an orderly young man, a methodist,
apprenticed in the neighborhood to the same business,
and a few times accompanied him to their meeting,
out of curiosity to observe their mode of worship;
but I never saw anything among them that attracted me,
or produced any dissatisfaction with my own religious profession.

On the contrary, in some of their prayer meetings,
the passions appeared to be much excited,
and their efforts to convert persons from their evil ways,
that they might "`get religion,`" as they call it,
seemed to operate much through the nervous system.

Familiar association with other professors, or attending their meetings,
appears to me quite improper for the members of our Society.
Those whose feelings are lively may be caught by the excitement,
and receive a bias which may unsettle them a long time, perhaps through life.
If we keep to our divine Lord and Master,
He will instruct us in the mysteries of his kingdom,
and nourish with the bread and water of life which He gives,
by which the inner man will be strengthened,
and the soul made wiser than all teachers who are acting in their own spirit.
"`He that drinks of this water shall thirst again,
but he that drinks of the water that I shall give him,`" said Christ,
"`shall never thirst,
but it shall be in him a well of water springing up unto everlasting life.`"

I had now put my hand to the plough,
and hoped never to look back again into the condition I was once in;
but a long fight of affliction was passed through,
before I was in any good degree brought from under the bonds of corruption.
Refraining from company,
tended to keep me out of the way of the gross evils which abound in populous cities,
yet for lack of watchfulness and close obedience to the will of my Heavenly Father,
I was often overcome by temptation, which brought great distress upon me.
In my trouble I looked towards Him whom I had offended,
and in mercy He would bring me up out of the pit
and put a new song of thanksgiving into my heart.
These seasons of rejoicing were succeeded by feelings of great strippedness,
and instead of keeping the faith and patiently waiting for the appearance of my Lord,
I was too easily drawn aside again by a light and frothy spirit,
and received fresh wounds from my enemy.
He seemed to rejoice over me, and suggested that it was impossible for me to overcome,
which I was sometimes ready to fear would be the case; yet through all my combats,
the power of darkness over me, and the strength of my propensities to evil,
gradually diminished.
I frequently walked into solitary places,
either for the purpose of meditation or to bemoan my condition,
and one dark night in the skirts of the city,
where no sound was heard but the howling of some dogs,
I thought the state of my mind bore a strong resemblance to the
darkness of the night and the doleful noise of those creatures.

When I was thus plunged, and endeavored to bear it patiently and steadfastly,
He whose tender mercies are over all his works,
again appeared in the needful time with healing in his wings,
and then I rejoiced in his judgments as well as his mercies,
and would be thankful that I had endured instead of seeking relief in a wrong way.

At one time when I was passing through much mental conflict,
an impression was distinctly made upon my mind that at a
certain period I should be favored with a renewed visitation.

It was a season of great trial to Friends of this city,
in which I partook very keenly according to my capacity;
and when it had in some measure passed over,
a divine visitation was extended to me of the
most remarkable character I had yet experienced;
in which I saw in the openings of divine light,
the power of darkness from which all temptation proceeded,
and was also favored to see the power of divine Grace which was over all,
and as it is obeyed,
would effectually give the victory over all sin to
those who unreservedly give themselves up to it.
I never had before such a clear and undoubted sense of the two powers of light and life,
and of death and darkness,
and my faith was strong and unshaken in the unlimited
superiority of the former over the latter.
But instead of hiding it in my own heart and
quietly dwelling under its heavenly operation,
I spoke of it too freely to my religious companions,
desirous that they should see it as clearly as I did, and thereby talked it much away,
and failed to partake of the full benefit of the
divine visitation as I ought to have done.

During my apprenticeship there was a large body of substantial ministers and
elders of extraordinary gifts belonging to our Yearly Meeting;
and as I made progress, though slowly and often in a halting way,
in religious experience, my concern strengthened to attend meetings for discipline,
as well as for worship.

Those large annual assemblies, where there was such a concentration of gifts,
talents and religious weight, were very interesting,
especially when a concern for the welfare and
encouragement of the young members took hold of them.
George Dillwyn, who reminded me of the beloved disciple that leaned on Jesus`' bosom,
rarely forgot those who were in difficulty and needed help,
and he was at times very instructive in his application
of doctrine to the different states and growths,
and very cheering to the youthful disciple.
The gravity with which they sat in those assemblies,
and the solemnity with which many of them delivered
their sentiments were impressive on young minds,
and tended to inspire a love for the religion which produced such men, and such fruits,
and for the beauty and dignity of the church and its concerns.
Eli Yarnall was remarkable for the inwardness of his spirit,
his great caution in speaking, and the peculiar brightness of his countenance,
reminding me of Stephen, of whom, it is said, that all who beheld him,
"`saw his face as it had been the face of an angel.`"

Our Quarterly Meeting was held in the North house, in Key`'s alley.
A large number of ministers belonged to it;
and during my minority Ann Alexander paid a religious visit to this country,
whose Gospel labors were evidently from a living spring.
At one of these meetings she foretold in a very
impressive manner the reduction of the ministers,
and the scarcity of spiritual food instrumentally communicated.
I concluded then to treasure up the prediction for the purpose
of ascertaining what dependence could be placed upon it--and
it has since been fully and strikingly realized.
A number in that station were in a few years removed by death, others have fallen away,
several joined with the separation which took place in 1827,
and very few in our Quarterly Meeting have since been raised up.

William Savery,
a minister much beloved and very decided in his public testimony to the divinity,
and the various offices of our Lord Jesus Christ, died during my apprenticeship.
I attended the Market street Meeting on the evening of
the 25th of the Twelfth month when he preached,
appearing to be in a declining state of health,
and which I believe was the last time he appeared in the ministry in a public meeting.
What made the opportunity more impressive was his pallid countenance,
and the text with which he rose,
"`Abraham saw my day and was glad,`" and which he
uttered with a heavenly spirit and solemn tone of voice.
This was the subject of all others which lay near his heart--and he was an
indefatigable advocate for the truths and the importance of Christianity,
Rebecca Jones, a minister and mother in Israel,
who had paid a religious visit to Friends in England,
and was highly esteemed by her contemporaries, for religious experience,
a sound judgment and spiritual discernment, resided in this city,
and her house was frequented by ministers and elders,
and the younger members coming under the love of the Truth,
who sought the benefit of her counsel and instructive conversation.
Her circumstances were limited--at one time she kept a school for small children--
and sold some books and articles of dress worn by females of plain habit.
Among others who visited her compact habitation in Brooke`'s court,
I was one who found the way there, after being brought under religious concern.
She treated her young friends in a kind and affable manner,
and yet with Christian dignity and gravity;
sometimes entertaining them with anecdotes of her early religious life, or her travels,
particularly in Europe,
having in view the object of drawing them into a love for the Truth,
or strengthening their desires and resolutions to persevere in
the good way in which they had commenced walking.
She told me that when quite a young woman,
after the power of Truth had taken hold of her heart,
and brought her to seek for those things which belong
to the everlasting welfare of the immortal soul,
she was introduced to the house of Daniel Stanton,
then one of the principal ministers in this city.
It was a place of resort for the young converts of that time,
and deriving much help from the society of that valuable man,
she then concluded if she ever became a housekeeper,
her house should be open to the visits of persons seeking after heavenly treasure.
Her conclusions were realized to the comfort of many.
In a little religious communication one evening to a young Friend and myself,
she gave us the excellent advice, which had been given to her in early experience,
"`Keep near to Truth, and the friends of Truth, and the Truth will keep you.`"

It made a strong impression, and so far I have realized its verity,
and have had frequent occasion to hand it to others.
To have such a Friend to resort to when beset with temptation,
or closely tried with desertion and poverty of spirit, was a great benefit to the weary,
inexperienced traveler;
from whose company we sometimes returned comforted and cheered to hold on our way.

My uncle Thomas Scattergood`'s residence was a house of similar resort,
where the mourner found a deeply sympathizing friend,
and the young soldier one who had large experience in
the trials of the spiritual warfare,
and who gladly seized the opportunity of cheering him on to victory.
Sometimes when I have visited him,
and would silently sit without doing anything to prompt him to
conversation,--for he passed much time in meditation and in
communion with the Lord,--he would brighten up,
and enter into the subject which he knew had taken hold of my mind,
and relate portions of his own experience and travels--or of the openings of
Truth in his mind relative to the great cause of universal righteousness,
and the events passing in Christendom.
He was not only remarkable for the gift of the
ministry of the gospel of life and salvation,
but also for the spirit of prophecy, with which he was at times clearly endowed,
and under which he often foretold coming events;
being a man who lived in the Spirit and walked in the Spirit,
and to whom the Lord condescended to make known his
secrets relating to the spiritual condition of others,
and of his works among the children of men.
I loved him much, and he manifested his love and interest for me,
like a tender father in the Truth.

As I advanced through my apprenticeship,
at times deeply afflicted that I did not gain
that victory over my passions and propensities,
which I believed through the grace of our Lord Jesus Christ,
the obedient soul would attain--at others`' consoled with his peace
and the blessed hope that I should eventually be made a conqueror,
over all the powers of darkness;
I was often favored with clear views of the condition of the true church,
clothed with the sun, having the moon under her feet,
and of the certainty that the prophecies would be fulfilled in the Lord`'s way and time,
when the earth shall be filled with the knowledge of the glory of the Lord,
and righteousness shall cover it as the waters do the sea.
It then appeared clearly to me,
that the members of our religious Society collected in the capacity of Yearly,
Quarterly and Monthly Meetings, ought individually,
as members of Christ`'s visible church, to wait upon Him for wisdom,
ability and authority, to engage in and to manage the affairs of the church.
That the work is the Lord`'s;
that it is his prerogative to select whom he will to take an active part therein;
and that such should depend upon the immediate aid of his Holy Spirit,
in the discharge of the various duties,
which pertain to the oversight of the flock--in reclaiming or disowning transgressors,
and in the general administration of the discipline.
Also that those who were not called upon to take so active a part as some others,
would nevertheless have their allotment of service, both in a silent,
spiritual travail for the prevalence of Divine life and power in our meetings,
and at times in showing their unity with the judgment and concerns of others.

The dignified station of a minister and messenger of the gospel of Christ,
for the purpose of gathering souls to Him and exalting his name and kingdom among men,
was opened before me,
and I fully believed that all who are rightly placed in that honorable office,
are made ministers by Christ himself;
and that what they preach should be from the direct
openings and communication of his Spirit in the heart,
who only knows when his flock need instrumental help,
and what is suited to their respective conditions.
These things I was favored to see in the light of the Lord Jesus,
and at times I felt as if I could stand forth as a servant under his
authority to proclaim the glad tidings of life and salvation,
and gather souls in the gospel net.

While an apprentice,
I accompanied my mother and two other ministers of our meeting to Cain Quarterly Meeting.
This introduced me to some substantial Friends in the country,
whose society and conversation were very interesting and instructive,
particularly of that innocent-spirited and lively minister,
James Wilson of the Western Quarter, who was then at Cain.
To sit down in a strange meeting and partake of
sensations either of enjoyment or suffering,
and to mingle with Friends at the different houses where we were entertained,
was a new scene, and gave rise to views and feelings,
of a cast contributing to my attachment to the cause of Truth.
At another time I was sent to Oley with Mercy Ellis and her companion,
who had visited the families of our Monthly Meeting.
It took us two days to accomplish it.
We put up at Thomas Lee`'s, and on the following morning I intended to return,
but the weather set in wet and I was persuaded to stay their meeting.

Among strangers and the weather gloomy, I felt depressed; but going to their meeting,
my mind was replenished with a sense of the love of my Heavenly Father,
which was a full reward for the difficulty I had in taking
these dear Friends thus far on their journey homeward.
I believe it is good for young people to be in
the way of the society of substantial Friends,
and to cherish a disposition to wait upon them and aid
them in the prosecution of their religious services:
a blessing will attend those who render such assistance from sincere motives,
inasmuch as "`he that gives to one of these a cup of cold water,
in the name of a disciple, shall receive a disciple`'s reward.`"

David Sands, an eminent minister belonging to New York Yearly Meeting,
visited our city about this period.
His ministry was peculiar, addressed to the states of the people,
and at times describing in very vivid terms the joys of
a future state prepared for the righteous,
which had a quickening effect.
He came to my father`'s house;
I felt a particular desire that he would preach to one of my brothers and myself,
he being reputed a man who was favored with a
clear discernment of the conditions of people.
He did address us in that way, but not according to my wishes.
He simply told us that we knew the path we should walk in, and exhorted us to keep in it.

But I wanted something more definite and impressive, like the Syrian,
a little display of divine power and condescension in opening our particular states.
In the course of my exercises,
I was at times persuaded that it would become my
place to engage in the work of the ministry;
and had I been faithful in denying self and steadfastly
bearing the cross as I ought to have done,
it is not improbable I should have been sufficiently
reduced into the state of a little child,
so as to be entrusted with the gift at an earlier period of life.
But my unstable nature was hard to curb, and though this prospect at times presented,
and some hints were given by others,
yet not having a distinct pointing of duty to engage in it,
and being persuaded of the great importance of being right in that weighty work,
I dared not to put forth a hand,
until the period came round in which a necessity was laid upon me,
and the fear came over me, that by putting off, I should be left in darkness.

About the seventeenth year of my age, our beloved friend Sarah Cresson,
a valuable minister, staying then at my father`'s,
suggested whether I would not derive benefit from reading Robert Barclay`'s Apology.
I had occasionally looked into it, but not thoroughly, and at her suggestion,
I went through the work, which was of use,
confirming me in the doctrines of the Christian religion as held by Friends,
and as they were opened to me in reading the Holy Scriptures.
I consider it the clearest and best argumentative exposition
of the principles and the effects of the Christian religion,
in print.

After having passed through many baptisms and mortifying
dispensations in order to reduce the old inhabitants of the land;
and also experienced many seasons of divine consolation,
wherein I was enabled to pour out my soul before the Lord,
and fervently to desire to be made one of his children,
and to serve Him all the days of my life, it pleased Him to hide his face from me,
and to withdraw the sensible influences of his blessed Spirit;
through which alone we derive living faith, and are enabled savingly to believe in Him.
The enemy soon took advantage of this bereaved condition,
and started the doubt whether Jesus Christ was my Savior.
I remembered that He had declared:
"`My sheep hear my voice and they follow me;`" and then
I began to doubt whether I was one of his sheep;
for Satan insinuated that I had never heard his voice.
This was a new trial;
but when I was so clouded that I could not be certain I
had really heard the voice of the true Shepherd,
then the devil raised the doubt, whether Jesus Christ was the Son of God;
and without having done anything that I knew of, to bring myself into this state,
I found I was incapable of really believing in the Savior of the world.
I felt no disposition to deny or to reject Him,
but I could not command that faith in the Lord Jesus Christ, which I had heretofore,
as I once thought, possessed.

Great distress and anxiety came upon me.
Unwilling to lose my faith, I searched the Holy Scriptures,
and diligently read various religious works which I hoped would restore the lost pearl;
but it was all in vain.
I was utterly unable to regain my faith in Christ,
which had been an anchor to my soul in many tossings and tempests.
For a long time I was kept shut up in this condition, until I gave over searching books,
or striving to satisfy myself by any argument.
I looked up to my Heavenly Father, but all was hid from me, and I wondered how it was,
that I should be unable to believe in the Lord Jesus Christ,
who I had been taught to believe and never before doubted, was the Savior;
and yet through all, something kept me steadfast and patient;
and I never told any one of my suffering condition.

One evening as I was walking out for meditation, according to my frequent custom,
with my mind turned towards the Lord, He whom my soul sought above all things,
suddenly came to his temple, and by his Holy Spirit, revived my faith,
and gave me to see,
that He alone is the author of that faith which enters within the veil,
and gives victory over the world, the flesh, and the devil;
and that it is not founded merely on what is read,
but is really of the operation of God on the heart.
I rejoiced exceedingly and gave thanks to Him who is worthy of all praise and honor,
and who will not give his glory to another.
I could now firmly believe in the Lord Jesus as my Savior,
because of the renewed revelation by the Holy Spirit giving me
that faith in Him--and through mercy I have never since been
permitted to feel any doubt respecting his divinity,
his mediation, or any of his offices in the redemption and salvation of man.
I record this under a sense of my own nothingness,
and for the purpose of exalting the glory of his Grace;
believing that the foundation of true gospel,
saving faith is the immediate manifestations of the Holy Spirit,
and it is this which draws the dedicated soul to Christ,
and enables it to believe in Him savingly,
to rely upon and to follow Him in the regeneration,
as our Redeemer and the Captain of our salvation.
This faith works by love, and this love is evidenced and maintained in obedience.
No man can be in the true faith unless Jesus Christ dwells in him; and where He rules,
the fruits and the works of the Spirit will be brought forth; and the faith of such,
though it may be tried as gold in the fire, will be renewed from time to time,
and give the victory over all the powers of darkness.

Although this trial occurred some time before I was of age,
I have often referred to it since as a peculiar favor and blessing,
especially when the separation of the Hicksites drew on; inasmuch,
as that turned upon the denial of the divinity and atonement of the Lord
Jesus--and also when some have been disposed to make the Holy Scriptures the
origin and foundation of true faith in our Lord Jesus Christ.
They are an invaluable record of all those things most
surely believed by the faithful followers of Christ,
who have the opportunity of reading them,
but it is God alone who can give true and saving faith
in his beloved Son and in the truths of the Gospel,
and it is by his mercy we are preserved to the end in possession of that faith.

When I became of age the prospect of commencing business for
myself involved me in serious thoughtfulness,
but as it was for my support, I took a house and opened a drug store in a moderate way,
in the Twelfth month, 1808;
but while it was a necessary duty to provide for my own subsistence,
the kingdom of heaven and the righteousness thereof were in my view,
primary to everything else.
I set out with the desire to have the world kept under foot,
and to devote myself to the Lord and to whatever service He might call to;
at the same time it was my settled conviction,
that to provide things honest in the sight of
all men is a bound duty where health permits,
and that in the prosecution of business, strict integrity in dealing,
and a scrupulous guard against contracting debts without ability to discharge them,
and to live within the limits of our income,
are also duties indispensable to the Christian.

I had a great fear of bringing any shade or reproach upon the profession of the Truth,
or upon the Society to which I belonged; and whenever any business presented,
however profitable, which appeared to me to conflict with either,
I felt most easy to decline engaging in it.
Although my transactions were on a small scale,
and consequently did not open the way for the accumulation of riches,
which sometimes was humiliating,
and produced sensations of dissatisfaction that I was not
likely to stand among men as independent as many others,
or procure the accommodations which they had,
yet I never was involved in any difficulty in timely meeting my engagements,
and was always able to provide every comfort in life that I desired.

Since that day I have observed some among us who had succeeded in accumulating wealth,
plain in their garb and active in religious society,
who looked upon those who were in small business with contempt,
and at times spoke slightly of their scruples
respecting Friends engaging in extensive concerns.

But the latter have a refuge which cannot be assailed by the pride or arrogance of man,
into which they are often permitted to flee and find safety.
Whenever I was subjected to sensations of that kind,
retirement to my divine Lord and Master,
committing myself and the course I had taken to Him,
and looking to Him for consolation and the recompense of reward at the end of the race,
raised me above these earthly and sordid views,
and gave me an authority and dominion over that spirit, of which none could deprive me.
Wealth and the importance arising from it were nothing to me,
and not worthy of comparison with a place in the Lord`'s house,
and the honor and dignity with which He clothes his humble, faithful children.

1809+++.+++ Business opening very slowly in the following spring,
If It concerned lest it should not prove adequate to my necessities,
and one day sitting in the store seriously and solitarily contemplating my prospects,
my gracious Master condescended to show me that if I was faithful to his requirings,
I should never lack food nor raiment.
The language and impression were so clear, humbling my heart before Him,
that I believed his word, and thereby proved that that faith, of which He is the author,
is the substance of things hoped for, the evidence of things not seen;
my mind firmly and peacefully rested in it,
as much as it would have done in an independent estate,
although no change in the business very soon occurred.

On the 11th of the Twelfth month, 1811, I was married to Deborah,
daughter of Aaron and Abigail Musgrave.
Some time before, she had been brought under the convicting power of Truth,
with several other young persons who attended our meeting,
and was strengthened to exchange a life of gaiety and mirth for one
of simplicity and humble walking with her divine Lord and Master,
and was then received a member among Friends.
Our engagement was not entered upon without the requisite deliberation,
and strong desire to be preserved from taking such an important step,
unless accompanied with a sense of divine approbation.
This was graciously afforded by Him whom we desired to obey in all things;
and although many years were not allowed for our earthly pilgrimage together,
yet the few were passed in much sweetness of fellowship,
and their termination was a bitter cup to the survivor.

Being now settled in life,
my time was necessarily occupied with the various
duties pertaining to a proper provision for a family;
which were attended to in unison with that dedication to the will of my Heavenly Father,
and to the various services of religious society,
which I felt of indispensable obligation and
connected with a growth in the life of religion.
I was not without seasons of close trial and humiliation,
all which were needed to humble my proud and volatile spirit;
and had I maintained more faithfully the watch,
I should have made more progress in the Christian warfare,
and attained a deeper and firmer establishment in religious weight and solidity.

In the summer of 1812,
I went with several members of our meeting to Long Branch for the purpose of sea bathing.
It was the first view I had of the ocean,
and standing on the beach contemplating the works of the Almighty hand,
man seemed like a speck in comparison with the irresistible force of such a vast body,
when its mighty billows are wrought into fury by the power of the tempest.
We put up at a private house with few besides ourselves,
and attended the meeting at Shrewsbury.

At that time it was a place of little resort compared with what it has been since.
To weakly or sick persons, sea air and bathing are doubtless often useful;
but among the mixed companies that resort to these watering places,
there are many incitements to throw off the restraints of the cross,
and to fall in with the current of fashion and dissipation,
and the use of language and manners quite at variance with our religious profession.

Being removed from the society of parents and religious friends,
and consequently from under the influence of their example and their
known sentiments in opposition to these corrupt liberties,
a salutary restraint is withdrawn,
which makes it easier for young persons to take liberties they
would not resort to under their supervision;
and they may be too easily induced to frequent those places,
where they may receive moral wounds more dangerous than
the physical disorders which they seek to have cured.

Voluntary subscriptions being set on foot to create a fund for the erection of an
asylum for the benefit of persons deprived of the use of their reason,--members of
our religious society and professors with us,--I accompanied one or two Friends in
soliciting the subscriptions of some of our members,
and found that the proposed institution was generally approved.
Much good has been conferred on that afflicted class since that day,
who have been placed in it, and doubtless it had a right origin.

First month 27th, 1813.
Susanna Horne from England,
and Thomas Scattergood each opened in our Monthly
Meeting a religious concern to visit the families,
which was united with.

They came to our house on the 29th,
and had a religious opportunity with my wife and myself.
My uncle Scattergood sat a considerable time in
deep silence after Susanna had relieved her mind.
He seemed impressed with a sense of afflictions to come,
and then spoke on the necessity of close adherence to the internal guide,
in order to witness preservation on the sure foundation in times of deep trial,
that might be permitted to assail, for farther purification,
and preparation to bear burdens that may be assigned or permitted to come upon us.

Our country being now at war with Great Britain, business was much at a stand,
and the state of the country at large was gloomy and distressing.
At such a time wickedness is let loose,
and unprincipled men strive to gain the ascendency in power,
manifesting very little feeling for those who are
conscientiously restrained from falling in with the current.
A bill was introduced this spring into the legislature
of this State for a new organization of the militia,
containing provisions that would operate with great severity upon Friends.
Our Meeting for Sufferings prepared a remonstrance against it,
which was taken to Harrisburg by a committee appointed for that purpose.
The bill was finally thrown out by the Senate, and of course did not become a law.

Fifth month 7th. The sudden death of the Friend who had very
faithfully waited on Susanna Horne in her travels in this country,
produced strong sensations among his friends and acquaintance.
He had taken up his saddle-bags at his own house
to set off in order to meet her in New Jersey,
when he fell on the floor,
having been previously sick at the stomach and complained of pain in the head;
and though great efforts were made by several physicians, they were unable to revive him.
Information of the afflicting event was communicated to Susanna Horne,
and she came to the city and attended the burial on the 9th, being first day.
She knelt in supplication at the grave side,
and Arthur Howell and Thomas Scattergood spoke
in testimony to the dedication of the Friend,
and their undoubted persuasion that he now enjoyed a mansion among the blessed.
The suddenness of his death when apparently in usual health,
and just intending to set out on a journey,
was an impressive instance of the great uncertainty of life,
and a loud call to faithfulness to the manifested will of our Heavenly Father,
that when our day is over, we may be ready to meet the awful Judge of quick and dead.

The English vessels of war being now on our coast,
and committing depredations in many places,
the coasting trade was almost entirely stopped,
which kept away from the neighborhood of my store, which was in sight of the river,
most of the craft usually there.
This greatly lessened what little business I had,
and could not but produce serious thoughtfulness in relation to the means of subsistence.

In the fall of this year my beloved mother,
being liberated by the Monthly Meeting to visit the Meetings composing Salem Quarter,
and the two on Great Egg Harbor, I drove the carriage, Ann Offley being her companion.
John Baldwin, a minister living near Downingtown, Chester county, Pennsylvania,
and Isaac W. Morris in another carriage, went in company.

We travelled in much harmony, visited all the meetings,
in the course of which we had some solid opportunities,
and returned the last day of the Eleventh month.
