== Chapter II

[.chapter-synopsis]
* 1813--1819. Proposed change of Business
* Uneasiness therewith
* Relinquishes it and finds Peace
* Before a Court Martial
* Reflections on the Unchristian Practice of War
* Peace Principles applicable to National Government
* Death of T. Scattergood
* Commencement of his Wife`'s last Illness
* Her Character and Convincement
* Her last Sickness and Death
* Weighty Expressions during her Illness
* Accompanies his Mother on a Religious Visit
* Goes to reside with his Parents
* Accompanies his Mother to New York Yearly Meeting
* Death of his Father-in-law
* Accompanies his Mother to New England Yearly Meeting
* First Appearance in the Ministry
* Source of True Faith
* Necessity of keeping to First Principles
* Death of Sarah Wilson.

In consequence of the war with England, business was much depressed,
and having the expenses of a family to meet, which it seemed improbable,
if the difficulties continued, the little I had to do, would be sufficient for,
I became so dissatisfied that I resolved to make some change.
A relative, who was a dealer in dry goods, wanting a partner,
I concluded to join him as soon as the war was brought to a close,
and made arrangements to borrow a sum of money, which with that employed by him,
was deemed a sufficient capital.
The prospect of the connection,
and engaging in a business that looked likely to be profitable,
was animating and pleasant; and from the feelings of my mind,
I thought I had given the subject ample consideration.

We entered upon some of the preparatory steps, which brought us frequently together,
and to converse upon the business and the manner of conducting it.
As I was led into a knowledge of the course pursued in that line,
scruples occasionally arose in my mind,
which I attributed to fear produced by the novelty of my situation.
Selling articles which I should not be easy to wear, or recommend others to wear,
presented some apprehension of difficulty, but I concluded these might be dispensed with,
and the business still be large enough; or perhaps when I became fully engaged,
these feelings would wear off.
Then arose the thought of entering into a business which I did not understand,
and the condition in which I should find myself, were my partner removed by death.
This circumstance I hoped would not occur,
and I endeavored to suppress my apprehensions with the belief that
experience would soon render me familiar with my new employment.
In his desire to open the way for our union and future operations,
my relative told me that besides the amount of our capital, which was borrowed,
it would be necessary to purchase on credit large quantities of certain articles,
the payment of which would be provided for in the returns of our sales.
This was a further insight of the responsibilities we were about to take upon us,
and which raised fresh doubts and fears.

My present business being small and one that I understood, was managed with ease.
It required little capital,
and involved me in no engagements that I did not hold the means to meet;
so that I was free from anxiety on that account,
and at liberty to attend unencumbered to any of the appointments of the Society,
or any impression of duty to go to a meeting that I might have.
When I contrasted my present situation, for I had not yet given up the drug business,
with the project before me,
and recollected that I had never been accustomed to the
anxiety which often attends large commercial concerns,
I began to feel stronger doubts of the safety of making so great change.

These doubts increased; and one day sitting in our religious meeting,
it plainly appeared to me, that though the mind may be able to compass much,
yet beyond its capacity it cannot go.
If all its energies are enlisted in the concerns of the world,
and their pressure is as great as it is capable of bearing,
the all-important work of religion must be neglected.
This appeared to me, must inevitably be my case.
My time and talents would be wholly engrossed,
and I must abandon all prospect of usefulness in religious
society for the servitude of a man of the world.
It seemed if I pursued the prospect of adopting the proposed change of business,
that I should be lost to religious society and to the work of religion in my own heart.

These views brought me to full stop.
I was afraid to risk my everlasting salvation for the sake of worldly emolument;
and notwithstanding the mortification,
I determined that it was best to inform my proposed partner in a proper manner,
that I could not proceed, and also of the cause;
which was a trial to him as well as to myself, though no steps had been taken,
that would involve him in difficulty.
After having come to this conclusion, and my concern for his disappointment had subsided,
I felt relieved of a great burden,
and then resolved that as long as I could make a
living by the business I was brought up to,
I would not abandon it for any other,
but labor after contentment in such things as my Heavenly Father granted to me.
I looked forward with renewed peace and satisfaction at
the path and the business before me,
though small, remembering that the earth is the Lord`'s,
and the cattle on a thousand hills, and He in his inscrutable wisdom and kindness,
will dispense what He knows we need.

My relative died in less than three years,
and the very great losses produced by a falling market,
proved in the end that I had escaped from a load of anxiety,
and almost inextricable embarrassment.
Indeed, being left alone in a business I was in nowise fitted for,
it is probable it would have proved my ruin.

It is good to trust in the Lord,
and to mind the secret intimations of his blessed Spirit;
for I believe it was nothing less than his merciful superintending
care that snatched me from the thralldom I was preparing for myself.

In the fall of 1813,
the citizens illuminated their houses on the event of a victory
gained by the Americans over the British in a naval engagement,
which produced sadness in many minds.

Our Savior forbade his disciples to rejoice, even when spirits were made subject to them,
in their religious engagements;
and when some enquired whether they should command fire
to come down from heaven as Elijah did,
to consume his opponents, He replied, "`You know not what manner of spirit you are of;
the Son of Man came not to destroy men`'s lives, but to save them.`"

How lamentable it is that men calling themselves Christians,
can promote the destruction of their fellow creatures, and when many have been killed,
or wounded and crippled for life, then make a festival and rejoice over them.
What difference in this respect is there between the savage and the professed Christian?
Jesus Christ declared, "`My kingdom is not of this world,
else would my servants fight,`" evidently implying that those who do fight,
are not servants and subjects in his holy and peaceful kingdom.

Second month 24th, 1814.
I was compelled to appear before a court-martial sitting in this city,
to answer a charge of disobedience of the orders of the President of the United States,
in refusing to march as a militiaman last spring.
I stated to the court-martial,
that I was conscientiously bound to decline all warlike measures,
and could not by any means comply with such requisitions.
That I was a member of the Society of Friends,
and although we cannot actively comply with laws that would violate our consciences,
yet we do not rise against the Government;
we passively suffer the penalty which they inflict--at the
same time we think it right to plead for liberty of conscience,
to maintain our rights in a peaceable manner,
and not tacitly suffer distraint or imprisonment without law.

They heard me patiently and respectfully, making but little exception to what I advanced.
I understood they decide the question by vote, whether the fine shall be exacted:
what was their course in my case I never heard,
but they never attempted to collect any fine of me and I suppose they voted me free.

It is very important at all times to bear a clear and faithful
testimony to the coming and kingdom of the Prince of peace;
and when the noise and spirit of war are over the land,
and wicked men are ready to make a prey of those who cannot join in their measures,
the times call for increased watchfulness that we may not be caught with that spirit,
and the desire of success on the arms of either belligerent party,
or in any manner let the testimony against war and bloodshed fall to the ground.

Seventh month 17th. There is now a great pleading by many for war.
Some who assume the name of Christians say they
deprecate such a state of things as much as any;
but when their rights are invaded,
their dwellings and the lives of their families endangered,
they ought to defend themselves--and though they wish not to destroy life,
yet if in self-defense, the aggressor is killed, they consider themselves justified.
But while they think his blood will be upon his own head,
they know not how far the act of taking human life may
rest with awful weight on their consciences,
when the heat of passion and revenge has gone off.
They lose sight of the superintendence and protection of an Almighty Providence,
and of the duty of putting their trust in Him.
They argue that power is the support of government,
and that it is the knowledge of this power that compels many to comply with the
requisitions of the law--that there is an analogy between nations and individuals.

When differences occur between individuals,
it is power that obliges the aggressor to make restitution to
the injured--so when a dispute arises between nations,
which they plead cannot be amicably adjusted,
the advocates of war say that recourse must be had to the sword,
to obtain that which the jarring views of the parties prevent taking place.
At the same time they acknowledge that war is a dreadful evil which
ought if possible to be avoided--that the time will come when sin,
being banished from the earth, war will cease; but in the present state of the world,
it is, they think, inevitable and justifiable.

Power may be exercised in a government to great extent without destroying life,
for the purpose of punishing the transgressor,
and preserving the peace and the property of the citizen.

As true religion prevails,
less physical force will produce greater effect on the remaining vicious;
and in proportion as the former spreads, the latter will be less needed.
Where no military force is called in,
there is less cause to excite the evil part of the
community to retaliate and resort to the same.
The use of arms stirs up men to provide themselves with and to use them.
How much wiser and better would it be to settle differences between nations by the
arbitration of a friendly Power--inasmuch as after having fought and killed,
negotiation must be the final resort to settle the dispute.

In reflecting upon this subject,
it may be right to take a view of the character of a disciple of Christ,
and how he became a disciple.
"`Take my yoke upon you,`" said our blessed Lord, "`and learn of me,
for I am meek and lowly of heart.`"
Here the attention of the mind is arrested, and as it submits to Him,
He gradually unfolds to it what He would have us to leave undone and what to do.
As his requirings often prove the reverse of our inclinations,
we need the aid of his Spirit in conforming to them;
which in this case is compared to a yoke to keep down our propensity to evil;
or a cross to crucify our stubborn wills,
which often rise in opposition to the coming of his kingdom in the heart.
"`If any man will come after me let him deny himself,
take up his cross daily and follow me.`"
The direction and rule of the heart are to be entirely given into his hands.
We are not to choose for ourselves,
but simply as little children attend to his daily instructions,
which as we carefully follow will produce a growth and increase of spiritual strength.

Our sinful propensities and passions will become gradually
weakened--our affections loosened from things below,
and set on things above; and through the prevalence of his love,
it will become our meat and our drink to do the will of our Father who is in heaven.
Various are the baptisms, the inward plunges and washings that we must witness,
before this state is attained;
but it is nevertheless our duty and our highest interest to come to it,
and without it we shall fall short of the stature of a perfect man in Christ Jesus.

Living under the yoke and daily cross of Christ we become joined to Him in one Spirit,
and according to our measures are partaking of the divine nature; for says He,
"`He that does the will of my Father, the same is my mother, and sister,
and brother;`" and again, "`I am the vine, you are the branches.`"

Here such a union is formed between Christ and his brethren, that those who touch them,
touch him, and not a hair of their head shall perish without his notice.
They can suffer no injury, nor be in any emergency however secret or pressing,
without his knowledge; and as all power in heaven and in earth is given to Him,
they have great cause to put their trust in Him, believing if it be for their good,
and the promotion of his righteous cause,
He will deliver them as He has defended many of his children,
in the hour of appalling danger.
He has also permitted some of his most faithful
servants to seal their testimony with their blood,
but the proportion of these to the whole of his family is small.
But yet in this they have infinitely the advantage over their enemies,
in that standing faithful to their Master they have been made partakers of his glory;
whereas their persecutors, if they do not repent and bow to his name,
will in the end be cast into utter darkness,
where will be weeping and wailing and gnashing of teeth.
The longest life is short--the duration of suffering here is limited,
and as the design of our creation is the glory of God,
if He sees meet in the promotion of it to suffer our
life to be terminated by the hands of cruel men,
we have nothing to fear or to murmur at;
but rather through the power of his love to rejoice in suffering,
which is but for a moment,
and that it will work for us a far more exceeding and eternal weight of glory.

The smallness of the number of righteous men and women, conscientiously opposed to war,
who suffer violent death from mobs or armies, is quite remarkable.
These are rarely assaulted either in their dwellings or on the high road,
which shows that the protection of Divine Providence is extended to them.

From this we may suppose, that were there a nation of such Christians,
who lived in love and harmony among themselves,
and who from conviction of its unlawfulness,
never could resort to arms to defend themselves,
it would become known among the nations of the earth;
and from the fact that no warlike resistance would be made on any occasion,
they would refrain from meddling with them;
either because He who turns the heart of a man
as a man turns the water-course in his field,
would show them it would be wrong to disturb them and would not permit them;
or from the principle, that as there would be no resistance by arms,
it would be unmanly and unworthy to assail such a people.

In the Fourth month, my beloved uncle Thomas Scattergood died,
after an illness of but a few days.
He attended about half the sittings of the Yearly Meeting when he was taken sick,
and on the first day morning following he was released
from the trials of this earthly pilgrimage,
and I have no doubt passed into the church triumphant.
On seventh day, a Friend expressed to him that he felt consolation in sitting by him;
he replied that he had experienced it also,
and that his mind was established on the sure foundation.
One of the physicians saying something respecting his dissolution,
he answered that if it was to take place now it was hid from him,
as many of the Lord`'s secrets are, from his servants.
He was a living, baptizing minister, often led into the states of the people,
and was instrumental in quickening many to a
more fervent exercise for their own salvation.

1815+++.+++ My late beloved wife was of a delicate constitution;
last winter her health and strength were much reduced.
She contracted several colds which were accompanied by cough and pain in the chest;
and being appointed a representative of the Monthly Meeting,
she attended the Quarterly Meeting in the Second month, although very unfit to go out.
She came home much spent,
and becoming much indisposed kept her room very generally afterwards.
We did not apprehend for a considerable time that her lungs were affected,
though the obstinacy of some of the symptoms and the variable state
of her feelings excited anxiety respecting the issue of the complaint;
she being sometimes apparently so free from disease, as to seem to be fast recovering,
and then would suddenly become so unwell, as to be scarcely able to keep out of bed.
The spring was unusually cold with easterly storms of rain.
It was, however, hoped notwithstanding her discouraging symptoms,
that when the weather became warm and settled,
a few week`'s residence in the country would check the progress of the disease,
and restore her to health and to her family and friends.
She was accordingly taken out on the 22nd of the Fifth month,
and continued in the country three weeks.
The air was cool for the season,
and the change did not produce any intermission of her complaint;
and the weather becoming warm during the last week, she weakened very fast.
One evening her mother observing her to be in pain expressed her sympathy;
when she answered,
"`We ought not to murmur at the dispensations of Providence,`" and added,
"`Mother, most of your children are in heaven, and I shall soon be there with them.`"
She concluded to return to the city,
and remarked that though the state of her body was changed, that of her mind was not;
believing it was right that the trial had been made.

She was naturally of a sprightly, amiable disposition, and in the early part of her life,
fond of gaiety and the amusements which her companions partook of.
This drew her into company that was calculated to keep
her from yielding to the convictions of Divine Grace,
which at times were powerfully brought over her.

On some occasions when associated with others who were dancing and singing,
her mind was so arrested with the visitations and reproofs of heavenly love,
that she would be unable to participate in the mirth and amusements surrounding her.
Through Divine mercy she was finally brought to submit to these visitations,
to withdraw from all these vain delights,
and to seek a closer acquaintance and union with the Lord,
who had thus enlightened her by his Spirit to see the emptiness of her former pursuits,
and the necessity of seeking enduring substance.

Persevering in faithfulness to the unfolding of Divine Light,
she was convinced that simplicity in dress and manners
was obligatory upon the follower of Christ,
and she became an example therein, even to those whose opportunities of a religious,
guarded education had been widely different from hers.
On this subject she remarks in some of her memoranda,
that "`The evidence was confirmed to her,
that simplicity in life and manners attends the narrow way which leads to life,
while the partaking of the enjoyments,
possessions and allurements of this deceitful world,
will inevitably lead to destruction.`"

In the twentieth year of her age, she made application,
and was received into membership in our religious
Society by the Southern District Monthly Meeting.
She was much beloved by her intimate acquaintances,
and was engaged privately to seek their furtherance in
the path of dedication to their divine Lord and Master.
With some of these she was frequently employed in visiting the habitations of the poor,
manifesting much tender feeling for them in their distresses,
by her persevering efforts in procuring and
administering the requisite comforts for their relief.
A select school for girls being opened within the limits of her Monthly Meeting,
she took charge of it for about eighteen months,
and proved herself well qualified for the care of the little children.
When she entered into the married life her testimony to
plainness was still kept in the furniture of her house,
guarding against a conformity to the fashions of
a vain world with which many are led astray.
Her gentle spirit, softened and regulated by the love of God,
rendered her a faithful and affectionate wife,
and she was religiously concerned for the future
welfare and preservation of her tender offspring.

Having in health submitted to bear the yoke of Christ,
and in good measure experienced its sanctifying operations in her heart,
she was now favored at a time when under an incurable pulmonary consumption, as she said,
with a "`heavenly state of mind,`" and enabled with
great calmness to look towards her dissolution,
which she was early sensible would be the termination of this sickness.
The disease made steady progress after her return to the city, and she suffered much.

In the course of her sickness she uttered many weighty expressions,
showing a living experience of inward communion with her Savior,
and of that redemption from sin and the fear of death,
which by the working of his mighty power in the soul,
He effects for his obedient children.
Before she went into the country, a few Friends having called to see her,
after a time of silence, a belief was expressed by one of them,
that her bed had been made in her sickness,
and that the guardian angel of the Lord`'s presence, had encamped around about her,
and supported her, when outward help failed.
After a short pause she uttered some expressions of
thanksgiving for Divine support during her sickness,
and added: "`I feel that I am unworthy of so many favors.`"
Then with uncommon energy, she broke forth nearly in these words:
"`Oh that I had the opportunity to testify to the goodness of the Almighty,
and that it was in my power to impress on the young people the
very great importance of giving up in early life,
that the mind may have a foundation to rest upon in the time of trial,
when the world is as nothing.`"

The prospect of parting with my beloved wife was at
times attended with feelings that seemed insupportable.
We had been married but a few years,
and to be obliged to give up one whose purified spirit rendered her a
most desirable companion in this scene of probation,
appeared at some seasons altogether irreconcilable.
And one day the prospect came over me with such force,
that I was tossed with a tempest I could hardly support;
but as I was walking alone up and down the floor in this state,
the Savior graciously appeared, and in the midst of my perturbation,
said to my mental ear, "`Peace, be still,`" and there was a great calm.
I then became more resigned,
but still secretly clung to the hope that she would be spared.

On the 18th of the Sixth, she was visited by one of her cousins,
whose mind had been brought under religious exercise, to whom she said:
"`My desire for you since you have been sitting here, dear Susan, has been,
that you may dig deep, and get to that sure foundation,
against which storms and tempests shall never be able to prevail;
that when you come to be laid on such a bed as I now am,
you may have a well grounded hope of entering into that rest,
where sorrowing and sighing will be done away.`"
This cousin died in a short time after her.
One of her aunts sitting by, observing her to be in much suffering,
said she believed it was not because she was cast off,
that her distress of body was so great; she rejoined,
"`Whom the Lord loves, He chastens.`"
And in the course of the same day, her father remarking that she had a suffering time,
she sweetly replied,
"`Yes, father, but I have an Almighty Friend underneath who supports me over all.`"
On the 19th, she supplicated thus, "`Oh great and glorious Lord,
grant me patience that will carry even through the gates of death.
You know that I have endeavored to serve you according to my measure;
prepare for me according to your eternal goodness, a mansion of rest;
and shorten the time, if consistent with your holy will.`"
After a few minutes,
"`In all my trials and deep afflictions, I have refreshing seasons.`"

At a time of great bodily suffering, her mother-in-law being present, she said,
"`I should consider it a favor to be removed in one of these spells, but I am resigned;
it is my meat and drink to do the Lord`'s will.`"
Some time after she expressed, "`Well is it for me,
that part of the work was done before such a time as this.`"
Then making a solemn pause, she broke forth in commemoration of His goodness,
and in intercession, "`Almighty God, my soul does magnify you,
and my spirit rejoices in your salvation.
Oh, grant that I may receive daily a portion of your holy, everlasting patience.`"

On the 22nd, being in much pain she said, "`I had need to cry aloud for patience.
O Lord, hear the voice of my supplication; be near in the hour of deep distress.`"
Some little time after, on taking some drink she said,
"`I ought to be thankful for the many blessings and favors I receive;
there are many poor things who have to suffer all this,
and have not these,`" alluding to the refreshments furnished her.

Her father and mother-in-law being present in the evening, she said to them,
"`You have not heard me my dear parents,
say much respecting these dear children I am about to leave.
In the early part of my sickness I had a comfortable impression on my mind,
that if I should be taken from them,
there was a Father to the fatherless and a Husband to the widow,
so I have been mercifully kept from anxiety about them;
yet I have been at times concerned for their everlasting welfare;
desiring they might know the God of their fathers,
that they may become earlier acquainted with their Creator than their mother was;
though when but about eleven years old I was so clearly convinced of a principle within,
that condemned for doing wrong, and led to do that which was right,
that I have been induced to leave my pillow, with my cheeks bathed with tears,
and on my knees pray that I might be a good child.
I have craved that they may remember their Creator in the days of their youth,
and have desired that rather than they should
not walk in the way that is well pleasing to Him,
He would be pleased, while in their innocency, to take them to Himself.`"

On the morning of the 23rd. "`Oh great and holy Being,
be pleased to grant fresh supplies of your patience.
Oh hear the voice of my supplication; be near and uphold me,
for I have none in heaven to look unto but you,
nor in all the earth in comparison with you.
I magnify you for your mercy, and for all your benefits;
I love to speak of your goodness.`"

Her sufferings on the morning of the 24th were very great and exhausted her much.
About 4 o`'clock in the morning, in much agony, she prayed, "`O Lord be near;
grant me patience in this trying hour.`"
Then said, "`Oh what a trial and conflict I have had!
Had my God been pleased to have taken me in this trying hour, what a favor!
Oh grant me patience; let resignation be my constant theme.
You are great, and you are merciful.
You know all my deep afflictions; you will not try me beyond what I am able to bear;
therefore let me bless and praise you with this poor
breath;`" her breathing being very difficult.
A little while after, "`O Lord, take me to yourself.
O Lord how good are you to me.
My heart is filled with praises to the High God who reigns above with the Lamb forever.
Oh the sweet peace.`"
After those trying sensations had a little subsided,
she appeared like one just about to enter the kingdom,
clothed with the meekness and purity of one of the Lord`'s redeemed children.
In a sweet and heavenly tone she said,
"`I have been thinking of the expression of our Savior,
Suffer little children to come unto me, for of such,
is the kingdom of heaven--their angels do always minister to my Father who is in heaven.
I do not know whether it is correct, but it is what I have been thinking of.`"

She took some nourishment, and endeavored to compose herself to sleep,
but the cough being frequent it was much interrupted.

Her mind appeared to be occupied with her two infant children,
of whom she had spoken but a few times throughout her sickness.
In her sweet and affectionate manner she said, "`Oh my dear little prattlings;
when I see them under the protection of an omnipotent and omniscient Being,
overshadowed as with the banner of his love, my soul is filled with love, with praises,
high praises to his great and most excellent name--a Savior that will
go with them and preserve them in the slippery paths of youth.
Oh if the Lord will hear my prayer, and check their early propensity to evil.`"

On parting with her brother, Joel Evans, who had called to see her, she said,
"`Farewell my dear brother; and whether I ever see you in this life or no,
may the Lord bless you--bless you with the dew of heaven;
and may you walk worthy of his Holy name, that so you may glorify Him,
not only in this world, but in the world to come--Farewell.`"

Being asked in the afternoon how she felt, she replied, "`The body is comfortably fixed.`"
It was then inquired whether she did not feel comfortable in mind, she answered,
"`Yes,`" and then proceeded, "`That glorious Presence is not withdrawn,
but I believe is near to support my poor, weary, tried, tossed mind;
not tossed with tempest but weakness;
and when it shall be his glorious will to take me hence, I go rejoicingly.
If I love and serve him, will He not keep his covenant?
yes, most surely.`"

On the 25th her brother and sister-in-law, Joseph and Grace Evans, from the country,
came to see her, and previously to their leaving she addressed them in this wise,
"`I cannot, my dear brother and sister, let you pass away, as my time here may be short,
perhaps very short--which will be cause of rejoicing to me and thankfulness
to my heavenly Father--without mentioning what has presented to my mind of
the importance of becoming acquainted with what it is to be a true Christian;
not only to believe in the Scriptures that Christ was born, died and rose again,
but come to experience Him to visit you, guide you and direct your path through life.
Do what your hands find to do, not only as it regards the outward,
but know the inward work to go on with the day.
Thus you will become united to the Son of God.
This will sweeten your path through life,
and at the close give you an inheritance in his kingdom,
where there is peace and joy forevermore.`"

Notwithstanding the intense suffering which at times she endured,
her heart was often filled with praise to Him who had
redeemed her by the spirit of judgment and of burning,
and washed away her sins by his precious blood.
In the course of the day she said, "`Praise the Lord, Oh my soul, bless his holy name;
glorify Him while you are here; sing of his mercy and goodness,
for they are very great.`"

In the course of the night, her beloved friend Mary Morton, who was watching with her,
observing to her that she had indeed need of patience,
and that she thought she was abundantly supplied with it, she replied,
"`I am sensible of it and it is a great mercy,`"--and holding her friend`'s hand,
she continued nearly in these words: "`I have much to be thankful for.
I was visited in very early life, and was enabled to yield to the heavenly visitation;
this was a great favor.
He has been with me all my life long, and does not forsake me in this closing period;
but is graciously pleased at times to qualify, me under all my bodily sufferings,
to commemorate his marvelous goodness, and to sing praise,
high praises to his ever-excellent Name.`"

In the afternoon of the 27th, a few hours before her death, she said: "`Praise the Lord,
praise the Lord, Oh my soul; praise his great and glorious name.
Lean upon him that you may know him to be your support in the hour of deep conflict,
and to receive you into the kingdom of everlasting rest.`"

Her close drawing near, she took a solemn leave of her connections present.
To her husband she said, "`Farewell, farewell,
dear William--we shall meet in a better world; the Lord will bless us there.`"
"`Lord Almighty receive my spirit;
angels wait to receive my spirit`"--then as if something held her, she said,
"`Don`'t hold me, don`'t hold me to this world.`"
She quietly departed about twenty-five minutes past 11 o`'clock at night,
the 27th of the Sixth month, 1815, in the twenty-eighth year of her age;
and doubtless has entered one of those mansions which the Son
of God went before to prepare for his devoted followers.

My situation was felt to be destitute, and as our two children were mere infants,
it was concluded that I should break up housekeeping and return to board with my parents.

My dear mother having a religious concern to visit Burlington, Shrewsbury and Eahway,
and Bucks, and Abington Quarterly Meetings,
and some one being needed to drive the horses,
it was concluded that I should undertake it;
and my health being somewhat impaired by confinement and waiting on my late dear wife,
the journey, particularly through the pines in New Jersey,
would probably have a restorative effect.
We set out in the Eighth month, and visiting all the meetings in prospect;
we were absent about eight weeks.
It could not be supposed the journey would be to me a very cheering one,
but notwithstanding my own situation,
and the trials we met with among those who were
but little alive to the great cause of religion,
I was satisfied with having given up to it,
and was forcibly struck as we rode home with the reflection, how short the time had been.
It seemed an emblem of life.
Looking forward to so many meetings and places, the time requisite to accomplish it all,
looked long; but after it was concluded,
it was like a dream or a vapor that soon vanished.

After my return I broke up housekeeping,
and took up my residence with my beloved parents on the 10th of the Eleventh month.

Eleventh month 13th. Since the decease of my dear wife,
I have often had to feel the loss of her precious society,
but a belief that she is in the company of saints and angels,
and the spirits of the just made perfect,
and the recollection that my own time will be short,
incite me to endeavor patiently and cheerfully to hold out to the end.
This is a state of mutability;
it is therefore necessary we should be sensible that every outward
gift is held by a very slender thread--let us then strive to become
increasingly acquainted with that which never changes,
but will endure beyond time.

1816+++.+++ In the Fourth month of this year my mother having
a religious concern to attend New York Yearly Meeting,
in which Sarah Wilson a minister belonging to our meeting united, I accompanied them.
We made our home at Thomas Eddy`'s, who, with his exercised wife,
received and entertained us with much kindness.
There was a spirit at work in some there who put on great plainness,
but who under the profession of supporting spiritual religion,
were beginning to undervalue the benefits and importance of the Holy Scriptures.

In the course of the sittings of the Yearly Meeting,
an epistle was prepared in reply to that received from the London Yearly Meeting,
in which the frequent reading of the Scriptures and the
proper observance of the first day of the week,
were enforced in a manner which appeared to me consistent with the
views the Society of Friends had always held on these subjects.

Elias Hicks made an attack upon those parts of the epistle,
in which he spoke very disparagingly of the Sacred Writings,
and improperly of the observance of the first day;
affirming that the spreading of the Bible was a part of the system of priestcraft.

We visited Mamaroneck Meeting and the meetings on Long Island.
When at Jericho,
the women Friends lodged at Elias Hick`'s--I stayed at his son-in
law`'s. My mother told me that she had a serious opportunity
with him respecting the course he was pursuing,
and remonstrated firmly against it,
endeavoring to bring him to feel the danger that awaited himself,
and the prejudicial effects it must have upon others.
She said he appeared to be affected by her labors with him.
It however availed little, as his after course proved.
After getting through with the services which my mother and Sarah Wilson had in view,
we returned home.

1817, Second month 15th. The Delaware river closed about the 24th of last month;
preceding that time the weather had been unusually mild,
which gave rise to the expectation that we should have a very moderate winter;
but the greater part of the last two weeks has been excessively cold.
Sleighs,
carts and wagons have been running on the river
without the smallest apprehension of danger.
This morning the mercury stood at five degrees below zero.

16th. This morning my father-in-law, Aaron Musgrave, died, in the 54th year of his age.
He manifested a steady patience throughout his illness,
and though he expressed but little respecting his prospects of futurity, yet his quiet,
resigned frame of mind, left no doubt with those who attended him in his sickness,
that his end was peace.

The view of a fellow mortal gradually wasting away,
until the earthly tabernacle is no longer able to retain that
part which is designed for an eternal duration,
is humbling.
It shows the weakness of the tenure of all sublunary enjoyments,
and calls loudly to those yet left behind,
to use all diligence in the great business of salvation.
But how easily do we suffer ourselves to elude
the force of impressions made by such examples.

Self-denial of the fleeting gratifications of this
world is a work very unwelcome to the natural man;
but it must nevertheless be submitted to,
if we expect to become conquerors through him that loved and died for us.
"`They that are Christ`'s have crucified the flesh, with the affections and lusts.`"

Sixth month.
Hannah Shinn, a minister belonging to our Monthly Meeting, and my dear mother,
having concerns to attend New England Yearly Meeting, I accompanied them to it.

We went to New York and from there in the steamboat for New London,
where we took stage for Providence, Rhode Island,
and put up at Obadiah Brown`'s. Our women Friends were taken in their carriage to Newport,
and I went by water.

In Newport we were quartered at D. Williams`',
where we often had the company of many Friends.
The Yearly Meeting was one of considerable exercise to our women Friends.

During the week we had several religious opportunities; in one of them at our lodgings,
my mind was so brought under exercise on account of some present,
and the passage presenting,
"`If any man among you seems to be wise in this world let him first become a
fool that he may be wise,`" that I felt constrained to revive it,
with a short application.
A minister took it up and spoke upon it, which seemed confirming that I was not mistaken.
We attended a few meetings after the Yearly Meeting, crossed to Conanicut Island,
and from there on to Narraganset, where we procured a conveyance to New London.
Next morning left the wharf in a steamboat for New Haven,
and from there to New York--attended the meeting at Liberty Street,
and next morning took our departure for home,
which we reached the following day about 11 o`'clock.

Eighth month 8th. In consequence of the fines assessed by the late court martial,
upon Friends, who could not comply with the requisitions of the Government,
either to serve in the recent war with Great Britain, or to furnish substitutes,
the houses of many were visited by the marshal`'s deputies,
and their bedding and furniture carried off by cart loads.
In several instances the value of the goods distrained
was from one hundred to two hundred dollars.
One Friend, residing in the vicinity of the city, had his carriage, worth one hundred,
dollars taken and sold for rather more than forty dollars.
The fine being fifty dollars, the deputy returned and took his chaise,
which lately cost one hundred dollars.
Thus a family were not only deprived of the
means of conveyance to their religious meetings,
but compelled to sustain a loss of two hundred dollars to meet a fine of fifty dollars,
arbitrarily imposed by a court-martial, from whose decisions there is no appeal.
These decisions were evidently marked with great partiality;
as a neighbor of the Friend was fined but nine dollars,
though no shade of difference could be perceived
in the circumstances of the respective cases;
except that one was a member of a religious society whose
testimony against war is coeval with its existence.
While these distraints and great sacrifice of Friends`' property were carrying on,
they did not fail to lay account of them before the public through Stephen Grellet,
the medium of one of the daily papers,
and some of them were such flagrant violations
of what even military men would regard as just,
that they brought some of the deputies to shame, and a stop was put to it.

The unjust proceedings consequent upon the late war,
often led me to many serious reflections upon its desolating effects,
both in the destruction of human life,
and the unjust persecution of conscientious men who cannot join in with it.
The mind that is clothed with Divine love, the charity which endures all things,
sincerely and humbly desires the welfare of all men,
even of those who treat us with coldness, or actuated by the spirit of revenge,
seek to injure us.
Where this heavenly feeling subsists, the spirit of revenge, which is the spirit of war,
has no place.
One is from heaven, from the Fountain of love, which seeks the salvation of all men;
the other is derived from the malevolence of the fallen spirits or devils,
who are constantly seeking the injury and final destruction of all men.

1818, Ninth mo.
9th. At different times in the course of my life I have apprehended that at some period,
I should be engaged in publicly laboring in the great cause of Truth,
to turn the attention of others, through its constraining power,
from darkness to light and from the power of Satan unto God.
Clear and distinct openings have been made upon my mind in a very impressive manner,
in relation to the standing and qualification of a gospel minister.
It has appeared to me necessary that through the humbling power of Christ,
and the baptisms of the cross, his will should be reduced,
and a state of childlike reliance on the Leader of Israel, in a good degree attained,
that he may be prepared to stand as an instrument through whom
the Lord condescends to speak to his people.

For several months past the time appeared to be drawing nigh for me to make
more public the concern that had been shut up in my own breast.
I had many impressive openings which seemed nearly ripe for communicating,
but remembering the awfulness and importance of the work, I kept back.
Sometimes I rejoiced after meetings in believing they were Divine impressions,
and sometimes I felt concerned that by putting off too long,
I might get into the habit of slighting them,
while I was looking for satisfactory evidence of the origin of the concern.

But He who knows how to deal with his children, did not forsake me,
but furnished with a fresh opening this morning in our Fourth-day meeting.
As heretofore I was preparing to set it aside for further confirmation,
when a beloved Friend was engaged to call upon some to
be faithful--that no sign should be given,
but that of the prophet Jonah,
who for his disobedience was permitted to descend into deep suffering and anguish.
This seemed so clearly applicable,
that recollecting I had passed through many night seasons,
and feeling after she sat down the fresh arisings of the concern,
I stood up and with an audible voice, said, "`God is our refuge,
in Him will we put our trust.
They that trust in the Lord shall never be confounded,
but they shall be as Mount Zion that cannot be removed.
Christ Jesus remains to be the eternal Rock and foundation;
blessed are all they that are built upon Him.`"

My mind was preserved in calmness throughout the day,
free from doubt of the propriety of my moving in the weighty and solemn work.
My dear friend, Thomas Kite, called down at the store to see me,
and though he said but little, seemed like one who rejoiced that a child was born,
secretly desiring that preservation and proper nourishment
might be vouchsafed by Him who alone can give them.

Tenth month 15th. "`Who do men say that I, the Son of Man, am?`"
And they said, "`Some say that you are John the Baptist; some Elias, and others,
Jeremias, or one of the prophets.`"
Various have been the opinions of many, perhaps in every age since,
respecting the Messiah, and in none, more so than in the present.
There are societies who consider themselves Christians that make no
scruple to profess they believe Him to be no other than man,
though they acknowledge He was a great prophet, divinely inspired,
but in no way differing from those prophets and good men who preceded Him.
It is a most fearful state of unbelief to be introduced into,
and must finally land the mind in great wretchedness.

When Jesus put the question to his disciples, "`But who say you that I am?`"
Peter answered, "`You are the Christ, the Son of the living God.
And Jesus answered and said unto him, Blessed are you, Simon Barjona,
for flesh and blood has not revealed it unto you, but my Father which is in heaven;
and I say also unto you, that you are Peter, and upon this rock I will build my church,
and the gates of hell shall not prevail against it.`"
Men may endeavor to satisfy themselves, from the testimony of the prophets and apostles,
respecting our blessed Savior,
whose testimony is true and invaluable to the true believer,
yet I believe the saving knowledge of God and of his dear Son, and true faith in Him,
are received in no other way but by the revelation of the Spirit in the soul.
By a childlike reception and reliance upon its divine openings,
walking in the obedience of faith,
we shall be prepared for further discoveries of his will,
and be gradually enabled to comprehend in degree, as He sees fit,
the mystery of Godliness.
Numerous are the testimonies of Christ himself
and of his apostles to his eternal divinity,
as recorded in the Scriptures of Truth, which become substantial evidence to us,
as they are unfolded and confirmed by the Holy Spirit;
leading us to an unreserved belief of them,
as it would assuredly do all who have the Holy Scriptures,
and are entirely given up to its requirings.
The apostle Paul clearly shows the distinction between the Son and Sent of the Father,
and his angels and ministers.
"`Who makes his angels, spirits, and his ministers a flame of fire;
but unto the Son he says, Your throne, O God, is forever and ever;
a scepter of righteousness is the scepter of your kingdom.`"

Tenth month 25th. In our morning and afternoon meetings
the prevalence of a worldly spirit was felt.
If the profits and friendship of the world be our primary pursuit,
they become in a great measure the gods we worship; and it is not to be supposed,
that such worshippers who have their backs to the temple,
will be favored to feel the life of Truth to rise into dominion over their fleshly minds,
just when they may choose to assemble in the character of public worshippers.

Tenth month 28th. This day was held our Monthly Meeting for the Southern District.
We had the company of Silas Dowming from Long Island, and William Hickman from England.

On answering some of the Queries,
it was evident that much delinquency prevailed in the attendance of our
meetings for worship and discipline--the free circulation of true love,
and its invariable companion, unity, has been much impeded;
and hence the barrenness often felt in our meetings for Divine
worship which no doubt is a discouragement to many,
who are not sufficiently zealous in the performance of this essential duty.
There is a number who are concerned at heart for the upright support of our
discipline and cannot rest satisfied with superficial conclusions:
but the same cause which hinders the arising of
Divine life in our assemblies for public worship,
operates to produce indifference and unsound judgment on the part of others,
in relation to the disposal of some cases that come before us.

Eleventh month 1st. This morning the meeting was held in silence.
When the disciples enquired of the Master "`Who
is the greatest in the kingdom of heaven?`"
Jesus called a little child unto Him and set him in the midst of them and said, verily,
I say unto you, except you be converted and become as little children,
you shall not enter into the kingdom of heaven.
"`Whosoever therefore shall humble himself as this little child,
the same is greatest in the kingdom of heaven.`"
Oh the great value of true humility! not a mere voluntary servile humility,
which is often accompanied with an improper
admiration of the gifts and standing of others.
True humility is attained through mortification and the abasement of self,
while the false and spurious,
may be held with imaginary importance and a quickness of sensibility
that is incapable of bearing the reproaches of others.
Under the humbling operations of the power of Truth we are prepared for the Master`'s use,
either silently to suffer with the Seed that is oppressed in the hearts of men,
or when He arises, openly to advocate his blessed cause,
to bring judgment home to the transgressor,
and encourage the sincere travelers to hold up their heads in hope.

4th. The marriage of Joseph Rhoads with my sister Hannah was accomplished today.
Being surrounded by friends and connections,
the occasion frequently revived the recollection of my own marriage a few years since,
and the endearing countenance and manners of a beloved companion,
now among the spirits of the blessed; and also the uncertain tenure of all earthly joys.
Richard Jordan attended the meeting and dined with us.
He mentioned in his testimony, that our trials if rightly profited by,
would tend to advance the great work of man`'s salvation.
I remembered some of my own conflicts,
and hoped that through the continued goodness of my Heavenly Father,
I might not miss of being benefited by them,
but might spend my strength and the remainder of my time in my blessed Master`'s service;
either in bearing the requisite share of baptism for myself and for the sake of others,
or in more openly advocating his glorious cause of truth and righteousness in the earth.

15th. I have felt concerned for the lapsed, mixed state of the church.
I have seen a spirit at work among us,
which aims at drawing the minds of many from a simple dependence upon
the internal guidance of the Head of the Church,
and is opposed to the administration of sound discipline.
It is very ready to judge the ministry of substantial Friends,
while it pleads for that which is supported with money,
and stands in the will and wisdom of man.
We are weak enough already, but propagating unsound opinions,
neither contributes to our own good nor that of others.
As certainly as we forsake the secret sense which the
Truth begets in relation to our individual duty,
and depend upon the wisdom and the reasoning of man,
our ministry will become destitute of the quickening power and virtue of the Holy Spirit,
and the Society dwindle into lifeless formality.

I have continued attending the meeting to which I belong,
without feeling any inclination to go to any other in the city.
They have not been without instruction to myself,
though I have not felt it to be right to impart
the exercise which has come over me at times,
until this morning, when the impressions attending a little opening were such,
that I was induced to offer it.

26th. There are many pollutions in the world with which we are liable to be denied,
through unwatchfullness, or disobedience;
but the Lord of life and glory will not dwell in a defiled heart.
How necessary then to submit to his purifying baptisms--that of the Holy Ghost and fire;
and when in his unspeakable goodness,
He has cleansed and prepared the heart a fit temple for his Holy Spirit to dwell in,
let us be very careful how we defile it.
"`If any man defile the temple of God, him will God destroy.`"

"`One day is with the Lord as a thousand years and a thousand years as one day.`"
There is no haste with Him in carrying on his work;
and in order to witness the accomplishment of his gracious purposes concerning us,
we must learn to dwell in the faith and patience of the saints.
Christ Jesus is the blessed author and finisher of the saints`' faith;
He will furnish with sufficient light to discover our respective duties,
and as we humbly follow his leadings, will carry on and perfect his work,
to his own praise and our everlasting peace.

Twelfth month 31st. On the 29th, about two o`'clock in the afternoon,
died our beloved friend, Sarah Wilson,
(wife of Edward,) a minister and member of our Monthly Meeting.
She was taken sick on the 26th, and on the 28th became alarmingly ill, and sank very fast.
Her mind was kept in a tranquil state,
and with much composure she took leave of all her family.
Richard Jordan, who was strongly attached to her,
I understood was present at her departure,
and afterwards said he thought he had never witnessed
such feelings of solemnity and awfulness,
as on that occasion;
accompanied with an indubitable evidence that she was received into
the arms of her Savior in the mansions of everlasting blessedness.
She was possessed of a mild temper and affable manners--
cheerful though not light--dignified in her deportment,
yet truly humble, and manifesting a sympathizing spirit towards those in affliction.
Her gift in the ministry was precious--her appearances were not frequent,
but attended with a degree of baptizing virtue,
and evidently the product of heartfelt exercise on account of those,
to whom her divine Master put her forth to minister.
We might have expected from her age and health, and her qualifications for usefulness,
that at this time of weakness in the church,
and departure of many from a steady submission to the yoke of Christ,
she would have been continued long to occupy her
valuable gift and talents in helping to guard the flock,
and to build up the waste places of Zion.
But He who made her what she was, has in his unsearchable wisdom,
cut short her work in righteousness,
and although the privation of her society and labors has been painful to us,
it must be her gain.
We have our day`'s work to perform,
and to endeavor to have our lamps trimmed and loins girded.
Waiting daily upon our Lord to know and to fulfill his will, is our individual duty;
and happy will it be when the end comes, to have a well-grounded hope,
from the testimony of the Holy Spirit,
that a place of glorious rest is prepared for us through the
unutterable mercy of God in Christ Jesus our Lord;
having walked in faithfulness to his divine requirings.
