== Chapter III

1819--1823

Waiting before the Lord--Visit to Ohio--Unsound Sentiments of Elias Hicks--
Necessity for Watchfulness--Family Visit--Duty of Keeping in True Patience--Severe
Illness--Desertion and Distress--Trial of Faith--Letter from a Friend--Acknowledged
as a Minister--Yearly Meeting Discouraging Fears--Ranterism in New England--Spread
of Unsound Doctrines--Testimony of J. Whitall--Reflections on the State of Society.

1819,
First month 10th. There is a material difference between what we call good thoughts,
and being brought to sit under the teachings of Christ in our own hearts,
when assembled for divine worship.
His words are spirit and they are life to the soul;
but the wanderings of the mind in contemplating religious truths,
without the influence of his Spirit, must end in barrenness and poverty.
Hence it is our chief business to labor to get to a state of humble waiting before Him,
that we may be instructed by the gracious words that still
proceed from Him in his spiritual appearance in the heart.

Fifth month 2nd. It is a great favor to be
redeemed from all outward and human dependence,
and to have the mind brought simply and singly to wait upon God.
In a state of reverent silence before him,
He is at times pleased to manifest himself by the diffusion of his light and love,
and the soul being clothed with gratitude to the Author of all its sure mercies,
is enabled to worship as in his presence,
and to offer up thanksgivings and praise to his great name.
Herein is experienced the communion of saints as at his table,
a participation of the body and blood of Christ.
The soul is nourished and strengthened not only by the
living virtue immediately flowing from the Head,
but is edified by that strength which every joint supplies,
by the effectual working of the measure of Grace in every part of the body.
These views opened before me this morning, but for lack of coming to a state of humble,
patient waiting, I did not fully realize them in my own experience.

Latterly this has been nothing new--but perhaps the period is not far distant,
when I shall be again restored to a more steady
and sensible enjoyment of this blessed communion,
so essential to our spiritual life,
and the successful maintenance of the Christian warfare.
Oh! the necessity of keeping the faith in times of stripping and desertion.
Without it we shall be overcome by temptation, rather than be made conquerors.

Sixth month 11th. After a time of silence for several months, on fourth-day the 9th,
I again apprehended myself called upon to communicate
some matter which was opened before me.
Like many other presentations, I had doubts whether it was designed for others,
and nearly concluded I should leave the meeting in silence;
but after attaining a state of resignation either to speak or to be silent,
all doubt was removed, and I was enabled to offer what came before me,
with calmness and a degree of innocent boldness.
I make these memoranda for my own use at a future period of life, should it be prolonged,
that on looking back I may see how I have progressed from one time to another.

There are many lessons to be learned in silence as well as in speaking,
and to be brought into a state of childlike docility,
and obedience to the leadings of our heavenly Shepherd,
seems to be the principal end of all the dispensations of his wisdom.

The haughtiness of man must be laid low,
and the Lord alone exalted in that heart which is
prepared to be acceptably engaged in his service.
In a state of deep humility and patient waiting upon Him,
we become prepared to discern the motions of his Spirit,
and in simplicity to yield compliance therewith.

There is as much need to learn to be still, and to know the active,
forward disposition of the human mind reduced to subjection,
as there is to experience a willingness wrought
to perform the Lord`'s will when it is manifested.
He is a wise Master Builder, and if we abide under his preparing hand,
He will fashion us into vessels and instruments for his use.

Ninth month 26th. Having had some views of attending Ohio Yearly Meeting,
and being desirous of seeing a beloved sister-in-law, I set off the 17th of last month,
for Zanesville, to which town she had removed with her husband last winter.
I got there on the 28th, after a lonely ride through a country altogether new to me,
and remained with them five days.
I set out homeward for Mount Pleasant,
and on the way came up with a Friend residing in that State,
who was going to the Yearly Meeting.
It was pleasant to foil in with a Friend, though a stranger to me,
and we kept in company throughout the remainder of the journey there.
I went to a public house,
but was soon comfortably provided for at a Friend`'s house in the village.
I attended the sittings of the Yearly Meeting,
which were accompanied with a good degree of solemnity.

They had been engaged in revising their discipline, which was read and adopted.
A proposition to divide the Yearly Meeting,
which had been under consideration for two years, was dismissed,
from a belief that the time for such a measure was not yet come.
This conclusion appeared to be unexpected by many,
but such was the evidence of its propriety,
that Friends generally expressed their satisfaction with it.
This opportunity furnished fresh evidence of the goodness and care of our Holy Shepherd,
who watches his flock by night and by day, and in the needful time, as He is waited upon,
manifests himself for its preservation.
Several Friends from the eastern Yearly Meetings were present.
I returned home, having been absent five weeks and four days.

Vessels must be emptied before they are prepared to be filled; and not only emptied,
but cleansed.
This is especially the case with the vessels of the Lord`'s house.

Tenth month 11th. Attended the Monthly Meeting of Haddonfield,
in which I had a little service.
It was accompanied and concluded with peacefulness.

Eleventh month 2nd. Elias Hicks having been in the city six days,
went out to Germantown this morning.
The meetings where he was present have been very large.
The variety and novelty in his communications excited much curiosity,
a great deal of remark, and perhaps, in some instances, disgust.
He is bold in assertion, extensive in his ranges,
and not infrequently appears inconsistent with his previously expressed opinions.

I was tried with his manner of treating the
doctrine of the Three that bear record in heaven,
in one of his testimonies at Mount Pleasant, Ohio.
In speaking of the new birth in man, as effected by the Holy Spirit, he said,
here is Father, Son and Holy Ghost;
which according to the manner in which he and his adherents applied Scripture,
appeared to me to be designed to draw away the mind from a
sound belief in the Three that bear record in heaven,
and fasten upon his hearers the idea that in no other way are
we to believe in the Son of God than as the new birth in man.
I spoke to him as we walked from meeting over to Jonathan Taylor`'s,
and remarked that it appeared to me he had not
held forth the faith of Friends in our Savior,
as he is glorified at the right hand of the Father.
He turned away from the subject by saying,
"`The Apostles were often misunderstood;`" but he
avoided giving any further explanation of his opinions,
as we might suppose a man would do who was not afraid of being detected,
and really held and wished to advocate the doctrines of our Savior and his Apostles.

It is a favor amidst the noises and confusion there are in the
world to feel something on which we can rest with certainty.
As we labor to dwell near the Truth in our own hearts,
this is at such seasons more eminently experienced,
and its advantages more correctly prized.
"`My sheep,`" said Christ, "`hear my voice and I know them, and they follow me;
and I give unto them eternal life and they shall never perish,
neither shall any pluck them out of my hand.`"
He is still the Bishop and Shepherd of his flock;
He still feeds them by day and keeps them by night;
He causes them to feed in green pastures, the pastures of life;
He makes them to lie down beside still waters.

This is a state of true peacefulness,
the enjoyment of that peace which passes the understanding of man, and of which,
as we abide under the shadow of his wing, the world and all its commotions cannot rob us.

Eleventh month 5th. I attended the meeting at Springfield yesterday,
where I was impressed with the belief it was right to
communicate some matter which opened before me;
but on sitting down an inquiry was raised in my
mind whether I had not better have kept silent.
I could not perceive any uneasiness that convinced me I had erred,
and therefore concluded the sensation of desertion was best for me,
though not pleasant to the creature.
It is a humbling, mortifying work; but if we are preserved in the Lord`'s hand,
not running without his command, nor lagging behind our guide, it will be enough;
and when He sees proper, He will give evidence that the work is his,
and that as we faithfully submit to him in all things,
He will perfect it to his praise--at least this is my sincere hope and belief.

Eleventh month 16th. The instances that have occurred of persons who began well,
but afterwards made shipwreck of faith and of a good conscience,
are subjects of mournful reflection, both for their`'s and the great cause sake.
Under feelings of love to our Heavenly Father, we may at times be ready to conclude,
that we are resolved to Follow Him and shall no more forsake him.
The power of temptation is often strong and potently pressing, and although, so far,
we have been kept from being cast away, yet unless the watch is maintained;
and we are frequently brought to feel our need of daily help,
and that of ourselves we cannot stand,
and thereby are led to cry unto the Lord for preservation,
we may be overtaken in an unwary hour,
and carried by temptation into a land of pits and snares,
from which we cannot easily escape, and may bring upon ourselves deep suffering,
and reproach on the holy cause we had espoused.

The growth from infancy to manhood is by slow and almost imperceptible gradations;
as we advance in religious experience by little and little,
so by a gradual neglect of watchfulness and prayer,
we may decline and finally lose our standing in the Truth.
How important then frequently to remember the rock from which we were hewn,
and the hole of the pit from which we were digged.
It was not our own arm that effected this, but His who saw us in a state of corruption,
and in mercy said unto us, live!
Oh let us lie low before Him, and above all things desire, that in heights and in depths,
He will be pleased to keep us in the hollow of his holy hand,
and by the cleansing operations of his baptizing power,
qualify us for the performance of our allotted service in his church militant on earth.

Eleventh month 17th. When the Master directed Simon and his companions to
launch out into the deep and let down the net for a draught;
thinking perhaps it would be unavailing, he replied,
that they had toiled all the night and had taken nothing; nevertheless,
at your word I will let down the net;
and complying with his direction when and where to cast it,
they enclosed a great multitude of fishes.
If this is figurative of the Christian`'s duty and experience, it shows that our exertion,
independent of Divine direction and aid, will prove unavailing that we must,
notwithstanding, be prepared to receive the command of our divine Master,
and that by obedience we shall not fail to obtain that
heavenly food which will nourish and sustain the soul.

Twelfth month 26th. Last fifth-day I attended Green Street Monthly Meeting.
It required some exertion to get through the discouragement presented in the way;
but I was satisfied in going,
as it furnished an opportunity of viewing some of the defects,
and the lack of a lively zeal in some--a worldly spirit having so gained the ascendency,
that many do not see, or view with much indifference,
the degeneracy that has overtaken us.

Others having become accustomed to this state of things,
although they sometimes show some concern for the support of Truth`'s cause,
yet in a general way,
they seem to have scarcely energy to make any
opposition to unsound measures and conclusions;
and thus they drag along, keeping up something of the form,
without knowing the power to be in dominion.
A little service in the second meeting,
opened the way for me from under a cloud which had rested on me for several months.

My way was shut up during that period for any public service,
although I was frequently favored with instructive
openings in relation to the Christian warfare,
and would be almost ready to conclude they were designed for others;
but as I kept patiently waiting for a satisfactory evidence, they gradually disappeared.

These dispensations are comparable to a state of death and burial:
out of which nothing but the same quickening power that reanimated Lazarus,
can raise the soul and qualify it for service in the great cause;
and this He will certainly do, as we endeavor to keep the faith,
waiting upon Him for his appearance.
"`I am the resurrection and the life; he that believes in me, though he were dead,
yet shall he live; and whosoever lives and believes in me, shall never die.`"

The life of these, though not visible to themselves, is hid with Christ in God;
and in these seasons, some may be ready to conclude,
as Martha did respecting her brother, that all hope of restoration to life is lost,
and by this time they have become offensive.
They may suppose that Divine Goodness has seen them unworthy of his gifts,
and consequently He has wholly taken them away.
But let none of the tribulated followers of Christ cast away their confidence in Him.
Although He is called the Lord that hides his face from the house of Jacob,
He has never said to his wrestling seed,
"`Seek you my face in vain;`" but when the end of these necessary baptisms is attained,
He will again appear to their unspeakable comfort, renew their faith,
and clothe them with fresh qualification to sing of his mercies and of his judgments.

1820+++.+++ Third month 30th. The Monthly Meeting having been
brought under religious exercise on account of the frequent
absence of some of the members from many of our meetings,
believed it right to separate a few Friends to take the concern in charge,
and as was opened to visit the objects of it.
When we sat down together, a sense of our weakness and poverty was felt;
but believing that as our dependence was steadily placed upon Him who declared,
that if two of his disciples agreed touching anything they should ask in his name,
it should be done for them of his Father,
He would grant the requisite ability to discharge the duties He required of us,
we proceeded in making the necessary arrangements for the performance of the service;
and so far as I have been a witness, there was reason for humble thankfulness,
for the timely manifestation of his goodness, in covering our hearts with love,
and furnishing matter for the different states of the visited;
with whom we were favored with some seasons of great tenderness.

Sixth month 11th. On reviewing our progress in the above-mentioned visit,
I believe it was peculiarly useful to myself.
It afforded an opportunity of experiencing the gentle openings of Truth,
at times when nothing else could supply ability
to discharge the service which was laid upon us;
thereby strengthening our confidence in the alone Arm of saving help,
and showing that however destitute we may feel,
as we are rightly introduced and engaged in his work,
He will not fail in due season to show Himself strong on the
behalf of his children whose trust is in Him alone.
He will string their bow and cover their heads in the time of every battle,
and cause them to rejoice in his unmerited goodness and condescension.
Oh! that all who are employed in his service, would hold fast their confidence,
not daring to go forth without the evidence of his preparing power,
but firmly possess their souls in patience until the evidence is given;
and then their bow would not be turned backward,
nor would they fail to perform the work to which He has sent them.

For lack of keeping the word of the Lord`'s patience,
how are many warming themselves with sparks of their own kindling,
and thereby not only reaping the reward of poverty and sorrow,
but bringing into disrepute the precious cause,
and the dignified office of a Gospel minister,
in which they profess themselves to have a part.
Neither the most extensively gifted, nor those of the largest experience,
have anything of their own to communicate which can really profit the people.
All must reverently wait upon Him, without whom they can do nothing;
and it is only as He opens the spring and causes it afresh to flow, that any,
the least or the greatest, are authorized and qualified,
to attempt to minister to the states of others.

Sixth month 18th. The Meeting for Sufferings was held on the 16th, which I attended,
having been appointed by the late Yearly Meeting to supply a vacancy.
It was an interesting occasion.
The degree of responsibility which is attached to that body is weighty.
They seem like the guardians of the principles and character of the Society,
in relation to its publications,
and its appearance before the world in vindication of our civil and religious rights,
and the rights of the oppressed who are unable to plead their own cause.

Seventh month 16th. Several weeks past have been a time of
much stripping of all qualification for religious service.
Such seasons are abundantly necessary for me,
in order that I may from real experience and feeling,
become effectually convinced that He who puts forth his own sheep and goes before them,
is the only Source from which ability can be derived for any good word or work.
Nothing so indelibly stamps the conviction of this,
as the withdrawal of his sensible presence.
When this is the case, our situation resembles Mount Gilboa,
where David wished there might be neither dew nor rain, nor fields of offering.

Those seasons would no doubt be shortened if we adhered
faithfully to the Captain of our salvation.
But how apt are we to become weary of a state in
which all our building seems to be taken down,
and all capacity that was heretofore furnished for the work seems to be almost lost.
Were it not for a secret confidence in the Lord`'s unfailing goodness,
the hope of its restoration must be entirely abandoned.
He that walks about as a roaring lion, seeking whom he may devour,
is also not lacking in attempts, through his subtle insinuations,
to destroy the love and unity which has been felt with the brethren,
and which seems the only remaining stay to the tossed mind.
But all bitterness and evil surmising must be purged out,
and we brought to dwell under the covering of that charity which thinks no evil,
and enables to bear patiently the reproaches or unfavorable opinions of others.

Eighth month 21st. Until yesterday I had been silent in our meetings, nearly three months.
My mind has not, through that period, been without encouraging and instructive openings,
but I did not feel authorized to communicate them;
although sometimes almost ready to conclude they
were designed for others as well as myself.
But carefully waiting for a satisfactory evidence of this,
they have been gradually withdrawn,
and the persuasion has generally remained that silence was properly my duty.
Sometimes I thought perhaps I should no more be called on to expose myself in that way,
though I had no reason to doubt the propriety of my previous steps in this work;
yet the floods of temptation were such,
that I had not always kept the faith so as to have my thoughts
sufficiently brought into captivity to the obedience of Christ,
and therefore I should not be favored with a qualification to
advocate the power of Divine Grace in enabling to resist temptation,
and thus tread down the enemy in all his approaches.

Purity of heart is unquestionably a necessary preparation for the Lord`'s work;
and it is an abominable sentiment that a man may
be a minister and servant of Jesus Christ,
while he is trampling upon his holy law written in the heart, serving his own lusts.
We must in a good degree experience the work of regeneration,
before we can expect to be entrusted with his gifts for the edification of the church.
After He has given the gifts, if any man sin we have an advocate with the Father,
even Jesus Christ the righteous, who knew no sin.
In his adorable condescension, He is pleased, upon unfeigned repentance,
to blot out our misses and transgressions, restore us to his favor,
and again clothe with authority to preach the glad tidings of the gospel of salvation.

Ninth month 27th. Several weeks past a malignant fever has prevailed in this city,
which proved mortal in most of the cases.
They were not numerous,
yet it was found necessary to remove the inhabitants
from the neighborhood where it first appeared,
and to fence in the district.
It was a little distance from my store, and on the night of the 26th of last month,
I was attacked with the disease, and confined about twelve days,
greater part of the time to the bed.
Reflecting upon the uncertainty of the result,
and the instances of my unfaithfulness which presented, my situation felt truly awful.
I remembered the description of those who had eaten and drunk in the Lord`'s presence,
partaken of his teachings, and had cast out devils, and performed many wonderful works;
but for lack of keeping their integrity to the end,
received at last the awful sentence of separation from his holy presence.
I seemed to be in company with the spirits of those unfaithful servants.
The sun was turned into darkness and the moon into blood,
the heavens passed away like a scroll,
and every mountain and island was removed out of its place.
The beams of the Sun of righteousness were entirely withdrawn,
and the sentence of death seemed to have gone forth.
All my former experiences were perfectly obliterated,
and there appeared nothing left upon which I could ground any hope of happiness.

After passing several days of darkness, distress and uncertainty,
a glimmer of hope that this was a dispensation for my refinement,
was produced by the presentation of those expressions: "`The kings of the earth,
the great men, and the mighty men, hid themselves.`"
I saw that everything "`high and lifted up,`" had now disappeared,
and I was ready to surrender all that the Lord`'s controversy was with,
if I should be again entrusted with time to perform the
duties that yet remained to fill up my allotted measure.
I think I never passed through a season,
wherein every feeling of Divine good was so entirely removed.
After some time, my hope and confidence in Divine mercy were gradually restored.
Some passages of the Scriptures were opened, and the views I was again favored with,
of the humility and purity indispensably necessary for a minister and servant of Christ,
raised the belief that the Divine hand was still at work.
The language that perhaps "`This sickness was not unto death,
but for the glory of God,`" raised a further hope that I was not cast off;
but that He would again have mercy, and that it would prove the means for preparing me,
more acceptably to come up in his service.
For if these were his fatherly dealings for my purification, though in judgment,
He had not entirely forsaken me,
but in due time would again manifest Himself to my comfort and rejoicing.

A few days after the crisis of the disease, I began to take nourishment,
and when sufficiently restored, went to my brother`'s, at Springfield,
to recover my former strength.

Twelfth month 24th. In the revelations made to the apostle John,
he had a view of those who had come through great tribulation,
and had washed their robes and made them white in the blood of the Lamb.
This vision was corroborative of the testimony of our blessed Lord to his disciples:
"`In the world you shall have tribulation,`" but He immediately adds, "`Be of good cheer,
I have overcome the world.`"
It is in this path the righteous have trodden in all ages,
and it is only by faithfully adhering to the invincible Captain of salvation,
that any of the present or of any succeeding day,
will be enabled to walk in their footsteps.
There are seasons of bitter trial, and dispensations peculiarly abasing,
which are necessary for our humiliation and refinement,
and which we have need to recollect during their operation, are nothing new.
But oh! the reluctance we feel at taking these cups.
How many start aside at the presentation,
and seem determined to walk no more with their Lord.
Such, if they persist, will be cripples all their lives;
they cannot attain to the measure of the stature of the fulness of Divine power,
which He would bestow, where simple obedience accompanies all his requisitions.

In our meeting last fourth-day, the 20th, I felt an intimation to kneel,
which after a time of shrinking, was given up to.
It was such a trial as I had never before experienced.
I was favored to get through,
though under such feelings of great unworthiness and deep mortification,
that afterwards I thought if the elders were to inform me they
were now satisfied I had no part in the ministry,
it would be sufficient to induce me to refrain hereafter from appearing in that way.
Although very little sense of Divine power seemed to accompany my
mind in the performance of what I believed was the Master`'s requiring,
I have not felt anything like condemnation,
but a desire to be more steadily devoted to his service,
that in childlike simplicity I may comply with his commands,
however foolish the work may appear in the eye of worldly
wisdom--this must all be mortified and laid in the dust.

1821, Second month 4th. This morning we had a stranger at our meeting.
In his testimony he told us his mind had been much exercised for several days past,
under a belief that considerable change would be made among us in this place.
Many who were as spiritual fathers and mothers would be removed;
and he wished the younger part of the Society might manifest
the desire Elisha did to continue with his master Elijah,
so as to bear up their hands during their stay amongst us; and that as he did,
we also should be engaged to desire that a double
portion of the good Spirit which had influenced them,
might rest on their successors.

It is consistent with Infinite Wisdom in his dealings with his children,
to strip them at times of the armor which He had furnished for his work,
and to draw their attention to the state of their own minds;
that having been engaged to promote the cultivation of the vineyards of others,
their own may not be neglected.
In this dispensation it is necessary to watch against the feeling of impatience,
so as to be induced to seek after something,
to supply the loss which is experienced by the removal
of that portion of exercise we have had for others,
and in which we have been furnished with suitable matter for them and food for ourselves.
Here it is necessary to keep the faith and the patience of the saints;
in which we shall be enabled to resist temptation,
and be prepared to receive our Lord at his coming,
who will pronounce those servants blessed, whom He shall find watching.

25th. Several days ago,
I had some instructive conversation with my beloved father respecting the ministry,
and the present very depressed state of our religious Society.
The falling away among us of many,
who had been divinely favored with gifts for the edification of the church,
and perfecting the work assigned them,
appeared to me to have produced a slight estimation of these gifts,
and to create the opinion that very little dependence
was to be placed upon those occupying this station;
as such sorrowful evidence had been given of great
instability in some who had made high profession,
and preached much against the defects of others.
He remarked that the degeneracy was not greater than among the Jews;
and yet the prophets, by faithfulness to the Heavenly Leader,
were enabled to stand their ground,
and boldly declare against the corruptions of that day.
That a gift in the ministry was more important than any other.
By living in the gift, keeping daily under religious exercise,
so as to be prepared to act whenever the gift opens any service, and in simplicity,
without creaturely contrivance or adorning, yielding obedience thereto,
we may experience a growth, and be instrumental in building up the waste places of Zion.
On the other hand, if we keep not close to our gifts, we may miss of a growth,
and become the means of introducing a lifeless, windy ministry into the church,
which may bring people into a form of godliness, but without the power.

Fifth month 10th. When we seem a little to have left that
innocency and childlike dependence which is essential to those
who desire to be the faithful companions of a crucified Lord,
He in whom are hid all the treasures of wisdom and knowledge,
sees proper to vary his dispensations in order
to bring back and to show us by experience,
that safety is only to be witnessed through
close watchfulness and entire reliance upon Him.
In our meeting on first-day morning the sixth,
a number of instructive views passed before my mind,
in relation to the fearful condition which those will be found
in who have been living as without God in the world,
when He rises up to judgment and also regarding the
fallacy of cherishing any disposition or practice,
opposed to the humility and self-denial of Christ;
to which seemed applicable his declaration,
"`Every plant which my heavenly Father has not planted shall be rooted up.`"

As has been the case before, these openings disappeared without leaving much impression,
and a time of wrestling with floating thoughts,
in order to get to a place of steady waiting, ensued.
Towards the latter part of the meeting, that expression again came up,
producing the sensation of duty to communicate it,
accompanied with the reluctance to engage in the awful work.
I endeavored to wait for the perturbation to subside, that if anything was said,
it might be with proper deliberation; and when the word seemed to be in my mouth,
I stood up and repeated the above expression of our Savior, with some little addition;
but as I waited in expectation that further matter would be furnished,
as it had been at other times, to my admiration, the prospect died away,
with all ability to say a word.
A declaration of the Most High, respecting his own Divine character presented,
but fearing to utter anything as in his name, without feeling his authority,
and thus be liable to the query, "`Who has required this at your hand?`"
I omitted it and stood silent for some little time,
and then closed with a short observation in reference to the passage I had recited,
and sat down.
I felt quite calm, and, though without seeing how I had missed my way,
concluded the affair had laid me open to criticism, and perhaps just censure;
but I believed it best to submit quietly to all the consequences;
not doubting that if I labored to keep near to Him whom I desired to serve,
it would prove useful in the end.

When an opportunity occurred, I made the enquiry of my beloved parents,
whether they did not think I had missed in some way?
My father, in a tender manner replied, it was best not to dwell too much upon it;
what I had said was not unsound,
and it was our duty to endeavor to keep near to the gift,
and in simplicity to yield to its requiring.
He had found in his services, that to begin low and gradually to rise,
as the opening strengthened, was safest.
This led me to apprehend I had spoken too loudly and strongly,
from a degree of excitement, and that might have been one cause of closing the opening,
if there was no other.
How necessary is it for all who have been in measure cleansed by his sanctifying Word,
carefully to guard against the subtlety of the enemy in all his presentations,
lest they thereby become wounded;
and in the day when they should have on their armor to engage in the Lord`'s cause,
they may find that He is not with them,
as He was wont to be in seasons of greater tenderness,
and more faithful obedience to his will.

After the above event,
I received the following note from a tender-feeling Friend in the ministry:

'`Dear Friend,

If I was capable of feeling with you this morning,
I supposed the opening closed unexpectedly;
and am free to tell you it has several times been my case: when I have risen,
as I thought in the clearness, the opening has suddenly closed,
and I have taken my seat in much self-abasement,
and been brought into deep searching of heart.
But as I have endeavored to yield myself to the all-wise disposal of Him,
who knows the motive for action better than we know it ourselves,
I have found them instructive lessons.
He condescends to make use of the means best calculated to humble our proud natures,
and promote our purification,
and furtherance in the way and work whereunto He has called us;
making us fully sensible from where comes our sufficiency,
that we may draw all our supplies from the alone sure Source of strength and consolation.

For verily the applause or the reproaches of men,
will avail but little in the hour of trial.
I feel my own littleness, and am aware that my experience is small,
but desire your encouragement and preservation in the Truth.

Your affectionate Friend,

S+++.+++ H.

27th. Living near the river,
I have often observed great care is taken by the seamen when they come into port,
to secure their vessels properly at the wharf.
While they are thus riding in deep water, although high winds may arise,
creating much agitation in the unstable element, they remain uninjured.
Equal caution is manifest when they are about taking their departure.

All parts of the rigging are put in complete readiness; the fasts are gradually loosened,
and the proper time is watched to detach the last mooring,
in order to guard against running in contact with other vessels,
and thereby damaging themselves and others.
When they have satisfactorily made the stream,
the commands of the pilot must be strictly
observed to keep from grounding on either shore.
This caution is necessarily observed in vessels of all dimensions,
in proportion to their size and importance.
These circumstances conveyed instruction to me on the subject of the ministry.
When the mind is in a state of rest,
the first openings of Truth may produce a slight
impression of the service to be performed;
or an introduction into a painful labor after the life of Truth,
under a conviction of our inability to do anything for ourselves or others,
may tend to let the mind down into a view of its own weakness.
These sensations seem like loosening it from its moorings,
and beget a willingness to do anything that the Lord may require.
Sometimes these openings are taken away and seem lost,
and are followed with the apprehension they will not reappear.
But He in whose hand the work is, knows when to put forth his own.
He gently brings the concern up with more life and clearness,
until the word is in the mouth,
and we feel released from all impediment to communicate
what the Lord may gradually open before us.

If this preparation is not carefully waited for, either the Gospel may not be preached,
or the instrument labor with pain to himself, or to those who hear him.
It is of great importance to wait for, and to move in the Lord`'s time.
Then shall we be enabled, through humble reliance upon Him,
faithfully and acceptably to comply with all his requirings,
in the prosecution of this truly weighty and awful work.

Sixth month 6th. Last week my brother Thomas and myself, went to John Comfort`'s,
in Bucks county, and attended the Quarterly Meeting held the 31st. The lack of faithful,
skillful standard-bearers, who know how to keep their places in patience,
appeared evident.
A meeting may be easily drawn from a solid, gathered state,
by hasty and unadvised interference and creaturely activity.

Seventh month 26th. There are seasons in which it is peculiarly
needful to profit by the exhortation of Paul to Timothy:
"`You therefore endure hardness as a good soldier of Jesus Christ.`"
We cannot suppose he wished him to become callous and
insensible to the natural effect on his feelings,
of those things which are hard to bear, but that he might attain to that state of quiet,
firm standing, in which he could patiently endure them,
without being in danger of making shipwreck and becoming cast away.
When little encouragement is to be derived from others,
and the soul is closely beset with tossing,
and is tempted to apply to the creature for relief and consolation,
how needful is it to feel after a renewal of the invincible faith,
by which we may be enabled to possess the soul in patience, and to stand still,
confiding in the eternal arm; in the belief that according to his ancient goodness,
the Lord will appear in due time for our help,
and enable us to tread Satan and all his presentations under foot,
and to ascribe unto the Lord God, the power and the glory,
and the right to rule and to reign in the hearts of all his rational creation.

Ninth month 9th. Within the last two months I have passed through several close trials,
which I hope terminated to my advantage.

The enemy of all righteousness seeks to destroy
the precious birth which is of Divine begetting.
It matters not to him by what means and unless those who are
the disciples of Christ keep steadily upon the watch,
he may even delude them under the pretext of religious
concern for the preservation of an individual,
to speak of his defects, or to represent actions which he has done innocently,
in such a manner to another, as to create an unfavorable prejudice against him,
and thereby block up his way for the free exercise of his gift.
What mischief would be prevented, if the Divine exhortation was always complied with,
under the clothing of a restoring spirit: "`If your brother shall trespass against you,
go and tell him his fault between you and him alone.`"
Many surmises respecting actions and motives would prove unfounded,
and the precious unity of the Spirit be preserved and strengthened.
But through all my besetments and plungings, gracious Goodness was near,
and manifested itself for my help; and when the tempest beat high,
at times the Master commanded a calm;
furnishing renewed ability to rise above all the swellings and raging of the enemy,
and to put my trust in Him alone, who tenderly watches over his flock,
and preserves it by day and by night.

16th. The goodness and mercy of our Heavenly Father are
often manifested in visiting us with his love and life,
even at times when we have not as faithfully kept his command as we should;
giving us a share of the work in his vineyard,
and thereby engaging us to bow before Him in gratitude and humility.
What cause have we reverently to acknowledge his long suffering and kindness toward us,
in plucking our feet out of the miry clay,
and setting them upon a Rock that is higher than we, again establishing our goings,
and putting a new song into our mouths,
even praises to his great and everlastingly worthy name.
I feel desirous to increase in dedication and obedience to Him;
so that everything that denies may be escaped,
and my heart be made and preserved a temple for his holiness to dwell in.

1822,
Second month 3rd. The Monthly Meeting having recommended me to the care of
the Quarterly Meeting of Ministers and Elders in the Eleventh month last,
after holding the subject under its consideration,
I was yesterday acknowledged a minister by that meeting,
and acquainted with its conclusion this morning, by two Friends,
nominated for the purpose.
No station in the church will exempt us from temptation.
Poverty has been my clothing,
and the evil one has not been lacking in his
presentations in order to draw the mind from the watch,
and render it unfit for the reception of heavenly good.

Third month 1st. The ministry of the Gospel is a deep and weighty work.
Many baptisms and mortifications are often necessary,
to prepare the creature to minister altogether from the gift,
and unreservedly to attribute the praise and the
power to Him from whom alone it is derived,
and to whom it belongs.

These dispensations are ungrateful to our natural feelings.
Abasement and insufficiency in ourselves, manifested to the view of others,
seem the opposite of that ability with which the creature delights to be furnished,
and which the great Head of the church, at times, graciously affords,
but for wise purposes, also sees proper to withhold in a great degree,
even when a necessity is imposed to stand forth in the work.
In such case it is difficult to see the right stepping stones;
and if we do not abide under the cross, we may utter what He does not give;
which confuses the mind, exposes our impotence, and fails to profit the people.
I think this was my own case, in some measure, about two weeks back.
It had a humbling effect, producing conviction of my utter incapacity for the work,
only as the Lord is pleased renewedly to endow with
fresh qualification and matter for the service.

Fourth month 21st. During the past week was held our Yearly Meeting.
On the previous seventh-day I attended that for ministers and elders,
the first Select Meeting I have sat in.
The answers to the queries would indicate a sound substantial ministry among us;
but it is sorrowful to believe that they do not all give a just view of its state.
There is much passed off upon the people for Gospel ministry,
which is no better than the divination of man,
having its origin in his will and contrivance.
Many are deceived with it,
for lack of having access themselves to that which is within the veil,
and would give a true sense of what is, and what is not of the pure Truth.

While the minds of people are outward, looking for words,
and ministers are not careful steadfastly to keep in their tents,
until the true Shepherd puts forth and goes before,
but are seeking to gratify the itching ear and their own unruly tongues,
we shall have a ministry of words;
which though amusing to the multitude and tickling the vanity of the preacher,
will eventually land both in confusion and barrenness.

Our beloved Friend, George Withy, from Frenchay, near Bristol, England, was with us,
and faithfully bore testimony to the ancient foundation
on which the Church of Christ is built,
and to the doctrines of the everlasting Gospel;
cautioning Friends against airy flights into the region of speculation;
and declaring that however some may soar, as among the stars,
or build their nests as with the eagles, the Lord in his time would bring them down,
and lay their honor, (if honor it might be called,) in the dust.
It was now a time of peculiar trial, permitted to come upon us;
but as we dwelt in the everlasting patience, the time would again come,
when the Lord would take his work into his own hands, and it should again be said,
"`The Lord`'s power is over all.`"

We got through the business of the meeting for discipline in a pretty satisfactory manner.
In all the sittings a degree of weight and solemnity was felt,
although in one a spirit of darkness got up, through the unadvised interference of a few,
as well as the unsavory doctrine one of them held forth.
Several important subjects were brought before the meeting.
A committee, which had been appointed to visit the Quarterly and Monthly Meetings,
made an explicit report of the state of things within our borders,
exhibiting evidence of great declension from the life and power we make profession of.
The propriety of endeavoring to advance our testimony against the distillation,
trading in and retailing of spirituous liquors,
was called into view by a minute from Maddonfield Quarterly Meeting,
and the subject was recommended to the weighty attention of subordinate meetings,
which were desired to report the result of their labors.

Seventh month 17th. Under an apprehension it would be proper
for me to attend the meeting at the Twelfth Street house,
last first-day morning, I went to it.
It was a trial, but being desirous to be wherever it was my place,
I gave up to the impression, though not without various thoughts how it might terminate.
In the course of the meeting,
there seemed to me much lack of a real sensibility on
the important object for which we had convened.
The minds of some seemed outward,
and destitute of that travail and exercise of spirit which must be maintained,
in order to experience the arising of Divine life and virtue in themselves.
As these thoughts and sensations continued with me much of the time,
I believed it right to stand up, and as it might be opened before me,
express the views we hold of the nature of Divine worship,
and the requisite preparation for its right performance.
There was something of the openings of Divine life experienced;
but not keeping sufficiently low, I got, as I apprehended afterward,
a little from the gift, and expressed a sentence or two, which though sound,
yet lacked the savor of life;
and on sitting down I was apprehensive that very little
baptizing influence had accompanied my testimony.

I was almost a stranger in the meeting, having but seldom attended it,
and felt mortified and concerned lest I was
instrumental in ministering to a state of death,
painful to those who are preserved alive in the Truth.
On returning home and reflecting upon what had passed,
I gave way to the suggestions of the evil-one to such degree,
that I became carried away with his insinuations.
My pride was mortified with the belief,
that those at meeting must have seen my inability for the work,
and I concluded it was evident I was unfit for the ministry.
Under much distress, and fear lest I might be drawn from the true foundation,
my secret petitions, through an interval of tenderness, were put up,
that He who only could preserve from falling, would be round about,
and still keep the swellings of temptations from overpowering me.
I hope the instruction conveyed under this occurrence will not be soon forgotten.
The repetition of such is very undesirable to the unmortified pride of man,
and doubtless would be less frequent if we dwelt in the valley of humility,
keeping a watch over that tendency in us to be exalted by the favors conferred;
not to feed our pride, but for the honor of his great Name who immediately bestows them,
and for the advancement of his cause in the earth.

About a week afterward I met a beloved elderly Friend,
and told him of the distress I had passed through,
from the apprehension that my appearance at their
meeting was not accompanied with the savor of life,
as gospel ministry ought to be.
He was very tender of me,
and gave me to understand that it had not given him any uneasiness.
So I hoped that, in part, my distress had been produced through the buffetings of Satan.

Ninth month 17th. In the course of the last five years,
a few members of our religious Society in the Eastern States,
having indulged a disposition to think themselves wise above what is written,
fell into the practice of spiritualizing many parts of
the Holy Scriptures which have a literal meaning.

Differing from their Friends respecting some passages,
and imagining they had attained to greater light and experience,
they pretended that as every one had the light in himself,
their supposed revelations were not to be submitted to the judgment of others,
as any criterion of their correctness.
Their pretensions were plausible in the view of those
who were unacquainted with the delusions of Satan,
and as they could make long speeches with feigned words and high sounding sentiments,
they deceived some into the opinion that they were to revive
the ancient principles and spirituality of the Society;
from which, they averred, it had now lamentably degenerated.
At first their real sentiments were much concealed;
but as they became exalted in their own conceit, and the childlike state,
in which alone there is safety, was lost, they grew more bold,
their errors more apparent, and they denounced the Society generally, as corrupt;
and some went so far as to pronounce individuals as cursed.
They were labored with by their friends for their preservation and recovery,
but to little effect; they alleged that they could see the states of others,
but such were their attainments, that others could not comprehend them.

All kind of restraint was irksome.
They pronounced the discipline mere tradition,
and useless to those who had a spiritual guide;
meetings of ministers and elders were compared to synagogues of Satan,
where the power and influence of mystery Babylon were peculiarly exerted.
Thus a disposition was openly manifested wholly to disregard the order of the Society,
and to set at defiance the government and subordination which must be maintained,
to preserve a religious body from anarchy and confusion.

Several of those people having run out in principle, and in their unbecoming conduct,
given great disturbance to some meetings, they were finally disowned.
But the delusive spirit which actuated those persons,
was not slain or banished from our borders.
It is covertly at work in other Yearly Meetings, sowing the seeds of disorganization,
and laboring to destroy the faith of the members
in the fundamental doctrines of the gospel,
as laid down in the New Testament,
and professed and fully believed by our religious Society from its rise.
And what adds to the mournful consideration, is,
that many who have been divinely visited, and in measure obedient to the visitation,
do not believe this to be the case; but are giving their strength to that spirit,
which it is much to be feared has gained the ascendancy
in some persons of influence in the Society.

Efforts have been made to lay waste the faith of Friends,
in the divinity and atonement of our Lord Jesus Christ,
and in the Divine authority of the Holy Scriptures;
doubtless for the purpose of destroying them as a test of doctrines,
and to make way for the introduction and more easy spread of infidel sentiments.

The qualifications and authority, which through long faithfulness to the Truth,
have been given to some by the blessed Head of the church,
for the care and edification of others, are by these unsound and disaffected members,
considered an arbitrary assumption of power.
Although well acquainted with the leadings of the true Shepherd,
if such experienced Friends unite in opposing the disorganizing
attempts of the enemies of wholesome government and sound doctrine,
they are considered as dangerous to the religious liberty of the members of the Society;
while their concern and labor are designed to guard it
from licentiousness of principle and practice.

It is a time of peculiar trial,
in which it is truly needful for every sincere-hearted
disciple to have his loins girded and light burning,
waiting and watching for the coming of his Lord.
Unless our hearts are kept pure and faithful to Him,
we shall not be prepared to meet Him at his coming; and it is only when He appears,
that ability is received to advocate his cause availingly,
and to exalt the Truth and its blessed testimonies, over all unruly spirits.

Eleventh month 20th. Last first-day I attended Darby Meeting.
The advantages of a humble, dedicated state of mind,
carefully leaning on the gentle openings of the Shepherd of Israel, were experienced,
to my comfort and the renewal of faith in his goodness and all-sufficiency.

Twelfth month 14th. Elias Hicks having been set
at liberty by his Monthly and Quarterly Meetings,
to visit parts of our Yearly Meeting, and to attend Baltimore Yearly Meeting,
he arrived in Philadelphia the 7th of this month.

The following testimony was drawn up by Joseph Whitall,
a minister who was remarkably well versed in the doctrines of our religious Society,
as set forth by Robert Barclay, and other ancient Friends,
and a most firm and steadfast believer in them:

"`Having attended the last Yearly Meeting at New York, I heard Elias Hicks declare,
in a public testimony, in a large meeting in the North House,
that '`The same power that made Christ a Christian must make us Christians;
and the same power that saved Him must save us.`'
Being very uneasy with the doctrine,
I took a private opportunity to state to him my uneasiness.
I informed him that for several years,
reports had been in circulation unfavorable towards him, and that on those occasions,
I had vindicated his character, from a belief that he must have been misrepresented;
until last fall I met with a piece in writing, said to be from his pen,
in which he called Christ the Jewish Messiah; that He was only the Savior of the Jews;
and that He was not the Son of God, till after the baptism by John,
and the descent of the Holy Ghost.
To this I offered my objections as unscriptural; but he justified them.
He also declared that he considered it a matter of the greatest
encouragement to believe that Christ was no more than a man,
for if he were anything more, it would destroy the effect of his example to him.
He admitted that he had not, till of latter time,
held up the doctrine that Christ was liable to fall like other men.

When I quoted the testimony of John, that the Word was made flesh,
(or took on flesh,) he said it was impossible.
I offered my sentiment, that if he persisted in preaching these doctrines,
so contrary to the Scriptures, and the testimony of our ancient Friends,
it would produce one of the greatest schisms that had ever happened.
He allowed it would produce a schism, but that it would soon be over,
for he believed his doctrine must and would prevail.
Seeing that we differed so widely in sentiment on these points,
I proposed to him to have a few solid Friends, ministers and elders, convened,
that a discussion might be had; but he would not consent thereto;
saying that he was so confirmed in his sentiments, that he should persevere therein,
let the consequences be what they might.`"

Signed, Joseph Whitall.

Philadelphia, Twelfth month 12th, 1822.

On fifth-day, the 19th, E. Hicks attended Green Street Meeting;
said much that was very exceptionable,
as it evidently tended to lower our Savior to an equality with his servants,
and also to lessen the authority of the Holy Scriptures.

Twelfth month 26th. E. Hicks left the city yesterday morning.
It seemed removing a weight of anxiety from our minds,
and if his principles would vanish as easily, the relief would be still more complete.

1823,
First month 5th. It is mournful to reflect upon
the present state of our religious Society,
in many places.
While there is preserved a large body of substantial Friends, many others,
deeply immersed in the love of the world, the desire of ease and outward greatness,
and lacking in religious depth, are degenerated from that purity of heart,
and well-founded zeal for the support of our principles and Christian testimonies,
which so conspicuously appeared amongst our primitive Friends.

Their principles, and testimonies were dearer to them than all temporal accommodations,
liberty, or life itself.
Being preserved in a state of living faith and devotion to Christ Jesus,
their Lord and Master,
they were made quick in discerning the approach of the enemy in his most insidious forms;
and they kept their eye inward to the Lord.
Through his baptizing power,
they were united together in bearing a faithful protest
against the devices of Satan and his agents,
and were thus rendered instrumental in warning and
preserving the flock from his desolating ravages.
But weakness and blindness have so overtaken many at this day,
that they seem scarcely to know their own religious principles,
and not being circumcised in heart and ears, are carried away with the sophistry of some,
who through self-conceit and dependence upon their powers as men,
have gone about disseminating their unsound views;
much to the grief of those yet preserved as a righteous seed,
and greatly to the injury of the inexperienced in the work of regeneration,
and of the general welfare of the body at large.

When we hear that sentiments degrading to the divinity of our Lord Jesus Christ,
and the Divine authority of the Holy Scriptures,
are not only openly delivered from our galleries, and their unsoundness unnoticed,
but contended for as being real gospel ministry, even by ministers and elders,
it may be said the signs of the times are awfully portentous.
What the effects of these things may be, is not yet manifest, though, I believe,
all such persons, with their anti-christian sentiments, will be laid low.
It may be permitted, as a scourge, to go through the Society,
in order to discover the foundations we are severally building upon,
and who those are that prefer Jerusalem to their chief joy.
Certainly, the devastations of this spirit, and its doctrines, will be great,
and the sufferings of those who stand firm against it will be proportionally severe.
But if we can be favored to keep our habitations in the immutable Truth,
the storm will beat against us in vain, to destroy the faith;
and when the tribulation of those days is overpast, like Noah,
released from his confinement, we also,
in a feeling of the abatement of the floods of trial and deep suffering,
will be permitted to offer the sacrifice of thanksgiving and praise,
from hearts contrited under a sense of the Lord`'s goodness and care over us.
