== Chapter IV

1823--1826

Paul and Amicus--Yearly Meeting--Philadelphia Quarterly Meeting William Forster,
Jr.--Richard Jordan--Visit to Washington about the Slave trade--Attends
Baltimore Yearly Meeting--Fatherly Advice--Lack of a United Travail by
Ministers and Elders--Visit to Quarterly Meetings--Yearly Meeting--
Extraordinary Case Related--Letter to his Brother Thomas--Attends Rhode
Island Yearly Meeting--Canonicut--South Kingston--Testimony of his Mother--
Second Marriage--Yearly Meeting--Concern Respecting the Spread of Unsound
Doctrines by Ministers--Nearly Meeting--Attends New York Yearly Meeting.

First month 17th. An adjourned Meeting for Sufferings was held today.
A person with the signature of Paul, having, in the Christian Repository, at Wilmington,
Delaware, addressed the Society of Friends on some doctrinal points,
was replied to by another, "`Amicus,`" declaring himself to be a member of the Society.
After the controversy had been continued more than a year,
the dispute embraced the Trinity, Divinity of Christ, and the Atonement;
and sentiments being advanced by Amicus,
which some Friends believed to be derogatory to our faith,
the subject was introduced to a late Meeting for Sufferings, paragraphs read,
and a committee appointed to take the whole subject into consideration,
and to report what they might judge proper for the occasion.
Their report was now produced, containing a clause, disavowing any knowledge of Amicus,
etc.; to be printed with those essays,
which we were informed are designed to be republished in pamphlet form.
It also set forth our belief respecting the Holy Scriptures, our faith in God,
and in our Lord Jesus Christ, his advent, sufferings, death, atonement and resurrection,
and ascension, chiefly taken from the writings of ancient Friends.

They were agreed to; the former to be sent to the Wilmington editor,
and the latter to be printed in a pamphlet, and distributed through our Yearly Meeting.
The excitement prevailing in our city, and in other places,
occasioned by the visit of E. Hicks, produced fears in some,
of circulating anything of the kind at this time,
and the Meeting not coming to any decision at its first sitting,
adjourned till the afternoon.
On sitting down together again,
the influence of external commotion seemed to have subsided, and Friends were enabled,
under a covering of unusual solemnity, to unite in the foregoing conclusions.

Whatever may have been E. Hick`'s object in his visit to this city, the effects have been,
discord and divisions among Friends.
Old friendships have been dissolved, and new ones formed,
according as persons have agreed or disagreed, respecting his pernicious opinions.
Ministers opposed to them, are suspected to allude, in their ministry,
to particular circumstances or individuals, because of the closeness of its application,
and their way is accordingly much shut up.

Third month 16th. Feeling an impression upon my mind,
I have attended all Friends`' meetings for worship in the city,
and through the condescending goodness of the Shepherd of Israel have
in all of them been enabled to deliver what was opened to me,
pretty much to my relief and satisfaction.
In some it was trying, owing to the lowness of the stream, and perhaps,
some opposition from the party spirit that prevails.
This is at work to subvert the order and principles of the Society,
and to gain an ascendency over those who desire to maintain them faithfully,
in the wisdom and authority of Truth.
The sense of this, and that many, who in years past were preciously visited,
with whom we had fellowship, have now become leavened with this spirit,
and are giving their strength to it, is truly affecting,
and occasions much mourning for them, and for the precious cause`'s sake.

Fourth month 21st. This day commenced the sittings of our Yearly Meeting.
After the reading of the minutes of the Meeting for Sufferings, a valuable,
judicious Friend rose and said he felt more than a liberty to
express his entire unity with the proceedings of that meeting,
and he wished their encouragement.

Immediately after him, a member said, that in regard to that "`creed,
or confession of faith,`" contained in the minutes, he thought it right to say,
"`Who has required this at your hands?`"
This was the signal for opposition; and those extracts from the writings of George Fox,
R+++.+++ Barclay, W. Penn, R. Claridge, and W. Sewell,
containing the most solemn and important truths of the Christian`'s faith,
mostly expressed in Scripture terms, were denounced by some wild, inexperienced persons,
as inconsistent with reason, revelation, and the Holy Scriptures.
It broke out and spread, like a flame among light rubbish.

Many unbecoming expressions were used, both in relation to the doctrine,
and the Meeting for Sufferings.
It soon appeared that much confusion was at hand,
and the Meeting adjourned till 9 o`'clock the next morning.
Nearly three hours were then spent in discussing a proposition to
expunge those extracts from the Meeting for Sufferings`' minutes.
Another person proposed that a committee be appointed to examine and
report their judgment of the proceedings of that meeting.
A preacher residing in this city, joined with this,
and further recommended they should be instructed to
consider the constitution of that body.
He thought a radical change was needed;
the members should hold the office for three years,
and five be chosen out of each Quarterly Meeting.
Another thought the two subjects should be kept distinct,
and urged the expunging of the extracts, and postponing the other to a future sitting.

During this scene of confusion, and unexampled torrent of abuse,
and invidious reflection upon the Meeting for Sufferings,
the members of that meeting remained unmoved,
and patiently bore the unbecoming conduct of many, without making a single retort.
The clerk was several times urged to make a minute
directing the obnoxious record to be expunged,
and one proposed that if he persisted in deferring to do it,
that another Friend should be named to take his place.

At length my father rose,
and gave a concise statement of the institution of that Meeting, and its operations.
He mentioned that the publication of our religious
principles had been repeatedly made by it,
in various ways, and denied the truth of those insinuations of design, on its part,
to impose anything upon the Society; that the extracts were drawn from Fox, Barclay,
Penn and other books, repeatedly printed and owned by our Society, etc.
His remarks appeared to have an effect upon the meeting,
and the clerk stated that he was the servant of the meeting,
and had been endeavoring to discover what was the mind of the meeting,
but from so many propositions and opposite opinions, he was unable to decide, and,
therefore, would suggest that a minute be made,
directing the Meeting for Sufferings not to publish the Extracts.
This was acceded to by some of the leading opponents;
but others more violent openly rejected it,
and seemed determined to be satisfied with nothing short of an obliteration.
The clerk`'s proposal, however, at length prevailed; but some remarked,
that allowing it to remain upon the minutes,
was acknowledging the doctrine by the Yearly Meeting.

This circumstance was altogether a new kind of exercise to some of us,
but it was cause of gratitude,
to be favored with calmness and entire freedom from all irritation.
Indeed, it seemed like being preserved from the strife of tongues,
and hid in the secret of the tabernacle of the Most High.
The remaining sittings of the meeting were generally more satisfactory;
though often attended by a painful feeling of the presence of false brethren.
Our dear friend, William Forster, Jr., from England, in the closing sitting,
was engaged in fervent supplication for the extendings
of Divine regard towards the Lord`'s tribulated children;
and the meeting closed soon after,
under a covering of most solemn and impressive silence,
which produced in my heart the involuntary acknowledgment, we are unworthy of this.

Fifth month 3rd, Was held our Quarterly Meeting of Ministers and Elders.
In the deliberations, a spirit was manifest,
that would overturn the order of the Society, crying out overbearance,
and lack of condescension, in those who felt bound to support it.
The feelings produced by the spread of this spirit are becoming more painful,
and as it gains strength, the love and life of Truth are departing from such.
Many are robbed of their true strength, and they know it not;
but are so deluded as to believe they are engaged in the work of reformation;
while alas! blindness and insensibility have lamentably overtaken them.

5th. The Quarterly Meeting for Discipline got through the
little business which came before it with general harmony;
our friend, William Forster, Jr.,
having much acceptable and appropriate service amongst us.

7th. Feeling much sympathy with our beloved friend, William Forster, Jr.,
in the trying path in which he is led amongst us,
and his way being increasingly discouraging, I was inclined to meet him at Cropwell,
and spend a day or two in his company; as he was about leaving the city,
with the prospect of being absent many months.
Accordingly, in company with our worthy friend, Richard Jordan, I attended that meeting;
in which they were both engaged in public labor.
In the afternoon we rode to Moorestown, and were at the Monthly Meeting there next day.
William was much opened into the state of the Meeting,
and upon several important doctrinal points.
After he had taken his seat,
my mind having been introduced into desire for the preservation of the few still left,
who were given to suffer for the name of their dear Lord and Master,
I believed it right to endeavor to encourage them to stand upon the watch,
that no man might deprive them of their crown;
and that in his own time He would give the victory over our enemies,
even if it be through suffering.
R+++.+++ Jordan followed,
and in a forcible manner labored to show the condescension of the Redeemer,
and the danger those were in, who were crucifying Him afresh,
counting the blood of the covenant an unholy thing,
and doing despite to the Spirit of Grace.
I believe we all left the meeting with heavy hearts,
from the fear that many had been beguiled,
and were in jeopardy of becoming bewildered in the mazes of uncertain speculation,
by following their own unmortified wills,
instead of living under the daily operation of the cross of Christ.

In the afternoon we rode to Josiah Reeve`'s, at Upper Evesham,
where we passed an agreeable evening.
W+++.+++ Forster, Jr., set out next morning for Bass River, and we returned home.

18th. This morning being first-day, I went over to Newtown Meeting,
accompanied by my brother Thomas.
Pretty early in the meeting Richard Jordan rose, and after some introductory matter,
opened the subject of man`'s creation; the purity in which he stood;
the law given for his preservation and his Maker`'s glory;
the penalty attached to the transgression of that law,
and the consequences affecting himself and his posterity.

By sin he lost the Divine life, wherein he held sweet communion with his Maker;
but the Son of God offered himself a ransom for fallen man, to be manifested in due time,
and procured for him the opportunity,
and the means to enable him to work out his salvation.
As in Adam all died, so in and by Christ, shall all be made alive; that is,
all who are obedient to the requirings of his Holy Spirit,
shall be renewed up into the image of God, and made alive unto Him.
The Apostle testified, "`You are not your own, you are bought with a price;
therefore glorify God in your body and in your spirit, which are God`'s.`"

If Adam`'s natural life alone had been spared, he remarked,
he would still have remained in a state of separation from God;
as he possessed no power whereby he could restore himself to
that Divine spiritual life which he lost by transgression;
and, therefore,
the means through which his restoration to the Divine communion was to be effected,
must also have been provided, agreeable to the declaration,
"`He that spared not his own Son, but delivered Him up for us all,
how shall He not with him freely give us all things.`"
"`And because you are sons, God has sent forth the Spirit of his Son into your hearts,
crying, Abba, Father.`"

My mind was brought under exercise,
in feeling the lifelessness and barrenness which predominate among many there;
produced by frequent disobedience,
and despising the many favors which a long suffering God, had from time to time,
extended to them, immediately and instrumentally.
The language was brought to view,
"`You only have I known of all the families of the earth,
and therefore I will punish you.`"
I was enabled to discharge myself pretty fully.
R+++.+++ Jordan appeared in supplication, and I hope some profitable impression was made.

23rd. Having been appointed, with several other members of the Meeting for Sufferings,
to obtain information respecting the foreign trade in the natives of Africa,
two of us set off this day at noon for Washington,
and arrived there in about twenty-four hours.
By the open, frank attentions of the Secretary of the Navy, and several of his clerks,
we had access to the public documents upon the subject,
and made such transcripts as we thought would be interesting and useful,
to show the present state of that horrible traffic; and returned home in about a week.

Sixth month 22nd. Feeling a draft in my mind, I attended the meetings in the city,
and the Monthly Meeting of Frankford.
Some humiliating feelings were passed through, which tended to diminish self-dependence;
but through all, I had reason to believe that the good Hand was still extended,
even towards a rebellious gainsaying people,
to gather them to the teachings of Christ in themselves;
that thereby they might have spiritual food in their own houses,
and water in their own cisterns.

Tenth month 15th. Having a concern to attend the meetings in this city,
I went accordingly to them all, and whatever effect may have been produced upon others,
I derived some instruction in the exercise of the gift of Gospel ministry.
In the first meeting, the matter opened before me, as I thought,
too slowly to be accompanied with the evidence that it was of Divine origin,
which I desired.
Sometimes I was ready to fear I should stop and close in confusion.
But as I endeavored to be composed and steady in my mind, the openings continued,
until I believed my duty was discharged.
I felt calm and peaceful.

The strait into which I had been brought, remained with me several days,
and had a useful effect; and to the close of this service,
I was more and more favored with the Master`'s help, and no doubt,
it tended to enable me to bear these favors, without being puffed up with them, as poor,
weak mortals are too apt to be.
It also increased my dependence upon, and confidence in the Divine openings of the gift;
by which I was enabled to speak more deliberately,
and to avoid alarm when matter did not flow as fast as I wished,
or the sense of power was not as strong as I desired.

We have great cause to put our trust in the great Shepherd of the sheep,
who is altogether sufficient for his own work, and will take care of it and of us too,
as we faithfully follow and rely upon Him.
He will not only put us forth, but go before, qualifying as He shall see meet,
for the work whereunto He has called us, gradually enlarging the gift,
and instructing us in the right use and improvement of it.
On the 13th I attended Haddonfield Monthly Meeting,
where we had the company of Micajah Collins.
It was to some of us a serious time, and we hoped an awakening one to some there.

Eleventh month 6th. Having attended the Yearly Meeting of Baltimore,
with a minute of unity of the Monthly Meeting, I returned home some days since.
Being the first religious visit with a minute, I felt more than usual on the occasion;
desiring I might be preserved from everything, either in meeting or out among Friends,
that would injure any one, or the cause in which I professed to be engaged.
A reserved deportment is an unwelcome restraint to young people,
whose minds are not under the tendering visitations of Heavenly good;
and it is a trial to apprehend that our company produces this kind of feeling in them.
But although cheerfulness, rightly tempered, is at times,
properly the innocent clothing of the devoted mind,
yet there are seasons when we are called to mourning,
and the tongue seems as if it would cleave to the roof of the mouth.
Subjects for conversation vanish, and we sit as objects of wonder or ridicule.

This is mortifying to the pride of our nature;
but it is nevertheless useful to ourselves,
and may be also to some whose conditions we are not fully aware of.
It is not a pleasant thing to be a savour of death unto any,
and unless our sufficiency for these things is derived from above,
we may turn aside into what is not convenient for ourselves or others.
To maintain a steady exercise of spirit, contributes to preserve our own strength;
and may minister a savor of life to some whose souls are secretly bowed,
when their exterior would not indicate such a state.

I think the Meeting was generally favored with the overshadowings of Divine good;
by which the faithful were enabled in good measure to keep down wrong things,
and the meeting preserved in a solid frame.
It was not a time for rejoicing,
as it felt as if the power of Truth rose very little
higher than to keep unsettled spirits in subjection;
while some were clothed with a sense that a
disposition secretly prevailed to change laws,
and customs, and principles heretofore owned and established by the great Head himself.
Indeed, it seemed that unless He who rules with a rod of iron, and dashes in pieces,
as a potter`'s vessel, whenever He sees fit,
should manifest himself in a remarkable manner,
for limiting the raging waves of the sea of unbelief,
our Society will be overspread in this country,
from north to south and from east to west, with the desolating ravages of that spirit,
which is adulterated from the innocent life,
and seeks to draw from the faith and simplicity of the gospel of Christ,
into a dependence upon and conformity with the fallen wisdom of man.
Its baits and snares are many,
generally concealed under the guise of greater spirituality,
and freedom from all entanglement by doctrine and church order and government.
It is very confident of its own,
and ever ready to condemn or lightly esteem the service of others,
who see into its devices and testify against them.

When about leaving home,
my beloved father wrote me a note on something he wished attended to,
to which he subjoined the following useful hints:
"`Attending a Yearly Meeting exposes to much company;
and watchfulness against a great deal of conversation seems peculiarly needful,
lest weakness through that channel be introduced into the mind;
and in meetings I have found it most conducive to a right getting on,
to keep my mind as much as possible to an inward exercise.
In this state,
you will experience a qualification to discover
the openings or shuttings of the Divine hand,
and only to move when He puts forth; and when He gives ability,
make use of it in simplicity and faithfulness,
not regarding or forecasting what this or that one may say or think;
for it is the Lord`'s power alone,
that is the authority of all our meetings for worship and discipline.`"

14th. In company with my brother Thomas, I attended the Quarterly Meeting at Salem,
on the 12th and 13th. A deep united travail amongst ministers and elders,
both in their select meetings and those for worship and discipline,
that we might experience the baptism of the One Spirit,
by which alone we are baptized into one body,
and enabled to drink together into the same Spirit, is much needed among us.
Too many are great strangers to it, and appear scarcely to understand what it means.
Oh! the need there is for us individually,
to strive to keep near to the Master out of meetings,
that we may become acquainted with his voice, and witness his preserving power,
to keep us clean from the various defilements which
arise from an alliance with the spirit of the world;
then we should be better prepared to come together in a lively state of mind,
to engage in the work the Lord would assign to us.
It is only as we apply to our holy Head for his help and instruction,
that we can grow in grace and the knowledge of the Son of God.
All speculations on this knowledge are totally incompetent to
furnish one glimpse of his transcendent glory,
or to remove doubts with which the unregenerate soul is surrounded.
These truths were held up to view, under a little renewed ability,
derived from his exhaustless treasury,
though accompanied with feelings that there were impediments
to the free arising of the power of Truth into dominion.

1824, Second month 2nd. In our Quarterly Meeting we had the company of our friends,
William Forster, Jr. and John Justice of Bucks County.
It was attended with painful feelings, from the prevalence of a disorganizing spirit,
covertly at work, to unsettle the unwary,
and to strengthen those who are enemies to the cross of Christ,
and consequently to good order and sound judgment in the church.
Sensible that the Divine life and power of Truth were oppressed,
the honest-hearted were bowed in spirit,
and kept in a state of silent waiting and suffering.

One of the unsettled, members said, the knowledge of the Scriptures puffed up;
they made hireling ministers, and had done more hurt than good in our Society;
and he was not easy to apply the word holy to them:
this was a plain indication of the evil spirit of unbelief at work among these people.

The power of Truth appeared to gain but little ascendency,
yet these disturbers were so kept down,
that the meeting passed over without any material difficulty,
except the painful sensations produced by those remarks.

15th. On the 7th, I left home for Springfield, attended that meeting,
and on the 9th proceeded to Concord, and was at their Select Quarterly Meeting.
The unsoundness of some elders was plainly alluded to,
and the great loss arising therefrom to persons in the station of ministers,
especially the young and inexperienced.
How is it possible for elders to judge and to
decide rightly of the soundness of ministers,
when they themselves have departed from the Christian faith,
and gone into uncertain speculation, and a worldly spirit?
In the forepart of the meeting next day, I had something to say, by way of ministry;
but being under some fear of going beyond the commission,
I was afterwards apprehensive I took my seat too early.
It was in backwardness, I attempted to speak in so large a meeting;
but I derived some instruction on the necessity of faithfully doing our duty,
without improperly giving way to the fear of man.
Yet even in this, I believe there may be a snare;
as some who say they are not to fear or regard men in their religious duty,
run out into great activity, to the burden of the church,
and thereby dissipate what little tenderness and godly fear they were once favored with.

I stayed the meeting for worship held at Concord, the following day, the 11th,
in which William Forster, Jr., had close, searching service;
fifth-day was with him at Birmingham,
and went from there in the afternoon to my brother`'s. The review, upon the whole,
afforded peace.

Third month 10th. Having for some weeks had my mind
turned towards Haddonfield Quarterly Meeting,
I gave up to go this morning, after thinking I was released from it;
having no will to go or stay distinct from doing the Divine will.
Although nothing remarkable occurred in either meeting,
I was well satisfied on my return, that I was led there.
The unmerited mercy of the Shepherd of Israel,
in still continuing his goodness and favors to us, however undeserving,
was felt and held forth; but He might be so slighted by frequent disobedience,
as to withdraw his kindness,
and the gifts which He had bestowed for the good of individuals,
and of the Society at large, and for the glory and renown of his great Name.
There was some exercise felt in the meeting for discipline,
for the preservation of that which was ready to die,
and for restoring the waste places in the walls of Zion.
But the lack of a more general living concern and united travail,
makes it laborious work, and the little apprehended benefit is discouraging;
yet I hope those who prefer Jerusalem above their chief joy,
will hold fast their confidence in the Lord`'s power and goodness;
believing he will yet make the courts of Zion to flourish,
and give them to see the desire of their souls, and be satisfied.

Fourth month 17th. The Yearly Meeting of Ministers and Elders commenced this day.
Some Friends had acceptable service, tending to enforce the practice of inward,
reverent waiting in our religious meetings;
which will contribute more to gather the people than the mere expression of words.
The replies to the Queries,
exhibited a low state of the inferior Meetings of Ministers and Elders,
as regards unity and blameless conduct amongst men, in some places.

On first-day morning, the 18th, Isaac Stevenson, from England,
who was present at Pine Street Meeting,
bore a clear and unequivocal testimony to the divinity of Christ,
and the efficacy of his propitiatory sacrifice;
that it is through much tribulation the righteous enter the kingdom;
but there are seasons in which they are permitted to have a
foretaste of the joys which shall be hereafter revealed;
that as the glory of the latter house was to transcend that of the former, the humble,
faithful traveler at times experiences the glory of the Lord revealed in his soul,
to his unspeakable consolation.

On second-day, the 19th, we began the business of the Yearly Meeting;
when the reading of the usual epistolary correspondence
brought a solemnity over the meeting;
renewing the evidence that unity still subsists between
the various parts of our widely extended Society.
The sittings on Third-day were generally occupied in hearing the
reports and considering the state of the subordinate meetings,
as set forth in the replies to the Queries; during which much was said to edification.
Fourth-day morning, the Select Meeting concluded its sessions.
A proposition from the Southern Quarterly Meeting,
which is located in the State of Delaware, where slavery exists,
that a rule of discipline should be made against
Friends hiring slaves for the profit of the owners,
was referred to a committee; and at a future sitting, a rule was adopted,
authorizing Monthly Meetings to disown those members
who could not be persuaded to desist from the practice.

A woman Friend^
footnote:[Elizabeth Robson]
who came into our meeting in the afternoon,
was extensively engaged in speaking to those members who had partaken,
or were in danger of eating, of the fruit of the tree of unbelief.
She related the case of a young man of very superior talents and advantages,
who spent much time to ascertain and decide upon
the religious principles he should adopt;
when before he was aware, he had so imbibed the spirit of unbelief,
that he became darkened and bewildered to that degree,
his mind could settle upon no fixed principles.
He adopted the infidel opinion that we are not
bound to believe what we cannot comprehend;
and then rejected the plain testimony of the Holy Scriptures, to the sacred,
mysterious truths of the gospel of salvation, by our Lord and Savior Jesus Christ.
It pleased the Lord to lay him upon a bed of languishing; he lingered long,
and finding himself destitute of all foundation for the
hope of future happiness in the world to come,
his state of mind became awful.
Ardently desirous of some evidence upon which he could rest his hope of salvation,
and yet utterly incapable of believing the unutterable truths
he had so long accustomed himself to doubt or call in question,
he was led at last fervently to pray,
that the Lord would be pleased to grant him some assurance of their reality.
After a long season of bitter conflict, his prayer was heard;
his mind was furnished with a degree of the true faith,
which is of the operation of the Spirit of God in the heart;
which had once been tendered by it, and long since lost.
Now he could receive the doctrines of the Scriptures,
which had been to him as sealed with seven seals; and at his desire,
they were frequently read to him, with some other religious books, I think she said,
sometimes in the middle of the night.
He became like a weaned child; all dependence upon reason, or any other power of his own,
was utterly renounced, and as a new-born babe, he now received, with meekness,
the engrafted Word, which is able to save the soul;
rejoicing in the means which a gracious Creator has provided,
as helps in the way and work of salvation, through faith in our Lord Jesus Christ.

The false position which the young man had unwisely adopted, was controverted at large:
and individuals in the meeting were feelingly and fervently labored with,
to guard them against an evil heart of unbelief,
and to convince them of the dangerous consequence of
attempting to weaken the testimony of the Holy Scriptures,
and thus destroy the faith of others,
in the doctrines of life and salvation by Jesus Christ.

The remaining business of the Yearly Meeting was
satisfactorily disposed of in three sittings,
closing on sixth-day evening.
There was much cause for humble acknowledgment
to the God and Father of all our sure mercies,
for the signal and continued extension of his Divine regard to us,
throughout the sittings of this meeting; clothing the minds of many with a solid,
steady travail, for the welfare and stability of the church;
and granting the evidence of his power and authority presiding over and amongst us.
It seemed to confound the wisdom of the carnally wise,
and to bring to naught all the plans which had been devised against the peace,
order and government which have so long prevailed in our religious Society.
I trust it will prove as food that shall be found again after many days;
and as a stay to some who have been too easily
tossed to and fro by the windy doctrines of men.

Fifth month 3rd. Our Quarterly Meeting for Ministers and Elders was held.
In the meeting for business, R. Jordan was acceptably engaged,
bearing a full and clear testimony to our blessed Savior,
both as to his Godhead and manhood.

23rd. Within the last two weeks, I felt a concern to attend all the meetings in the city,
and though considerable discouragement was in the way, I gave up to the prospect,
and was enabled to get through to tolerable satisfaction.
A greater now of strength and matter was afforded at some times than at others,
and when the stream seemed low, it tended to humble and keep me low with it.
The work under such dispensations, is more mortifying,
though not the less salutary to the preacher as well as hearer,
provided we are steadily kept under Divine guidance.
I hope it was the case in a good degree,
and I at least derived some instruction in the course of the visit,
in which there seemed to be some enlargement of the gift.

My brother Thomas being absent, in company with Isaac Stevenson,
on his religious visit to this country, in one of the letters which passed between us,
was the following paragraph, which I wish to preserve;
as it contains an exercise I have sometimes felt
for the preservation of my brothers and sisters,
and our right improvement of the talents and favors that have been dispensed to us:
"`I have been often led to reflect upon the many favors which have
been conferred upon our family by a merciful and beneficent Creator.
Although temporal riches have not fallen to our trust,
yet a plentiful supply of the necessaries and comforts of life has been within our reach;
and while these have been thus bestowed for our own accommodation,
we have also possessed the means to fulfill the duties of social life,
and to contribute to meliorate the distressed condition of others.

But above all these, are to be acknowledged the gifts of the Holy Spirit.
Our parents being visited in early life by the Day-Spring from on high,
and with sincerity of heart faithfully yielding to these visitations,
were entrusted with precious gifts; not only designed for their blessing,
but fitting them for exemplary usefulness in the church of Christ.
Through their faithfulness in bearing the cross,
and suffering with the despised followers of the Lamb,
they have obtained an honorable station in the church; ruled well in their own family,
and by their example and precepts, have placed a weight of religious obligation upon us,
their children.
Where much is given much will be required.

He who has thus signally favored us with such valuable parents,
as well as with spiritual gifts, will look for fruits in their season;
and if we are not found in the footsteps of Christ`'s companions, no natural connections,
nor descent from virtuous parents, will remedy the defect, or be admitted as an excuse.
It will be useless to imagine that the faithfulness of dedicated parents,
will preserve us from the evils that abound in the world,
or shield us for neglect of the means put into our hands,
from the just and awful inquisition for the use we have made of our Lord`'s goods.
I often feel desirous we may lay these things deeply to heart;
that being convinced of the indispensable necessity of
dedicating ourselves wholly to the Lord`'s service;
and under the sense of our continued need of Divine preservation,
we may in humility and reverence, implore Him from day to day,
for fresh supplies of his Holy Spirit, to enable us to follow Him in the regeneration,
and to fill with propriety whatever station He may design for us in his church.
Being thoroughly washed and purged from every defilement, we should thus become living,
experimental witnesses of the efficacy of his Grace;
and prepared in truth to declare to others,
what our eyes had seen and our hands had handled of the good Word of life.
May we then, my dear brother,
not seeking to adorn ourselves in any manner
with what has been dispensed for our stewardship,
but in true humility of heart, seek the Lord`'s honor above everything else;
and then He will continue the blessing which rested upon the head of Joseph,
unto the utmost bound of the everlasting hills.`"

Sixth month 19th. At our last Monthly Meeting,
I obtained a minute of its concurrence to attend
the Yearly Meeting to be held in Rhode Island,
and a few meetings in the neighborhood of Newport.
On several accounts, the Yearly Meeting was a very exercising time.
In that for worship, held on first-day,
some disaffected persons interrupted the solemnity,
with their unsavory and unauthorized communications.
The reports indicated that love and unity, and the attendance of public worship,
were at a low ebb in some places.
Considerable counsel was extended by our friends William Forster, Jr.,
and Isaac Stevenson, of England, and others;
which appeared to be acceptable to many Friends, and in which I had some little share.
But the lack of feeling and clear discernment on the part of some others,
was very affecting; which with observations made by some persons, made several sittings,
seasons of painful exercise and mourning.
Friends are very generally opposed to the wild pretensions of these visionary,
ranting spirits,
and seem resolved to maintain the discipline and order of the Society over their heads.
Many have suffered deeply by them, and I hope with a good degree of patience.
Friends were encouraged to stand firm,
and to treat with offenders in the restoring spirit of meekness;
waiting upon the Head of the Church, to feel their own incapacity for the work;
that in the spirit of prayer and supplication,
they might apply to Him for Divine aid to labor
successfully for the help of their brethren;
and thereby raise a testimony in the hearts of the rebellious,
that their restoration to the footsteps of the flock,
was the primary object of their concern.

The business was finished on fifth-day evening, and after such occasions of suffering,
it afforded comfort to be favored with a peaceful satisfactory close; our dear friend,
William Forster, Jr., being engaged in fervent supplication for the different classes;
that we might be concerned to fill up faithfully the various measures of assigned duty;
experiencing strength and preservation in our different allotments,
however distantly separated from each other.
Friends manifested much kindness, particularly our much valued and attentive hostess,
Abigail Robinson, at whose house, my brother Joseph Rhoads and myself,
were very agreeably accommodated.

Having a meeting appointed on Canonicut Island, where a few Friends reside,
we went over on sixth-day morning, and attended it.
Being the first I had held of that description,
it was felt to be a serious matter for me;
but believing the only ground on which we can safely move, is that of simple obedience,
I was preserved in calmness and dedication to the Lord`'s will;
wherein I was enabled to discharge myself of what appeared to be opened for the people;
and as I was a child in the work, He who knows how to lead forth his children,
dealt with me according to my capacity; neither trusting me with great things,
nor failing to afford the consolation of peaceful tranquility throughout the day.
The Friends there appeared to be satisfied.

We attended the Western Meeting at South Kingston on first-day;
the Monthly Meeting at Tower Hill on second-day, and on third and fourth-days,
had appointed meetings at Richmond and Hopkinton.
The last was a favored time, in which the love and life of the Gospel were felt,
and flowed freely towards the people;
it was quite unexpected to me to be thus favored in the close,
but it seemed to be granted as an encouragement
to future dedication to the Master`'s will.
The people were much tendered, and an elderly man, who I supposed, was not a member,
said it was the doctrine he had believed for forty years.

Ninth month 5th. My dear mother having been much
confined with sickness during the last seven months,
so far recovered, as to be able to attend our meeting a few times in the past four weeks.
This morning she was engaged to declare that our Lord Jesus Christ, is the Way,
the Truth, and the Life, by whom alone our salvation is to be effected.
She said "`She was never before so fully prepared to bear testimony to the excellency,
the wisdom, and the blessedness of the Gospel plan: that Christ was the way,
she was bold to declare, and that it was a precious thing to have faith in Him.`"
Speaking of the hope of the true believer, she observed,
that at a time when she apprehended herself on the confines of the grave, "`I said,
what a blessed hope! and any other hope of salvation than by
and through the mediation of our Lord and Savior Jesus Christ,
will prove like the hope of the hypocrite, that shall perish.
When brought to such a crisis as this, having experienced our own wills,
lusts and affections,
reduced by the operation of his grace--that grace which
came by Jesus Christ--and nailed to the cross,
in some little degree comparable to his body being nailed to the outward cross,
in which we might say, if this cup may not pass from me, not my will but yours be done,
then are we prepared to acknowledge that it is not by anything we have done,
but all of the mercy of God; not by works of righteousness which we have done,
but according to his mercy He saves us; by the washing of regeneration,
and the renewing of the Holy Ghost.`"

Such a testimony to the Gospel of salvation;
and the entire uselessness of man`'s righteousness,
which he performs in his own time and strength,
delivered by one who seemed to be raised from the dead, I thought was worth preserving.
It shows the continued goodness of the Heavenly Parent,
in authorizing his servants to publish the glad
tidings of peace through his well beloved Son,
even to a rebellious and gainsaying people, whether they hear or forbear.

After the decease of my dear wife, I continued unmarried between nine and ten years;
during which I passed through many dispensations, designed, I trust,
to promote my growth in the work of salvation,
and prepare me for the service to which the Lord would call me in his church.
At one time when my mind was under deep plunges,
and with little sense of the Lord`'s presence and supporting power, our friend,
Elizabeth Robson, came to our meeting at Pine street;
and as I sat under such feelings stripped of all good, I said in my heart,
if she would rise and utter the expressions of our blessed Savior to Peter,
it would be a convincing confirmation that I was not entirely forsaken.
Soon after the thought had passed through my mind, she rose and began with these words,
"`Simon behold, Satan has desired to have you that he may sift you as wheat,
but I have prayed for you, that your faith fail not.`"
It was very striking to me, and tendered my spirit,
reviving my faith and dissipating those fears with which I had been assailed.
It seemed an evidence of the reality of the communion of exercised spirits,
still continued in the church of Christ.

My thoughts having been drawn towards my beloved friend Elizabeth Barton, a minister,
daughter of John and Rebecca Barton, with a view of proposing our marriage,
the prospect of entering again into the marriage covenant,
was not less serious than in the former union;
and brought me into strong desire to do nothing
but what was according to the Lord`'s will;
often looking to Him for evidence of the propriety of such a movement;
which I believe was also her sincere concern.

My dear friend having a religions draft to attend Baltimore Yearly Meeting,
she was accompanied to it, in the Tenth month, by our valued Friends,
Josiah and Elizabeth Reeve, who were like parents in the Truth to both of us.
The Lord equipped and anointed her for the work she was engaged in,
much to the satisfaction of Friends there, and to her beloved companions.

Our marriage was accomplished after her return from this visit, at Newtown, N. J.,
on the twenty-third day of the Twelfth month, 1824;
at which time we were favored with a solid satisfactory meeting,
under a sense of the owning presence of our blessed Lord and Master.

1825, Fourth month 18th. Our Yearly Meeting began on this day.
The epistles from the different Yearly Meetings were read,
to the comfort and strength of the meeting.
A proposal that "`All important appointments should be made for a limited time,`"
was introduced to the Yearly Meeting by the report of one of the Quarterly Meetings.
It was a favorite scheme with the followers of Elias Hicks.
The opposition made to his principles by the Elders of Philadelphia,
having been the beginning of difficulty to him in spreading his unsound notions,
by rousing up many in the Society to examine and to reject them,
as subversive of the fundamental doctrines of Christianity,
and the peace and discipline of our Society, he had expressed at different times,
his repugnance to Meetings of Ministers and Elders, and the Meeting for Sufferings;
saying they were blocks in his way and must be removed.
Considerable discussion followed the opening of it to the meeting.
The friends of Elias Hicks labored hard to induce the
meeting to take hold of the proposition;
but after much time spent on it, a minute was made,
that way did not open to take any such step.

It was very obvious that the design of introducing this subject,
was to pave the way for the formation of such a Meeting for Sufferings,
as would publish and spread these anti-christian sentiments;
and to remove all elders who had or should discountenance E. Hicks,
and other ministers who held his opinions.

Ministers who preached the doctrines of the New Testament,
would be subjected to the same treatment.
The plea that such had "`become burdensome,`"
advanced by one of them during the discussion,
and, in their estimation, had lost their gifts, would be sufficient to remove them.
Unsound principles might thus be propagated with impunity,
and libertinism and ranterism would, in places, overrun the Society.
Thus the beautiful and excellent order,
which the Head of the church has instituted in our Religious Society,
and the hedge erected as a defense upon the glory, might be destroyed;
and the members become a prey to the wild schemes and
imaginations of every ambitious pretender to superior light.

Much concern was felt by many Friends, respecting this Yearly Meeting.
Although we were not favored at all times,
with such a covering of solemnity as we might desire, those restless people,
notwithstanding their exertions to support their own plans, were entirely defeated;
they did not gain a single point;
and Friends rejoiced in a sense of the preservation
still extended to us in this large annual assembly,
by our holy Head and High Priest.

Fifth month 25th. At our Monthly Meeting, held this day,
a Friend opened a concern with which his mind had been long impressed,
respecting the spreading of unsound principles amongst the members, by various means.
He thought it his place to open the subject,
that we might consider whether it was the duty of the meeting to adopt any
measures to guard the members against their pernicious tendency.
Several spoke in favor of something being done
to warn the members of the dangerous opinions.
Nothing, however, was agreed to be done at present;
yet the opening and spreading of the subject before the meeting,
showed that Friends were alive to the dangerous tendency of the sentiments of E. Hicks,
and it will gradually prepare for decisive measures in due time.

Eighth month 1st. Our Quarterly Meeting was a time of debate,
on the case of a substantial elder whom the
Green Street Meeting had attempted to displace,
under the plea that he was out of the unity,
on account of his joining with the sound elders among us,
in declaring their disunity with Elias Hicks.
Some tried to dismiss the case from the notice of the Quarterly Meeting,
but not succeeding, it was referred to the next meeting.

Tenth month 25th. I attended the Northern District Monthly Meeting,
where we had the company of Elizabeth Robson, from England.
Her labors in the first meeting, and in the men`'s Monthly Meeting,
I thought were well adapted.

26th. E. Robson was with us at our Monthly Meeting very satisfactorily,
and appeared to have a just sense of the states of many.

1826,
First month 25th. Having had my mind drawn at different
times to visit the meetings in the country,
belonging to our Quarterly Meeting,
I mentioned it to the Monthly Meeting informing that as
Radnor Monthly Meeting was within a convenient distance,
I had attended the meetings composing it, except one;
but although the discipline gave me liberty, I did not feel easy to visit the others,
without the consent of the Monthly Meeting; being little known among them as a minister.

The experienced and weighty part expressed their unity,
and approbation of granting me a minute.
But those dissatisfied members objected to a minute being given,
yet some were willing I should go without one; and persisting in their opposition,
it was not minuted,
and I informed Friends that I should not be easy
to attend to the concern without its concurrence,
expressed in writing; the prosecution of it will, of course, be deferred.
Suffering for well-doing will be of use to those who rightly endure it,
in a true Christian spirit.
I desire to be favored with this, and to manifest the fruits of it towards others,
even my inconsiderate opponents.

Second month 6th. Being convinced that the principles of infidelity
have taken root in some members of our religious Society,
and that it is much to be attributed to an unauthorized ministry,
as the subject rested with weight upon my mind,
I was induced to open it in our Select Quarterly Meeting, on the 4th,
I expressed my fears that there were those among us, who, with or without design,
were giving encouragement to the growth of these principles.
The practice of dwelling particularly on passages of Holy Scripture,
which relate to the manhood of the Lord Jesus, and in clipping others,
in which his Divinity is set forth, tended to inculcate those sentiments of unbelief,
and settle the young people in a disposition to slight
some of the fundamental principles of Christianity.
They were quick in discerning those departures, which have an injurious tendency.
I had been told by one person that he did not see how the
sufferings and death of Christ could affect his salvation.

This was one evidence of the effect of these unsound opinions; and it was also said,
"`We are not bound to believe what we cannot understand.`"
While some were holding up the doctrine of Christ in us the hope of glory,
which is a true, sound, gospel doctrine,
they were detracting from the high and holy character of the Lord Jesus;
in striving to weaken or destroy the faith of the
people in his sufferings in the prepared body,
as of no avail in the salvation of mankind.
Friends were warned against this desolating spirit;
that however some might be soaring above others, and drawing persons to them,
the time would come when all would be brought down,
as into the valley of Jehosophat where the Lord would plead with all flesh,
and show some the awfulness of endeavoring to lessen and detract from
the character and offices of our Lord Jesus Christ.

Fourth month 15th. This morning the Yearly Meeting of Ministers and Elders commenced.
Richard Jordan bore testimony to the Divine origin and excellency of the Holy Scriptures.
He expressed his thankfulness that Divine Goodness had influenced his prophets,
and messengers and apostles to record the creation of the visible world,
and his dealings with man from the beginning;
that the outward creation was analogous to the spiritual;
so that even the apostle declared that it displayed the invisible power of the Creator;
and the experiences of the righteous corroborated each other;
and under the Divine influence,
they owned the testimonies of the Holy Spirit which had gone before.
He repeated the first verse of the Epistle to the Hebrews,
and particularly dwelt on the value of the record, that God had, in the last days,
spoken unto us by his Son, whom He had appointed heir of all things.

Elizabeth Robson followed him in testimony to the promise of the Messiah,
at the fall of Adam; renewal of that promise to Abraham;
the prophecy of it by Jacob respecting Judah;
and the more minute description of the character
of the Redeemer by the succeeding prophets.
She showed the fulfillment of those prophecies in Jesus Christ;
his rejection and contemptuous treatment by the Jews,
and their final assent to his crucifixion.

That He thus bore our sins, as the great propitiatory sacrifice,
without the gates of Jerusalem; and that it was the gospel commission to the apostles,
and to every true minister of Christ down to this day,
that repentance and remission of sins should be
preached in the name of our Lord Jesus Christ.
She closed her communication with expressions of
great sympathy with a tried remnant among us,
and the firm belief that these, as they kept on the immutable foundation,
would be preserved; that a poor despised remnant would be raised up in our Society,
who should stand for the honor of the great Name;
and that to these the Lord would be for a crown of glory and a diadem of beauty.

16th. This morning, first-day, we had the company of our friend, E. Robson,
at our meeting.
She bore a plain testimony to the Redeemer and Savior of men;
and expressed her sense of those present,
who were endeavoring to fence themselves in a confidence in themselves,
and were resisting the knockings of Christ, to gain an entrance in their hearts;
and she pressed the necessity of yielding thereto, as time was fast spending,
and it was a gift to be accounted for.
John Parker followed in a short, lively testimony;
and she concluded the meeting with solemn and affecting supplication,
both for those who were thus hardening themselves
against the reproofs of the Spirit of Christ,
and for those who counted nothing too dear to part with for his name`'s sake.

17th. Soon after the opening of the Yearly Meeting,
Richard Jordan spoke on the different sounds there are in the world;
and whether of pipe or harp,
it was necessary we should have our spiritual
senses exercised to distinguish between them.
If the trumpet gave an uncertain sound, who would prepare himself for the battle?
He showed the difference between the first and second Adam;
the first was of the earthy earthy; the second the Lord from heaven;
the first was made a living soul, the second was the quickening Spirit.
It was by the latter, the soul was made alive, and without it,
it would be in a state of spiritual death.
He bore testimony to the blessedness of having the Holy Scriptures;
and mentioned the expressions of Peter, respecting Paul`'s writings, which, he said,
the ignorant and unlearned wrested, as they did the other Scriptures.
That man, by all his powers, was unable to comprehend spiritual things.
He must be renewedly quickened, taught in the school of Christ;
or in his ignorance going about to unravel the mysteries of the Gospel,
he would involve himself in perplexity.
This was the sentiment of the Society, in the beginning.
They set out with no new mystery, but owned the doctrines of the Gospel,
as they were promulgated by our Lord and his apostles, etc.

18th. This morning the attention of the meeting was
principally occupied with the subject of the slave trade;
and besides a minute expressive of the unity of the meeting
with the proceedings of the Meeting for Sufferings,
prepared yesterday and read this morning, it was agreed the clerk should prepare another,
descriptive of the concern of the Yearly Meeting, as evinced this morning;
and referring to the particular care of the Meeting for Sufferings,
the subject of the slave trade, foreign and domestic.
The Queries were taken up in the afternoon,
and proceeded in as far as the fourth and fifth.

Feeling my own mind brought under some religious concern,
I observed that I believed there was no religious Society,
that had a more just estimate of the character and
value of the Scriptures than the Society of Friends.
That although we did not call them the Word of God,
because that title belonged to our Lord Jesus Christ,
yet we believed that holy men of God wrote and
spoke them as they were moved by the Holy Ghost;
and the more we were under the influence and government of that Grace and Truth,
which came and comes by Jesus Christ, the more we should value them.
I stated, as an evidence of the high estimate set upon them by our Society,
that we had a rule of discipline,
that any one denying the Divine authority of the Holy Scriptures,
was subject to disownment, if he could not be brought to acknowledge his error.
By the Query which we had just heard,
this meeting indirectly advises its members to
be in the practice of frequently reading them.
This, I stated, was conclusive proof that Friends set a high value upon them;
and warned some against calling them a dead letter, having no life in them.
The more we were under the influence of Divine life in ourselves,
the more comfort and strength we should find in reading them.
To these the experiences of the holy ancients were peculiarly valuable.
They are profitable for doctrine, for reproof, for correction,
and instruction in righteousness, that the man of God may be perfect,
thoroughly furnished unto all good works; being able to make wise unto salvation,
through faith which is in Christ Jesus.
In proportion to the various means dispensed in inscrutable wisdom and unmerited mercy,
for our aid in the work of salvation through the Holy Spirit,
would be our responsibility; and at some period,
an awful account must be rendered for the use of them.
The meeting was very quiet and attentive;
and a Friend followed and confirmed what I had said as correct; and added,
that the Society had always held them as a test of their doctrines,
and expected Friends to be in the practice of frequently reading them in their families.

21st. The remaining business was attended to on the 19th, 20th, and this day.
Upon the whole, the meeting was preserved in much quiet throughout its sittings;
but notwithstanding we had cause to believe that Divine mercy was roundabout;
still keeping us from anarchy and confusion;
there was a constant painful sense of a dark spirit, secretly at work in many,
that was waiting and watching to lay waste the heritage.
This was like a heavy load upon the upright, sincerely devoted servants of Christ,
and seemed to hinder the power of Divine life from rising into
that dominion which we have sometimes known it to do.

28th. In our Quarterly Meeting of Ministers and Elders, held this morning,
much pertinent advice and encouragement were communicated.
Elders were particularly exhorted to faithfulness in
the discharge of their duties towards ministers;
and sympathy with such as had faithfully kept their ground against wrong things,
and had heavy burdens to bear, was freely expressed.

Fifth month 1st. We have had the most solid Quarterly Meeting this day,
that has been held here in the last eighteen months.
Elizabeth Robson came into the men`'s meeting, and had very weighty and pertinent service.
She mentioned the instance of David going to see his brethren,
that he might know how they fared, and how the battle went;
and when his motive was questioned, he asked, "`Is there not a cause?`"
He did not go forth in Saul`'s armor, but chose smooth stones out of the brook;
and with a simple sling smote the giant, and cut off his head with his own sword,
and a great deliverance was wrought for Israel,
through the faithfulness of a single individual.
Notwithstanding the king`'s decree,
Daniel failed not to offer his prayers three times a day, with his windows open,
as he had been wont to do;
and thus bore a public and faithful testimony of his allegiance to the true God.
She said it was time for some who have too much secluded themselves,
to show on whose side they are.
The mouths of the lions were stopped, and an acknowledgment extorted from the king,
by whose decree he had been put into the den, that Daniel`'s God was the living God,
and able to deliver those who trust in Him.
When the three children were cast into the furnace,
which was heated seven times hotter than it was wont to be heated,
they walked in the midst of it unhurt, because the Son of God was with them;
and not even the smell of fire was perceptible on their garments.
But those who cast them in were slain by the fire.
This she applied, in a striking manner,
to those who were endeavoring to destroy the true seed.
She then appeared in very solemn supplication,
much to the comfort and strength of many Friends.

Sixth month 8th. On the 26th of last month,
I left home to attend New York Yearly Meeting,
with a minute of the Southern District Monthly Meeting.
It was throughout a trying occasion; a spirit of opposition in many to sound Friends,
and to some of the principles of the Christian religion,
as held by the Society from its rise,
was a constant burden upon the rightly exercised members.
This was increased from time to time, by opinions of a disorganizing tendency,
which were avowed by some,
who seemed determined to destroy all regard to doctrines and principles,
as wholly unimportant; and to dissolve the bands of Society,
by denying the accountability of the members,
for the opinions which they held and expressed.
As it might be expected, persons of little or no religious weight and feeling,
manifested no restraint, in taking an undue part in the discussions of the meeting,
and were very ready and importunate to have their views adopted.
A solid judgment, concluded under the solemnizing presence of the Head of the church,
was rarely witnessed throughout the meeting.
The original ground on which the decisions of the Society
heretofore stood--a prevailing conviction that the Truth led
into the measure--appeared to be lost sight of by many;
and a majority of voices regarded as the governing authority;
without any discrimination of age, experience, soundness of judgment,
or clearness of discerning.
