== Chapter V

[.chapter-synopsis]
* 1826--1833. Progress and Effects of Unsound Opinions
* Death of Richard Jordan
* Charge against Elias Hicks forwarded by Southern District Monthly Meeting
* Yearly Meeting of 1827
* Separation from the Society of Friends
* Incidents in some of the Meetings
* Abington Quarter
* Conference held at Mount Pleasant
* Ohio Yearly Meeting of 1828
* Visit to North Carolina
* North Carolina Yearly Meeting
* Visits within Philadelphia Yearly Meeting
* Visit within New England Yearly Meeting.

1826, Eighth month 20th.
The state of things among us
is rapidly assuming a very dark and gloomy cast.
Unless a blast is brought upon this disorganizing spirit,
it would seem that great devastation will be made in the Society.
Our meetings for Divine worship are, at times,
almost destitute of the sensible presence of our holy Head and High Priest,
which tenders and humbles the minds of Friends,
and qualifies for the performance of that solemn duty.
The streams of gospel ministry are nearly stopped,
and the ministers are clothed with mourning, at the great change.
But we are not without faith and hope, that the Lord is secretly at work,
to make way for his truth and power, to rise again into dominion;
when He will confound this exalted spirit,
and bring some of those who are troubling Israel, down as into the valley of Jehoshaphat,
where He will plead with them in a very awful manner.
Great will be their confusion at that day; and many, I believe,
will look back with astonishment at the delusion
with which they and others have been overtaken.

Ninth month 16th. On the 13th, in company with my wife,
I attended Haddonfield Select Quarterly Meeting.
It was a low, distressing time.
The benumbing effects of the love of the world upon very many,
makes our assemblies seasons of laborious, discouraging exercise;
in which apprehensions come over the mind,
that we are in danger of having the candlestick removed out of its place,
and becoming a forsaken people.
These sensations were experienced in both meetings.

At the Meeting for Sufferings held yesterday,
several minutes of new appointments by different Quarterly Meetings were received.
One from the Southern Quarter stated,
that a committee had been appointed to consider the
revision of their representation in this Meeting;
and reported, as their sense,
that it would be proper to release all their representatives, excepting one.
As the case was new, several Friends expressed doubts of the propriety of such a measure:
frequent changes in the appointment might be followed
by injurious consequences and to make it,
involved a principle which the Yearly Meeting only could settle;
and it was proposed to appoint a committee on the subject.
A few Friends were accordingly verbally appointed to attend to it.

Eleventh month.
On the 14th of last month, our beloved and honored friend, Richard Jordan,
was released from the trials attendant upon this earthly scene,
after a sickness of about eight weeks.
Without much apparent suffering, the worn-out system gave way to the force of disease,
and the spirit that longed to depart and be with Christ, his Savior and Redeemer,
was permitted to take its flight to those blissful regions,
"`Where the wicked cease from troubling and the weary are at rest.`"
He gave ample testimony, in his illness, of the firmness of his faith in Christ;
through whose grace and merits, he said, he hoped for salvation.
This was the faith he had lived in, and the faith he should die in.

Great quiet and solemnity prevailed at the time of his burial and after the interment,
Friends convening in the meetinghouse, a very satisfactory meeting was held;
in which our dear friend, Ann Jones of England,
bore testimony to the faithfulness of the deceased,
in discharging his duties to the righteous and the unrighteous,
as one who must give account of the souls committed to his care; saying,
she believed he had received the crown of an apostle.
He was a very judicious, nursing father to inexperienced, devoted children;
equally careful to guard them against premature fruit,
as well as to hand suitable encouragement in due season, when they were ready to sink.

On the 4th of this month, was held our Quarterly Meeting of Ministers and Elders,
which was in the main a comfortable meeting.
Our friends, George and Ann Jones, of England, and Elizabeth Robson,
who had just returned from Baltimore Yearly Meeting, were with us,
and had acceptable service.

On the 6th, the Quarterly Meeting was held; it was unusually large,
many young men being present who showed their interest in the preservation of order,
and the principles of the Society,
by supporting the elder Friends in such measures as they believed it right to adopt,
for the maintenance of the discipline.

The Quarterly Meeting of Bucks was held at Middletown,
on the 29th and 30th of this month, which I attended,
and was glad to have the opportunity for the company of our friends,
George and Ann Jones.
Several other Friends were there from neighboring meetings.

On sixth-day morning we took breakfast at Sarah Comfort`'s,
whose valuable husband had lately deceased.
We then proceeded to Byberry, and attended a meeting there,
appointed by George and Ann Jones.
The latter was there led in a way much in opposition to those who cry peace,
when there is none.
Death had come up into their houses;
and those who had been teaching the children rebellion, would, she believed,
experience the sad consequences of it in their own families.
Near the close of the meeting,
I spoke on the awful and responsible situation of those who were
promoting a disbelief in Jesus Christ as the Savior of men;
that the effects of the spirit of unbelief were to be seen and felt.
All restraint would be much removed;
and it was evidently the case with the young people in that part of the country.
It lay as a burden upon me, which I was unwilling to bring away with me.

Twelfth month.
Being one of the Committee having charge of the Boarding School at West-town,
I left the city on the 9th of this month, on an appointment to visit the schools,
and was absent till the 13th. At the adjournment of our Monthly Meeting of this month,
my father called the attention of Friends to the disorder at a late meeting,
attended by Elias Hicks, and the unsound principles advanced in it by him;
and after some opposition to it, made by seven of his adherents,
the meeting made a minute,
stating that the disorder which occurred in this house on the 11th,
and those unsound principles and sentiments therein advanced by Elias Hicks,
being weightily brought into view,
five persons were appointed to investigate the subject and report thereon.

1827, First month 24th.
The above committee produced to the Monthly Meeting a full report;
in which they exhibit some of the prominent features of the disorder,
and the very exceptionable doctrines delivered by Elias Hicks;
closing with the expression of their concern on account
of the propagation of such poisonous sentiments;
and also that some of his adherents may be snatched as brands from the burning.
A copy of this report was directed to be forwarded to Jericho Monthly Meeting,
of which Elias Hicks is a member; with which women Friends concurred.

Second month 3rd. Today we have had a very exercising Select Quarterly Meeting.
In the forepart, a comfortable evidence was felt,
that condescending mercy and goodness were round about us;
strengthening the faith of the Lord`'s children in his Divine power,
and affording the consoling conviction, that He will defend and preserve his church,
as its confidence is maintained in Him alone, and in due time will scatter his enemies,
and grant a peaceful release from the trials with which it is now assailed.

On reading the answers to the second query,
my father hinted at the difficulty of admitting the correctness of
the reply to it from one of the Preparative Meetings,
which asserted the soundness of its ministry;
but of the reverse of which we had had sufficient evidence.
In his remarks,
he adverted to attempts now made to spread the belief
that Jesus Christ our Savior was no more than a man,
or one of us.
A member of the meeting alluded to replied to him,
as if he felt the allusion applied to himself; and in his remarks,
stated there was but one Savior, and that was God;
and making allusions to declarations of George Fox and William Penn,
attempted to infer that those who preached "`Christ crucified,`" as the Savior,
were they who made the Savior a mere man.
He declared that Christ was sent to the Jews only; that He was an external Savior.
He was no Trinitarian, nor Satisfactionist;
by which it was understood he did not receive the Scripture
doctrine of the Three that bear record in heaven,
the Father, the Word and the Holy Spirit;
nor believe in the propitiatory offering of the Lord Jesus,
by which we have remission of sins, and perfect sanctification,
through repentance and obedience to his Holy Spirit.

5th. Some opposition was made in the Quarterly Meeting for discipline,
to the summary answers to the third Query; which contained expressions of belief,
that pernicious publications supporting unsound doctrine, were tolerated among some,
to the grief and concern of many Friends; but the meeting retained it,
to go up to the Yearly Meeting.

The Committee appointed to visit the Monthly Meetings reported attention to the service,
and that they had evidence the appointment originated in best wisdom.
Several of the disaffected strove to get the committee discharged,
but the meeting continued it.

One of the Green Street elders proposed that a committee
should be appointed to consult with that meeting,
so that they might be joined to Abington Quarter.
This was one of the preliminary steps to the breaking
up of our Quarterly and Monthly Meetings,
and the division of the Yearly Meeting.
No notice was taken of it.

10th. This afternoon I drove George and Ann Jones, with C. W. Morris,
to my brother-in-law`'s, Joseph Rhoads.
Next day, first-day, we attended Springfield Meeting,
and being met there by Charles Allen,
he accompanied them to Abraham Sharpless in the afternoon.

12th. My wife and myself went to Concord,
and attended the Select Quarterly Meeting there; a distressing time;
in which it was evident to me, that some were desirous of persuading themselves,
that not as much disunity and unsoundness of principle had crept in,
as some others imagined.

There is great lack of a lively zeal in some, and an honest faithful discharge of duty,
against the insidious approaches of the spirit of unbelief;
which is watching to ensnare the unwary, and will commit great ravages in the flock,
unless the watchmen who are placed upon the walls, are awake to the surrounding dangers,
and timely give the alarm.

13th. In the course of reading the queries and answers in the Meeting for Discipline,
I believed it proper to call the attention of Friends to the
contrast between the answers to the second and third queries--
the former very full and the latter much the reverse.
That while much love and unity were professed,
it was plain great deficiency existed in the education of children.
I adverted to the advice of the Yearly Meeting to parents,
to practice their children in the frequent reading of the Holy Scriptures,
and to instruct them in the doctrines of the Christian religion, which they inculcate:
viz., the miraculous conception, birth, holy life, sufferings, meritorious death,
glorious resurrection, ascension and mediation of our Lord and Savior Jesus Christ;
as well as in the belief of the immediate influences of the Holy Spirit.
But there were pamphlets in circulation among us,
which tended to lay waste a belief in many of these Christian doctrines; one of which,
was issued within the precincts of that Quarter;
which I considered one of the most pernicious books in circulation;
tending to destroy all reverence for our Lord Jesus Christ,
who suffered without the gates of Jerusalem, as the Savior of men;
to destroy the authenticity and authority of the Holy Scriptures;
and to spread the seeds of infidelity;
and I believed it my duty to bear a testimony against it.

Fourth month 14th. Our Yearly Meeting of Ministers and Elders convened this morning;
in which we had the very acceptable company of our
beloved friends George and Ann Jones and E. Robson.
On reading the summary reply to the second query,
and the judgment of the Quarterly Meeting by which it was sent up,
that an unsound ministry existed within its borders, some of the disaffected members,
earnestly contended that it should be expunged; but the proposition was rejected,
and the answer retained.
William Jackson opened his views,
and queried whether there was nothing further for the meeting to do;
expressing his belief that it should go further, either by epistolary advice,
or by appointing a committee to visit the constituent meetings, to afford them help.
After a time of deliberation, it was concluded to appoint a committee, which was done.

16th. The morning meeting for business was passed with little interruption.
Elizabeth Robson paid us a very acceptable visit.
The representatives convening at the rise of the meeting,
one of them proposed that John Comly should be reported for clerk;
another that Samuel Bettle should be reported to be continued.

One wished a Friend might come to the table and draw up a minute reporting John Comly,
which, such as united with him, might sign.
This was rejected.
He then proposed that such as united with him
should withdraw to another part of the house,
and prepare a report;
which he endeavored to effect by leaving his seat and walking towards the aisle;
a few rose to follow, but others protesting against it, they took their seats again.

Finding that they could not adopt any one to name to the meeting,
the representatives pretty generally agreed,
to authorize John Cox to inform the meeting they could not unite to report any name.
We were detained until the meeting convened in the afternoon,
and John Cox made that report accordingly.
Some asserted that they had not concluded on any report,
and were to meet again next morning.
Others had heard nothing of such adjournment; and it being evident we could not unite,
it was eventually concluded to reappoint the old clerks,
after much opposition by the followers of Elias Hicks,
John Comly came to the table as assistant, with great reluctance;
and the minutes of the Meeting for Sufferings were read,
with very little remark by way of objection, to their proceedings;
their care on the subject of slavery was approbated.

17th. Early after the meeting opened, John Comly rose and remarked,
that he had come to the table in condescension to the request of a few Friends;
that this Yearly Meeting was divided into two distinct parties,
which were irreconcilable, and unity was destroyed.
We had a query whether love and unity were preserved among us.
He thought it was needful to have it restored,
and therefore proposed that the meeting should be adjourned.
The query is also asked, When differences arise are endeavors used to end them?
He thought if there were men of peace among us, it would be well for them,
in the meantime, to exert themselves in removing those differences.
He could not conscientiously act as the organ of such a body; and therefore,
if the meeting decided not to adjourn,
he wished to be permitted to withdraw from the table.
This opened the way for his party to express themselves upon the state of the Society;
and some were accordingly prepared to dissolve the meeting.

Sound Friends generally kept still, with the exception of a few,
who thought the proceedings need not be delayed any time for lack of John Comly`'s services.
When he discovered he could not effect his purpose of breaking up the meeting,
he wished Friends to mind that he had not said dissolve, but adjourn;
and as he had apprehended many Friends did not unite with his appointment,
if it was now the general sense that he should remain at the table,
he would accordingly serve: thus he waived his conscientious scruples,
though no increase of unity had been obtained.

The usual concerns of the Yearly Meeting were transacted, and towards its close,
information was sent in from women Friends,
that they had before them a concern to appoint a committee,
if united with by men Friends, to visit the Monthly and Quarterly Meetings.
Opposition was started by the disaffected, as it would, in some measure,
interfere with them;
but when the meeting was informed of their conferences and plans to create a separation,
it stopped them.
Friends more fully saw the need of sending down
help to strengthen the hands of sound Friends,
and aid in supporting their meetings.
A committee was accordingly appointed of both sexes.
The Yearly Meeting adjourned to meet at the usual time next year,
if consistent with the Divine will.

Fifth month 5th. Our Quarterly Meeting of Ministers and Elders was held,
and attended by the Committee appointed by the
late Yearly Meeting of Ministers and Elders.
In reading the replies to the Queries,
some pretty close remarks were made upon that to the second,
from one of the Preparative Meetings;
and Friends there were encouraged to extend faithful, private labor.
After finishing the Queries,
Elizabeth Robson adverted to the poverty and weakness
into which the Lord`'s children were introduced,
and this was preparatory to being employed in his service; that out of weakness,
they might be made strong, and that his strength might be made perfect in their weakness.
She believed some would have to partake of bitter cups; and might be ready to conclude,
at times, there was no way for them to get on;
but as they held fast their trust in the Lord, and were courageous,
the hills would flow down at his presence.

7th. We had a very quiet, satisfactory Quarterly Meeting.
No report from Green Street being produced,
one of their members appointed to inform the meeting of
their disjunction from Philadelphia Quarter,
laid a minute on the clerk`'s table.
The committee appointed to visit the Monthly Meetings,
made a detailed report of their proceedings.
Some members of Green Street, addressed the Quarterly Meeting,
stating their disunity with the acts of that meeting,
and received the sympathy and encouragement of Friends, to abide steadfast,
in a faithful adherence to the leadings of the Holy Spirit;
that they may witness preservation,
and advance in religious qualification to support the
principles and discipline of our religious Society.
The whole of the business was conducted with much unanimity and quiet;
so that it was evident the abstraction of the Green Street members,
of a certain description,
carried with them the noise and confusion which have
agitated and distressed our Quarterly Meeting.

20th. On second-day, the 14th, I attended Haddonfield Monthly Meeting,
which ended comfortably.

22nd. I attended the Northern District Monthly Meeting.
The minute of the Quarterly Meeting,
stating it had concluded to lay down Green Street Monthly Meeting,
and attach the members to this, was produced, and taken on record;
and a committee appointed to deliberate upon the
steps proper to be pursued in relation thereto.

23rd. A private meeting having been held in a school-house, within the Southern District,
made up of some of its members and others,
to devise means to obtain possession of part of the property of the Monthly Meeting,
they prepared a paper on the subject;
and before going into our Monthly Meeting this morning,
some Friends were informed that it would be presented,
and that the disaffected members had decided, that if it was rejected,
to divide off to the other side of the meeting-room,
and there hold a Monthly Meeting themselves.
Many of our members, who had not been seen for years at our Monthly Meeting, assembled;
and some from the country, and also some from other Meetings in the city;
doubtless with design to swell their numbers in appearance,
in case of the proposed division.
After a passing on account of marriage, and reading some certificates, W. W. arose,
and expressed his thankfulness whenever the meeting was covered with solemnity;
and his unwillingness to do anything that would disturb it; but he believed,
that in the disposition that breathed glory to God and good-will to men,
we might discuss subjects, and not be excited.
He had one to propose, and though it was rather new,
he hoped it would not produce such effect.
He then mentioned, that some of them believed it proper to propose,
that a division of the property should be made;
so as to enable them to build a meetinghouse; purchase the site,
and provide the necessary accommodations.

A paper had been prepared, which, he said, was signed by forty-five members,
and approved by several others, who were not yet prepared to sign it;
he would hand it to the clerk.
The paper was referred to six Friends, to examine and report to a future meeting.

After this Monthly Meeting,
it was ascertained that fourteen of our members had applied to Byberry Monthly Meeting,
to be received as its members; which was acceded to;
and that they appointed a committee of men and women to attend
the opening of a meeting for worship in this city.
This act of Byberry Monthly Meeting, is a violation of the discipline,
and of the just right of the Southern District Monthly Meeting over its members.
It is an invasion of the limits and jurisdiction of Philadelphia Quarterly Meeting,
and of its Monthly Meetings,
to attempt thus to institute a meeting within the borders of any of those meetings.

Sixth month 4th. This separating party held their Meeting of Conference,
appointed in the Fourth month last.
They issued an address to the Quarterly and Monthly Meetings,
within the compass of Philadelphia Yearly Meeting;
the design of which is to induce a separation from it,
and to prevail with the Quarterly Meetings,
to send deputies to an assemblage on the third second-day of the Tenth month next.
It contains several unfounded accusations against the late Yearly Meeting.

21st. At our Meeting for Sufferings, held at this time,
the present state of our religious Society was brought into view by one of its members.
He adverted to the meeting which the Hicksites had held,
and some of the measures adopted to produce a separation from the Society,
and draw its members after them.
After some time of deliberation on the affecting subject,
a pretty large committee was appointed upon it, and the meeting adjourned for one month;
very few of the Hicksites attended.

Seventh month.
At the Meeting for Sufferings, held in this month, an epistle was adopted,
addressed to the members of our Yearly Meeting.
The Committee on the present state of the Society was continued.

Eighth month.
A part of the members of Abington Quarter, separating from Philadelphia Yearly Meeting,
by appointing a number of their party to attend, as their representatives,
a meeting to be held in the Tenth month, under the name of Philadelphia Yearly Meeting,
the sound members decided to remain together,
in order to hold Abington Quarter as a branch of the Yearly Meeting of Friends;
and a number of men and women Friends, as I understood, accordingly stopped,
but as it was late, they adjourned to the succeeding morning.
When Friends met at the house, they found the doors secured,
and a collection of persons on the ground, determined they should not enter the house.
Some of the elderly and infirm women were furnished with cushions to sit on the ground,
while the rest stood, and remained about an hour.
Ann Jones knelt on the ground, in supplication, supporting herself by a tree.
Finding there was no probability of gaining entrance to the house,
they drew up a statement of the circumstance; to be recorded on the minutes,
and adjourned, to meet at once, in Charles Shoemaker`'s mill.
About one hundred men and one hundred and seventy-five women Friends convened in the mill.
They appointed clerks for the day,
made a detailed record of the disorderly proceedings of the Separatists,
at Abington Quarterly Meeting;
and appointed various committees to carry into
effect concerns which engaged their attention.
It was said to be a very affecting and tendering opportunity,
much to the comfort and strength of Friends.

In the Tenth month, the Separatists held what they termed Philadelphia Yearly Meeting,
at the Green Street house; and concluded to hold it next year,
on the second second-day in the Fourth month;
which would be in the week preceding the Yearly Meeting of Friends.
Before our Yearly Meeting commenced,
the Meeting for Sufferings believed it right to prepare a statement of the separation;
the gradual progress of the Separatists, in some of our meetings,
to obtain the ascendency; and the unsound doctrines preached and printed by some of them;
which latter were contrasted with the doctrines of Friends on these points.
This was united with, to be laid before our Yearly Meeting of 1828, for its judgment;
and if approved, to be signed by the clerk on its behalf.
When read in the Yearly Meeting, our aged friend, William Jackson,
expressed his thankfulness that there were those raised
up and qualified to prepare such a document;
and it received the unity of the meeting,
and was afterwards printed and largely distributed among Friends.

The Yearly Meeting of Ohio, held in the autumn of 1827,
having made a proposition to the other Yearly Meetings in this country,
to appoint delegates,
in order to hold a Conference on the state of our religious Society, our Yearly Meeting,
held this spring, appointed a number of Friends to represent it in that body.
I went in a carriage with our friends Thomas Stewardson and Samuel Bettle, and my father,
to Mt. Pleasant, Ohio, to attend this Conference;
where we put up at the house of our beloved friend, Jonathan Taylor.
Representatives from all the other Yearly Meetings, except New York,
were also in attendance; and in the course of the week, a Conference was held;
but all the Yearly Meetings not being represented, nothing definite was concluded upon.
Opportunity was, however, given for an interchange of sentiments,
and to judge of each other`'s views in relation to such a convention,
and what might be its probable influence on the Society.

The first sitting of the Ohio Yearly Meeting of 1828, was a very disturbed one.
Friends adjourned to assemble next morning, at the usual hour.
The Separatists met earlier, and took possession of the house,
keeping Friends in the yard, where they held a meeting, standing.
After a suitable time, they adjourned to the old house at Short Creek,
rather less than half a mile distant.
The weather being warm, the sash were taken out of some of the windows,
and temporary seats were placed at each end,
to accommodate the men and women who could not get into the house.
The meeting was prolonged into the next week;
a time being fixed for the Conference to meet in Philadelphia, next year.
As soon as we could leave, our company took carriage and returned to our homes.

In 1829, representatives of all the Yearly Meetings of Friends in America,
convened in Philadelphia, and drew up a document,
on the doctrines and testimonies of Friends; which they denominated,
"`The Testimony of Friends in America.`"
In the year 1830,
Philadelphia Yearly Meeting declined repeating the appointment of delegates.
Time has clearly showed that this decision was a right one.

In the year 1829, and in the First month of 1830,
I obtained minutes from the Monthly Meeting,
and paid religious visits to the meetings of Haddonfield,
Concord and the Western Quarters which I accomplished to my own satisfaction.

On the 27th of Tenth month 1830,
I obtained a certificate to attend North Carolina Yearly Meeting,
and a few meetings belonging to it, having Henry Cope as companion.
We proceeded to Baltimore, and on sixth-day morning took steamboat for Norfolk,
where we arrived early on seventh-day.
The blacks about the town, who, we were told, were mostly slaves, appeared cheerful.
There was, however, a schooner lying in the stream, crowded with those poor creatures,
intended for the New Orleans market,
to which they are exported from Virginia as an article of trade.
It was an affecting spectacle,
which would have aroused the commiseration of John
Woolman and Anthony Benezet to a great degree.
Such is their degraded state of mind, having been brought up as though they were brutes,
and treated as if they had no souls, that at the distance we passed them,
they appeared indifferent to what awaited them.

We took the steamboat, going up the James river, and after landing, rode to Petersburg,
where we were detained until next day, much to our disappointment.
We then had difficulty in procuring our passage in the stage,
because of many persons going to a horse race; whose company was unpleasant, especially,
during the time we rode with them in the night.
We were all the next day reaching Greensburg,
and next morning got to a Friend`'s house at New Garden.
As he had no carriage to convey us to Deep river, he sent a boy to pilot us,
and we walked to the meetinghouse, about seven miles;
where we attended the Meeting of Ministers and Elders, and their first-day meeting,
which was large.
We lodged at Abel Coffin`'s, who conveyed us on second-day to New Garden,
where the Yearly Meeting was held.
Our lodging was about a mile from the meetinghouse;
the Friends were kind and hospitable, and we had the agreeable company of Nathan Hunt,
Jonathan Taylor from Ohio, and sometimes of Asenath Clark and her husband;
Isaac Hammer was also a short time with us.

The young people in attendance at this Yearly Meeting were very generally plain,
and becoming in their deportment; and as far as I could judge,
not a few of the young men possessed religious attainments,
and are concerned for the promotion of the good cause,
and the proper support of our testimonies and discipline.
The meeting sat daily about four hours; and every morning, except second-day,
either the Meeting for Sufferings, or that of Ministers and Elders,
convened at nine o`'clock; which kept us pretty steadily in the meetinghouse.

Third-day was set apart for investigating the state of the subordinate meetings.
They had read all the reports, including the answers to the Queries, read on second-day;
and the clerks having prepared a summary, the partition shutters,
between the men and women, were opened; so that both might hear each other`'s answers,
and the observations made by men and women Friends on different subjects;
and upon the whole it was a satisfactory time.
They agreed to address an epistle to the Quarterly and Monthly Meetings,
to incite the members to more faithfulness.

The state of education within their limits being brought to view,
we took the liberty of proposing,
that the Quarterly and Monthly Meetings should be instructed to send up, next year,
explicit accounts of the number and description
of schools within their respective districts;
which was adopted and appended to the epistle.
They were desired to state whether the teachers are members,
and what proportion of the scholars are the children of Friends.
We also endeavored to press the importance of home education;
the necessity of parents feeling and manifesting a religious
interest in the improvement and preservation of their children,
by taking frequent opportunities with them,
in reading the Holy Scriptures and other religious works.
Some notice of this branch of the concern was placed in the epistle;
advising retirement and silent waiting upon the Lord in their families.
They were also urged to cultivate their minds by
reading other useful books of a historical,
descriptive, or scientific character.

The Yearly Meeting closed on fifth-day after a long sitting.

Next day we were conveyed to J. Stanley`'s,
and attended the Select Western Quarterly Meeting, there.
The Quarterly Meeting next day, was a larger company of Friends than we expected to see.
I felt peaceful in the part I had in it; and in the second meeting,
we encouraged the young men and others to faithfulness in their respective duties,
so that they might become prepared to maintain the discipline and our testimonies.

Next day we parted from our beloved friend Jonathan Taylor,
with whom we had sojourned several days very agreeably;
and on first-day were at Springfield Meeting,
where we lodged at Nathan Hunt`'s.
From there to Kennet, Hopewell and New Garden.

After finishing what rested on my mind, we took stage at Greensburg,
through the upper route to Fredericksburg, Washington, Baltimore, etc.,
and reached our homes safely and with peace.

[.offset]
+++[+++From this time until Ninth month 1835, no memoranda appear to have been preserved.
In Seventh month 1831, W. Evans obtained a minute from his Monthly Meeting,
to visit the meetings belonging to Abington, Bucks, Burlington,
and Shrewsbury and Eahway Quarterly Meetings;
all within the limits of Philadelphia Yearly Meeting.
In Seventh month 1833, certificates were granted him to visit, as way might open,
the meetings of Friends within the limits of New England Yearly Meeting,
more particularly those constituting the Northern and Eastern Quarters.
In this journey he had Joseph Snowdon as companion.
From letters written to his family during his absence,
the following extracts have been made:]

Eighth month 21st, 1833.
"`Beached the house of our friend Estes Newhall, at Lynn.
Attended the meeting here.
Went to Salem next morning; the meeting small.
A qualification was furnished to open a little
the spirituality of the Gospel dispensation;
and to invite to an investigation how far we, who are making a high profession of it,
are living under it, and experiencing its redeeming and sanctifying efficacy.
The opportunity was serious, and satisfactory to myself.

28th. "`I wrote you from Berwick, just before we went to their meeting;
which we attended in peaceful silence.
At Oakwood, in the afternoon, a company assembled in a private house.

To me it was the most suffering time I almost ever passed through;
the way opened to express a little, towards the time for separating.
Next morning we rode to Elliott, a very small meeting.
Here the spring of the Gospel was a little opened.

On parting with the Friends where we dined,
the importance of the right education of their children,
and the necessity of being good examples ourselves,
was attempted to be impressed on their minds.
From this place we went to a Friend`'s near Rochester meetinghouse.
This meeting was little larger than Elliott.
Some qualification was felt to labor with them,
in order to draw them to the Spirit of Christ in their own hearts; to learn of Him,
and to take his yoke upon them;
by which they might realize the substance of the religion they professed.
It is not every one who is to be helped by us; if there be one here and another there,
who are quickened a little in the journey towards the good land, we must be satisfied,
and leave the work to the Master.

30th. "`Reached Wolfsborough,
and found the letter requesting the appointment of a
meeting for us on seventh-day had not been received.
Some exertion was made to spread notice, but the company was small;
the number of families composing the meeting being few,
and not many of other professions.
I passed the meeting in silence.
At Sandwich we heard of our silent meeting at Berwick;
a person told there were six preachers at it,
and he thought it was the stillest meeting he had attended for some time;
nothing being said by any of them.
I felt quite satisfied with the part I had in the meeting;
believing there is as much necessity of holding
up the testimony of Friends to silent waiting,
as to preach the Gospel when called to it.
Wolfsborough lies at the south side of a lake, which is twenty-three miles long,
and in the widest part, eight miles broad.
The scenery in various parts of the ride to Sandwich, and round that country,
is beautiful.
The prospect from many hills taking in a circuit of
twenty-five or thirty miles distance from the eye.

Ninth month 6th. "`At Raymond, a small meeting about sixteen miles from Windham;
notice having been given at the Quarterly Meeting for this and other meetings.

"`The scenery at Raymond is uncommonly grand.
On the east side of the road, running north and south, rises a range of hills,
from the top of which we have a very extensive prospect.
At our feet, on the west side of the road, runs a great valley; to the southwest,
Lake Sebago, several miles long; and to the south and east, an open, hilly country,
interspersed with large pools of water; and beyond the valley,
we see ranges of lofty mountains extending from southwest nearly round to the north;
the highest of which are the White Mountains of New
Hampshire in the northwest from where we stood;
Mount Washington, the highest peak, was distinctly in view.

7th. Went to Falmouth, where we were favored with a solemn, quiet meeting,
in which I thought the importance of silent waiting was
never more clearly and forcibly impressed on me.
It seemed proper to encourage Friends to faithful perseverance
in their silent approaches to the throne of Grace;
patiently waiting for the presence of Him, in whom was their delight,
that they might be strengthened to hold up a testimony to spiritual worship.
The next meeting being North Windham, we went back to N. P.`'s,
and on first-day morning attended it; the house below stairs being pretty much filled,
principally by those not of our Society.
Such meetings are often a close trial upon one`'s courage.
We often sit long before we can feel much solemnity.
I endeavored to deliver what arose in my mind,
but the stream had not such free course as is desirable.

In the afternoon we went to Gorham, and notice having been spread for several days,
the house, containing nearly two hundred persons, was almost filled,
with the exception of a small number, by persons of other professions.
My mind was pretty calm, though not without some fears about the result.
The people sat with the most becoming quiet, and after a season of inward,
reverent waiting, I rose with the expressions of the Apostle, '`We are the circumcision,
which worship God in the Spirit, and rejoice in Christ Jesus,
and have no confidence in the flesh.`'
The necessity of experiencing our religious performances to
proceed from the influences of the Holy Spirit;
and the blessing which flows from a life of true dedication to its government,
were opened; with many views appertaining to the Christian warfare;
encouraging those who had entered the straight gate, to maintain close watchfulness,
lest by the stratagems of an unwearied enemy, they might be again drawn aside.
I have seldom been more helped on any occasion.
It was cause of gratitude to our holy Helper and Caretaker,
who knows how to deal with us, to be thus furnished with evidence, in the time of need,
that He has not forgotten to be gracious;
and I desire to be preserved under a humble sense of my own nothingness,
and that all good must be derived from Him.

Ninth month 11th. Attended Yassalborough Quarterly Meeting.
The Select Meeting was much larger than at Windham;
the men`'s side more numerous than our own Quarterly Meeting.
It was an agreeable one to me;
the language of consolation being much more congenial to my feelings,
than that of reproof, though indirectly conveyed;
and which was offered in the endearing expression of our Lord:
'`As the Father has loved me, so have I loved you;
continue you in my love;`' which can only be expected
by faithfully doing or suffering his will.
The meeting for discipline was rather painful.
The way appeared to open, after we came upon the Queries,
to make some remarks upon the solemnity of the purpose
for which our religious meetings were held;
that they could only be profitable as the power and authority of Truth presided in them;
which was only to be expected,
as every one kept to the gift of Divine grace in his own heart, waiting on that,
so as to be preserved in his proper place in the body.
For the first time,
I was impressed with a belief it was right to propose going into the women`'s meeting;
a similar concern resting on my mind respecting them.
After enquiry was made of them, and men Friends uniting with it,
J+++.+++ W. was named to accompany me.`"

[.offset]
+++[+++William Evans and companion then attended meetings at St. Albans, Albion and China.]

Ninth month 18th. "`Attended Yassalborough Monthly Meeting.
We were brought into tender feeling with some,
to whom the bread of adversity and the water of affliction had been dispensed;
and they were reminded of the reverses which Job experienced;
reduced as he was from the highest standing among men, though a perfect and upright man,
to sit in ashes; and yet, in all this, he did not let go his integrity;
but when advised by his companion, to curse God and die, he reproved her,
as speaking foolishly, and said, '`Shall we receive good at the hand of God,
and shall we not receive evil?`'
That these very afflictions would contribute to
prepare us for vessels in the Lord`'s house,
where there were those of honor and dishonor.

I thought some in keeping their places,
might not be esteemed by the uncircumcised in heart and ear, as honorable as some others;
yet it was highly important they should keep their places,
discharging their duty faithfully in the sight of the Lord.

Ninth month 30th. We are progressing daily in the
accomplishment of the work for which we left our homes;
and have good reason to believe, that the Shepherd of the sheep has been with us,
uniting us more closely to Him,
and in near fellowship with those who love Him in sincerity.
Friends are very kind and affectionate to us,
willingly conducting us from meeting to meeting, and manifesting a readiness to attend;
also people of other professions, when they hear of them, freely come;
though our invitations are simply to Friends,
and such as usually frequent their meetings.

Tenth month 3rd, 1833.
"`Yours of the 24th, we found at S. F. H.`'s, on our arrival yesterday,
giving the affecting intelligence of the increasing disease
and suffering of our daughter R. +++[+++A child of eight years,
who was suffering with disease of the hip, which terminated her life,
in the Eleventh month of 1836.]
Were it proper for me to return homeward,
I should be glad to aid in making her as comfortable as her situation would admit;
and if it should be your judgment, that it would be best to do so,
we would give up the remaining parts of the proposed visit.
It was very pleasant to find by your letter that the Good Hand is round about,
sustaining your mind in the accumulated cares of the family,
and the trial produced by the very affecting situation of a beloved child;
and I trust as we all endeavor to keep our places, that support will not be withdrawn,
but will be experienced, adequate to the labors of the day,
and the anxiety and sympathy which must attend our present circumstances.`"

After leaving Yassalborough, We crossed the Kennebec river,
and were at a meeting appointed for us at Sidney; it was rather a heavy, laborious time.
Then rode to Belgrade, piloted by P. P. and wife.
He is the Nantucket whale-man,
who caught the whale which his men had struck thirteen years before,
and had left a part of the harpoon remaining; with which it then escaped,
and which they found on cutting it up.
The harpoon was stamped with P. P.`'s initials.

Belgrade Meeting was held in a private dwelling, and though not large,
was a solemn opportunity.

Attended Winthrop Meeting, which was a mournful time;
under a persuasion that the standard-bearers had lost ground,
through the love of other things than the blessed Truth.
In the afternoon, held a meeting at Litchfield, which was large;
and a favored time it proved, the spring of the ministry being, as I believed,
freely opened, and the people conducting in a solid manner.

Attended Pownall Meeting, where, as on one or two other occasions,
we had to deal with some Universalists;
whose principles are as dangerous as any other infidel doctrine,
and which they are seeking to spread.
Rode down to Portland and lodged.

Today (Tenth month 3rd,) attended their meeting in silence.

[.offset]
+++[+++After attending meetings at Cape Elizabeth and Berwick,
William Evans and companion proceeded to Meadersborough,
where they were detained a few days by the indisposition of the former.
Here, he writes to his wife:]

"`Home came up frequently, with the sufferings our daughter is enduring,
and the labor and care which devolve upon you;
but it did not seem as if our work was finished,
however unimportant it may be in the great scale of affairs.`"

Tenth month 11th. "`An appointed meeting at North Weare.
In the afternoon, rode over to Henniker, accompanied by T. D., in his eighty-first year.
We found his residence a model of simplicity; everything very plain,
but very nice and clean.

Their manner of living is of corresponding character.
They consume, either in clothing or food, but little they do not make or raise; and,
sitting at their table, everything seemed to partake of such purity,
that it reminded me of patriarchal times.

T+++.+++ D. was enlisted for three years in the revolutionary war;
was at Cambridge during the battle of Banker`'s Hill; but was not in any engagement,
though he was anxious to kill many of his opponents.
When his eyes were opened to see the anti-christianity of war,
he found he had been under a delusion;
and was thankful he had never been permitted to destroy a fellow creature.
He has been among Friends about forty years.

We attended the first-day meeting at Unity; the morning wet and cloudy,
which probably occasioned it to be small;
but we had cause for gratitude to our Lord and Master, for the extension of his goodness;
affording renewed help to advocate his cause,
after a time of long watching and waiting for his Divine presence and quickening power.
On second-day afternoon, attended the meeting at Henniker.
A lack of religious exercise, too often evident in our meetings,
produced sorrowful feelings; and the fear that, as in other places,
there was a deficiency in the right qualification to
maintain our testimony to spiritual worship.
The way, however, opened to show the effect of true religion,
in leading into a deep inward travail of spirit, for the salvation of our immortal souls;
and that as this was our situation, when we came together in our meetings, a united,
harmonious labor would be experienced, for the prevalence of the Divine life among us.

I hope your next will give the desirable intelligence,
that the acute sufferings of our afflicted child are mitigated;
and that your anxious labors and watchings are lessened; it would cheer me much,
and encourage to try to finish what little work I might have to do.
But we cannot change things when we may please;
and to be favored with fortitude and proper resignation to bear our lot,
will promote our comfort and best interests.

How many are enduring afflictive bereavements or painful suffering;
and while we are in the body, I anticipate little else than trial,
mortification or affliction of some kind.
If it work for us a far more exceeding and eternal weight of glory,
this will outbalance every possible tribulation we can here endure.

It is, however, not necessary to be constantly dwelling on the gloomy pictures of life;
let us gird up our loins and try to keep our lamps burning,
so as to be ready to open to our Lord at his coming;
and all those servants whom He finds thus watching, He will command to sit down to meat,
and come forth and serve them himself.
And thus we shall as we pass along, realize the blessedness of the religion we profess,
to sustain in the hoar of trial,
comfort and cheer with Divine consolation from time to time,
and furnish in the end with a blessed hope of everlasting rest and peace;
where all sorrow ceases, and God shall wipe away all tears from every eye.

Tenth month 16th. "`Attended their Select Meeting at South Weare.
Towards the close,
the way opened to call the attention of Friends
to the foundation of our religious meetings;
that being wearied with the lifeless performances of the day,
which were no better than husks to them,
our early Friends sat down in silence to wait upon the Lord;
not daring to engage in vocal communications,
without the putting forth of the Shepherd of the sheep;
that it was indispensable we should keep to the same ground,
if the ministry is preserved a living ministry,
proceeding from the spring of Divine life, which would water the flock, etc.
Next day attended the Quarterly Meeting.

We have hardly sat a more laborious meeting of that kind.
I said nothing before the shutters were closed.
After the meeting for business was ready for closing,
it seemed proper to make some allusion to the difficulty with
which our chariot wheels had dragged that day;
and to urge it as an incitement to more zealous, individual concern;
to apply for wisdom and strength for managing the affairs of the church; which,
no more than Divine worship, could be rightly performed,
but by the aid of the Holy Spirit; the influence of which was to be lived under daily;
as we could not expect it when we came together,
if at other times we were so absorbed with the
world as scarcely to remember our religious duty,
until such occasions recalled it.
Our discipline is an excellent institution;
but not like a machine that could be set in operation by the ingenuity of man;
the same wisdom that instituted it was to be waited and sought for,
in the various duties to be performed by the different members.
I felt for the young people, lest they might be discouraged by such seasons;
but exhorted them to come to Christ in their own hearts,
that they might be taught and prepared by Him for his service in the church;
and be preserved from having all their faculties absorbed by the world;
be enabled to keep their duties in their proper places;
having their hearts lifted up to Him in the heavens,
while their hands were necessarily engaged in their lawful occupations;
and thus He would qualify them to stand in those
stations He would allot them in his church.

Sixth-day morning set out for Concord,
and there held a meeting with the few who assemble in that place; several Friends,
on their way home, also attending.
It was a good meeting;
the language of sympathy and encouragement towards the few who lived there, was held out;
to keep their eye over all discouraging prospects, to their divine Master,
who would sustain in times of conflict;
and make a way for them to escape every trial and temptation with which they were beset,
as they relied on Him.
The spirit of infidelity came very unexpectedly into view;
and a warning was given of the awful consequence which must result from it,
unless repentance and forgiveness were timely experienced.
The meeting closed with supplication for our preservation and
support through the conflicts we may have to endure.

21st. "`Held a meeting at Gilmanton, which, in the forepart, was very exercising,
from the belief, that the desire for words was too prevalent here,
as in some other places.
After long sitting, it seemed proper to say, I hoped the time would not come,
when we should either be ashamed or incapable of
holding our religious meetings in solemn silence,
whenever it was the will of the great Head of the church that they should be so held.
After adverting to the circumstance of our first
Friends being withdrawn from a lifeless ministry,
and the ceremonies of that time, to sit down under the teachings of Christ;
the nature of Divine worship, as set forth by Him,
in the interview with the woman at Jacob`'s well, was a little opened;
and the necessity of experiencing the efficacy in ourselves,
of the religion we were making profession of, was enforced;
which I have found it much my place to do, wherever we have been.

We are getting very outward, full of doctrinal knowledge;
but where are the fruits of our principles?
Tenth month 23rd and 24th.
Attended the Quarterly Meeting at Dover, which was large.
Through the mercy and kindness of the Shepherd of the flock,
we were favored with a solemn meeting;
the way opening to take leave of them and the extensive tract we have travelled over,
with relieved and peaceful minds.

Went to Seabrook on seventh-day afternoon.
This meeting was once large; and many of the members eminent among Friends.
Comfort Collins, who lived to the age of one hundred and five years, belonged to it.
We attended the meeting, now reduced to three or four plain men, and eight or ten women.

"`In the afternoon rode down to Amesbury; and, to our surprise,
found we were to hold a meeting in a manufacturing town.
We had been told it was a very small meeting; and, supposing it to be a country place,
consented to the proposal to have it in the afternoon.
When we went to the house, we found it filling up with all descriptions of people,
nothing like Friends;
scarcely any present who knew much about the proper exercise for such occasions.
I saw no other way than to cast ourselves upon
Him who only can enable us to meet difficulties,
with the hope the cause might not be permitted to suffer;
there was some ability furnished to preach the gospel of salvation to them.
The company sat very still and attentive.

[.offset]
+++[+++After attending several meetings in the eastern and southeastern parts of Massachusetts,
and on Nantucket, William Evans writes, under date of Eleventh month 14th:]

This afternoon returned to New Bedford, and found a letter from brother T.,
which gives a much more unfavorable view of our dear daughter`'s case;
and I think I shall be easy, after being at two meetings,
appointed for sixth and seventh-days, and at New Bedford on first-day,
to set off for Newport on second-day morning; take the steamboat there for New York,
+++[+++and from there to Philadelphia.]
"`I have felt incapable of taking satisfaction in anything,
since I received the affecting intelligence of our beloved child`'s situation;
excepting in the evidence, I think I have had, from place to place,
that the blaster was with us;
this has made me hope that our child would at least be
continued until I was favored to reach our residence in peace.
It would be a close trial to me, indeed, not to be permitted to see her face again;
but I cannot be persuaded yet,
to think I shall not be with you some time before the final event;
if it be not consistent with the Divine Will to restore her.
No one knows the feelings I pass through daily at being detained from you;
it seems as if I could not stay;
and yet I have not been able to see that the time had come to take my departure,
until this afternoon.
In looking back at the original prospect, it appears to be pretty much accomplished;
excepting four meetings in this Quarterly Meeting,
and four or five in Rhode Island Quarter, which I had intended to visit.`"

[.small-break]
'''

+++[+++William Evan`'s minute, with endorsements, was returned to his Monthly Meeting,
Eleventh month 27th, 1833.

1834,
Ninth month 24th. A certificate was granted him
to attend the next Yearly Meeting of Friends,
to be held in Baltimore.
This was returned, Eleventh month 26th, of the same year.]
