== Chapter VI

[.chapter-synopsis]
* 1835+++.+++ Religious visit to Friends in the Eastern parts of New York, and in Vermont.

I having obtained a certificate from the Monthly and the Quarterly Meeting,
of their unity with a concern I had felt for several months,
to visit the meetings of Friends in the eastern side of New York Yearly Meeting,
I set out on the journey on the 18th of the Ninth month, 1835;
having for companion my beloved friend Joseph Snowden, who had a minute for the purpose.

Leaving a beloved wife and family of children, naturally awakened peculiar feelings,
on account of the increased weight of the charge of all
the domestic concerns devolving upon one head,
and the reflection, that while we travel abroad to promote the welfare of others,
temptation surrounds our own children;
by which they may be led into things unbecoming our profession; and thereby,
if yielded to, bring reproach upon the blessed cause which we espouse.
But after receiving the unity of Friends,
there appeared to be no other right course but to commit them
all to the protection and care of the Shepherd of Israel;
trusting that when He does lead forth into service,
if we endeavor to discharge our duty to them faithfully, while at home,
He will be round about, and guard them from evil and from danger.

We reached the residence of that worthy mother in Israel, Ruth Ely, near New Hope,
that evening, where we were very kindly and agreeably entertained.
The company of those who feel a deep interest in our religions Society,
and are capable of estimating its usefulness, and its weaknesses, is very interesting,
and deservedly valued.
On the following day we rode to N. Y.`'s, at Plainfield,
and attended their meeting on first-day; which was rather dull and heavy,
too few being willing to enter into labor for themselves.
The spirit of speculating in property having
prevailed in and near some of our large cities,
seemed to have had its influence here;
conversation frequently running upon the sale and increased value of land.
Although the first-day of the week is set apart for religious retirement and meditation,
yet making money would come up, and show that it was a prime and absorbing subject.
Its effect is sorrowful upon old and young;
leading one into the fashions and vanities of the world,
and producing spiritual dryness and even death in the other.
We took tea at J. S.`'s, and being alone,
had a little sitting with them in which the language of
sympathy and encouragement was freely offered;
his wife being a minister,
and appearing to need strength and courage to occupy her gift faithfully.

N+++.+++ Y. kindly piloted us to Newark,
where we fed our horses and made enquiries after the best route to Blooming-grove,
and proceeded; putting up that night at a tavern, being forty-one miles from Plainfield.
Third-day morning, 22nd, set out and rode through a mountainous country,
passing several iron works and factories; the road was very good.
After dining, eighteen miles on, we obtained directions,
and went nine miles further to D. B.`'s, at Blooming-grove.
He is an elderly Friend, who, with his family, joined the Society;
they live very comfortably in a plain manner, and entertain their friends well,
and with a good will.

Notice was spread for a meeting with Friends, and those who usually attend,
to be at the eleventh hour, fourth-day morning.
The company was small, considerable part of the members having gone off with Elias Hicks.
The importance of silent, patient waiting for the arising of the life of Truth,
to qualify for every act in Divine worship, was much impressed on my mind;
but there seemed little qualification to say anything.

Some became restless, and a Friend, who, I was afraid, caught that feeling,
rose and urged the people not to look to man, whose breath was in his nostrils,
but to Him alone, who could give the bread of life.
The advice was good, if it proceeded from right authority, but it rather distressed me.
He took his seat, and after sitting a few minutes rose again,
and enlarged in the same strain.
I then thought we should soon close the meeting without any thing further;
but in looking towards that,
I was fearful of omitting to disclose the exercise which had attended my mind,
respecting the importance of practicing silent, patient waiting upon Christ,
for the renewal of our strength, and ability to do his will, whatever it might be.
In this humble engagement, we should find that without Him we can do nothing;
and however active man may be in things very proper to be done, when He commands,
yet without this renewed unction, all will amount to nothing.
The nature of true, spiritual religion;
the cleansing operation of Him who now sits as a refiner`'s fire,
and as a fuller with soap; and the participation of the supper of the Lord,
by opening our hearts to Him, was a little dwelt upon.
Some Methodists were there, and some of us, may have needed such views to be held up.

In the afternoon we rode to Canterbury, near the North River,
and put up at N. A.`'s.
He and his brother, sons of S. A.,
are largely in the brick-making business.
They employ simple but ingenious machinery in working up and mixing the clay and sand,
and a small proportion of fine anthracite coal to form the brick;
and another contrivance by which the prepared composition is pressed into the moulds;
turning out four bricks every compression.
Two of these machines, with the aid of six men and six boys,
make about 19,000 bricks per day, after the clay is prepared by others.
On fifth-day the 24th, we attended the Monthly Meeting here, called Cornwall,
of which that effectual minister of the Gospel, David Sands, was formerly a member.

We passed his residence in going to the meeting-house;
it has an air of ancient simplicity and comfort; being a long one-story building,
with a high roof, admitting of lodging in the attic story.
His ancient widow, about ninety, walked to the meeting, over quarter of a mile.
It was a small company of Friends for a Monthly Meeting; constituted of Blooming-grove,
and Cornwall Preparative Meetings.
The need of steadfastly abiding upon the watch,
in order to escape the captivating snares of the enemy, was held up to view,
in the injunction of our Lord,
"`What I say unto you, I say unto all, watch!`"
"`Watch and pray, lest you enter into temptation;`"
for though the spirit may often be ready, the flesh is weak.
It appeared to me that the lawful things of this world were to be watched against;
though all things might be lawful, they were not all expedient;
and the Apostle declared he would not be brought under the power of any.
Some appeared to be in danger of being so absorbed in worldly pursuits,
as to live in almost total forgetfulness of the Giver of every outward blessing we enjoy,
and consequent neglect of the soul`'s salvation.

These were invited to return to the watch-tower,
and take heed to the voice of the true Shepherd;
that they might be again brought out of bondage into the liberty of the children of God.
It was a pretty open time.
The widow Sands expressed her belief that the Lord had
not left Himself without witnesses to the Truth,
and desired that each might take that which applied to them.
Their business was passed through with but little expression,
though five Queries were answered.
I thought it proper to urge the right and due support of the discipline,
in the spirit and wisdom by which it was instituted;
as the health of the Society would be materially influenced by it.
The sentiments were accorded with by two Friends.

At Newberry Valley, fourteen miles further,
we had an appointed meeting on the following afternoon, at two o`'clock.
It collected very irregularly, which kept up a state of unsettlement for a long time.
Feelings of poverty and desertion, and a fear whether it would be held to profit,
crowded into my mind; but after a time of inward waiting,
and looking to the Master for his direction,
it seemed right to stand up with the expression,
"`None of them can by any means redeem his brother,
nor give to God a ransom for him;`" neither could we become
partakers of that redemption which comes by Jesus Christ,
unless we were individually concerned to enter into labor in our own hearts,
under the aid and direction of his Holy Spirit;
that sanctification may be effected in us.
It was a solemn opportunity;
in which the necessity of working out the salvation of the soul with fear and trembling,
and the certainty that everlasting separation from the redeemed,
will be the portion of the rebellious who die unforgiven, were feelingly expressed.
We lodged at the house of a Friend, and in the morning,
had a short sitting with the family:
in which the heads were encouraged to occupy faithfully the gifts bestowed on them,
whatever they might be, not trusting in their own strength.
It seemed to me,
that the wife was called to more open acknowledgment of the side she ought to take;
perhaps, in publicly espousing the cause of Truth.

A meeting being appointed for us at Marlborough, we rode over to it, seven miles.
The company was small; and though in the forepart of the time,
several passages of Scripture instructively presented,
and seemed as if they were very suitable for communication,
the feeling gradually subsided, and no intimation to offer them being distinctly felt,
we closed the sitting in silence.
The subjects were the necessity of the fruit-bearing branches being purged; and,
also that of stillness, before the Searcher of hearts, that we may know Him,
and his manner of dealing with us, and thereby renew our strength.
I think I was willing to speak or be silent, as the Master should order,
and afterwards hoped these openings might tend to my own benefit.

Rode to Jacob Heaton`'s in the afternoon, and attended Plattekill Meeting on first-day.
Notice having been spread through the neighborhood,
the house was pretty well filled by Friends and others.
The distinction between John`'s baptism and that of Christ, the former being with water,
and the latter with the Spirit,
each designating the nature of the dispensation to which it appertained,
was held up to view.
One decreasing must come to an end, and the other increasing must overspread all;
and as the Apostle declares, that to us there is but "`one Lord,
one faith and one baptism; one God and Father of all who is above all,
through all and in you all;`" this baptism must be that of Christ,
which is with the Holy Ghost and fire: it is therefore essential,
that the professors of his name should deeply and
frequently examine whether they are submitting to it,
and thereby witnessing the chaff and every defilement purely purged away;
so as to make fit temples for the Holy One to dwell in.
The work of regeneration, and the effects of it upon our lives, and conduct,
and conversation, were pretty fully treated on.
The meeting was quiet, and ended with a covering of solemnity.

After dinner, a few Friends coming in, we had a precious parting opportunity;
in which some, who I believed,
had been of latter time brought under feelings of increased seriousness,
were affectionately called upon to yield to those precious visitations,
and resort to nothing to divert their attention from Him, who has thus been drawing near,
to enlist them under his government.
We left these dear Friends with feelings of tender affection,
and desire for their growth in the Truth; and rode to W. M.`'s, at Paltz.
His house is placed on the side of a mountain,
and among a description of people not very suitable society for a young family.
The meeting was small, and a very trying one to my feelings;
so little heartfelt concern for their own spiritual welfare being apparent.
I endeavored to discharge my duty, in exhorting them to more zeal and diligence;
but we left them with little hope that Truth would soon prosper there.
When we see the young children of the principal Friend, fashionably dressed,
we cannot expect that the life of religion will be sought after and cherished.
I spoke to him upon the subject; which he appeared to take kindly,
and acknowledged he had yielded to it contrary to his judgment,
and thought in future he should be more firm.

Attended an appointed meeting at three o`'clock, at the Plains; which was also a low time,
though accompanied by rather more lively feelings than in the morning.
We lodged at a Friend`'s house;
and in the morning had an opportunity with him and his daughters,
who had lost their mother about a year since, and one of them her husband;
in which sympathy was felt with them in their bereavements,
and the young women affectionately counseled to follow their mother,
as she had followed Christ.
Then set out for Dutchess County; crossed the North River at Poughkeepsie,
and went to the Creek, to the residence of our kind friends, Smith and Sarah Upton;
who received and entertained us with much cordiality.

The next day, being the last of the Ninth month, we attended their usual mid-week meeting.
It was much reduced by the absence of several members, summoned to court at Poughkeepsie.
Some of the little company, according to my feelings,
were partaking of poverty of spirit, and under suffering of a close nature.
We sat long in silence,
when it seemed proper to address them with the language of Christ:
"`Blessed are you poor, for yours is the kingdom of God.`"
I hoped that the Master was present with us, to comfort them that mourned;
and that in his time, He would give to such, "`beauty for ashes;
the oil of joy for mourning; and the garment of praise for the spirit of heaviness.`"
We passed the remainder of the day at S. Upton`'s, with his wife;
Smith being at Poughkeepsie.
It seemed like being with people who understood our language;
and with whom we could hold converse with freedom.

Tenth month 1st. Accompanied by our beloved friend,
we went to the regular meeting at Stanford, to which that worthy man,
and dignified minister of Christ, Henry Hull, belonged, during his lifetime.
A qualification was here afforded, to preach the gospel of life and salvation,
through Jesus Christ our Lord, to some who had wandered from the footsteps of the flock,
into a far country, where they were perishing with hunger;
and destitute of all hope of any solid comfort or peace.
They were pressingly invited to receive the everlasting Shepherd,
in his offers of help to restore them to the Father`'s house and flock.

It was a season of favor;
and we had reason to believe that the states of some were closely spoken to.
Returned in the evening to S. Upton`'s; and on sixth-day morning,
he piloted us to little Nine Partners; a very small company;
but it was rather a comfortable opportunity: dined at the house of an aged Friend,
who is a great landholder and very extensive farmer, having large flocks of sheep,
and many fat cattle.
Before we left his house,
I was most easy to spend a little time in silent waiting with him and his daughter;
and the necessity of preparing for the midnight cry, presenting forcibly, I endeavored,
in a way becoming my youth and his age,
to impress the importance of being broken off from his worldly pursuits;
and experiencing his affections set on things which are above.
As we brought nothing into this world, certain it is,
we can carry nothing out and neither corn, the finest wheat, the largest flocks,
nor the richest land, can procure for us the oil of the kingdom,
with which our lamps should be replenished.
It appeared to have a tendering effect; and the old man parted with us affectionately.

We then rode about six miles to North-east.
Notice having been spread, we had a meeting with Friends and others of the neighborhood,
on seventh-day.
As is often the case, some were restless, in the forepart of the time;
being accustomed to hear preaching at their own places of worship;
but the parable of the sower, and the different soils into which the seed was cast,
presented; and after waiting for the putting forth of the good hand,
it was opened to them; and with instruction to myself also.
We had cause for renewed thankfulness to our blessed Master for his aid,
and the solemnizing influence of his presence.
After dining, we sat with the family of the kind Friend, at whose house we stayed,
and the tendering invitations of Divine love were renewed to some of his
children--whose appearance was not sufficiently conformed to the simplicity
of the Truth--to take up the cross and openly confess their dear Lord,
in plainness of dress and address, and in the fruits of a meek and quiet spirit.
It seemed to me that Grace had been at work,
in bringing some of them under more serious thoughtfulness, than at previous periods.

We then returned with S. Upton to his hospitable mansion--twelve miles.
On first-day we attended their meeting;
where we had also the company of a number not belonging with Friends.
Here it appeared proper to hold forth the doctrine, that true religion is an inward,
silent, progressive work; its beginning is small,
being compared to a grain of mustard-seed, the least of all seeds;
but as it is suffered to take root in the heart,
will eradicate all other plants that produce fruit contrary to the Divine nature,
and eventually overspread all.
The incorruptible seed and Word of God is called by many names: as the Seed; the Light;
the manifestation of the Spirit; the grace of God that brings salvation,
and has appeared unto all men; and as man is passive, under its operation,
it will bring him from under the dominion of his evil passions and propensities,
in which Satan holds his rule;
and set up and establish the kingdom of heaven in his heart.
The subject opened gradually, and the meeting was clothed with much solemnity;
furnishing renewed cause for grateful, humble acknowledgment to the Master of assemblies,
for his Divine presence and assistance.
In the evening, we took tea with Isaac and Ruth Halleck.
He is nearly eighty-two years of age; his wife a few years younger,
and in the station of a minister.
He named several Friends of our Yearly Meeting, long since deceased,
and among them my grandfather, David Bacon; who, in company with some others,
attended a treaty with the Indians in this State.
Afterwards an old Indian undertook to give a character of those Friends,
to a Friend who visited them, and David Bacon,
he called a "`cleared field`"--meaning that he saw all around him.
Dropping into silence, just before we left,
the language of sympathy and comfort was extended to these ancient Friends;
who have passed through much domestic affliction; and yet to old age,
have been favored to hold on their way, and grow stronger in faith and confidence,
in Him, who was with the three children in the furnace, and delivered them,
so that the smell of fire was not found upon their garments;
and continues to be with his children now in their deepest afflictions.

On second-day morning, Tenth month 5th, accompanied by Smith Upton,
we set out for the meetings in Nine Partners Quarterly Meeting.
We stopped to see Anne Thorne, who was about to embark for Europe, on a religious visit.
She seemed quite cheerful.
While sitting with them,
I adverted to the necessity of keeping to the inward guidance of the Holy Spirit,
in all our movements; it was that which could alone preserve us,
whatever might be our stations in the church; whether fathers or mothers,
young men or children; and if we were permitted at any time to ride,
as upon the king`'s horse, we must return to the gate;
in a lowly dependence upon the Lord.
We were not to look on the countenance, or the height of the stature of any,
but our eye and expectation must be to the Lord alone, for his guidance and direction.
This was the ground on which our early Friends came forth,
and a doctrine the Society has ever held;
and it is only as we keep in humble reliance on the inward guidance of Christ`'s spirit,
that we can experience preservation.
She remarked that our coming in had reminded her
of the meeting of the Apostle and the brethren,
at the Three Taverns; and she trusted that we should remember each other,
when far separated.
We rode five miles to New Milford, where the meeting is held;
much of the way through heavy rain, which deterred several from coming.
This meeting, we were informed,
originated among a number of students at a college in Connecticut; who were, in measure,
convinced of the principles of Friends, by reading Barclay`'s Apology,
which they found in the library.
They met together for the performance of public worship,
before they knew where there were any Friends; and not knowing the practice of Friends,
some one of them exercised the office of preacher among them.
Hearing of a Yearly Meeting, held on Long Island, some went to it;
and becoming more perfectly informed of the church government established in the Society,
they became members, and this meeting was acknowledged by Friends.

In sitting with the company now meeting there, the impression attended me,
that there was more appearance of the Friend than an
experimental acquaintance with the work of regeneration.
The language of the Apostle, that "`All are not Israel that are of Israel,`" reviving,
I endeavored, in a plain but tender manner,
to hold up the necessity of examining and proving ourselves,
whether we be in the faith which gives the victory over the world,
the flesh and the devil.
That the outward profession,
without a living acquaintance with the inward work of sanctification, could avail little;
and the danger of deceiving ourselves with the opinion,
that we are better than we really are,
made it needful frequently to present ourselves as in the presence of the Lord,
that by his light we may see our true condition.
In the afternoon, we rode up a very long, steep hill, to Oblong,
to the house of Paul Osborne.
His father, now in the ninety-second year of his age, lives with him.
He retains his faculties and bodily powers in rather an extraordinary degree;
has no pain or disease; and never had much sickness throughout his long life;
he walks regularly to meeting, twice a week, distance half a mile.

We attended the meeting at Oblong, which was a heavy, dull time;
and being able to come at little feeling of life, and religious exercise among them,
concluded the sitting in silence.

Being the Preparative Meeting, and the time for answering five of their Queries,
some opportunity was furnished for calling the
attention of Friends to the reply to the Query,
respecting the attendance of meetings, and the manner of conducting themselves therein;
but not being able to divest myself of an impression to
have an opportunity with men and women together,
the partitions were opened, and, through the help of the Shepherd of Israel,
we had a tendering opportunity.
The danger of forgetting his mercy, who delivered us in the dark and cloudy day,
as out of the paw of the lion, and the paw of the bear, was impressed;
and Friends were called on to show forth in life and conversation,
and in the weightiness of their spirits,
the excellency of those principles which they professed:
but if those among whom they dwelt,
saw that they were engrossed with the things of the world; its comforts and pleasures;
it must tend to the sentiment,
that it made but little difference what our profession is.

Several very goodly young men and women were present; who appeared to have, in measure,
yielded to the convictions of Truth in their minds;
and the language of affectionate invitation was extended,
to treasure up in their own hearts, the sayings of their Lord to them;
to retire frequently, and enter into communion with Him;
to take up his cross and follow Him; and they would witness a growth in grace,
and come to be preachers of righteousness;
by which others would be drawn to unite with them, in walking in the same blessed path.
The necessity of a lively travail of spirit, when they assembled for Divine worship,
every one for himself, was brought into view;
this was the experience of Friends in the beginning; who sat down together in silence,
waiting upon the Lord, and not on one another.
As they gathered here,
He who declared Himself to be in the midst of the two or three who meet in his name,
broke in upon them, and melted and contrited their spirits,
and enabled them to offer praise and thanksgiving to his ever worthy name.

On fifth-day we had an appointed meeting at the Branch, now held at a private house.
It was a mixed company, Friends, a few Separatists, and a number not of us.
The labor was difficult; part of it being directed against an active,
self-confident spirit, ever ready to be doing;
on which account I thought some made opposition.
Christ`'s language at the marriage in Cana,
"`What have I to do with you? Mine hour is not yet come,`" etc,
and his direction to his immediate followers,
to tarry at Jerusalem, until they were endued with power from on high, were alluded to.
If they could do nothing without Him, who had seen his miracles, and been with Him,
but were to wait for power, it surely must be necessary for us All preaching and prayer,
without a renewed qualification, would avail but little;
it would leave the mind barren and empty.

Several expressed their satisfaction with the meeting;
but I did not feel as though the Divine unction as much attended and softened the people,
as at some other times.
Before we left our Friends, with whom we dined,
sympathy with them in the responsibility which attaches to their station;
at the head of a little company driven out of
their meeting-house by the spirit of Hicksism,
was expressed;
as well as the need of asking wisdom to lead the flock connected with them.
The prophet told Saul, he had done foolishly in offering,
for fear the people should be scattered;
and now it is needful to wait patiently for the Master, that whatever is done,
may be under his direction.

Sixth-day the 9th. Attended Beekman Meeting;
the house here is in the possession of Friends, but few having separated.
It is a Preparative Meeting, and now includes Oswego.
The company convened today nearly filled the house; and the advice of the wise man,
not to say that the former days were better than the present, was revived.
Notwithstanding it is our duty to commemorate the virtues of holy men, and women,
yet it is also needful to remember that the power which made them so, is unchangeable;
and as it is yielded to, will produce similar effects in our day.
It was by giving heed to the little requisitions of Truth,
that they grew in Grace from stature to stature; and in the same way must we,
if we come to an establishment on the same foundation.
They that are faithful in a little, shall be made rulers over more.
That night we lodged at the house of the widow of James Congdon, at Oswego;
it was an agreeable resting place.

Seventh-day 10th. Friends being deprived of their meetinghouse,
nearly all the members having joined with Elias Hicks, the few who maintain their ground,
meet at the house of the widow.
Several of those who met today were not members, and a few of them had been,
or are connected with the Separatists.
A lack of practical acquaintance with silent,
patient waiting for the springing up of Divine life,
sometimes makes it hard work for the few who endeavor to maintain that ground.
This was the case here; but after a time, the way opened to relieve myself;
though it required a patient, steady attention to the opening of the gift,
so as to communicate what was designed for them.
Tenderness spread over us,
and the meeting concluded with prayer for our individual preservation,
and strength to pursue the path of allotted duty faithfully.
After meeting rode to Isaac Thorn`'s, at Nine Partners.
Shortly after we got there, he arrived from New York, having accompanied his wife,
going there for the purpose of embarking for England.
She sailed on the 8th; and Hanna Chapman Backhouse also,
who had been in this country on a religious visit, above five years.

First-day 11th. We were at the meeting here, which was a large company for these times;
the children of the school being present.
The service today,
seemed to be for the purpose of encouraging those who
were favored with a knowledge of their Master`'s will,
to stand faithfully to it, notwithstanding the opposition they may have to meet.
"`All that will live godly in Christ Jesus, shall suffer persecution.`"
Even the adverse opinions of our most intimate friends are sometimes to be borne,
though they inflict great trial upon us;
yet it is our duty to keep firm to what is right, and in due time,
our opponents may be convinced and brought to unite with us.
The Apostle declared that,
"`If I yet pleased men I should not be the servant of Christ;`" our
business is to please Him that has visited and called us by his grace.
A qualification was graciously furnished to show the dignified standing of a true,
self-denying follower of Christ, let what may, come upon him;
and that as he keeps faithful, he will be built up and established on that Rock,
which is Christ; against which, the powers of darkness cannot prevail.
Some advice was also communicated to parents,
on the necessity of restraining their children, as well as counseling them.
The complaint against Eli was, that he had not restrained his sons;
and they both died in one day, and the ark fell into the hands of their enemies.
Similar danger awaited us.
The duty of obedience to all the lawful commands of parents,
was also enforced upon the children.

I was much disappointed in finding very nearly all the children in the school,
+++[+++under the care of the Yearly Meeting,]
dressed in a fashionable manner,
and that more than one-half of them were not members of the Society of Friends.
If the Yearly Meeting admits into its school such a departure from plainness,
the children who are placed there,
receive the impression that the Society regards dress as of little consequence.

Being naturally fond of finery, they will expect to be indulged in it;
and if a proper restraint is not maintained,
the example may spread a disadvantageous influence to other children in the Society.
As it is their practice to read in the afternoon, we sat with them,
and after several chapters of the Bible had been read,
the way opened to hold up the excellency of these inestimable writings,
and the advantage of daily reading them.

Every one has the gift of Grace, or the manifestation of the Spirit; a reprover,
and teacher which accompanies us wherever we go,
and knows the most secret thought and intention of the heart.
They were tenderly invited to mind and obey its convictions,
and it would bring them to love their Creator in the days of their youth;
and give them that peace which the world could not; nor could it deprive them of it.
We then set out for Pleasant Valley,
and were agreeably received and lodged at the house of a Friend, who, with his wife,
treated us very affectionately.

Second-day morning 12th. A meeting having been appointed at Poughkeepsie,
we sat with a small company who assembled there.
Much the larger part of the Society here, seceded;
and Friends had to build a house to accommodate themselves.

It proved a good opportunity; one of the young men was much broken into tears.
If any good is done, we have cause to be thankful to Him,
by whom alone it can be effected.
In prosecuting our religious duty in visiting meetings,
we are often assailed with doubt whether any good is produced by it;
and sometimes are ready to think, were it not for the purpose of doing what is required,
we might as well be at home.
Such feelings contribute to our humiliation,
and tend to keep us under religious exercise,
that our Divine Leader may continue with us,
and accompany what He may give for the people, with his baptizing power,
and thereby carry on his own work.
In the afternoon, we crossed the North River at Poughkeepsie.

On the following afternoon, we rode to Canterbury,
and attended Cornwall Quarterly Meeting, held on fourth and fifth-days.
In the Meeting of Ministers and Elders,
the situation of Israel abiding in their tents according to their tribes,
impressed my mind, as representing the members of the church,
keeping their habitation in the Truth; and every one filling up his duty,
allotted by the Great Head.
The subject was a little opened, to show the happy effects it has on them individually;
dwelling in a state of lowly-mindedness,
where they may know the dew of heaven to rest upon them,
and a growth to be experienced in the Truth.
In this situation they are prepared to be instrumental
in exalting the kingdom of the Messiah,
and to draw from others, the acknowledgment that they are a settled, substantial people;
inwardly gathered to the teachings of the Holy Spirit;
and against whom no divination or enchantment can prevail.
Some further remarks were made to awaken some to the great importance of silent,
patient waiting in our religious meetings; that they might not, like Saul,
attempt to offer any thing lest the people should be scattered.

In the meeting, next day, it did not appear to be my place to say anything.
When the Meeting for Discipline was about to close,
I thought it right to request the partitions to be opened;
that we might have a few minutes together.
The weak state of the Society was adverted to,
and the means by which it would be strengthened;
the importance of every one keeping in their own places, with a single eye to the Master,
that no one might put forth a hand to steady the ark unbidden; that gifts were dispensed;
to some the gift of discerning spirits;
and when any one misapprehends his or her service, and offered that which brought death,
such were to caution them, that they might be preserved;
and that those only who had experienced, in measure, the work of sanctification,
were suitable to take an active part in the discipline of the church.

Some Friends who attended the Quarterly Meeting, piloted us to Beekman, in the evening;
and early the following morning, we rode eighteen miles to Smith Upton`'s;
and that day attended the Creek Monthly Meeting, to satisfaction.
Our friends treated us with marked kindness,
being anxious to do everything they could to promote our comfort.

Tenth month 17th, seventh-day, we rode to Stanford,
to the house of our late beloved friend Henry Hull; his widow,
who had been on a visit south, when we were there before, having returned.
Attended the Monthly Meeting;
in which the need of patient submission to the sittings permitted to come upon us,
was feelingly opened; and the states of some who need it,
and of some who were partaking of such dispensations, were spoken to.
Sarah M. Upton, who accompanied us, appeared in supplication.

On answering the Queries,
it was evident that the maintenance of the discipline was much neglected;
and that cases of long standing had been suffered to remain unattended to.
The sound,
healthy condition of a meeting is much promoted by the
support and faithful administration of the discipline.

They admitted their weakness;
and I suggested the expediency of the overseers
from all the Preparative Meetings uniting,
and entering into a thorough investigation of the state of their members;
for where the discipline is not sustained, a meeting must decline.
It was approved.
Set off in the afternoon for Hudson, and got to the meeting on first-day.
Here we sat under a painful sense of the life of religion being low among them;
and that some who had known the visitations of Divine love, in time past,
had turned their back upon the Truth, and were pursuing their own ways.
The expressions of our Lord, that
"`Many are called, but few are chosen;`" and that
"`Many that are first shall be last, and the last shall be first;`" were brought into view,
and exemplified by the parable of the marriage of the king`'s son.
They were warned of the awful consequence of doing despite to the Spirit of Grace:
"`Seeing they crucify to themselves the Son of God afresh,
and put him to open shame;`" though should the period arrive when,
for fear of Him who sits upon the throne, and the wrath of the Lamb,
they might call on the rocks and the mountains to hide them, it would be in vain.
Several of the doctrines of the Christian religion were opened and enforced,
and a solemn covering came over the meeting.

Notice was spread for a meeting at two o`'clock, in the afternoon of the 19th, at Chatham;
to which the few Friends, who compose the meeting here, came.
Several others, not Friends, also attended.
The nature of Divine worship, under the gospel dispensation, was opened,
from the expression of the apostle Paul:
"`We are the circumcision which worship God in the spirit; and rejoice in Christ Jesus;
and have no confidence in the flesh;`" and according to the declaration of our Lord:
"`God is a Spirit,
and they that worship Him must worship Him in spirit and in
truth;`" for such "`the Father seeks to worship Him.`"
To offer acceptable worship, really and truly from the heart,
it must undergo a change from its fallen, corrupt state.
Everything proceeding from man, of himself, in this latter condition, must be impure,
and cannot find acceptance.

No fountain, at the same time, sends forth sweet water and bitter.
Regeneration, under the powerful operation of the Holy Ghost and fire, was enforced;
that the heart being cleansed and sanctified, offerings,
prepared by the High Priest of our profession,
may be offered to Him who searches the heart,
and will not look on iniquity or transgression.
In the course of the communication,
I had occasion to show the advantages of knowing our passions subjugated,
and brought under the contriting power of the Spirit of the Redeemer;
who prayed for the forgiveness of his enemies; that those who were not thus regulated,
were often carried away with gusts of passion; committing acts of violence,
which afterwards covered them with blushes and confusion;
but the true followers of Christ, when they were reviled, reviled not again;
and when persecuted, threatened not.

I was told, afterwards, that an old man, who was present,
was noted in the neighborhood for the uncommon violence of his passion,
and had disgraced himself on one or more occasions, by his conduct,
when under the terrible influence of it.
This meeting was rather a trying opportunity to me, and when closed,
I desired Friends to remain.
I endeavored to awaken in them a just sense of the importance of their situation;
and of self-examination;
whether the things of the world were too much engrossing their time and talents,
that through Holy help, they might become lights in their neighborhood;
and sitting down together in humble dependence upon the Lord,
be a means of drawing others to join with them;
their demeanor and the state of their spirits,
holding forth the invitation Come "`That you also may have fellowship with us;
and truly our fellowship is with the Father, and with his Son, Jesus Christ.`"

The situation of the few Friends here,
is very unfavorable for the right education of children.
What society they have, is mostly with those by whom their principles are endangered;
and their parents indulge them in dressing in a fashionable manner;
so that there is little prospect of a meeting being sustained here with reputation.

Tenth month 20th. We rode thirty miles to a house near South-Adams;
passing Lebanon Springs, and in sight of the Hancock settlement of the Shakers;
many of whom we met on the road.
From there through Hancock village, Lanesborough, Cheshire Corner, and South Adams,
where several factories are located, on a stream running to it.
Having no guide, though we found the route readily, our pilgrimage felt a little lonely;
especially as we now entered a section of country,
where but little attention appeared to be paid, rightly to cultivate the mind,
and raise it above the grovelling pursuits of earthly things.
The superior advantages of the members in our own beloved city,
where such various opportunities are afforded for improvement in every respect;
and where many are found availing themselves of these peculiar benefits, came into view;
and while it warmed up feelings of strong attachment to many there,
also raised desires that we might all duly prize our privileges,
and be found putting shoulder to shoulder in the work of the Lord.
I believe,
if the younger members of our Society do heartily devote themselves to his cause,
that a noble band will be raised up, from generation to generation,
to exalt the testimonies and discipline given us to bear;
and that the Lord will still make the place of his feet glorious among us.
He will glorify the house of his glory,
and dignify them that truly and steadfastly honor Him.

Fourth-day 21st. Attended Hoosic Preparative Meeting held here,
consisting of a small company who have resisted the influence of Hicksism.
The men are all, about or below the meridian of life,
and do not appear to have had much experience,
though well disposed to maintain our principles.
The service in the first meeting seemed to run against
the state that considers itself whole and sound,
as not needing a physician; which can argue, and defend sound principles,
and appear very knowing in spiritual things, while ignorant of itself.
Such are very liable to be misled by the subtle deceiver,
in his transformations as an angel of light,
and become instrumental in leading others astray.
"`They that be whole need not a physician, but they that are sick.`"
"`I am not come to call the righteous but sinners to repentance.`"
It is only as we are willing to come to the light,
that we can see our diseased and sinful state,
and receive a disposition to apply to the Great
Physician to be healed and cleansed of our maladies.
This was pressed upon the audience, several of whom were not members;
as well as the dangers of the transformations of Satan, as a leader in religious matters.
The few Friends were encouraged to yield to the sanctifying power of Him,
who is compared to a refiner of silver; that the dross and tin may be purged away,
and they be prepared to offer acceptable sacrifices to the Lord,
and hold up a pure testimony to the blessed Truth in that place; leading forward,
as shepherds and shepherdesses, the flock in their charge.

It was by no means a high day; but keeping low and speaking deliberately,
I was sensible of being led in a path which the Master cast up,
and which I believe was descriptive of the states of individuals present;
for which I felt peaceful and thankful.

In the second meeting, I made some remarks, after the Queries,
on the importance of rightly and faithfully maintaining the discipline,
as a means of preserving the body sound and healthy.
We left a few books and tracts with several Friends,
and in the afternoon rode fourteen miles to Ware`'s tavern,
where we lodged and breakfasted.
From this place we proceeded to Hoosic Corners, eleven miles,
and from there to the house of an elderly Friend in Pittstown, nine miles.
He and his wife received and dined us kindly,
and then piloted us over to Schaghticoke Point.

In Pittstown, a pretty large meeting of Friends was held, before the separation;
but M. H. and his family are now nearly all that remain united to the Society.
They have thirty miles to ride to South Adams, to attend the Monthly Meeting there,
to which they belong; and eleven miles to Schaghticoke, to a small meeting of worship,
held in a private house, but which is a branch of another Monthly Meeting;
no meeting of Friends being held at Pittstown.
It is truly deplorable to witness the ravages of unsound
principles through this part of New York Yearly Meeting;
and from the information received, as we pass along,
many who did not at first approve of those principles, now advocate them;
and those who did, progress still deeper in the dark mazes of infidelity.

On sixth-day 23rd, we held a meeting with the few Friends at Schaghticoke Point,
in a private dwelling where they usually meet.
Nearly all of them--about ten--appeared to be exemplary,
and concerned to bring up their children in a consistent manner; and, I thought,
were under exercise, that they might be found in the discharge of their religious duties.
The way opened to encourage them to put their trust in the Shepherd of Israel,
and endeavor to do what their hands found to do in his service;
that they might be enabled to hold up a testimony to Truth in their neighborhood;
by which others might be drawn to join them in the same good work.
We distributed some books among the young people; and after dining,
rode to Union village, fourteen miles, and put up at a tavern.
Seventh-day rode twenty-six miles, to J. W.`'s, near Bishop`'s Corners, in Granville.
This Friend and wife removed, a few years since, from Dartmouth, near New Bedford,
Massachusetts; they entertained us very pleasantly.

On first-day 25th, attended their meeting, composed of about thirteen families,
held in an upper room in an old tavern house, now a private dwelling.
The accommodation is better than most private rooms,
but the members contemplate building next year.
It appears to me very desirable, that Friends who are turned out of their meeting-houses,
should erect others as early as convenient.
Young persons and strangers are more willing to attend a meeting held
in a house appropriated exclusively for the purpose of Divine worship;
and to others, it feels more like assembling for that object.
The meeting here was rather trying to me,
from an apprehension that many are much immersed in the world.

Dined at N. P.`'s, where we had a little opportunity to encourage him and his wife,
who are at the head of the meeting,
to labor to fulfill their duties as overseers of the flock,
in bringing forward the young people, by their example,
under the government and yoke of Christ.
Our friends J. W. and wife piloted us, in the afternoon, over to Danby,
when we put up at the house of a Friend.
We passed the evening in agreeable conversation.
It afforded an opportunity of entering upon some of
those points which clash with the doctrines of Friends;
particularly in relation to the continuance of
immediate revelation in the church of Christ.
The Friend recited several instances of those who professed to have it on all occasions,
but who afterwards made shipwreck of faith.
I told him that I believed those who were most favored with it,
would say the least of having it themselves; but endeavoring to keep to its guidance,
left it to their friends to feel and decide
whether their services originated in that source;
that professors carrying any one point to an extreme,
or making shipwreck of faith and a good profession, was no argument against the truth;
which lay out of all extremes; and we should be on our guard against suffering one error,
or extreme, to drive us from the Truth, into another.
I disapproved of all unauthorized and unsanctified pretensions; but, at the same time,
the immediate influence and guidance of the Holy Spirit,
were the root and foundation of true faith, and the work of religion in the soul.
It was to this the primitive believers were gathered;
the manifestation of the Spirit which is given to every man to profit withal;
and by which alone we can savingly understand the Holy Scriptures.

Christ opened the understandings of his immediate disciples to comprehend the Scriptures;
and He does the same thing now, by his Spirit in the hearts of his believing children,
as He sees fit for them; and if any man has not the Spirit of Christ, he is none of his.
It was so in the Apostolic church, and it remains to be the case still,
and ever will so remain.
He united with me,
though at first he seemed disposed to bring into
view the defections of some wild pretenders.
I told him that the Anabaptists of Munster,
pretending to the authority of the Spirit for their wild actions,
were sometimes cited by the opponents of revelation,
to disprove its continuation in the church; but that Robert Barclay remarked,
it was no more a valid argument against it,
than that the reference of others to the Holy Scriptures,
as authority for the many wrong deeds they have committed,
destroys their truth and authenticity.
On second-day morning, we held a meeting at Danby with the few members there,
and some others who came in.
The stream was low, which made the work laborious; and after the meeting was over,
it seemed as if nothing was gained, and I felt discouraged.
Just before setting out, the family came into the parlor,
and through the gracious goodness of our Holy Helper, we had a tendering time with them.
Soon after entering the house,
I had been arrested with the impression that one of the
daughters was brought under Divine visitation,
and referring to it in this interview, it affected the parents and herself especially;
so that we had cause to thank Him, who mercifully regards us in our various conditions,
and to take fresh courage to press forward.
Rode sixteen miles to Clarendon, put up at a tavern,
and early the following morning set out again, and proceeded forty-one miles,
and again lodged at a public house.

On fourth-day morning, 28fch of tenth month,
we reached the house of an elderly man at Ferrisburg, to whom we had been recommended.
They kindly prepared us breakfast, and we attended the Monthly Meeting held at Monkton.
Here I felt the situation of sitting in a company, every one of whom was a stranger to me.
Endeavoring to retire in my mind, the language of sympathy and encouragement arrested me;
and after a Friend had spoken, I rose with the declaration,
"`I will bring the blind by a way which they know not,
and lead them in paths they have not known; I will make darkness light before them,
and crooked things straight; this will I do unto them, and not forsake them,
says the Lord.`"
The stream of consolation flowed gently towards some present,
and we had cause of thankfulness to the Leader of
Israel for favoring with a little opening of this kind,
for our own comfort and strength, as well as that of others.
We were at first, as completely strangers to them, as they were to us.
Finding that a Preparative Meeting of Ministers and
Elders was to be held next day at Starksborough,
and their Monthly Meeting on sixth-day, we went there.

Attended the select meeting; in which after the business was nearly finished,
way opened to show that every gift was derived from Him,
"`who ascended up on high, led captivity captive, and gave gifts unto men:`"
that no man could make himself a minister;
nor could he exercise the gift after receiving it,
but under the direction of Him who gave it;
and for this he must be exercised in patient waiting;
and when any thing is given him of the Lord, he is not to be hasty in offering it;
as George Fox remarked, when a man receives any thing from the Lord,
he keeps it and waits to feel the Lord`'s power go forth over the assembly.
As a minister thus waits, he will be furnished,
if the great Master calls upon him to minister to the people,
with sufficient clearness to rise, and a word will be put into his mouth;
and when he does speak, he should keep calm and deliberate, out of all excitement;
communicating that which is opened to his mind by Him,
who alone knows what is necessary for the states of the people.

The house of our kind and intelligent friend, where we were entertained,
was an agreeable lodging-place to us; the influence of education and suitable reading,
in expanding the mind, divesting it of many illiberal, contracted notions,
was visible here.
But in too many cases, we find Friends, of sufficient means,
who have neglected the education of their children very much; or,
after having given them small portions, do not provide them with suitable books,
to employ their leisure hours, in storing their minds with useful and instructive ideas.
Labor for our subsistence, is unquestionably necessary,
but we may slide into the habit of pursuing our worldly concerns with such avidity,
as to lose all relish for mental improvement;
and for those things which are invisible and eternal.
When old age overtakes this description of persons,
they have few objects of thought and conversation,
but the little round of worldly concerns,
which have engrossed their time and attention for many years;
but little interest in anything beyond their own affairs;
and for lack of having been engaged to lay up treasure in heaven,
are often destitute of any ability to promote the welfare of religious society,
and the advancement of the testimonies of Truth.
Their example tends to lead those around them into the same worldly pursuits; and thus,
instead of being the salt of the earth, and lights in the world,
they prove stumbling blocks to sincere enquirers after Truth,
and blind guides to the youth in the Society.
Such persons are objects of commiseration and regret.
These are subjects that ought to call forth the energies of the Society;
not only in a fervent concern for the religious welfare of the young people,
but in adopting proper measures for their guarded school education;
visiting them in their families,
and endeavoring to elevate their minds by furnishing
suitable libraries in the Preparative Meetings.
