== Chapter VII

[.chapter-synopsis]
* 1835--1836. Continuation of visit to Friends in New York and Vermont
* Returns Home
* Engages in a Periodical Publication of the Approved Writings of Friends
* Attends the Yearly Meeting in New York
* Religious visit to Ohio Yearly Meeting, and the Meetings belonging to it in the Western part of Pennsylvania.

On sixth-day, I attended the Monthly Meeting of Starksborough; composed of Montpelier,
Lincoln, Creek and Starksborough Particular Meetings.
No separation has taken place in this Monthly Meeting, and it is large.
A feeling of solemn silence spread over us early after sitting down;
and it appeared to be my place to address the younger classes,
whose minds were measurably seasoned with Divine love;
to show them that the work of Grace was gradual and progressive.

The figure of the preparation of the clay, by pulverizing, watering and softening,
preparatory to forming vessels; and the process of drying and burning,
before they are fit to receive what they are designed to contain,
was opened before me in a lively manner.
The further necessity of enduring the baptisms,
which shall be administered from time to time, to keep the vessel clean,
was also affectionately held up to their view.
He that puts forth, graciously furnished with matter adapted to the occasion;
and another Friend followed in short testimony, confirmatory of what had been offered.
We then proceeded to the business of the Monthly Meeting, which kept us a long time.
That evening we rode, through rain, and after dark, to Monkton.

Tenth month 31st, seventh-day.
Held a meeting here with the few Friends which compose it.
It was a cold, unfeeling time; I was able to come at nothing like an evidence,
that it was my place to say anything;
though there were some presentations which died away, and we closed in silence.
It may be a trial to call Friends together,
and pass the whole time without having anything to communicate;
but He only that sees in secret knows what is best;
and it is our place to stand submissive to his will.
Friends may become so habituated to hear words, that they may depend too much upon them;
and then the mouths of ministers may be closed;
to show the necessity of every one laboring for himself,
and maintaining a constant dependence upon the Minister of the Sanctuary.
I felt low through the afternoon, thinking that the fault might be in myself,
and that I may not have kept sufficiently humble,
under the favors which have been conferred on us in this visit.
I looked at the feelings of my mind, on requesting the notice of the meeting to be given,
and remembered that they were then clear and settled;
and could not now charge myself with willfully omitting to speak in the meeting.
Hoping that it might be in the Divine ordering,
I settled down under the desire to bear whatever might be my place,
and to endeavor to profit by the various changes which our Holy Leader may see proper.

We had a little opportunity with the family where we dined;
in which the children were much tendered.
They were invited to take up the cross and follow their Lord and Master;
who would strengthen them, as they yielded to Him,
to deny themselves of whatever He called them to give up.
Attended Ferrisburg Meeting on first-day morning.
Here we had a laborious time;
under a sense that very few were engaged to labor for themselves,
depending on what they may hear from others;
yet there are a number who appear sincerely desirous to know the Truth,
and to live under its direction.

In conversation with a man who had travelled but little,
and who was not a little contracted in his views of others, I was led to the reflection,
that where people are delving in the earth all their lives,
and paying scarcely any attention to the improvement and enlargement of their minds,
they possess little qualification to judge of others.
They try everything by their own standard,
which is formed according to the limited sphere they move in; and for lack of knowing,
either by interaction with others, or reading,
the great variety of habits which prevails among people equally pious,
they often censure what differs from their customs;
and conclude that those who so differ are influenced by pride.
This is especially obvious,
where the heart has not been softened by the Spirit of the Redeemer,
and brought to see its own deformity, and from there clothed with Divine charity.
True religion effects wonderful changes in us;
while it clothes us with proper love and allowance for others, it erects a standard,
founded upon the purity and simplicity of the gospel of Christ;
and neither condemns for those distinctions,
which arise from mere difference of education;
nor admits of those varieties which spring from and foster pride in the human heart,
and are inconsistent with the Truth.

The abolition of slavery is a subject which engrosses
much thought and conversation in these parts;
and it appeared to me,
that Friends are drawn into coalition with
others in their measures to effect this object,
more than is best for them.
Ever since we cleared our hands of slavery,
Friends have advocated the freedom of the blacks on principle;
but if we enter into alliances with others, we may find before we expect it,
that some measures will be proposed,
which will violate other principles that we hold equally dear; or in their operation,
land us in circumstances which will not admit of our union with others,
if we retain the character of consistent Friends.
I believe we had better pursue our own course, under the direction of Divine Wisdom,
in promoting the spread of the Redeemer`'s kingdom;
and by lives of strict conformity to his benign precepts, we should be lights to others;
and offer the most effectual stimulus to them, to go and do likewise.
Each denomination would be likely to act according to the light it possesses,
and they would mutually stimulate one another to zeal and diligence.

On the following morning, we attended a meeting appointed for us at the Creek,
formerly South Starksborough.
The subject of living and walking in the Truth,
by which we partake of the greatest blessing in this life, was opened;
and the means placed within the reach of all, explained,
as laid down in the Scripture doctrine;
that the true Light enlightens every man that comes into the world.
And "`This is the condemnation, that light is come into the world;
and men loved darkness rather than light, because their deeds were evil.
For every one that does evil, hates the light; neither comes to the light,
lest his deeds should be reproved.
But he that does truth comes to the light,
that his deeds may be made manifest that they are wrought in God.`"
I was led to show that this Divine light convicted us of sin,
and brought condemnation and shame upon us for it; that, if received in its visitations,
it gives strength to resist temptation, and to come out of our evil practices,
and enlist under the government of Christ.
But by resisting its convictions, and the offers of love and mercy,
the heart becomes more and more hardened;
and at last might reach that condition in which we may deny that
these convictions proceed from the Holy Spirit striving with man,
and come to attribute them to mere imagination.
It felt to me that there were those there, who were unbelievers in Divine revelation,
and the truths of the gospel of Christ; and I believed it right to say,
that if any persisted in denying and rejecting the strivings of the Holy Spirit,
throughout the day of visitation, they would be left in darkness.

After dining, we rode to the house of a minister, and in conversation,
he expressed his satisfaction that some points had been opened, as they were,
in the meeting.
He said a young man and his father were present,
who were known to deny immediate revelation.
The young man had been clerk of their Preparative Meeting, and was displaced,
and a minute made on its records, that it was in consequence of his unsound principles.

On Eleventh month 4th, fourth-day,
we attended the Select Quarterly Meeting held at Lincoln, which was a dull time.
At the close, I mentioned my apprehension,
that Friends joining others in Anti-slavery and Temperance Societies,
would be attended with injury to them and the young people;
their spiritual strength would be impaired; and it did appear to me not proper,
that our ministers should attend such places It was true, we had our individual rights,
and the Society had not prohibited it;
but I feared it would affect their growth in the life of Truth.

We went to the Meeting for Discipline, which gathered very irregularly and late;
so that it seemed hardly probable we should have much solemnity very soon.
After a Friend had made some observations,
showing the necessity of feeling our own inability to do any good work;
though my feelings indicated little like communicating anything,
the testimony of the Apostle, that "`The weapons of our warfare are not carnal,
but mighty through God, to the pulling down strongholds,`" etc., had presented;
and recurring with some weight, I rose with it,
and endeavored to show that the weapons of the
Christian`'s warfare remained the same at this day;
and any that man could invent or use, in his own wisdom and strength,
would not prove mighty through God, to the pulling down of the strongholds of sin,
either in himself or in others;
that Christ alone could clothe us with the "`armor of God,`" by which we were to
make war in righteousness against the man of sin and son of perdition.
These weapons were to cast down all imaginations of self-importance,
and every high thing, however specious, that exalts itself against the knowledge of God;
bringing into captivity every thought to the obedience of Christ.
In the first place, experiencing this, in measure, effected in ourselves,
we should be prepared to be used in his hand to promote it in others;
and whatever might have been our attainments,
it is necessary to be frequently stripped and searched,
that we may be found in a situation to be renewedly clothed with this armor.

Satan could transform himself into the appearance of an angel of light;
and unless every thought of our own importance
and ability was brought into obedience to Christ,
we might be deceived and led into things which would not advance the Redeemer`'s kingdom.
Even those who had known the sword of the Spirit
unsheathed against the transgressing nature,
and in good degree gained the victory over it,
may be deceived if they do not abide in lowly watchfulness before the Lord;
for the beast had seven heads and ten crowns; and after being wounded,
its deadly wound was healed.
I was also led to show that the church of Christ
was compared to a body having many members;
each of which has its function to perform.
As we kept our places in the body, every one eyeing the Head,
and receiving direction from Him,
we should be preserved from interfering with each other`'s duties;
Ephraim would not envy Judah, nor would Judah vex Ephraim.
When any felt the Spirit of the Lord stirring in them, as in the camp of Dan;
or as fire shut up in their bones; after waiting patiently his time,
they were to deliver in his fear,
what He gave them to communicate and that which was brought forth under right authority,
would raise the life in others, who were keeping their places.
There were those whose voices were not frequently heard,
but who maintained a steadfast travail of spirit,
that all might be preserved in the right exercise of their gifts,
and a harmonious action together.
These were like ballast in a vessel.
Several views were taken of the subject;
and the young people encouraged to keep under exercise,
and to be faithful to the Lord`'s requirings.

A solemn covering spread over the meeting.
But little was said to the Queries and Answers by any one.
I made a few remarks, in which a Friend united,
on the disadvantage of retaining persons in membership, merely because they requested;
after they had transgressed the discipline.
We often found that such were of very little use to the Society;
and if their principles were unsound,
it gave them greater opportunity to spread the infection by mingling with the members.

Next day attended the meeting for public worship there;
which is still held by this Quarter.
In the afternoon returned to Starksborough,
to the house of our very kind friends, J. and L. B., where we lodged.

Eleventh month 7th. Set off this morning early, in company with our friend C. S.,
and wife and daughter, for his residence near Montpelier; the weather being wet,
and part of the road bad, made the ride uncomfortable.
Notice having been spread, a number of respectable-looking people assembled with Friends,
at their first-day meeting.
It appeared to be my place to hold up the doctrine of
the immediate influence of the Holy Spirit;
and that those who, through its converting power,
became the adopted children of our Heavenly Father,
are drawn to pray for its assistance and preservation, day by day;
that according to the language of our Savior, "`If you being evil,
know how to give good gifts to your children,
how much more shall your Heavenly Father give the Holy Spirit to them that ask Him.`"

The subject opened in various ways;
both in relation to the universality of the gift of Grace;
its various operations in baptizing the soul, as fire to purge away its defilements,
and render it fit to offer acceptable worship to God;
and also as to the mediation of the Lord Jesus, by whom it is communicated.
I thought, however, that the stream did not rise as at some other times;
yet the people were very still and attentive.
I could not see that I had made any mistake, unless it was in rising too early;
but of this I could feel no conviction; and yet I was brought low,
so that I took little satisfaction in the company of Friends.

Second-day, 9th. We rode forty-three miles to Burlington, on Lake Champlain;
put up at an inn, and the following morning, placing carriage and horses on a steamboat,
we landed them at Port Kent, on the opposite shore; where we were joined by a Friend,
and then proceeded in the steamboat to Grand Isle,
where a meeting had been appointed for us, to be held at half-past eleven o`'clock.
Through detention, the boat did not arrive until after twelve.
We took a wagon, and at once rode two miles to the meetinghouse,
where we found a number of women convened, and some men, waiting for us.
We sat down with them; several more came in,
and after some time of waiting upon the Lord,
the subject of love to God and to our brother was presented;
and help was mercifully near, to qualify for the service.
First-days`' experience made me renewedly sensible, that the gospel cannot be preached,
but as the Master condescends to open and furnish matter,
and accompany it with his baptizing power;
and I felt very desirous of doing nothing but what He should direct.
In this humble state, one thing was opened after another;
and prayer and thanksgiving arose, for the continuance of his Divine presence,
and aid in the work which He appoints.
When the boat returned from St. Albans, we went on board, landed at Port Kent,
and taking horses and carriage, reached Peru after dark.

Fourth-day 11th. Attended the usual week-day meeting here,
and was distressed with the indifference of many.
It seemed as if not a few have contracted the habit of looking for preaching,
and neglecting their own business of seeking for sustenance for themselves.
About time to close the meeting it appeared proper to bring into view
the object for which we assemble which is to wait upon the Lord,
and to feel after him, if happily we may find Him;
but if we pass the time in thinking our own thoughts,
suffering the mind to range abroad among the objects of our worldly pursuits,
we may come and go without receiving any benefit.
I endeavored to relieve my mind among them.
We have now got through the meetings of Ferrisburg Quarter,
with the exception of Farnham, a meeting in Canada,
which we could not visit in time to reach Saratoga Quarter.

There are many goodly, well-concerned Friends in this part of the Society,
who are desirous of maintaining our religious principles and discipline;
but it appears to me, that there is too much fondness for words; and some,
without authority, undertake to exercise the office of the ministry.
Wherever there is a fondness for speaking and hearing,
there will be danger that a sound judgment will not be exercised, in suppressing forward,
active persons, who would intrude themselves into this sacred office.
Hence a spurious ministry grows up, and the people love to have it so,
rather than endure silence in our religious meetings.

By this means, instead of being seasons of solemnity, imparting spiritual strength,
the mind is vacant, uneasy and listless.
Many seem to be very ignorant of the nature of religious exercise;
and the practice of thus assembling, is in danger of becoming a mere form.
If the habit of public speaking without life is promoted,
a multitude of such preachers may be spread over the Society, ministering death;
and leading the members away from the place of true waiting and feeding,
into a restless desire after words; which will never build any on the most holy faith,
nor strengthen them against one sin.
Such find that speaking smooth things pleases their hearers,
who will caress them for their fair speeches, and extol them as fine preachers;
while the true minister, who cannot flinch from speaking the truth,
will feel that his testimony is not relished,
and a secret prejudice is indulged against him.
But there are in almost every meeting, some painful travelers,
who understand the language of the Spirit,
and rejoice to find others speaking the same thing,
and walking in the same tribulated path.
These will salute each other as brethren and sisters,
and rejoice in the fellowship of the Gospel;
and a secret satisfaction is felt in having been instrumental in visiting the seed.

Before leaving our lodgings, I had a little opportunity with the family;
in which I affectionately pressed the necessity of
living loose to the world and its gratifications,
and following the Lord Jesus, under the subjecting power of the cross.
The general simplicity of their children was a pleasant sight;
and they were encouraged to join with their parents,
in faithfully giving up to the requisitions of Truth,
so that they might become lights in the world, and living members of the body of Christ;
prepared for usefulness in his church.
Left there between nine and ten o`'clock, and rode about eighteen miles to a tavern,
and dined, on our way to Queensbury, about one hundred miles distant from Peru.
Our course lay through a mountainous, rude country, many parts of it little settled,
or capable of much improvement; and the road, in some places, extremely bad,
being very rocky, and the logged parts decayed, which made it very jolting.
That night and the next, we lodged at taverns; and on seventh-day afternoon,
got safely to Queensbury, where we put up at the house of a Friend.

At the time of the division, Friends, for the sake of holding their meetings peaceably,
assembled in the afternoon of first-day,
though their members were about equal in number with the Separatists.
We attended the meeting, and from our feelings,
thought a disadvantage sustained by assembling at that hour.
It seemed difficult to come at much lively feeling,
or a clearness of what was proper to be done;
not feeling easy to leave the meeting without bringing into view,
the blessing of being brought under a right exercise of
mind for the salvation of our own souls;
and the still greater favor, of being kept under it from day to day.
I was enabled to speak to the states, as I apprehended, of some present,
who had suffered their minds to be drawn aside
from pursuing those things which they had seen,
in the light of Truth, belong to their everlasting peace.

The fire was to be kept constantly burning on the altar, under the law;
and it is necessary, under the Gospel,
to have the fire of Divine love daily replenished in the heart,
that we may be qualified to offer acceptable sacrifices to God,
through Jesus Christ our Lord, the Great High Priest of our profession.
I felt very desirous, in using plainness of speech to some present,
that it might be under that unction,
which will open the heart to receive and acknowledge the truth of what is said;
and that this description of service, which represents the defects of professors,
may be evidently a work of necessity and not of choice.

On third-day attended the Select Quarterly Meeting,
in which some ability was granted to encourage those who meet in the
little companies which constitute the meetings of this Quarter,
to keep faithfully to religious exercise, and the support of their meetings.
Friends were few in the beginning;
but by faithfulness and steadfast dependence upon the Lord,
they were increased in number and strength; and so, by the same means,
in the present day, the few who keep their places,
may be like the roots of a new growth among us.

The Quarterly Meeting was now again composed of the members of Easton and Saratoga,
by conclusion of the Yearly Meeting;
the latter having been instituted a Quarterly Meeting out of the former.
This was the first time they again met in connection.

On the subject of education, and the perusal of the Holy Scriptures,
I made a few remarks,
tending to enforce the duty of parents to watch over and rightly educate their offspring;
exampling them in bearing the daily cross,
and instructing them to yield to the influences
of the Spirit of Christ in their own hearts;
which would lead them into self-denial,
and to love to read the records of the experiences of holy men of old,
and the doctrines of Christ and his Apostles.
It is the custom here to hold a meeting for public worship;
the weather being very dark and foggy, it was not so large as usual.
The forepart was heavy,
and I think I have scarcely ever been kept in more suspense respecting my duty,
as for a long time in this meeting; but believing it unsafe to attempt to move,
until greater clearness, though several presentations were made to my mind,
I kept still and inward.
After a Friend had delivered a short testimony, the way appeared to open;
and through the Lord`'s goodness and condescension, matter was furnished,
and the solemnizing power of Truth spread over the meeting.
Strong desires prevailed in my mind, that all present might,
through submission to the washings of regeneration, and by the precious blood of Christ,
be found among the multitude that surround the throne of the Lord God, and the Lamb;
who shall ascribe blessing and honor,
thanksgiving and high renown to Him that has redeemed them.
We parted from many of our friends in near affection.

Eleventh month 20th. Attended a meeting appointed at Greenfield;
at the interment of a minister.
It was composed of a great mixture.
The prophetic description of the Messiah: "`Unto us a child is born,
unto us a Son is given, and the government shall be upon his shoulder;
and his name shall be called Wonderful, Counsellor, The mighty God,
The everlasting Father, and The Prince of Peace;`" and the testimony of Peter,
that there was no other name, under heaven, given among men whereby we must be saved;
also that of Paul, that he had fought the good fight, kept the faith, etc.,
were brought into view, and salvation by faith in the Son and Sent of God,
and obedience to Him, preached to the company.
It came before me also, to warn the believers in Christ, who were present,
of the dangerous influence of infidelity, and not to touch it in any manner;
and in describing the awful consequences of it, I referred to the testimony of Christ,
that those who heard his sayings and did them not,
were building on a foundation that would fail;
and that the hope of the infidel would be no better than that of the hypocrite, etc.
A Friend informed us afterwards, that some unbelievers were present.
That evening we reached a tavern, lodged, and early the following morning,
(seventh-day,) proceed to Providence, where we attended an appointed meeting.
The doctrine of unconditional predestination was controverted;
its effect to settle in fatal security, those who imagined themselves of the elect,
but were living in sin; and the tendency to despair, or to neglect their salvation,
in those who were tempted to suppose they were reprobated from all eternity,
were exposed; and the universal love of God to all mankind,
in providing the means for their reconciliation,
by sending his beloved Son into the world, to offer himself a sacrifice for their sins,
and furnishing them with the gift of Divine Grace, to effect their regeneration,
was advocated.
The people were quiet and very attentive.
Several Calvanistic Baptists were present, as we were afterwards told by a Friend.
In the afternoon, we rode to Ballston, eighteen miles, and put up at a tavern.

22nd, First-day morning.
Rose early and rode to W. C.`'s, at Half Moon, to breakfast.
He and his family received and entertained us very kindly.
Their first-day meetings commence at two p.m.,
in consequence of the Separatists keeping the house in the forenoon.
We sat long in silence; until I supposed we should separate as we came;
but the expression,
"`The race is not to the swift, nor the battle to the strong;`"
but they that hold out to the end shall be saved;
having frequently revived and presented,
I was fearful of leaving the place without communicating it; and holding up to view,
that those who had begun well, but again turned aside, became stumbling-blocks,
and brought reproach upon the religion they had professed.
We passed the evening in agreeable conversation,
and closed it with reading a portion of the Scriptures;
and endeavoring to enlist the young people in the service of their Lord,
that they might experience preservation from the snares that abound in the world,
and be prepared to fill up their stations in the church.

Eleventh month 23rd, second-day morning.
Rode through snow, twenty miles, to Albany; dined there, and proceeded on our way,
seven miles, towards Middlebury Monthly Meeting, in Duanesburg Quarter,
and then stopped at an inn.
The road being covered eight inches with snow, made traveling heavy and difficult.

The Quarterly Meeting of Saratoga, though increased by the reunion of Easton,
is not large.
There are sound, judicious members; and some who, though not possessing much experience,
appear to be devoted to the cause and testimonies of Truth.
But, like other parts of the Society, too many are engrossed in their worldly concerns,
and do not come forward with that strength and clearness,
which entire dedication to the Master would effect.

24th. We rose early, and riding twelve miles through the snow,
in which we crossed the mountain called the Haldeburg, we stopped at an inn, breakfasted,
and then proceeded to Peter Stover`'s, in Berne.
The snow being deep and frozen, and the road not fully broken, the prospect of traveling,
in this mountainous country, looked very discouraging.
Arriving at the house of a Friend was very pleasant, after being at taverns;
and especially so,
to find he was willing to take us in a sleigh to Middlebury Monthly Meeting;
by which our horses could rest.
Enquiry being made by our host, whether we wished to have a meeting appointed,
and proposing a small meetinghouse near, I told him,
as Friends meet in his house to hold their little meeting on first-day,
I was willing to sit with them,
and such of their near neighbors as they were disposed to invite, in the evening.
About six o`'clock, they began to collect; and, to our surprise,
two sitting-rooms were filled by strangers.
A preacher of another profession,
who had appointed a meeting in the above-mentioned house, finding but few coming to hear,
him, proposed to them to go to Peter Stover`'s; and they accordingly came.
Our religious principles, on the subject of regeneration, Divine worship,
preaching and praying, were opened to the people;
and they affectionately invited to come to Christ, and take his yoke upon them,
and learn of Him.

They were also cautioned against seeking the living among the dead;
either in the lifeless forms which man has invented, or in any creaturely exertions,
which they can perform in their own time and strength.
Public vocal prayer always appears to me a very solemn act,
in which I have felt a reluctance to engage;
but feeling the spirit of supplication, I yielded to it,
and have rarely known sweeter access to the Throne of Grace than on this occasion.

Eleventh month 25th. Attended Middlebury Monthly Meeting; which was quite small.
The view of such a remnant convened in that capacity, was disheartening;
but it seemed to be my place to endeavor to strengthen Friends
in the faithful discharge of their religious duties;
that they might hold up a good light to others;
and that the ark of the testimony may not fall to the ground among them.

Though it appeared improbable, when riding through the heavy snow,
that we should be able to attend Coeymans Monthly Meeting,
yet we rose very early on fifth-day morning, and Egbert Stover and wife,
Smith Upton--who had joined us at the Quarterly Meeting--and myself,
got into their sleigh, and Joseph Snowden drove the carriage;
and we reached the house of a Friend, near the meetinghouse,
about an hour before the time.
The sensations that spread over my mind in this meeting, indicated the lack of a lively,
daily exercise in some present,
to experience the work of the soul`'s salvation to progress, as time was passing away;
by which they would be qualified to engage in the Lord`'s cause,
and rightly to manage the concerns of the church.
Instead of which, a disposition prevailed to procrastinate,
and defer this all-important work to a future day,
when their worldly business would admit of laying hold of it;
trusting that then it could be entered into, and effected with more convenience,
and with dispatch.
The warning of the Apostle was revived:
"`If the righteous scarcely be saved, where shall the ungodly and sinner appear?`"
and if judgment begin at the house of God,
"`What shall the end be of them that obey not the gospel of God?`"
showing that the salvation of the soul was not so light a thing,
and so easily accomplished, as some might be persuading themselves.
Some appeared to be affected.
When we entered on the business of the Monthly Meeting,
the representatives appointed to their late Quarterly Meeting reported,
that none of them attended; and but one could offer an excuse;
which afforded proof of the lack of a lively zeal for the cause of Truth,
and the support of the discipline.
If those who take part in the affairs of the discipline at home,
and make a plain appearance, can lightly disregard their duty,
when it may require a little sacrifice of time and labor to perform it,
the younger members must imbibe the idea,
that the concerns of religious society are of
secondary importance to their worldly profits;
and thus such unfaithful members may stumble others,
and be the means of spreading spiritual death in the camp.

Lodged at Thomas Bedell`'s; and on Eleventh month 27th, sixth-day morning,
rode about thirty-eight miles to little Nine Partners;
having crossed the North River at Hudson; and the following morning,
reached the residence of our very kind and affectionate friends,
Smith and Sarah M. Upton.
In being favored to return thus far from this little journey,
gratitude and thankfulness to our Heavenly Father, covered my mind;
for the preservation of health and our safety from casualty,
and for the unmerited extension of the aid of his Holy Spirit,
to discharge what appeared to be required duty;
though a sense of frailty and unprofitableness as a servant,
was felt to appertain to the poor, unworthy creature.
But it is a mercy and favor to be able to call Him, Father;
and to look up unto Him with humble, sincere desire,
that He will still grant wisdom and strength to do the work assigned;
and keep us in the way He would have us to go.
And I believe, He will keep, by his own power, for the sake of his beloved Son,
those who thus rely on Him alone; and desire to be daily humbled,
under a conviction of their own helplessness to preserve themselves.

Eleventh month 29th. Being first-day, we attended the meeting at the Creek:
and in the afternoon set off in a sleigh, our kind friend Asa Upton accompanying us,
for Canaan; a small remnant of Friends residing there,
who hold a meeting once or twice a month,
with the aid of a committee of Nine Partners Monthly Meeting.
Lodged that evening at E. C.`'s; and early on second-day morning, set out again;
and between twelve and one o`'clock, reached the residence of one of the Friends.

In the evening, we held a meeting at a Friend`'s house, composed of a few members,
and several Methodists and others.
The people expressed satisfaction with the visit; but to me it was a shallow time;
there seemed a necessity to utter many things which presented,
but the life-giving virtue, according to my feelings, but sparingly attended.
Asa Upton observing me to appear depressed, enquired the cause;
and when I told him it was a low time, he replied, it exceeded his expectation so much,
he was concluding it was a time of favor.
Lodged there; rose before day on third-day morning; returned to our ancient Friend,
E+++.+++ C.`'s, where we dined; and after a little opportunity,
in which encouragement was offered to trust in the never-failing Helper of his people;
who, having been with his children in six troubles, will not forsake them in the seventh;
we proceeded towards the Creek.
On our way, we stopped half an hour at the mansion of our
late honored friend and father in the Truth,
Henry Hull, to take leave of his widow; to whom the language of sympathy was extended.
We were permitted to unite together in a sense of the
continued protection of our Heavenly Father surrounding us,
his unworthy, but dependent creatures.
Drank tea with A. Upton and wife; and after spending most of the evening,
took an affectionate leave; and rejoined our friends S. and S. M. Upton,
at their hospitable mansion.
The kindness of these beloved Friends, in various ways, has been marked,
and esteemed by me as an evidence of the propriety of this little journey;
inasmuch as the unity of the brethren and sisterhood,
does prove that the Great Head owns a concern,
by leading his children to own one another.

Twelfth month 2nd. We parted from our beloved Creek friends with much affection;
and having Paul Upton, as guide, we rode twelve miles;
and attended the little meeting at Oswego.

Here the stream of sympathy and consolation, was again opened towards the faithful few,
who are endeavoring to maintain a public confession of
their allegiance to the King of kings;
who, we did believe, would sustain and strengthen their hands,
as they maintained the Christian warfare;
and would grant a crown of life to all that are faithful unto death.

3rd. Proceeded on our way to Salem, in Purchase Quarter.

Twelfth month 4th. We had a meeting at a Friend`'s house, in the morning; with his family,
his son-in-law and daughter, and a few of the neighbors;
the principal part of Salem Meeting having joined the ranks of the Separatists.
It was a satisfactory opportunity to them and to us.
In the afternoon, went to a Friend`'s, near Croton Valley Meetinghouse;
and in the evening,
the remaining members of that meeting convened at this Friend`'s house,
where they usually hold their meeting for worship.

The necessity of laboring for daily spiritual sustenance,
and becoming willing to endure the hardships and
privations attendant on this militant state,
in order that we may grow in the Divine life, and be qualified for service in the church,
were held forth to their view.

5th. Rode over to Amawalk, and attended a meeting appointed there.
The condescension and goodness of the Blessed Head of the church were manifest,
in furnishing renewed qualification to preach his
everlasting gospel of conversion and regeneration;
the object whereof is, to fit us for that kingdom into which nothing impure can enter.
The disposition which has ever existed in man,
to clothe himself with his own righteousness, was brought into view.
The prophet Isaiah, under a sense of the degeneracy of the Jews,
while they were pluming themselves with their outward observances, declared,
"`All our righteousnesses are as filthy rags.`"
Our Lord told his hearers,
that "`Except your righteousness shall exceed
the righteousness of the Scribes and Pharisees,
you shall in no case enter the kingdom of heaven.`"
They neglected the weightier matters of the law; judgment, mercy and faith;
while they paid tithe of mint, and anise, and cummin; these ought they to have done,
and not to leave the other undone.
It was easy to practice these outward things, without any cross or mortification;
and indeed by them, to gain popularity among men.
Paul told the believers, that it was "`Not by works of righteousness which we have done,
but according to his mercy, He saved us; by the washing of regeneration,
and the renewing, of the Holy Ghost;
which He shed on us abundantly through Jesus Christ our Savior.`"
The Holy Spirit, in the revelations made to John, reproved the church of Laodicea,
for trusting to their own righteousness: Because you sayest, I am rich,
and increased with goods, and have need of nothing, and know not that you are wretched,
and miserable, and poor, and blind, and naked; I counsel you to buy of me gold,
tried in the fire, that you may be rich; and white raiment, that you may be clothed;
and that the shame of your nakedness do not appear;
and anoint your eyes with eye salve that you may see.
As many as I love, I rebuke and chasten.`"
I felt very low in going into the meeting; and, fearful of moving,
when these things opened before me; but at last thought it best to rise,
with some introductory remarks on the high value of the Holy Scriptures,
given by inspiration, and providentially preserved to us;
and while we were justly entertaining such an esteem for them,
it was necessary to examine whether our lives and conduct corresponded with
the precious precepts and doctrines therein inculcated.
It was a solemn opportunity.

The 6th, being first-day, attended the meeting at Peekskill.
Here the necessity was enforced of submitting to that baptism and cup of suffering,
which our blessed Lord partook of, according to our respective measures,
and the dispensations of his wisdom; if we expect to participate in the glory, and honor,
and dignity, which appertain to Him and to his cause.
Nothing in which man could glory,
attended the little service that appeared to be required.
Such changes, from one day to another, sometimes try our faith and perseverance; but,
I believe, they are essential,
to empty the vessel and to cut off all glorying before God.

7th. Had an appointed meeting at Croton, with the few remaining members, and some others.
The encouraging declaration of our Lord, that "`If two of you shall agree on earth,
as touching anything that they shall ask,
it shall be done for them of my Father which is in heaven.
For where two or three are gathered together in my name,
there am I in the midst of them;`" presented to my mind;
and led the way to encourage the little remnant,
with the belief that their Lord would regard
them in their faithful endeavors to serve Him,
and to uphold a testimony to his name and goodness; and would minister to their needs,
by the blessed influences of his Spirit.
An invitation was also held out to the wanderers,
to embrace the visitation of Divine love; which seeks to save that which is lost;
as exemplified in the lost sheep, and the prodigal.
It was a comfortable opportunity; in which I had cause for thankfulness to Him,
who opens and shuts, when He pleases.
C+++.+++ U. and wife met us at this meeting,
and piloted us that evening to their house, at Chappaqua.

8th. At Chappaqua Meeting, we were again favored with the presence of our Divine Master;
qualifying to open the need we have of dispensations of humiliation;
by which the earth and the heavens are shaken,
so that those things which cannot be shaken, may remain;
that we may be preserved from sinking into earthly-mindedness,
and through the purging operations of that Word, which is as a fire and a hammer,
be prepared to produce those fruits which redound to
the glory and honor of our Heavenly Father.

9th. We attended Mamaroueck Monthly Meeting.
Here we were led into sympathy with some who had heavy burdens, at times, to bear;
and yet felt often as if but little good would result from it.
The sufferings and reproaches which the Captain of our salvation endured for us,
and the great privations and afflictions our early Friends bore, were alluded to;
showing that it is through suffering the truth triumphs; and if He, for our sake,
submitted to such treatment,
we ought to be willing to partake cheerfully of
those afflictions which appertain to the gospel,
both for our own sakes, and for the church.
On the following day, we rode to see the remnant of a small meeting, called Middlesex;
consisting of five females, who meet once or twice a week, for Divine worship,
at the residence of Catharine Seely; who has been confined mostly to the bed,
eleven years.
We had sittings with them; and they were glad of our visit.

Lodged at Charles Field`'s; and on sixth-day, 11th, had an appointed meeting at Purchase,
to our own comfort and the satisfaction of Friends; and on seventh-day, rode to New York,
where we put up with Hannah and Lucy Eddy.

On first-day, 13th, attended the morning and afternoon meetings;
which were rather relieving opportunities; especially the latter,
in which much interest in the welfare of the younger members was felt;
on account of the all-engrossing spirit of the world,
to which they are exposed in this city of great business.
They were affectionately invited to take the yoke of Christ upon them,
that they might become crucified to the world, and the world to them;
and know those things to be kept under foot, and used as servants and not as masters.

14th. Went to Flushing, where we had an appointed meeting the next day;
in which the necessity of living and walking by faith, was treated on;
as the path which the righteous of all ages have walked in, and found safety,
and witnessed an establishment on the immutable foundation;
which will sustain against the storms and trials of time.

16th. We attended the Monthly Meeting of Westbury;
in which it appeared needful to stir up those who had known the Lord`'s
hand to be extended for their help in time of extremity;
and yet were now in danger of falling into a lethargic state,
taking their comfort in the things of this world.

This was the last meeting that I expected to be at; and when it was over,
my mind felt at liberty,
and peaceful in the prospect of soon rejoining my beloved family at home.
Returned to S. P.`'s, and lodged.
The weather was very cold; the thermometer falling two degrees below zero, that evening.
Before ten o`'clock,
we saw a large column of flame and smoke rising in the direction of New York.
When the family rose, at six the following morning, it was still burning,
in the same degree; and when we reached the city,
the destructive element was unconquered; the firemen exhausted,
and the extreme cold rendering the fire engines and hose almost useless.
The fire commenced in Wall Street, and extended south-east,
destroying a large amount of property.

On fifth-day night, we lodged at Nathan Yail`'s. Sixth and seventh-day, at Ruth Ely`'s;
and on first-day, Twelfth month 20th, 1835, reached home;
having travelled about seventeen hundred miles.
We were blessed with health, so as to meet no detention; which is a great favor;
and have good cause to acknowledge the kindness and condescension of our Heavenly Father,
in strengthening us for the little services, that He required us to perform;
and also for the hospitality of our friends throughout the journey.

1836+++.+++ The Meeting for Sufferings of this Yearly Meeting, having, for a long time,
been desirous that some mode might be adopted
for spreading the approved works of Friends,
more generally among the members, now extensively scattered in this country;
it was suggested to my brother Thomas and myself,
whether we could not undertake the work.
After deliberating upon it, and no other Friends appearing to be willing to engage in it,
we drew up a proposal, which was submitted to that meeting, and approved;
and after some modification and enlargement, under the supervision of the Book Committee,
the prospectus was printed, and spread throughout the meetings in the Yearly Meeting.
It was not without serious apprehension of many
difficulties attending the prosecution of such a labor,
that we took the step; but the consideration,
that a large number of members were growing up in the Society,
who must be unable to procure the approved writings of Friends, owing to their scarcity,
induced us to make the attempt;
in the hope that we might thereby contribute to their benefit,
and to the advancement of the cause of Christ in the earth.
Copies of the prospectus were also forwarded to all the
Meetings for Sufferings on this continent;
and, I believe, approved by them all most of whom issued minutes to that effect.

In the Fifth month, I attended the Yearly Meeting of New York,
where several ministers from this and other similar meetings, were also present.
The Meeting for Sufferings there, issued a pretty full minute,
encouraging its members to take the proposed periodical; containing the journals, etc.,
of Friends.
Much business came before the meeting, which was resulted in harmony;
though I thought the desire, on the part of some from the country,
to avail themselves of the steamboats, for returning home, induced them to hurry,
more than the dignity of such a meeting, and the nature of the business would warrant.

The spirit of the world operating upon the members of our religious Society,
to draw them into extensive and hazardous business,
produces a very injurious effect upon them.
If it banishes the spirit and character of a humble follower of the Truth,
a sense of oppression is felt among them, by those who desire above all things,
to do the will of their Divine Master;
the precious fellowship of the gospel is obstructed, and mourning over their degeneracy,
is the clothing of the suffering seed.

Through the forepart of this summer I was much at home.
An afflicted child had long been claiming our sympathies and attention.
She had now suffered more than three years; was often confined to her bed,
and most of the time, unable to move about without help.

Eighth month.
Having felt my mind drawn to attend the Yearly Meeting of Ohio,
and to visit the meetings composing Red Stone Quarter,
I laid the concern before the Monthly Meeting, in the Eighth month,
and obtained a minute of its unity.
My esteemed friend Henry Cope, having agreed to bear me company,
also received a similar minute.
Though it was a trial to leave my beloved wife in charge of the family,
one of the children having been long confined with disease,
yet I was not easy to omit attending to the service
which I believed my Divine Master laid upon me.
We set out on the 27th, in public conveyance,
by railroad and the canal through Pennsylvania to Pittsburg,
where we arrived on fourth-day morning, 31st; having had our friends,
Elizabeth Coggeshall and companions, fellow passengers.
There we hired a stage to take us to Mount Pleasant, which we reached next evening;
lodged that night in the village.
Dr. Isaac Parker called on us in the morning,
and invited us to take lodgings at his house, we were very pleasantly accommodated there,
through the week.

On seventh-day morning I attended the Meeting of Ministers and Elders,
and after the usual business was transacted,
felt engaged to draw the attention of Friends to
the importance of holding a Yearly Meeting,
and the privileges which, as members of this Society, we enjoy.
That in order to preserve these privileges, it is necessary properly to estimate them,
and to endeavor to keep our respective places in the church;
dwelling near to our Divine Lord, and relying wholly upon Him,
for ability to per form our duty.
Thus we should be instrumental in strengthening one another,
and spreading the kingdom of the dear Son of God.
The Meeting for Sufferings being held in the afternoon, my companion and I attended it.

On first-day we attended the morning and afternoon meetings at the old house.
In the former,
it appeared to be my place to hold up the indispensable
necessity of dying daily to our own wills and inclinations;
that so we may know Christ to live in us, by his Holy Spirit;
that being crucified with Him, the life which we now live in the flesh,
may be by the faith of the Son of God, who loved us, and gave Himself for us.
In our religious assemblings,
it is needful to endure patiently the stripping and desertion which He sees proper,
that we may be prepared to be filled by Him, with his goodness;
and with a qualification to make the offerings He prepares and calls for.
A feeling of solemnity spread over us, and His name was secretly praised,
who puts forth and goes before.

On second-day commenced the business of the Yearly Meeting.
Its sittings were attended with a general quiet, and much unanimity in its decisions.
Ministers from North Carolina, Indiana, New York, New England and Philadelphia,
were present.
Committees were appointed by both meetings to visit the subordinate branches,
both the select and those for discipline.
The Meeting of Ministers and Elders sat twice in the week.

In the last of these sittings,
I adverted to the attempts to lay waste some of the testimonies of our Society,
made in former times, by unsettled, discontented members,
who were soaring above their places; but who eventually fell away and came to nothing.
We had recent evidence of this, in those, who but a few years ago,
assailed the peace and order of the Society.

And I believed this would be the end of all who persisted in such work.
Though they might soar as among the stars, and build their nests on high, the Lord,
in his own time, would bring them down and lay them as in the dust.
He would not permit those testimonies, which He entrusted our forefathers with,
to be destroyed; nor this people, if they are faithful to Him, to be laid waste,
whom He had raised up to hold forth the standard of pure righteousness to the world.

On sixth-day morning the Select Committee was appointed to visit the meetings.
Much was said respecting the spirit in which this visit should be made;
and when the stream that way subsided, I felt a concern for those who were to be visited;
that they might receive it in a proper spirit,
and guard against the insinuations which the enemy was watching to infuse into the mind,
for the purpose of closing it up,
against the sincere concern of their Friends for their help.
If any had swerved from the right way, it would be well for them to draw into retirement,
and seek the presence of the Searcher of hearts;
that they may be favored with a clear view of their condition,
and ability to confess their sins unto Him,
and witness restoration to the unity of the body;
so that its circulation may be witnessed without obstruction.

The numerous subjects which engaged the time of the Yearly Meeting,
extended the sittings until seventh-day.
Near the close, the language of encouragement was held out to honest Friends,
to put their trust in the Lord Jesus Christ, the leader and commander of his people.
Trials had ever attended them.

The Apostle admonished one of the churches, that even from among themselves,
men would arise, speaking perverse things, to draw away disciples after them.
Friends here would have their trials and difficulties;
but those who dwelt under a sense of their inability to preserve themselves,
and were endeavoring to maintain their confidence in Him,
who has been the refuge of his people, will know his Name to be a strong tower,
in the day of trouble; to which they may run and find safety.
He who has been with them in many conflicts, will not forsake them in others;
but will mercifully condescend to sustain them to the end,
and crown them with joy unspeakable and full of glory.

Friends parted with feelings of near affection for each other;
thankful for the gracious extension of Divine help, solemnizing them together,
and enabling them to transact the concerns of the meeting with decision and harmony.
