== Chapter VIII

[.chapter-synopsis]
* 1836--1837. Finishes the visit in Western Pennsylvania
* Concern respecting the wrongs of the Colored Races in the United States
* Yearly Meeting of 1837
* Reflections on a Worldly Spirit and the State of the Country
* Second Religious Visit in New England.

Some of our kind friends of Westland and Bedstone,
having made arrangements for conveying us into that Quarter,
we left Mt. Pleasant on first-day morning; Mildred Ratcliff being in company.
Attended Concord Meeting,
where my mind was invested with a concern on account of
an undue attachment to persons or things;
which subjects to the danger of losing that sensibility
and discernment which the Truth gives.
"`Let not the wise man glory in his wisdom,
neither let the mighty man glory in his might; let not the rich man glory in his riches;
but let him that glories glory in this, that he understands and knows Me,
that I am the Lord, which exercises loving kindness,
judgment and righteousness in the earth.`"

If we are indulging in inordinate attachment to persons or their gifts,
we thereby suffer something to get between us and Him,
who only has the right to the possession of our hearts,
and by this means our allegiance to the King of kings will be affected.
Our greatest wisdom is to know the Lord executing his righteous judgments in us,
against everything that stands in competition with his Divine government;
and thus we shall experience his loving kindness to
preserve us from the snares of our cruel enemy,
however subtle and insidious they may be.
The meeting closed with supplication for continued help and preservation.

The following night we lodged at Washington, thirty-two miles from Wheeling;
and the next day reached John Fisher`'s, at Westland.
In the course of the ride,
our friend Mildred Ratcliff related several instructive incidents in her life.
Her parents were Baptists, residing in one of the Southern States;
and she was educated in that profession, sprinkled when a child,
and plunged into water at mature age.
At quite an early period of life, her mind was brought under very serious impressions;
particularly on account of the condition of the blacks,
held in slavery by her father and others.
The cruelties to which they were subjected, especially the flogging of females,
affected her deeply.
When quite a child,
her tender sympathies were drawn towards the infant children of the slaves;
and though not allowed to mingle with those that occupied the outhouses,
called the negro quarters, she would privately visit them,
and carry to the little creatures small portions of food,
which she had clandestinely procured, to feed them.
At first, having rarely seen a white face, they would shun her from fear;
but after a few visits, they showed a fondness for her,
and would cry after her if she left them without giving them some eatables.

One day after being at a meeting of her own profession,
where she was favored with some fresh convictions, she told her father,
as they returned home, she believed the blacks ought to have their freedom.
Her mind was also clearly convinced of the obligation which Christians were under,
to keep to simplicity in their dress;
and though her sisters conformed to the fashions of the place,
she had her clothing made in a very simple manner,
particularly at the time of her marriage; this was at the age of sixteen.
Her father gave her a number of slaves on settling her, which she accepted; having got,
in some degree from under those early convictions.
She was not, however, left in this state,--they were renewed,
and she liberated all her slaves.
One, however, who had nursed her in infancy, refused to leave, saying to her,
you cannot do without me, I have as much liberty as I want, I shall never leave you;
and accordingly she remained till death.

The journal of John Woolman falling in her way, she concluded one day to look into it,
in order to see "`Whether the Quaker could write anything that had any sense in it.`"
She proceeded but little way before she discovered that the
sentiments and experience of that self-denying follower of Christ,
corresponded very exactly with the openings of Truth in her own mind,
and feeling a strong desire to become further acquainted with it, she read it,
at first secretly, and then openly;
as she soon became convinced it contained the doctrines of Truth.

This work not only sealed on her mind the duty of manumitting her slaves,
in which her patrimony mainly consisted,
but prepared the way for uniting herself to the despised Quakers; an event,
of which at the time of marriage, though her husband was a member,
she had neither the slightest inclination or expectation.

At her request, in the evening, we walked to her house, and,
her health being so delicate as frequently to require her to be on the bed,
we spent our time mostly in her chamber.
Next day being the regular meeting at Westland, to which she belongs, we attended it,
some little notice having been spread in the neighborhood.
The doctrine of regeneration, by obedience to the Grace of God in the heart,
was preached to some who had long slighted its convictions;
and the young people were tenderly invited to yield
themselves to the visitations of their blessed Savior;
who, if they received Him in the way of his appearance to their souls,
would tabernacle with them,
and become their teacher and preserver from the snares of their unwearied enemy.
Mildred Ratcliff added an invitation,
to join in with what she believed to he a renewed offer of help from our Heavenly Father.

The next day we were taken by our kind and attentive friend John Fisher,
to Pike Run Meeting, held since the separation in the house of David Graves,
now in his 84th year.
A qualification was here unexpectedly furnished,
to set forth the indispensable necessity of watching over,
and frequently examining ourselves,
that we may not be deceived by the devices of the unwearied and insidious enemy.
While we were professing a belief in the Divine authority of the Holy Scriptures,
and earnestly recommending their frequent reading,
it was needful to put in practice their precepts,
and profit by the experiences therein recorded.
The things that were written aforetime, were written for our learning;
and are profitable for doctrine, for reproof, for correction,
for instruction in righteousness;
and it becomes us to try ourselves by the doctrines we recommend to others.
We have there recorded, instances of great men swerving from the right way,
through unwatchfulness and disobedience of the Divine command.
The Apostle Paul, though a distinguished minister of the Gospel, said:
"`I keep under my body, and bring it into subjection,
lest that by any means when I have preached to others, I myself should be a castaway.`"
Here he holds out the possibility of becoming a castaway,
and the need of keeping a steadfast watch over ourselves,
and experiencing self to be held in subjection.
The necessity of submitting to the purging, refining operation, which Christ speaks of,
when he compares Himself to the vine and his disciples to the branches,
was also brought into view, as one of the means which He uses to preserve his children.
Even those who have had large experience of his mercy and of his faithfulness;
in clothing them with strength to fulfill his will,
must be stripped and prostrated in abasement of soul.
All the armor with which they were arrayed, in his cause, seems to be taken off;
and scarcely anything left but a humiliating sense of their own weakness and vileness;
and sometimes their past sins and follies rise up against them,
and make them loathe themselves.
These are humbling dispensations; but are nevertheless salutary,
and prepare the creature, if it keeps the word of the Lord`'s patience,
to experience a resurrection into newness of life, from this baptism into death.

"`If we have been planted together in the likeness of his death,
we shall be also in the likeness of his resurrection.`"
"`That like as Christ was raised from the dead by the glory of the Father,
so we also shall walk in newness of life.`"
And we need not be afraid of being forsaken in this state.
He is ever with his children;
and as they endeavor to hold fast their love and allegiance to Him,
He will keep them in the hollow of his hand; and again restore to them beauty for ashes;
the oil of joy for mourning: and the garment of praise for the spirit of heaviness.
These views were held out to some present,
who were in danger of falling into a superficial state; depending upon former experience,
without going again and again into baptism and death.
It was a solid opportunity, in which Holy Help was near,
to qualify for the faithful discharge of duty; and yet,
under a recollection that we are poor creatures,
all needing Divine mercy and forbearance.

Ninth month 16th.
We had an appointed meeting with Friends, and some others, at Brownsville.
I was burdened with a worldly spirit; which, it appeared to me, had overpowered some,
even in advanced years, to a very lamentable degree.
The importance of experiencing a change, and entering into the vineyard and laboring,
though at, the eleventh hour of the day, was seriously pressed upon some;
as well as the benefits of such change and its fruits,
upon the rising generation round about them.
But little relief was obtained, and I left them with the fear,
that the cause of Truth was in a suffering state in that place.
Dined at D. C.`'s; who kindly offered to take us to several of the remaining meetings;
and with whom we went that evening to Sandy Hill, seven miles.

Next morning, 17th, set off for Sandy Creek; a small meeting in the edge of Virginia,
about twenty-six miles southeast of Uniontown.
Notice being given, we attended their first-day meeting; a few Friends,
and some strangers; and rode back to a tavern on the United States turnpike.
Lodged and returned to Sandy Hill, where a mixed company collected by appointment,
at the old meeting-house; the meeting there,
having been laid down by Red Stone Monthly Meeting,
in consequence of the great negligence of the members in attending it.
Neither of these meetings were opportunities of much refreshment to me; but laborious;
though some ability was afforded, in the first, to open the principles of Friends,
on some points.
In the latter, death seemed to have overspread many,
who had long neglected their religious duties.
To some, who were secretly enquiring, Who shall show us any good?
the invitation was held out, to come unto Christ, and take his yoke upon them;
and He would help them;
though they were surrounded by those who had slighted their own mercies,
and were become stumbling-blocks to sincere enquirers.

20th. Had an appointed meeting at Centre;
where the life of religion also appeared to be at a low ebb.
Some seemed little better than blind watchmen;
putting but little restraint on the young people; and some present, it seemed to me,
had fallen into a spirit of defiance against religion itself;
and were endeavoring to bring others into the same state.
The dangerous condition and influence of such persons were plainly held up to view; both,
of those who had the form of godliness, yet denied the power thereof;
and those who were of corrupt minds,
reprobate concerning the faith of our Lord Jesus Christ.
The declaration made to the prophet Ezekiel, that if the sword destroyed any,
and the watchman failed to give them warning,
the blood of such should be required of him, was brought into view; and,
as applicable to parents who would not restrain their children, the case of Eli,
the high priest; to whom Samuel declared the determination of the Lord,
respecting him and his house, because he restrained not his sons in their vileness;
the result of which, was the loss of their lives in one day,
and the ark of God falling into the hands of the Philistines.
Some of these things were brought home closely to individuals present;
and though the testimony of Truth was sharp to some, others were tendered,
and encouraged to give themselves up into the Lord`'s hand;
that He might prepare them to stand in that place,
as witnesses of his power and goodness;
and to be instrumental to draw others from the broad way into the way of holiness.

In some of these meetings, the work which appeared to be assigned me,
was of such a laborious nature, and so little effect evident, that I was, at times,
discouraged; sometimes thought that perhaps I had mistaken my service; and at others,
that I possessed little or no qualification for it;
and yet I could not perceive that I had done wrong; and therefore endeavored to hold on,
in dedication to the Lord`'s will, and in humble reliance upon Him,
for help to fulfill whatever might be my duty.

24th and 25th. Had appointed meetings at Providence and Sewickly;
in which Divine kindness was manifested towards me, a poor creature;
and for the comforting, strengthening and arousing of individuals, in the meetings.
In both there appeared to be a remnant of concerned Friends;
to whom the language of encouragement, to keep close to their Lord and Master,
was extended; also some, who were in danger of losing what they had once known,
and being caught by the stratagems of the enemy, were warned of their danger;
as well as those who were settling down at ease.
"`Such as we sow, such shall we reap.
If we sow to the flesh, we shall of the flesh reap corruption;
but if we sow to the Spirit, we shall of the Spirit reap life everlasting.`"
The certainty of Divine judgment, according to the deeds done in the body, was enforced.
We were afterwards told that a person who sat before me, at Sewickly,
and who rarely attended Friends`' meeting, was a Universalist.
He appeared to be wrought upon.

Sewickly meeting finished our visit in this journey;
and under a tendering feeling of the condescension and goodness of our Divine Master,
thanksgiving for mercies past, and prayer for their continuance,
in the various conflicts and close provings, yet to be passed through,
were offered to Him; and we parted from our friends with sentiments of near affection,
and with fervent desire for our mutual preservation,
in our various allotments in the world and in the church.

There are within the limits of this Quarterly Meeting, a number of valuable,
well-qualified Friends,
who evince a proper concern for the maintenance of our principles and discipline;
but the proportion who have fallen into the love of the world,
and feel little or no interest in those things, is so great, that, taken together,
the body of Friends here, may be said to be in a weak condition.
Cases of violation of the discipline are left too long without attention, in some places.
The number of members at Sandy Hill is sufficient to make a reputable meeting;
but after long labor, they were deprived of their meeting,
in consequence of almost total apathy and delinquency.
Such an instance I was never before acquainted with; and it was sorrowful,
in riding from the meeting-house, to have pointed out the residences of many,
either families, or parts of families, belonging to the Society,
within its former limits; and who, young and old, were they alive in the Truth,
might hold up a noble testimony in that neighborhood.
Surely the judgments of the Lord will overtake
such as thus turn their back upon his mercies,
and the opportunities placed within their reach, to grow in good liking before Him.
I felt much for some,
on whom the principal weight of the affairs of the Society rests here;
and much desired their faithfulness.
Though they may feel burdened with so great part of the care of the church,
and some lukewarm professors, like the murmuring Israelites,
may charge them with taking too much upon themselves,
yet I believed it was necessary that they should be diligent and faithful;
not regarding the insinuations of the scornful;
and they would receive a blessed reward of precious peace;
and be the means of guarding the young people
from the inroads of looseness and libertinism.
The upright example of a few, often exerts a very valuable preserving influence;
it is like the salt that prevents corruption, and gives a good savor.

On sixth-day, 23rd, we rode to Pittsburg,
in hopes of finding a canal-boat to leave the city in the morning, but were disappointed;
and detained at an inn till evening.
To fill up the day, we walked through the town and its environs.
Were it not for the black appearance, which the smoke of bituminous coal burnt here,
gives the city, it would be a very pleasant looking place.
The trade which centers here, from the Monongahela, Allegheny, and Ohio Rivers,
and the canal and railroad from Philadelphia, makes it a lively business town.
It is also a great manufacturing town; particularly in iron and glass;
and a large number of steamboats ascend the Ohio, to load and unload at its wharves.
During the day, the retrospect of the embassy, just finished, afforded a flow, at times,
of as peaceful feeling as I have ever witnessed on such occasions.
About 9 o`'clock in the evening, 23rd of Ninth month, we took the canal-boat,
and reached our beloved homes on third-day, the 27th, in good health.
I found my family in their usual health, excepting our afflicted daughter;
who had wasted much in my absence, by accumulated disease.
But her mind was preserved in much sweetness and calmness.
She continued to decline, until her sufferings were terminated by death,
on the 13th of Eleventh month, aged eleven years.
We all felt the removal of her purified spirit from among us,
her solidity and example producing a useful effect upon the family.

1837+++.+++ By appointment of the Yearly Meeting, in company with my friend Benjamin Cooper,
I went to Plainfield, New Jersey; and attended their Monthly Meeting,
and the Quarterly Meeting of Shrewsbury and Rahway, held there.
These meetings have been much reduced by the separation.
For the few who have been left to maintain our discipline and testimonies,
we felt sincere desires that their hands may be strengthened;
and I was enabled to labor among them,
to dissuade from the influence of the spirit and fashions of the world,
and to draw them into closer fellowship with our Holy Leader;
that they might hold up a clearer light among the people,
and experience a growth in the blessed Truth among themselves.
We were brought near to one another,
and parted with feelings of mutual love and desire for each other`'s welfare.

Our last Yearly Meeting having referred the slavery of the blacks in this country,
to the consideration of the Meeting for Sufferings, that if way opened for it,
it might address the citizens of the United States on the subject,
it was regularly brought before the meeting, at its various sittings.
It was believed that such an address might be prepared, and circulated with benefit;
that the attention of the public mind was much awakened to the importance of the subject;
and many of the members of our Society,
feeling a deep interest in the abolition of this abominable institution,
were joining with others, in such measures,
as they judged would conduce to its extirpation; while, as a religious body, we were not,
at the present time, taking any active steps in it.
From these considerations,
and especially on account of the responsibility
which our silence increased upon ourselves,
some were desirous that the present time might not be suffered to pass unimproved;
believing that Friends,
might be instrumental in strengthening the hands of
those who were sincerely laboring to remove the evil;
awakening others who had taken little, or no hold of it; and, at the same time,
show our members that the Society was alive to the subject,
and still maintained the testimony it has long held,
against the oppression of that people.
After spending some time in deliberating upon it,
in which a large number of the members expressed their unity,
a committee was separated to prepare an address;
embracing the wrongs inflicted on the Indians, as well as on the slave population,
in these United States.
An address was accordingly prepared, which, with some alterations,
was adopted by the meeting in Fourth Month;
and from there carried up to the Yearly Meeting,
where it received the sanction of that body.

Our evening meetings closed with the last first-day in the Third month.
They were generally held to satisfaction, remarkably quiet and orderly;
a good degree of solemnity overspread the assemblies,
and it appeared that the desire for their
continuance in the winter season was increasing.
If the ministers and elders, and active members are preserved in the unity of the Spirit,
they will be seasons of harmonious travail for the welfare and preservation,
one of another, and for the spreading of the dominion of Truth within our borders.
There is a large number of plain young Friends in this city;
and those who are placed as overseers of the flock,
cannot but feel a warm solicitude for them; that they may give up all to follow Christ,
and become standard bearers and advocates in his glorious cause.

Our Yearly Meeting held in the Fourth month was large.
Much interest in its concerns was manifested by the younger members,
whose deportment was becoming the occasion.
We were favored with a good degree of religious weight in our deliberations throughout,
which were conducted and resulted in love and harmony.
Our friend, John Cox, of Burlington, who is in the eighty-third year of his age,
came down on second-day, and joined us on third-day morning.
He was very lively and pertinent in his remarks,
in application to several subjects brought into view by the Queries and Answers.
The number of visitors from other Yearly Meetings was unusually small.
The closing sitting was considered by several of the older Friends,
to be one of the most solemn that we have had for several years.

Fifth month 1st. Our friend, Joseph Gibbons, who,
for many years has been a member and minister in our meeting, died this afternoon,
after an illness of several weeks.
My wife and myself called the day before his death, to make inquiry after him,
and being invited into his room, saw that a great change had taken place.
He labored for breath, and could say but a few words at a time.
She remarked that the work was finishing,
and that she believed he would soon be released from his sufferings.

He added, he believed the Lord would deliver him out of all his troubles;
that the wedding garment was nearly completed,
and that he would be permitted soon to rejoin his beloved companion,
who had recently gone before.
Soon after, he said,
"`'`Lord, now let your servant depart in peace, for mine eyes have seen your salvation.`'
Oh, blessed and glorious conclusion to come to,
through the mercies of God in Christ Jesus our Lord.
I am a poor, unworthy creature; it is all through mercy, unmerited mercy,
unworthy as we are.`"
He expressed much love for us, and took an affectionate leave, saying,
"`May the Lord bless and preserve you to the end of the race;
to the coming of our Lord and Savior Jesus Christ.`"
On taking him by the hand, I said,
I trusted it would not be long before he would be released from all his sufferings;
he replied, "`We must be resigned, and wait the Lord`'s time.`"
He departed the next afternoon, in the seventy-fifth year of his age.

Today our Quarterly Meeting convened in the western end of the Arch street house;
men and women together.
It was a very quiet, solid meeting; and from the sensations which clothed my mind,
I thought the change from a separate meeting of the sexes, was advantageous.
It felt more like a religious meeting; and I trust will prove a proper step.
After the meeting for worship, the women withdrew into the eastern end,
to transact their business.

In the Select Meeting, held on seventh-day preceding,
the state of things among its members, was a little gone into,
and the great necessity of Divine wisdom to guide us,
that we might not improperly exalt or depress
any above or below what the Master appoints,
was spoken to.

12th. In the course of my short pilgrimage, being now in the fiftieth year of my age,
I have encountered some difficulties,
and passed through seasons of deep discouragement on various accounts.
On commencing business for myself, I fully believed that my life, and my talents,
should be devoted to the service of my Heavenly Father.
Though it was necessary to make suitable provision for myself,
and for those who might be dependent on me, yet, in my view,
this was secondary to the main object of serving Him;
and through the aid of his blessed Spirit,
taking part in the interests and concerns of his church and people.

Very early I had the promise, that if I devoted myself to his service,
I should never lack food or raiment.
But though I fully believed the certainty of the promise,
and have never since been permitted to doubt its fulfillment;
yet when things in the outward have worn a gloomy aspect, and my business was very small,
and an increasing family looking to me for their daily supplies,
my faith at times has been closely proved.
This has had a very humbling effect;
and while I have been weaned from the desire after outward things,
both riches and temporal enjoyments, it has tended to bring me many times,
in a prostrated state of mind, to his footstool, and to lay all before Him,
and ask for the continuance of his countenance and mercy towards me,
a poor unworthy creature before Him.
Herein I have experienced the renewed extendings of his unmerited regard;
the load under which my mind had been laboring, was for the present, removed;
and ability was received to feel with and for the afflicted,
and to hold forth to them the language of consolation,
in their secret and bitter conflicts.
Under the discipline of the Cross of Christ,
I have been convinced that much too great a part of the time,
and of the energies of body and mind, are absorbed in the pursuit of worldly things.
A great part of mankind miss of the true enjoyment of
the provisions of a beneficent Providence,
even after they gain them, for lack of living to Him, and not to themselves.
They are kept either in a constant hurried frame of mind, confused,
or in doubt what to lay hold of to obtain happiness,
or they settle down in the love of money; hoarding it, and husbanding it,
out of a sordid attachment to it.
They are in bonds; unable to enjoy, or to see in what true enjoyment consists.
The work of religion is either overlooked, rarely attended to,
or postponed to a future day,
when they think it will suit their inclination and convenience.

I am convinced that it is in our power, as we live in obedience to the Divine will,
to find time for all our duties, social and religious.
Even the poor, with common industry;
as their desires and expenses are circumscribed by the Divine will, may,
through his blessing, procure sufficient food and raiment;
and when it is proper to leave their outward business,
in order to perform their religious duties,
they may confide in his superintending providence over their affairs, and their families,
so that they shall not suffer from their faithfulness.
How simple, and how few are the needs of such!
They do not envy the rich, nor covet their possessions.

"`Their delight is in the law of the Lord, and therein they meditate day and night.`"
They eat their bread with gladness and singleness of heart.
Their labors and their rest are sweet;
and as they seek first the kingdom of God and the righteousness thereof,
all those things necessary to their accommodation, will be added.
Here the devoted follower of Christ experiences the right use of his time and talents;
and the true enjoyment of the various blessings which his Heavenly Father provides,
and bestows upon him.
As time and the energies of body and mind are wasting away, he is growing in grace,
and in the knowledge of those things which pertain to life and salvation;
he is laying up treasure in heaven, where his heart centers;
and he becomes more and more established upon that Rock, against which death, hell,
and the grave, cannot prevail.

Our country has now been at peace with other
nations for several years--the channels of trade,
both at home and with foreign nations, have been open,
and the inhabitants have very extensively engaged in it.
The poor colored population, held in bonds in this land, have been bought and sold,
and taken to the South and Southwest, where they have been driven and worked very hard.
The profits of their labor have whetted the appetite of
the slaveholder for enlarging his operations;
and the disposition to secure himself against the possibility of losing his
bondmen through the growing opposition to the system in the North,
has strengthened, and his excitability increased.
Pride and corruption have risen to a great height.

Not only towards the poor slaves have injustice and cruelty been practiced,
but the poor Indians in the Southern States have felt their dreadful effects,
in a very sorrowful manner.
In violation of treaties, and of the solemn requisitions of the precepts of Christ,
they have been abused;
their situation on their own lands rendered uncertain and dangerous;
and they at last compelled to migrate into uncultivated regions; where, it is said,
not a few have perished from want.
While the citizens of these United States have been living in abundance, those men,
the descendants of Africa, and the natives, once the owners of the country,
have been subjected to a life of rigor and distress, and their appeals disregarded.
Can it be a matter of wonder, if the judgments of the Almighty should overtake a people,
guilty of such oppression and injustice?
Last year the crops of grain, particularly of wheat and rye,
fell much short of the usual product,
and at the present juncture the trade of the country has been suddenly arrested;
many wealthy merchants have failed;
and distress and embarrassment have overspread the community.
It has fallen very heavily upon the South.
Their produce has declined nearly one half in price,
and it is said that some have been compelled to sell part of their slaves,
to procure corn to subsist the rest.
The Lord is slow to anger, and of great compassion; but He cannot be partial;
his judgments will not always sleep.
If the hand of violence continues to rest upon the helpless and unoffending,
we shall experience them to be again and again poured out upon us.

15th. A Convention to revise and prepare a constitution for the State of Pennsylvania,
being now in session,
such members of the Meeting for Sufferings as could be conveniently notified,
met this afternoon to consider whether the cause of Truth could be promoted,
by an application to that body to alter the article on the militia,
so as to exonerate Friends, and all other conscientious persons,
from training or serving in war, or paying any fine for declining to do so.
Four Friends were selected to draft a memorial to that body on the occasion.

19th. Sixteen members of the Meeting for Sufferings met
today to consider the essay of a memorial,
prepared to be laid before the Convention.
The subject was renewedly deliberated on;
and after some time spent in examining the document, it was adopted;
and three Friends were appointed to take it to Harrisburg.

25th. Today I laid before the Monthly Meeting a prospect,
with which my mind has been impressed for some time,
to attend the New England Yearly Meeting,
and visit a few meetings in the neighborhood of Newport;
which I had in view when in that country a few years ago.
The concern was owned, and a minute granted.

31st. After a silence of nearly six months, in our own meeting,
it appeared to be my place this morning, to warn some who were growing lukewarm,
and gradually swerving from the strait and narrow way; of the loss they were sustaining,
and the danger to which they are exposed.
Many are called, but few are chosen.
Though they may at first obey the call; yet through unwatchfulness,
and an unwillingness to suffer the seed sown in their hearts to take deep root,
and spread there; like those comparable to stony places; when trial overtakes them,
the plant of renown withers,
and they never bring forth fruit to the praise of the heavenly Husbandman.

Sixth month 8th. I set off, accompanied by my friend, Joseph Snowdon,
to attend the Yearly Meeting on Rhode Island, and a few meetings belonging to it.
We got into New York about two o`'clock; left it at five o`'clock;
and at six on the following morning, found ourselves entering Newport harbor.
On landing, we rode out to David Buffum`'s.

Seventh-day morning, the 10th, went to Portsmouth,
and attended the Meeting of Ministers and Elders; which, through the most of it,
was a heavy time.
The clerk remarked, just before concluding the meeting,
that things had not passed on as currently as was usual;
and wished every one to search for the obstruction.
I had some serious feelings,
and made some remarks in relation to the importance of holding a Yearly Meeting;
and the necessity of every one keeping their respective places,
so as to act under Divine direction.
It was no uncommon thing to feel barren, and destitute of Divine good,
at the commencement of such meetings; and if we made a right use of such dispensations,
their proper effect would be to drive us to the Master`'s feet;
there to wait for his arising, to qualify for his work;
and when He puts forth his sheep He will go before them.

We must be emptied before we are prepared to be filled;
and as we are engaged to keep our habitations in the Truth, we shall, in his time,
find that there is bread enough in his house, and to spare.
Several Friends spoke a little afterward, and we were in some degree quickened together.
Many of the members present,
whom I had seen in the course of my journey in the Eastern States, a few years ago,
expressed their satisfaction in now seeing me with them, and the feeling was reciprocal.
In the afternoon attended the Meeting for Sufferings.

11th. We stayed at Portsmouth, and attended the morning meeting.
It was composed of many persons not of our profession,
and a pretty large collection of Friends.
Wm. Kenard, of Ohio, spoke some time very suitably;
and my mind being brought under exercise,
I believed it right to hold up to view the coincidence between
the prophetic testimonies of the Psalmist and Isaiah,
and that of our blessed Lord himself; as also of the Apostle Peter respecting Him;
that He is the only way by which we can come to the Father,
and be made partakers of salvation.
I was concerned to show how we were to become true believers in Christ, by obedience;
by receiving Him in his coming into our hearts;
and thus being true witnesses of his power and goodness,
in delivering us from the bondage of corruption,
and bringing us into the enjoyment of the liberty of his sons.
The young people were affectionately invited to enlist under his banner;
that they might receive the blessings which He has in store for them.
The awful consequences of unbelief, and a willful denial of the Lord Jesus,
were brought into view;
also the wretched condition of him whose only hope is in unbelief,
and in destroying the authority of the holy Scriptures.

They were solemnly cautioned against this dark spirit,
and invited openly to confess the Lord Jesus Christ before men,
in their lives and conduct.

In the afternoon we came to Newport, and attended a very large meeting there.
Several Friends bore testimony to the Truth;
and towards the close it was impressed on me,
to show that religion is not a speculative thing, but a real, heartfelt work.
The prophet Malachi compared the dispensation, to be afterwards introduced,
to the burning of an oven.
John, the forerunner, said, that the axe was laid to the root of the trees,
and every tree that brought not forth good fruit, was to be hewn down,
and cast into the fire.
He that sent him to baptize, said, "`Upon whom you shall see the Spirit descending,
and remaining on him, the same is He which baptizes with the Holy Ghost.`"
Whose fan is in his hand, and He shall thoroughly purge his floor,
and will gather the wheat into his garner;
but the chaff He will burn with fire unquenchable.`"
Here the operation of Christ`'s religion is, in three places, compared to fire.
From there I was led to describe some of its effects,
in rooting out and destroying every evil plant and fruit in us;
and thereby preparing the soul to receive Christ, and his kingdom and government.
Where this is experienced, love prevails; first to our heavenly Father,
and then towards one another, and all mankind.
Here, wars and confusion are brought to an end; and all such,
being baptized by one Spirit into one body,
become united together in spreading the kingdom of the Messiah;
whose design and work it is, that it may extend from sea to sea,
and from the river to the ends of the earth.

12th, 13th and 14th. Attended the several sittings of the Yearly Meeting;
in which way opened to hold forth the ground on which our religious Society was gathered;
that of entire dependence upon the Minister of the Sanctuary,
in all its religious assemblies.
The importance of rightly maintaining our discipline, was also adverted to;
as a means of preservation to the flock;
and a source of instruction and of useful exercise of
the gifts and faculties bestowed upon us.
The young people were called upon to dedicate themselves to his service;
and as they were properly concerned,
they would be benefitted by the example and wisdom of their elders;
and feel their hearts knit to one another, and to their more advanced brethren,
as that of Jonathan and David were, in the work of the Lord, in their day.

The practice, which has obtained in a few places, of opening Friends`' meeting-houses,
for other purposes than those of the concerns of our Society, having rested much with me,
I mentioned it at the close of the afternoon meeting, on third-clay,
for the consideration of Friends, in their different localities.
It was taken up by the meeting; and the practice disapproved;
and the clerk directed to prepare a minute on the occasion,
to go to the subordinate meetings; which was adopted the following afternoon.

The Yearly Meeting concluded, with one sitting, on sixth-day; having been enabled,
through Divine kindness, to conduct and result its business in much harmony.
When such a feeling prevails,
it tends to unite Friends of the same meeting to each other, and also to their visitors,
in stronger fellowship;
by which we may be qualified more availingly to advance
the cause in which we all profess to be engaged;
sectional feeling and prejudices, if they exist, come to be softened down;
and the way opened to benefit, and be benefitted by, one another.
However great the attainments of any may be, if they keep in a proper disposition,
they will find something to instruct and enlighten them, in almost all places;
and such a state of mind is peculiarly needful,
to fit us to impart instruction to others.
A due regard for the peculiar habits and views of those we visit;
but without giving away the truth and the judgment of Truth;
will often render it more practicable, to convey in a suitable way, our own sentiments,
and availingly impress them upon others.

On the afternoon of sixth-day, we went by steamboat to Providence;
attended their meeting for worship on first-day morning;
and were at the boarding-school in the afternoon; in both which,
Divine help was granted to preach the gospel.
We sat an hour and a half, before the way opened for me to say anything;
but afterwards a qualification was granted,
to enforce the importance of cooperating with the means which Divine mercy has provided,
to enable man to work out the salvation of the soul.
This is very simple in its requisitions; but must, nevertheless, be accepted and obeyed;
if it is not, we shall be rejected and left to ourselves.
The expressions were brought into view,
"`They have Moses and the prophets, let them hear them;`"
"`If they hear not Moses and the prophets,
neither will they be persuaded though one rose from the dead.`"
Naaman, the Syrian, was offended at the simplicity of the means pointed out for his cure;
but when he yielded, it effected the object,
and his flesh returned as that of a little child.
It was a pretty open time.

In the afternoon, the protection of our Heavenly Father, extended to Jacob and Joseph,
when separated from parental care, was held up to the view of the children,
at the boarding-school;
and their caretakers were encouraged to apply
for that wisdom which is derived from above,
to enable them to go in and out rightly before their interesting charge;
and so to govern them, as to bring them to Christ; that they might be prepared,
as good ground, to receive the precious seed of the kingdom in their hearts.

19th. We had an appointed meeting at Cranston in the morning,
and one at Greenwich in the afternoon.
They were both seasons of Divine favor.
In the latter, the caution of the Apostle,
to "`Beware lest any man spoil you through philosophy and vain deceit,`" etc,
was impressed on the audience; and the danger of a captious,
cavilling spirit pointed out; and the visited souls of little experience,
cautioned against talking away religious convictions and impressions,
by which they would suffer loss; and to beware of skeptical persons,
who would watch to betray them, and turn them aside from the truths of the gospel.

We went home with our friend T. H., where we passed the evening and following morning,
very agreeably, the weather proving rainy.
Here we were furnished with a chaise, and piloted to Hopkinton;
where we had an appointed meeting in the morning
(21st;) and one in the afternoon at Richmond;
both of them rather trying; though in the latter part of the first,
Truth rose into dominion, after a drowsy, lethargic spirit was exposed and reproved.

On the 22nd, attended Towerhill Meeting, and on the 23rd,
had an appointed meeting on Canonicut Island.
The first was a very laborious meeting;
the spirit of the world having gained such ascendency in some,
that they appeared to be almost swallowed up by their various pursuits;
so as to give little or no time to the great work of salvation.
Such, occasion much painful feeling to those who visit them in the love of the gospel;
and block up the way for the stream of comfort and consolation, to flow to the weary,
yet pursuing pilgrim.

After dining with our friends J. and M. R., who reside on Point Judith,
we walked down to the seaside to view a large stone wharf,
which a company were building for a steamboat landing.
It was pleasant once more to visit the house of these Friends,
who accompanied me in 1823, from the Yearly Meeting at Newport, to Canonicut;
where I held my first appointed meeting.

Their son kindly conveyed us, after taking tea, to the house of a Friend,
residing about a mile from the ferry; and in the morning,
we had a pleasant passage back to the Island; the meeting was pretty satisfactory.
We dined at J. G.`'s; his sister Anne, a minister, is in her eighty-fifth year.
She seemed to be in a humble, confiding state of mind;
expressing thankfulness that her Heavenly Father
had granted her the gift of his Holy Spirit;
which had been her support under many trials,
and was her comforter in the decline of bodily and mental strength.

In the afternoon we took steamboat at Newport for New York; and on the following morning,
landed and went to our friends T. and H. Eddy`'s. On first-day, 25th,
attended the morning and afternoon meetings.
In the first, Truth opened the way to set forth the necessity of faith in God;
without which it is impossible to please Him;
that faith which gives victory over our corrupt propensities,
and through which we are enabled to bring forth the fruits of the Holy Spirit;
for as the body without the spirit is dead, so faith without works, is dead also.
The importance of coming to realize the blessings of the Gospel of Christ;
in which we profess to be true believers;
not contenting ourselves in a mere belief and profession, were enforced,
under feelings of love, and sincere desire for those present;
that thus they might be preachers of righteousness in life and conversation;
and lights to others, in the midst of a worldly-minded and dissipated people.
It was a time of renewed favor;
and prayer was offered up for the feeble-minded and fearful,
yet sincere disciples of the Lord Jesus; that He would lift up his Holy Spirit,
as a standard against Satan, in his assaults upon them;
and strengthen them to acknowledge, in all their ways,
the right of the dear Son of God to set up his kingdom,
and rule in the hearts of all mankind.

Our beloved and endeared friend Elizabeth Coggeshall,
having received a severe injury from a fall, a few days before we reached the city;
on going to see her,
she expressed much thankfulness that her life was not taken in that manner;
and that not even a bone was broken.
Yet in a retrospect of the many trials which, in the course of her life,
had fallen to her lot, she was much affected.
I endeavored to comfort her with the fact, that in the midst of all her deep afflictions,
she had endeavored to show forth the efficacy of the religion of the Lord Jesus;
and in the end, as she persevered, all would be well with her.
She was a strength to her friends in the consistent example which she set,
by her meekness and cheerfulness under affliction.
She expressed her fellowship with me in the bonds of the gospel; which was encouraging,
coming from one who had ministered to me when I was an apprentice,
and by her very affectionate notice, not only endeared herself,
but the Truth she preached, and invited others to.

Friends showed us much kind attention in this city, though our stay was short.
We left them on second-day morning, and reached home that afternoon,
with peaceful and cheerful minds;
under a hope that the cause of Christ had not suffered
by us and that He had condescended to open the way,
and go before, furnishing with matter for the states of the people,
according to his Divine appointment.
