== Chapter IX

[.chapter-synopsis]
* 1837--1838. Memorial to a Convention
* Visits to Neighboring Meetings
* Abington, Salem and Burlington Quarterly Meetings
* Concern of the Meeting for Sufferings on account of the Introduction of Unsound Doctrines
* Concord Quarterly Meeting
* Religious Visit within Haddonfield and Burlington Quarterly Meetings.

Seventh month 1st. Several days of this week, I was engaged,
with the other members of the Book Committee of the Meeting for Sufferings,
in reading and examining the Journal of William Savery,
as compiled by my beloved and aged father, now in his seventy-ninth year.
He had been employed, at different times, within the last three years,
in transcribing and arranging the memoranda of that excellent minister of the Gospel,
and having accomplished the undertaking, it was submitted to this committee.

10th. A Committee of the Meeting for Sufferings,
appointed to present to the State Convention,
a memorial relative to the clause requiring military service, or a fine,
went to Harrisburg this day; had conversation with a few members in the evening,
and the following morning it was presented and directed to be printed.
In conversing with several of the members,
we found a number who were disposed to sustain the views of Friends,
and to make such alteration as, they hoped, would be a relief.

We pressed upon them the propriety of securing the liberty of conscience unmolested,
and free from the imposition of any penalty.
Some were fearful if they attempted a direct exemption of such conscientious persons,
they would be defeated;
but by striking out those words which were inserted to relieve them,
and leave the subject altogether to the Legislature;
with the declaration contained in the Bill of Rights,
that no human power shall in any case whatever, interfere with the right of conscience,
Friends might be effectually relieved; at least in time of peace.
The delegates appeared much worn with constant application;
and having decided to adjourn,
they were too unsettled to afford so favorable an
opportunity for impressing our views upon them,
as at an earlier period of the session.

We were, however, better satisfied in going, and doing what we could,
than to defer it longer.
Returned home on the 12th.

15th. My wife and myself went up this afternoon to the
residence of our beloved friends Josiah and Elizabeth Reeve,
at Upper Evesham,
with whom we have had a very agreeable acquaintance and interaction for several years.
They are elders, who are worthy of double honor,
for their integrity and love to the cause of Truth,
and their faithfulness in its defense at the hour of close trial, when many deserted it,
and brought all the strength they could to bear against it.
Judicious in their notice of ministers,
they neither shrink from giving counsel and admonition when it appears needful,
nor from administering encouragement to those who are weary,
to occupy their gifts to the honor of the great Giver,
and to their own and the church`'s comfort.
In their lives and conversation they are examples to the flock.
Shunning parsimoniousness or ostentation, they use this world without abusing it;
and at their hospitable mansion the poor meet with cheerful relief,
and the traveler and friendly visitor an agreeable retreat.
The enjoyments in the social circle of their intimate friends,
are heightened by the ease and freedom with which they entertain them,
and the consciousness of their wishes to render
their house and society a source of pleasure,
as they are the means of instruction and real comfort.

They have had their share of affliction; but endeavoring to wash and anoint,
they have shown the power and excellency of true religion, in supporting through it;
and enabling them to animate and strengthen others with the
saving strength with which they were mercifully sustained.
May they go down to the grave in peace, having the full assurance of hope,
that He whom they have served, will accompany in the valley of the shadow of death,
and graciously confess them as his own;
giving them an inheritance among them that are sanctified, incorruptible, undefiled,
and that cannot fade away.

We attended the meeting to which they belong, on first-day,
and had to sound the alarm to those that are at ease in Zion who are
in danger of contenting themselves with their outward comforts,
as being rich and full, and having need of nothing.
A word of counsel and warning was also communicated to some,
who had made some straight steps and entered into covenant,
but were in danger of losing their zeal, and becoming lukewarm,
and turning back to their former delights.
My beloved wife was favored to intercede for such,
and for those who had few outward helps on their spiritual journey;
and that all of us may be favored with the choicest of blessings,
preservation to the end.

Seventh month 30th. My wife and I attended Abington Meeting.
She had a little to communicate; but on the whole, it was an exercising meeting.
Dined with Margaret Shoemaker, the widow of our late beloved friend Charles Shoemaker,
deceased a few weeks since.
He was a man endowed with a good understanding; and through the power of Divine Grace,
he had experienced a change of heart;
so that though he was possessed of an extensive knowledge of men and things,
he was clothed with the humility and gentleness of the Christian.
His conversation was instructive and interesting;
and his kind and affable manners rendered his society very agreeable to his friends.
There was a dignity in his deportment,
and a shrewdness and clearness in his observations, which commanded respect,
while they attracted the affection of his younger friends.

The Monthly Meeting occurring on the 31st, we attended it;
and the way opened to hold forth the efficacy of
true faith in the grace of our Lord Jesus Christ;
and the necessity of keeping it steadfastly unto the end;
that so we might fight the good fight, and finish our course with joy,
in the prospect of receiving the crown of righteousness,
which is laid up for all that love Him with sincerity.
The visitations of heavenly love in early life,
and the advantage of obeying the Divine voice, as Samuel did,
were pressed upon the young people.
It was a tendering time to many of them;
and my dear wife was favored to petition the Father of mercies, on behalf of the youth,
the strong men, and the fathers and mothers,
who had held forth a hand of help and encouragement to others; but who,
as they drew near the close of their day, were assailed with the buffetings of Satan;
and sometimes with fears lest they should not, at last,
find that resting place and blessed reward they longed for.
We returned home in the evening, satisfied that we had made the visit.

Eighth month 7th. Our Quarterly Meeting was held this day; and, on the whole,
was a comfortable meeting.
I think we were helped and strengthened.

10th. Today I attended the Quarterly Meeting of Abington, held at Germantown.
It appeared to me, that more willingness was needful among us,
to partake of the cup and baptism which our Lord partook of;
that we might dwell with the seed, which is under suffering in various ways.
Were we daily preserved here, we should become more quick of understanding in his fear;
and receive qualification from Him for his service in the church.
There is danger of being wise in the letter, and remaining on the surface;
without a deep,
inward acquaintance with the teachings of the Holy Spirit in our own hearts.

17th. I went to Salem Quarterly Meeting, held at Woodbury.
After Hinchman Haines and Rebecca Hubbs had borne testimonies,
I was engaged to hold forth the importance of faithfulness in little things.
As our growth in the Truth was by slow gradations,
so he that despised the day of small things, would fall by little and little.
The departure of such from the straight and narrow way,
as well as from the entrance into it, was from a small beginning; and if we left it,
though we might think we kept much in the same course,
yet every step took us further and further from it.
Little things were often an indication that some
were losing that sincere love to the Truth,
and fervent desire to walk in it, which they had once felt.
It might be in some small departures in dress, language or manners,
from the simplicity of the Cross, which their friends would be painfully affected with;
though they might not at once disclose to them,
the sorrow and exercise which it occasioned them.
The eye which had been closed, would be opened to look upon temptation;
and that eye which the Lord had anointed and opened to see, in measure,
the beauty and excellency of the Truth, would become dim;
and they would not be able to see things in the true light, as they had once seen them.
Their judgment would be clouded;
and the way opened for the tempter to gain further advantages;
and having departed from the path cast up for the Lord`'s children to walk in,
they could not foresee where they might be permitted to wander,
or into what temptation they might fall.
Warning and invitation were extended to the youth;
and the language of encouragement to the honest-hearted travelers, who might,
in this day of stripping, be like one of a family and two of a tribe;
mourning over the desolations of Zion.

28th. My wife and myself went to Burlington, to attend the Quarterly Meeting.
Some ability was furnished to labor among them,
particularly in the meeting held on third-day.
It appeared to be my place to hold up the glory of the Gospel dispensation;
which consists in the universal outpouring of the Lord`'s Spirit on all flesh,
agreeably to the prophecy of Joel, and the revelations made to John the beloved apostle;
when he saw the pure river of the water of life, clear as crystal,
proceeding out of the throne of God and of the Lamb;
and the universal invitation to partake of it, in this language:
"`The Spirit and the bride say, come: and let him that hears say, come:
and let him that is athirst come; and whosoever will,
let him take the water of life freely.`"
The necessity of obedience to the early manifestations of this Divine Spirit, which,
as it is received and obeyed, becomes as a well of living water to the thirsty soul;
the gradations by which the babes in Christ witness a
growth to the state of young men and strong men in Him,
and through mercy, if they persevere, become established as pillars in the Lord`'s house,
where the streams of that river "`make glad the city of God,
the holy places of the tabernacle of the Most High,`" were opened and enforced,
under the feeling and authority of Divine love.
Near the close, the condition of one or more,
who had long resisted the strivings of this Spirit,
and might be in danger of hearing the awful sentence,
"`Let him that is filthy be filthy still,`" was closely spoken to,
and encouraged to lay hold of the renewed offers of Holy Help.
My beloved wife closed the meeting with reverent, fervent prayer;
in which the last state was feelingly included; also the dear children,
the lambs of the fold; the young and strong;
and those whose earthly tabernacles were tottering,
but who had endeavored to serve the Lord in their generation.
It was a time of renewed favor, for which we humbly desired to ascribe praise,
and thanksgiving, and gratitude to our Heavenly Father.
We returned home next morning.

Ninth month 5th. Went to West-town Boarding School,
where the committee met on the 6th. We found the
concerns of the institution in their usual condition.
The difficulty of obtaining teachers, especially men of proper age,
forms an obstacle in the advancement of the interests of that seminary.

14th. We attended Haddonfield Quarterly Meeting, in which my wife had good service.
In that for ministers and elders,
I felt it impressed on me to revive the importance of keeping our places in the Truth.
That however poor and stripped we may be; whether despised and rejected of men;
if our life is preserved; if we are deriving our strength from the true Vine,
all else will be unimportant.
It is only as we keep here, that we shall be made quick of understanding,
to detect the wiles of the enemy; who is ever watching to ensnare,
even those who have known the voice of the true Shepherd.

15th. In the Meeting for Sufferings held today,
the attention of Friends was called to the changes which some were
attempting to introduce in the doctrines held by the Society.
These innovations are principally directed against the spiritual
views which Friends have always taken of the Christian religion,
and the universal love of God to all mankind; in providing the means for their salvation;
whether possessed of the Holy Scriptures or not.
Such sentiments spread, over the Society by publications,
might have the effect to alter materially the principles of the members,
if they were permitted to pass without correction.
The subject made a serious impression on many minds;
and several expressed opinions in unison with those at first imparted.
One or two, however, seemed to be ignorant of what was alluded to;
and hoped that private labor might be extended,
where it was known that such views were held and propagated.
Our only hope of preservation is in the goodness and
infallible guidance of the Shepherd of the sheep,
who can open a way for his dependent, humble followers,
where at times there appears to be none.

Tenth month.
My wife and myself having long had a prospect of making
a visit among our friends at Salem and Greenwich, N. J.,
we attended their Monthly Meetings in this month;
in both of which we had religious service.
It appeared that there are a few of the younger and middle-aged members,
who are concerned for the cause of Truth, and desirous to be found in their right places.
Encouragement was held out to these, to be faithful in their allotments;
that they may obtain the reward,
and become instrumental in helping others in the straight and narrow way.
We returned home with peaceful feelings, and glad that we had made the visit.

28th. Our first-day evening meeting for worship for
Friends of all the Monthly Meetings in the city, was opened.
This concern was not as animating to some of us, as at previous seasons;
though we could not feel easy to discourage the holding of the meeting.
It was opened in an orderly, becoming manner;
and my beloved companion appeared in solemn, tendering supplication.

Eleventh month 6th. Was held our Quarterly Meeting.
The importance of having our dependence individually placed on the Lord Jesus Christ,
and not on one another, was enforced.
Many were concluding that but little was doing by the Society; and one reason is,
that we may be looking to man, instead of waiting on the Lord,
to know Him to be in the midst,
apportioning to every one his several duty and work in the church.
He is represented in the Scriptures as a jealous God; jealous of his honor and glory;
which He will not give to another, nor his praise to graven images.
It is, therefore, no marvel that gifts are not dispensed as they have been,
while we are looking up to man and honoring him, instead of the Lord of life and glory.

Were we all gathered to the place of true waiting, incense, kindled by fire from Him,
upon the altar of the heart, would ascend,
and He would condescend to smell a pleasant savor in our assemblies.
Gifts, we might hope, would be bestowed,
and babes in Christ be engaged to lisp forth his praise;
and thus an army would be raised to display the banner of the Prince of Peace.
It was thought to be a solid, comfortable meeting.

18th. This afternoon my wife and myself took the steamboat for Wilmington;
and attended the meeting there, on first-day.
The floor was pretty well covered, both morning and afternoon.
There seemed to be those who were relying too much on external performances;
without coming sufficiently to the inward work of religion and
experiencing the regenerating power of the Holy Spirit.
Christ was preached to them, as the way, the truth and the life.
The Holy Scriptures, in which we are true believers, abundantly testify of Him;
but while many exalt these invaluable records, they do not, as He declared to the Jews,
come to Him that they might have life.
As the natural life is of more importance than the food which sustains it,
and the body than the raiment with which it is clothed,
so the life and substance of religion are more
important than the external show and profession of it.
We may have the latter without the former;
but whenever the life and power of religion prevail,
they will regulate both the heart and the outside,
or practical performance of our religious and social duties.
All were invited to press after this inward knowledge of Christ,
and his cleansing baptism; and those who had kept their ground in time of trial,
were encouraged to maintain their reliance on the same
power which had heretofore sustained them.

20th. Second-day morning.
Edward Tatnall took us to Concord,
where we attended the Quarterly Meeting of Ministers and Elders;
and endeavored to promote watchfulness, and the faithful occupancy of their gifts.

21st. The Meeting for Worship and Discipline, in the forepart, was a time of poverty,
and inward struggle for the arising of Divine life;
and towards the period for entering on the business,
it appeared right to hold forth the injunction of the Apostle,
"`Let this mind be in you which was also in Christ Jesus who, being in the form of God,
thought it not robbery to be equal with God, but yet made himself of no reputation,
and took upon him the form of a servant, etc.`"
Submission to his humbling power,
and a willingness to become of no reputation among men,
that we might be prepared for his use, and experience preservation,
were tenderly enforced.
Those who were enduring these refining processes,
were encouraged to hold fast the faith and patience of the saints;
and in due time they would witness Him to return to them, with healing in his wings,
and receive renewed ability to engage in his work.
He wounds to heal, and kills but to make alive again.
The dear young people were affectionately and earnestly
invited to take the yoke of Christ upon them; and,
forsaking those things which prevented their entrance into the path which He casts up,
which the vulture`'s eye has not seen, nor the lion`'s whelp trodden in;
to come and join themselves to those, who, above all things,
were desirous of loving and serving Him.
My beloved wife closed the meeting,
with fervent prayer for the various states which had been spoken to.
In the second meeting,
David Cope was earnestly engaged to stir up the young men to a faithful,
diligent discharge of the duty of public worship,
and the attendance of all our religious meetings.
We rode, in the afternoon, to our brother Joseph Rhoads`' at Marple.

23rd. We attended their meeting at Springfield;
in which I felt constrained to speak on the example of our blessed Savior,
"`Who, when He was reviled, reviled not again; when He suffered He threatened not,
but committed himself to Him that judges righteously:`"
from which, the virtue of Christian forbearance and endurance was inculcated
Several points opened respecting his character and offices,
and the efficacy of his blood, shed for the forgiveness of sins.

Twelfth month.
Our evening meeting on first-day, the 10th, was quiet, but rather a low time.
A lack of a true harmonious labor in the one great cause,
and indifference respecting the object of church fellowship, will produce weakness;
and we shall suffer loss, both individually and as a society,
in the life and virtue of religion.
I am more and more convinced that all our fresh springs, both of the quickening power,
and the qualification for usefulness, are in our blessed and holy Head.
When He withdraws, we cannot availingly act for Him, or for ourselves, and the people.
I have felt much more of my own weakness, for some time past,
than anything like ability for the Lord`'s work.
If it has but the effect,
to fix the determination to refrain from everything which He disapproves,
and to redeem from mere earthly enjoyments, the suffering attending it,
will be well endured.

16th. Our Meeting for Sufferings, held yesterday, was unusually large.
The subject of a more extensive dissemination of
Friends`' approved writings was brought again before it,
by a report from the Book Committee;
which proposed the establishment of an office for their sale and distribution;
and that books written for the use of schools, and for the instruction of children,
should be prepared; some to be historical, some biographical, and some didactic;
the latter taken from the writings of Friends,
and illustrative of their principles and testimonies.

30th. In conversation last evening with my beloved father,
he said that in the course of his experience, he had remarked,
that those Friends who manifested a disposition to palliate
the offenses of those who had broken the discipline,
generally lost ground in a religious sense; and those whom they were disposed to screen,
rarely came to anything in the church; and when such fell away,
they were more severe against the unfaithful ones, than against those, who,
in the uprightness of their hearts, could not compromise the cause of Truth,
but stood steadfast in its support, against wrong things.
He was not in favor of a rigid administration of the discipline;
but he believed that where it was kept to, in a disposition to restore,
and when that failed to produce the effect, to keep to the judgment of Truth;
it would always be found in the end, best for the meeting and for the offender.

1838, First month 3rd. Having been liberated by our late Monthly Meeting,
to visit the Meetings of Haddonfield Quarter, and some in Burlington, and my friend,
Henry Warrington, having agreed to take me in his carriage,
we met at the ferry and went this evening to his house.
Attended their meeting at Westfield, in silence; next day,
the Monthly Meeting of Evesham;
where the Master qualified to call upon Friends to come into, and maintain inward,
daily watchfulness unto prayer,
that they may witness preservation from undue attachment to the things of this world,
and by a growth in the Truth, become more and more prepared to advance its cause;
and finally to receive the end of our faith, even the salvation of the soul.
It was a season of impressive solemnity.
In the afternoon,
we rode over to the hospitable dwelling of our beloved and honored friends,
Josiah and Elizabeth Reeve.
They received us with the wonted kindness which they have shown to me for several years.
We attended the Monthly Meeting of Upper Evesham;
to which a large number of young Friends belong,
whose appearance indicates a respect for our profession; and I trust, many of them,
are at times, sincerely desirous for their own improvement.
May they be preserved from the snares which Satan prepares,
for those who are surrounded with the possessions and comforts of this world.

7th. Attended Cropwell meeting; it being first-day, and the weather mild and fine,
a large company collected.
It was a great trial to me to be obliged to dwell so much upon
the dangers of being engrossed with earthly pursuits;
but my mind was greatly burdened with a sense of the earnest
pursuit of many after the increase of their worldly interests.
To be diligent in business,
that we may provide properly for those who are dependent upon us, is a duty;
but it should always be pursued with reference to the blessing of our Heavenly Father;
in seeking which,
all worldly acquirement would be regarded as of minor and temporary importance.

After a season of painful labor,
Truth rose into some dominion and tendered the spirits of many;
and the meeting closed with thanksgiving and prayer to our Heavenly Father,
for the present favor,
and for the extension of his visitations to those immersed in the cares of the world;
and to the young people;
that they might be gathered to the teaching and
guidance of the Shepherd and Bishop of Souls.
We dined and lodged at Joseph Evans`'; and a number of young Friends being there,
after reading a few chapters in the Bible, in the evening,
the way opened to renew the call to them, to lives of dedication,
and steadfast walking in the Truth.
Sarah Hillman, who was there, followed in prayer,
that the word spoken that day might be blessed,
and have due place in the hearts of those to whom it was sent.

On second-day morning, the 8th, we attended Haddonfield Monthly Meeting;
and the next day, Chester Monthly Meeting, at Moorestown.
In the latter, ability was afforded to show the importance of renewed baptisms,
to keep the branches alive and vigorous in the Truth;
and to enable them to bring forth fruit, to the praise of the Great Husbandman.
Through ease and negligence,
we may fall into a formal way of performing our religious duties,
and lose that heartfelt concern which we once experienced,
and under which a growth was known.
It is not because we are once in grace, that we shall be always so.
"`If you abide in me,`" said Christ, "`and my words abide in you,
you shall ask what you will, and it shall be done unto you.`"
Again, "`He that abides in me and I in him, the same brings forth much fruit;
for without me you can do nothing.`"
The tendering power of Truth accompanied;
and under it a lively interest was felt for Friends,
that they might really witness the baptizing power of the Holy Spirit,
to purge away all inordinate attachment to the world;
and unite them together in increased love to God, and travail of soul,
for the spreading of the kingdom of his dear Son.
It was a comforting, strengthening opportunity.

The following morning we set off for Great Egg Harbor.
The road lies through a wilderness of pine wood, about forty miles in width.
This timber is cut for the Philadelphia and New York markets;
large quantities of it are consumed by steamboats;
and it is also converted into charcoal for the Iron Works,
located in different parts of the forest.
We reached Samuel Leeds`' near sunset, and next day, were at their week-day meeting.
My mind was introduced into sympathy with some
who have partaken of the cup of affliction;
and the language of encouragement was held forth,
to labor to keep the faith and patience of the saints, and to profit by it,
and affliction would prove a blessing in disguise.
Several states were spoken to,
and vocal prayer put up for the health and strength of
those who were surrounded with difficulties;
and for the prosperity of the Truth among them.

At the lower end of the shore, near Somers Point, we were entertained by Daniel Leeds.
We walked down to the marsh to view the great beds of oyster shells,
deposited there by the tribes of Indians that formerly resided along these shores,
and were the original proprietors of the lands in this State.
It is a mournful subject to contemplate, that a people,
who were the peaceful occupants of this and other eastern parts of these United States,
should now be almost exterminated.
Had a disposition been cultivated to cherish them,
and teach them the arts of civilized life,
it is probable that many would have embraced them;
and by having their lands secured and divided to them in suitable farms,
we might suppose they could have been weaned from their wild habits,
and embodied among the citizens of the country.

The meeting appointed for us was a close, searching opportunity for some present;
and encouraging to the few, sincere lovers of Christ, located here,
to hold on faithfully in the path of allotted duty;
showing forth by an example of uprightness, sobriety, and humble walking with God,
the excellency of the religion they profess:
by which they might be instrumental in drawing others to have fellowship with them,
and with the Father and his Son Jesus Christ.
We parted from them with feelings of true affection,
and sincere desire for their best welfare.

On first-day we attended their meeting at Tuckerton; and the next day the 14th,
were at Barnegat; where we held a meeting, in a school-house, with the few Friends there,
and a number of others.
They sat in a very quiet, becoming manner, both during the silence,
and while some of the doctrines of Christianity were held forth to them.
The meeting ended with fervent prayer; it was mostly a laborious time.
The situation of Friends along the shore,
affords very little hope of much succession from among the young members;
many of them removing to Philadelphia, or other parts of the country.

16th. We rose early; and with diligent traveling,
reached Bancocas about the middle of the afternoon; and on the following day,
attended their usual week-day meeting.
It appeared to me that some present had been brought to submit to the forming Hand,
and were they obedient to the further openings of Truth,
would become prepared for usefulness in the church.
To these the language of encouragement was affectionately addressed;
and those were warned and entreated, who,
notwithstanding the clear convictions of Divine light,
were too ardently pursuing the world,
and putting off the great work of salvation to some more convenient season.
The necessity of worshipping and glorifying our Heavenly Father, whether we eat or drink,
or whatever we do, was inculcated and enforced,
as what ought to be the daily clothing and engagement of our spirits.
In the afternoon, we went to John Bishop`'s; and next day attended Mansfield Meeting.

19th. Notice having been spread for a meeting this morning, at Crosswicks,
Friends and others assembled and filled the house.
Such meetings are not held without producing a deep
concern that the cause of Truth may not suffer;
and I went to it with sensations of poverty and weakness; not knowing how it might end.
But He, whose mercies are over all his works, did not forsake us;
and after a time of silent waiting, I rose with some fear,
having had the subject of the small beginnings of the kingdom of heaven in the heart,
brought before me.
The doctrine that "`The kingdom of God comes not with observation;
neither shall they say,
Lo here! or Lo there! for behold the kingdom of God is within you,`" was shown;
to set forth the commencement and experience of Christ`'s religion to be in the heart.
It was also compared to a grain of mustard-seed, that a man sowed in his field; which,
though the least of seeds, when it grew, it became the greatest among herbs.
Christ gave himself for our sins, the just for the unjust, that He might bring us to God;
but it is only as we receive and obey Him in his spiritual manifestations to the soul;
which, though clear and certain, are often very small and gentle;
that we can fully realize, the benefits of his coming, suffering and death.
All present were solicited to give themselves into his hand;
and more and more devote themselves to his service; that,
through the washing of regeneration, and the renewings of the Holy Spirit,
they might be sanctified; and,
partaking of the efficacy of his blood in the forgiveness of their sins,
they might be prepared, at the awful period when soul and body sever,
to enter those mansions of glory, where the morning stars sing together,
and the sons of God shout for joy.

The meeting ended with prayer for the strengthening of the feeble,
yet sincere lovers of the Lord Jesus,
for the confirmation of those whose hearts were touched that day,
and for the young people; that they might be preserved from the principles of unbelief,
and brought under the government of Christ; to whom with the Father,
thanksgiving and praise were ascribed through the Holy Spirit.
Amen.
I was much overdone by the exercise;
and seemed to have little inclination to converse much throughout the afternoon,
to any one.
We returned to John Bishop`'s, and lodged.

20th. The weather changed from a warm, damp atmosphere, to a clear, cold one;
by which the roads were frozen and made very rough.
On the way to Mount Holly, we called upon our ancient friend John Cox,
being nearly eighty-four years of age.
He had been kept from meeting, about two months, by sickness and feebleness; and,
though not recovered altogether,
he received us with his wonted cheerful and courteous manner.
After sitting and conversing nearly an hour, we took leave of him,
with feelings of respect and affection; and proceeded to Mount Holly,
and held a meeting by appointment at two o`'clock; which was satisfactory.

On first-day morning, the 21st, we attended Burlington Meeting.
Many experienced and gifted members have been removed by death,
within the last thirty years, and few have risen in their places, in this meeting.
The importance of regarding this and other events, as teachers,
to quicken their attention to the in-speaking word of faith, was pressed upon them;
as well as the benefits of faithfulness, as evidenced by those,
whoso lives are devoted to the truth.
My mind was relieved,
under a clothing of affectionate solicitude for the cause of Christ,
and for the best welfare of the audience.

22nd. On second-day morning, we held a meeting at Easton; which was a painful season;
being brought under the apprehension that some, who had begun well,
were in danger of coming short of the crown.

Lodged that night at the house of my kind and very attentive companion H. Warrington.
After I had taken an affectionate leave of his wife and daughter,
commending them to the Shepherd of Israel, he conveyed me down to the ferry;
and I soon reached my beloved family and home; where I found all in good health,
and glad to have me returned to them again.
My mind has been favored with peacefulness, though made sensible that I am a poor,
unprofitable servant; unable to do or say any good thing, without the help of Him,
who I desire may be my Lord and Master.
