== Chapter X

[.chapter-synopsis]
* 1838--1839. Visit with a Committee to Muncy and Exeter Monthly Meetings
* Accompanies his Wife on a religious visit to two Quarterly Meetings in New York
* Causes of Discouragement
* Death of his Father
* His Character
* Visit to Cain and Western Quarterly Meetings.

Fifth month 12th.
A committee, of which I was one,
having been appointed by the Quarterly Meeting,
to visit Muncy and Exeter Monthly Meetings, and their branches, we set off this morning;
and reaching Pottstown, half of the number attended the meeting there, on first-day,
and the rest that at Exeter, ten miles further on our way.
Here I was enabled, after a season of silent waiting,
in which poverty and emptiness were felt,
to enter a little into the states of some present,
and to minister to them under renewed help; and my dear friend, Sarah Hilman,
appeared in vocal prayer.
Several substantial Friends,
members of this--Exeter Meeting--have latterly been removed by death;
and the younger Friends, not having much experience, feel their reduced condition.
Our companions joined us in the afternoon from Pottstown; and on second-day morning,
we set out for Fishing Creek, which we reached on fourth-day;
distance about ninety miles.
Attended their Preparative Meeting next day; and there labored to impress the elders,
overseers, and parents of children, with the responsibility of their respective stations.
There were a few names, even in Sardis, who had not defiled their garments;
and those here who had been favored to resist the
corrupt principles by which others were swept away,
were not to sit down in ease, and negligence of the flock; but to watch over them,
and warn and restrain in the authority and ability which the Truth gives.
Thus they would be clear of the blood of others,
and might be instrumental in preserving them from the snares which surround;
and even to gather into the true sheepfold.
Thomas Kite closed the meeting,
with some suitable exhortation enforcing the previous exercise.

That night we lodged at Andrew Eves; and next morning went to Muncy.
Here we procured a wagon to convey one company to Elkland,
a settlement of Friends in the Allegheny Mountains, thirty miles further northwest;
for which place four of us set out on seventh-day morning.
Parts of the road are rough and mountainous, and not very wide;
so that some of the eminences were dangerous to drive over.
Our horses were true and able, which are very necessary qualities on such roads,
and we got through in pretty good time; being a little before sundown.
Lodged at Joel and Ellen McCarty`'s, the latter a minister with a good gift.
The meeting-house is five miles further on, at Hogeland`'s settlement;
a piece of as bad road as I ever passed over.
We attended the meeting,
and were favored with the presence and help of Him who knows all our needs,
and qualifies to speak to the conditions of the people.
It was shown that faithfulness to our duty was
to be proved by the fruits of righteousness;
that it was possible to make much profession, and to be active in outward performances;
all which might be done with an unchanged heart; but if so, it would avail us no good;
it was necessary to have the inside of the cup and platter first cleansed,
and then the outside would be made clean also.
Some were closely spoken to, and the tendering power of Truth came over us.
Our friend, Ellen McCarty,
has been a good example of diligence and exertion in getting to their meeting,
often through much difficulty.

Hearing of a militia muster about three miles from her residence,
she felt drawn to go there,
and by her faithful dealing with some of the young men there assembled,
she convinced two of them of the unlawfulness of war;
and they afterwards joined the Society of Friends; and the wife of one of them,
we were informed, had appeared in the ministry.
Our feelings were much interested in this place and people,
and we felt hopes that truth would spread among them,
and their condition in many respects become improved.

21st. On second-day morning we resumed our wagon
and retraced our rough road deliberately,
seldom out of a walk.
The streams of water, which are very numerous in Pennsylvania,
are remarkable for their transparency.
Elk Creek and Loyal-Sock are beautiful.
The former falls from an eminence of forty feet, in sight from the road.
We walked to it, and found the passage to it was a large cavity,
apparently cut out of a rocky mountain, ending in a breastwork,
over which the creek falls; the walls rising on each side of the stream.

The rays of the sun being shut out, the spray and surrounding stone work,
from which water constantly oozed, kept the atmosphere quite cool there;
though a few yards out of it, the temperature was oppressively warm.
A considerable mass of ice, left from the preceding winter,
still remained under the projecting walls of rocks.
We got to the house of our friend, Mercy Ellis, before dark;
our women Friends being a good deal wearied.

On third-day morning, 22nd, we called upon two ancient Friends, one of them,
Elizabeth Kitely, a minister, in the ninety-sixth year of her age.
She seemed full of gratitude to her Divine Master for the comforts which she enjoys;
and though her memory of late occurrences fails her,
she expressed much gladness at seeing us.
She said her candle was nearly burnt out;
and the preceding night she thought would have been her last.
Mercy Ellis informed us that when of ability to travel,
she had often stopped at houses of strangers, as she felt her mind attracted,
and would communicate counsel and advice;
particularly to persons who appeared to be in low circumstances,
and not in the way of religious instruction.
It was truly pleasant and cheering to see one so far advanced, recounting her blessings,
and seeming to feel nothing but peace.
It formed a happy contrast with a fretful, discontented mind;
so undesirable in one who has nearly done with this world,
and ought to be clothed with a heavenly frame,
waiting in faith for an entrance into a better.

The afternoon proved very wet,
and we were glad to get under the roof of our kind friends, Andrew Eves and wife,
at Fishing Creek, after a ride of twenty miles.
The next day attended Muncy Monthly Meeting, held at Greenwood.
Still very rainy,
which we apprehended made the meeting smaller than it would otherwise have been.
The way opened for some labor in both meetings, and Friends appeared glad of the visit.
The members of this Monthly Meeting are scattered over a great extent of country;
which makes it difficult for the overseers to extend that care
which their welfare and that of the Society require.
On fifth-day morning, 24th, we left the comfortable residence of our friend,
David Masters, and rode thirty-five miles to Spohn`'s tavern, on the Broad Mountain;
lodged there.

Next morning stopped at Pottsville to breakfast,
and to repair a broken stay on one of the carriages;
and that evening reached Maiden Creek; part of the company putting up at Sybilla Starr`'s,
and the other at Enos Lee`'s. Our kind and valuable friend Jeremiah Starr,
died on the day of our late select Quarterly Meeting.
He will be much missed by the members of his own meeting,
and we felt the blank made in his family.
We visited the families of Friends there on seventh-day,
and attended their meeting on first-day; which to me was a very laborious time;
a number of persons being present who, according to my feelings,
were very little acquainted with the work of religion in their own hearts.
It appeared to be my place to hold forth the universal
operation of Divine Grace upon the heart,
as the convictor for sin, and the regenerator of the heart,
where it is received and submitted to.
Very little relief was obtained,
and I felt depressed in spirit on returning to our lodgings.

Third-day the 29th,
was employed in finishing a visit to the families of Friends in Exeter;
in which a degree of heavenly help was extended,
enabling us to enter into the states of the visited; though we felt our own weakness.
On the following day attended the Monthly Meeting;
in which some of the committee labored for their help.
There are some honest-hearted Friends here,
who sigh over the low condition of the church,
and desire its enlargement in the life of religion.
Took an affectionate leave of our very kind friends, and lodged that night at Pottstown,
and the next afternoon joined our beloved families at our respective homes.
The review of this journey affords peace;
for I believe we did endeavor to fulfill our mission according to the ability granted,
and to avoid giving offense on any occasion.

Sixth month 11th.
The streams of Divine life feel much blocked up, by some secret cause;
so that mourning and heaviness have been my portion for some days past.
In addition to this, trade is much depressed;
which renders the means of subsistence more uncertain.
But my faith in the unfailing goodness and providence of an Almighty Protector,
has not been permitted to fail.
We have many more comforts than we have any right to expect;
and have so far been enabled to perform all those little services called for,
away from home, without improperly neglecting the business,
or the oversight of our families.
This I consider a very incumbent duty,
and which may be neglected more than we are aware of, if unwatchfulness overtake us.
Many of the sincerely exercised members of our Society have
been wading along for many years under deep discouragement,
at the little evidence they have of the Truth gaining ground among us,
in this Yearly Meeting.
The late separation cut off many, who ought now to be fathers and mothers,
brothers and sisters in the church.
Some, since that period, have experienced changes,
and made an open acknowledgment of the Truth;
but do not come forth in that usefulness which Christ would qualify for and lead into,
had they kept their covenants, by obedience to Him.
The trials of those who have been endeavoring to encourage and strengthen their brethren,
hoping against hope,
have been latterly augmented by the dissemination of
other unsound sentiments in the Society.

18th. Our meetings for worship yesterday, both morning and afternoon,
were depressing and lifeless seasons; at least as regards my feelings.
There seemed but little capacity even to hunger and thirst after righteousness;
and nothing like ministering to others.
I thought of the appellation by which our Almighty Father is denominated in Scripture:
"`The Lord that hides his face from the house of Jacob.`"
Sometimes sin separates between Him and us; and sometimes He veils his presence,
to prove the love and allegiance of his children,
and to humble them under a feeling of their nothingness,
and lack of all things without Him.

Seventh month 1st.
Notwithstanding the warmth of the weather,
and the number of members absent in the country, our morning meeting was large;
and my wife was led to speak to the states of many present,
in a feeling and affecting manner.
I was drawn to kneel in supplication to the Father of mercies,
that He would administer to the respective states of those assembled before Him;
cause the Angel of his presence to encamp round about us; and preserve,
in an especial manner, the dear children, from the temptations to which they are exposed.
Some hearts were humbled; and solemnity spread over us.

4th. Today we had two marriages at our meeting; a very large concourse attended.
They were addressed on the importance of living conformably
with the doctrines and precepts of our blessed Savior;
as laid down in the Holy Scriptures.
A woman minister knelt in prayer; and, considering the occasion and the mixed company,
Friends thought the meeting was held with religious weight.

Eighth month 17th. My wife having a concern to attend
the Quarterly Meetings of Nine Partners and Stanford,
in the State of New York, and a few meetings belonging to them,
obtained a minute from the Monthly Meeting;
and as the journey was not likely to require much time,
and feeling drawn to accompany her, the meeting gave me a minute of its approbation.

We did not leave home without feelings of reluctance and discouragement;
not knowing what might be our lot.
But having nothing in view, except the discharge of our duty,
we set out on the 3rd of this month, and reached Poughkeepsie, on the North River,
one hundred and seventy-five miles, about half past nine o`'clock.
The weather was fine, and the whole passage was pleasant; the evening being moonlit,
which rendered the river and the highlands beautifully picturesque.
Our boat moved with great ease and celerity;
and the engine worked with uncommonly little jar.

On seventh-day morning, the 4th, our kind and beloved friend Smith Upton,
met us at Poughkeepsie, and took us to a Friend`'s house on our way to Beekman.

First-day attended Beekman Meeting,
in which we both had some service tending to show the
importance of steadfast devotion to our religious duties.
Next morning, the Friend at whose house we lodged, gave us a passage to Oblong.
We attended the Quarterly Meeting, and a meeting for public worship, on fourth-day.
My wife, and our friend J. W. of New York, had the principal part of the service.
There are a number of young Friends, of both sexes,
whose appearance would lead us to hope they are concerned for themselves,
and for the maintenance of the cause of Truth;
and they had our sincere desires and labors for their preservation and growth in it.

Next morning we proceeded to the residence of our friend Sarah Hull, at Stanford.
In the Select Quarterly Meeting held here,
J+++.+++ W. recited the communication of the Master to his disciples,
"`Satan has desired to have you, that he may sift you as wheat;`" also,
that of the Apostle Paul,
"`If any man preach any other Gospel unto you than that you have received,
let him be accursed;`" and held forth the language of warning,
and counsel to watchfulness.
I found it my place to encourage those who had received gifts,
to occupy them under their Lord`'s guidance and direction; following Him in faith.

In the Quarterly Meeting, on sixth-day,
I stood up with the injunction to one of the ancient churches,
and which is applicable to some in the present day:
"`Be watchful, and strengthen the things which remain that are ready to die;
for I have not found your works perfect before God.`"
To be qualified to strengthen others,
we must be sensible of our own weakness and imperfections;
and in our humiliation before the Lord, in his own time He will arise,
and clothe with ability to labor in his cause, for the help of others.
It appeared to me there was need for individual examination;
that the things which remain, but are ready to die, might be strengthened;
and the works of some be made more perfect before the Lord, than they had yet ever been.
The reduced state of this meeting, in point of numbers, is affecting;
and but very few young members are coming up, under the preparing hand of the Lord,
for service in the church.

Having no meeting appointed on seventh-day,
we stayed at the pleasant residence of our kind friend Sarah Hull,
widow of that excellent minister of the Gospel, Henry Hull.

First-day 12th. Attended Stanford Meeting in the morning,
and one appointed at the Creek in the afternoon.
My dear wife had the chief of the service in both.
I trust they were held to profit, to individuals who were present.
Next day we had a meeting at Nine Partners,
in which she found it her place to treat on the subject of the ministry.
I felt engaged to hold forth a warning against the danger of forsaking the Truth,
and joining with that which will deprive us of the crown,
that is in reserve for those who continue to the end with our Lord,
in the temptations or trials which beset his church and cause.

"`Blessed is the man that endures temptation; for when he is tried,
he shall receive the crown of life.`"
When his fidelity and allegiance are fully proved,
his Lord will come forth and reward him with his presence and acceptance;
and as such hold out to the end,
the incorruptible crown of glory will be mercifully granted to them,
in the kingdom of their Father.
We returned in the evening to our friend Asa Upton`'s and spent the next day there,
and at the houses of his brothers, Paul and Smith.

On fourth-day, the 15th, we took our departure homeward, where we arrived in safety,
the next afternoon;
having the clothing of peacefulness in the fulfillment of this little portion of duty.

Ninth month.
On the 11th I went with my brother Joel to West-town School.
We had a very tendering time in the meeting there, in the forenoon.
The danger of losing our first love, and relying upon what we have known in time past,
without experiencing the renewed baptisms of the Holy Spirit, was held up to view.
In this condition we may be deceived respecting ourselves,
and suppose that we are in a better state than we really are.
Watchfulness unto prayer, and the disposition to desire those proving dispensations,
wherein we experience a being baptized into the likeness of Christ`'s death and suffering,
were recommended; that thus we might, from season to season,
be raised up into newness of life; and be qualified from experience,
to testify to the Truth; and not merely because we have read or heard of it,
through others.
Sarah Emlen knelt, returning thanks for the present favor,
and praying that messengers might be sent forth to roll the stone from the well`'s mouth,
as it had been done that day; that so the flocks might be watered;
that the word preached might sink deep into the hearts of some present,
who were ashamed to confess their Lord before men;
and that their eyes might be anointed to see,
and to discriminate between the chaff and the wheat;
the alloy and the precious gold and silver.
It was a season of renewing our strength and confidence in the
mercy and goodness of the unslumbering Shepherd of Israel;
for which we desired, in reverence and humility,
to return thanks to his great and worthy name.

I stayed the afternoon meeting, and also sat with the boys in the collecting room;
in both of which, counsel was extended on other subjects;
and on the next morning returned to Springfield, and so home;
enjoying the calm of peaceful poverty, yet well satisfied that I went.

25th. Yesterday my wife and myself attended Frankford Monthly Meeting, held at Germantown.
It was a day of Divine favor; the blessed Head of the Church qualifying us both,
to preach the Gospel to the weary and tried among them, and to the younger members;
inviting them, under the influence of heavenly love,
to obey the discoveries of the light of Christ, and taking his yoke upon their necks,
to follow Him whithersoever He leads.

From the state of many meetings,
there is reason to fear a declension from the life and
power of religion among us is taking place.
Death is removing the older members, and comparatively few of the younger,
appear to be coming forth in dedication to the work of the Lord.
Unless the Head of the church turns his hand upon sons and daughters,
and raises up a band of faithful laborers, clothing them with zeal as with a garment,
for his cause and honor`'s sake, there is reason to fear, that in some places,
the Society may become a desolation.
Such a picture is truly mournful; but what can we expect,
when so little fruit has been produced,
after so many gifts and favors have been conferred upon us.

Eleventh month 30th. The ministry of the Gospel is a mystery to those who are
unacquainted with the teachings and movings of the Spirit of Christ in the heart.
I have many times been instructed by the gradual unfolding of matter,
designed to be communicated in a religious assembly.
If we are not preserved in patience,
it is possible to miss the particular point which is designed to be held up to view,
or to give a wrong construction to the portion of Scripture
brought before the mind He who has the work in his own hand,
and sees the needs of the people, can alone prepare the creature for his service,
and that which He intends for them to do.
There is at the present time much unsettlement among many of the members of our Society.
They are attracted by wordy, doctrinal discourses, which fill the head,
and leave the heart little benefitted.
An aversion is produced to a spiritual, practical ministry,
which lays open the negligence and unfaithfulness of the professors,
and insists on the indispensable necessity of self-denial,
and a steadfast following of Christ in the way of the cross.

Many appear to want a religion without a cross;
and to be ranked among the followers of Christ,
without yielding to the baptisms and humiliations which
He introduces the obedient soul into.
But this desire is vain; and all that such may hear will avail nothing,
unless they are brought to Christ; and, in the submissiveness of little children,
take his yoke upon them,
and follow the leadings and discoveries of his divine
and saving light in the secret of the heart.

Twelfth month 1st. My wife and I went to our
beloved friends Josiah and Elizabeth Reeve`'s,
near Medford, New Jersey, and attended the meeting there; in which we both had service.
Our love for these dear Friends increases as they draw near to the period
when the church is to be deprived of their counsel and consistent example.
They have watched faithfully over the flock committed to their trust in that meeting,
and have been favored with the spirit of wisdom and
discernment in the discharge of their religious duties,
as elders and overseers in the church.

1839, Second month.
At our Monthly Meeting I obtained liberty to
visit the Western and Cain Quarterly Meetings,
and the meetings composing them.
As our own Quarterly Meeting occurs in the early part of the Second month,
I deferred leaving home; intending soon after to set out on the proposed visit.

Our friend Daniel Wheeler arrived in this city on the 1st of the Second month,
and attended both the Select and General Quarterly Meetings.
His services were very acceptable to Friends;
his doctrine corresponding with the ancient principles of the Society,
and tending to bring the minds of the hearers to the work of religion,
and to the teachings of Christ in their own hearts.

My dear and honored father had been in a declining state of health for several months,
and on fourth-day the 30th of last month, had a severe chill.
Though he came downstairs on the following morning,
he found himself too much prostrated in strength to remain,
and accordingly returned to his bed; which he left but little until removed by death.
It being proposed to call in a consulting physician he declined, saying,
that at his time of life it was not probable he could continue here long,
and he was entirely satisfied with what his son, the attending physician,
might do for him.
He daily grew weaker, until he departed, on sixth-day morning the 8th,
a little after eight o`'clock.
He was nursed by his children, who watched him with much solicitude.
One morning when asked how he was, he replied, "`very quiet--very quiet, but very weak.`"
I remarked, it was a trial to have those removed, at this time,
who have long stood for the defense of the Truth.
He rejoined, "`I have felt a great deal on that account, a great deal.
I am satisfied there is a spirit at work which would lay waste
the ancient profession and doctrines of our Society,
and draw Friends away from the spirituality of that which they have once known;
and many are caught with it.`"

During the first three days of his confinement, his mind appeared to be under exercise,
and though, as was usual with him, be said little of his own exercises,
I believe he was introduced into a very humbling view of himself,
and made deeply sensible of the frailties which pertain to man;
and that it is only through Divine mercy, after we have done the will of God,
that we are accepted at last.
He became settled in a holy confidence;
being gathered and centered to the sure foundation, Christ Jesus,
the hope of the saints`' glory.
He endured with patience the infirmities produced by advanced age and disease;
alluded with much serenity to his approaching close;
and the peacefulness and heavenly settlement which were felt,
gave evidence that his eye was firmly fixed on the eternal recompense,
laid up in store for those who follow the Lamb of God, whithersoever He leads.
He retained the use of his faculties to the last, and expired without any struggle,
or the change of a feature.
To his children it was a solemn and affecting event; and to the Society,
in which he has long stood as a faithful watchman,
his removal will be felt as leaving a blank that cannot soon be filled.
He was favored with a clear, sound and discerning mind;
and soon detecting the specious appearances of the enemy,
he raised his voice with unwavering firmness against them;
and though he often incurred the censure of the superficial professor,
and of those who sought the honor of men, yet he kept his ground,
and very generally proved that his judgment was correct.
He was faithful in waiting for the arising of
the power of Truth in our religious assemblies,
both for worship and discipline.
It was his delight and life to feel it, both in himself and in the services of others;
and when he was sensible of it, it was his authority for his own movements,
and satisfied him respecting others, however simple and unlearned they might be.
The interment took place on second-day morning the 11th,
and the solemnity which prevailed in the house and over the company,
there and at the ground, was very remarkable;
it was in character with his love of silence and his deep inward waiting,
rather than the expression of many words.

After the decease of my dear parent,
I concluded to put off the proposed visit to Cain and the Western Quarters,
until the close of our Yearly Meeting; but in the course of a week or two,
the apprehension came over me, that it would be unsafe to defer it,
lest it might lose its freshness;
and that the Lord`'s work is not to be done in man`'s time.
Accordingly, I left home, with my brother Joseph Evans,
and on the 23rd of the Second month, rode to Bradford.

Attended that meeting on first-day;
in which I was engaged to revive the language of Elisha,
after the removal of Elijah "`Where is the Lord God of Elijah?`"
and from there to show the necessity of the enquiry after that Almighty power,
which raised up our ancient Friends, and made them a substantial,
spiritually minded people; and to endeavor to stir up Friends to more zeal and devotion;
that through their example,
the young people might be enlisted under the government of the Prince of Peace.

On second-day morning we rode over to East Cain; the traveling being very heavy.
I was encouraged to hope,
that there are a number of young men here who love the Truth and that, in time,
they will be prepared to be useful in the church.
Third-day morning was very wet, and yet a pretty large company collected at Downingtown.
The emptiness of all worldly possessions, as the means of procuring true happiness;
the vanity of man in his best estate, surrounded by all that he can acquire;
and the certainty of death, were brought into view;
and the necessity of redemption from the world,
and an entire dedication to the will and service of God, were affectionately enforced.
It was a season of favor,
in which the tendering influences of Divine love spread over us;
and thanksgiving and prayer were offered for the favor,
and for the strength and preservation of different classes, in the right way.

Fourth-day at Uwchlan.
The people were nearly all strangers to me,
and I had hard labor with the spirit of infidelity; but was enabled to warn those,
faithfully, who were led away with it.
It was a solemn opportunity, after which I felt clear and peaceful.
Next day we attended an appointed meeting at Nantmeal, where very few Friends remain.
The peculiar blessings of the New Covenant,
in which the Divine law is written in the heart,
and we are under no absolute necessity to apply to man for a knowledge of it,
the Lord having placed his Spirit in the hearts of all men, were opened to the people;
a number not professing with Friends being present.
I was led to say, that where He who ascended up on high,
had given gifts for the work of the ministry, the duty of such was,
to turn the attention to Christ; who by his grace, which brings salvation,
appears in the heart; that their hearers might come to be taught and led by Him,
and know Him to become their Redeemer and Savior, the Shepherd and Bishop of their souls,
indeed.

Attended Robeson Preparative Meeting; and the following day,
we got to the comfortable residence of our beloved friend and mother in the Truth,
Hannah Gibbons, at Lampeter, before dark.
Such stopping-places are peculiarly grateful to those who have left all,
in the service of their Lord and Master.
Under the roofs of such, they often find fathers and mothers, brothers and sisters,
and enjoy houses and lands, as if their own;
thus realizing the promises of Christ to his poor, yet dedicated disciples.

Attended their meeting on first-day (3rd of Third month;) in which
the little company was permitted to drink together of the consolation
and strength wherewith the Master rewards them that keep the watch,
faithfully, for his coming;
and the young were affectionately invited to come under his yoke,
that they might witness preservation from the allurements of the world.

On second-day morning, we had an appointed meeting at West Cain,
and another in the afternoon at East Sadsbury.

Both of them were seasons wherein Holy help was extended,
to minister to the states of the people.
When we got to West Cain,
we found that a separatist from New York had
appointed a meeting at the same time and place;
which at first felt trying to us; but being early at the house, we took our seats,
endeavoring to retire in spirit to the Master, for his help and direction.
Friends gathered pretty promptly, and filled the gallery and the seats under it;
and notice having been spread, that two ministers were to be there,
the house was early filled by Friends and others.
A Friend sitting near us, told us after the meeting closed, that two men,
one of whom he supposed to be the separatist, came into the yard, and then rode away.

Most probably, seeing the gallery and house filled,
they declined attempting to force themselves on the meeting; of which we were truly glad;
and thankful to the great Head of the churcl for his goodness,
in solemnizing the meeting,
and qualifying to preach redemption and salvation through Him.
It was as quiet and orderly a meeting as I have almost ever sat in;
and ended with thanksgiving for His continued mercy,
and prayer for the help of those who had been made sensible of it.

The Monthly Meeting of Sadsbury, held today, the 5th, was large.
To deliver close doctrine among our Friends is a trial;
but sometimes the danger of resting in an outside show of religion,
while the heart is unchanged, makes it necessary to search Jerusalem as with candles;
and to call upon the men of Israel to renew the examination of themselves,
as they may be favored with the visitations of the Searcher of Hearts;
who is of purer eyes than to look on iniquity in his church and people.

It was a solemn season;
and though it is more pleasant to the creature to pour in the oil and the wine,
yet I believe no offense was taken at the doctrine delivered.

Fourth-day had an appointed meeting at Bart, which was satisfactory;
and the next day attended the Monthly Meeting of London Grove, held at Fallowfield.
Lodged at S. Swain`'s, and held a meeting in Friends`' House at London Grove,
which was a favored time.
The importance of individual faithfulness was held up to view;
and the doctrine of salvation through the merits and mediation of Christ,
and the sanctification of the Spirit, was preached; and the certainty of the Stone,
cut out of the mountain without hands, increasing and overpowering all opposition,
in the Lord`'s time, was declared in the authority of Truth.
We tarried until the following noon with our kind friend Isaac Pusey and wife;
visited his relative Edith Edge and her daughter, who were at home.
It was refreshing to find there are those, in many places,
whose minds are in good measure imbued with the love of Christ,
and their conduct and appearance circumspect.
From among these we hope to see faithful soldiers raised up,
who will not flinch from suffering and reproach; but, growing in grace and strength,
will valiantly maintain the testimonies which our Holy
Head communicated to us to hold forth in the world,
and for which our devoted forefathers suffered many privations, and not a few,
even death.

The meeting at West Grove was laborious,
under a sense that many are engrossed with the things of time;
and not coming forward in that dedication to the Lord`'s will which He requires;
and thus the testimonies of Truth are in danger of falling to the ground among them.
I missed the help of the spirits of William Jackson and his wife;
two ancient and substantial ministers,
who were removed a few years since to their everlasting reward.
They were living when I last visited this meeting;
and not only treated me with much affection, but were a strength and comfort,
from their staidness of mind, and deep indwelling with the Seed of Life in their hearts.

On first-day morning attended London-Britain Meeting.
The day was fine, and without notice, the members generally,
with some not of us, convened.
The impossibility of the natural man comprehending Divine things;
and the indispensable need of regeneration, to enable us to see the kingdom of God,
were subjects brought before me; and in the ability afforded, I labored with some there,
to bring them to see that all their acquirements, without a change of heart,
would avail them little;
that those who thought they knew something in relation to the things of God,
which they had collected by study and the exertions of their own faculties, as men,
knew nothing in those things as they ought to know.
There seemed to be a self-sufficiency in some,
which rendered it hard work to obtain much relief.
A Friend, after the meeting, expressed that he did not marvel at the labor;
and though I alluded to the trial it is to have to deal with such spirits,
he said he wished me to be faithful, and to be encouraged.

Second-day morning we rode to New Garden,
and a pretty large company of Friends and their neighbors convened;
and though I felt somewhat depressed, yet the good Master condescended to afford help.
Quiet and solemnity spread over us, and I was opened on the importance of a wakeful,
watchful state in our respective allotments in the church;
being withdrawn from all improper dependence on man,
and having our reliance placed on Him, without whom the watchman wakes in vain,
and they labor in vain who build the house.
Some hearts were humbled and tendered.

On third and fourth-days held meetings at Hockessin and Kennett.
These two, form a Monthly Meeting,
in which there are but few young men who appear like Friends.
Most of them having become involved in the spirit, and habits,
and principles of the world, they have lost the simplicity of the Truth,
and the love for its cause,
which is the noblest object that can claim the devotion of our time and talents;
and which will truly dignify and render man useful.
The sensations of my mind were mournful,
from a feeling of the great degeneracy of not a few of the children,
even of valuable members of the Society, and I left them with heaviness.
After dining, we rode twenty miles to my brother`'s residence at Springfield,
and found his family in good health.
Next morning I got to my own home,
which I think I rarely ever entered with more peacefulness.
I desire to bless and to thank my Lord and Master with humility and reverence,
for the sweet reward;
and to be preserved amid the temptations which yet await my earthly pilgrimage.
