== Chapter XI

[.chapter-synopsis]
* 1839--1841. Yearly Meeting
* Visits various Meetings in Philadelphia Yearly Meeting
* Baltimore Quarterly Meeting
* Visit to Westbury and Purchase Quarterly Meetings
* Attends the Yearly Meeting in Virginia
* Death of his Son.

Fourth month 9th. The Yearly Meeting being near at hand,
brings with it an unusual degree of concern,
respecting the manner in which it will be held.
It is greatly to be feared,
that some have become blinded by a spirit which is seeking to
draw Friends away from the spirituality of our holy profession,
and to bring them into an alliance with the friendships of the world.

Nothing short of the extension of Divine help,
can preserve our poor Society from distraction and division.
May our trust and confidence be placed in the protecting arm of the Shepherd of Israel,
who has ever been the defense of his dependent children;
and though He may permit them to go into deep baptism and suffering,
as they endeavor to keep their faith and reliance in Him, He will bring them up again,
rejoicing in his mercy and faithfulness.

On third-day morning, the Yearly Meeting entered on the Queries and Answers,
and Friends were favored to speak suitably to the different subjects;
holding up the importance of public Divine worship,
and the preservation of the unity which stands in Christ;
wherein we should all speak the same language,
and harmonize in our various labors to promote the
cause of Truth in the church and in the world.
Our ancient testimony to the Light of Christ, as the primary rule of faith and practice,
and the subordination of the Scriptures to it, was held forth,
and a general concern was manifest to keep Friends to our religious profession.
Throughout the various sittings, the meeting was favored with much solemnity.

In the Fifth month, I attended Cain and the Western Quarters,
and was enabled to labor in them under the influence of Gospel love,
for the encouragement of sound-hearted Friends,
and to draw others away from the inordinate love and pursuit of worldly things.
The last meeting was one of renewed favor.

Eighth month 5th. Jacob Green from Ireland, on a second visit to this country,
attended our Quarterly Meeting.
I felt a strong desire that he might be baptized into the
states of individuals and of meetings where he visited;
and through the quickening power of Him,
who declared Himself to be "`the resurrection and the life,`"
be enabled to minister, so as to reach the life in others,
who desire to be fed with that food only which comes from the Divine hand;
and feeling incited thereto, I ventured to express it,
as my sincere and tender desire for him.
My dear wife brought before the meeting a concern to
attend the Yearly Meetings of Ohio and Indiana,
and to visit some meetings belonging to them, etc.,
for which she had a certificate of concurrence from our Monthly Meeting.

8th. I attended Abington Quarterly Meeting,
and was enabled to hold forth the doctrine of our Lord,
when He thanked the Father that he had hid the
mysteries of his kingdom from the wise and prudent,
and revealed them unto babes.
That unregenerate man with all his wisdom and natural powers,
was unable to discover the truth as it is in Jesus.
His pride led him to overlook it, as too simple and too little for him to believe in.
It was only as he was brought down into the dust; into a humble, childlike state,
that he could be prepared to have these things revealed to him.
"`Except you be converted and become as little children,
you cannot enter the kingdom of heaven;`" and unless we enter the
kingdom of the dear Son of God and come under his government,
we cannot see the things that pertain thereto.
When we are brought here, He will reveal the knowledge of God,
and those things which belong to our everlasting peace;
and this knowledge of God and of his beloved Son, as it is thus revealed,
is life eternal to the soul.
Much more was opened, and the meeting was brought under a solemn covering.
A woman Friend closed the meeting in humble,
fervent prayer that the solemn truths delivered that day, might be sealed on every heart,
and that the praise might be ascribed to the Lord alone to whom it belongs.

27th. Having some time felt a draft to the Quarterly Meeting of Bucks,
I took the car to Trenton and from there the stage to New Hope.
I was very kindly received by my highly esteemed friend and mother in the Truth, Ruth Ely.
On fourth-day attended the Select Meeting; in which some ability was afforded to show,
that while we are in no degree to become negligent of our duty,
all over anxiety for the good cause will add nothing to our stature,
nor promote its advancement.
But He who makes the lilies to grow,
and arrays them in a manner far superior to Solomon`'s robes,
can take care of and defend his cause, and prosper it and us,
as our trust is placed in Him alone.
Friends convened on fifth-day morning in greater number than was usual, at Buckingham.
The power of religion appeared low;
and for a time it felt doubtful whether we should know
what it was to rise from the dead into newness of life.
I endeavored to draw near to Him who alone can bring out of the pit,
and open our mouths to declare his will.
After struggling with fear,
I believed it right to rise with the testimony of the Apostle:
"`There is therefore now no condemnation to them that are in Christ Jesus,
who walk not after the flesh, but after the Spirit;
for the law of the Spirit of life in Christ Jesus has set me
free from the law of sin and death;`" and to declare that this
continues to be the case to the obedient soul to this very day.
I was led to open the condition of those who had obeyed
the dictates of the Spirit of Christ in their hearts;
who had submitted to the administration of condemnation for sin;
and after abiding under it the appointed time, experienced a change of condition;
having the love of God shed abroad in their hearts,
and receiving the law of the Spirit of life, and yielding faithfully to it,
came to be freed from the dominion of the law of sin and death.

These were prepared to advance in the spiritual journey;
and as they were faithful to their Divine Leader, would grow from stature to stature,
and witness an establishment in the blessed Truth.
Those who persisted in disobedience, would grow harder in sin;
shame and confusion would cover them;
and they could have no other prospect than separation from the presence of the Lord,
and the glory of his power, "`When He shall come to be glorified in his saints,
and to be admired in all them that believe, at that day.`"
Such as deny the possibility of keeping the commandments of God,
and contend for the commission of sin through life, are not true Christians.
We cannot serve two masters.
Either we shall love one and hate the other, or cleave to one and despise the other.
We cannot serve God and mammon.
A kingdom divided against itself cannot stand.
We must serve Christ or antichrist; and all who submit to Christ,
will be brought from under the government of the prince of the power of the air,
into the freedom of the children of God; freed from sin, as well as the guilt of sin.
There was present, I was afterwards told,
one of those preachers who inculcate the idea
that we are not made free from sin in this life.

Ninth month 5th. I attended the Arch Street Meeting,
where I sat some time under a consideration of my own weaknesses and imperfections.
Clothed with these sensations, we feel entirely unfit for the Lord`'s work,
and are disposed to retire from it, and keep silence before Him,
with the mouth as in the dust.

After a time, I was introduced into a different feeling,
and seemed to be gradually prepared to speak;
but something seemed to give me a gentle check;
with the intimation to wait and examine the presentation a little further;
and on recurring to the passage of Scripture before me:
"`To obey is better than sacrifice,
and to hearken than the fat of rams,`" it appeared to be applicable,
and perhaps designed for myself.
I kept still; and was glad that my Divine Master was so kind and condescending,
as to keep me and instruct me in this way.
May I become more and more conformed to his Divine will,
and prepared to hear and obey his voice.

10th. I went to Medford to attend Haddonfield Quarterly Meeting, and took up my abode,
for the time, with my dear, aged friends Josiah and Elizabeth Reeve,
who are in declining health.
Attended the Quarterly Meeting of Ministers and Elders.

The Quarterly Meeting for business, held next day, was a solid, gathered assembly;
and the way opened to preach the gospel of Christ,
both in relation to the efficacy of his sufferings,
and the immediate manifestation of his Spirit in the heart;
by which He is revealed to the soul as the Redeemer and Sanctifior of his people.

1840, Fourth month.
The past winter has been a season of close, inward conflict;
the way opening for but little service;
and it is to be feared that the unity among Friends has not increased.
I have, however, attended a few meetings out of the city;
and at times have been favored with best help in
the discharge of what appeared to be required.

29th. Our Yearly Meeting was held last week.
The business was conducted with great harmony, as to external appearances;
but there was much secret suffering endured.
The duties of clerk were more trying to me than at any previous period;
so that I felt desirous of a release.
Caleb Pennock, a minister, in his eighty-eighth year,
expressed the encouragement he felt at seeing so many young men there;
he believed that better days are ahead,
and that the faith of this religious Society
would rise and shine with greater brightness.
He rejoiced at believing this, though he might not live to see it.
A memorial, prepared by the Southern District Monthly Meeting of Philadelphia,
concerning my beloved father, was forwarded by the Meeting for Sufferings,
and united with by the Yearly Meeting.

Fifth month.
I obtained a minute from the Monthly Meeting,
to attend the Quarterly Meeting of Baltimore;
and in company with my friend Charles Allen, accomplished the service.
We paid several visits to Friends in that city; in some of which,
the way opened to impart counsel and encouragement to come
under the government and teaching of the Spirit of Christ;
that through its regenerating operations,
individuals might be prepared for service in his church militant,
and union with the church triumphant,
when done with the trials of this probationary scene.
The Quarterly Meeting is very small; also the Select Meeting;
in both of which I had some service.

We rode out to Gunpowder, and had an appointed meeting, on sixth-day,
composed of a few members and others.
Here there is little prospect of a succession among Friends;
and yet it seemed proper to warn them against
discouragement in assembling for Divine worship.
Nearly all the members of this meeting joined in the separation of 1828;
and the reduced state of the remaining members, called forth sympathy with them.

We returned to Baltimore on seventh-day, and visited an afflicted Friend,
in the station of a minister.
The testimony of the Apostle was brought into view:
"`How that not many wise men after the flesh, not many mighty,
not many noble are called but God has chosen the foolish things of the world,
to confound the wise;
and God has chosen the weak things of the world to confound the things that are mighty;
and base things of the world, and things which are despised has God chosen;
yes and things which are not, to bring to naught things that are;
that no flesh should glory in his presence.`"
And when we had been arrayed as in the king`'s apparel and placed upon the king`'s horse,
like Mordecai, we must be stripped again, and return to the gate.
When the Lord has a work for us to do, He often brings us down low,
that we may feel our own nothingness; that when He again equips for service,
we may be sensible the treasure is in earthen vessels,
and the excellency of the power is of God and not of us.

In the meeting on first-day morning,
the states of some who were often convinced of what the Lord required at their hands,
but who were putting off the work of religion, were spoken to; and in the afternoon,
those who stood as overseers, were exhorted to faithfulness in feeding the flock.
I also felt a concern for the young, visited members,
that they might not be allured from the fold by
the insidious temptations of an unwearied enemy,
and the lack of proper example in their elder Friends; but that they all might harmonize,
in strengthening each other in the right way;
whereby a succession of consistent Friends might be raised and preserved in that city.
We returned home on second-day, and I felt well satisfied I had made the visit;
though there was little to rejoice in.

Having obtained a minute of the unity of the Monthly Meeting,
I set off on the 17th of the Tenth month, 1840,
in company with my friend Samuel Hilles of Wilmington,
to visit the Quarterly Meetings of Westbury and Purchase, in the State of New York;
some of their constituent branches, and a few meetings on the way.
After accomplishing the visit, I returned home on the 3rd of Eleventh month, in peace,
and found my beloved family in usual health,
which was cause of gratitude to our Heavenly Father.

Eleventh month 11th. This morning I received the intelligence of the
decease of my much beloved and honored friend and father in the Truth,
Josiah Reeve of Upper Evesham, New Jersey.
Thus, one after another, the fathers and pillars are removed from among us,
at a time when the church seems greatly to need them.
May the blessed Head of the church, in mercy look down upon our poor Society,
and arouse many to a lively sense of the course they are pursuing,
and snatch them as brands from the burning; that during the day of grace,
they may be induced to enter into the vineyard and labor.
But oh! the benumbing effects of this world;
how it is slaying thousands who should be employed in the Lord`'s work,
and under his direction, spreading the kingdom of righteousness and truth in the earth.

On fifth-day, the 12th, I went to the late residence of my beloved friend,
and felt much sympathy with his widow,
who has also long been afflicted with bodily indisposition.
She is a mother in Israel,
furnished with a discerning spirit and soundness of judgment
that qualifies her for usefulness in the church of Christ.

Twelfth month 20th. My beloved wife having been engaged nearly four weeks in
visiting the families of Friends of Chester and Haddonfield Monthly Meetings, N. J.,
returned home this afternoon, having accomplished the work to her own relief and peace.

24th. Since my return from New York,
I have passed through seasons of great poverty and desertion.
But though closely proved in various ways, I have endeavored to keep patient,
and wait for the return of the Beloved of my soul; having underneath all,
a secret trust and belief that light would again break forth,
and a renewed qualification be granted,
to testify of his mercy and unfailing compassion towards his dependent creature, man.

This day I went to the Arch Street Meeting, where, after a time of inward waiting,
the testimony of an eminent Apostle arose;
"`That the trial of your faith being much more precious than of gold that perishes,
though it be tried with fire, might be found unto praise and honor and glory,
at the appearing of Jesus Christ;`" and in the fresh openings of the Spirit,
I was led to speak of the afflictions and provings of their faith,
which the Lord`'s children and servants had to pass through.
He only knew when, and how far to try their faith and allegiance,
by withdrawing his sensible presence;
but as they endeavored to possess their souls in patience,
keeping their eye to Him alone, when He saw it had produced the effect designed,
He would return with healing in his wings, and give these the joys of his salvation.

These could then sing of his judgments and his mercies and would know a growth,
and an establishment upon the Rock of ages, and the Foundation of many generations.
The trial of their faith works patience, patience experience, and experience hope;
that hope which makes not ashamed of the tribulations
that pertain to the Gospel of Christ.
I was also led to encourage the dear young people to keep to their exercises,
and not to cast away their confidence in their Lord;
and through obedience and submission to his baptizing power,
they would advance until they should be prepared to endure hardness,
as good soldiers of Jesus Christ.

Being their Monthly Meeting, I remained with them.
Towards the close there arose the language of encouragement to the members,
to devote themselves to the Lord`'s work, the few remaining years of their lives.
Our religious Society had been signally blessed in this city,
and within our Yearly Meeting, as well as in other places;
but we had not brought forth fruits answerable to those blessings.
Scattering and separation had taken place;
but I believed if we were willing to submit to the necessary baptisms,
and give ourselves up to his service,
that his blessings would still be poured forth upon us, ungrateful as we had been;
the waste places would be built up,
and the doctrines and testimonies given to this Society, would not only be preached,
but their nature and effect would be shown in the lives and conversation of our members;
and living witnesses to those doctrines would be raised up, from age to age,
and they should spread from the rivers to the ends of the earth.

1841, Fourth month 5th.
Attended a semi-annual examination of the scholars at West-town School.
I was engaged, in the girls`' department, to remind them,
it was not once entering into the narrow way, and making a few sacrifices, that would do;
but a steady, watchful state of mind,
to receive further manifestations of duty was needful;
that we may experience the humility and tenderness, renewed from time to time,
which we felt in the day of our first visitation;
and in which we were made willing to give up all that was required of us.
Herein alone we should experience preservation, and a growth in the Truth.
I was also drawn forth in affectionate solicitude for the boys;
that they might be favored with serious impressions,
and engaged to enter into covenant with their Heavenly Father,
that if He would give them bread to eat and raiment to put on, He should be their God,
and they would serve Him.
Though we are not often permitted to see fruit produced by the labor bestowed,
yet it is our duty to be diligent in sowing the seed which the great Seedsman furnishes,
morning or evening, not knowing which shall prosper.
He can give the increase if He pleases, and if there be none,
the faithful servants will be clear.

21st. Our Yearly Meeting was unusually large on the men`'s side this year,
and the business conducted with religious weight and much harmony.
The state of the Society is not, however, settled,
and all the members thoroughly united as branches of the true Vine;
deriving strength and wisdom from the same Divine source.
A painful sense is often attendant,
that there are some who would exercise an influence that arises from a worldly spirit,
that loves its own, and is at enmity with the cross of Christ,
and the government of his Spirit.
Such as these cry out for liberty and liberality.
They are ready to confederate with men of the world in plans of benevolence;
and could they have the predominance,
they would draw the Society away from the sure foundation,
and from a humble and steady reliance on the guidance of the Great Head;
whose right alone it is to direct the affairs of his church.
But there is also a body of exercised members, who desire to have their loins girded,
and lights burning, waiting for the coming of their Lord,
and who dare not be active in their own will and wisdom.
These are baptized into death; having the sentence of death in themselves,
not to trust in themselves, but in God who raises the dead,
and gives ability to stand for his cause.
May their number increase,
and the arms of their hands be made strong by the hands of the mighty God of Jacob.

Fifth month 12th. Accompanied by my beloved friend Henry Cope,
I set out to attend the Yearly Meeting of Virginia, held at Cedar Creek,
having minutes of the unity of our Monthly Meeting therewith.
Travelling by railroads and steamboats has now become so rapid,
that we reached Taylorsville,
about thirteen miles distant from N. Crenshaw`'s at Cedar Creek,
by three o`'clock the next day after leaving home;
where we were met by carriages and taken to his hospitable residence.
The Quarterly Meeting held on the 14th, was small; on the men`'s side,
reports were received from but one Monthly Meeting;
the remaining two being nearly extinct through the removal or decease of the members.

The Yearly Meeting of Ministers and Elders consisted of seven men and three women.
On first-day a very large company of persons came together, who, from their deportment,
manifested that they had very little acquaintance with silent meetings,
or spiritual worship; some talking; and many going in and out of the house.
After two or three Friends had spoken, and there had been a time of silence,
it appeared right for me to rise with the expressions of Christ,
"`Many shall come from the east and the west, and shall sit down with Abraham,
Isaac and Jacob, in the kingdom of heaven,
but the children of the kingdom shall be cast out.`"
From which I was led to hold forth the doctrine,
that those who were favored with various opportunities of spiritual improvement,
and neglected them, were in danger of being cast off; while others,
whose privileges were few, but who made a right use of them,
would be gathered to the innumerable company that surrounds the throne.
The necessity of witnessing the work of religion in the heart,
by which we are prepared to glorify God in the highest,
and experience peace and good will towards all men, was opened.
That where this is known, wars and fightings come to an end;
and thus the kingdom of Christ will gradually
take the possession of the gates of its enemies;
until the kingdoms of this world become the kingdoms of our Lord and his Christ.
The universality of Divine love, with many other points of Christian doctrine,
was opened; a degree of solemnity spread over the company,
and I believe impressions of a serious nature were made on some minds.

On the way to Flemming Bates`', the horses pressed so much on the side of a bank,
as to run the carriage on a stump; by which we were overturned.
I was much alarmed at the perilous situation in which my companion was placed;
he being between the front of the carriage and the corner of the fence,
lest he should be crushed; but the horses being stopped he was rescued,
with only a slight injury.
I was very thankful for the preservation of his life.
It felt awful to me, the apprehension, that I might have to return without him;
which brought over me the seriousness of setting out from home,
and being the means of taking away the valuable parent and head of a family,
who might never return to them.
Many times did I feel that I had great cause for gratitude,
that none of the company were seriously injured;
and I thought it might have been permitted to show us what poor, frail creatures we are;
and how unable to keep ourselves from danger;
and that it was needful we should keep constantly on the watch, under a humble,
reverent sense, towards the Lord, of our insignificance,
and unworthiness of all his favors; that so He might have mercy upon us,
and preserve us by his power.

The Yearly Meeting was very small; and though there are a few exercised members,
who desire the right maintenance of the testimonies of Truth;
yet it appeared to me doubtful whether it is held to the honor of the great Head,
and the real benefit of the few who compose it.
As the way opened for it, we endeavored to strengthen the hands of the exercised ones,
and to counsel and warn those, who appeared to be under little or no weight,
in relation to the right holding of such a meeting;
or of conducting themselves out of it with decorum,
and a seriousness becoming the occasion.
The meeting closed on fourth-day afternoon.
In the evening, at our lodgings, we had a large company of young persons,
mostly quite gay, invited to sit with us;
and I was drawn forth to call them to the duty of watchfulness and sobriety;
lest their adversary, the devil, who is ever walking about as a roaring lion,
seeking whom he may devour, should lead them off, by his temptations,
into a land of pits and snares, and great distress.
They were affectionately invited to come to Christ Jesus, and take his yoke upon them;
that they might know Him to strip them of their vain ornaments,
and by the baptizing and sanctifying power of his grace,
prepare them for Him to tabernacle in their
hearts and fit them for service in his church.
They seemed brought under serious impression and retired, I apprehended,
in a different frame of mind from what they would have done,
had we not been faithful with them.
Next day we rode to Taylorsville; lodged at a tavern,
and next morning took the cars for Fredericksburg; from there to the Potomac,
where we went on board the steamboat for Washington;
which city we reached about half past three o`'clock, and at half past five,
again seated ourselves in the cars for Baltimore.

On seventh-day afternoon we arrived at our homes, and I found my beloved family well,
with the exception of my oldest son, who for some time has appeared to be in a decline,
and had gone to one of my brothers at Springfield, to try the benefit of country air.
I soon made him a visit, and found him more unwell than I expected.
After remaining in the country a few weeks,
and appearing to derive no benefit from the change, but continuing to grow weaker;
he was desirous to return to the city, and was accordingly brought home.

He had lived an unblemished life;
and though his business subjected him to the company of people of the world,
of great variety of character, he was unusually circumspect in his deportment;
and has drawn from many of them, sentiments of much respect for his example.
He conducted himself with invariable respect for his parents and their judgment;
and never departed in dress from the usual simplicity observed among us.
Although he had thus lived, and was much beloved and approved by his friends;
when he saw the inevitable result of his disease;
his mind was brought under great exercise, that he might be prepared for the awful event.
Speaking of the exercises he underwent, at Springfield, he said:
"`The conflict I passed through for two days and nights, is indescribable.
It seemed as if everything wrong that I had done, from my childhood to that day,
was brought before me; and, at last, in mercy,
I received an evidence that they were all forgiven and blotted out.`"
I felt calm and peaceful, notwithstanding this comfortable assurance,
he underwent great reduction, and was often brought into close searching of heart,
lest he should be deceived.
Being thus left to struggle with the evil suggestions of Satan,
and to feel his own weakness,
he many times apprehended there remained a veil between him and his Heavenly Father,
which he said he could not rend; and, at one time, under these sensations, he said:
"`I feel like a poor, condemned criminal.`"
He, however, experienced, at times, this state of mind to be changed;
and was enabled to acknowledge the goodness and mercy of God;
and when visited by some of his young friends, he imparted suitable counsel;
particularly to those in business, against the spirit of the world;
and their being drawn away after the acquisition of wealth.
In such a situation as this, into which he was brought, he remarked,
What would wealth do for any?
It would then be found that earthly possessions were of no value whatever,
to a soul in the prospect of eternity.
He became more and more withdrawn from his outward concerns,
and seldom said much about them.

His time was chiefly spent in silent meditation; and he manifested a solidity of spirit,
and deep feeling of seriousness,
becoming the situation of one who was gradually
approaching the termination of his earthly career.
He appeared to have acquired much command over himself;
so that he endured with patience the tediousness of a lingering consumption.

At one time, he supplicated thus, in a very solemn and humble manner: "`Oh, Lord Jesus,
be with me through the valley and shadow of death!
Oh, righteous Father, wash me and make me clean in the blood of the holy Jesus!`"
After this, his mind appeared to be calm and settled; and near his close,
when it was supposed he would speak no more, he seemed to receive a full assurance,
that every obstruction was taken out of the way, and distinctly and audibly said:
"`I am now ready to go;`" and on the morning of the 5th of Seventh month, 1841,
his redeemed spirit was released from the conflicts and trials of time.
