== Chapter XII

[.chapter-synopsis]
* 1841+++.+++ Religious Visit to North Carolina Yearly Meeting

1841, Ninth month 17th.
Having for some time believed it would be my duty to pay a
religious visit to the meetings of North Carolina and Virginia Yearly Meetings,
I spread the subject before the Monthly and Quarterly Meetings,
and obtained their certificates of unity and sympathy with me,
and liberating me for the service.
It was no small trial to engage in such a visit;
requiring much time and labor to reach the meetings in prospect; but it appeared to me,
that my own peace and growth in the Truth,
were concerned in giving up faithfully to do what the
Great Head of the church allotted for my service.

Many experienced Friends expressed their gladness that
I was drawn into that part of the vineyard;
and desired my encouragement and strength; which was a comfort.
Not only the unity of the brethren, but their affectionate desires for us, are helpful.
They show they are alive to the prosperity of Truth;
and they give encouragement to the stripped and tried servant,
who has the labor to perform.
A number of the solid members of the Meeting for Sufferings,
which met on the day we set off, manifested their affectionate feeling for me,
in this way; which savored of the precious fellowship of the Gospel,
and was truly cheering.
The weather was wet and stormy; but my companion J. Hacker, and myself,
rode down to West-town; and the next day reached London-Britain.
We attended their meeting on first-day, where I felt much sympathy with the few there,
who are endeavoring to hold up the testimonies
of the Gospel in the sight of their neighbors;
many of whom have separated from the Society.
Some ability was furnished to encourage them to hold on in the right way,
that they may draw the children into a love of the Truth,
and become the salt of the neighborhood, and lights to those around them.
The necessity of regeneration,
that they may be renewed in the image which Adam lost by transgression,
was also presented to others who were invited to take the cross of Christ upon them,
and thereby know Him to be their Savior indeed.
In the afternoon, we rode over the Susquehanna to Deer Creek; and on second-day,
the 20th, proceeded to Baltimore.
Several Friends visited us in the evening, which we passed in agreeable conversation,
on several subjects connected with the cause of Truth and righteousness;
it ended peacefully, and, I trust, with some instruction to us all.

Having obtained from our friend Hugh Balderston, a draft of the route to Goose Creek,
we set out in the morning, and rode to Rockville, on the Georgetown Turnpike,
and put up at a public house.
The thought of the long distance we must ride to reach meetings in Tennessee,
is sometimes trying; but under all,
the sustaining goodness and mercy of our Heavenly Father is felt to be near;
speaking peace, when the mind is kept chaste unto Him,
and a fervent desire is maintained,
that the thoughts of the heart may be preserved in purity;
seeking to stand prepared to do his will, whenever He may call for any service.
Above all things, it is desirable to be kept in his fear,
and clothed with a fervent travail for the exaltation of Christ`'s
kingdom of holiness and truth among mankind universally.
Alas! what wickedness abounds in the earth; and in these Southern States,
the crime of slavery.
The appearance of the man and the child of color,
fills me with distress and mourning for his degradation,
and the sins of his unrighteous master.

Something requiring the attention of a smith about the carriage,
after he +++[+++a colored man] had completed it,
I asked him if he carried on the business for himself?
He replied, "`No; but for the man who gave some directions at the carriage;
he gave eight hundred dollars for me, cash; a good deal,`" he said,
"`when my life was not insured.`"
He spoke as if he was indifferent to his situation; but it seemed astonishing to me,
that the Lord`'s noble creature, man, should be held as the property of another,
and forcibly prevented from using his own strength and
ingenuity for his own benefit and profit.
I felt sad in leaving him his efforts to appear cheerful,
seemed a cover to his reflections.
A man who, by his trade, could make several dollars a day,
and yet not a cent could he call his own, or appropriate to his own use,
unless given to him by his master; all he got, he said, was food and clothing.

22nd. Passed through several small villages, and generally a poor, worn-out country;
much of it appeared to be deserted some of the houses of the former owners were in ruins;
impressing the mind of the contemplative spectator with sadness,
at the proof it furnishes of the blasting effects of slaveholding.
We ferried the Potomac, and rode through Leesburg in Virginia, to Goose Creek,
and attended the regular meeting, on fifth-day.

The company of Friends was very small, but steady in the support of the meeting.
We sympathized with them in their stripped state; and through the goodness of the Lord,
were led to administer a word of encouragement; which tendered our hearts together, and,
we trusted, had a comforting and strengthening effect upon the little band.

The next morning, before leaving the Friend`'s house where we lodged,
I felt drawn to impart counsel to the members of the family,
on the necessity of keeping close to the Captain of our salvation;
that they may live and act under his Divine guidance;
and be concerned to lead their children in the path which the
Lord casts up for the ransomed and redeemed ones to walk in.

24th. The weather wet; but we were best satisfied to set out for Hopewell;
which we reached before sundown.
On seventh-day we held no meeting, as the Friends lay much scattered,
and in the afternoon visited Lewis Neal, now in the ninety-fifth year of his age.
He told us, that three of the Friends who were banished from Philadelphia,
in the time of the revolutionary war, were billetted at his house;
spoke of the sickness and death of Jno.
Hunt and T. Gilpin and also of the residence of Israel, John and James Pemberton,
while in exile.
The trials of that day, he remarked, no one could have a full conception of,
but those who witnessed them.
It was interesting to hold converse with so aged a man,
who had been an eyewitness of facts,
relating to the trials those banished Friends underwent.

We attended Hopewell Meeting, where we sat a pretty good length of time,
before there was sufficient clearness to say anything; but at length,
through Divine kindness, the spring was a little opened;
and the importance of waiting upon the Father of lights,
from whom every good and perfect gift comes, was brought into view.
The necessity of taking up the cross, denying ourselves, and following the Lord Jesus,
was pressed upon the middle-aged and younger members;
by which alone they can know their hearts cleansed and sanctified,
and made fit temples for the Lord, by his Spirit, to dwell in.
The power of Truth rose into dominion, and many were contrited;
and I hope it terminated to the refreshment of those who are right-minded.
I was humbled under this renewed evidence of Divine condescension.
We rode, after the meeting to Aaron H. Griffith`'s,
about two miles from Winchester, and lodged.

27th. We have had clear weather three days, and having rested two,
we set out this morning up the Winchester Valley, on our route to Tennessee;
and in the afternoon, put up at a tavern,
on the bank of the north fork of the Shenandoah, thirty-eight miles from Winchester.
At the supper, I asked the landlady,
if the farmers carried on their business with white or colored laborers?
She said, with both; they were numerous here.
I expressed the opinion, that they would get along better with free laborers;
but she did not concur,
though she admitted there was a less number of slaves
in this part of Virginia than on the more eastern side.
I enquired of another person, whether the slaves, set to do a piece of work,
would do it without being overlooked?
He answered in the affirmative;
and said there were many severe masters in that neighborhood,
who would have their work done, and the slaves knew it must be done.

The landlord told us in the morning, that he did not sell ardent spirits;
he would not inebriate a man nor suffer one who was intoxicated,
to remain on his premises.
I took the opportunity to remark,
it was a satisfaction that he declined selling spirits
and I thought it would add to their comfort,
if they were to free themselves from slavery.
"`Tell us,`" said he, "`how we shall get clear of it, and we will do so.`"
I replied there was something in his own breast
which would tell him how it was to be done.
He said, he thought the slaves were better off under some persons to take care of them,
than those who were free.
To which I rejoined, there was in every one an inherent desire for freedom,
let their circumstances be what they may.
The people of this country contended with Great Britain
against what they considered an imposition,
though we were not deprived of our liberty;
and the colored people have the same feelings;
and though many of the free black people were degraded, as were also many whites,
yet some of the former possessed property, and were very respectable.
Though he kept himself cool, and refrained from any reflections;
yet I thought the observations on the subject were unpleasant to him.

Tenth month 1st. We have had fine weather, and have ridden about thirty-six miles a day,
through a very hilly country; some parts of it pretty well cultivated,
and much of it very poor; though, in general,
it is in a better condition than the eastern side of Virginia.
Several of the taverns at which we have latterly stopped, are poorly furnished;
no carpets on the floor; and in other respects,
do not indicate the progress in refinement and good management,
which may be seen in similar establishments in the free States.
Our landlord, last evening, went into some defense of the Government,
in removing the Indians to the west.
I told him the natives had as good right to their land and houses, as he had to his;
and the Government might as well turn him off his property, and take possession of it,
as to treat Indians so.
He thought there was a hand of Providence in it, as they were heathens;
and while they remained, Christianity would not spread.
I remarked, they were believers in, and worshipped the Almighty,
under the character of "`the Great Spirit;`" and some of them read the Scriptures,
and had joined some of the different Christian sects.
But why did they not send away the colored people?
the slaves; many of whom were no better than heathen; why did they keep them among them?
To this he made no answer.
I told him they had coveted the Indians`' lands;
and acted on the same principle that Ahab and Jezebel did,
when he wanted Naboth`'s vineyard; and she procured men to destroy Naboth;
and then told the king to go and take possession.
He said he did not like the principle.
I hoped he did not, nor the practice either.

The degraded state of the free blacks among slaveholders,
so far as instances of it can be found, is referred to by them,
as a palliative for the iniquity of the system; which, I believe,
requires a degree of hardness of heart, in all of them, to enable them to justify it;
and without which, they cannot suppress the convictions of Truth in their own breasts.
These convictions, I have no doubt, do often arise,
and they resort to various expedients to suppress them.
The example of other States, and latterly of the British,
in liberating the slaves within their jurisdiction, must add force to these convictions;
and whatever sophistry they resort to, in order to justify themselves,
the testimony and the practice of others,
prove that there is a way safely to liberate the slaves;
and public opinion is constantly rising in greater force against the horrible system.

This morning we stopped to view the astonishing,
stupendous Natural Bridge over Cedar Creek.
From the top of it to the water, is said to be two hundred and ten feet.
The mass of stone forming the arch, thirty feet through;
the distance from the under curve of the arch to the surface of the water below,
one hundred and eighty feet; and the chord of the arch ninety feet.
We are struck with admiration in standing under the huge superstructure,
and contemplating the vast pile of stone so compactly placed;
forming walls and abutments; and, thrown over such a space, an arch,
of the enormous weight of stone, that rests upon them.
Nor are the comparative perfectness of the arch, the regularity of the under curve,
and the evenness of the surface less wonderful;
when we reflect that it has not been effected by any force,
acting according to the ordinary laws of nature; but by some extraordinary convulsion,
of which we can have no adequate idea; but which we should suppose,
would have left the standing masses of stone,
craggy and without any such appearance of harmony and
regularity as that in which they now are.
The length of time before we hear a stone, thrown from the top,
strike the water below,--two or three seconds perhaps,--gives
striking proof of the depth of the abyss into which it falls.

The tavern keeper, with whom we last put up, enquired at the breakfast table,
whether we were Quakers?
and whether they always had preaching in their meetings?
We replied that we were Quakers, or Friends; but we do not appoint any to preach.
We believe it right to meet together in silence to wait upon our Almighty Creator,
to receive ability to worship Him in spirit and in truth; and that the Lord Jesus Christ,
who is the Head of his church, gives the gift for the Gospel ministry to whom He pleases;
and such whom He sets apart for that service, preach as they are moved to it by Him;
but we often hold our meetings in silence.
I also told him that we took no pay for preaching;
that we followed some business for a livelihood; maintained ourselves,
and when traveling, paid our own expenses.
When a minister had not the means to do this,
the Society took care that he should not lack, but they paid him no salary.
He was very ignorant of Friends, and seemed rather surprised at this.
We gave him some books to inform him of our principles, for which he thanked us.
He also enquired whether we approved of war?
I told him that we do not.
He supposed, as we do not fight, we paid the fine.
I said, we neither engage in war ourselves, nor can we pay for a substitute;
but when we are called on for a fine, we suffer our goods to be taken;
and some are put in jail.
This also puzzled him; as we knew the fine must be paid,
he saw no reason why we should not do it.
I observed there was the difference between voluntarily paying,
and passively suffering the penalty prescribed by law.

Tenth month 2nd. We have now been six days on the road,
from Winchester to Christiansburg, about two hundred and nineteen miles.
The weather mostly dry, until this afternoon, and much of the road very good.
Here we felt ourselves disappointed,
in being thrown into the company of a number of boarders,
who seemed hardly able to keep their eyes off of us;
perhaps having never before seen a person in our garb, or been in their society,
so as to hold conversation with them.
We have found the people of this valley,
generally very ignorant of Friends and their principles.

5th. In the last three days we have travelled but ninety-four miles,
owing to the stony and muddy condition of the road,
which made traveling very fatiguing to us, and wearing to the horses.
During this period,
I have had several conversations with persons of apparent respectability,
on the enslaved condition of the blacks.
All admit that it is a dreadful system, and profess a willingness to liberate them,
could they see the way to do it with safety;
but I do not believe there is much sincerity in these professions.
As long as they can keep them as servants, to labor for them,
so that the master and his children may live in idleness and luxury, and pride,
very few will look for any way to free them.
They love ease too much.

6th. After a very rough, fatiguing ride, we stopped at a low log building,
and enquired of the mistress of the house, if we could have accommodation for the night?
She made some difficulty, but eventually consented to take us in.
Though the appearance of things was not promising, they were clean,
and we made out pretty well.
Not being able to get any information respecting Friends at Limestone,
we hired a man to pilot us over to Mark Reeve`'s, near Elizabethtown;
where we were received and entertained with hospitality,
and one of his sons went with us the following morning to Henry Marsh`'s;
and on the 9th we had a meeting at Limestone.
Proceeded in the afternoon to Rheatown; lodged at John Marshall`'s,
and attended the meeting, called New Hope, on first-day.
Some notice being spread, the house was pretty well filled by Friends and others;
many of whom appearing to be strangers to silent waiting upon the Lord,
in order to perform Divine worship, soon became restless, and went out.
I found it necessary to keep inward, and not give way to the spirit of restlessness,
which was craving words;
and the Lord brought my mind into a state of simple reliance upon Him.
After a time, the exhortation of Christ to his disciples, when trouble came upon them,
was brought before me;
"`In your patience possess your souls,`" and I was
led to show the importance of learning to stand still;
especially when met for the solemn purpose of Divine worship;
that we may know Christ to manifest Himself to be in the midst; to teach the humble,
attentive soul, and to enable it to worship the Father in spirit and in truth.
Some of the fundamental doctrines of the Gospel were opened;
the necessity of being broken off from the wild olive tree,
and grafted into the true Vine, was pressed upon the people,
and a tender invitation held out to those who had spent
their substance in an improper way of living,
to yield to the convictions of Divine Grace,
that they might be brought to the Father`'s house,
where there is bread enough and to spare.
The meeting ended with thanksgiving and praise for the Lord`'s goodness, extended to us,
and supplication for his continued preservation.

From this place we were taken by Aaron Hammer, down to Newberry, in Blount County;
where we held a meeting on sixth-day, the 15th, which was a favored time;
the states of individuals being spoken to,
and the necessity of obedience to the righteous law written in the heart enforced;
and the young were encouraged to come up in their places, in the Truth.
An elder, after meeting, expressed his satisfaction,
and that he considered it a favored time.
We came away with peace; and rode about twelve miles to a house of private entertainment,
where we had poor accommodations;
neither of the windows in our lodging-room having any sash, and one of them no shutter.

Next day we passed through Knoxville; breakfasted there, and reached William H. Morgan`'s,
at Lost Creek, in the afternoon.

17th. Attended Lost Creek Meeting.
Being first-day, a large concourse of people assembled,
but few of whom seemed acquainted with having their minds stayed upon the Lord.
Accustomed to associate Divine worship with preaching and vocal prayer,
the time of silence seemed long to some, and yet they behaved with propriety generally.
The way at last appeared to open,
to speak upon the effect of vital religion to bring the
mind of man off from dependence upon man,
who cannot save his brother, nor give a ransom for him; and to call them to Christ,
the great mediator and minister of the New Covenant; that they might learn of Him.
The doctrine of the universality of his appearance in the heart;
of the angel which John saw flying through the midst of heaven,
having the everlasting gospel to preach to them that dwell on the earth, of every nation,
kindred, tongue and people, under heaven; of Christ,
as the administrator of the baptism of the Holy Ghost and fire,
by which He burns up the chaff; He who sits as a refiner with fire,
and a fuller with soap,
to purify and prepare the sons of Levi to offer offerings in righteousness;
our propitiation for sin, and Advocate with the Father, were a little opened;
and those who loved Him with sincerity, were encouraged to dedication.
The Truth at times, seemed, in measure, to prevail over the meeting,
and the people were solemnized; but after it was over, I felt tried, lest the humbling,
tendering power of it, had not reached the heart, as much as is desirable;
which depressed my spirits,
and produced fear that I had not kept as close to my guide as I ought;
but I could not discover where I had missed my way.

In the afternoon, we walked from William Morgan, Sr.`'s, to his nephew`'s;
and had a religious opportunity with his family.
In the evening, we had also a tendering time at the house of the above aged Friend;
several young persons being present; which was a comfortable close of this day`'s labor.
A little humiliation is both necessary and beneficial;
and our Divine Master knows when and how to administer it.
May all his servants kiss the rod, and cleave to Him when He appoints it.
I believe He sees fit to withdraw the evidence of his approbation,
and also the capacity to judge of our labors,
at times when we have not willfully done wrong,
that we may be kept in the nothingness of self.

In the course of the visit in Lost Creek Quarterly Meeting,
we found Friends mostly in low circumstances, and living in a plain, rough manner;
some of their houses having few lights of glass in them;
their children partaking of little opportunity for education,
either at home or at school.
In many instances, this is occasioned by the lack of means,
and their time being mostly occupied at their work, to get bread and clothing.
I felt sympathy with them,
and could but contrast their condition with that of
many affluent members in other parts of the Society,
whose children are brought up in delicacy and luxury,
and know nothing of the difficulties and privations to which
the children of Friends in these parts are subjected.
If a large part of the surplus wealth of rich
Friends was applied to aid their fellow members,
in educating their offspring, and in spreading the writings of Friends;
much good would be done.
It would tend to keep the hearts of the rich open to the trials of their fellow members,
and to the great cause of the Redeemer`'s kingdom;
which would be a blessing to themselves, by keeping out a covetous,
parsimonious attachment to this world`'s treasures;
while it would confer an important benefit upon others.

We visited a school which was taught by a Friend, a few of the scholars being members.
It was in an open, log building, without a window; what light they had,
came in through the openings between the timbers, and at the door;
there was no floor but the earth; and no fire-place or stove.
A little fire in the middle of the room, was the only means of warming it;
the smoke passing out of any avenue it found.
The children, though with cheerful countenances, were clothed with scanty covering,
nearly all without shoes or stockings.
Their situation appeared unfavorable for acquiring the
necessary portion of useful learning,
not only from these circumstances, but from the incompetency of the teacher,
and the general habits and sentiments of their parents and caretakers.
When we reflect upon the importance of a right education,
and the little effort made by many to guard their children,
by watching over and restraining, and instructing them in the great duties of life;
cultivating their minds, and leading them into habits of cleanliness and industry,
and warning them of the dangers of improper associations,
and of every description of immoral taint; above all, by precept and example,
inculcating the indispensable obligations of living in the fear of Almighty God,
and working out their salvation, through the aid of his Spirit;
we cannot but feel for children who partake of very few of these advantages;
and desire that their parents were more aroused to a
lively sense of the obligation which rests on them,
towards their tender offspring.
Many have difficulties in providing for their families;
but were they more devoted to the love and service of their Heavenly Father,
way would be made, either by his blessing, on their efforts,
or through the help of the Society, to educate them in schools of suitable character,
and to draw them into a love of our religious principles and testimonies.
A blessing, I believe,
has rested upon the honest concern and labor of Friends in many parts of our Society,
in watching over and educating the youth; and in many instances, I trust,
it will prepare the ground for the good seed which the Son of Man sows,
and which will bring forth abundant fruit, under his blessing;
and thus be instrumental in preserving many among us,
who will be qualified to maintain the doctrines and testimonies of the Gospel,
to the Lord`'s praise and the comfort and enlargement of the Church.

20th. We had intended going on from Rheatown, to cross the mountains into North Carolina;
but a Friend offering to go as guide, provided we waited until the following morning,
we accordingly stayed the Preparative Meeting at New Hope;
and being impressed with a belief that Friends are
suffering great loss in letting the discipline fall,
by passing over, in a very superficial manner, marriages accomplished in violation of it,
the way opened to set forth the importance of the church government,
established in the wisdom and authority of Christ, among us.
It is only as the members individually live under the
subjecting power of the cross of Christ,
that they are prepared to support the ark of the testimonies,
and administer the discipline as it ought to be;
in the same power and wisdom in which it was instituted.
"`The righteous holds on his way,
and he that has clean hands shall be stronger and stronger.`"
These are not drawn aside from a firm and straightforward support of the cause of Truth,
by a false tenderness towards others, whose eyes have become blinded;
and in the faithful discharge of their religious duty, they grow in spiritual strength,
and are a blessing to the church.
Where a body of such members is preserved,
and the discipline is rightly maintained by them,
the Society is kept in a healthy and vigorous state.
The young members growing up under their example,
will receive right views of church government;
the motions and openings of Divine Grace in their minds,
will be confirmed and enforced by the faithfulness of such upright men and women;
and thus successors are prepared to receive gifts from the great Head of the church,
to be occupied in his service, in their day.
What a comfort and strength these are to one another, and to their elders in the Truth.
When ministers who keep to their gifts, come among them,
they partake of the help of their spirits, and the "`spring shut up "`is often opened,
to the mutual refreshment of the visitors and the visited.
How different from those meetings, where a worldly spirit has overspread,
and darkened and benumbed the professors of the christian religion.

But where the rules of Discipline are let fall,
or administered by those who have lost ground,
through disobedience to the convictions of Divine light,
and whose hands are thereby weakened, desolation spreads; wrong things prevail;
and though something of the form may be left,
the power of Godliness is lost among such a people.
The young members, who are at times favored with the visitations of the love of God,
are very likely to be turned aside by the evil example of older ones,
who seem to be the leaders; and thus such meetings continue to dwindle,
until they can no longer be held with reputation.
The salt has lost its savor, and men of the world trample it under foot,
because they can perceive such are no Quakers in reality.
In this way many have become an ill-savor,
and caused the way of Truth to be evilly spoken of, to the grief of the sincere-hearted,
and the obstruction of the spread of the kingdom of Christ, through us as a people.

Tenth month 21st. We rode to M. Reeves, near Elizabethtown; and the next morning,
with one of his sons to go before us through some difficult fords; we set off,
the weather cloudy, and rode up Doe River;
crossing it six times in about that number of miles.
We had heard much of the difficulties some Friends had encountered,
which produced gloomy anticipations of the journey through these mountains;
but we were mercifully preserved from any apparent dangers, or meeting with any accident.
It snowed or hailed the greater part of the day; the atmosphere was chilling,
and we were quite ready to stop at the house of a farmer, in this rough country,
after a ride of twenty-nine miles, where we were hospitably entertained.
Our course, the next day, lay through deep ravines;
along streams of water which we forded many times; and over the Stone Mountain,
whose lofty peaks were whitened with snow.
When we reached the summit, the snow lay about half an inch deep,
and the air was quite cold; so that the snow did not disappear,
though the sun shone quite clearly nearly all the day.
This was laborious traveling, as we walked up most of the ascents;
and there was little to cheer us,
but the belief of being in the way of our religious duty;
which makes hard things easy and bitter things sweet.

First-day the 24th, brought us to Wilkesboro, about eleven miles from the Blue Ridge,
the last or most eastern of these ranges of mountains,
and said to be the highest ground in the United States.
When we reached the highest point, over which this road passes,
we stopped to take a survey of the magnificent scene spread before us.
Standing on the edge of a vast precipice,
we had at our feet mountains piled on one another, and deep ravines intervening;
to whose bottoms the eye could not penetrate.
It was the grandest sight of the kind I ever saw.

The road was generally good, and the rise as well as descent being gradual,
made the traveling much more pleasant than the two preceding days.
Some spots are cultivated, affording good grass and corn; but here, as in other parts,
we see decayed buildings and deserted clearings, and where the inhabitants still remain,
the land affords but a scanty subsistence beyond the supply of food;
it being impracticable to obtain many of the comforts,
and few or none of the refinements or luxuries of civilized christian life.

25th. We got to Anderson Johnson`'s at Hunting Creek;
whose wife is a daughter of David Brooks, a minister, with whom my uncle,
Thomas Scattergood, was traveling as companion, when he first appeared in the ministry.
To find ourselves once more among those of the same religious profession,
imparted pleasant sensations.
This Friend, we were informed, was prosecuted for aiding a slave to make his escape;
and though the charge was entirely unfounded, yet from false evidence,
he was amerced to the value of the runaway, and costs and damages,
amounting to about twelve hundred dollars.
This iniquitous decision seemed likely to ruin him;
he was compelled to sell his horses and cattle, and part of his house furniture,
and with much difficulty made up the sum,
and prevented his prosecutors from selling his farm;
and thereby throwing him and his dependent family houseless upon the world.
Now, more than seventy years old, he is unable to labor hard,
and from the great loss and the difficulty in selling produce,
he has to endure privations which, at their time of life,
he and his afflicted wife ought not to be subjected to.

On the 26th, had an appointed meeting at Hunting Creek,
and on the 27th and 28th attended those of Forbush and Deep Creek.
The low state of the life of true religion among many,
was cause of mournful feelings on their account.
To see the dwindling condition of many,
and the effect which their example has upon the younger members,
leading them into an association with light and frivolous company,
produced apprehensions, that unless there is a turning about,
and giving themselves up to the restraining power of the cross,
the Society must run out in these parts.
Divine goodness was mercifully near, qualifying to labor for their help,
especially in the last meeting.
I never, perhaps,
felt more destitute of a lively feeling of the presence of the Helper of Israel,
and very much gave up expectation of saying anything;
but after sitting long under the burden of a worldly spirit,
there seemed a little pointing to express my fearfulness,
of the danger of that spirit overspreading the professors under our name among them;
and reciting the testimony of the Apostle that, "`To be carnally minded is death,
but to be spiritually minded is life and peace;`" the truth gradually rose,
and I have rarely known more strength to labor with such,
in the spirit and fervor of the Gospel,
to turn from their ways and to come under the
heart-changing power of the Grace of Christ Jesus,
than in this meeting.
Some were softened, and prayer was offered that He, who knows our condition,
would baptize and re-baptize, until the heart was prepared for Him to dwell in;
yet in the midst of judgment He was interceded with to remember mercy,
lest the spirit which He had made should fail before Him.
A valuable minister said at the close of the meeting, it was deep wading;
and he thought if he had been faithful,
he should have said something to open the way for me.
As it had ended well, it appeared to me best as it was;
having nothing to depend upon but the Lord alone.
I came away humbly thankful for this renewed evidence that I was not forsaken,
and went with Wm. Dobbins, a sensible, devoted Friend, to his home.

29th. Accompanied by him, we rode to Chestnut Creek, on the Blue Ridge;
put up at William Davis`', and held an appointed meeting there next afternoon.
Here, the obligation to forgive those who trespass against us,
and the impossibility that revenge can dwell in the
heart of a true disciple and follower of Christ,
were brought before me;
and though it seemed singular to open such views
in a little company of Friends and a few others,
yet I could not see any other way, and accordingly gave up to it.
There were other gospel truths declared and enforced; and after the opportunity,
I found a man who attracted my attention, when delivering some close things,
was a Mormon preacher;
which sect of visionary people are represented as arming themselves,
in an extensive settlement in the western country,
and holding out the idea that the sword is to be used in making way for their impostures.

31st. Rode down this steep, high mountain, about the middle of the day;
stopped by a stream of water,
and with some provisions which we had brought for ourselves and horses,
refreshed ourselves, and then pursued our way back to the house of our friend.
Here we had an opportunity with his children, and the partners of the married ones;
in which the way opened to warn some against a carnal, worldly spirit,
and to encourage all to yield their hearts to the convicting power of Divine grace;
that they might become useful members of religious society.

Eleventh month 1st. Reached Salem in the evening, a settlement of the Moravians.
The title to the property, comprising a large tract of many hundred acres, is vested,
we were informed, in their bishop.
The land is leased out, so that it cannot go into the hands of others,
and they suffer none of any other profession to settle among them.
The person who keeps the large and commodious hotel where we stayed, we were told,
is the only exception.

2nd. Stopped at J. S.`'s, and dined,
and made arrangements for meetings at Dover and Hopewell.
On the road we called at a smith`'s shop to get a burr screwed up, and stepping out,
I trod on a round stick,
turned my right foot under me so as to wrench it out of the socket.
Though soon replaced, it gave me great pain, and prevented me from walking about,
unless with much difficulty.

We came on after bathing it, and put up at the boarding-school,
with our kind and much valued friends Dougan and Asenath Clark.
Next day attended New Garden Meeting,
where I felt engaged to encourage the young people to
receive the Truth in its visitations to their souls;
by which they would be preserved from the temptations that abound in the world,
and lay the foundation for usefulness in the church.
Dougan Clark accompanied us to Hopewell, to an appointed meeting;
where the way opened to press the necessity of
rightly considering the dispensation of sickness,
with which that neighborhood has been visited; that they might improve by it.
The righteous were removed from the evil to come, and those who are still spared,
are loudly called on to consider their latter end,
and diligently improve the remnant of their days;
so that when the summons is sounded in their ears, "`Steward,
give an account of your stewardship,`" they may be ready to render it with joy.
It was a serious and impressive opportunity,
and closed with supplication to the Father of mercies,
that those afflictions might be sanctified to some.
Returned to the school with feelings of peace.

4th. Went out to the meeting of Hopewell;
in which I was distressed with an outside show of religion,
where the power of godliness was lacking; and though it was hard to get at anything,
and a trial to deliver what at last arose,
yet I saw no other way than plainly to open what appeared to me the state of some.
I endeavored to keep on the clothing of charity, and to speak with fear;
and Truth gradually arose, so that at last I was enabled to labor with fervency,
to draw such into a close examination of themselves;
that they might experience the life and power of Christ to reign in them.
The language of encouragement flowed to the states of others, of a different character,
who had many trials to contend with; but who,
if they did as the prophet directed the poor widow, to bake a cake for him first,
the meal in the barrel should not waste, nor the oil in the cruse fail.
We dined at O. P.`'s,
who piloted us to Deep River where we attended the Meeting for Sufferings,
and the Meeting of Ministers and Elders.

My strained ankle gave me much uneasiness, at times,
prevented me from walking to the meetinghouse, about a quarter of a mile distant,
and sometimes raised apprehensions, whether I should ever be able to walk as I had done.
It was a trial to be thus disabled;
not knowing whether it might not prevent me from
steadily prosecuting the concern I was engaged in;
yet I thought it might have been permitted,
to teach me more caution and deliberation in my movements.
In the full possession of the powers of body and mind,
when we are also favored with the openings of the Spirit of Truth,
and qualified to minister to the needs of the people, self may get up a little;
and the creature, unless plunged down into poverty and suffering,
may feel strong in the cause and work of the Lord.
He has many ways to humble man, and purge away pride; and pain of body,
frequently reminding him of his crippled and disabled condition,
may contribute to keep him lowly, and lead him to depend more steadily on Him,
who can heal diseases of body and mind.

On first-day, a large concourse of Friends and others assembled at New Garden,
and after a time of silent waiting, a Friend having addressed the company,
I apprehended it was my place to advert to the conversation, which our Lord gives,
as having taken place between the rich man and Abraham;
when he solicited him to send one from the dead to his five brethren,
that they might not come into the place of torment; and Abraham finally replied to him,
"`If they hear not Moses and the prophets, neither will they be persuaded,
though one rose from the dead.`"
From which it is evident,
if man will not embrace the means already appointed for his salvation,
no other will be granted;
and that while he refuses to comply with the terms of acceptance,
he would be likely to reject a miraculous visitation, sent for their confirmation.
The grace of God appearing in the hearts of all men, was held up as the immediate means;
and denying self, taking up the cross daily and following Christ, the terms laid down,
upon which alone we can hope to partake of that salvation,
which He has purchased for all those who obey Him.
Christ`'s incarnation, sufferings, death, resurrection, ascension and glorification,
wherein He is our propitiation for sin, and our intercessor with the Father,
and his inward and spiritual appearance,
knocking at the door of the heart for an entrance;
his office as the great Baptizer of his people;
sitting as a refiner with fire and a fuller with soap,
in which He administers the one saving baptism with the Holy Ghost and fire,
and prepares the heart as a temple for Him by his Spirit to dwell in,
thus setting up his kingdom there, and ruling as Lord, Judge, Lawgiver and King,
were treated on and supported by Scripture testimony.
The Truth rose into a good degree of dominion, and our ancient friend Nathan Hunt,
expressed his satisfaction, saying, "`They were the doctrines he held and believed,
and he was opposed to all innovation upon them.`"

Second-day the 8th, commenced the Yearly Meeting for Discipline,
which continued its sittings until the 12th inclusive.
The business was conducted with much harmony throughout,
and after hearing the reports from the respective Quarterly Meetings,
an epistle of counsel was directed to be prepared on the different points of defection,
referred to in the answers to the Queries.
The subject of the guarded and religious education of the youth was brought into view,
by reading the report of the Boarding School Committee;
which furnished an opportunity to press upon Friends,
a more deep and thorough attention to the right education of their children.
The money which some parents might be laying up
for them in the latter part of their lives,
would never be of as much value to them,
as when expended in giving them proper literary instruction,
at a period of life when they were most capable of receiving it.
If this period is suffered to pass, they may grow up in ignorance,
and never be of that service in society which they ought to be.

A hope was entertained that the Boarding School would continue to be supported,
and its benefits be extended among the youth of this Yearly Meeting.
Making our home at the schoolhouse,
gave us an opportunity of mingling with the committees;
and being invited to sit with one appointed to consider the expediency of
continuing the liberty to children not members to enter the school,
all the strangers, with one voice, gave their judgment against it;
both because it was not the original design,
and would tend to expose our youth to the principles of others, but in our opinion,
would diminish eventually the number of scholars, and consequently,
destroy the institution, instead of contributing to its support.
The committee adopted this sentiment, and it received the sanction of the Yearly Meeting.
Many solid, young and middle-aged men attended the Yearly Meeting,
who appeared to love the testimonies of Truth,
and were devoted to the services of the Society.

On seventh-day morning I parted, in much affection,
with my kind and esteemed friends D. and A. Clark, and went to Deep River;
where we held a meeting with the members and others
which proved a hard and laborious opportunity.
After dinner, we rode to our friend John Carter`'s where we were comfortably quartered.

On first-day, 14th, we were at Springfield,
where a considerable number of Friends and others convened;
some of whom appear to be a seeking people,
and not knowing where to find what they longed for, are wandering from place to place,
and from one preacher to another.
These were recommended to the gift of Grace in their own hearts;
by receiving which they would come to have their eyes opened to see their conditions,
and true faith be given them to believe in Christ their
Savior who would feed them with the bread of life,
and open in them the spring of living water;
by which their souls would be refreshed and nourished up unto everlasting life.
Christ was preached as the Author of this true faith,
as the Rock on which the church is built; as the Captain of salvation,
who only can arm his soldiers for the spiritual warfare;
and who gives them victory over their soul`'s enemies.
No man can come to the Father, but by Him; and it is only as He is revealed in the heart,
by the same spirit which revealed Him to Peter,
that any can have true and saving faith in Him;
by which they lay hold of the offers of his love and mercy,
and through the obedience of which, they obtain victory over the world,
the flesh and the devil; and persevering to the end, inherit the promises,
and are made partakers of that salvation,
which He purchased for all those who receive and obey Him.
It was a season of Divine regard; wherein I was greatly favored with utterance,
and the presentation of many passages of Scripture,
to show the nature of the Gospel dispensation, and to confirm the principles of Friends.
It was cause of humble gratitude to our Holy Helper,
that He was pleased to open the treasury of things, new and old,
and qualify to exalt his great name,
and call upon the people to come and enlist under the banner of the Prince of peace.

On second-day, J. P. piloted us to Piney Woods, about eight miles; a very reduced meeting.
A fatal disease had prevailed there for several months,
removing about one hundred out of five hundred persons, to their everlasting reward.
It was thought some good effect had been produced upon
a rough and rather dissipated people,
by this awful visitation; but from the feelings which came over me in the meeting,
and the description of doctrine I had to preach, it seemed to me,
some still remained in a very crude state,
with little regard for the restrictions of true religion.

We dined at the house of a sick Friend, and before going away,
I was led to draw him into a consideration of the uncertainty of all earthly things,
and the importance of having the day`'s work done in the daytime.
For when the pale messenger is sent to our habitation,
there can be no refusal of the summons; go we must, prepared or unprepared.
We put up at J. P.`'s, and in the morning had a religious opportunity with his family,
encouraging the parents and children more faithfully to yield themselves to the Lord,
and to the support of his cause.

Our friend John Carter went with us to Kennet,
where we had another trying meeting with a few members;
and yet some ability was felt to labor with them, and to intercede that their last days,
through greater dedication to Christ, might become their best days.
A Friend of this meeting offering to pilot us,
we took an affectionate farewell of our beloved friend John Carter,
and went on to the house of a Friend, whom we found sick in bed.
This put us to a stand whether we might not be in danger of taking this fever,
by lodging where it prevailed; and we accordingly told his wife,
that as we wished to go through the Yearly Meeting,
we felt cautious of exposing ourselves to the liability of sickness;
so far as we could guard against it; and perhaps we had better go further.
She said we could have a room,
separate from all other parts of the house where we could lodge and remain, if we chose.
Her offer was made with such hearty good will and
desire to keep us that we made no further hesitation.
A fire was soon kindled on the hearth in the chamber, and myself and companion,
after having spent a little time with the invalid, retired to our comfortable apartment,
where we ruminated on the singular transitions travelers like ourselves are subjected to,
and the unfeigned kindness displayed by those we visit; and often by none more heartily,
than those whose means are limited, and their accommodations of the simpler kind.
Before setting out to meeting on the following morning,
I did not feel easy without taking an opportunity with the father of the family,
in the presence of his wife; in which I expressed the belief,
that when disease assailed us, the Holy Spirit at times,
made use of it as a means to show us our frailty,
and the great uncertainty of all earthly possessions and enjoyments;
that the gracious design of our Heavenly Father, in thus opening, to our view, our state,
and the instability of all things here below,
was to draw us from all inordinate pursuit and attachment to them;
to redeem us from them, and set our affections on things that are above.
When the message was delivered to Hezekiah, "`Set your house in order,
for you shall die and not live,`" he turned his face to the wall and prayed;
and fifteen years were added to his days.
But if it should be the Lord`'s will to add fifteen days, or months, or years,
it was of great moment that the present dispensation should be rightly improved;
for we know not that such another offer of Divine love and help will be made.

The meeting was a reduced one, and after a season of silent waiting,
the language was brought before me, "`Be watchful,
and strengthen the things which remain, that are ready to die;
for I have not found your works perfect before God.`"
I felt tenderly for the stripped company, believing they had given way to discouragement,
on account of the few who remained to bear the burden;
and for lack of steadily looking to the unfailing Source of all strength,
they had lost ground; the enemy had prevailed over them;
and their works were not perfect before God.
Though it is our duty to deliver plainly what the Master gives for the people,
yet I felt desirous not to hurt the oil or the wine; but, as ability was given,
to lay judgment to the line where it belonged, and to strengthen the things that remain,
which might appear to be ready to die;
and to encourage some to put their trust in the Lord Jehovah,
in whom there remains everlasting strength.
Strength that will last through all time, and through all trials, as we lean upon it,
and lay hold of it.

Our hostess, who sat at the head of the gallery,
looked as if her heart had been tenderly touched,
and took leave of me very affectionately.
A Friend afterwards told me, she was glad we had put up at their house,
for she had been in quite a depressed and discouraged state of mind.
Thus it appears that the hand of Divine Providence, at times,
turns his children into places for the help of others;
for had our guide told us that sickness was there, I doubt whether we should have gone.

We rode from the meetinghouse to our friends J. and A. S.`'s;
where we found a pleasant resting-place.
Attended their meeting, Centre,
where I was led to speak of the value and effect of inward,
united exercise of spirit before the Lord,
that the life and power of Truth might be experienced to arise,
and circulate from member to member.
The church was compared to a body having members; and as each performed its function,
it ministered to the benefit of others,
and the body was thereby kept in a healthy condition.
So it was in the mystical body and church of Christ;
where every one maintains its place and performs its duty, strength would be preserved,
and the circulation of Divine life would prevail from one to another.
But where many were indifferent and negligent, this circulation was impeded,
and the living members are burdened.
Such negligent ones become stumbling-blocks, and choke up the wells of water;
and this makes hard work for the few.
Where one member suffers, the others suffer with it; and where one is honored,
the rest rejoice with it.
The necessity of making clean the inside of the cup and platter;
for the Lord looks not on the countenance, nor the height of the stature,
but at the heart, was enforced.

As the subject opened, the possibility and the obligation to become freed from sin,
in this life, and the practice of some professed ministers of Christ,
pleading for sin during life, being an evidence they are not his ministers,
were brought into view.
As Satan transforms himself into an angel of light,
it is no marvel if his ministers should transform
themselves into the appearance of Christ`'s ministers;
but no fountain can at the same time send forth sweet water and bitter.
"`A good man out of the good treasure of the heart, brings forth good things;
and an evil man out of the evil treasure, brings forth evil things.`"
A tree is known by its fruit; when the fruit is bad, we pronounce the tree bad.
Christ came to destroy the works of the devil.

He did not suffer, that man might sin with impunity;
but gave Himself for us that He might redeem us from all iniquity,
and purify unto Himself a peculiar people, zealous of good works--not evil works.
"`If any man will come after me, let him deny himself, take up his cross, and follow me.`"
We cannot follow Him and follow Satan at the same time.
It was very unexpected to me to be thus drawn forth
upon the necessity of being cleansed from all impurity;
that we may partake of the fullness of the blessing of the gospel of Christ;
but it is probable there was a cause.

We dined with an afflicted Friend and his daughter,
with whom we had a little opportunity to manifest our sympathy,
and desire that their trials may be blessed to them.
Returned to J. Stanley`'s; and next morning,
after acknowledging the refreshment it had afforded us,
in being so kindly cared for under their roof,
we set off in the rain for Providence Meeting Here we had a small company;
nearly all plain people; and for a long time I felt unable to discover what they were.
The language presented, "`Who is blind but my servant;
or deaf as my messenger that I sent?`"
but this did not appear to be designed for them.
Then it revived, "`I will bring the blind by a way they know not;
I will lead them in paths which they have not known;
I will make darkness light before them, and crooked things straight,`" etc.,
and I found it necessary to wait patiently to see what the Lord would do.
After a time, the condition of the Laodicean church came before me,
as being descriptive of this people; and with fear and caution,
I believed it right to stand up and bring into view the
language of the Spirit to that ancient church.
Many things of a close nature were delivered,
under feelings of sincere desire for their help;
and though there seemed few who had not fallen into great lukewarmness,
yet the spirit of prayer was granted, to intercede for their revival.

On the 23rd, we had a meeting at New Salem,
in which the call and qualification of a gospel minister were treated on.
It was declared that no man could take this honor to himself, unless he is called of God;
which call is by the revelation of Christ in the soul;
through obedience to whom a preparation is experienced
for the reception of a gift in the ministry.
This is freely given by the Head of the church Himself, and is to be freely exercised,
under his putting forth, without price or bargaining.
The importance of professing Christians coming to wait upon Him, and not upon man,
that they may receive the blessings and privileges provided for them in the gospel,
was held up and enforced.
In the afternoon, we rode to Marlborough.

We attended the meeting at Marlborough, being first-day;
in which the state of things felt to be low.
It appeared proper to sound an alarm among them,
lest they become swallowed up by the world,
and lost in a state of indifference to the work of their own salvation,
and the support of the cause of Christ.
The right education of their children;
which is often neglected by parents becoming engrossed with schemes of business,
was plainly spoken to, and parents solemnly called upon,
to give more close and serious attention to the
cultivation of the minds of their children,
the proper care of their persons, and to subjugating their wills and passions,
at an early period of life.
They were urged not to withhold from them a suitable share of school instruction;
so that they might not be sunk in ignorance, and feel themselves lessened by it.
The happiness which resulted to parents and children,
where they were joined in walking together in the right way of the Lord;
promoting each other`'s best welfare; far outweighs any pecuniary advantages,
arising from entire devotion to the pursuit of business.
The toil and watchful care of such pious parents,
would generally be amply repaid in old age, by the fruits of it in their offspring.

Then would these, under the influence of the power of religion,
cherish and console their valued and declining parents; whose joy it would be,
to see their sons and daughters established in the Truth, and as upright pillars,
supporting the ark of its testimonies.

In the afternoon we set off for Back Creek,
and in the evening reached the residence of our friend Phineas Nixon,
where we were kindly and comfortably entertained.
The weather being wet in the morning, occasioned the meeting to be smaller,
particularly on the women`'s side; and though I was kept a considerable time empty,
and shut up from any opening, I believed it right to keep still,
and refrain from attempting to stir up or awake Him, who has the key of David,
and the right to hide his face as long as He pleases.
This state of mind was preparatory to unfolding the necessity of abiding in Christ,
and keeping the word of his patience; that nothing man could do,
in his time and strength, would be any better than filthy rags; but those who waited for,
and relied upon the renewed manifestations of Holy Help, whatever their gifts,
would be qualified to bring forth fruit, to the praise of the Great Husbandman,
and the edification of his church and people.
It was a time of strengthening the hands of the faithful,
and inviting the young members to accept the offers of Heavenly love and mercy,
extended to their souls;
and to enlist under the banner of the Captain of their salvation.
The feelings of my mind were serene and peaceful;
yet after reaching the comfortable residence of Samuel Hill, I felt low and weary,
and did not sleep well through the night.
There seemed little from without, to which I could resort for comfort;
and after taking a solitary walk, I thought it was designed to keep me in a humble,
dependent state; and that such dispensations are a mercy,
and indispensable for us to pass through.
Went to meeting poor, and sat there empty,
yet looking to and striving to wait upon the Master.

Two-thirds of the company were not of our Society; to whom it appeared to be my place,
to open a little, the nature of the worship instituted by Christ under the gospel;
which is not limited to time nor place, but is in spirit and in truth;
as declared by Him to the Samaritan woman at Jacob`'s well.

We rode to Ashborough, and put up at a tavern kept by a Methodist;
who informed us that their discipline does not admit of buying or selling slaves;
yet does not prohibit the members from holding them.
I gave him some account of the progress made among
Friends in clearing the Society of slaveholding,
and expressed my wish that they could adopt the same course, and come to the same result.
He remarked it would suit him very well; he did not hold any,
but hired them as he needed help; which amounts nearly to the same thing.
A person, not of us, in company with his wife, inclining to attend the meeting,
piloted us to Bethel, where we found a company, mostly of other professors,
sitting around the house, waiting our arrival.
As we observed in many places, they did not take their seats until the stranger,
or the chief members, went into the house.
The principal service was relating to the nature of the gospel dispensation;
particularly enforcing as a fundamental and practical truth,
the necessity of being made free from sin in this life,
that we may partake of that salvation which comes by Jesus Christ.
The people were quiet and serious.
