== Chapter XIII

[.chapter-synopsis]
* 1841--1842. Continuation of Visit to North Carolina Yearly Meeting
* Causes of Trial
* Visit to Money Select Preparative Meeting.

Eleventh month 25th. Fifth-day, attended Holly Spring Meeting,
composed of a large number of plain Friends; to whom the injunction of Christ,
"`Take no thought saying, what shall we eat? what shall we drink?
or wherewithal shall we be clothed?
for after all these things do the Gentiles seek;
for your Heavenly Father knows that you have need of all these things.
But seek first the kingdom of God and his righteousness,
and all these things shall be added unto you,`" was treated on.
It was shown where this was carefully attended to in early life,
and faithfully persevered in,
the follower of Christ was preserved from the entanglements and perplexities,
which the disobedient often become involved in.
While these run into the inordinate pursuit of the world,
after they had been visited in early life,
and lose the life and greenness which they once had,
the dedicated sons and daughters of God,
are enabled to keep their worldly concerns in their proper place,
and to fulfill their social and religious duties, in the right time and manner.
The young people were earnestly pressed to mind the openings of Divine light,
upon their understanding: and to walk in obedience thereto;
that so they may grow in the knowledge of the Truth, and become established in it.
The solemnizing power of the Blessed Head was felt among us,
and I hoped some of the young ones would be aroused to increased devotion and zeal.

The ignorance which prevails among some,
and their indifference to the work of religion in their own hearts,
and to the spreading of it among us, is truly lamentable.
They are so engrossed in the grovelling pursuit of earthly treasure,
that they feel little or no interest in the concerns of their own religious society;
neglecting their religious meetings, particularly Quarterly and Yearly Meetings;
as if they could not spare any time from the world to attend them.
These often imbibe prejudices against Friends, and the decisions of meetings; which,
did they faithfully discharge their own duties,
would never gain an entrance into their minds, or long hold possession of them.

We held an appointed meeting at Piney Ridge on the 26th,
and afterwards rode about eighteen miles, much of the way through the woods,
to our friend Phineas Nixon`'s. Here we met our friends, Abner Heald and David Fawcet,
of Salem, Ohio.
It is pleasant to get into the company of those who are abroad,
laboring in the Master`'s cause; the number of such being small in this day.
I believe we were mutually comforted in thus being thrown together.
Next day attended the Quarterly Meeting; where a pretty large body of Friends,
and a large number of others assembled.
The great lack of practical religion among the professors of the name of Christ;
what that religion would lead to;
and the blessed fruits which would be produced by it in the world;
were largely treated on;
the Master of our assemblies furnishing matter
and strength to preach his everlasting gospel,
in the demonstration of his spirit and power.
Great solemnity and quiet prevailed over the meeting.

In the meeting for Discipline,
I endeavored to press upon Friends the advice of the Yearly Meeting,
contained in its epistle;
to labor affectionately with those who use ardent spirits as a drink,
or give it to their workmen; that, if possible,
they may be reclaimed from the evil habit; and that those who persist in it,
may be enumerated, and the account taken up to the next Yearly Meeting.
The subject of education being brought to view in reading the Boarding School report,
it afforded an opportunity to plead with Friends on behalf of the dear children;
that those who had the means should devote a proper
portion of it to give them suitable school learning,
at an age when they will best acquire it.

Money expended for this object will yield the best interest,
and will be far more valuable to them, than given to them when arriving at manhood,
without education.
On the guarded religious instruction and care of the youth,
very much depends the hope of the preservation and continuance of our Society;
and in other places this watchful care had been productive of much good.
I came away from the meeting altogether relieved and peaceful; got our horses,
and we set off immediately and rode sixteen miles to our friend, J. A.`'s,
having his son for guide.

The road as far as Ashborough, was mountainous and tedious,
and we did not arrive until about twenty minutes after seven o`'clock;
but the moonlight aided us much in driving safely.

The welcome we met with here, as in other places, was grateful,
especially after the fatigue of a long meeting, and the ride in the evening.
On the following morning a snow storm set in, which lasted all the day,
beating in our faces much of the way to Rocky River, about twelve miles.
Here we had a meeting at three o`'clock in the afternoon; about twenty men and eight women.
The way opened to encourage the few members to
diligence and faithfulness in their religious duties;
and to warn some transgressors present, to forsake their evil ways,
and turn unto the Lord who would have mercy,
if they repented and forsook their wrong courses.
In a little opportunity with the family of the Friend where we stopped,
I endeavored to encourage the parents and children;
expressing the belief that the Son of Peace had
been at work in the hearts of some of them.

29th. Had an appointed meeting at Cane Creek, where we met with our friends,
Dougan and Asenath Clark.
It was to me a trying time.
I labored some among them under discouragement,
from a feeling of the low state of religion there; in which it felt,
that except the Lord build the house, they labor in vain who build it.
D+++.+++ Clark spoke of it as another offer of Divine visitation,
and exhorted them to close in with it.
The weather being cold and the ground covered with snow,
we concluded to tarry with our friends, Joseph Dixon and family;
whom we found under some concern for the state of society here.
I had a good deal of conversation with him,
respecting the lack of liberality in education.
After an opportunity with the family, in the morning,
he piloted us to South Fork meeting, appointed at ten o`'clock;
from there we went to Chatham, at three o`'clock in the afternoon.
I was engaged to labor for the encouragement of the sincere-hearted in both meetings;
that they might, through dedication to the Lord,
be strengthened to build up the waste places, and support their religious meetings,
and the testimonies given us to bear.
In the latter meeting there was a number of persons, to whom it was my place to show,
that man is not judged and condemned because he has no
light or knowledge of what is right and wrong,
but because he is not obedient to that which he has.
Our Savior lays down the doctrine very plainly: "`This is the condemnation,
that light has come into the world, but men loved darkness rather than light,
because their deeds were evil.
For every one that does evil hates the light, neither comes to the light,
lest his deeds should be reproved; but he that does truth, comes to the light,
that his deeds may be made manifest that they are wrought in God.`"

They were appealed to for the verity of the doctrine, in their own experience,
and called upon to receive and obey the light of
Christ in its manifestations to the soul;
that they might receive strength from Him to forsake their evil practices,
and experience reconciliation with God through Him.
Some of them were serious,
and I believe were convinced of the truth of what was delivered.
Our friend John Newlin, came to the meeting; with whom we went home,
and the next day were at the Spring Meeting, being the 1st of the Twelfth month.

Twelfth month 2nd. Set off in company with John Newlin who was going to Hillsborough,
and when we came to the road which we had proposed to take for Raleigh,
I felt some doubts of leaving the few Friends residing at Eno,
lest I should carry away a burden in relation to them,
which would be undesirable to bear.
On mentioning my fears of omitting to go there to John Newlin,
and asking whether the few Friends could be got together soon, he replied, yes,
in half an hour; and encouraged me to go.
Although a trial to turn out of our course, I believed it best.
We reached the house of T. T.; whose wife has frequently sat alone in the meeting-house;
I think as often as five mid-week meeting days successively;
and a messenger was soon dispatched to his brother to invite his family to meet there.

After dinner, we sat down together, six or eight children of each family;
and my Divine Master soon prepared me to communicate to them;
bringing to my remembrance the circumstance of the
woman who broke the alabaster box of ointment,
of great value, and poured it on His head; for which some found fault,
as a waste of that which might have been sold and given to the poor.
It appeared applicable to this devoted woman; who, through many difficulties,
was openly acknowledging her fidelity to her Lord,
in devoting a portion of her time and labor to attend her religious meetings;
while others were neglecting them,
and perhaps thinking it a waste of time in her to go there.
The conditions of the others were also spoken to;
calling upon them to obey the invitation often extended
to them--to enter into the vineyard of their own hearts,
and labor by the aid of the Holy Spirit,
to have everything eradicated that obstructed the growth of the Seed of the kingdom.
To the heads of the families, who were in the neglect of their duty,
the intimation was given that the eleventh hour was at hand,
and they were solemnly warned of the danger of putting off this all-important work;
and the young people were affectionately pressed to open the door of their hearts,
and let the King of Glory come in and make them what He would have them to be;
lights in the world, and as a city set upon a hill that could not be hid;
that others might see their good works and glorify their Father which is in heaven.
Some of them were brought under serious feelings, and I left them,
thankful for the extension of holy help to discharge my duty towards them.

We rode to Hillsborough and put up at a tavern; not very agreeable to my feelings.
The unpleasantness of the place, the dark rainy weather,
and the trial I had passed through, in turning aside from our original route,
covered me with sadness;
which none can rightly understand who have never had such a mission to fulfill,
and know not what it is to have their faith closely proved,
when they have no other desire than to be found faithful to their Lord in his requirings.
But I went to bed and slept pretty well; rose early the next morning,
and about seven o`'clock left the place, and through some rain and mud rode to Raleigh,
The weather cleared off in the evening,
and we succeeded in getting our breakfast at the hotel the following morning,
in time to leave the town at eight o`'clock.
We had forty-three miles to ride in order to reach J. K.`'s;
much of the way through a piney country; the roads pretty level and sandy;
and though we stopped nearly an hour to feed our horses,
we arrived at our friends about sunset, and were hospitably received and entertained.

On first-day morning, Twelfth month 5th, we went to Neuse Meeting, about seven miles;
crossing that river in a flat which we did not deem very safe, owing to its small size,
the strength of the current, and the depth of the water;
which had risen considerably from the late snow and rain.
Persons of other persuasions, as well as Friends, collected,
and it was some trial to be placed before such a company, a stranger,
to whom their attention was naturally directed.
But after some time,
there was an opening on the preciousness of the salvation of the immortal soul,
and that nothing in this world was worthy of being brought into competition with it.

The people sat very still and attentive.
In the course of the communication, my mind was turned to the state of an infidel.
After having set forth the object of the coming, sufferings, death, resurrection, etc,
of our Lord Jesus Christ, I was led to dwell upon the awfulness of falling into a state,
which landed individuals in a feeling like that of Cain, a vagabond on the earth;
and having fallen into great wretchedness,
such seek to draw others into the like condition with themselves.
"`Their vine is the vine of Sodom, and of the fields of Gomorrah;
their grapes are grapes of gall, their clusters are bitter.`"
"`The poison of asps is under their lips.`"
These were solemnly warned of their danger, and invited to yield to the grace of God,
which at times was bringing them under fearful
apprehensions of his just and inevitable judgments,
if they die in this condition.
To those who love the Lord Jesus,
the blessedness of the heavenly reward at the end of the race, if they persevere,
when God will wipe away all tears from their eyes, was held forth;
and they were encouraged to increased faithfulness and dedication.
It was a solemn opportunity, and when the meeting closed, several men,
not of our Society,
shook hands in a manner which indicated their unity with the doctrine.
We returned after dinner to J. K.`'s,
and in the evening had a religious opportunity with his family.

6th. Rode eight miles to Nahunta Meeting, and though early when we reached the house,
found a number collected, who seemed like a people willing to hear the Gospel preached.
We sat a long time in silence;
as it seemed to me to show that we were not to be ready to speak in man`'s time,
and that the Lord will not gratify that disposition, which many have,
to wait and depend upon man.
These feelings prepared me, in some degree,
to show the people that it is not according to the Gospel
dispensation to look to man for a knowledge of the Divine will,
nor for spiritual bread.
No man can impart spiritual bread, but as it is given him by Christ.
It was under the Jewish dispensation,
that the law was to be received from the priests`' lips; not so under the Gospel.
Every one is to come to and wait upon Christ.
The Lord will not give his glory to another.
The way gradually opened to invite the people to come to Christ,
that they might know Him to be their teacher;
to instruct them in the things which pertain to their soul`'s salvation,
and to give them the bread and water of life, to nourish them up unto everlasting life.
They were also shown, that as they thus came into his government and kingdom,
there could be no revenge, nor ill-will, nor use of improper language towards each other.
Parents being united in this, they would be concerned for their children,
to bring them also to Christ;
and such families would verify the description given by the Psalmist,
of this unity being like the ointment poured upon the head,
which ran down to the skirts of the garment;
and like the dew which descends upon the mountains of Zion;
where the Lord commanded the blessing, even life forevermore.

The meeting closed with prayer, for some who have nearly reached the eleventh hour;
that they might, by the love of God,
be constrained to labor in the vineyards of their own hearts,
and have every wrong plant removed; that they might be clothed with gravity and wisdom,
to set a proper example to their children: and for those who meet in this place, that,
through increased dedication,
they might be qualified to support the ark of the testimonies,
and show forth the praises of the Lord God and the Lamb.
The meeting ended solemnly, and the people were serious, and some of them tendered.
We then rode home with a member, and stayed with him and his family that night.
Within the limits of this meeting, we were informed, of two Friends and their wives,
who do not know their letters.
They have raised a large number of children, who, of course,
they could not instruct themselves, by reading to them in the Holy Scriptures.

7th. Had a meeting at Contentnea.
The house being very open, and no fire, I suffered so from the cold,
that when speaking I could hardly prevent my teeth from striking together.
The state of this meeting appeared to me very low, and my feelings were discouraging,
and I said but little in the meeting.

Went to the house of a Friend living on the way towards Rich Square,
and several being there in the evening,
I felt willing to have a religious opportunity with them;
in which I endeavored to press upon them the necessity
of more thorough devotion to the cause of Truth,
that they may be instrumental in supporting the testimonies given to us to bear,
and in reviving the zeal of others.
I am persuaded that the open,
comfortless condition of most of their meeting-houses,--
nearly all without any means of warming them,
or drying the wet clothes of those who ride or walk in the rain or snow,--
has the effect to keep their meetings smaller than they would be,
were proper care taken to make them fit places to meet for the worship of Him,
to whom we owe ourselves, and all that we possess.
Men of ability will provide for themselves suitable habitations;
and how much more careful should they be, to have buildings decent,
and appropriate for the worship of the Lord of Hosts,
where they assemble professedly to pay the homage due to his great name.
The dilapidated state of the house,
may strike strangers as an index to the kind of
religion which the professed worshippers possess,
and may stumble or turn aside sincere seekers.
I mentioned the subject to several of the members, at the close of the meeting,
and they admitted the force of the observations;
remarking that some other Friend had spoken to them respecting it before.

It is to be feared, that the general apathy on the subject of vital, practical religion,
has an influence, in many places,
to deter Friends from providing all the accommodation they require,
and the sheds to defend their horses from the inclemency of the weather.

We set off early on the 8th, accompanied by two guides, and rode to Tarborough,
thirty-seven miles, and lodged.
The next morning, proceeded to Roanoke River;
which had been over its banks in some places,--caused
by a late freshet,--and lodged timber on the road,
so as to obstruct it: but we succeeded in finding a way around,
which we could not have passed a few days earlier.

After reaching T. P.`'s, we had notices sent out for a meeting en the next day,
at Rich Square; which we attended; being a pretty large collection of Friends and others.
This was the meeting to which that deep and powerful minister of the Gospel of Christ,
Richard Jordan, belonged; where he labored in his early life,
in his Divine Master`'s cause.
After sitting down in the meeting,
I was assailed with the suggestion that I had done wrong in omitting to go to Core Sound,
and now I might be left to myself to get along as well as I could;
and what a condition I should bring myself into, if I could now get no further,
and be obliged to inform Friends that I had missed my way,
and must turn back to that meeting, about two hundred miles distant.

I was willing to do anything for peace of mind,
and to have the favor of my Divine Master restored;
if I had forfeited it through disobedience, or undertaking to decide for myself.
These views humbled me greatly, and my faith and hope were reduced low.
But He, whose the cause is which I desired might not suffer, had compassion on me;
and in the midst of my conflict gave me unexpectedly an
intimation to stand up with the testimony:
"`There is none other name under heaven given among men whereby we must be saved,`"
but the name of Jesus Christ of Nazareth.
I was, at first, afraid to comply lest I was deceived; but in mercy it was repeated;
and I arose, not knowing what I was to say further,
and leaving it all to the Lord to supply the matter.
The way was opened to preach Christ Jesus as the only way to the Father,
and his spiritual baptism with the Holy Ghost and fire,
as the appointed means by which sin and corruption are
to be purged out of the heart of man;
and he prepared to be made a partaker of the
fulness of the blessings of the gospel of Christ;
both in what He did and suffered for us, in the prepared body,
and the glorious reward at the end of the race;
laid up for all those who love and serve Him with sincerity and faithfulness.
The current then turned to the exercised remnant in this meeting;
who were encouraged to increased dedication in the occupancy of their gifts,
and to be willing to be again and again baptized into suffering on their own account,
and for the body`'s sake, the church.
The young people were also invited to receive Christ in his visitations to their souls;
to take his yoke upon them and learn of Him, that they may be made servants in his house,
and qualified to support the doctrines and testimonies given to us to bear.
Some of the sincere-hearted were tendered, and manifested their unity,
in seeming unwillingness to part from us,
as well as by expressing their satisfaction with our company.
But I left them in a low state of mind,
not knowing how I should get through with the remaining meetings;
and whether I should not yet find my way blocked up, by disqualification for service,
brought on by omitting to go to that distant meeting.

A young man offering to pilot us, we set off for B. C.`'s, seventeen miles,
on our way to Piney Woods, eating our dinner in the carriage;
whose house we reached just before dusk.
This family, residing so far from their meeting, as seldom to get there,
I had a religious opportunity with them;
in which I held up to view the great object of life,
the importance of bringing up their children in a proper manner; and whether,
if they rightly felt the importance of regularly attending their religious meetings,
the way would not be made to remove where they
would be able to be at them more frequently.

We left here the following morning, 11th, and rode forty miles to J. N.`'s,
and finding that our friend B. C. of Indiana,
had notice spread of his intention to be here next day,
we went down on first-day morning to Little River Meeting;
where we found a small company; six or eight Friends and a number of others.
In the afternoon we proceeded to Symond`'s Creek and Newbegan Creek,
appointing meetings for the next day.
We put up at J. P.`'s.

We had a meeting next day at Newbegan Creek; in which the duty of silent waiting,
and introversion of mind before the Lord,
that we may hear and understand the still small voice which speaks as never man spake,
and by obedience thereto, be brought to the knowledge of God and Jesus Christ,
whom He has sent, which is life eternal; was opened and enforced.
It was shown that, however valuable the knowledge communicated by the Scriptures,
and highly to be prized and cherished, yet this of itself was not sufficient.
The saving knowledge of the Father is received by and through the Son; who is the way,
the truth and the life, communicated by the operations of his Spirit in the heart.
It was a time of renewed favor.

After dining, we rode to Symond`'s Creek,
where we had the company of nearly all the members of the two meetings last visited.
It was satisfactory to have them together;
giving the opportunity of entering into feeling with them, in their reduced condition;
in which the way was opened to encourage the
honest-hearted to keep hold of the shield of faith;
whereby they might quench the darts of the enemy,
who seeks to discourage and turn aside from the path of duty.
The necessity of watching over,
and restraining the children from the corruptions which abound in the world,
and of Friends coming under religious exercise,
that they may be qualified to bring them up in the nurture and admonition of the Lord,
were pointed out;
and the danger of being overwhelmed by the pursuit of business and the love of money,
impressed upon some.
The Truth rose into dominion, and brought some into tenderness,
and they took leave of us in near affection and unity,
desiring our preservation every way.

It is not many years since the meetings held at these lower houses were quite large;
but the climate being unhealthy in these counties,
and Friends surrounded by slaves and slaveholders,
they have gradually moved into the Western States;
until the number is scarcely sufficient to keep up their meetings with reputation.
The Yearly Meeting of North Carolina was first held altogether at Little River;
then alternately here and at New Garden;
but as Friends increased in the middle and western side of the State,
and went from there into Tennessee, it has been held altogether at New Garden.
It produces mournful feelings to see our meetings reducing and going down,
and the houses deserted and sold.
Friends have the right to leave one country, and go into another,
where they are satisfied that Divine wisdom points to such change.
It is, however, very needful to know,
that it is the mind of our Holy Leader we should make such a move;
for not only trials are brought upon those who remain, by the reduction of the meeting,
and by Friends selling their property to slaveholders, who move in among them;
but those who go, it is to be feared, in some instances,
have not improved their condition, either temporally or spiritually.
But had they remained,
they might have been instrumental in gathering others to the Truth;
and by keeping up the meetings, preserved the children of Friends in the Society;
many of whom, for lack of proper company and example, have gone into the world,
and formed connections for life, which have led them out of the Society,
and proved a lasting injury.
Some have, no doubt, removed from honest motives, and have prospered;
yet it is not an evidence of redemption from the love of the world, to see Friends,
the highest professing people among Christians, so ready to take wing,
and hasten after the valuable lands, recently obtained from the conquered natives;
who are driven here and there, having scarcely any certain dwelling-place.
The example of thirst for gain does not become a professedly self-denying people,
and must make an impression on others,
unfavorable to the reception of the gospel as held by us.
It, moreover, brings dimness of vision on ourselves,
and the loss of that lively zeal and spiritual-mindedness,
which belong to the true Christian;
and eminently characterized the early members of our Society.

We had an appointed meeting at Well`'s, on the 14th; attended Bush Spring on the 15th;
both of which were exercising.
It is painful to have to sit where the negligent and
slothful sit and partake of the food proper for them.
I endeavored to labor faithfully among them; but sometimes on sitting down,
I would feel as if all sense of Divine life and strength had left me; and then,
for a short time,
would fear that I had not been ministering in the power and authority of Truth.
This humbled and kept me poor in spirit, seeking to the Lord in and out of meetings;
and at times having no qualification to enter into much conversation.
But I felt no condemnation; and the tendering, contriting peace of God,
which surpasses the understanding of the unregenerate man, would flow into my heart,
and enable me to trust in Him, and lean upon Christ,
the great High Priest of our profession,
who is touched with a feeling of our infirmities.

16th. Much rain having fallen during the night, and continuing,
the traveling was disagreeable; but,
notwithstanding the unfavorable state of the weather,
notice having been spread of our intention to be at Piney Woods,
at the usual week-day meeting, a large company convened.
I felt, as common for me, exceedingly empty,
and my faith perhaps never lower at such a time; but after a time of waiting,
the testimony of the holy apostle, was revived:
"`Without faith, it is impossible to please God.`"
We must not only believe that He is,
but that He is a rewarder of them who diligently seek Him.
Though I was so stripped, I believed it was my duty to rise with this testimony;
and as I kept patient and steady, one thing was opened after another,
until the stream became like a river for a man to swim in; the people were solemnized,
and the name of the Lord exalted; and I went to D. W.`'s with a peaceful mind.
This finished the visit to the meetings of North Carolina;
and that night I slept soundly till near the time to
rise for an early departure into Virginia.
We were joined by our friend J. N., at whose house we had stayed three nights;
and through a storm of rain and snow, we rode thirty-eight miles, to our friend J. H.`'s,
at Somerton, and had notice spread for a meeting there next day.

We had a meeting at Somerton, with Friends, and a few not professing with us,
to some satisfaction.
Next morning, being first-day, we rode over to Western Branch,
and there met a little company; parts of two or three families of Friends;
among whom there was some ability received, to show the unwillingness of man,
in his first nature, to submit to the restraints of the power of religion;
and the consequence which must result to him in
refusing to come under the yoke and cross of Christ.
Some were fervently and affectionately pleaded with, to lay these things to heart,
and to give up to the convictions of the Spirit of Christ,
while the day of mercy was extended to them.
We dined with some Friends,
and had a farther opportunity of laying before them the duty of restraining the children;
and also the danger of being carried away with
the fascination of vain and fashionable society;
that the Lord will bring all to judgment;
and what will all our creaturely indulgences do for us, in that awful day?
Rode back to N. J.`'s, and on second-day, the 20th, had a meeting at their meeting-house;
wherein I had close labor with the negligent members,
who are often absent from their meetings,
and live in much indifference respecting their religious duties.
It was a season of earnest labor with members and others,
to draw them into a right sense of the obligations they are under,
and the great importance of working out their soul`'s salvation,
while the Lord is striving with them, by the convictions of his Holy Spirit.

A Friend, of Black Creek, met us here, and conducted us to his house.
His father came into the Society, and, from the account we had,
was a diligent attender of meetings, and careful to take his children with him.
The benefit of his faithfulness, is seen in his children;
who appear to be exemplary Friends; upon whom the support of the meeting much devolves.
It was peculiarly encouraging to find some who had joined Friends,
and manifested their love to the Society, by supporting a plain, consistent appearance;
where degeneracy has greatly crept in;
and many who profess with us have so gone into the world, that the meetings, in places,
are dropped, and others nearly gone down.

21st. A pretty large company, besides Friends, assembled with us today;
many of whom appeared to me to be persons of inquiring minds.
The Master condescended to furnish ability to preach the gospel;
showing that it is a dispensation of the spirit, life and power;
to bring man out of his lost and sinful condition,
and restore him into that in which Adam stood before he fell.
Christ said of his sheep,
"`I am come that they might have life, and that they might have it more abundantly.`"
He also promised the gift of the Comforter, the Spirit of Truth,
who was with them and should be in them.
And the Apostle declared, "`I am not ashamed of the gospel of Christ,
for it is the power of God unto salvation, to every one that believes;
to the Jew first, and also to the Greek.`"
It is not a dispensation of outward ceremonies, as the Jewish,
which may be performed in the will and wisdom of man.
You are not come unto the Mount that might be touched, etc,
"`But you are come unto Mount Zion, and unto the city of the living God,
the heavenly Jerusalem, and to an innumerable company of angels,
and to the general assembly and church of the first born, which are written in heaven;
and to God the judge of all, and to Jesus the Mediator of the New Covenant,
and to the blood of sprinkling that speaks better things than that of Abel.`"
The blood of Abel cried from the ground for vengeance; but Christ said of his enemies:
"`Father, forgive them, they know not what they do.`"
Those who are truly brought under the gospel dispensation,
are brought up into the image of Christ, clothed with his spirit;
and they die to the spirit of revenge,
and to the inordinate indulgence of all their carnal appetites and propensities.
They breathe, in their conduct and in their spirit, "`Glory to God in the highest,
on earth peace and good will to men.`"
Many passages of the Holy Scriptures were brought to my remembrance,
setting forth the blessed,
heavenly nature of the religion of which our holy Redeemer is the Author and Finisher;
and confirming the doctrines of our Society; that it is a dispensation of the Spirit,
the life and power of the dear Son of God,
for the perfect restoration of fallen man to the heavenly image,
and unto favor and acceptance with his gracious and most merciful Creator.
I believe the hearts of many were touched by the
solemnizing power of our holy Head and Helper,
and responded to the truth of the doctrine delivered.
The meeting closed with acknowledgments of our nothingness and unworthiness;
and humble supplication that the truths of the gospel might be fastened by Him,
who only can give the increase, as a nail in a sure place;
and that his protecting power might be round about us,
to preserve us from the snares and temptations of our unwearied enemy.
The people shook hands with me very respectfully; among them were some zealous Baptists.

In the afternoon we went to Black Water.
The distance being twenty miles,
it admitted of but very short time for notice of a meeting with them next day.
But this, like all other meetings in Virginia, has become much reduced;
three or four families only, being left of what was once a pretty large meeting.

We met with the little company and a few descendants of Friends.
I was led to speak to some respecting the feeling which they were brought under,
in the midst of their efforts to obtain happiness from worldly enjoyments.
That there is at times a longing desire in the soul after substantial
food which none of those earthly delights can satisfy.
However they may be pursued with avidity, they all fail;
leaving the soul empty and destitute; often followed by the convictions of Divine Grace,
that the work of salvation is neglected,
and these delights are leading their votary in the
broad way which must terminate in destruction.
Some of this description were earnestly labored with,
to arouse them to a sense of their danger,
and the necessity of giving heed to the warning voice
of the Lord`'s Holy Spirit while the day of mercy lasts.
There were a few exemplary young Friends present,
to whom the language of encouragement was extended,
to dedicate themselves to the cause of Christ; and taking his yoke upon them,
openly confess Him before men.
It was a comfort to meet with such, where the Society has become almost extinct.
We got into our carriage, and rode on our way twenty miles towards Gravelly Run,
eating our dinner as we rode.
Finding no tavern, we went to a store,
hoping that the person who kept it gave entertainment to travelers for pay.
On inquiry of him, he said, that he did not keep a house of entertainment;
but as it was cold, and nearly night, he insisted upon our alighting;
and said he would take the best care of us and of our horses that he could.
Though it was not pleasant to cast ourselves on the hospitality of a stranger,
not of our own religious profession,
yet the lateness of the evening and the frankness of the man,
induced us to stop with him.
After supper, we fell into conversation on water baptism, and a hireling ministry;
in which the young man united very much with our views,
and condemned the sentiment that water baptism is essential to salvation,
and that none are saved without it.
He mentioned that he had heard a Quaker lady, as he called her, preach at Fredericksburg,
last spring; and said it was the best sermon he ever heard preached.
From his account, we judged it to have been our friend Elizabeth Robson,
who had a meeting there about that time.
This shows there are often useful impressions made by a sound gospel ministry,
of which we have no knowledge, and when we may not suspect it.

We got upon the subject of slavery;
in which also he appeared to agree with us in sentiment; though, he said,
there was no disposition among the slaveholders to abandon it.
He informed us of a very respectable neighbor, Daniel Grant, sometimes called Dr. Grant,
from his kind attentions and prescriptions for the sick,
who never owned nor hired a slave.
He has raised thirteen children, seven sons and six daughters,
all of whom are married but one; and provided for them by his own labor, and their aid,
as they became old enough to work.
Our host stated that one evening at his store,
where a number of the neighbors met to obtain their papers by the mail,
the character of a candidate for President of the United States was discussed,
and some alleged that he was an abolitionist.
Dr. Grant in reply remarked, that slavery was a sin.
They cried out that he was an abolitionist.
The doctor appealed to several of them whether they had
not heard their own fathers say that it is a sin;
which they admitted they had.
Well, added the doctor, if believing slavery to be a sin, makes me an abolitionist,
I must be an abolitionist.
Though heretofore held in universal esteem by his neighbors and acquaintance,
this honest avowal of his opinion alienated a number of them;
but without altering his opinion or practice.
His sons follow the example of their venerable father,
who is now about seventy-five years old, neither owning nor hiring slaves;
and on one occasion drew upon them the resentment of their associates,
for uttering their sentiments relating to the horrid system of slavery.
Such upright independence, in the midst of inveterate slaveholders, is worthy of record,
and is highly creditable to the man,
who has the moral courage to differ from his neighbors
on a subject of such exciting character;
and is an example well worthy of being followed and held up to public estimation.
The doctor is regarded as a practical christian,
and his religious tenets as consistent with the spiritual nature of the gospel.

Our hospitable Virginian entertained us very comfortably,
and we hoped our tarriance might prove mutually advantageous;
on parting the invitation was given to repeat our calls whenever we travelled that road.

23rd. We resumed our carriage,
and after traveling twenty-five miles through almost continued rain,
we got to J. B.`'s, at Gravelly Run.
The dark and rainy weather made the shelter of his commodious and well-secured house,
and our friendly reception, doubly welcome.
As there are but one member, and part of another family, besides his own,
who constitute the meeting here, we had them invited to his house that evening;
but the storm preventing them from coming, we sat down with his household and a neighbor,
and held a satisfactory meeting; which, I believe, was encouraging and strengthening,
at least to a part of the little company.
On our way to Petersburg, next morning, we called upon the family above alluded to,
and had a religious opportunity with them;
and then proceeded through Petersburg to Richmond.
My thoughts on the road were much occupied with home;
and reflecting on the great uncertainty of time,
I was engrossed with the idea that I might not find all my dear family living;
which depressed me much;
in connection with the reduced condition of our Society in these parts.
Such reflections introduce the mind into a low state;
in which the consciousness of the short and uncertain duration of temporal enjoyments,
brings the end of all things so near at hand,
that there appears to be but little space between us and death;
and scarcely anything worth living for, but to prepare for that awful event.
The force of these views went off in part before we reached Richmond; and I thought,
perhaps, they were preparatory to the finishing of this little embassy;
that I should retire from the field under a
proper sense of my own weakness and nothingness,
and entire dependence upon the gracious Giver of every good and perfect gift,
for all that was entrusted to me, both spiritual and temporal.

It was my intention to have gone to Wain Oak, in Charles City County;
but on being informed of the very reduced number of members,
and that it was probable if I went there, without notice being first sent,
I should find no one at their first-day meeting;
on deliberately feeling after the matter, I was easy to omit going;
and concluded to request a meeting next day with Friends,
and such as usually meet with them, in Richmond.

A little company met on seventh-day, the 25th, and to my admiration,
I was renewedly qualified, and furnished with matter to minister to their states.
Man was created to be the servant of God; to love and serve his Almighty Creator;
and under whatever circumstance he may be placed,
it is practicable to answer the design of Him who made him,
by obeying the dictates of his Holy Spirit.
"`You shall love the Lord your God with all your heart, and with all your soul,
and with all your mind,
and with all your strength;`" and "`You shall love your neighbor as yourself.`"
There were some present, who I apprehended, had widely departed from the Divine law,
and from loving and serving God;
and ability was furnished to plead with these to turn at his reproofs,
that they may be raised into the dignity and nobility which man was designed for;
being created a little lower than the angels, and crowned with glory and honor.
Others, who had in measure seen the beauty of the Truth,
were called upon to come forth and confess Christ,
in the midst of a crooked and perverse generation.

The few Friends in this city are much exposed to an influence
very unfavorable to the growth of vital religion.
To be enabled to labor faithfully for their help,
was a little evidence that Divine goodness was still watching over them,
and I left the city with a peaceful and thankful heart.
Having about twenty-one miles to ride, we hastened away,
taking something with us to eat on the road, and by diligent traveling,
we got to our friend E. T. C.`'s before dark: who, with his family,
received and entertained us with their wonted kindness and hospitality.

On first-day, we attended Cedar Creek Meeting;
a considerable part of the company not appearing to be members.
The subject brought before me, was the fruit of the Christian religion,
where it was really prevailing, as contained in the command of the Savior.
"`A new command I give unto you, that you love one another; as I have loved you,
that you also love one another.`"
In this love, Christ left the bosom of the Father, came, not to be ministered unto,
but to minister, and to give his life a ransom for many.
He came not as a great, earthly prince, but in the form of a servant;
and made Himself of no reputation.
His spirit and his religion divest man of selfishness;
lead him to feel for the sufferings of his fellow
creatures and to regard every man as his brother;
to feed the hungry, clothe the naked, visit the sick and those in prisons;
agreeable to Christ`'s declaration when speaking
of the different rewards of those who do so,
and those who do not.
The states of some who were bringing forth the fruits of darkness,
and seeking their selfish gratifications,
whatever may be the sufferings they bring upon others, were closely spoken to,
and they labored with,
to persuade them to yield to the heavenly
convictions of the grace of God in their hearts.

After dinner we walked over to L. C.`'s,
to visit his aged mother where I had an opportunity with several of the members,
to urge them to increased zeal and faithfulness in keeping up their religious meetings.
But the state of this meeting looks discouraging.

A considerable freshet in the streams,
made it necessary to ride several miles to cross a bridge over the South Anna River,
to get into the neighborhood of Caroline Meeting;
which we reached on second-day afternoon, the 27th;
and the following morning had a meeting with the few members and others;
in which the importance of rightly occupying the time and talents committed to our trust,
was enforced upon some;
and prayer was offered for the continued aid and protection of our Heavenly Father;
that we might be preserved in humility,
and delivered from the snares and temptations by which
a cruel enemy would seek to lay waste and destroy,
even those who had made a good confession before men, of the blessed Truth.
We returned to our lodgings,
and in the evening had a little religious communication to our hostess,
her son and her sister;
referring to the love and kindness which our Lord showed to Martha and Mary,
and their brother Lazarus; and which I believed He would still manifest to others,
who sought unto Him, and sincerely loved Him; encouraging them to attend their meeting,
and to seek retirement before the Lord at home,
that their spiritual strength might be renewed.

29th. Took an affectionate leave of our friends, and rode to Fredericksburg;
where we found the nephew of my companion,
waiting to take charge of the carriage and horses;
which we put on board the steamboat the following morning,
and reached Washington in the evening.

31st. Rose early, and taking the car at six o`'clock,
we got to Baltimore a few minutes after eight; breakfasted,
and again entered the cars for Philadelphia, which we reached about four o`'clock;
and were gladly received by our beloved families and friends;
having been absent exactly fifteen weeks,
and travelled about twenty-two hundred and forty miles.
Home was exceedingly grateful, and my mind being favored with calm and peaceful feelings,
it seemed as if the time since I left it had been but a few days.
For all the mercies of our gracious Caretaker,
in preserving us from sickness and serious casualty; and, from season to season,
granting renewed ability for the work whereunto He had appointed us,
may my soul be kept in deep prostration before Him; and in humility and fear;
relying on his Holy Spirit to put forth afresh, when He shall see meet,
and while He shuts, not daring to open; ascribing unto Him, the Lord God,
and to the Lamb, all glory and honor, salvation and strength,
which is alone due to his everlastingly worthy, holy name.

1842+++.+++ After returning from North Carolina, I was much at home,
and passed through dispensations of poverty of spirit;
in which my faith at times was put to a close test.
There were also trials arising out of the state of our religious Society,
and the disposition of some to indulge in a party and censorious spirit.
But under all these afflictions there is a secret support, and in the Lord`'s time,
way is made to show ourselves on his side;
and that He can grant deliverance from bonds and imprisonment,
and furnish qualification to testify of his mercy and goodness.

In the Second month, I attended Concord Quarterly Meeting,
in which I was livingly qualified to preach the gospel;
and my dear wife followed in reverent, fervent supplication.
The way also opened, in the Meeting for Discipline, for further service,
to the encouragement of Friends in the support of our Christian testimonies.

At our Meeting for Sufferings in the Third month,
a committee was appointed to prepare an epistle to the Meeting for Sufferings in London;
and it being believed,
that it would be proper to call the attention of the latter to
the practice of allowing their members to write,
print and publish works on our religious principles,
without proper examination by an authorized body,
the matter was discussed in the committee, and a few Friends appointed to draft an essay.
The introduction of works into this country,
containing sentiments not in accordance with the doctrines
which the Society has held and promulgated from the beginning,
was mentioned.
The epistle being prepared, was very fully approved,
both in the Meeting for Sufferings and in the Yearly Meeting.

Samuel Bettle and myself having been appointed
by our Quarterly Meeting of Ministers and Elders,
to attend the Select Preparative Meeting of Muncy,
we took the railroad cars on second-day, the 18th of the Seventh month,
and that evening reached Danville, one hundred and twenty-six miles from Philadelphia.

The weather was very warm, and riding in a crowded stage,
part of the distance from Pottsville, over the mountains, was very oppressive.
Here we were met on third-day morning, by Andrew Eves, Jr., who took us to his father`'s;
and in the afternoon we sat with the Friends;
and next day attended their Monthly Meeting.
The neglect to send representatives, and sometimes to forward the reports in time,
were the occasion of our appointment; on which points,
we endeavored to stir up and encourage Friends to greater care and faithfulness.
Both of us were engaged on fourth-day, in the ministry,
and also in advising Friends on some matters which were brought into view.
There is a painful state of indolence in some; but we were encouraged by the hope,
that among the young Friends,
there is an increasing attachment to the Society and its testimonies;
and that some of them are preparing for usefulness in the church.
We had a religious opportunity at the house of David Masters, with part of his family,
and other Friends present; and leaving there on fifth-day, lodged at Danville,
and arrived at our homes, sixth-day evening,
satisfied with this little act of dedication.

Eighth month 10th. I went to Woodbury, and attended Salem Quarterly Meeting held there.
After the Select Meeting, dined and took tea at Joseph Whitall`'s,
who was in a frail, diseased state.
Very few have passed through more trials than he has;
in which he has been an excellent example;
as well as in his undeviating faithfulness to the doctrines and testimonies of Friends.
When it shall please the Head of the church to
remove him from a militant to a triumphant state,
the Quarterly and Monthly Meeting, of which he is a valuable member,
will greatly miss him, as a father and counselor among them.
I felt very poor and unfit for anything in the meeting on fifth-day;
but the power of Truth finally seemed to prevail,
and I hope some were aroused to a fresh sense of
the necessity of working out their salvation,
with fear and trembling; and that the desponding, mournful ones,
who have many burdens to bear, were a little encouraged and revived.

10th month 16th. Was held our Meeting for Sufferings; in which the subject of slavery,
and the disabilities under which the colored people are placed,
occupied much of the time of the meeting, particularly as regards the State of Delaware.
