== Chapter XV

[.chapter-synopsis]
* 1842--1843. Second Religious Visit within the Limits of Ohio Yearly Meeting

On the 10th of Eleventh month, 1842, I left my comfortable home,
and tenderly beloved wife and children,
and took passage in the public line of cars and stages for Wheeling;
for the purpose of paying a religious visit to
the meetings composing Ohio Yearly Meeting;
for which, I obtained a certificate of the unity of the Monthly Meeting,
and an endorsement of the Quarterly Meeting.
The general expression of approbation and desire for my encouragement was strengthening,
and raised the hope that the proposed movement was right.
I had been much shut up, for several weeks,
and stripped of all ability to engage in any good word or work; under which dispensation,
I endeavored to abide with patience; though at times assailed with fears,
whether I was not mistaken in my prospect;
yet at times light would shine on those distant meetings.
The difficulty of leaving my temporal concerns, on which my living chiefly depended,
in the hands of apprentice boys; and the solitary situation of my family, all, at times,
came over me with force; inducing the enquiry, whether it was my duty,
as a parent and provider, to leave them in this way.
But I believed it right to commit them to the tender
care and protection of our Heavenly Father,
and endeavor in fear and lowliness of mind, to do his will.

We reached Baltimore in the afternoon; lodged there,
and took the cars next morning for Cumberland,
one hundred and seventy-eight miles by railroad, from Baltimore;
and at about eight o`'clock in the evening, got into the stage for Brownsville;
rode all night through the Allegheny Mountains, in snow and rain,
and drove into Brownsville about twelve o`'clock next day.

We had for our fellow passengers in the stage, five or six low, profane slaveholders;
whose depraved spirits, and vulgar language, were very unpleasant and annoying.
But taking no notice of them, they discovered we were not like themselves, and finally,
they ceased talking.
After breakfast, some remarks were made on the subject of farming,
which led to the effects of slavery upon the state of the country in the Southern States;
and the irrationality of a man keeping forty or fifty slaves,
while he could make little more than a bare living with them; which,
with proper industry, he could do, without them.
It was taking on him the care of persons who could take care of themselves,
and without whom he could make out to live as well.
"`Ah but,`" said one of the company, "`there are the young niggers;
he can sell one of them once in awhile and live on that.`"
I answered, I should not like to subsist on human flesh.

This roused them up, to defend their dark and unrighteous system; in doing which,
they could offer little, except that the free blacks, and many whites,
were not as well provided for as the slaves; which in some cases might be true,
but was not so to any great extent.
Moreover, the latter have their liberty,
and are able to exercise their right to labor where they please;
and even those who have to labor hard, very often live upon the best food,
though at the expense of frugality and economy.

At Brownsville, a Friend offered to take us out to Sewickly Meeting;
and leaving our baggage, we rode to our aged friend`'s, Samuel Cope, at Providence,
eight miles, and were heartily received.
The road being wet and hilly, we rose early and were about five hours riding to Sewickly,
sixteen miles; where we attended their first-day meeting.
Some ability was granted to labor for arousing the careless, and negligent,
and the transgressor;
and the language of encouragement was offered to the sincere-hearted,
and to the young people, to come under the yoke of Christ.

We dined at G. G.`'s, who appears to be a well-concerned Friend;
and lodged at his brother B. G.`'s. In the morning,
I had a tendering communication to his aged and weakly mother and her sister;
in which they were recommended to the mercy of our Heavenly Father, extended to poor,
sinful man, through our Lord Jesus Christ;
and exhorted to labor to draw near to the footstool of Divine Grace,
that they may be prepared to partake of his pardoning mercy,
and in the awful close experience acceptance through Him.
We were all affected together to tears,
under a renewed feeling of the Lord`'s goodness and compassion.

Set off in a shower of rain, and got to D. C.`'s; dined,
and went to a meeting appointed at two o`'clock, at Providence; in which, after inward,
solid waiting, the power of Christ spread over us; and the humble-hearted,
visited children, were encouraged to increased devotedness to the Lord and his cause;
and I trust the burden-bearers were comforted.
Samuel Cope asked me, in the evening,
whether I did right in limiting the invitation to Friends,
and those who usually attended their meetings;
but it appeared to me that my concern was principally to strengthen,
as ability may be granted, our own flock, and to turn transgressors among us,
to the saving power of Divine Grace.
In the evening, Samuel Cope`'s sons and their wives being present,
I had an opportunity with them;
and labored to impress them with the responsibility of their station as parents,
and the importance of rightly exampling their children,
and restraining them from wrong things; so that, as far as in our power,
we may be instrumental in preparing the ground of the heart, for the seed of the kingdom;
when the good Husbandman shall see proper to sow it there.
It was a heart-tendering time, and the aged Friends seemed comforted.

15th. Third-day morning.
Had an appointed meeting at Centre; in which the Master furnished matter,
adapted to the different states.
I was low and weak; but keeping down to the Seed of life, I was enabled to minister,
so as to reach the witness in some, and experience peace in my own bosom.
The state of one, to whom I was a stranger, a Friend said afterwards,
was particularly described.
This was a little encouraging;
having many fears lest I should be deserted of my gracious Master.
We dined with the sister of D. M., a widow, and rode home with him,
and were kindly received by his wife.

16th. Attended their usual meeting at Brownsville,
which was not so animating and comforting as some others.
A lack of faithfulness seemed to have brought weakness over some;
and when plain things arose to deliver, the separatists being in meeting,
on the other side of the partition, made it embarrassing to communicate;
and I labored along rather heavily.
But the doctrines of the gospel, and the use and authority of the Holy Scriptures,
were plainly held up and enforced.

In going from house to house, there is a difference in our feelings.
In some a sense of oppression is felt, in which we cannot breathe as in a pure atmosphere.
This is a source of exercise, and we have need to keep inward to the Master;
that if anything is given to hand to them, it may be done faithfully,
and yet in the spirit of love, and sincere desire for their help.
In other families; particularly those of young, tender-spirited Friends,
who love the Truth, and desire to be faithful to their Lord and Master,
the spirits of the true travelers for the prosperity of Zion, are more at liberty;
and it is a strength to be in the company of this description.

We took stage in the afternoon and rode to Wheeling;
where we arrived about three o`'clock in the morning.
One of the passengers seemed disposed to talk on political subjects,
and I remarked to him that I thought the Government better
employed in making such roads as we were riding over,
and in other improvements, for the benefit of the county,
than in building forts and vessels of war.
He then argued in favor of self-defense;
said he would defend himself and family if assailed by a person who would destroy life,
if he was not killed.
I told him I could not tell what I would do in such an emergency;
but I believed it would be wrong to take the
life of a fellow creature under any circumstance;
that it would be best to put our trust in Divine Providence, and relying on Him,
suffer death rather than destroy the life of a human being.
But I believed his care was remarkably extended to those who confided in Him.
That this was exemplified in the civil wars in Ireland;
where Friends were exposed to the violence of the banditti, like others;
but of whom none were destroyed except two, who took up guns to defend themselves.
And while William Penn and his friends held the government of Pennsylvania,
there was no war with the natives; but in other colonies,
there was much destruction on both sides.
I also remarked, that when the children of Israel served the Lord,
they were preserved in peace; but when they worshipped idols, the defense was withdrawn,
and their enemies, who had been in peace with them,
came in and reduced them to servitude.
More of this confidence in providential protection was needed in this country;
but by placing our dependence in our institutions, and the right of suffrage,
we may be disappointed; as we had been already.
He united in part with my sentiments, but advocated self-defense.

We retired, being fatigued, and found ourselves refreshed by a few hours`' rest.
The profanity of persons in and about the hotel,
made it feel to me a dark and wicked place to be in.
It seemed as if many were utterly reckless of religion, morality and character;
and were given up to their depraved passions and propensities.
To be thrown in such society is very distressing.
The next morning, the 18th, we went on to Mt. Pleasant Boarding School.

18th. I attended the Select Quarterly Meeting;
my mind being encompassed with fears in relation to myself, and the journey before me.
Towards the close of the meeting,
under an apprehension that the defection of some which had
occasioned the acknowledgment of a lack of unity in one branch,
required the exercise of faith and patience, and a willingness to endure suffering,
I thought it right to revive the exhortation of our Lord to His disciples,
"`In your patience possess you your souls,`" and to express
the belief that patience was a necessary lesson to learn;
that it was not only a means of our preservation, but through suffering,
victory and dominion over wrong spirits was often obtained.
Dear William Wood, in his eighty-fifth year,
said he thought he had never been more tempted to take flight in the winter season,
than he had been for some months past.

19th. Seventh-day.
Went to Short Creek Quarterly Meeting.
Two Friends spoke in the ministry;
which I was ready to conclude might be all that was required in that meeting;
but when near time to close the partitions,
I was afraid to leave the meeting without reviving the expressions of our Lord,
"`The life is more than meat, and the body than raiment.`"
In a spiritual sense,
it is of little moment what food the Shepherd and Bishop of
souls appoints to nourish and sustain the spiritual life.
He knows what is best for us; and though He may appoint stripping and poverty,
and deep suffering for his children,
it is our duty and interest to submit with cheerfulness; and in this condition,
wait upon Him until he sees fit to change the dispensation.

The fruit-bearing branches are to be purged,
that they may bring forth more fruit to the praise of the Great Husbandman.
Our dependence is to be individually on the Head of the Church;
every one in his place and allotment in the body waiting upon Him and not on man,
and faithfully acting as He puts forth.
This will not destroy the honor and esteem due to those of greater experience;
but all being baptized by the same Spirit into one body,
they being banded together in the unity and fellowship of the gospel,
will render to each other the love and respect that is due;
and thus would be like the church coming out of the wilderness, fair as the moon,
clear as the sun, and terrible as an army with banners.

On first-day I was at the meeting in the large house; a small company,
among whom I was engaged to labor in the love of the gospel;
especially with some who had chosen their own way;
in order to show them that it is not in man that walks to direct his own steps;
and the difficulties and perplexities in which such involve themselves,
often not being permitted to acquire what they are grasping after; or when they do,
they cannot draw that comfort and happiness which they have
anticipated from their worldly schemes and pursuits.
But a good man`'s steps are ordered of the Lord,
and he has not only the reward of true peace,
but has the true enjoyment of the outward gifts of a beneficent Providence.
The dignity of the true Christian was brought into view,
as a member of the mystical body of Christ; described by John, the beloved disciple,
as a woman clothed with the sun; having the moon under her feet; all terrestrial,
changeable objects in subjection to Christ, the Sun of righteousness.
After sitting down, the pointing to vocal prayer came over me;
and in fear I ventured to bow the knee before the Most High; and to ask of Him,
who knows our infirmities, to grant preservation to the end of our days;
and in his mercy to touch with the finger of his love,
the hearts of some who had wandered from the path of rectitude.
A Friend, who accompanied me to the meeting, remarked, as we walked away,
that William Penn told J. Richardson he thought he might now be cheerful; but I replied,
it is best to keep low and on our guard;
for I was afraid of anything like getting from under the reduced condition I was in.

A Friend kindly offering to take me to Smithfield, we set off in the afternoon,
and next day attended the Monthly Meeting.
Here I was painfully affected with the feeling that some who
had known something of the visitations of Grace,
had not kept their first love; to whom I was led to apply the text given by our Lord,
"`Every one that does evil hates the light, neither comes to the light,
lest his deeds should be reproved; but he that does truth comes to the light,
that his deeds may be made manifest that they are wrought in God.`"
I believe there was ability to reach the states of some,
and to hold up to others the importance of standing
upright in maintaining the testimonies of the gospel:
that a plumb, upright pillar, though small, would bear much weight;
but if it leaned either way, it was likely to fall and bring down what rested upon it.
We dined with our aged friend William Wood, who was kept from meeting by indisposition;
afterwards called on a few Friends, and in one family,
had a tendering communication on the necessity of being redeemed from the world,
and showing our gratitude for the outward blessings conferred upon us,
by dedication to our Heavenly Father;
and thus become qualified to example and train the
children in the nurture and admonition of the Lord.
Third-day morning rode back to Short Creek, and was at their Monthly Meeting;
in which I was silent.

My friend N. H., having agreed to take me in his carriage to some meetings,
we rode to R. C.`'s and lodged.
Next morning attended Plainfield Monthly Meeting; a small company of Friends;
some of whom, I feared, had been more concerned to lay up treasure on earth,
than for the right maintenance of the cause of Truth.
Many who settled in this country when land was low in price, have through industry,
and the advance in the value of it, become comparatively rich; and, it is to be feared,
have not increased in heavenly treasure.

24th. Attending Flushing Monthly Meeting, a pretty large company of Friends,
I was exceedingly stripped, and the fear of being left to myself,
with which I have been unusually tried on this journey, came over me;
but I determined to strive to draw near to the Master,
and to do nothing without his bidding; and after a time, the direction of the prophet,
to bring empty vessels not a few, was presented, with an intimation to rise with it.
By keeping low, to the gentle openings of Divine life,
I was enabled to preach the gospel;
and the power of Truth rose and spread over the meeting.
The humble traveler was encouraged not to be
alarmed with seasons of poverty and emptiness,
when the Master withheld the manifestation of his presence,
and there seemed not the least capacity to attain to any good;
but patiently abiding here.
He will reward these sooner or later, with the smiles of his approbation,
and renew their spiritual strength.
I was humbly thankful for the evidence which He condescended to give,
that He had not forsaken me;
and desired to be more given up to endure whatever He sees proper for my good.
I know that I cannot bear much favor, but often need stripping;
and if I am but kept in the life, and from uttering words without the power,
so that the living may savor it, and the negligent be quickened, it is enough,
with his approbation.

The ground was now covered with snow, the weather cold,
and having nine or ten miles to ride after the meeting,
we did not get off till near four o`'clock, nor reach Smyrna until some time after dark.
The country is very hilly,
and we had some roads to pass over which were dangerous in the dark;
being cut out of the sides of steep and deep precipices;
where a little deviation from the track might plunge us into great ravines.
But by slow, careful driving, we got on safely,
and were glad to shelter ourselves under a Friend`'s roof,
where hospitality was freely bestowed.

25th. Today we had two appointed meetings; the first near Freeport;
in which more Scripture passages were brought to
remembrance than is common in my ministry.
I thought it might be for the instruction of some, and for the reproof of others,
who were active in outward, religious performances, while their hearts and their conduct,
at other times, were inconsistent with the Gospel.
To some of these the doctrine delivered, was close and pointed.
Before leaving the house where we dined, I had a sympathetic communication to the Friend,
who appeared to me, to be an exercised woman and under trial.

We then rode to Guernsey Meeting, appointed at two o`'clock,
which was a large company; mainly plain people.
It was an exercising time;
the great prevalence of a worldly spirit obstructing the stream of consolation.
It seemed as if some had made gold their god; which makes hard work;
such being much out of the reach of instrumental labor.
We rode to J. B.`'s and lodged, and the following morning rose early, and at daybreak,
set off for Stillwater.
At this meeting some ability was received to labor among them in the love of the Gospel.

27th. First-day.
Had a little opportunity with the family where we stayed;
in which the necessity of religious care, in exampling the children,
and laboring to restrain them from wrong things, and to have their wills subjected,
while young, were brought into view.
Rode to Captina Meeting; a little company.
The exhortation of the Apostle to one of the professing churches,
"`Examine yourselves whether you be in the faith; prove your ownselves;
know you not your ownselves, how that Jesus Christ is in you, except you be reprobates?`"
came before me.

I reminded the company, that it is equally necessary for us at this day to do this,
as it was for them.
If we are in the true faith,
Jesus Christ is dwelling and reigning in our hearts by his Spirit,
and we are not in the reprobate state.
Two kinds of faith were brought to view; one of which He is the author,
in which we have dominion and victory over sin.
The other is of our own devising, and leaves man in his sins.
The people were admonished not to rely upon a mere belief in the doctrines of religion;
without coming to Christ, and receiving faith from Him,
that would enable them to overcome temptation and sin.
The meeting was closed with supplication.
In the afternoon, went to J. Edgerton`'s, who was absent on a religious visit,
and spent a short time with his wife and children,
with whom we had a religious opportunity.

29th. Second-day.
Attended Somerset Monthly Meeting.
The injunction of our Lord, "`Labor not for the meat which perishes,
but for that meat which endures unto everlasting life,`" came before me,
and the Master gave ability to search into the states of some who
were in danger of being too much engrossed with a worldly spirit;
and to strengthen the faithful in the discharge of their various duties;
particularly some young and middle-aged Friends;
among whom there appeared to be some talented and lively-spirited individuals.
These were encouraged,
notwithstanding there might not be that dedication in others which they desire,
and travail for, to keep themselves steadfast, immovable,
always abounding in the work of the Lord;
and I believed their labors of love would not be in vain in the Lord;
but would be blessed to themselves, and at least to some of their children.
It was a good meeting; the humbling, solemnizing power of Truth being over us.
While my certificate was before the Monthly Meeting, an elderly Friend remarked,
that "`Though the Friend might go mourning on his way, bearing precious seed,
yet he believed as he was faithful, he would return with joy,
bringing his sheaves with him.`"
I mention these things, only to speak well of the excellent name of the Lord,
and to encourage others to put their trust in Him;
and to labor to keep close to their Master in their lowest seasons,
as well as when He condescends to reign.

We rode to Barnesville, and put up with our kind friends Wm. and E. Green.
After breakfast, a portion of the Holy Scriptures was read; a practice which I believe,
when properly observed, will be beneficial to parents and children.
Though I felt a guard against getting into a habit of
making religious communications on such occasions,
without the fresh putting forth of the Master,
I believed it right to endeavor to encourage the children to yield to the counsel
and restraints which their beloved parents thought proper to extend to them.
They would find it their true interest;
and as they were favored with the visitations of Heavenly Love, and submitted thereto,
it would produce true peace and happiness.

This morning, 29th, N. H. returned home, and E. S. of Stillwater,
agreeing to take me to the southern meetings, we rode six miles to Richland,
and attended an appointed meeting there.
This part of the State, and some of the remaining original log dwellings,
have the appearance of a newly settled country;
while the new and improved houses show the advance of many of
the inhabitants in the comforts and means of living.
The meeting-house was pretty well filled,
and I was engaged to call the attention of those present,
to the privations and hardships endured by those
who commenced the settlement of the country;
the apprehensions they may often have had,
as to getting sufficient food for themselves and their little ones;
the simplicity of their views;
the gratitude they felt for the blessing of Divine Providence upon their labors;
the covenants they were willing to make in the days of their beginnings, to serve Him,
and the desire they then felt to promote the cause of Truth and righteousness.

They were enquired of, how it is with them now?
when prosperity has attended them,
and the means of living and various comforts are increasing.
Do they suffer these things to absorb their thoughts and affections,
and alienate them from the beneficent Creator?
And are their children, who have not known these hardships,
taking wings and fleeing from the convictions and restraints
of Divine Grace into the world and self-gratification?
They were reminded of Jacob`'s setting out in the world;
his first night`'s lodging on the earth with a stone for a pillow;
the vision he had of the angels of God ascending and descending upon the ladder;
so that he said in the morning, "`Surely the Lord is in this place, and I knew it not:
how dreadful is this place; this is none other but the house of God,
and this is the gate of heaven.`"
And he made a covenant with the Lord, saying, "`If God will be with me,
and keep me in the way that I go, and will give me bread to eat and raiment to put on,
so that I come again to my father`'s house in peace, then shall the Lord be my God.`"
He also set up a stone as a testimony of the covenant he made.
When he returned, having become two bands,
notwithstanding the hardships he passed through, he went again to Bethel,
and renewed his covenant; previously calling on his household,
to bring to him their jewels and ornaments, which he hid under the oak in Shechem.
The people were solid, and I hoped some good impressions were made.
We rode after dinner about nine miles to Senecaville, and put up.
In the morning we found the ground covered with snow, and the weather inclement;
so that the prospect of getting on over this hilly
country to a Friend`'s house by the next night,
was discouraging; but with much industry we got to J. M.`'s, at McConnellsville,
on the Muskingum River, a little after dark, thirty-three miles.
It was pleasant to get under the roof of a Friend.

We rested comfortably, and the next morning, fifth-day, Twelfth month 1st,
crossed the river in a horse boat; and over a road mountainous and quite dangerous,
when rendered slippery by snow and ice, we rode to Hopewell Meeting;
the house being well filled.
I felt myself introduced into sympathy with some who, I apprehended,
had secret trials to endure, in this newly settled and somewhat wilderness country;
and I believed it right to hold up to view, that it was a matter of little moment,
where our habitation is, if we are in our right places,
and are sincerely endeavoring to know and do our Lord`'s will.
That though some may be taken where they would not; yet,
resigning themselves to the Lord, and seeking strength of Him to endure their trials,
his love and compassion will be extended to them; and through faithfulness,
they will be made a blessing to their families, and prepared for usefulness to others.
The spring opened slowly,
but in the end the power of Truth tendered the hearts of not a few;
and prayer was offered for the sincere traveler, and those of a sorrowful spirit;
and that the visitations of heavenly love might be extended to the dear young people.
Friends manifested affectionate kindness.

Twelfth month 2nd. Sixth-day.
Attended Stillwater Quarterly Meeting of Ministers and Elders,
held once a year at this place.
The company was small, seven men and six women.
Near the close, I endeavored to hold up the responsibility of the stations we stand in,
and of our example to the flock; and the need of daily exercise,
that we may be kept alive in the Truth; and season, by our spirits,
the minds of the dear youth.
Returned to our lodgings, and passed the afternoon in retirement of spirit.

3rd. Attended the Quarterly Meeting for Discipline; wherein,
though under fear and emptiness, a renewed qualification was unexpectedly furnished,
to preach the gospel of life and salvation through Jesus Christ our Lord;
showing that in order to be made partakers of that salvation which He purchased for us,
we must be in the daily practice of waiting upon Him for the renewal of strength,
by the bread of life and the water of life, which He gives; both for our own growth,
and to fit us for every good work in his cause;
and to perform that worship to Almighty God which is in spirit and in truth.
The rebellious were warned and pleaded with,
to turn their backs upon the corruptions of the world,
and take the yoke of their Redeemer upon them.
The blessedness of the religion of Christ was opened; being inward in its operation;
every one receiving Him in his spiritual appearance in the heart,
may become possessed of it; and, through perseverance,
experience the old man with his deeds to be put off, and the new man put on;
and thus be brought under the flaming sword,
which separates between the precious and the vile, into the paradise of God,
and into the image which Adam was created in.
It was a solid time, and the power of Truth went over the meeting.

The subject of education engaging my mind in the second meeting;
I endeavored to press on the fathers the great necessity for,
and the blessings of a good home education; wherein, with love and firmness,
a steady restraint is kept over the children, with relation to dress, company,
and indulging them in other things not suitable for them.
With the unity of the men and women, I went into the apartment of the latter,
and affectionately enjoined this duty upon the mothers also,
who are more with the children,
and have opportunity of early commencing the regulation of their will and temper; and,
by a religious concern and firmness,
of bringing them up in the nurture and admonition of the Lord.

4th. Rode out to Chesterfield, about seven miles, to their first-day meeting,
which was very large;
some Friends stopping there who were on their way home from the Quarterly Meeting.
I was here led to speak on the subject that we are not our own,
but are bought with a price;
and were to glorify God in our bodies and spirits which are his;
and that we have no right to say we will go into such a city or place, and buy, and sell,
and get gain; but should say, if the Lord will, we will do thus and so.
Many have lost ground, in a spiritual sense,
by becoming unsettled with a speculative spirit;
and without taking counsel of the Divine gift in their own breasts,
have removed into distant parts, with a view of promoting their worldly interests.
Those who go from their former habitation, like Abraham, by faith, under Divine guidance,
have good reason to believe that the blessing of the Lord will go with them;
and if they continue to love and serve Him above all, keeping the world under foot,
they will prosper in the Truth, and with proper industry,
will be blessed in their outward substance.
The effects of a worldly, speculative spirit, were opened;
and some who had got involved in it, by which they had lost their first love,
were affectionately and pressingly entreated once more
to open their hearts to the Lord of life and glory,
who had long knocked for an entrance, and let Him set up his kingdom there,
before it be too late.
All were invited to greater devotion to Him,
that they might be established in righteousness,
and be made more useful in its blessed cause.

Owing to some coming from a distance,
the meeting was kept an unusual time in an unsettled state;
and though when it appeared proper to rise, I had little before me,
the Master was pleased gradually to open one thing after another; and towards the close,
a solemn covering was spread over us; some were tendered and the Lord`'s name was praised.
Rode to Plymouth in the afternoon and lodged.

5th. Here we had an appointed meeting at ten o`'clock; the people filled the house,
yet it was long in settling, and did not prove as satisfactory as some others,
though the way opened to treat on various subjects.
The spirit of supplication was granted, for the poor and lonely of the flock,
and for the preservation of the young people from the snares of a cruel devourer.

6th. Rode back to near Pennsville and lodged.
Yesterday`'s labor left me under fresh feeling of my own inability to do anything.
Without the Master furnishing matter and power for the work,
all our anxiety and past experience cannot open the spring, nor baptize the people.
Holding a meeting today in this place, renewed strong desire to keep near the Shepherd,
and to wait his time to see what to do.
A large company collected, composed of various descriptions of people,
and the prospect was trying.
I thought for some time it would be proper to sit there, an example of silent waiting.
But after much suffering, from the outward and unsettled state of many,
it seemed necessary to rise and open the object of our religious meetings;
not to utter words nor to hear words, but to worship God in spirit and in truth.
The need of stillness of body, as well as of mind; the benefit of self-control;
having our thoughts restrained, and maintaining a patient waiting upon the Lord,
were impressed.
Every one being gathered to the gift of God in themselves,
there would be a united travail to gain ascendency over the roving thoughts;
and to experience the solemnizing presence of the Head of the church,
to arise into dominion in each one, and over all.
The benefit of accustoming children to restraint at home,
and to sit still in our religious meetings,
enforced by the example and authority of parents;
the importance of parents discharging their duties to the children,
and of the children submitting to their parents, were affectionately pressed upon them.
The prodigals were warned of the fearful consequences of evil company,
and pleaded with to come out of it, and return to the path of rectitude,
that they might escape the inevitable results of disobedience and rebellion.
It was a solemn time in the end, wherein the humbling power of Truth was felt,
and I felt clear of the place.

Crossed the Muskingum river, and rode to a private house of entertainment.
On fourth-day the 7th, rose before day, and as soon as we could see to drive we set out,
making slow progress; the road being stiff clay mud, a little frozen;
not travelling more than fifteen miles in six hours.
At a small town called Cumberland, we dined as speedily as we could,
and went on as soon as was proper for the horses;
though it proved a very hard day`'s toil to them;
and about eight o`'clock in the evening got to T. W.`'s. Some parts of the road,
at all times a little unsafe, were rendered quite so, for lack of light,
and the danger of sliding on the side of banks that were slippery.
We also crossed two bridges in the dark,
which our host told us he thought dangerous in the day time;
and had it not been for an obscure moonlight we could
not have travelled during the last two hours.
It was relieving to have a good house to lodge in;
being very weary after traveling fourteen hours;
nearly all that time sitting in the carriage.

On fifth-day morning, before setting out, we had the family collected,
with whom I had a serious opportunity.
Got to Barnesyille about noon,
and my kind friend Wm. Green offered to take me to Sunbury and Somerton.

9th. Sixth-day had an appointed meeting at Sunbury.
A laborious time, without getting much relief; a worldly spirit being in the way,
which is hard to contend with.
Lodged at D. C.`'s, and had a religious opportunity with his family.

10th At an appointed meeting at Somerton, I was kept long in an empty state.
Some presentations passed before me,
but the recollection of the unrelieving result of yesterday`'s labor,
induced fear of moving,
and giving to others what might be altogether designed for instruction to myself.
I waited to see whether the Master would call for any vocal service;
and his language to his immediate followers,
"`Without me you can do nothing,`" revived;
with an intimation to stand up, which I did, and communicated it with fear; adding,
if they could do nothing without Him, neither could we.
I remembered the expression of an experienced minister,
in relation to the early ministers in our Society, that,
"`As it was once a cross to us to speak, though the Lord required it at our hands,
let it never be a cross to us to be silent when He does not.`"
If we are baptized into the likeness of Christ`'s death, we shall be, also,
in the likeness of his resurrection; and those who are baptized into Him,
are baptized into his death.
As we abide here, his time,
we shall know Him to be unto us the resurrection and the life; when He sees fit to arise,
we shall also be raised into newness of life.
Other matter to different states opened,
and was delivered under the humbling hand of the Lord upon me,
and reached the states of some.
It appeared afterwards,
that I was introduced into sympathy with a young
Friend who had been exercised in the ministry.

Dined with two goodly young people;
to whom a word of encouragement was offered before we left,
and then rode to our friend J. Edgerton`'s habitation, where we found that his daughter,
about seventeen years of age, had just died; having been sick about three weeks.

We sat down with the afflicted mother and children;
the father being on a religious visit in New York Yearly Meeting;
and mingled our tears with theirs.
The resignation which Job manifested, was recommended to them, when he said,
"`The Lord gave and the Lord has taken away, blessed be the name of the Lord.`"
Returned to William Green`'s, and lodged; which was a pleasant resting-place to me.

11th. First-day morning, rose before day, and was then taken by W. Green, eighteen miles,
to St. Clairsville; and attended their meeting.
This felt to me to be a dark place;
and after alluding to the sufferings which the righteous experience from the wicked,
I was engaged to point out the darkness and progress of the spirit of infidelity.
There are those, who, sinning against the convictions of the Holy Spirit;
and finding the denunciations of the Scriptures are against them,
endeavor to invalidate their truth, and then deny them;
but they cannot deny the fearful judgments, which God, by his light, shining at times,
into their dark hearts, brings them to feel will be their portion,
if they persist in their evil courses; unless, indeed,
they become so hardened as to deny the existence of a God;
to which dreadful consummation, some appear to be permitted to arrive.
It was a laborious, distressing time; and without affording much relief.
I was afterwards informed that infidelity prevails in this town to a great extent.
I remained here until the next morning, and felt like a prisoner in bonds.

12th. A Friend kindly took me over to Concord;
word having been sent for an appointed meeting there, and at two other places.
The weather having become cold, the roads which were soft the preceding evening,
were now hard frozen and very rough; which made riding very unpleasant.
Here, I saw the benefit of yesterday`'s trial of faith; and being low,
I waited patiently for the Master.
After several presentations passed by, He brought before me the states of some;
to whom I was led to minister in fear.
The life of Truth arose, and we were watered together.

13th. Third-day.
Some snow fell last night, and the road being very rough,
a Friend took me in his sleigh to Harrisville; where we held a meeting by appointment.
Here the promise to the poor and needy, who seek water and find none, was revived;
and the Lord`'s poor, who are panting after the living God,
were encouraged to maintain their labor and travail of spirit,
for the bread and water of life.
Some who were in a worldly spirit were closely spoken to.
How this worldly-mindedness brings poverty on the professors of Christianity,
and distress upon the living members!
When the head of a family devotes himself, almost exclusively, to the love of the world,
it has a prejudicial influence upon the children.
If his companion loves the Truth, it discourages her from being faithful;
and thus may derange everything pertaining to their spiritual journey.

14th. This morning I rose with the persuasion it would be right for me to
return to those places where I had attended the Monthly Meetings,
and hold meetings with the members of the Particular Meetings.
I felt it when I was about leaving Barnesville;
but having sent notices to several places, I was obliged to come away.
In the meeting at St. Clairsville, it came over me with fear that I had been too hasty,
in my desire to waste no time, and get through as soon as practicable;
and I was brought to offer to do whatever the Lord required;
but again hoped it might go off.
It was a trial to go back, lest I might be mistaken;
but mentioning it to some Friends, T. H. and G. P.,
they encouraged me; and N. H. very promptly offered to accompany me.

Went to West Grove, where their little meeting-house was filled with Friends and others.
I was led to bring to view the circumstance of
the original members of our religious Society,
being gathered from the various professions, to sit down in silence,
and wait upon the Lord.
They had been strict in the different ceremonial performances,
and tried the most eminent preachers; but failed to find what their longing souls lacked.

After they were brought to see their own inability, and that of others,
to supply what they ardently sought, they were drawn to wait upon the Lord Jesus Christ,
and found Him in their own hearts.
Thus they were gathered to a teacher that could not be taken from them;
who could speak to their condition,
and give them power over Satan and all his temptations.
They received gifts,
and were prepared to occupy them to the honor of their Lord and Master,
and to the furtherance of others in the way of salvation.
So I was led to preach Christ to the people, as their present Savior;
as well as the one offering for sin, without them;
by whom the Father has forever perfected them that are sanctified,
by the spirit of judgment and of burning.
And I was enabled to pray fervently to God that He would
strengthen the weak hands and confirm the feeble knees;
visit the rebellious with his Day-spring from on high;
gather the children under the yoke of his dear Son,
and increase and preserve a band there,
to stand for his blessed name and cause and glory and honor
were ascribed unto the Lord God and the Lamb forever.
Amen.

15th. Fifth-day.
Rode to Mt. Pleasant.
Attended Short Creek Meeting; in which I was led to show, that,
according to the apostle`'s doctrine,
there is a measure of suffering for each member to fill up for the body`'s sake;
and which, as he is steadfast to his Lord and Master,
will contribute to his own preservation and advancement in the way of holiness.
But it is only those who continue with their Lord in his temptations,
who will witness this preservation;
and for them He will spread a table in the wilderness,
and direct them to sit down to eat; and He will come forth and serve them.
Not those who turn aside from the narrow way; who are allured by a false light,
with which Satan, transformed into the likeness of an angel of light,
seeks to deceive and betray those who grow impatient under suffering.
It was a season of renewed favor, and ability to communicate,
in a gentle and tender manner,
some cautions to those who had long made profession of the Truth; and some of whom,
had been caught with the delusive presentations of the enemy.

Rode back to N. H.`'s; and after dinner, he and I set out for Flushing,
and were heartily received by Jacob Branson,
who did not seem surprised that I was turned back to that place.

16th. Sixth-day.
Notice being sent out in the evening, we had a large meeting, principally of Friends.
I felt empty and destitute, and sat there, like a poor, contemptible creature,
unable to do or say anything.
It lasted so long, that I concluded we should separate in silence;
but at length a little opening presenting, I embraced it;
and though I endeavored to keep under the clothing of Divine love,
some close things were delivered in relation to the
benumbing and deadening influence of a worldly spirit;
that the wedge of gold destroyed more in the christian church,
than perhaps anything else.
It was a laborious and exercising meeting, and proved a trial of my faith.
In the afternoon went to Plainfield.

Seventh-day.
Had an appointed meeting here;
in which my dear Lord and Master renewedly
furnished ability to dip into the states of some;
and to show that as He declared to his disciples,
"`You have not chosen me, but I have chosen you,
and ordained you that you should go and bring forth fruit,
and that your fruit should remain;`"
so it was applicable to every regenerated child in his family,
in their respective measures and places.
He chooses them, as they submit to his heart-changing power;
ordains them for the place He allots to them in his church,
that they should bring forth fruit to his praise, and their own everlasting peace.
Many things were opened pertaining to the christian warfare;
and our hearts were tendered and bowed together before the Lord,
to whom alone belongs the praise of his works.
Rode up to Stillwater in the afternoon.

Many enter upon active life with small means,
and are necessarily obliged to make their needs few.
When a guard is not strictly kept, this frugal habit may produce a contracted mind,
watching at every point to save;
and in this way persons often deprive themselves
of those means of comfort and mental improvement,
which they have within their power;
and which they ought to use to qualify them more fully for usefulness in the world,
and to prepare the minds of their children to receive right impressions and views,
so as to fulfill their duties in civil and religious society.
For lack of a proper cultivation and expansion of mind,
the nobility of man and the glorious design of the
Creator in making him a little lower than the angels,
may be lost sight of.
When parents suffer themselves to be enslaved by this kind of life,
the education of their children is much overlooked;
they sometimes grow up like wild plants,
and either run out into unsuitable company and practices;
or follow the example of the parents in grovelling in the earth.
Thus even if the form of religion is kept, the life and power are lost,
and degeneracy is spread in our religious community.

18th. First-day.
Attended Stillwater meeting; a large, mixed company of people; among whom I had close,
laborious service.
We rode to J. E.`'s, who is still absent on religious service.

19th. Second-day.
Had an appointed meeting at the Ridge.
The impression was early made on my mind,
that much labor had been bestowed on this part of the vineyard,
and that the great Lord of the vineyard was looking for fruits; which was communicated.
While men may be willing to hear the gospel preached,
they may be like the man beholding his natural face in a glass,
who goes his way and straightway forgets what manner of man he is.
Consolation and encouragement were administered to the afflicted; whose trials,
I believed, would be sanctified to them, as they were faithful to their Lord.
The Lord`'s power was in good dominion, and many were much tendered.

Here I parted with some dear Friends in much affection;
for whom I felt strong desire that they might grow in the blessed Truth,
and become valiant for it in their day.
After dinner we rode to our friend Jacob Branson`'s at Flushing.
Having sixteen miles to ride, we rose early next morning,
and an hour before day set off for N. H.`'s. The moon shining very brightly,
we drove with safety, and reached his house between eight and nine o`'clock,
and proceeded to the Monthly Meeting at Short Creek.

20th. Third-day.
In sitting with Friends at Short Creek Monthly Meeting,
I felt myself in a destitute condition; as though my supplies were at an end;
yet after a time, my mind was introduced into exercise,
on account of a spirit that was seeking to lay waste the
doctrine of the necessity of being freed from sin in this life;
and while living in violation of the Divine law,
professing to rely upon the mercy of God in the end.
I was gradually opened on the doctrine of christian redemption,
and enabled to show that Christ gave Himself for our sins;
not to allow man to sin with impunity; but to bring him out of it;
and that it is only as we submit to the sanctification of the Spirit,
that we can have ground to hope that our past transgressions
will be washed away by the blood of the Lamb.
Many passages of Holy Scripture were brought before me,
showing the necessity of being made free from the practice and habits of sin;
and it seemed to me,
there were those who had great need to know the powerful operations of the Divine Word,
like fire, to purge away the corruptions of their hearts;
that they might be brought into acceptance with Him,
who is of purer eyes than to look on iniquity and transgression.

The attempts of some, of the present day,
to destroy our faith in the spiritual appearance of Christ in the heart,
as the hope of glory;
which the Apostle denominates the mystery hid from ages and generations,
but is now made manifest to the saints, were exposed; and this christian doctrine,
which is the glory of the gospel dispensation, was supported by Holy Scripture.
The efforts of some to invalidate other doctrines and
testimonies of the gospel as held by our ancient Friends,
and to tarnish their reputation, were declared against;
and I believed it proper to state that history furnished no evidence,
so far as I was acquainted with it, that those of us,
who had once been in measure subjected by the power of Christ,
and afterwards turned against the principles of the Society,
ever came to anything in a religious sense, while they remained in that opposition;
but I believed that the Lord, in his own way and time, would bring a blast upon such;
especially on those who had received spiritual gifts,
and occupied prominent stations in the Society.
It was very unexpected to be thus led forth, but I believe it was the Lord`'s doings;
and the young people were solemnly warned to beware of all those who seek to weaken
their attachment to our religious Society and its christian principles.

At the close of the meeting, a good old Friend, seeing it was a day of favor,
gave me a fatherly hint, that it was not of man;
and that it is needful to bear in mind that we are nothing.
He said he wanted those who were standing for the Truth, to stand.
I accepted it as an evidence of love, and desire for my preservation,
and wish ever to be kept under those humble, lowly feelings.
Went to the Boarding School in the afternoon, where I found agreeable company.
The society of those who are in heart devoted to the Lord`'s cause,
and desire nothing so much as its prosperity,
is at all times strengthening and consoling; but especially so, when we are separated,
for the work`'s sake, from our beloved nearest connections in life.
It is also heightened by the circumstance that we have so
often to mingle with those who are in the spirit of the world,
or do not feel the interest they ought in the cause of religion.

21st. Fourth-day.
I had a meeting with the scholars in the school-house;
they were affectionately labored with to draw them from everything that defiles;
to enlist under the banner of Christ, that they might witness an establishment in Him,
and be prepared for his service in the church and in the world.
The tendering, solemnizing presence of the Master was with us.
After dinner I took an affectionate leave of our beloved friends, and rode to N. H.`'s,
where I was pleasantly received by him and his wife.

22nd. During the night the weather became very cold,
and the soft snow froze hard on the roads; which made traveling difficult,
over the steep hills in this country; yet the clear, cold atmosphere,
was bracing and animating.
My friend N. H. having informed the Monthly Meeting of
his prospect to accompany me to the Northern Quarters,
and received its unity, we set out early in the morning, and reached Smithfield,
as the people were gathering to a meeting appointed for us.
After a season of humble waiting in poverty of spirit,
the object of our assembly was treated on;
showing that those who are gathered to the gift of God in themselves,
depending upon and waiting for Christ, the great Minister of the Sanctuary,
receive from Him ability to worship the Father in spirit and in truth,
though no vocal ministry be heard.
When the Lord authorizes any to preach the gospel,
it is a savor of life to these living worshippers, who receive power to try words,
as the mouth tastes meat.
The blessings conferred through the Holy Scriptures,
when they are brought to remembrance and applied by the same Spirit that dictated them,
were also spoken of; showing that, though ancient, they are then new.
My words, said Christ, are spirit and they are life;
and when He opens the scriptures to his children,
they convey spirit and life to the soul.
It was a season of consolation and renewing of strength,
and I felt love flow in my heart;
particularly to some of the ancients who had long walked in the Truth.

23rd. The morning was very cold,
and we had some fears of being unable to get through a creek we had to pass,
owing to the ice.
Several on horseback went before, and following the route they pointed out,
we got on safely.
The meeting was very exercising to me.

24th. Seventh-day.
Having heard much said about the difficulty of getting to Salineville, we set out,
the morning being very cold, under apprehensions of not arriving there by night.

When we came to Yellow Creek,
we found the ice was not of sufficient strength to bear the horses;
and with the kind assistance of a person living near,
a passage was broken for them to be led through;
and we run the carriage quickly over on ice strong enough to support it.
We found some parts in the mountain a good deal blocked with drifted snow;
but after getting on a mile or two, the road was more broken and settled,
and to our surprise, we reached Salineville between two and three o`'clock.
We were received and entertained very hospitably by Friends; notice was spread,
and we held a meeting for the few families of Friends, and some others residing here.
It ended to pretty good satisfaction.

On first and second-days we were at Sandy Spring and Augusta,
which were both exercising meetings to me.
There seemed to be those there whom I could not feel as bone of my bone,
and flesh of my flesh; and such was my distress,
that I feared whether I was keeping so close to my Guide as I ought to do,
though I endeavored to do the best I could.
Towards the close of the latter meeting, however, feeling the spirit of supplication,
I prostrated myself before the Lord,
and prayed that He would strengthen his children to follow Him in the way of his leading;
the aged, the young men, and the youth; and I was comforted by the ability thus granted,
to supplicate the Helper of Israel.

The Lord knows how to humble man, and to hide pride from him;
and it was the sincere desire of my heart, this afternoon, as I rode to New Garden,
to be brought low and kept low having a constant fear of getting wrong.
I desired to be enabled to move in child-like obedience to Him;
so as to deliver to the people, in a proper spirit and manner,
whatever He may require of me.
Words will do little without the baptizing power of the Holy Spirit.
May the Lord accompany the word spoken, with his Spirit,
and fasten them where He sees fit, as nails in a sure place; keep the poor,
unworthy creature in the dust, and exalt his own name and power.
After a ride of seven or eight miles, we got to J. J.`'s,
who resides near New Garden meetinghouse;
and were agreeably received and lodged by these ancient Friends.

27th. Third-day.
A large company collected; Friends, separatists and others; so that the house was crowded.
We sat a long time in silence, in which some things were brought before me,
which I thought might be designed for the people;
but though I endeavored to keep a close eye to the Master,
I could not find it was my place to deliver them.
The impression was repeated we are nothing, and can do nothing, without Christ.
After a time, having an intimation to break up the meeting,
I shook hands with my companion.
It was a trial to be made as a sign, but I apprehended it was right,
expectation after words being high; and it is necessary,
when the Head of the church leads into it,
to show by example that we cannot preach when man pleases,
and that true worship may be performed in solemn silence.

Before leaving our lodgings,
it appeared right to hold up to the aged Friends who sat at the head of the meeting,
the responsibility of those who are looked to as watchmen on the walls.
That it is needful, daily to apply, in humility, for Divine wisdom and strength,
to go in and out before the people; and to discriminate between thing and thing;
so that they may give a right judgment for the Lord in his church.
To keep those in their places, who are forward, and if they are not timely checked,
would grow headstrong and high-minded, requires the help of his Spirit.
We rode to a Friend`'s house near New Garden village, who had lately lost her husband;
and were there joined by two other Friends, with whom we spent the evening.

28th. Fourth-day.
Before leaving the house in the morning,
I had a word of consolation for the widow and two of her children;
in which Truth tendered us together;
and she expressed her thankfulness that I had been there to comfort them.
The saying was again realized, "`He that waters shall be watered also himself.`"
We then rode about thirty-two miles to a Friend`'s house, near Kendal, a poor little town.

Fifth-day.
Held a meeting here, in which some were brought into tenderness; it was a small company.
After dining, we rode twenty-one miles, through rain and snow, to a Friend`'s house,
near Marlborough.
Part of the road led through land that I suppose had never been cleared;
the timber was heavy and stood very thick, and it seemed like a wilderness country;
requiring hard labor to remove and destroy the wood.
Our host seemed to be placed in the woods; and though kind and hospitable,
things indicated that they had a pretty rough life.

30th. Sixth-day.
Attended an appointed meeting here, which was laborious;
fearing that the spirit of infidelity was at work in those remote parts,
to destroy the principles of the young people.
I was engaged to revive the conversation between our Lord and his disciples,
relating to the opinions among men concerning Him;
and to show that although the unregenerate could not see the kingdom of God,
it was plain Christ was revealed to the disciples, by the Father,
as the Son of the living God;
and there is no other way by which we can come to the saving knowledge of Him.
By the Holy Spirit that proceeds from the Father and the Son,
Christ reveals Himself in the heart,
and communicates true faith in Himself and in the testimony of the Holy Scriptures.
I labored to put the young people on their guard against the dark,
insidious spirit of unbelief, which was lurking about,
and watching to betray and rob them of their faith;
and they were invited to come to Christ, take his yoke upon them, and learn of Him.
The parents and the watchmen were reminded of their duty in setting a proper example,
and restraining the young people from temptations which surround them.
I hope the meeting ended well, though I did not feel that relief I desired.
After it was over,
I was told there were some present of those who
deny Christ in his outward coming in the flesh,
and others who deny his appearance, by his Spirit, in the heart.
Rode to the house of a Friend, who was formerly a resident in Philadelphia,
where we lodged, and were kindly entertained.

On seventh-day, had a meeting at Lexington, with a small company;
in which we experienced the tendering power of Divine Grace among us.
Proceeded after dining, with some young people, to Damascus.

1843, First month 1st. On first-day morning, we were at Springfield Meeting;
held in a large brick building near the village of Damascus;
in which a numerous company of Friends convene, many of them young.
The message of the Apostle was revived, that "`God is light,
and in Him is no darkness at all;`" and, "`If we walk in the light as He is in the light,
we have fellowship one with another, and the blood of Jesus Christ his Son,
cleanses us from all sin.`"
I felt engaged to labor to bring Friends to an individual examination in this light,
that they might see their true state; for a plain exterior, and a mere profession,
will avail little.
I feared there was a lack of inward exercise,
that the life and power of Truth might be more witnessed among them.
It appeared to me, that through negligence and indifference,
there was a danger of some Friends becoming an ill-savor among others,
and incurring the denunciation, "`I will spew you out of my mouth.`"
I was enabled to discharge my duty honestly among them, and felt peace.
Went home with a Friend, where several persons coming in, two of whom were not members,
but were under affliction from sickness and the loss of a child,
we fell into silence a little before it was time to disperse;
and a word of consolation arose in my heart towards those afflicted persons;
with which they were affected and tendered.

2nd. Rode to Goshen, and held an appointed meeting.
The house was filled, an interment of a young woman having taken place,
and drawn Friends together from other meetings.
She had died after four days`' illness.
Such a sudden transition, from full health to the grave,
brought with it great seriousness.
The people gathered very punctually, and soon settled into solemn stillness.
I was led to show, that in the prosecution of every right concern in the church,
the individual to whom it was communicated,
passes through a baptism into death before he was
prepared for use in the Divine hand in the service,
or for the gathering of others into the church.
By submission to those deaths oft; in which openings of duty are removed out of sight;
man sees his impotence; that without Christ he can do nothing,
and that all wisdom and strength come from Him; and the sincere,
fervent desire of his heart then is, that the Lord`'s will may be done,
and Christ alone be honored and exalted.
The doctrine of redemption, through obedience to the Spirit of Christ was also enforced;
and the meeting closed with solemn supplication to the Father of all our sure mercies,
for his continued care and protection;
and that those who were brought under affliction by his dispensations,
might kiss the rod and Him who has appointed it;
and experience their bereavements and trials sanctified and blessed to them.
The silence and solemnity over the meeting were such
that it seemed difficult to conclude to break it.
Friends parted under feelings of religious weight,
and thankful for the Lord`'s goodness to us.

4th. Attended Salem Meeting.
After a time of silent exercise and waiting upon the Lord,
I was strengthened to bear testimony to the necessity of examining in the light,
whether we are walking in the straight and narrow way.
There are but two gates and two ways laid down in the Scriptures; and in the end,
mankind will be divided into sheep and goats; to one of whom the language will be,
"`Come, you blessed,`" and to the other, "`Go, you cursed.`"
The folly of being swallowed up with the world, was declared against,
and retrenchment and self-denial pressed upon some.
To the little flock who had bitter cups to partake of, and many baptisms to endure,
the language of encouragement was freely held forth.

5th. My valued friend David Fawcett, with whom I became acquainted in North Carolina,
being willing to take me to the remaining meetings, as far as Brownsville, Pennsylvania,
N+++.+++ H. concluded to return; and accordingly set out this morning for home.
We parted in good fellowship, having travelled in much harmony;
he has been a strength to me, and showed true brotherly affection and kindness,
in taking me from place to place.

Not feeling clear of New Garden, I attended the regular meeting there, today.
Here I was engaged to hold up the spiritual nature of Divine worship,
and the necessity of having our dependence withdrawn
from man and placed upon the Lord Jesus Christ alone,
who ministers to the conditions of his people, and leads them in the way of salvation.
Prayer was offered for those who stood as watchmen and judges;
that the spirit of discerning and sound judgment might be granted them;
and that all classes may be favored to see and to keep in their right places,
so that the enemy may get no advantage over them.
It was something of a trial to return to this meeting,
but in the end I believed it was well.

A meeting having been appointed at Middletown, at ten o`'clock, and another at Elk Run,
at two o`'clock, we rose early, on sixth-day morning, the 6th;
and my beloved friend D. Fawcett, took me to the former, eleven miles;
which was a season of favor and instruction;
particularly on the need of keeping out of all self-confidence; of which,
the defection of Peter, who thought that though all men forsook their Lord,
yet would not he, was an impressive example.
Baptisms, oft repeated, are the means our Master uses to humble us; and unless we submit,
and are thereby incited to close watchfulness, we cannot hope for preservation.
The meeting in the afternoon was attended by a
considerable number of persons not of our Society,
who sat quietly attentive to the doctrine delivered,
respecting the appearance of the Grace of God in the heart, which brings salvation.

The spirit of prayer was granted,
to intercede for the gathering of all into the heavenly harmony;
that they may be saved with an everlasting salvation.
Rode to A. H.`'s, a minister, where we had the company of several Friends.

We rode six miles to Carmel, the 7th, and had a meeting at ten o`'clock;
in which I was introduced into sympathy with the afflicted,
to whom consolation was administered; and then my mind was turned to open to others,
the spirituality of this dispensation, and of that baptism, which now saves,
and which was set over all the outward washings,
dippings and sprinklings that man can apply.
Having about eighteen miles to ride to Brighton, we set out,
and rode into the town a little after dark.

8th. Attended their first-day meeting, which was small.
It appeared to be my place to hold up to view
the reduction it was necessary to experience,
that we may enter into and walk in the narrow way that leads to everlasting life.
The need there is of remembering the history and example of our Savior,
whose birth-place was a stable, and his lodging a manger;
who appeared on earth as a servant, and not in the pomp and splendor of a prince.
As we live in his Spirit, we shall not covet grandeur and wealth;
but having food and raiment, we shall be therewith content.
The sad consequences of losing a good condition,
and the necessity of returning to the place of beginning in the days of our espousals,
were pressed upon some;
and those among them who were striving to hold fast their allegiance to Christ,
were exhorted to keep close to Him, and follow on in faithfulness.
Some, I hope, were comforted, and others warned of the day of recompense.
The weather having been wet, and the traveling being made difficult,
we concluded to remain until morning,
as we could not reach Westland short of two days`' riding.
In the morning we took leave of our friends, and proceeded on our journey.

9th. Second-day.
Rode up the margin of the Ohio River, which was very high and covered with floating ice.
Our sensations in passing through Rapp`'s settlement were gloomy.
The people settled on it, appearing more like vassals, than free persons;
being under his control, and dependent on him for everything they require.
To me it seemed dark and distressing;
not calculated to promote their present or future best interests.

In the afternoon, crossed the Allegheny River, into Pittsburg, then the Monongahela,
and ascended a mountainous hill, on which we met a stage.
This started our horses to running back, placing us in a fearful position;
but the stage horses being driven very fast,
passed us so soon that we got ours to move on up the hill,
and thus saved us from being overturned.
We went on about six miles from Pittsburg, supped and lodged,
and in the morning rode about twenty-three miles, to a Friend`'s house,
where we dined in the afternoon.
The roads were now getting deep, with the rain falling,
and the frost coming out of the ground, and, the country being mountainous,
traveling was laborious and disagreeable.
Pennsylvania is remarkable for abundance of water,
and the great number of small and large streams.
They were pouring down the sides of the great hills, and crossing our road frequently,
and the rapidity with which they rose, from the gentle rain, was quite striking;
the frost not being altogether out, prevented the water from settling away.
We proceeded to J. F.`'s, leaving word where we had stopped,
of our intention of being at Pike Run Meeting on fifth-day.

11th. Fourth-day.
Attended Westland Meeting, and contrary to my expectation,
I was raised out of poverty and weakness, to preach the Gospel to those assembled;
opening the deceptive workings of the grand
enemy to allure man into the love of the world,
and trusting to the form of godliness,
while in life and conduct he was denying the power thereof.
I think Divine help was remarkably extended,
enabling me to enter into the states of some; the dangers to which they were exposed,
and to labor with them in the tendering restoring love of the Gospel.
The spirit of prayer was also granted, under which,
supplication was offered to the Father of mercies,
that He would renew his visitations to some,
and revive the work of religion in their hearts in the midst of the years.
That He would mercifully regard the young and inexperienced, defend them from temptation,
and in the precious blood of the Lamb, wash away all our sins and transgressions;
that so we may be prepared to stand with acceptance before Him, and sing his praise,
world without end, Amen.
It was a season of humiliation and Divine favor;
for which grateful thanks and acknowledgments are due to our Heavenly Father,
and his dear Son our Lord Jesus Christ, through the Holy Spirit.

Went to our beloved afflicted friend Mildred Ratcliff`'s; dined and lodged.
She expressed her gladness at seeing me,
and frequently spoke of the goodness of her Lord and Master;
with whom she said she had precious communion when left alone;
though at other times deeply mourning over the state of the church.
She said she loved the Truth and its blessed cause,
and believed that the Lord would preserve a faithful remnant,
who would be enabled to maintain its doctrines and its testimonies.
These would not be permitted to fall to the ground;
but the Lord would continue to raise up those whom He would qualify to support them,
as in the days of our early Friends, and to bear a plain testimony against wrong things.
She was particularly strong in her disapprobation of
Friends sleeping in our meetings for Divine worship;
on account of which, she said, some thought she had been too severe;
but she was decided that such sleeping Quakers were
stumbling blocks to honest inquirers after the truth,
and that they were denying the faith that would give the victory over all such weakness.

Some Friends came in the evening, which we passed in pleasant, and, I hope,
instructive conversation; principally on the state of our religious Society;
both in relation to our besetting difficulties,
and also on the cheering evidences without and within,
that the gracious Head of the church has not forsaken us;
but is visiting our dear young people, and giving gifts to sons and daughters,
for his glory, and theirs and the church`'s benefit.

On the following morning I took an affectionate leave of our dear friend,
in which she expressed her motherly desire for my preservation,
and that the blaster might be with me; which she said she believed would be the case,
as He is faithfully and humbly sought unto.

Went to Pike Run Meeting; in which I was engaged to labor with some,
who are in danger of settling upon their lees; and having lost the true faith,
of saying the Lord will not do good, neither will He do evil.
And to warn them of the day that will overtake all,
in which He will search Jerusalem with candles; and every man`'s foundation will be tried.
Others were warned against denying the Lord Jesus,
in his outward appearance in the prepared body,
or in his spiritual appearance in the heart.
I was also engaged in close and earnest pleading
with some to receive Him into their hearts,
before the awful period arrives when the door of mercy will be shut.
After the meeting broke up, there was a profligate deist pointed out to me.
Though I labored faithfully and felt peace,
yet I did not partake of such relief and comfort as I did the day before.
J+++.+++ F. brought me to a Friend`'s house near Brownsville, where I lodged.

13th. Sixth-day.
Had an appointed meeting here, in which the necessity of perseverance was held forth;
that having known the arm of the Lord extended for their help,
under the storms which assailed them in years past,
they might be prepared to detect the enemy in his future stratagems;
wherein he was seeking to draw some to deny the
spiritual appearance of Christ in the heart;
and thus strike a blow at vital religion, which is found only there.
Ability was measurably furnished to caution Friends of these stratagems.

Set off this afternoon to go to Sandy Spring Meeting, in the edge of Virginia.
We lodged about six miles out from Brownsville, and rising early on seventh-day morning,
set out to cross the mountains; the road being extremely rough,
and a thin covering of snow on the ground; which continued falling at times,
through most of the day.
It was a dreary, cold ride, but we were received with great kindness by the Friends.
The meeting-house was pretty well filled, and there appeared some opening for service;
but many who came,
seemed not to understand the nature and importance of a religious life.
I was fearful that all that was said, made little impression upon many.

After dinner a young man kindly offered to take
me to the turnpike to meet the stage going east,
which was effected in a small one-horse sleigh.
The stage coming on about ten o`'clock, I rode all night,
and reached Cumberland about sunrise.
There I took the train for Baltimore, which we reached before six o`'clock.
Lodged in the city, and the next morning took the line for Philadelphia;
and on third-day, arrived at my own home;
rejoiced to be restored to my beloved wife and children, in peace and safety.

17th. I arrived at my comfortable home,
and was through the tender mercy and loving kindness of my gracious Lord and Master,
permitted to find my beloved wife and children in good health,
and to join them with feelings of peace and tranquillity,
after an absence of rather more than two months.
Oh, how many favors, temporal and spiritual, we have to be thankful and accountable for!
May we not only render Him the return of gratitude and praise,
but of increased dedication to his will and service in the world and in the church.

20th. Was held a special Meeting for Sufferings,
in which a memorial to the Legislature of Pennsylvania,
asking for the passage of a law to defend the free
colored population of the State from being kidnapped,
was adopted; and four Friends appointed to attend that body with it.
When the business was chiefly finished, our friend Thomas Kite,
adverted to the publication of a book written by a Dr. Ash of Bristol, England,
professedly to expose and refute certain alleged errors in Robert Barclay`'s Apology.
The circumstance took much hold of the meeting, and brought on a lively discussion;
in which Friends animadverted freely upon the work,
and other attempts made of latter time,
to turn the Society away from the faith which it has always maintained, as a body,
from its rise.
There are parts of the Society in this country,
where young persons are much exposed to imposition,
both from the attempts to undermine our peculiar testimonies; and also from the busy,
insidious efforts of persons, holding the principles of infidelity.
As these things were opened, Friends became invested with the conviction,
that if we expected to maintain the character
and ground we have held as a religious Society,
it would be necessary to bear an unequivocal testimony against all
such attempts to turn away the members from our Christian faith;
and for the information and encouragement of the younger Friends,
to draw up a declaration of some of the doctrines and
testimonies needful to be revived at this time.
A committee of eight or nine Friends was accordingly appointed, with great unanimity,
for the purpose.
When the committee met, the same unity in the concern was felt,
and the members encouraged one another in the work; four Friends were separated,
to prepare such a testimony.

At the Meeting for Sufferings in the Third month,
a brief history of the rise and progress of the abolition of slavery,
and the buying and selling slaves within the limits of the Society, was read.
It was compiled chiefly of selected documents and records of meetings;
connected by observations and statements of facts, drawn from other sources,
and was satisfactory to the meeting.

The committee appointed for the service, in the First month, had prepared,
and now produced, a document, entitled,
"`The Ancient Testimony of the Religious Society of Friends, commonly called Quakers,
respecting some of their Christian doctrines and practices.`"
At the Meeting for Sufferings in the Fourth month, it was read, deliberately considered,
and adopted, without a dissenting voice.
After the many trials which had been passed through,
in bearing our testimony against the innovations
attempted upon the doctrines of the Society,
it afforded a degree of comfort,
that we were enabled to unite so harmoniously in
a testimony so decidedly against these errors,
and supporting the doctrines of the gospel as held by Friends.

Fourth month 15th. Was held our Yearly Meeting of Ministers and Elders;
in which we felt the great change which has been annually taking place within it;
so large a number of substantial ministers and elders have been removed by death;
while but few, especially ministers, are coming forward to fill their places.
Friends were brought under a lively concern, for a more harmonious labor among us.

17th. Commenced the Yearly Meeting for business,
throughout which there appeared a satisfactory unity.
The Address, prepared by the Meeting for Sufferings, on our doctrines,
was very feelingly approbated, and directed to be printed.
It was a solid and comfortable meeting.
It was the Lord`'s doings,
and doubtless a special favor from Him to encourage his
children to faithfulness in his cause,
and to show to others that He has not deserted us,
however unworthy we are of the least of all his mercies.

Fifth month 3rd and 4th. My wife and myself attended Abington Quarterly Meeting;
in which the Lord furnished fresh ability to preach his gospel,
and to put up prayer to Him on behalf of some whose faith, at times, was ready to fail.
It was a solid, good meeting; in which not a few hearts were contrited,
and returned thanks to Him.

23rd. For several months past, I have been led through a wilderness state,
in which but little clear shining of the light
of the Sun of Righteousness has been dispensed.
Fear of the qualification to labor in the cause of Christ, being taken away,
has been my portion; under which I have desired to keep patient,
and to know the refinement necessary for a follower of Him.

The low state of our Society, in many respects and in many parts, has been much upon me;
with apprehensions that some who have been visited,
are not coming forward in the strength and devotedness that they ought;
while others seem more disposed to promote the
assimilating of the members of our Society with others,
than to build it up on the faith which the first members were built upon.
These things are discouraging;
and yet there are not a few among us who are united in the fellowship of suffering;
and are praying and watching for the consolation of Israel.
If these can do no more, they may, through faithfulness, deliver their own souls;
and others, seeing their steadfastness,
may be drawn to follow them as they follow Christ.
Today I attended the Northern District Monthly Meeting.
At the close of the last meeting a word of exhortation sprung in my heart,
to encourage Friends to daily, inward travail of soul;
that they may be kept alive in the Truth.
It was this that made us, in the beginning, a living people,
and in which the members were made helpful to one another, and quick,
in discerning the devices of the enemy, who is always seeking our destruction,
both individually and as a body.
