== Chapter XV

1843--1844

Religious visit to New York Yearly Meeting--Origin and Intention of
the Book Store in Philadelphia--Visits to Various Meetings within his
own Yearly Meeting--Religious visit to Indiana Yearly Meeting,
and some of its Meetings--Visits to Friends`' Schools--
Yearly Meeting--The Value of a Religious Life.

1843, Fifth month.
I obtained a minute from the Monthly Meeting, and attended New York Yearly Meeting,
throughout most of which I found it my place to keep under a silent travail of spirit,
for my own preservation,
and that I might be ready to receive the intimations of religious
duty whenever it pleased the Lord to put me forth in his service.
On first-day morning, in the large meeting room,
after my friend Thomas Kite had been engaged in the ministry,
my way appeared to open to rise with the call of the prophet Jeremiah,
"`Pass over the isles of Chittim, and see; send unto Kedar, and consider diligently,
and see if there be such a thing: Has a nation changed their gods, which are yet no gods?
but my people have changed their glory for that which does not profit.
Be astonished, O you heavens, at this, and be horribly afraid, be very desolate,
says the Lord.
For my people have committed two evils; they have forsaken me,
the Fountain of living waters, and hewed them out cisterns, broken cisterns,
that can hold no water.`"
I was led to show that, like the children of Israel,
many among us have forsaken the Truth; and where they have done this,
they have attempted in various instances to invent
substitutes for obedience to the Divine will,
inwardly made known,
and taking up the cross daily and following Christ in the path of self-denial.
It was through the immediate revelation of the Spirit of God,
that his disciples could know and declare Him to be the Christ,
the Son of the living God; and it is only by the manifestation of the same Spirit,
that any now can have true and saving faith in Him.
The indispensable necessity of receiving Christ in the heart,
that we may know Him for ourselves to save us from our sins,
and the danger of losing that precious state, after we have known it,
was opened to the people; and his humbling, solemnizing power was felt among us.

We dined in company with several Friends, with whom I was drawn into conversation,
on various points of doctrine and practice;
and had fears excited that there is danger of some
losing that firm attachment to our ancient testimonies,
which ought to characterize members, holding important stations in our Society;
and a departure from which, by any,
is proof that the sure rock and foundation is slidden from.

In the course of the deliberations of the Yearly Meeting,
it was to be apprehended that there is danger of the habit of too easily speaking,
and therefore too frequently, in these meetings;
where religious weight ought always to attend the consideration of subjects,
involving the interests of the Society.
The indispensable need of being gathered to the gift of God in the heart,
was held up to view; that every one might know his place and duty,
and receive from the blessed Head of the Church, wisdom, and knowledge,
and strength to perform it in his fear, and to his honor and the benefit of the body.
Having a gentle intimation that it might be right for me to visit the women`'s meeting,
and my friend Thomas Kite opening to the meeting a concern for the same service,
we were set at liberty;
after I had informed Friends that my mind had been also turned that way.

In walking up to their apartment I felt exceedingly stripped,
and thoughtful whether I had sufficient commission for the proposed visit;
which led me to look steadily towards the Master,
desiring I might be preserved from acting in any way unbidden.
Thomas Kite pretty soon rose, and mentioned various instances recorded in the Scriptures,
of the use which the Lord had made of women in his cause and service;
and to whom He revealed Himself,
and deputed them to announce the glad tidings of the Gospel.

After he had been sometime engaged and had taken his seat,
there seemed in me the stirrings of the Holy Spirit, and I was led,
in unison with his concern, to encourage those upon whom the weight of the ark, at times,
rested heavily, to keep to their religious exercises,
even where their number was few in a place;
relying upon and being faithful to their Lord;
and He would bless them and their steadfastness, to the help of others.
The younger part were also invited to enlist under the banner of Christ Jesus,
the Captain of salvation, that they might be prepared for service and usefulness here,
and for an inheritance hereafter, amongst the saints in light.
I came away thankful for the renewed evidence that the Lord was gracious;
still qualifying us, unworthy as we are, for his work, and going before,
preparing the hearts of some, like Lydia of old, to receive the word preached.

We had several religious opportunities in families,
where pretty large companies of young and old were collected: and, I believe,
to the contriting of their spirits, and strengthening their desires and resolutions,
to follow on to know the Lord with greater dedication.
It was a week of close exercise to me, in which I felt myself in bonds,
and in fear of doing anything that would hurt any one, or the precious cause;
and preservation, I believe, was mercifully granted.
I returned in peace, well satisfied that I had given up to the service.

Seventh month 22nd. Luring the past week,
the Book Committee of the Meeting for Sufferings,
has been engaged in getting printed the doctrinal
address issued by our late Yearly Meeting.
Many of the more elderly Friends in this city,
upon whom the care of such matters formerly rested, having been removed by death,
the putting forth such a document brought feelings of unusual responsibility over us;
lest anything might escape our notice that the opponents of our doctrines could cavil at.
There is a spirit working in different parts, and under various pretexts,
which is at enmity with the cross of Christ,
and the simple self-denying religion into which the Lord led Friends, in the beginning,
and which is the strait and narrow way, laid down in the New Testament,
as that which leads to everlasting life.

29th. Today in conversation with my friend Samuel Bettle, Sr., upon some of the concerns,
and the present state of our religious Society, he informed me,
that at their late Monthly Meeting,
he had mentioned the subject of erecting a suitable building on the
northeast corner of the Arch Street meeting-house ground,
for the purpose of depositing Friend`'s books for sale, and for gratuitous distribution;
as a depository of religious tracts, setting forth Friend`'s principles;
as an office for the Treasurer of West-town Boarding School;
and an office for a Recording Clerk of the Minutes and Epistles of the Yearly Meeting,
and Meeting for Sufferings.
Such a building has been long needed, and if properly used,
and the various concerns conducted with a single eye to the cause of Christ,
and the spread and support of our religious principles,
and the real welfare of the rising generation,
it may prove a blessing to our religious Society.
May those who come after us, if the depository is instituted,
be preserved in lowliness and humility of mind; seeking for Divine counsel,
that they may be kept from introducing any works tending to impair a sure
and full belief of all the doctrines and testimonies of the gospel,
as laid down by George Fox, Robert Barclay, William Penn, Isaac Penington,
George Whitehead, and others of our primitive Friends.
The design is to spread our own principles as they have
always been held and published by this Yearly Meeting;
and not to give publicity or circulation to any other.

Eighth month 19th. Last third-day, the 15th, I felt my mind turned to the North Meeting,
where I accordingly went.
A testimony was delivered to some, who, when they saw their state,
felt they had need to confess their sins and implore forgiveness,
if they expected to partake of the benefits of the mediation and atonement of Him,
who is the propitiation for the sins of the whole world,
and our holy Advocate with the Father.
They were encouraged,
not to cast away their hope in the mercy and long forbearance of a gracious Creator;
for under these visitations,
there was ground to believe that He would forgive their transgressions,
and blot them out, and enable them to forsake their wrong ways, and serve Him faithfully.
In the afternoon of the 16th, I rode out to my brother Joseph`'s, at Springfield,
where my wife and family had gone a few days before.
To their meeting, on fifth-day, I went in emptiness.

My mind was, however, led to look at the state of some dear children,
who were loving and serving their Lord and Master,
and whom He had made witnesses for Him in their private daily walks,
as salt in the earth, and reprovers of the wrong courses of others.
These I was led to salute in the renewed springing of the love of the Gospel;
also to open to the disobedient, their ways,
which are accompanied with convictions of being wrong,
and entirely fail to satisfy the secret longings of the immortal soul;
and to plead with them to turn to the Lord, when He again visits by his good Spirit,
and shows them the consequences of their unfaithfulness, and rebellion.
My dear wife closed the meeting in fervent prayer for them,
and for some others more advanced in years;
and we had cause to thank our compassionate Heavenly Father,
for his goodness and condescension to his poor unworthy creatures,
and to acknowledge that it all came from his bountiful hand.
The difference between a dry and barren state when there is no opening,
and being favored with the gentle presentations of the Holy Spirit,
raised a hope that the Lord had not forsaken, and that it was his work,
in which He was engaging me, for the help of others,
and to fill up my own measure of suffering and service.

21st. Rode with others to Concord,
and attended the Quarterly Meeting of Ministers and Elders.
Here, deep seemed to call unto deep, at the noise of the waterspouts.
To hear Friends from different parts utter the same language,
respecting the poverty and trial they passed through, was encouraging,
and confirming that the path which the Lord`'s children walk in,
is much the same everywhere; and the language they use in describing their pilgrimage,
very similar.
Through Divine goodness,
we were enabled to comfort one another in true love and fellowship,
and I believe our unity in the blessed Truth was strengthened.

Notwithstanding the dullness of the weather, the next day, many collected;
and ability was granted to hand a word of encouragement to them, to hold on their way,
in their respective allotments, with a single eye to their Divine Master;
who will help and cause them to grow, in his strength, from stature to stature;
though but few may be near to take them by the hand,
and to cheer them on their heavenly journey.
"`The righteous holds on his way,
and he that has clean hands shall be stronger and stronger.`"
The dear children were tenderly counseled,
and invited to take the yoke of the Lord upon them,
and come up in the footsteps of his flock,
and they would be fitted for service in his church;
and to hold up to the nations of the earth, the standard of peace and righteousness.
It was a good day.

So much rain fell,
that we apprehended there would be some difficulty in fording Chester Creek;
the bridges having been nearly all carried away,
by a great flood which occurred about three weeks before; destroying, it is said,
more than fifty bridges; and several mills, houses and dams in Delaware County.
But we got safely to Springfield.

23rd. My wife and I rode into Philadelphia, and attended our Monthly Meeting;
by which I was liberated to go to Indiana Yearly Meeting;
having had the prospect several months resting upon my mind.
Returned to Springfield in the evening.

24th. Went with my brother Joel to Samuel Swain`'s at London Grove, where we lodged;
and the next day attended the Western Quarterly Meeting.
It was larger than I had seen it, since the separation; and I trust was owned,
in some good degree, by the ever-merciful Shepherd of Israel;
though the number of faithful laborers is much reduced here,
as it is in most other places.
Still there is ground to hope,
that a succession of young men and women will come forward,
so that the doctrines and testimonies held by Friends will not be lost, in this place.

The principles of unbelief have taken deep hold of many,
who were once in membership with us in our Society, in this part of the country;
and it is no marvel, if our religious Society should have a long struggle,
before it rises above the effects of this mournful defection.
We reached West-town School, about eight o`'clock that evening;
and the following morning rode to Springfield.

Ninth month 13th. I have seldom, in my own meeting,
been clothed with more fervent and affectionate solicitude for my fellow professors,
than on this occasion; and the gathering, restoring spirit of our Holy High Priest,
seemed to be present,
to heal and revive some who have long neglected the work of their own salvation.
In the prospect of soon leaving home, I was glad to part with my beloved friends,
with such a covering of heavenly good.
The praise and the glory belong to the Lord our God, to whom with his dear Son,
the Lamb immaculate, be ascribed all praise, and honor and thanksgiving,
world without end.
Amen.

15th. In the afternoon I took an affectionate leave of my dear wife and children,
and with Henry Cope for my companion, and Thomas Kite,
went on board the steamboat for Baltimore;
where we arrived about one o`'clock in the morning.
We stayed on board until about five o`'clock, A. M.,
sleeping on the seats as well as we could.
Breakfasted, and took the cars for Cumberland, at the foot of the Allegheny Mountains.
A ride of one hundred and seventy-eight miles, though on a railroad,
occasions some fatigue; but this mode of traveling is so expeditious and comfortable,
that it may be ranked among the great discoveries and
improvements of this day of novelty and invention.
We had a fine, extended view of mountain and water scenery,
the road being mostly located on the banks of the Patapsco and Potomac Rivers;
and were it not for the blighting influence of the unrighteous system of slavery,
many parts of the country would exhibit proofs of high culture,
and have better buildings than are seen in some places.

At Cumberland, where we arrived between five and six o`'clock,
we were put into one of the mail coaches, heavily laden;
and having nine passengers inside, and the weather warm, riding was irksome;
but traveling day and night, we got safely into Wheeling on first-day evening.
It is undesirable to be on the road during the first day of the week,
but owing to uncertainty of meeting a steamboat at this place,
it appeared unsafe to tarry at Baltimore;
as we wished to be at the week-day meeting in Cincinnati.
A night`'s rest at Wheeling refreshed us much; and engaging our passage in a steamboat,
early in the morning, we left about eleven o`'clock.
The company behaved respectfully; and some manifesting a disposition to converse,
it afforded an opportunity to explain the views of Friends,
on slavery and other subjects.
The passage was prolonged one day, by the dense fogs on the river;
which made it necessary to come to, and fasten to the trees, near the water edge,
every night.
I often felt little capacity for conversation, and was shut up in silence, at times:
being burdened with the light, and frothy and worldly spirits of most of the company.
But I believed inward, mental suffering,
in steady watchfulness over our words and actions,
is not only profitable to our own preservation and growth,
but it has a restraining influence over others,
and may lead some to examine their own hearts, and strengthen the right-minded,
to hold on in the right way.

After a tedious passage of three days, we landed on fifth-day morning, the 21st,
at Cincinnati, and attended the regular meeting; which was owned by the Great Master,
qualifying to labor amongst them in the love of the gospel;
to show some that they had left their first love, and were gone into the earth;
and some were getting into the air.
I thought I perceived the advantage it was, to have been preserved, on the passage,
under suffering with the oppressed seed in the hearts of the earthly,
and airy people on board; and I was led affectionately to persuade Friends,
to examine themselves where they were, and to turn again to the Lord:
and those who sincerely loved the Truth, were encouraged to greater dedication.
The meeting ended under feelings of solemnity; Thomas Kite closing it with prayer.

Sixth-day.
Called upon our aged and valued friend Ann Shipley,
with whom we spent some time in pleasant conversation; and just before parting,
we fell into silence;
in which my mind was tenderly and affectionately drawn to our dear friend,
as to a mother in the Truth; and the language of comfort,
and promise of the blessed reward at the end of the race, was imparted;
to our mutual refreshing.
In the afternoon, visited a woman Friend, in the prime of life,
lately acknowledged a minister, to whom counsel was handed,
in relation to the occupancy of so important a gift.

23rd. We rose between two and three o`'clock;
and about four o`'clock left the city in a stage,
on our way to Richmond distance sixty-five miles; which we reached at dusk,
and were kindly received by our friend E. C. and wife,
where we were hospitably entertained during the sittings of the Yearly Meeting,
and had the company of many interesting Friends.

24th. First-day morning.
Felt my mind drawn to Milford Meeting; where we had hard labor for a season,
to come to any sense of Divine life, stirring among them;
but the Good Shepherd opened the spring a little, and qualified to minister to them;
with which my companions afterwards expressed their satisfaction.
After dining, we returned to Richmond.

Second-day, attended the Meeting for Sufferings.
Third-day, the Meeting of Ministers and Elders; and on fourth-day,
a meeting for public worship; in which I was engaged in preaching the gospel of Christ,
to a very large congregation; showing the need of perseverance to the end,
in order to gain the crown.

The young people were invited to come to Christ and learn of Him.
In the afternoon, at the Meeting of Ministers and Elders,
it appeared right to open the nature of gospel ministry; showing that they who minister,
are to speak as those, through whom the Lord condescends to speak to the people;
also alluding to the necessity of not meeting the desire of the people to hear,
nor our own, to utter, words.
It was the concern of our early Friends,
that as it was a great cross to them in the beginning of their ministry to speak,
it might not become one to be silent, when they had nothing in command to say.

The Meeting for Sufferings having before it an essay,
designed as an address to other christian professors, on slavery,
and not feeling quite satisfied with it, referred it back to the committee for revision;
and requested the strangers to sit with them; which we did,
and aided them in remodeling it; and the meeting adopted it as altered.
Sat fifth, sixth and seventh days of the Yearly Meeting much in silence.

First-day, a large concourse of people came together.
The young people were unsettled; coming into the meeting at a late hour,
and many going out very soon.
This is an evidence of defective education; for were they properly instructed,
they could not easily disturb a religious meeting;
nor would they feel the same inclination to be going out, were their minds impressed,
as they ought to be, with the solemnity of Divine worship.

In the forenoon I was silent, other Friends being engaged in the ministry;
but in the afternoon I was led to call the attention of Friends to the afflictions,
permitted to overtake the Society;
and to consider how far our unfaithfulness had brought them upon us.
To examine how far the world and its attractions had absorbed the mind;
so that some may have forgotten the duties they owe to their Almighty Creator;
their spiritual eye had become dim,
and they unable to sound an alarm at the approach of the enemy,
because they had lost their discernment.

The young people were also spoken to, on their conduct;
and all classes invited to draw near to the Lord Almighty;
that they might be clothed with the spirit of prayer,
to cry unto Him for help in this day of trial; and come up faithfully,
in their generation, in showing forth the excellency of the religion we profess,
and laboring in its blessed cause.
I hope the Spirit of Him who seeks to save that which is lost,
and to preserve those who are in danger, was the clothing of my mind;
and that his power was exalted over disorderly walkers;
and the rightly-exercised comforted.

Tenth month 2nd. Second-day.
Much business was done.
The address prepared by the Meeting for Sufferings of this Yearly Meeting,
on the subject of slavery, was read and approved;
also an interesting memorial concerning Joseph Hunt, formerly of Evesham, New Jersey;
who deceased in the thirty-second year of his age.
The latter gives a very instructive view of his religious growth,
and his excellent example, and pertinent counsel to his family:
a large number of these papers were directed to be printed.

Third-day.
After the business was finished, it seemed incumbent upon me,
to endeavor to open a little of the concern I felt, particularly for the young men,
in these times of commotion and division; when many spirits are abroad in the world,
seeking to unsettle their minds, and draw them from that inward abiding with Christ,
the Captain of salvation; wherein only we can be preserved,
receive a knowledge of our place and service in the church;
and wisdom to do what He requires of us.
The danger of listening to those, who would spoil them,
through philosophy and vain deceit; and of being led astray from Christ,
the Sun of Righteousness; so as to become like wandering stars,
was plainly held out to them.
The faithful laborers, striving to stem the current of disaffection,
were encouraged to maintain their ground, with christian firmness;
and the young men invited to deep indwelling at the feet of Jesus;
that they may be prepared to bear their share of the weight of the ark,
and stand nobly in their day for the cause of Christ.
Many Friends, after the meeting was over, expressed their unity with our labors,
and the hope that they would prove useful.
We passed the remainder of the day at E. C.`'s,
where a large number called to take an affectionate leave of us.

Fourth-day.
Our kind friend E. C. sent H. Cope and myself to Newport, ten miles north of Richmond,
where a Friend took us to Cherry Grove Meeting, about seven miles further.
It was a heavy time, the spring of the ministry not rising freely.

Fifth-day morning, attended New Garden Meeting.
In the afternoon, an appointed meeting held at Newport;
which was a mixed company of Friends and the town people.
At parting with our beloved friend William Hobbs, he expressed, in a fatherly,
discreet manner, his satisfaction with my visit, and labors among them,
which was a strength to me.

Attended an appointed meeting at Dover, about six miles from New Garden,
and then rode to Richmond.

Tenth month 7th. Rose early to be ready for the stage,
but did not get off until some time after daylight; the weather was wet and heavy,
which made traveling unpleasant.
We passed through Easton; from there to Hamilton, a beautifully situated village;
the Miami running through it, and on one side a canal, coming from Cincinnati,
through a body of rich productive land;
where we hear that large crops of corn are raised.
We reached Cincinnati about eight o`'clock.

8th. First-day.
Attended their morning meeting;
in which I was enabled to set forth the nature of the christian religion;
which changes the heart, and constrains us, as one of the first duties,
to do justly in the sight of our great Creator; not as men pleasers, or eye servants,
but in the Lord`'s fear, who searches the heart.
This vital, practical religion, regulates the natural passions and propensities;
brings them into subjection, and qualifies man in every station in life,
to glorify God in his body and in his spirit, which are his.
In its nature and operation, it is plain and simple;
consisting in obedience to the Divine will, as made known in the heart.
As man, through the power of Divine Grace, glorifies his Maker,
he works out his own salvation, with fear and trembling, before Him;
and at the same time, is fitted for the Lord`'s service in the world and in the church.
Thomas Kite ended the meeting with prayer.

Feeling a concern to see the members alone,
I proposed they should convene in the afternoon; which was agreed to.
The number now composing this meeting, we were informed,
is about one hundred males and one hundred and fifty females.
A pretty large company collected, principally young persons;
and I had an opportunity to show, that separated as they are from the body of Friends,
some of them coming from places where they had had many advantages,
they have increasing need to watch and pray,
lest they enter into the temptations around them.
Habits or principles, not congenial with the purity and self-denial of the gospel,
getting among them, may easily spread;
unless those who know the voice of the true Shepherd, keep a firm ground,
in steadily opposing wrong things.
Faithfulness is not only of great moment to themselves, but may also be so,
to the rising city where they dwell.
They were affectionately entreated to yield to the
tendering convictions of the Spirit of Christ,
which some of them had known to operate powerfully on the heart;
and lay aside those things which He required them to give up;
that He may fashion them for his use;
and they would receive the consolations of his peace, to reward them for obedience.
Parents were impressively exhorted to watch over the children committed to their charge;
commanding them in love, and restraining them from unsuitable things; that,
as delegated shepherds, they might guard them from the corruptions of the world,
and prepare their hearts for the seed of the kingdom.
And no greater joy will they have in advanced life, next to Divine approbation,
than to see their sons as olive plants around their table,
and their daughters as cornerstones, polished by the Truth,
after the similitude of a palace I felt peaceful; Divine help having been extended,
to qualify for the discharge of duty.

9th. Second-day.
Our friends in this city have shown us much kind and affectionate attention;
and I believe have been united to us in the visit.
We parted from them with feelings of sincere regard, desiring their growth in the Truth;
and took passage in the steamboat for Pittsburg or Wheeling, as it might suit us best.
This mode of traveling is less fatiguing than most others;
yet the confinement with strangers, and the monotony, add to its wearisomeness.
One morning the passengers and men were startled at seeing a large steamboat meeting us,
and so near, as to appear improbable the boats could avoid striking.

The engine was working slowly, on account of taking in wood,
and the helmsman immediately giving the signal to the engineer, to turn the wheel back,
the other boat just passed our bow, without injury.
Our danger was occasioned by fog,
which prevented those on the two boats from seeing each other in time;
we accordingly came to, along side the shore, and waited until the fog had dispersed.
The captain said he had known boats to run over others and sink them;
so that we had cause to be thankful to our Great Preserver,
that no harm was permitted to befall us.
How near we sometimes come to the gates of death, without being destroyed,
we cannot tell; but we have a merciful Shepherd, who sleeps not by day or night,
and constantly cares for us; even when we are not remembering Him;
and kindly protects and delivers us from many dangers.
May the sons and daughters of men reverence; fear and praise his great and worthy name;
and serve Him with the whole heart.

We landed at Wheeling on fourth-day, the 11th; took stage for Cumberland, and from there,
by railroad and steamboat, reached the wharf at Philadelphia,
about three o`'clock on seventh-day morning.
It being moonlight, encouraged us to leave the boat at once,
and I soon gained entrance into my own dwelling,
and was heartily received by my beloved family; finding them all in health,
no evil having befallen any of them in my absence; for which,
and the help and preservation granted me in the
prosecution of this little requisition of duty,
and the peaceful mind now enjoyed, I desire to be humbly thankful to my gracious Leader.

On the 30th, feeling a gentle pointing to Chester Monthly Meeting,
held in this month at Springfield, I went to it;
and in unison with my beloved friend Sarah Emlen, who addressed the young people,
I was drawn forth in love towards them,
to show them the blessed results of obedience to the Divine commands.
The man who was born blind, received sight, after his eyes had been anointed with clay,
by following the direction of the Lord Jesus, to go to the pool of Siloam and wash.
And when the ten lepers were going to show themselves to the priest,
in conformity with Christ`'s bidding, as they went, they were healed.

Our dear friend S. Emlen,
having then a prospect of again spreading before
her friends a concern which she had long felt,
and once laid before her meetings, to pay a religious visit to England, Ireland, etc,
the current of the stream of the ministry seemed to embrace her situation also;
encompassed with fears; and proved a strength to her;
though I did not know it was her intention to bring it before that meeting.
We ought not to magnify our little impressions to duty, beyond their deserts;
yet going there in faith,
without any other object than a compliance with apprehended duty,
and being introduced into fellow feeling with a suffering sister,
and enabled in any degree to cheer and animate to faithfulness, was a comfort to me,
and a little evidence that the Lord`'s hand was in it.
He that waters shall be watered himself.

Twelfth month 23rd. Feeling my mind drawn to go down to West-town school,
I set off this morning.
Two deaths having occurred among the scholars, sympathy, and the impression of duty,
induced me to make them a visit.
Attended their meeting the next day.
I was exercised among them in the authority of Truth; being in the first place,
led to deal plainly with some of the children; who, it felt to me,
were under very little religious restraint in their own minds; but were doing what,
at times, they knew was wrong, and inciting one another to the same improper conduct.
Then I was turned to the care-takers;
to encourage them to a more fervent travail of soul for themselves,
and for the children entrusted to their charge.
The power of Truth spread over the meeting, and brought the spirits of some down;
tendered others, and I hope impressions were made that will be lastingly useful.
In the afternoon I felt bound to open to them the ground of
our testimony to the use of the plain language;
thee and thou to one, and you to more than one.
It was the scripture language from Genesis to Revelation;
and it was our duty to avoid the corruptions brought in through pride: also,
of our testimony against the vain titles given to men,
and against the heathen names of the days and months.
I returned home on the 25th in peace; but as is very common with me, in poverty of spirit.

1844+++.+++ First month 1st. Attended at the Girls`' Select School by appointment.
At the close of the school, after religious reading, was gone through,
Thomas Kite had a short communication,
on the importance of making a new beginning to improve with the new year.
I was impressed with the beautiful ornament of modesty and diffidence,
in the female character;
especially when it proceeds from the heavenly
influences of the spirit of our blessed Redeemer,
who was meek and lowly of heart.
As I gave up, unworthy as I felt myself, to the gentle impressions of duty,
the blessedness and substantial happiness experienced by the devoted soul,
in which the Lord condescends to take up his abode, was brought to view;
and the dear Children persuaded to yield to the visitations of Divine love.
He would clothe them with the modesty, and the graces imparted by his Spirit;
which would be as a barrier between them and those who
would allure them from the path of holiness.

7th. After a long silence in our Particular Meeting,
and passing through much discouragement on my own account,
and the opposition which prevails in worldly-minded men,
to the plain doctrines of the gospel, I was brought under exercise on account of a state,
which had tried many things, and sought after enjoyment in the comforts of life,
and was disappointed, and now had little or nothing to rest on.
The language of David presented: "`I have seen an end of all perfection;
but your commandment is exceeding broad.`"
Earthly comforts and delights, in their most perfect and complete state, would end;
but godliness, which is keeping God`'s commandments, is exceeding broad;
having the promise of the life that now is and of that which is to come.
I felt tenderly for those who seemed to have wasted time and strength,
and were brought to a sense of destitution;
believing that it was in mercy the Lord thus deals with poor,
negligent and unfaithful man;
that He may raise in him a longing desire after durable riches;
the bread and water of life.
These were fervently and affectionately labored with,
to persuade them to endure his dispensations, and apply to Him for help and strength,
to redeem the lost time, by faithfully following him in the work of regeneration.

At our large evening meeting, we had a long season of close, inward conflict;
during which, I expected we should close the sitting, as we did last first-day,
without anything being said which, if it was the will of the Head of the church,
I believe we were desirous of submitting to, as being in wisdom,
and for the good of the people.
At the same time, there was a yearning of heart,
towards some who were hungering and thirsting after the bread and water of life;
and were adopting the language, "`Tell me, O you whom my soul loves, where you feed,
and where you make your flock to rest at noon;
for why should I be as one that turns aside by the flocks of your companions?`"
and when it seemed near time to separate, I was induced, under fear of omitting my duty,
to revive the declaration of our Lord,
"`Where two or three are gathered together in my name,
there am I in the midst of them;`" and to say that He is in the midst of such,
whether they are sensible of it or not;
watching over them and beholding their respective conditions.
He may try their faith, but He will teach these to keep the word of his patience;
and if they wait upon Him, will sustain them,
until he sees fit to manifest himself to them.
Encouragement was handed to these seeking souls; that although,
they may have but few outward helps, yet if they continue dedicated to their Lord,
He will cause them to grow in the Truth, so as to be helpers to others.
Our beloved friend, Elizabeth Pitfield, knelt in solemn supplication,
and the meeting ended to satisfaction.

10th. Today I attended the Western District Meeting after a long absence;
and was favored through the unmerited condescension of the Lord our God,
to preach the way of life and salvation; being through the cross, and baptisms,
and deaths oft.

Second month 5th. We had a good Quarterly Meeting; our friend Isabel Cassin,
from England, being exercised among us, and enabled to bring up stones of memorial.
She said the struggle was between the seed of the bondmaid and that of the free woman;
and to the latter, Christ would give the victory.
She was glad to feel Friends in this city, as bone of her bone, and flesh of her flesh,
and there were those who are travailing in birth;
and some who are shut up as in prison-houses, to whom the language would be uttered,
"`Go forth you prisoners of hope.`"
She appeared to have the prospect,
that faithful ones would be raised up to maintain the testimonies of Truth;
and preach the glad tidings of salvation through a meek, and crucified,
and glorified Lord.
My dear wife bent the knee in solemn, fervent supplication; by which,
and the foregoing testimony, many hearts were tendered.

29th. For many weeks I have been moving along under secret bitterness of spirit.
My desires are at times strong for entire victory over every habit or
propensity that stands in the way of communion with the Father of mercies.
May the Lord in his infinite and unmerited mercy,
condescend to show me those things that are contrary to his blessed and holy will,
and lead me clean out of them;
that I may be more fitted for his use and enabled to hold forth an example of purity,
and gravity, and self-denial, that may tend to draw others to the blessed Truth,
and settle them on Christ, the Rock and Foundation of his church,
and of every living member of it.

Our friend Rachel Priestman, from England,
having a desire to hold a meeting with the laboring part of
the inhabitants in the southern suburbs of the city,
particularly with those who go to places of worship but little,
arrangements were made with the trustees of the Methodist Meeting-house,
on Wharton Street, for its use; which being granted, notice was spread;
both at the first-day meeting there, and by hand-bills through the district.

Last evening a very large concourse met there; many more than could get in the house.
It was computed that sixteen hundred were seated; who conducted with much propriety,
and to whom our friend preached, at considerable length.
After she had spoken, my mind was impressed with the belief,
that it would be right to open a little the inward and
spiritual nature of the gospel dispensation;
reviving the answer of our blessed Lord to the question,
"`when the kingdom of God should come:`" "`The kingdom of God,`" said He,
"`comes not with observation; neither shall they say, lo here,
or lo there! for behold the kingdom of God is within you.`"
The great liability to look abroad for that which is to be found within ourselves;
and the necessity of experiencing Christ, by his Spirit, to bind the strong man,
to spoil his goods, and cast him out, was set before the attentive company;
that so every one may know the heart cleansed and sanctified,
and made a temple for the Lord of life and glory to dwell in.
Divine help was near; enabling both of us to preach the gospel of salvation,
through the Son and Sent of God.
Our friend closed the meeting with prayer.
I understood afterwards, there was general satisfaction with the meeting.
Our annual assembly this year was large and solemn.

Many manifested a lively interest in its proceedings; and faithful, exercised Friends,
were engaged to labor for the promotion of greater
diligence and devotion in all our religious duties.
I believe that the blessed Head of the church was graciously near, uniting us together,
and qualifying us to do his will, and to show forth the excellent order,
and solid weightiness of spirit, that are to be found among his people,
where He presides, and every one, in humility, is desiring to keep his place in the body.
We have cause to be reverently thankful for his great condescension,
and to ascribe all the praise to his great and holy Name.

Information being received during its session,
that a treaty had been negotiated by the President, with the Texan government,
for the junction of its territories to the dominions of the United States,
the Meeting for Sufferings convened at the close of the Yearly Meeting,
to consider whether it would be right,
for Friends to remonstrate against the contemplated measure;
by which slavery and the slave trade would be extended in this land.

Such a document was concluded to be drawn up; a committee was appointed,
and on seventh-day morning, the 20th of Fourth month, it was produced, united with,
and several Friends named to take it to Washington, for presentation to Congress.
They accordingly went to the seat of government; had it offered to the Senate,
and had an interview with the President, and with the representatives of our city;
and returned on the 25th.

Fifth month 11th. Our city has been thrown into great commotion,
and some parts into great terror, by the circumstance of some persons,
said to be foreigners, firing into a meeting of Native Americans,
convened for political purposes in Northern Liberties.

A religious life is at all times blessed,
but its value is most especially felt in times of danger, and at the approach of death.
Those who love and serve God in the time of prosperity,
will not be forgotten nor deserted by him in the day of adversity.
His name will be to them a strong tower, to which they will flee and find safety;
even when terror and amazement overtake the worldly and the negligent ones.
What solid advantage is derived from giving up to the early visitations of Divine Grace,
progressing, through obedience to the cross, from stature to stature,
and thereby attaining an establishment in the Truth.
These have the pearl of great price, the white stone, and in it a new name written,
which no man knows, saving him that has it; an inestimable treasure;
Christ living and abiding in them, the hope of their glory,
and the foundation upon which they are built and settled.
They want no other; they thirst for no other water, than what springs in their souls,
from Him, the Fountain of living waters; and their prayer and travail is,
that they be made and kept as pillars in his house, that shall go no more out.
These are as salt in the earth, and lights in the world; soldiers in the Lamb`'s army,
who bear the ensign of the Prince of Peace; and who will, under his command,
finally obtain the victory over death, hell and the grave, in their own experience;
and over the kingdom of antichrist the world over; even so, Amen.

16th. Receiving a gentle intimation the day before,
to go to the Western District Meeting, I attended it yesterday.
A Friend from another Quarter, communicated a few words,
on the necessity of praying without ceasing, and in all things giving thanks.
Another, not belonging there, knelt soon after, in petition to the Almighty,
for preservation, and that as the harvest was great,
more laborers might be sent into the harvest field.
My duty appeared to be to hold up the plainness and the holiness of the path,
which Christ casts up for his children to walk in; that when He comes into a soul,
to begin the work of regeneration, He often causes his light to shine as in a dark place;
discovering to it its real condition;
what it must part with before it can be fit for Him, by his Spirit,
to take up his abode in, and before it is prepared to be made use of by Him,
in his work and service.
To such a soul this is peculiarly one of the days of the Son of man;
in which if it submits and does not resist, his love will be shed abroad;
He will raise in it fervent cries for strength to forsake all and to follow Him;
these cries will be heard and answered.
He begets the will, and works the deed in us, and as He is faithfully followed,
the soul is gradually led out of everything that defiles,
and is contrary to the Divine will;
and thus an entrance being obtained at the strait gate,
a growth and gradual establishment in the blessed Truth is known.
I began low, and the Lord furnished me with matter, one thing opening after another,
until the stream rose and overflowed the hearts of some present; softening them down,
and renewing desires for a participation in the precious things of God,
the blessing of the everlasting hills.
Christ Jesus, and Him crucified, was preached;
and some who had of latter time been awakened, as I believe, there were such present,
were pressingly called to believe on Him,
and yield to his heavenly visitations and convictions.
Another Friend closed the meeting with prayer,
particularly that those to whom the word of reconciliation was committed,
might be preserved to the end, and finish their course with joy,
and to testify the gospel of God`'s universal grace.
We have great cause to thank Him for his goodness and
great condescension to our low and unworthy state;
and to put our mouths in the dust;
humbly craving that He will suffer neither heights nor depths, principalities nor powers,
nor any other creature, to separate us from his love which is in Christ Jesus,
our crucified yet victorious Lord and Savior.
