== Chapter XVI

1844

Changes taking place in Philadelphia Yearly Meeting--Lydia Dean--
Philadelphia Quarterly Meeting--Concord and Western Quarterly
Meetings--Haddonfield Quarterly Meeting--Religious visit to the
Meetings in the Northwestern part of New York Yearly Meeting.

1844,
Fifth month 25th. Sarah Emlen being about to embark for England on a religious visit,
I called at her lodgings last evening, where I found several Friends.
After conversing pleasantly for a time, we fell into silence,
and several communications were made,
encouraging and counseling our dear friend to put her trust in
Him who has covered her head in the day of other battles;
who is the only foundation upon which we can rest with safety,
and the only leader and commander who can guide in the way and work,
so that it will yield peace in the conclusion,
when a retreat is sounded in the mental ear from the field of service.
And how important, at the close of the labor,
to have the evidence that we have fought in his ranks, and advocated his cause,
and not that of any other.
To these He will grant the reward of sweet peace,
which is of incomparably higher value than all the applause which vain man can bestow.
No party adulation or applause can give peace, but will rob us of it,
if we suffer ourselves to be drawn aside from faithfully following the Master.

On the 23rd, I was to the Arch Street Meeting in much weakness and fear,
yet did not feel easy to refrain from opening the
necessity of knowing Christ to be our baptizer,
and sanctifier.
These only are his servants, whom the Father will honor.
By the humiliating, refining operations of his fiery baptisms,
the creature is brought into the state of a little child; looking up to,
and leaning upon Him.
Hereby preservation is experienced; the spiritual eye is anointed to see,
and to discriminate between that which serves God, and that which serves him not.

And as they keep faithful,
these are made living witnesses of the power of his resurrection,
and the majesty and the mercy which He displays in delivering, leading on,
and clothing the soul, with the garments of his righteousness and praise.

Changes are gradually taking place among us in this city.
There are now very few left, to whom some of us can look as fathers and mothers,
counsellors and supporters, in the trials and exercises of the day.
Of the many who wear the garb of Friends,
too small a proportion are daily dwelling under a
heartfelt concern for their own soul`'s salvation,
and that they may come up as fellow helpers in the cause of Christ.
There are, however, some of this description,
who are a comfort and strength to their elder brethren and sisters.
But how have the love of the world, its fashions and its maxims,
together with its ease and its deceitful spirit,
captivated not a few who had made a good beginning; stopped their growth,
and eaten out the life and power of religion.
When we have looked around to see who would be found
prepared for the important station of elders,
we can discover but few who have not fallen back or are making but little progress;
so that instead of being ready for watchmen and watch-women,
and instructors of ministers, they have need to be reminded of their slackness,
and of the mournful feelings which their unfaithfulness brings over
those who have been watching for their growth in the blessed Truth.

This state of society is at times very discouraging; but, nevertheless,
we are not to be hindered by such slothful ones,
from doing the work which our Master points out, and requires us to perform;
whether others hear or refuse to profit by it.
To know our own souls delivered from the wrath to come,
is of the highest importance to us; and as we are engaged for ourselves,
the Lord may secretly bless the honest discharge of duty to others also.

Sixth month 17th. My beloved wife having been engaged
in visiting the families of Woodbury Meeting,
and being nearly ready to return home, I went there this morning.
In the afternoon, G. M. and wife accompanied us to Sculltown;
she having a concern to make a visit to a few in that neighborhood;
which she accomplished; being favored to minister, in much clearness,
to the states of several with whom we had religious opportunities.
We returned to Woodbury next afternoon, and to our own quiet,
peaceful home in Philadelphia.

21st. Our Meeting for Sufferings was held this day;
in which a committee was appointed to draw up a
brief address to our members in this State,
cautioning them against complying with the requisitions of a militia law,
recently enacted by the Legislature.
The meeting adjourned to nine o`'clock this morning, (22nd,) when the essay was read,
carefully examined, and directed to be printed and circulated among the members.
The unity and fellowship with which the subject was handled and resulted,
was truly encouraging and comforting.

30th. The state of our religious Society,
and the secret workings of a spirit which seeks ease and despises the cross, and would,
if it could, lay waste the testimonies the Holy Spirit leads into,
often brings sorrowful and depressing sensations over
those who desire to see those testimonies maintained.
Under these feelings, it was a comfort to witness the Truth rise into dominion,
through the ministry of my dear wife, this morning in our meeting;
who was qualified to preach the necessity of individually
experiencing Christ to be the resurrection and the life in us;
raising the soul out of a state of spiritual death,
and placing the affections upon things that are invisible.
It was unexpected to me,
but I felt constrained to follow her in supplication to the Lord our God,
that He would baptize and rebaptize us with his Holy Spirit,
not only to remove the chaff,
but to keep alive a flame of love and greater devotion to Him, on the altar of the heart;
to unite those who assemble in that place; that they may put shoulder to shoulder;
and with one heart, offer to Him, the Lord God and the Lamb,
through the powerful influence of the Holy Spirit, thanksgiving and praise, might,
majesty, dominion and power, to whom alone it belongs;
but to us blushing and confusion of face.

Seventh month 9th. This afternoon was interred, in the Western Burying Ground,
the remains of our much beloved friend Lydia Dean, late of New York;
a sound and lively minister of the gospel of Christ.
She believed it to be her duty to remove to this city, and accordingly came last autumn.
Her frame was remarkably delicate; and having been long afflicted with bronchial disease,
it terminated in consumption of the lungs;
which was the means of cutting short her valuable life.

She was favored, near the close, with a precious glimpse of her Savior; and said,
"`My Savior has come at last; how glorious!`"
Her resignation and preparation for death were a sweet consolation to her friends;
softening the trial of losing so excellent a minister,
and deep travailer for Zion`'s welfare.
She held fast to the end, her integrity to the Truth,
as declared and believed by Friends from the rise of the Society;
bearing a decided testimony against all attempts at modifying its doctrines,
or admitting any innovation upon them.

30th. Poverty and emptiness have been my portion for days past;
the thought sometimes arising,
whether I shall again be enabled to engage in the Lord`'s work with acceptance.
Yet strong desires have been felt to experience preservation,
greater degrees of purification, and a deeper establishment in the Truth.

One after another is being removed from works to rewards;
and how soon the awful summons may be sounded in the ear of those left behind,
no one of us knows.
But it has felt to me increasingly needful, to watch against temptation,
and to resist it steadily,
that the work of redemption and sanctification may continue to go on with the day.

Eighth month 5th. We held our Quarterly Meeting this day.
These meetings are often trying seasons; producing mournful feelings,
on account of the lack of fervent, united, spiritual labor,
for the prevalence of Divine life,
and the lively support of our discipline and testimonies;
so that we might see the Truth prevail, and the members prospering in it.
And yet, I trust, there is a body preserved, though it may not be numerous,
who are united in the fellowship of suffering, for the same blessed cause;
mourning and travailing together before the Lord,
on account of the effects of a worldly spirit, which cannot bear the cross;
even amongst some who would wish our religious Society
to be more like the other professors of Christianity,
in language, dress and manners.
Ah! these have inflicted a severe blow upon us,
which we were in nowise prepared to expect.
But the Lord on high, who is mightier than the noise of many waters,
can sustain his children in their deep probations, and mightily defend his blessed cause;
even though the truly devoted in heart may be few; and their strength, at times,
seem ready to fail.
The turning aside of some, like a deceitful bow in the day of battle,
giving their strength in secret to wrong things,
is a cause of great discouragement to the single-hearted soldiers of Christ.
It not only creates doubts and faltering among some others,
but it will certainly bring weakness and blindness on themselves.

Feeling drawings to attend Concord and the Western Quarterly Meetings,
I went to Springfield, and attended their first-day meeting, on the 18th;
in which it appeared to me,
that the example of faithful and upright members in the church,
would tend to lead others into the narrow way of self-denial,
and to keep up a defense against the inroad of error.
The obligation parents are under,
to rule their children in the authority and wisdom of Truth,
and to apply the same kind of restraint to them
which they are bound to live under themselves,
was also brought to view.
Where they permit wrong things in them, they weaken themselves,
and do an injury to their offspring.

19th. Accompanied my brother and sister Rhoads to Concord.
The Select Meeting was not a very animating time,
yet our dear friend and mother in Israel, Hannah Gibbons, had good service.

20th. Was held the Quarterly Meeting for discipline.
After some time, I felt it right to revive the apostolic injunction,
"`Believe not every spirit, but to try the spirits,
whether they are of God;`" and to hold forth a caution,
to beware of the many spirits and voices that are abroad in Christendom;
by which the grand enemy is seeking to allure
from a steadfast subjection to the Lord Jesus,
in his spiritual appearance in the heart.
It matters nothing to Satan, by what means he can effect this object;
even if it be by engaging the children of our Heavenly Father,
in various plans for bettering the condition of mankind,
but in which it may not be his will they should engage.
If we take the government of ourselves into our own hands, instead of bearing the cross,
in doing his will, and his appointed work, we lose his Divine guidance;
our spiritual eye will become blind; and we shall grope in the dark,
not knowing where we are going.
Thus we shall lose the place in the body, which He allots,
and must be cast forth as dead branches.

Some who have begun well, and walked in the Truth for a time by unwatchfulness,
and gradually again giving way to their own wills,
have at last fallen into such darkness, that they have done despite to the Holy Spirit,
and landed in a state of entire unbelief.
Friends were solemnly called upon to keep to Christ, and his inward guidance,
that a growth in grace, and an establishment on Him, the Rock of ages, may be witnessed.
The meeting closed with solemn prayer, by Thomas Kite.

21st. I stayed at Concord to attend the Particular Meeting; which was small,
being generally so at this time.
Some service presented; which was followed by peace; and in the afternoon,
I went to the Western Quarter.
The Select Meeting was made up of a small number.
They were exhorted to increased travail of spirit for themselves, and for the flock.
The Apostle James adduces the answer to the prayer of Elijah for rain,
after a drought of three years and six months, as proof that the fervent,
effectual prayer of a righteous man avails much.
And if the members of the church dwell under the clothing of the spirit of prayer,
and travail for the prosperity of the cause of Christ,
and the transformation of those not yet brought into the Truth,
we have ground to believe that it will be answered;
and the fruits of their exercise will gradually appear.

23rd. A pretty large company collected at the Quarterly Meeting.
Two ministers were led to speak to those who were not
occupying the gifts bestowed on them as they ought;
and who thus occasioned mourning to the baptized members of the church.
From the exercise and travail which prevailed,
and the condescension of the Blessed Helper of Israel,
I hoped that some good impressions were made;
but it is the Lord alone who can give the increase.
The next morning I returned home.

29th. This evening a fire occurred in the store
adjoining that occupied by me as a warehouse,
and where my brother and I had stored the unsold volumes of the "`Friends`' Library.`"
The prompt exertions of the firemen prevented much injury to the building;
but part of the roof being burned, a large quantity of water was thrown in,
which ruined many hundred copies of the Library, and some goods.
Several Friends, and other fellow citizens, labored perseveringly to save them;
to whose efforts, is to be attributed the preservation of so many, as escaped damage.
I esteemed it a favor that the whole contents of
the store were not permitted to be burned.
Had the fire occurred later in the night,
most of the books and goods must have been destroyed.

On returning home from the fire, to change my clothing,
being wet through by the water pouring down on
us while passing the books to the lower story,
the language passed through my mind, "`Shall we receive good at the hand of the Lord,
and shall we not receive evil;`" and resignation
was and has been the clothing of my spirit.
Ninth month 1st. Went to Newtown Meeting;
where I was engaged in warning some of the danger of spending
time without being employed in the great work of salvation;
and to pray for them, and the poor of the flock, that we might be helped,
and kept through all, to the end.
Returned with sensations of poverty and weakness;
yet without seeing that I had done wrong in anything.

2nd. Today calm and peaceful, and without condemnation;
and remembered as I walked the street, what Paul says.
"`There is, therefore, now no condemnation to them that are in Christ Jesus;
who walk not after the flesh, but after the Spirit;`" and I have tried to look to Him,
and to pray to Him for preservation herein.

10th. My wife and myself went to our friend S. and B. N.`'s, at Haddonfield, and lodged;
and the following morning we accompanied them to Medford, where was held, at this time,
Haddonfield Quarterly Meeting.
The Select Meeting, which is much reduced, was a season of inward poverty; and yet,
towards the close, there seemed a spring of encouragement opened;
in which it appeared to be the Master`'s will that we
should endeavor to draw nearer to one another in spirit,
and strengthen each other`'s hands for the Lord`'s work.
He can cause one to chase a thousand, and two to put ten thousand to flight,
if they are girded with his strength;
and their eye and confidence are directed to the Lord alone.
We dined at A. H.`'s, where we had the company of Hinchman Haines,
an honest laborer and burden-bearer in the Lord`'s cause; also of several others;
and their conversation and solid deportment were cheering and strengthening.

12th. In the morning a large company convened at the meeting.
I feared the lack of individual labor for the bread of life,
and looking for it through instrumental channels, shut up the spring of the ministry.
H+++.+++ Haines said a few words,
and my dear wife knelt in fervent supplication
on account of the lack of spiritual exercise,
in many convened.
The number of true travailers for the arising of Divine life,
was felt to be small and the weight resting on a few, very great;
for whose help and steadfastness, she also petitioned the Father of Mercies.
It was some relief; and the meeting soon afterwards proceeded to its business.
When the business was gone through,
our friend H. H. made some remarks on the members joining the
political processions and exhibitions of the present day;
which he considered to be below the dignity of men, and much more of Christians.

My mind had been under exercise on account of Friends
mingling with those political parties and associations,
and I revived the ancient testimony; "`Lo! the people shall dwell alone,
and shall not be reckoned among the nations.`"
Whenever they did mix with them, they were caught in their idolatrous practices,
lost their strength, and were often overrun and overpowered by them;
because they forsook the Lord and his worship.
And so it is with us.
Those who join the political assemblies, lose their spiritual strength;
become impregnated with their spirit; and, if they continue,
become like fruitless branches, cut off from the vine; they are dead,
as to the Divine life, and the men of this world gather them into their fellowships,
and they are burned or destroyed, as to any life or virtue.
Friends were called upon to observe whether any one, let his station be what it may,
is not crippled by thus associating in these worldly combinations.
Such are not alive in the Truth;
and it is obvious to their brethren that they have lost ground;
and their example must have a prejudicial influence
upon the younger and inexperienced members.
Several Friends united fully with what was said, and it appeared to reach some.
We remained until seventh-day morning, and then returned home.

Tenth month 3rd. Last week I was attacked with fever; which, with the remedies used,
reduced me not a little.
Being unaccustomed to sickness, it brought me low in body and mind;
in which I was engaged to take a retrospect of my life; which seemed much of a blank.
How little appears to have been done, compared with the time, and the offers of best Help.
Oh for more deep, inward abiding with the Seed of Divine life;
that a larger growth in the Truth,
and more solid religious exercise and weightiness of spirit may be attained.
That I may be enabled to go in and out before the flock, in such manner,
as to turn them to Christ, and induce them to take His yoke upon them and follow Him.

Eleventh month.
Having had a prospect for many months of visiting at some period,
the meetings of Friends in the northwestern parts of New York Yearly Meeting,
and the present appearing to be the proper season for undertaking it,
I laid the concern before the Monthly and Quarterly Meetings,
and obtained the unity and certificates of those meetings with it.
Parting with my beloved wife and children;
leaving my business in the hands of persons of little experience,
and traveling in a cold, snowy country in the winter,
made the undertaking more trying than on some other occasions;
but believing it was in the ordering of best Wisdom, I made preparation,
and with my kind and beloved friend, Joseph Elkinton, an elder of the same meeting,
set out from home on the 25th of the Eleventh month, in our own conveyance,
and got to New York on the 27th. We made an attempt to put our
carriage and horses on board of a steamboat for Hudson,
but the tide was so low it was impracticable to accomplish it,
as the horses could not descend the bridge to the deck.
The great hurry in landing and loading goods and produce, owing to the cold weather,
and the fear of the navigation soon closing,
made it difficult to get the carriage and horses on board the steamer;
and in the attempt to accomplish it, agreeable to the direction of the captain,
who had agreed to take them, the tongue of the wagon was broken, and we defeated.
The detention of a day, under all the circumstances of the lateness of the season,
was very trying to us;
especially as it was uncertain that we could get them up the river by the next boat.

The 28th was a wet and dark, cloudy day, not very cheering to the spirit;
but through the perseverance of my companion, we got all on board the boat.
Here we were detained three hours after the usual time, waiting for a loaded sloop,
which he was to tow up; and owing to this, the heavy deck load,
and the storm which had prevailed through the night, the boat rocked so much,
they were often compelled to stop the engine, for fear of breaking the shaft,
when a wheel would be deeply immersed; all which retarded our progress,
so that we did not reach Catskill until about one o`'clock, instead of six in the morning.
In the course of the evening, when the boat careened greatly,
I suppose one of our horses slipped,
and struck his foot against one of the sash of the forward cabin,
knocking it completely in.
The crash of the glass, and the noise he made on the deck, in recovering himself,
gave the passengers in the cabin the idea that he was entirely loose,
and might soon be down the stairway among them.
The affair was rather ludicrous, and soon passed over, when properly understood.
But all these occurrences had their effect upon our spirits.
In the night, awaking in my berth, they seemed to be against me;
but I was reminded of the situation of the Apostle Paul;
that he was a night and a day in the deep and
this was no proof that his mission was not valid;
so I endeavored to keep in the faith, and press on.
They had some difficulty in bringing the steamboat to the wharf at Catskill;
which put some of the sailors in a bad humor;
and everything being nearly covered with ice, and the ropes frozen,
it was with great effort they got the carriage and horses landed.
When on shore, we harnessed up, and drove out that afternoon to Grant`'s tavern,
sixteen miles, and put up.
The next day we rode to R. B.`'s, about twenty-eight miles; she,
and several of her children settled near her, being members.
Here we had a meeting at the house of one of her sons, on first-day,
being the first of the Twelfth month.

It rained during the night, after our arrival, and about eight, o`'clock in the morning,
the wind changing, the rain turned to snow; which made everything, out of the house,
look dreary, and doubtful as to the meeting.
But more collected than we had reason to expect; and I trust, the gospel of salvation,
through our Lord Jesus Christ,
both in his coming in the prepared body to do his Father`'s will,
and by his Spirit in the heart, was preached among them;
showing the necessity to cooperate with the latter,
in order to reap the full benefit of the former.
Some were tendered.

After dinner we set out on our journey; but the horses`' shoes being very smooth,
and the road, in places, icy and covered with partly melted snow,
they slipped so much we made but little progress, and stopped at a tavern for the night,
where there was a probability of getting the shoes sharpened.
In these journeyings, little difficulties are often magnified by the imagination;
producing fears as to how we shall get through;
and whether we shall accomplish the work to the honor of our Holy Redeemer,
and be favored to return to our dear home friends in safety and peace.
These are trials of faith, which such poor unworthy pilgrims have to endure;
and doubtless the trial of our faith, which is more precious than gold that perishes,
is essentially needful to keep us humble, and to quicken our desires unto Him,
and to the remembrance of his name.

Twelfth month 2nd. This morning the weather was cold,
but when our horses were ready we set out;
finding ourselves much relieved by their being able to take a firm hold of the ice;
and in the afternoon we got to our friend H. B.`'s, at Oneonta.
Notice was spread of our wish to have a meeting at Laurens.
It was truly grateful to get under the roof of kind friends, in a land strange to us;
several others came during the evening,
with whom we conversed on subjects connected with the
principles and order of our religious Society.
Third-day went to the meeting in weakness,
and under desire that the Master might be with us;
which I hope was in good degree experienced, to the tendering of some hearts.

Fourth-day.
The snow continuing upon the ground,
we were furnished with a sleigh to carry us to Butternuts;
it being the time of their Monthly Meeting.
Here I felt the importance of moving under right direction:
that no advantage in any way might be taken of what was said,
should I find it my place to communicate anything among them.

The indispensable necessity of daily waiting upon the Lord,
for the renewal of our spiritual strength,
and to be preserved quick of discernment in his fear,
to keep us from the temptations that surround us, was brought before me,
and with feelings of caution, and dependence upon the Head of the church, I rose,
and as things gradually opened, delivered them,
under a clothing of sincere desire for the present and everlasting welfare of the people.
The solemnizing presence of Him, who is in the midst of them who gather in his name,
was felt, and I believe carried home to some, the truth of the doctrines preached.
The need of submitting to the renewed baptisms of the Holy Spirit, was enforced,
that as fruit-bearing branches, we may be prepared to continue to the end,
in bringing forth fruit to the praise of the Great Husbandman.
Some who had known this in their beginning,
growing unwilling to come again and again under its reducing power,
and thinking themselves able to decide and act from their attainments, have fallen away.
And the necessity of being fervently engaged to crave
strength to yield to and bear those purging operations,
that we may be kept as little children, relying upon the Lord day by day,
was affectionately pressed upon Friends.

5th. We had an appointed meeting at Otego, held in the house of a Friend.
The company was nearly all composed of persons not of our Society,
who conducted in a very sober manner, and to whom the gospel of salvation was preached.
C+++.+++ B. who piloted us there, exhorted the people to receive the word preached,
and afterwards told us they were a tender-hearted people.
Here we were met by J. T., who conducted us to his house, near Oneonta; where we lodged,
and next morning had a religious opportunity with his family.
Our object in coming back to this neighborhood, was,
to take a sleigh to perform the remainder of the journey, should the snow continue,
leaving our carriage at H. B.`'s; but this day and the succeeding night,
the weather growing warmer, the snow nearly disappeared,
and we decided to keep to our comfortable carriage.

7th. Accompanied by H. B. and C. B., who set out to be at Le Bay Quarterly Meeting.
We left the house of the former, where we had been kindly cared for,
and rode to New Berlin, dined and fed our horses.
It rained most of the way, which made the ground muddy, and the traveling laborious,
over the mountainous country to Smyrna, about thirty-four miles.
After a tedious ride it was grateful, as night was coming on,
to be made welcome at the house of two women Friends,
who received and entertained us in a frank and comfortable manner.

The weather changed; the wind rose and blew with much violence,
and the roads froze hard that night; making them very rough; and our meeting,
in consequence of the cold and snow, was small.
I was engaged to encourage some to faithfulness,
and to warn others against the snare of lawful things;
by which the mind is often so absorbed,
as to close it up against the Truth and its requirings.
Some, who seemed like withered branches, were also warned of their danger,
and invited to turn to Him whom they had forsaken.

After dining, we set off to De Buyter, piloted by H. K. and his wife.
Hard, rough roads, obliged us to travel slowly,
and we did not reach the habitation of a Friend until about an hour after dark,
by which exposure we were much chilled.
But the hospitable Friends came out to us as soon as they found we were strangers,
and invited us in with a promptness and earnestness,
which bespoke a sincere readiness to entertain us;
which is peculiarly agreeable to such pilgrims as we are.
A young man was despatched to the house of a Friend, two miles distant,
to spread notice of a meeting to be held the next morning which was done,
so as to convene all their members, and some others.
We had some religious communication in the evening,
and hoped our visit here was in right ordering.

9th. We went to the meeting, and through holy help,
I was enabled to open the doctrine of christian perfection,
and the necessity of being made and kept free from sin;
that we might become partakers of that full redemption, which comes by Jesus Christ;
and in the end be acknowledged by Him in the presence of the Father and his holy angels.
We went to the house of a newly received member,
whose wife remarked that doctrine was the same
which persons in that neighborhood despised,
and some despised them for holding it.
That evening we rode about ten miles, mostly over a bad road, and lodged.

10th. Set out early, and rode about twenty-five miles, to a Friend`'s house,
near Skaneateles.
Here we met a hospitable reception, and our guide, after taking some refreshment,
went on foot about four miles to a Friend`'s house, to give information of a meeting,
to be held the next day, at Skaneateles.
There he got a horse and went about five miles further,
by which the notice was spread generally.
Before leaving our quarters, I had a tendering opportunity with the wife of our host,
on the responsibility of her station as mother of several children,
whom she was bound to watch over, and guard from the temptations that surround,
as far as was in her power.
If she was faithful to the will of God, and rightly concerned for her own salvation,
I believed she would feel a deep interest in that of her children,
and would be led to pour forth her prayers and her tears before the Lord,
that He would lay his Divine hand upon them, and bless and preserve them.
We then went to meeting where we met a little company;
towards whom my mind was drawn in affectionate desire for their best welfare.
The testimony that, "`Godliness is profitable unto all things,
having promise of the life that now is,
and of that which is to come,`" was brought before me;
and I was led to show that the promise of this life, and of that which is to come,
is to no other state or condition.

That wealth cannot purchase it,
but is often possessed where there is neither happiness here,
nor good ground to hope for it hereafter.
The uncertainty of riches was also pointed out even where they were
pulling down and building greater accommodations for their goods,
but that the awful language might be sounded in the ear, "`You fool,
this night your soul shall be required of you,
then whose shall all those things be which you have provided.`"
The Master helped me to preach the gospel with convincing force,
and some worldly-minded ones were brought to tears.
I felt humbly thankful for his condescension and goodness to them and to myself.

We dined in the village, and went about fourteen miles,
on our way to North Street Scipio Meeting, and next day,
which was their Preparative Meeting, we went to it.
Here I was led to treat on the great importance
of having our hearts imbued with love to God,
and love to one another, especially as we were approaching old age,
and according to the natural course, must soon leave everything here below.
In heaven there is nothing inconsistent with holy harmony and love,
and hence the necessity of knowing this to prevail and
predominate in our hearts over everything else.
Though it will not lead us to unite with wrong things,
yet it will lead us to desire that those who have got wrong,
may be convinced of their error, and reclaimed.

The lack of spiritual discernment among us, was alluded to,
which attends and arises from the inordinate
love and pursuit of the things of this world.
But I believed the Lord would lay his hand upon this people, and restore it,
and make a division in their view between the precious and the vile;
and a body would again be raised up,
who should stand for the doctrines and testimonies of the gospel,
which He called our forefathers to bear.
Christ Jesus is the Head of the true church, and can alone fit us for membership in it.
It is his prerogative to appoint the place for the members in his mystical body;
and if any one refuses to submit to his preparing hand, they cannot be initiated;
and if after being made members, they resume the government of themselves,
leave the function which He allotted them, and undertake to do something else,
they will lose that Divine life which flows from Him into every member;
however plausible the object they may engage in.
"`Abide in me, and I in you.
As the branch cannot bear fruit of itself, except it abide in the vine,
no more can you except you abide in me.
He that abides in me, and I in him, the same brings forth much fruit.
If a man abide not in me, he is cast forth as a branch, and is withered;
and men gather them and cast them into the fire, and they are burned.`"
I thought the doctrine was not acceptable to some;
but felt peaceful in leaving it with them.
We dined at H. H.`'s, who kindly offered to keep our horses,
and take us in his carriage to Scipio, the next day.
Lodged at our friends Joseph and Sarah Talcott`'s
and passed the evening in agreeable conversation,
respecting many things connected with the cause of righteousness;
particularly the declining state of our religious Society.

13th. In the morning we had a tendering opportunity with the old Friends,
two of their children, and a grandson.
Towards the younger Friends, my mind was affectionately drawn,
that they might be brought to yield to the will of their Heavenly Father,
take up the cross, and openly confess Christ before men.

Rode four miles to Scipio, which was a large meeting, being held by appointment.
I felt low and empty, but after a time, I believed it right to rise with the expression,
that true religion was not an outside thing,
which we could take upon ourselves when we pleased; nor was it to be put off,
according to the company or the circumstances in which we might be placed.
Our Lord commanded his disciples, to let their yes be yes, and their no, no.
They were not to say yes, when they meant no.
And when He sent them forth, He commanded them, not take two coats apiece.
They were not to wear one coat or appearance in one company,
and another in different company.

Many things were opened by the good Remembrancer, without whom we can do nothing;
especially the doctrine of the universality of Divine grace,
and the impossibility without it, of truly seeing and feeling our lost condition,
sunk in the pit of sin and corruption.
Christ alone by his Divine and saving light,
which enlightens every man that comes into the world,
can give us a true sight and sense of this state, and raise in us the cry,
"`A Savior or I die; a Redeemer or I perish forever.`"
At seasons He visits the soul for this purpose, and if it resists not,
He will lift it out of its lost state, and restore man into the Divine image.
I was humbly bowed for the present favor; and thanksgiving,
and prayer for continued preservation,
were vocally offered to the Father of all our sure mercies.

Returned to H. H.`'s, and after dining, his son,
took us in their carriage to Union Springs,
about eight miles north where we had an appointed
meeting with the few Friends residing there;
held at the house of an aged Friend, where they generally convene on first and fifth-day,
for the purpose of Divine worship.
I endeavored to discharge myself under affectionate desires for the
present and everlasting welfare of those who were assembled;
and though some tears were shed,
yet I feared the impression might be of but short duration.

14th. Snow fell this morning very fast, but getting an early breakfast,
we rode down Cayuga Lake to Aurora, where we were met by our carriage and horses,
which we resumed and proceeded on our way to Hector.
By the time we reached the ferry, we found little snow remaining,
and after waiting three-fourths of an hour, for the ferryman,
who was on the opposite shore when we arrived, we got under way;
but a directly head wind, a horse boat with little power,
and an expanse of water three miles in width,
kept us nearly two hours getting to the opposite shore.
The road being pretty good, we drove to A. K. O.`'s in about three hours,
and were kindly received and entertained.

15th. Attended their first-day meeting, which gathered very irregularly,
and was a very trying time to me.
The spirit of unbelief, arising from a departure from the true and living God,
and becoming involved in sin and wickedness,
appeared to me to have taken possession of some; with which I had a fight of affliction,
without seeming to gain much ascendency.
I was led to speak of the progress of iniquity,
how one violation of the Divine law makes way for another; that hardness of heart ensues,
and finally some lose their reputation among men.
Very little relief was obtained, and I left them, covered with sadness,
and wondering whether I was mistaken in what I had said.

In the afternoon, having our friend A. K. O. as guide, we rode to Ovid, nineteen miles,
and put up at an inn, snow falling pretty fast most of the way.
In the course of conversation through the evening;
A+++.+++ K. O. informed us of some circumstances, of a very dark and shocking character,
which seemed to explain the cause of my difficulty and distress in their meeting.
This gave me relief; and hope sprung up that, according to the condition of the people,
the Master would baptize us; and thereby prevent us from crying peace when there is none;
and if this is mercifully the case, though suffering is my lot,
there is no just cause for doubting that the present engagement is in his ordering.

16th. We rose early, and rode down the eastern bank of Seneca Lake to Geneva,
a flourishing town, near the outlet of this body of water.
The wind blew strong and cold across the lake, and snow almost constantly falling,
made the ride dreary and wintry in its influence upon us.
At another season of the year, and under different circumstances from ours,
the country and the scenery must be delightful.
Judging from the fine and expensive buildings,
which many farmers erect in this part of New York, the country must be very fertile,
and the people prosperous.
But some go beyond their own means, and embarrass themselves and others,
in their pecuniary transactions.
The great press after wealth, and the inordinate pursuit of trade to acquire it,
absorb their time and all their energies;
so that a life of self-denial and devotedness to the will of God, revealed in the heart,
is too little known by the great mass of professing Christians.
Where a worldly spirit predominates, religion is but little thought of,
and the way is open to pride, and spending time, when not engaged in commerce,
in a way dissipating to the mind, and displeasing to our Almighty Creator.
Many in our religious Society are caught with the love of money,
and become covered with the lust of the world, as with thick clay.

Thus our religious meetings are often places of much suffering,
to the self-denying Christian, instead of comfort, strength and rejoicing.
This discourages the sincere-hearted, and turns the young people out of the right way.
When will the Lord arise in his power, and not only shake the heavens,
but the earth also,
in order that those things which are shaken may be removed out of the way,
and those which cannot be shaken may remain.

After a ride of forty-one miles, we reached J. E.`'s, and lodged.
We proposed holding a meeting next day at Palmyra,
which we found some difficulty in bringing about; and some of the members,
we had reason to think, did not hear of it.

The meeting held on the 17th, was small and distressing;
but I endeavored to discharge my duty towards some who were swallowed up in the world,
and had brought difficulties on themselves and others;
and the spirit of supplication being poured out,
I was enabled to pray for the poor of the flock,
who desired to be found in the right way;
and that the Lord would not take his Spirit from us,
but go with and preserve us in the work to which He has appointed us.
This afforded me some relief.

After dining, we rode about four miles to H. P.`'s; snow falling and accumulating;
which gives everything a dreary aspect,
and produces apprehensions of our being unable to get through with the carriage.
But I endeavor to cast my care upon the Lord.
We passed the time pleasantly under the roof of this kind Friend and his wife, with,
I hope, some profit and strength to them, as well as comfort to ourselves.

18th. Attended Mardon Preparative Meeting;
which was a more relieving time than some others;
and in the afternoon we parted from our kind friends, and rode to J. L.`'s,
within Farmington Preparative Meeting.
This Friend, who came into the country at an early age,
and has seen the direful effects of ardent spirits upon many around him,
gave us some account of the change that has
taken place in that respect since his arrival.
He seemed much interested in promoting the cause of temperance; which,
as far as we can do by precept and example, without mingling, in an improper manner,
with persons not of our religious profession, it is very important we should promote.
I gave him an account of the difference of practice
which now prevailed within our Yearly Meeting,
in the use of fermented drinks, which were nearly discarded,
and water used as the common beverage.

19th. Was at the meeting of Farmington composed chiefly of Friends,
who are warm and active advocates for the freedom of the colored people,
and of the total disuse of ardent spirits.
They spend much time in discussing these topics; lecturing upon them,
and attending meetings held for the purpose.
There is reason to fear, that dwelling almost exclusively upon these subjects,
there is a danger of getting from under the government of Truth;
and that daily exercise of mind, which is necessary for our spiritual growth;
in which the voice of the true Shepherd is heard,
and we are led along by Him in the way and work which
He allots to the various members of his church.

After a time of silent waiting upon the Lord, who only knows the states of the people,
and what is proper for them,
I was led to open the necessity of being really
brought into the dispensation of the gospel;
in which we come to know Christ to be the Captain of our salvation;
clothing us with his invincible armor,
and making us victorious over the man of sin and son of perdition, in ourselves.
He is given for God`'s salvation to the ends of the earth,
and He will not give his glory to another, nor his praise to any graven image,
or substitute of man`'s devising.
He alone can give lost man a true sense of his condition;
in which state he is spiritually dead,
and can no more bring himself to a correct feeling of his condition,
until he is quickened by Him who is the resurrection and the life,
than a dead body can feel or perceive its state.
The Truth was exalted over all the specious devices of man;
and I had comfort in the evidence that the blessed Helper of his people,
enabled me to discharge myself of what He required.

20th. Had an appointed meeting at Rochester, which was pretty well attended;
and some plain truths were delivered among them;
under a sincere desire that those who had got
wrong might be brought to see their condition,
and through the pardoning mercy of Him who came to seek and to save that which is lost,
be reclaimed and restored to their right mind; and that humble state be experienced,
in which they could wash the Master`'s feet with their tears, and wipe them,
as the poor woman formerly, with the hairs of their head.
Left Rochester after our horses had been fed, and reached our friend B. B.`'s,
a little before night.

22nd. We were at their first-day meeting, which collected very irregularly;
perhaps owing to persons of other persuasions coming in.
It was a long time before we could come at any thing like quiet settlement.
But the way opened at last to treat on the nature of inward, spiritual worship;
which is not performed through a dependence upon man, but upon Christ Jesus,
the Minister of the sanctuary;
who appears in the midst of those that are gathered in his name,
and ministers to their states, enabling them to offer acceptable sacrifices to God,
by and through Him.
The doctrine of the gospel, that we must be made free from sin;
and the dangerous consequence of supposing that we may continue in sin with impunity,
because Christ suffered for our sins, the just for the unjust,
that He might bring us to God, was brought to view.
It seemed to me, there were those present, who regarded the doctrine with some surprise,
and doubted its practicability.
The meeting afforded but little relief.
How many nominal, outside professors and worshippers there are,
who are blind to the real nature of the gospel dispensation,
and the holiness which it requires.
If they go to meeting once or twice a week, and profess faith in Christ,
as their surety against the wrath to come,
a great proportion live in the gratification of their carnal appetites,
without thinking of the necessity of denying themselves, taking up their cross daily,
and following Christ in the way in which He would lead.
Alas what will such a dead, formal religion avail, which leaves the heart unchanged,
and can furnish no substantial ground upon which to rest a hope of everlasting life.

In the morning,
I had a religious opportunity in the family in which we were much broken together,
under a precious sense of the Lord`'s goodness in
providing for us in our pilgrimage through this country;
separated from our nearest connections, at home; and in which,
the kindness of Friends in conducting us from place to place,
and the unity of those who sincerely love the Truth, were felt and acknowledged.
The language of encouragement flowed to some present,
to maintain their ground in faithfully adhering to the Truth; and to the children,
to take counsel of their parents, both in relation to their dress,
and the company they should keep.
In the evening, some Friends called to see us;
and after spending part of it in social converse, we fell into silence,
and I was engaged to draw their attention to the
degeneracy that has overtaken our religious Society,
and to the necessity of individual faithfulness;
both in a daily travail of spirit for their own advancement in the Divine life,
and in the discharge of their duties in the support of the discipline,
and the various testimonies Friends are called to bear.

23rd. It commenced raining early, and continued most of the morning.
We set out for Elba, having our friend B. E. to pilot us.
The traveling was slavish to the horses, and very uncomfortable to us;
the wind being chilling, and the snow driving in upon us.
We stopped in Batavia, dined with E. E.,
and leaving word of our intention to hold a meeting the next day at Elba,
rode there in the afternoon.

24th. Attended the meeting;
in which I believe the Master introduced me into a sense of the states of some,
and qualified to labor with some who were living in creaturely indulgences; and others,
who I feared, were despising the Truth;
while their conduct and conversation were far from that
purity which pertains to the gospel dispensation,
and without which no man can see the Lord.
Faithful, fervent labor was extended; and humble supplication offered,
to the Father of mercies, for some,
that they might be brought into the vineyard to labor;
even if it might be at the eleventh hour of the day.
Also for a remnant who mourn over the degeneracy among them; and for the young people,
that the Lord would lay his hand again and again upon them, and bring them into his fold,
that they may stand for his cause in that place.
Scarcely a single one among them looked like a Friend`'s child,
and I was afraid some of the older ones cared little about it.
In the afternoon we rode to Shelby, seventeen miles.
Part of the road was hard dragging through the snow, which was a little frozen.
This renewed our fears of difficulty in getting on, if we should find the snow deep;
but we try to keep hold of faith, that way will be made for us;
having great cause of thankfulness that the Lord has helped us hitherto.
May we be humbled before Him; wait upon Him daily, for the renewal of our strength;
and may He keep us inward in spirit, watching our thoughts, words and actions,
that the Truth may not be evilly spoken of on our account.
We were kindly received at Shelby, and comfortably accommodated.

The female head of the family appears to be a religiously exercised Friend;
and concerned about the course pursued by some,
in lecturing to mixed companies upon slavery,
and encouraging their children to go to such meetings;
sometimes leaving their own meetings for worship to attend them.
What unsettlement has been produced in some neighborhoods, among Friends,
by the leaders of the people joining with others, in their political, abolition,
or other meetings.

25th. The meeting at Shelby was small.
After a time of waiting in silence, I believed it right to say,
there was such a thing as Christ being pressed down in the hearts of men,
as a cart is pressed under sheaves; and those who are his faithful followers,
must be willing to suffer with Him.
The Apostle said that he partook of the sufferings of Christ,
that remained to be filled up for the bodies`' sake, which is the church.
And Christ said, it is enough for the disciple to be as his master,
and the servant as his lord; if they have called the master of the house Beelzebub,
how much more will they call them of his household.
But if we are planted together in the likeness of his death,
we shall be also in the likeness of his resurrection;
and be raised up to walk in newness of life.
This doctrine may be called mysticism by the carnally minded,
who rely on their own wisdom and strength,
and are unwilling to submit to be baptized with Christ in his sufferings,
and therefore they reject it.
I was enabled to show that there is no other way to be made members of his church,
nor to be preserved alive in the Truth, but by thus submitting to his dispensations.
At the close of the meeting, I felt clear of those who were present,
and peaceful in my own mind.

After dining, we went to Hartland, twelve miles, and put up with kind Friends.
Information was spread of our intention to be at their meeting next day,
and a messenger was sent to Somerset, to have notice spread of a meeting there,
in the afternoon, at three o`'clock;
both of which we attended on the 26th. Some qualification was
given in them to labor to strengthen the things that remain,
that are ready to die; and to encourage those in whose hearts the Lord is at work,
to be faithful to Him, and patiently endure his dispensations;
by which his servants are prepared for his use.
And even where a single individual is thus fitted, like Deborah,
who arose a mother in Israel,
they often have an important influence in leading others in the right way of the Lord,
and in the government of the church.
We rode back to Hartland, part of the way through a wet, logged road,
which was cut in many places into deep holes;
not reaching our quarters until darkness made some part of the ride hazardous;
but we were favored to get through without accident.

27th. After a religious opportunity with the Friends, we set out for Lockport,
to attend a meeting appointed there for us.
The company was one of the smallest we had yet sat with.
I felt empty of everything like a qualification in myself to minister to any one;
but after a time, the parable of the sower who went out to sow, presented;
showing various obstructions to the growth of the seed; and under the humbling,
tendering power of Truth,
I was enabled to hold forth a warning to those who had known the good seed to spring up,
and bear some fruit, lest other things entering into their hearts,
it should become choked, and bring no more fruit to perfection.

28th. We got an early start for Hamburgh, about forty-two miles.
In some places the ground was frozen very rough; having been much tramped up;
which made traveling tedious.
Our course lay along the canal; Tonawanda Creek, which we crossed;
and from there by the side of the railroad to Buffalo.
Here I had the first view of the Niagara River; in which are the grand falls;
of the shore belonging to a foreign nation, and the outlet of one of the great lakes,
for which North America is celebrated.

It inspired peculiar feelings, arising from the grandeur of the scenery,
and the wonderful efforts which man is making to turn the
produce and trade of distant States into these inland seas,
and from there through the enterprising State of New York, to its metropolis.
The great destruction of human life at Buffalo, some time since,
occasioned by a high wind blowing over the lake,
and driving the water up Buffalo Creek to such a height
as to drown a large number of people in their houses,
and to cause the destruction of much property,
cast a shade for a time over the prosperity of the place; and proved how suddenly,
He who holds the power in his hands, can arrest man in his career,
and bring a blast over his proud attempts to aggrandize himself.
We stopped here with S. C, and after taking some refreshment, proceeded to Hamburg,
which we reached about dusk, and put up with a Friend.

29th. We attended the first-day meeting.
My mind was saluted with the language of our Savior to the Samaritan woman,
"`You worship you know not what;`" accompanied with the sense,
that there was a lack in some, of that knowledge of the Father and the Son,
which is life eternal.
Also Paul`'s address to the Athenians, presented,
that as he passed by and beheld their devotions, he found an altar, with the inscription,
"`To the unknown God.`"
The life of religion being almost extinct in many, and perhaps altogether so in some,
I was kept low with it; and administered in plainness what opened upon my mind.

Having twenty miles to ride to the next meeting, we got immediately into our carriage,
and rode to Collins, and put up with a Friend.
He soon despatched a young man with notice for a meeting in the morning,
and we passed the evening in his humble cottage, in cheerful conversation,
and peaceful feelings.
From what I afterwards heard,
there was great cause for our distressing feelings at Hamburg.

30th. The morning was stormy, but a pretty large number convened;
among whom were more exercised Friends than we meet with in some places.
This was encouraging; yet it felt to me there was need in others,
to experience the cleansing power of Divine grace in their hearts;
that they might show forth its efficacy in their lives and conduct,
and thereby invite others into the path of purity;
instead of being stumbling-blocks to sincere inquirers,
and leading the young people from the flock of Christ`'s companions.
He is not a Jew, who is one outwardly, but he is a Jew who is one inwardly;
and circumcision is that of the heart, in the Spirit, and not in the letter,
whose praise is not of men but of God.
For lack of being really, what some desired to be thought by others,
the way of Truth had been evilly spoken of, through their corrupt practices;
and thus the cause had suffered.
I was distressed, when the meeting was over, from having such things to communicate,
fearing lest I might be mistaken;
it is so much more agreeable to be employed in drawing the children to Christ,
and in comforting the afflicted and mourning ones, because of the desolations of Zion.

Afterwards an exercised Friend said, that now it was over, she would say,
that their condition had been truly described;
and she wished that it might have the proper effect.
It was pleasant to have the company of a few honest-hearted Friends at our lodgings;
who were also cheered with having an opportunity
of mingling with Friends from other parts,
who speak a language which they understand, and which goes to strengthen them;
and shows that they are not mistaken in their exercises;
and that the children of our Heavenly Father have similar
baptisms to pass through in their various allotments.

31st. Went to Clear Creek, and attended the meeting appointed for me;
which was slow in gathering,
and thereby disturbed and unsettled by persons coming in late.
It was another laborious opportunity; many manifesting indifference.
I felt peculiar interest in a state present,
which I believed was hungering and thirsting for
something to satisfy the longings of an immortal soul;
and to whom the invitation was extended, to come unto Christ,
who was secretly begetting these desires,
and bringing in his or her view a cloud over the things of this world.
