== Chapter XVII

1845

Continuation of Visit in New York State.

1845, First month 1st. This morning we rose early,
and set out to visit a small meeting at Ellery, about forty-five miles southwest;
but after riding five miles through a woody country,
we found the road so covered with ice--the snow having melted and then frozen,
that we we were unable to proceed with safety.

The great descents and ascents on the hills,
made it dangerous to attempt to pass over them in our carriage;
which would slide from side to side on these narrow, rounding roads,
and render us liable to overturn, or be thrown off them;
and which would be likely to increase as we got to a more mountainous country:
feeling easy to omit the meeting, we returned to the house where we had left our baggage.
From there we proceeded to Buffalo, where we reached about dusk; and after supper,
had a meeting at the house of our friend S. C, with about twenty persons;
who were mostly members, but whose appearance gave little indication of it.
The Lord granted ability to minister to their states,
and the spirit of supplication to intercede for those
who were endeavoring to walk in the right way;
that his power might be manifested to sustain them,
and renew their faith when reduced and proven;
and that the young persons might become enamored with the Truth,
and drawn from the delusive gratifications of this vain and transitory world.
This opportunity was relieving; and induced the hope, from the feelings of peace,
that I was not forsaken; for after passing through what I had for several days,
and the necessity to turn back from Ellery;
I began to fear lest I was mistaken in proceeding,
and home and my beloved family being brought very near, in affectionate recollection;
the thought presented, whether I had not better turn homeward.
But the next morning,
it seemed proper to pursue my original prospect of going into Canada;
and after getting a clearance from the customs officer, which detained us some time,
we crossed the Niagara River; and the officer there making no difficulty,
we rode nineteen miles on our way to Pelham,
and put up our horses to feed near the great falls.

Here we had a fine view of this stupendous cataract.
The whole body of a great river, the outlet to these inland seas,
which lie to the west and north-west,
pouring over a breastwork nearly two hundred feet high, of massive stone,
and in width about one mile.
The rushing and roar of this mighty torrent, the foam and spray,
created by its dashing on the rocks below;
the formation of a perfect rainbow by the rays of light decomposed in the vapor,
constantly rising and falling again like a thick shower of fine rain;
and also the foam and vapor and rainbow colors mingled together,
in the various parts of the cascade,
presented one of the grandest scenes that I had ever beheld.
It far exceeded my imagination of it; and to me, it was surprising,
that any one could turn from it with disappointment;
but as magnificent and overpowering as are these extraordinary falls of water,
they are an atom in the great works of the Almighty Creator.

We were late getting to a Friend`'s house at Pelham;
having ridden fourteen miles after four o`'clock;
part of the way along the Well and Canal, which connects Lakes Erie and Ontario;
and night coming on, made the road in some places difficult and dangerous.
It was a great relief to us to be overtaken by a kind Friend,
who supposing from our carriage that we were Friends, rode up to our guide,
and ascertaining who we were, piloted us to his house.

3rd. Had an appointed meeting at Pelham;
in which the call and qualification for the ministry,
and the preparation requisite for the reception of this and
all the diversified gifts which the great Head of the church
dispenses to those who yield to his sanctifying power,
came before me; and which, after a time of silent waiting, I believed it right to open.
After our Savior commissioned his disciples to teach all nations,
He directed them to tarry at Jerusalem until they were endued with power from on high.
Paul, speaking of his ministry, says "`He neither received it of man,
neither was he taught it but by the revelation of Jesus Christ;`" and
there remains to be no other source for the work of the ministry,
down to the present day.
This was the experience of Friends from the beginning,
who were brought off from all dependence on themselves, or on any man,
to wait upon the Lord; from whom they received gifts for the ministry,
and for judging in Israel, to discern and try words and spirits.
It was not a time of abounding.
The meeting appeared to be in rather a languishing state; the members, I feared,
depending too much on vocal ministry.
They were exhorted to gather to the Divine gift in themselves,
that they might receive ability to worship the Father in spirit and in truth,
and to partake of that food which the Son of Man will give.

Being detained that afternoon by the stormy weather,
I had some serious conversation with the Friend at whose house we stopped.
He expressed much concern at the state of the Society among them;
particularly on account of ministers encouraging a coalition with other professors;
speaking lightly of some of the testimonies held by us; and of our early Friends,
as having been contracted and illiberal.
I encouraged him to keep to the ancient ground;
for I believed that all such defective members would finally show more clearly,
that they were destitute of the life and substance of religion.
This is one means by which the growth of our Society is greatly obstructed;
the young people, who are in the air, being delighted with such sentiments;
which make way for them to indulge in the corrupt fashions and language of the world;
and to mingle with others, until they lose all relish for serious things,
and for their own religious Society;
whose principles they judge to be too strict for them.

4th. We rode to Stony Creek, and lodged at a tavern.
Next morning rose early, and went seven miles to Hamilton, at the head of Lake Ontario,
to breakfast; and about two o`'clock got to O. Ws, at the Jersey settlement.
He and his wife, and one son remain members, the rest having left the Society.
They are thirty-two miles from Norwich, to which meeting they belong;
which shows the disadvantage of members settling themselves,
so as to be out of reach of meetings and the company of their friends.
We found it had been a stopping place for many of our English Friends, passing through,
and for others traveling in the work of the ministry; but,
it is affecting to find members located where they, with a rising family,
are deprived of the advantages of religious society.

Notice being spread, a pretty large number of the neighbors collected, in the evening,
with whom we held a religious meeting.

For a time I labored along with difficulty, but at length Truth arose,
and qualified to set before them the importance
of being true believers in our Lord Jesus Christ,
and the danger of resting in a mere historical belief,
without knowing Him to save us from our sins.
Those who had known the shedding abroad of Divine love, tendering their hearts,
convicting them of sin, and bringing them under the baptism of repentance,
were warned of the danger of resting in the
conclusion that they had now obtained religion;
and when the Messenger of the covenant appears as a refiner`'s fire,
and as a fuller with soap, further to purify them, turn away,
apprehending they are already regenerated;
and thus fall short of that perfect redemption,
and growth from stature to stature in Christ, which makes the true Christian.
The opportunity was closed with prayer to the Father of Mercies,
for his continued goodness in visiting the souls which He has made;
reviving the work in the midst of the years of some,
and granting preservation and strength to perform our duty to Him and to one another.
I thought some of the company were brought under serious feelings,
from the manner in which they spoke with us; which I found afterwards to be the case.

6th. This morning we set out for Norwich, but had not proceeded far,
before one of the iron axletrees broke in the middle, and the carriage being on a long,
steep hill, up which I was walking,
I could not make my companion hear until the wheel was
completely separated from the under works;
tearing away part of the frame, and the wood work on the axletree.
We took off the body, and put a drag under the end of the broken axle;
secured our baggage upon it to return to O. W.`'s,
but as my companion was driving the horses down this steep, icy hill,
finding their shoes too smooth to hold back, they ran down so fast as to throw him down,
and being obliged to let go the lines to save himself
from being thrown over the precipitous side of the hill,
they went off with full speed through the woods, and striking a stump or two,
broke one of the forewheels to pieces, and so shattered the remainder,
that at first sight, we doubted whether it would be worth attempting to have it repaired.
The horses were stopped after running, perhaps, an eighth of a mile,
by a man working near the road,
or they would probably have ruined themselves among the trees and high stumps.
Our situation, as we walked up the corresponding hill, out of the valley,
to see what had become of them, felt discouraging; yet in the midst of our troubles,
it was cause of thankfulness that we were preserved from serious injury.
After viewing the ruins, we became more composed;
procured a man with his wagon to carry the wreck back to O. W.`'s,
and from there sent to a carriage-maker; who said it could be repaired in a few days,
while we were gone to Norwich; and our friends were very kind,
doing everything for us they could.

7th. Two persons agreeing to drive us to Norwich, in a lumber wagon,
our runaway horses were put to it, and we reached Wm. B.`'s,
near the meeting-house before dark; having ridden thirty-two miles,
about half of it in a driving snow, which, in an open conveyance,
was an unusual exposure to us; but we did not suffer much inconvenience.
The company of consistent Friends who are interested in the welfare of our Society,
had a cheering effect, after our disaster,
and we passed the evening in suitable conversation.
But the wormwood and the gall would come up in remembrance,
and in the night season I tried to cry to the Lord for
an evidence that I was in my right place;
but his face seemed to be hid from me;
and I hoped it was a dispensation for my renewed humiliation,
which in time would be followed with good.
It seemed like the chastising rod: perhaps I had grown a little too easy,
after some of the helping seasons I had been favored with.

8th. Went to meeting, which is perhaps the largest country meeting in this Yearly Meeting.
I felt poor, and fearful of being wrong or doing wrong;
but strove to look up to the Master, and to wait upon Him for direction.
Two states were brought before me; one a low, suffering seed, not numerous,
but who were endeavoring to fill up their measure of duty,
and whom the Lord qualified to behold the gradual lapse of some from the Truth,
and what they had once known of it, and who mourned over such.
The other, one that is sunk in the earth,
exerting every faculty and energy to acquire property;
by which their time and thoughts are absorbed; so that the work of salvation,
the necessary daily, spiritual food for the immortal soul,
and a deep and living concern for the education of
their children in the fear of the Lord are overlooked;
and the lambs entrusted to their care are suffered to run at large,
entering into various kinds of society, and into the corrupt practices of the world.
After a time it appeared proper to open these views, which I did in weakness and fear;
the enemy doubtless striving to hinder the work by his suggestions that I was deserted,
and all I could say would do no good.
But I kept patient and low, and spoke as things gradually arose; and after a time,
the Lord in mercy touched our hearts with the finger of his love and tendering power,
and brought us to tears;
giving me a renewed sense of my nothingness and inability to do anything without Him;
and his compassionate goodness was felt so as to affect many of us,
and to carry conviction home to others.
My soul humbly bowed in reverence and thankfulness before Him.
The business of the Monthly Meeting was transacted, I had no doubt,
on the part of not a few, under a sincere concern that it should be rightly managed.
I feared, however, they were too easy in receiving persons into membership,
and I mentioned, it was easier to increase a nation,
than to increase its joy and strength.
My companion was afterwards told,
that the condition of the meeting was remarkably described.
So that we have cause to trust in the Lord at all times, keeping a single eye to,
and closely following his leadings, though in fear and weakness.
After dining, we set out on our way back to a Friend`'s house, five miles;
called on M. P., a minister and a widow with eight children;
with whom we had a religious opportunity, encouraging them to be faithful to the Truth,
and the Lord would be a father to them and preserve them;
which brought them to tenderness and tears.

9th. We returned to O. W.`'s and found our carriage repaired.
The next morning, after a sitting with the family,
from whom we had received much kindness and attention,
we set out on our journey towards the north side of Lake Ontario;
and after dark reached the house of an English family,
part of which belongs to our religious Society.
Here we lodged,
and were brought into sympathy with them on account of some
keen afflictions which they had been passing through.

11th. This morning, after they had read a chapter, at the breakfast table,
of which I was glad to find them in the practice,
I believed it right to say that all the dispensations
of Divine Providence are in inscrutable wisdom,
and tend to hide pride from man.
Some trials we bring on ourselves, and some are brought upon us by others;
and I exhorted them, under their afflictions,
to humble themselves before their Heavenly Father inquiring of
Him what is his will concerning them in these things,
and applying to Him for the help of his Spirit, to profit by them.
The ride along the lake was rather dreary, through fields of stumps, dead trees,
and forests of growing timber; which made the sight of a busy town,
as we approached Toronto, quite cheering.
It seemed like coming into the civilized and habitable parts of the earth once more;
and after turning into Yonge Street, we were surprised at the cultivated land,
and the great number of good buildings, thickly strewed along this fine road.
We put up for the night, at a tavern, nine miles from the city,
where we had excellent provision for ourselves and horses.

Requesting an early breakfast, we rose between five and six o`'clock,
and a little before seven were in our carriages;
having twenty miles to ride to Yonge Street Meeting; which we accomplished with ease,
the road being smooth and frozen hard.

12th. First-day took some refreshment at a Friend`'s, near the meeting-house,
and then went to the meeting; which was not large.
The Master gave the word, and the states of some were ministered to; in which I had peace.
Speaking of the effect which submission to the Spirit of Christ would produce,
in separating man from the love of his worldly possessions,
I mentioned how much quarreling about property would be avoided;
every one being willing to suffer, rather than do wrong to another;
looking upon themselves, like the early Christians,
as stewards of their earthly substance;
willing to appropriate it to relieve the necessities of others,
after providing for themselves and their families.
The Friend with whom we stayed said one man at meeting would understand, at least,
a part of the communication;
being of a family much given to contention about their inheritance.
Being altogether strangers to everybody here,
it was confirming that the Lord still condescended to help us,
his poor dependent servants, from his sanctuary.
We lodged with the Friend at whose house we called.

13th and 14th. We had appointed meetings at Whitchurch and Tecumseh;
in which I endeavored to do what appeared to be required.
They were both small meetings, yet the houses were nearly filled;
and though considerable part of the assembly were not Friends,
they sat with becoming seriousness and quiet.
In the latter meeting,
I was particularly engaged to speak on the many trials
and afflictions which overtake us in this life;
and it being rather unusual for me to dwell so decidedly upon that subject,
I mentioned that I did not know there were any present under peculiar trial,
but if there were, I wished such to profit by them,
and be instructed in the great instability of earthly possessions.
In supplication to the Father of mercies,
I was led to petition that the everlasting arms might be underneath;
to sustain those who are in affliction, and that their faith might be renewed in Him.
The Friend who took us to the meeting, told us, as we were riding back to his house,
that two or three days before, a person intoxicated,
attempted to commit personal injury upon an industrious, orderly young man;
and also had threatened to burn down the outbuildings on his farm,
which he had made some effort to accomplish;
and that this young man and his brother were at the meeting.
How necessary, in the little services we may have to perform, to keep close to our guide,
and not attempt to choose for ourselves,
or refuse to communicate that which the omniscient One gives.
I mention this, as I hesitated, in my own mind, to speak on afflictions;
because it is a subject easily and often commented on;
but nothing else appeared to come before me to say.
We had a cold ride in a sleigh, of fifteen miles,
out and back to the house of the Friend, who, with his valuable wife,
took very kind care of us.

15th. Attended the Select Preparative Meeting, and on the 16th,
the Monthly Meeting of Yonge Street.
The latter was a large collection of Friends;
amongst whom I had a close testimony on the degeneracy of many, who, like Ephraim,
have joined themselves to idols; and whose strength strangers have devoured,
and they know it not.
The eager pursuit of wealth, has so absorbed the time and energies of many,
that they are a dead weight upon the Society; deriving little or no benefit from,
and conferring none upon it.
These neglect the imperative duty of Divine worship,
keep their children from the way of Truth, and their religious meetings.
The meeting minuted its unity with the labor.

This morning we found snow had fallen through the night,
and pretty soon it commenced again, and fell constantly through the day.
We try to hope that the good Hand will keep and provide for us,
so that we shall be able to accomplish the service required,
and join our beloved families in peace.
The distance between us and our homes, seems greater, owing to the inclement season,
and the dangers of the way; but the Lord can strengthen us to surmount them all.

17th. Lodged the second night at E. D.`'s, near the meetinghouse;
who appeared to understand the state of our religious Society,
and with whom we had some conversation about it.
The Monthly Meeting holding late yesterday,
we did not set out for Uxbridge until this morning.
We were kindly conveyed to it in a sleigh,
by one of the Friend`'s sons the distance being eighteen miles.
The carriages were driven to Pickering by two
young men who came up to the Monthly Meeting;
to which Friends of that place belong.
The weather was stormy; hail, rain or snow falling most of the time;
yet we suffered but little from the cold, and got in earlier than we had looked for.

Twelve miles of the road were through a wilderness, in which we saw but one house;
and bears, deer and wolves are found there in considerable numbers.
We quartered at the house of a Friend, who went from Pennsylvania;
but his mode of living is not quite like that in
the thickly settled counties of that State.
Yet he appeared to be in a thriving condition.
A Friend having gone on before, to spread notice for a meeting,
a company of Canadian-looking men, with woollen caps,
and a corresponding number of women, nearly all of whom had children with them,
assembled in their small meeting-house,
surrounded by snow fifteen or eighteen inches deep.
Though I felt empty and somewhat depressed,
yet Divine help was extended to speak to their conditions,
and to hold forth the indispensable necessity of working while it is day,
in the vineyard of their own hearts; before the night comes, in which no man can work.
The sight of so many women who had turned out with their infants, in snow and cold,
impressed me with the belief that they wanted to meet with good,
and I hoped they were not disappointed.
It came before me, to allude to the hardships that mothers have sometimes to endure;
the continual care of the children,
and the necessary provision for them and their families;
which much confined them at home; and to plead a little, with their hardy husbands,
to divide the toil, and to soften, as far as in their power,
the difficulties their wives have to endure.
I think the tendering power of Truth was felt,
and they shook hands very cordially with me when the meeting closed.

18th. This morning the weather was cold, and the wind from the northwest;
but our road lying much through the woods, we were a good deal defended from its force.
Before we started, I was drawn to sit down with the family,
and to remind them of the uncertainty of their earthly possessions,
and that riches can do nothing for us when the end comes:
and of the infinite importance of making ready for that awful period before it arrives.
I thought the man,
who has labored hard to get comfortable accommodations for himself and his cattle,
but is so much occupied by it, that he does not find time to attend his Monthly Meeting,
and perhaps others, felt what was said:
he parted with us in an affectionate and serious manner.
In the afternoon, we got to a Friend`'s, at Pickering,
where we were kindly received and entertained.

19th. We attended their first-day meeting,
in which the life and power of religion felt to me to be low.
The Lord enabled me to search into the condition of things among them;
to show the stumbling effect which those have,
who are not producing the fruits of religion in their lives,
and how they are looked on by honest people, who do not make such high profession.
Also the danger of forsaking silent waiting on the Lord,
and running into the expression of words, to gratify a restless disposition,
was spoken to, as being comparable to Saul, who without Divine authority,
made an offering in the absence of the prophet Samuel,
lest the people should be scattered; but whom the prophet told he had done foolishly.
The true preparation and qualification for the ministry were alluded to;
and the suffering remnant among them were encouraged to abide at the Lord`'s feet,
and to endure the baptisms which He administers; that so they may grow in grace,
and in the saving knowledge of their Lord and Savior Jesus Christ.
I felt constrained to bow in supplication for the few who are striving to keep the faith,
and to bear, though in fear and in meekness, a faithful testimony for the Truth,
and that those who are holding back, might be stirred up to more zeal and devotion,
and be brought forward in their ranks and service in the church.
Though I was favored with holy help, yet I came away in poverty, and some discouragement,
on account of the state of the members.
We were afterwards told of some things which confirmed my feelings.

Dined with a Friend, at whose house we had the company of several others.
In the morning, a Friend kindly offered to convey us in his sleigh to Haldemond,
fifty miles.
The thermometer stood at seventeen degrees above zero.
We covered up in buffalo robes, and though the weather was cloudy,
and the wind rather in our faces, we travelled comfortably in an open sleigh,
and reached J. S.`'s before night, who took us in very heartily.
A cheerful reception after traveling an obscure road, through a strange country,
is grateful to weary travelers, and should be thankfully accepted.

21st. The Friend who brought us here returned to Pickering,
and J. S. took us over to the house of a Friend, near Haldemond meeting-house,
eight miles; and also agreed to convey us to Cold Creek, where, he said,
we would find Friends to take us to Ameliasburg.
Our far separation from home at this wintry season, the almost constant cloudy weather,
with the falls of snow, have a depressing effect;
and the great distance between the meetings, makes our getting on tedious.
It is especially trying,
when we are placed in the care of those of little religious experience,
or who are not under the sanctifying power of Grace,
and cannot sympathize with and help us,
in bearing the burdens that attend these visits to the churches.
May the Lord, in tender compassion, regard and visit his people,
arouse some from their supineness; renew the confidence of the upright-hearted in Him,
and show unto us, by raising up servants and handmaidens, that He will not cast us off,
and take his name from our religious Society.

I felt myself in a low state, and did not know how the meeting,
which had been appointed here, would be got through.
But after sitting down, the language passed through my mind, "`The same Lord over all,
is rich unto all that call upon Him.`"
Again, "`Call upon me in the day of trouble, and I will deliver you,
and you shall glorify me;`" and faith sprang a
little in my heart that He would not forsake,
but in his time, change the dispensation.
The company was small, and I was enabled to minister to them,
so as to bring some under serious feelings.
They were affectionate in taking leave of us at the close.

22nd. J. S. came to us quite early in the morning,
and we rode twelve miles to a Friend`'s house, and refreshed ourselves and horses.
Cleanliness and godliness are very properly associated,
and have a happy influence on the feelings.
They give zest to simple fare,
and open the springs of friendship and union between
those who before have had no acquaintance.
These Friends are much secluded from our religious Society;
but they came to the meeting at Cold Creek.
On getting to W. V.`'s, arrangements were made to spread notice of a meeting next morning.
He and his family were from Ireland;
and appeared to have mingled with cultivated society;
being intelligent and well-informed of the principles and order of Friends.
We do not rely on learning, as an essential qualification for religious service,
but association with those of cultivated, religious minds,
is very pleasant and profitable.

23rd. Went to the meeting; in which were many persons of consistent appearance, and,
I have no doubt, honest in their love to the cause of Christ.
The blessedness of living and walking in the Truth, and being faithful to its requirings,
coming before me, I was strengthened to encourage the sincere-hearted,
and to plead with the earthly-minded, to yield to the convictions of Divine grace,
that thereby they may be brought into the love and service of their Heavenly Father.
After a short, tendering opportunity with our kind friends, we set out in his sleigh,
between three and four o`'clock, and rode through a rough, hilly country,
to the head of the bay of Quinti, and down along the lake shore, through a flat plain;
over which the wind swept with chilling force; and after a ride of twenty-five miles,
got to a Friend`'s house about eight o`'clock.

24th. The weather this morning proved to be rainy, and looked cheerless;
but notice having been spread, the members of Ameliasburg, generally assembled;
and through the goodness of the blessed Head of the church, we had a favored meeting.
His solemnizing presence spread over us, and the gospel was preached,
and the states of some reached.
It was a relieving time, and encouraged me to hold on,
in endeavoring to complete the service of this visit.

We went to J. C.`'s to lodge, which we found a comfortable resting place.
Marrying contrary to the discipline is so common in Canada,
even with some from whom a different example should be expected,
that the testimony against the practice, cannot be said to be maintained.
Some Friends are so weak, that they seem to approve, rather than disapprove,
of this violation of our wholesome discipline; on the ground, as they say,
that instead of losing a member, the Society mostly gains one.
But in the first place,
it lays waste the qualification of the offender to support the discipline,
in other cases, if he is retained in membership,
by "`offering a paper,`" as it is termed.
And when the discipline is loosely administered, weakness overspreads,
in relation to an upright and impartial course in other respects.

Secondly, if the party who had never been a member is received,
for the sake of accommodation,
or without real convincement of our principles and testimonies,
weakness and blindness may be, in like manner, introduced through this channel;
and thus meetings for discipline, become formal, lifeless appendages to the Society.

25th. In the afternoon we rode to J. B.`'s, where we lodged; and in the following morning,
being first-day, (26th,) were called for by J. C, who took us to West Lake Meeting;
which was large, and the forepart of it disturbed by persons coming late,
and moving about in the house.
My companion requested the boys in the gallery to keep still in one place,
and not be walking about, disturbing the meeting;
which had a good effect above and below stairs.
I felt desirous of keeping my place, as the Master should appoint,
and the way not opening to communicate anything, the meeting closed,
to the surprise of many.

We rode five miles to Pictou, and dined with a well-educated family.
The plain appearance and correct deportment of their children were cheering;
and before we left the table, I felt a word of encouragement to arise,
for them and their parents.

Notice having been sent to Adolphustown, for a meeting on second-day,
we crossed the bay of Quinti, on the ice, and lodged at W. C.`'s,
whose dwelling is situated a short distance from the water; a beautiful site.
These aged Friends came from the United States, into Canada, about fifty-eight years ago.
They used a boat on the different streams in the route,
which they had conveyed in wagons, from stream to stream;
and when they reached Oswego River, they descended it into Lake Ontario;
and went round to the outlet of the lake, into the bay of Quinti.
They travelled as the weather permitted;
landing on some part of the shore suitable for passing the night;
until they reached their stopping-place in Canada.
Their account of the difficulties they met with,
and their progress in making a settlement, was interesting.
Both of them, being now over fourscore years of age,
still retain a good share of mental strength;
though the husband is not able to pronounce his words perfectly,
owing to a paralytic affection.
They were among the first Friends who held a meeting in Canada;
and Adolphus was the first established meeting; its decisions as a Monthly Meeting,
being, as they informed us,
subject to revision and confirmation by a Monthly Meeting at Stanford.

27th. Attended the meeting at Adolphustown;
and labored to strengthen the faith of those who were often tried;
and to set forth the importance of a change of heart in the unregenerate.
The Master mercifully condescended to help us.
Returned to West Lake in the evening.

28th. At the Half-years Meeting of Ministers and Elders--a low time to me;
yet I did not feel easy,
without endeavoring to hold up the great responsibility of the stations they occupied;
the indispensable necessity of enforcing the doctrines of Christ, by example,
in all our interaction among men;
that the source of all true gospel ministry is the Great Head of the church;
who by his Spirit, opens to the minds of his servants,
what He ordains them to communicate to the people;
and that the same Spirit also gives a true discerning to elders;
by which they may rightly distinguish between that which comes from the true Spring,
and the deceptive workings of the natural reason and the imagination.
The necessity of the faithful discharge of their duties,
in laying a hand upon spurious offerings, was pressed upon them.
The practice which generally prevails, of sending for ministers to attend burials,
as if the dead could not be interred in a christian manner, without preaching,
was brought into view, and Friends were cautioned against encouraging it,
by going to places out of their own neighborhood, for such purpose,
unless under a sense of religious duty.

On the 29th, the Meeting for Discipline was held; in the forepart of which, many spoke.
I felt not a little grieved with a sense of the lack of sound and faithful elders,
and a right feeling of the order which belongs to the church of Christ;
in which the servants and ministers know how to keep their places,
under the direction of the great Lawgiver.
After a time,
I believed it right to bear testimony to the necessity of enduring suffering,
in order that we may reign with Christ; that being baptized into death,
we may know what it is to be raised up, by Him, who is the resurrection and the life;
and to encourage a remnant who were in suffering,
to be faithful to their Lord and Master.
One of the ancient martyrs said, though she could not say much for Christ,
she could suffer for Him.
It is through baptism, we are prepared to receive gifts,
and to be put into the stations which the Great Head designs us for, in his church;
and without this experience, none can take part or lot in the work of the Lord.
If they attempt to be active, in their own will and wisdom,
they minister death instead of life; wound themselves,
bring distress over the living members, and confusion into the church.
The true servants of Christ, who know how to keep their ranks in righteousness,
have the sentence of death in themselves, not to trust in themselves, but in God,
who raises the dead.
These in their services, are a savor of life unto life,
and of death unto them that are dead.
The Master helped me to discharge myself honestly,
and Truth came over some restless spirits.
The young people were invited to come under the
refining hand of the Baptizer of his people,
that by his cleansing power, they may be prepared for usefulness in his church.
A Friend returned thanks for the continued goodness and condescension of the Lord,
in manifesting Himself for our help, and the meeting proceeded to the business.

Some things which were cause of uneasiness, were brought before Friends;
particularly the neglect of frequently reading the Holy Scriptures;
both apart from their families, and also to them, at proper seasons.
Many going out of the Society in marriage, and Monthly Meetings conniving at it;
such disorderly persons being kept from attending their meetings for business,
but a short time,
and then undertaking to sit in judgment on other violations of the discipline.
These in their turn, are prepared to connive at the wrong doings of others,
and thus contribute to lay waste the order,
the discipline and the authority which were conferred
by the Head of the church for its health and growth.
Friends were also cautioned against the practice
of attending meetings held by the separatists,
by which the principles of young and old, may be subverted, and the advantages lost,
which we ought to derive from being a people, devoted to the Lord and his truth.

On fifth-day was held their usual public meeting for Divine worship.
I felt no ability for any public service.
In the afternoon we rode fifteen miles to A. E.`'s, widow of the late T. E.;
whom we heard spoken of as a sound minister, belonging to Adolphustown Meeting.
We found her house an agreeable lodging and resting-place,
where travelers are kindly entertained.
Next day, the 31st of First month, went to Camden, thirty-two miles,
situated in a newly-settled country.
The weather was very cold; and when about half way on our journey,
we called at the house of a kind person, warmed ourselves, and got some dinner;
and towards evening, reached our lodging-place;
which was warmed with a large stove in the room where we slept,
and one in the adjoining apartment, as well as a fire in the chimney;
all which were necessary to make us comfortable.

Second month 1st. This morning we found the thermometer at twenty degrees below zero;
the atmosphere clear and calm.
In new settlements,
where the benefits of religious education and habits are not always discoverable,
there is reason to fear that that circumspection, which true religion requires,
is not attained, as it ought to be, among some.
Population being thin,
it is natural for persons to seek such society as is within their reach;
and where there is a lack of christian watchfulness,
improper associations may be indulged,
obstructing the elevation of the standard of truth and righteousness.
In the meeting which we held here with the Friends and their neighbors,
I was exercised on the danger of mingling with
persons of uncertain principles and evil habits,
who have little or no reverence for religion and I warned them
against allowing their children to associate with such;
lest they should be poisoned in principle, and spoiled in their manners and conduct,
other subjects, as they were brought before me, were spoken to.
Afterwards, a Friend said, if they had told me beforehand their situation,
it could not have been more fully described;
which is another proof that the spring of all true gospel ministry,
is in Him who has the key of David: to whom all the honor and praise belong.

We rode back in the evening to A. E.`'s,
for the purpose of being at West Lake on first-day, not feeling clear of that place.
The ride was cold, and the latter part dangerous, on account of the slippery,
iced surface of the Bay road; where we had fears of gliding off, in the dark,
and were glad to get into our warm lodgings.

First-day morning, the 2nd, the thermometer was ten degrees below zero;
and having fifteen miles to ride, we rose and started early; the air was pinching cold.
Had a laborious time at meeting, with some whose spiritual faculties seemed blunted,
so that they have little qualification to engage in inward, spiritual worship,
and little energy to maintain our religious testimonies.

Called and dined at the boarding school,
and had a word of exhortation to the teachers and the scholars.
Rode back to A. E.`'s, rather weary, and after supper,
had a religious opportunity with the family.

3rd. Rode twenty-six miles to J. F.`'s, near Kingston,
and had a meeting at their meeting-house, about five miles distant,
with Friends and others.
For a time, I felt afraid that the Lord had deserted me, which brought me low;
but before the close, I hope He opened some things for the instruction of the people.
I returned to our lodgings in a humbled state of mind;
probably in part to prepare me for the trials which succeeded.

4th. As we came from meeting it snowed, and so continued through the night;
and this morning the weather was stormy; presenting a very dreary, discouraging aspect;
but notwithstanding, we set out and rode forty-six miles, through a severe snow storm,
to a Friend`'s house, five miles short of the meetinghouse at Leeds;
and glad we were to get under a warm shelter out of such inclement weather.
Here we found a large family of children, and the Friends in slender circumstances;
which caused us to feel much for them, and for their children.
Such have many hardships to encounter;
and their time being almost wholly occupied in providing necessary food and clothing,
leaves but little opportunity to give direct attention
to the habits and mental improvement of their offspring.
Yet such is the great importance of right
principles being impressed on their tender minds,
and adopted, they should do what they can,
to bring up the children not only in industry and cleanliness,
but instructing them in useful branches of learning;
in frequently reading the Holy Scriptures; and, above all,
to turn their hearts to the teachings of the Holy Spirit,
that they may be brought to live in the fear of their great Creator.
By this godly care, enforced by example,
the minds of the children would be stored with knowledge,
that would raise them above the practice of low jesting,
and trifling conversation on subjects or occurrences of a frivolous character;
and which tend to degrade the mind.
How responsible is the standing of those who are
engaged in instructing others in the work of religion.
While advocating the power of Divine Grace,
how ought they to show its efficacy in themselves,
and in a proper concern and care for their offspring.
Where practice does not enforce precept, there may be reason to fear that,
persons have mistaken their sphere in the church, and are carried away,
by creaturely activity, abroad,
as a substitute for the faithful discharge of domestic duties.
The profession of Divine guidance is brought into disrepute,
by the neglect of our own families,
manifested by uncultivated minds and irreligious manners;
however zealous we may appear for the welfare of others and their children.
Such may find it much easier to counsel others how they ought to live,
than to restrain and rightly tutor the lambs committed to their care.
There are persons in low circumstances, who, by their industry and prudent management,
bring up their children in habits of sobriety and proper labor,
and also get for them suitable school learning;
but it is generally those who stay much at home, minding these important duties;
and thus are a blessing to their families; and their children, as they grow up,
are often a blessing to such parents.

5th. Though the storm continued, and much snow fell through the night,
we believed it right to endeavor to get to the meeting;
but little did we know of the difficulties in our way.
We soon found ourselves in a depth of snow,
through which the horses could not draw the sleigh more than a rod or two,
without stopping to get breath.
After proceeding about a mile, with much difficulty, we desired our guide,
who was on horseback, to go to a Friend`'s house,
and get him to come out with a yoke of oxen, to break the road before us.
The Friend followed his oxen, often above his knees in the snow, in their track,
continually urging them forward.
We dragged after them at a slow, laborious pace, about a mile,
when he thought it impracticable to go further,
and advised us to return to the house we left in the morning.
To this we were decidedly opposed,
as the house we wished to reach was but one and a half mile distant.
We stopped at a house near the roadside, and though discouraged,
we prevailed on the man to get out his oxen to aid us; but one of them proved so weak,
he was unable to push through the snow, even without anything to draw after them.
He had neither accommodations for us, nor stabling for horses; and, of course,
it was necessary to make attempts to get on.
The man, without his oxen, accompanied us, assisting the Friend to drive his oxen;
whom we occasionally relieved by taking him on our sleigh.
Several kind persons, seeing our situation, turned out, and assisted breaking the road,
by trampling down the snow, sometimes up to the waist,
until we reached another farm-house.

Here they kindly yoked up two pair of oxen, and attached them to a sled;
and another person turned out on horseback, so that we soon had the road so open,
that we got to Harvey Derbyshire`'s; four miles from our starting place in the morning.
It was now after twelve o`'clock;
we having been about four and a half hours coming four miles;
and truly glad we were to find ourselves within reach
of so comfortable a shelter for ourselves and horses.
I had never experienced such feelings, from the apprehension of the consequences,
should we be left in fields of snow, by our horses getting down and giving out;
the harness breaking, and no houses within reach.
But we had cause for thankfulness,
that we were released from such dangers and sensations, and hospitably provided for.
The storm continued,
and I felt much concerned about the Friend who had
between two and three miles to travel back to his home;
lest he should be overpowered by the depth of the snow: he, however, got back safely.
The snow was so banked up about the house,
that they were fearful the cattle would get amidst buried in it;
and the Friend and his boy were up in the night, to ascertain their condition.

Next day I had a chill, and was obliged to go to bed; as it subsided, fever came on,
which went off towards night, with profuse perspiration;
and I hoped it would terminate the disease.

7th. The road being pretty well broken, we went to P. W.`'s, near the meeting-house;
and the next day I had a return of chill and fever.
The disease constantly prostrating me, the severity of the climate,
and the great distance from home, made my situation feel serious;
which was increased by the state of the roads;
and I have seldom passed through a greater trial of faith.
A Friend rode eight miles to the residence of a physician, but he had gone to Brockville.
Of course, he did not find him;
but P. W. going out about a mile in the opposite direction, to attend to some business,
met him and brought him to see me.
Having quinine with him, he prepared me a mixture,
and giving me directions how to take it,
expressed the belief that the disease would not continue long; which was encouraging.
The fever went off as before, and I took the medicine faithfully.

9th. This morning the thermometer was twenty-two degrees below zero,
at eight a.m. Though the doctor had advised me not to go to meeting,
yet as it was first-day, and I was desirous to do the work that might be required,
so as to be prepared, when able, to take my departure, I wrapped up well and went.
A large company collected, towards whom I had some service, but being weak,
and the house rather warm, I was not able to stand long.
When the time to close came, I requested Friends to remain together,
while others withdrew; and after a pause,
the way opened to address them on the preparation,
call and qualification for the ministry of the gospel, and the duties of elders;
also on the danger of mistaking our calling;
and hence the necessity of lowly watchfulness before the Lord,
and the spirit of discernment in those, whose place it is to judge;
that they may be qualified to counsel those who may speak
merely to answer the cravings of the people for words,
for fear they will be scattered.

The danger of setting up a man-made ministry,
out of which the Society was originally gathered, was opened;
that thereby the testimony would be laid waste, which the Lord gave us to bear,
to the spiritual character of Divine worship, in silent, reverent waiting upon Him.
When persons mistake their calling, and elders do not discharge their duty faithfully,
in silencing such intruders, they bring distress upon the living members,
and often make a party to support them; which introduces difficulty into a meeting.
In transacting the affairs of the church,
they were exhorted to retire to the gift of God in themselves,
as in their silent approaches in Divine worship;
that they may be made acquainted with their respective duties and services,
and enabled to perform them;
and when they have delivered what was impressed on their minds to say,
to leave it before their brethren and sisters, without urging it, and ruling over them.
Christ is given to be Head over all things, to his body the church.
These things were laid before them in love,
with a sincere desire they might be found laboring together for the faith of the gospel.

I felt very feeble on returning to my lodgings,
and being able to take but little nourishment, I was depressed with the apprehension,
that for lack of suitable aliment, I should sink so low as not soon to be able to travel.
Home, and my dear connections were far distant,
and such a great body of snow lying on the ground,
and it being probable still more would fall before long,
my faith seemed almost ready to fail; but looking up to my Heavenly Father,
I was enabled to pray to Him, that He would not permit anything to fall upon me,
that I could not bear, lest the spirit which He had made, should fail before Him.
I was oppressed in body and mind, and at the usual hour, retired to rest,
and after some conflict with the reported difficulties of crossing the St. Lawrence,
finally got asleep; and in the morning, rose somewhat refreshed.
As I sat alone in my lodging-room, an intimation was given me,
that my sufferings in that place, were at an end;
and then I knew that I should not be much longer kept there.
The weather proved more moderate, and though it was the usual day for the chill,
it did not return, and we concluded, contrary to the physician`'s advice,
to set out for Le Ray Quarter at noon.
By that time the road was well broken to Brockville, on the river,
and there was a plain track over it, so that our fears, on this account, soon vanished.
We passed over safely, and put up for the night at a tavern,
about a mile from the landing;
with thankful hearts that we were once more in our own country,
and progressing to the remaining work, which would bring us, comparatively,
in the neighborhood of home.
Lodged comfortably, and found my appetite improved by fresh air and change of diet,
and my strength increased.
No one who has not passed through similar feelings,
can realize the agreeable change I experienced.

11th. Third-day.
We rode seventeen miles, principally through a romantic country, called the Rossie Hills;
dined, and in the afternoon went eighteen miles further to the residence of E. T.,
near New Philadelphia, where we were kindly received and entertained.

12th. Snow again falling very fast, after rain,
rendered it doubtful that many would attend the usual meeting, held today;
though some notice of our wish to see Friends had been spread.
I went to it in weakness and fear, after such reduction in body and mind;
not knowing whether I should be owned and helped by Him, without whom we can do nothing.
After a time of silent, inward waiting, I was strengthened to stand up,
and found ability to search out some,
who were concealing themselves under a plain outside,
but greatly needed the inside to be made clean.
I was thankful for Divine help in discharging my duty to them,
and in strengthening the honest-hearted present.

In the afternoon, we rode to J. and L. C.`'s, not far from Le Rayville,
where we found a true resting place.
The concerns and interests of our religious Society, were uppermost with these Friends,
and after part of the evening had been spent in instructive converse,
we fell into silence,
and a word of consolation and encouragement was furnished for them and their daughters.

13th. Attended their regular meeting, in which I was engaged to labor, I hope,
in the authority of Truth.
Parting with these dear Friends seemed hard on both sides,
feeling one another in the best fellowship.
So few Friends visiting them from a distance,
they expressed their reluctance at our staying so short a time;
but in order to get to Lowville, and hold a meeting next morning,
it was necessary to ride fifteen miles this evening; which we did,
and lodged at a tavern.
The weather was cold; the mercury being several degrees below zero.
I thought I never before saw the moisture from the horses, freeze on their bodies,
as it did almost immediately after setting out, while the sun shone on them.

14th. Word having been taken over night, by a Friend, for a meeting, we rose early,
and without waiting for breakfast, which was quite indiscreet,
considering the severity of the weather,
we rode about ten miles to J. S.`'s. A fine hail commenced falling before meeting time.
The company was small, and in sitting with them, it appeared to me,
weakness had spread over the heads of the tribes; and the injunction,
"`Be watchful and strengthen the things which remain, that are ready to die;
for I have not found your works perfect before God,`" was revived and applied.
The spirit of prayer was granted, to petition for help from the sanctuary;
that those who were negligent and indifferent, and had lost ground,
might be forgiven and brought to renew their covenant,
and come up in greater faithfulness; also, for the young people,
who have so few to lead them in the right way;
that the Lord would touch their hearts with the finger of his love,
enamor them with the beauty of holiness, and the excellency of his blessed Truth.
The hearts of some were affected.
We went to T. T.`'s and lodged.

15th. In coming out this morning to the main road,
we found the track so filled with drifted hail, that, in some places,
the horses sunk in it nearly to their bodies,
and the sleigh was with difficulty prevented from overturning.
We drove south about fifteen miles, dined and fed our horses at an inn,
and towards evening, reached J. P.`'s at Lee.
Those who have never travelled in a country,
where the snow is above the tops of the fences, and there is but one track,
are not aware of the difficulty, and sometimes danger, in turning out of it,
to pass vehicles we meet.
The off horse plunges deep into the snow,
from which it requires a great effort to recover the road,
endangering the harness or getting entangled with the passing sleigh.

16th. First-day morning.
Snow falling fast, presenting a discouraging prospect,
both on account of the size of the meeting and the difficulties of traveling.
The number who came was greater than I expected; but,
though I endeavored to do what appeared to be required, it was not a very animating time;
yet I hoped that serious impressions were made on some.

After dinner, we parted with our companion, B. Bowerman,
who had been with us through Canada, and rode to Z. H.`'s;
being obliged to ride eleven miles round, instead of six miles across the hills,
owing to the fall of snow this morning.
We passed an agreeable evening in conversation with this Friend,
who appeared to be firm in the doctrine of the gospel as held by our Society.

The very general departure of the young people from plainness of dress,
throughout this Quarterly Meeting,
gives ground to apprehend that the Society in many places, will decline, if not run out.
To the indulgence of parents and others, it is to be much attributed; who,
instead of restraining the children, gratify their fondness for dress.
What abundant cause is there for mourning;
as it is evidence of the degeneracy overspreading many parts of this,
as well as other Yearly Meetings.

17th. We had an appointed meeting at Werkenville,
composed of members and other professors.
It was a good meeting,
in which was set forth the peculiar glory and excellency of the gospel dispensation;
which brings a knowledge of the Divine will home to every man, with strength to do it;
and enables him to worship God in spirit and in truth, without human aid,
or the intervention of words.
A solemnity was over us.
Friends were refreshed,
and I felt thankful for the Lord`'s goodness in qualifying for his work;
without which we can do nothing.
We rode six miles to an elderly Friend`'s house; dined,
and after a religious opportunity with a member,
who was absent when we were at the meeting to which she belongs,
we rode nearly eight miles to C. P.`'s, in Westmoreland.
Here we met with some hopeful young people,
and found it a pleasant lodging place for weary pilgrims.

18th. Held a meeting here; in which was emphatically opened and pressed,
the danger of being swallowed up in business;
by which the work of salvation would be almost or entirely, neglected.
I expressed the hope which I felt, that young persons present were designed by the Lord,
to be prepared and made use of, in building up the waste places,
and restoring the former desolations among us.
These were pleaded with to yield to the convictions and drawings of his Spirit,
that they might be redeemed from the love of the world,
and know Him to fit them for his service in the church.
It was a tendering time with some, which was renewed at our lodgings,
in a religious opportunity with a number of young persons,
before we set out for New Hartford; some of whom, I believed, if they are faithful,
will be qualified to support the ark of the testimonies.
It was pleasant to see marks of care and religious concern in some here,
to keep to simplicity, and to bring up their children rightly.
Oh how are the reins of government thrown upon the necks of children,
and they encouraged to copy the corrupting fashions,
and manners of the people around them, with whom they too freely mingle;
much to their hurt.

Rode in the afternoon to a Friend`'s house, near New Hartford meeting-house;
but found him so unwell that we could not be accommodated.
We went to the residence of another, and were told that he also was indisposed,
but no other being convenient they consented to take us in.
We went to the meeting-house, where we found a few Friends kindling a fire.
A little company gradually collected, with whom we had a tender opportunity,
to the comfort of the sincere ones,
who are striving to keep up their little meeting at this place.
Several expressed their satisfaction.
Plainness of speech was used towards a different class;
who are deficient in the life of religion.
After dinner rode to Madison, about twenty-four miles, and put up with a Friend,
in the village of Hamilton.

20th. Attended their regular meeting, which was small,
and in which I labored according to the ability afforded.
In the afternoon went to Brookfield; our guide gave notice to the families,
as we rode along, of the appointment of a meeting, to be held the next day; which to me,
was a trying time; the evidence of declension from primitive zeal,
and the neglect of the great work of salvation, were affecting to me.

In the afternoon we had a tedious ride of twenty miles,
some part of it difficult from snow banks, which began to give way under the horses,
so as to make them plunge a good deal in passing over the drifts.
We found H. B.`'s, which we reached about seven o`'clock, an agreeable resting place,
after such a ride.

22nd. We had a meeting at Burlington; which was much larger than we expected,
from the short notice, and it being seventh-day.
I was glad to see so many; it seemed an indication of life, and a desire to obtain good.
They were encouraged to individual faithfulness, from the example of Nehemiah, who,
notwithstanding, his besetments, effected much by perseverance;
through the Divine blessing.
I hoped it was a good meeting; there being, as I thought, sincerely concerned ones,
who would rejoice in the prosperity of Zion.
Under a sense of the protecting power and goodness of our Heavenly Father,
extended to us in this journey, I was led to bow before Him,
and acknowledge his mercy in visiting us in the morning of life,
and keeping us to this hour; and implored his continued preservation,
through the remaining snares and temptations with which a cruel enemy might assail us;
in order to destroy that which He had done in us and for us.

In a view of the trials awaiting us, from the unsettled state of our religious Society,
there is great need of watchfulness and fervent prayer to our Heavenly Father,
for his delivering arm, that it may be round about his afflicted children and servants.

After dinner we proceeded to H. B.`'s, at Oneonta, eighteen miles;
which was laborious traveling, the road being bare of snow nearly one-half the distance,
from the present mildness of the weather.
Here we felt like coming to the close of our visit,
this being the starting point where we set out,
for the meetings in this part of New York Yearly Meeting.
We were very cordially received by his wife, Henry being from home;
and acknowledgments of the Lord`'s mercy, secretly rose in my heart,
He having thus brought us safely through this trying and laborious journey.

23rd. Attended the first-day meeting at Butternuts;
in which I felt a strong interest in some of the young men;
to whom the language of persuasion was offered,
to yield to the convictions of the Holy Spirit,
which would change their hearts and their actions, and give them true peace;
in place of a restless, unhappy condition,
which often attends disobedience of the Divine law.
We must leave our labors with the Lord.

We were detained, waiting for the stage, until third-day afternoon; and in the meantime,
sold our carriage and horses; which was a great relief,
for we should probably have found it difficult, to drive through the mountains,
on account of snow.

We were taken to Oneonta; from which the stage started at twelve o`'clock in the night;
we got some sleep, but setting out in an open wagon, was rather chilling;
but there was no alternative.

We passed over a rough road, but reached Catskill, on the North River,
about eight o`'clock in the evening, somewhat fatigued;
the distance being seventy-three miles.
Here we were detained waiting for a steamboat, until after dark, next evening.
When on board,
we were well pleased to find ourselves in such
an expeditious mode of conveyance homeward.
The crowd in the boat, the darkness of the night,
and the driving of the vessel on large cakes of floating ice,
which made her tremble from stem to stern, together with some noisy passengers,
made the voyage unpleasant.
We landed in New York a little after five in the morning,
and walked to our friend John Wood`'s; whom we found in a poor state of health,
though at that time better than he had been.
He was a man of a christian spirit; and from the opportunity I had of observing him,
appeared to be ready to forgive his enemies, bearing their reproaches, in a pleasant,
cheerful spirit.
This was the last opportunity I had of seeing him, and he was then in this disposition,
while he conversed on some of his trials.
He died in a few weeks after,
firm in the faith that he had borne a righteous testimony to the Truth;
and having a well-grounded hope of entering into everlasting rest and peace with God,
through our Lord Jesus Christ; whose servant he was,
and was not ashamed to confess his Divine Master openly before men.
He was a lover of the Truth, and of the friends of Truth,
and an able minister of the gospel of life and salvation.

We crossed the North River to Jersey City, and took the car for Philadelphia,
at nine o`'clock; and in about six hours were restored, in safety and peace,
to our beloved families and friends.

My heart was clothed with gratitude and thanksgiving to our gracious Caretaker,
for his unmerited mercy and goodness in preserving us; furnishing renewed strength,
from time to time, to do his will, and bringing me back with the reward of sweet peace;
and to find the like peace and preservation had been dispensed
to my dear wife and children during my absence.

I endeavored throughout the visit to maintain a state of watchfulless,
that nothing might occur to mar the work; and after my return,
I was favored with much peace and serenity; and in looking over the journey,
nothing appeared that created uneasiness, or caused feelings of regret;
which I esteemed a mercy.
