== Chapter XVIII

[.chapter-synopsis]
* 1845--1846. Lack of the Life of Religion in the Society
* Visit to Exeter and Maiden Creek Meetings
* Visits to different Meetings within Philadelphia Yearly Meeting
* Ann Jones of Stockport, England
* Visit to Stanford Quarterly Meeting, New York, and its Branches.

1845, Tenth month 8th. After a season of long silence, my mind was invested,
at our own meeting, with the sense that what is lacking, is the life of religion;
accompanied with a renewed evidence, that He who is the resurrection and the life,
is graciously near to manifest Himself in that character.
The duties which are of an outward nature are to be performed; but they may be fulfilled,
and the power of godliness denied.
Many appeared to me in that situation; plain in the exterior,
regular in coming to meeting, and desirous of hearing ministry;
but are destitute of that travail of soul and fervency in seeking after Christ,
which He would reward with the cheering beams of his countenance,
and the bread which nourishes up the soul to everlasting life,
and renews our love and courage to follow Him, and to wait for Him.
Seldom have I felt my love to the Lord Jesus stronger than I did this day.
My spirit humbly bowed before Him, and returned thanks, that were not uttered,
for his mercy in raising me up as from the dead,
to testify of his truth and his goodness,
and to incite others to come and snbmit themselves to Him.

9th. Went to West-town to attend the semi-annual meeting of the committee there.
We found the school in rather a prosperous condition as
regards the progress of the pupils in their studies.
I rarely visit this institution without feelings
of peaceful delight arising from the persuasion,
that the unslumbering Shepherd of the sheep watches over the little flock there,
and will reward the sincere and faithful efforts of the caretakers
and teachers to guard and instruct the dear children.
Meeting with several beloved Friends on the appointment was animating;
and I hope productive of good.

28th. For days past poverty of spirit, and being brought low, have been my portion.
My only hope has been in the compassion and loving kindness of the Lord,
my helper and keeper, and the belief that He would not forsake me.
Today I went to Frankford Monthly Meeting;
and after struggling with feelings of great discouragement,
I yielded to apprehended duty; and the Lord, in mercy, opened the spring of the ministry,
and gave me tongue and utterance, to my own consolation, and the comfort of his people.
I was thankful for this token of his goodness, and proof that He had not forsaken me.

29th. Our Monthly Meeting, held today, was a solid opportunity;
both that for worship and for the administration of the discipline.
There was an unusual solemnity over the latter, in which, I believe,
not a few were under a sincere travail of spirit,
that we might be favored with the Master`'s presence,
and qualified to act in his authority.
It is this alone that strengthens to advance the cause of Truth,
and to edify the body on the true foundation.
Samuel Bettle, Sr., was with us,
and expressed his satisfaction in being united with his brethren in religious exercise.
We agreed to the proposition of the Philadelphia Monthly Meeting,
to open meetings for worship on first-day evening, through the winter.

Eleventh month 2nd. Our evening meeting was opened, which,
considering the wetness of the weather, was large.
It was thought to be a good beginning.

5th. The longer I live the more I am convinced,
that the gospel cannot be preached but as He who
has the key of David re-anoints for the work,
and furnishes that which quickens the soul,
and raises into dominion the precious life in an assembly.

10th. My beloved wife having had for some time a concern to
visit the Friends of Exeter and Maiden Creek Meetings,
we took the Pottsville car, and being met at Douglasville, by a Friend,
were taken by him to J. B.`'s. The weather was very fine, the traveling pleasant,
and being cordially received by our dear friends,
we passed the afternoon and evening to our mutual satisfaction.
On the following morning, J. and his wife set out with us for Maiden Creek.

12th. Called to see our aged friend Mary E. Lee,
who was confined with an injury received by a fall.
We had a religious opportunity in her chamber, and then went to the meeting.
My wife was engaged to strengthen the hands of the exercised few there,
and to invite the young people to give themselves up to the Lord and his service.
Afterwards it was my place to speak to the states of
those who were often brought to see they were,
not what the Lord required them to be,
and in whom He raised at times desires that they might die the death of the righteous,
and their latter end be like his.
The character and example of the righteous were often brought before their view,
and they saw their own shortcomings; yet refusing to yield to Divine conviction,
they remained unchanged in heart, and the day of mercy was passing away.
These were fervently pleaded with, to yield to the drawings of Divine love,
and they would know the nature of the lion to be put off,
and that of the lamb to take its place; old things would be done away,
and all things be made new, and all things of God.
The opportunity was closed with prayer and thanksgiving.
In the afternoon, we rode to E. L.`'s, where we parted with our friends J. and M. B.

13th. Attended Exeter Meeting, which was rather larger than usual;
in which we were both engaged to labor for the encouragement
and growth of the members in the right way.
I hoped some Divine quickening was felt in both these meetings.
Went to the residence of our aged friend John Lee and wife.
He is in an afflicted state of body.
It afforded us much satisfaction to find our aged friends so alive to the blessed cause,
committed in trust to our religious Society;
and they seemed to be refreshed as well as ourselves by the visit.

14th. We were brought to the railroad, and reached our home early in the afternoon.

19th. The Monthly Meeting of the Western District, was held today,
which I was drawn to visit.
The company was unusually large; and after a time of silent waiting,
the stirring of the Lord`'s power was felt,
under which I was gradually enabled to preach the gospel of salvation,
through our Lord Jesus Christ;
showing that the work of regeneration had its beginning in the heart,
through obedience to the manifestations of his Spirit, in little things.
Our Savior thanked the Father that He had hid the
things of his kingdom from the wise and prudent,
and revealed them unto babes.
To be brought into this blessed experience, we must become babes in Christ;
and the only way to experience the new birth and change of heart unto righteousness,
is by faithfulness to the requisitions of the Divine will, made known in us.
Many things were brought forth out of the treasury,
by Him who alone has the key and command of it;
and through Divine mercy and condescension the baptizing and solemnizing power of Christ,
went forth over the assembly; to the comfort and strength of the hungry,
weary and exercised ones.
Oh! that I may be enabled in humility and abasedness of soul to offer the
tribute of thanksgiving and praise to Him who has all power in his hand;
and to walk before Him with increasing fear and reverence,
for all his great condescension and unmerited compassion towards me, a poor creature,
and towards his church and people.

26th. This afternoon, my wife and myself went to visit a Friend in the country.
There is a union of spirit between those who see eye to eye,
and their countenances and company are cheering.
Where the Son of Peace abides,
a harmonious converse can be maintained between fellow travelers on the heavenly journey.
Their experiences and their Divine openings,
with which their mutual Lord and Leader has instructed them,
are brought forth from the treasury as things which are new and yet old.
Such converse is both entertaining, and, at times, very strengthening,
and according with the practice of the earliest disciples.
Two of them walked from Jerusalem to Emmaus talking as they went,
of the things which had just transpired.
Jesus joined himself to them, and asked,
"`What manner of communications are these that you have one to another,
as you walk, and are sad?`"
At a time of singular trial and disappointment,
it was natural for them to speak upon that which lay the nearest to their hearts.
And so it is now.
Disciples of the same Master will commune upon their trials,
and the straits and besetments of the church,
as well as upon its hopes and encouraging prospects.
Paul talked with his contemporary believers, on one occasion, until break of day.
In old time, when the proud were called happy,
and they that worked wickedness were set up, and they that tempted God were delivered;
"`Then they that feared the Lord spake often one to another;
and the Lord hearkened and heard it; and a book of remembrance was written before Him,
for them that feared the Lord, and that thought upon his name.
And they shall be mine, says the Lord of hosts, in that day when I make up my jewels;
and I will spare them as a man spares his own son that serves him.`"
This has been the case with the devoted children
of God in various ages since that period;
and thereby they have consoled one another; and he that watered, was watered himself.

Twelfth month 4th. Both inwardly and outwardly, clouds and darkness have prevailed much.
Faith has been put to the test; but I have endeavored to keep patient,
and hope for brighter days.
Went to the Arch Street Meeting,
and there was a little qualified to unfold the roll written with mourning;
and to set forth, that in these dispensations, the Lord teaches man his own impotence,
and that all good comes from Him.
The stream of the ministry rose a little, to the help of the preacher,
and we may hope some others.
Came away with a thankful heart that mercy and goodness were
not yet clean passed away from such a poor creature.

7th. At our meeting yesterday,
the administration of condemnation to those who have been living in sin, was presented,
as among the mercies of Him,
who wills not the spiritual death and everlasting separation from the heavenly host,
of a single soul which He has created.
"`No chastening for the present seems to be joyous,
but grievous; nevertheless, afterwards,
it yields the peaceable fruit of righteousness to them that are exercised thereby.`"
And "`Whom the Lord loves He chastens, and scourges every son that He receives.`"
If we are without chastisement, we are not the true-born sons and daughters of God.
I endeavored to persuade some to endure these dispensations,
that they might receive the gift of repentance; and be restored into Divine favor.
I felt encouraged before going to meeting, with a gentle intimation,
which I hoped was from the Divine Fountain;
that all our trials will be light in comparison
with the reward at the end of the journey;
and if they contributed to prepare us for that happy consummation,
they should be esteemed as the greatest blessings.

14th. First-day of the week, one of the most inclement we have had this winter;
snow and ice and rain to walk through to meeting; the clouds dark,
and the air thick and smoky.
Our meeting was larger than we anticipated: silent in the morning; in the afternoon,
a little was expressed, on the necessity of meeting and waiting,
not only in a belief of the doctrine,
that Christ is in the midst of those who gather in his name, but in feeling after Him,
that we may be sensible of the quickening power of his presence;
qualifying us to ask the Father, in his name, for what we have need of.
The evening assembly was very small; and before the hour was fully come,
the gaslights nearly all suddenly disappeared,
owing to the meter becoming covered with water from rain and melting snow.
The little company, except a few who went for lamps and candles,
kept steady to their places; the house was again sufficiently lighted,
and it was thought by many to be a good meeting.
I hope that the Lord was our helper,
and that some strength and comfort were imparted to weary souls,
longing for deliverance from sin.

21st. We had a comfortable and solemn meeting this morning;
in which the paramount importance of keeping an eye to the eternal recompense of reward;
and, like Moses, choosing to suffer affliction with the people of God,
rather than enjoy the pleasures of sin for a season;
esteeming the reproaches of Christ greater riches than all the treasures of Egypt,
was held forth to the meeting.
In the evening, we had a peculiarly solemn time;
my dear wife being clearly opened on the importance of the ministry,
and the indispensable need of abasedness of the creature,
in those engaged in the solemn work; and was afterwards engaged in supplication.
We have rarely sat under more solid weight and deep silence,
than that in which the meeting was closed.

1846, Third month 14th. We have had rather a trying winter, from cold and snow,
and the great variableness of the weather.
It has been so to me in a spiritual respect.
Clouds of discouragement, and fear of being or getting wrong have hung over me,
from day to day; in part occasioned by the peculiar state of our religious Society,
and doubtless also designed to humble the creature,
and to produce a more weighty and watchful state of mind.
If I can but be favored with the protection and guidance of the Holy Spirit,
so as to walk with acceptance before the Lord,
and to show forth the excellency of the religion of Christ,
all these afflictions will be of little moment,
except so far as they have contributed to this all-important end.

In the Second month, I attended Abington Quarterly Meeting;
in which I felt much for the trembling and diffident ones, who love the blessed Truth,
and desire to do the Divine will, and yet have many fears.
To these there appeared to be a word of comfort,
and tender invitation to hold fast that which they had received,
and to follow the Master; putting their trust constantly in Him;
and a way would be made for them.

Having a desire to be at Bucks Quarterly Meeting, my wife and I took stage for New Hope,
on the 25th ult., and got that afternoon to our worthy and honorable friend`'s, Ruth Ely,
whose hospitable residence is a pleasant lodging-place
for those who love and serve the Lord Jesus.
She gave us a very cordial reception, as a mother in Israel towards her children.
As the stage did not leave the city on third-day,
we were not at their Meeting of Ministers and Elders.
The meeting for business was a favored opportunity,
during the part allotted for Divine worship;
the mourners being cheered and refreshed by the visit and labors of their friends.
Returned to our resting-place, where we had the company of Christopher Healy,
a devoted minister of Christ,
and one who feels a deep interest in the doctrines and
testimonies of the gospel held by Friends,
having adopted them from convincement of their truth;
and long faithfully advocated them before small and great.
We spent the evening to our mutual comfort.
Next day we made two visits to some Friends of Solebury; and on seventh-day,
got back to the city; the weather cold, and snow falling through the day and that night.
The retrospect of the little excursion was peaceful; it being a duty we owe to aged,
experienced Friends, to visit, and, as we are enabled,
encourage and animate them in the closing days of their earthly pilgrimage.

Haddonfield Quarterly Meeting being held this week, E. Pitfield,
my wife and myself went over to it.
That for Ministers and Elders, was to us a low, and rather trying meeting.
The cruel enemy is at work in every way he can devise, to lay waste the unity,
and all capacity for usefulness in the church, and in the world.
We endeavored, according to what we apprehended was required, to warn some,
and to strengthen the watchful travailer.

The meeting on fifth-day was pretty large, many young and middle-aged Friends being there.
My wife and E. Pitfield had acceptable service, while I sat in poverty,
expecting to have little to do; but, very unlooked for,
the declaration of the prophet Jeremiah,
in relation to the Jews forsaking the Fountain of living water,
and hewing out cisterns that could hold no water, was brought before me.
There was a quickening virtue accompanied, and after some waiting,
it appeared proper to rise with it,
and to declare that it described the cause of all our difficulties.

I was led to show the process of the work of regeneration,
commenced by the in-shining of the light of Christ in man`'s dark heart;
its convictions for sin; and, as yielded to, its making an entire change in him.
Nothing could begin and carry on this work,
but the Author and Finisher of the saints`' faith;
and the Lord would not give his glory to any of man`'s devices.
Nothing is fit to receive the water of life, but regenerated souls,
sanctified vessels in the Lord`'s house;
and if we changed our glory for that which profits not;
hewing out cisterns that can hold no water, desolation would overspread the Society.
The language of affectionate entreaty was held out to the young people,
to enlist under Christ`'s banner, and to follow Him in the way of the cross.
The work is the Lord`'s, and He alone can carry it on;
before whom we are bound to bow in reverent thankfulness for the least of his mercies,
and with prayer and supplication, as the Spirit gives ability,
to ask Him for the continuance of his preserving power,
and for wisdom and strength to serve Him, in the gospel of his dear Son.
I returned to the city,
leaving my wife to make some visits she has had on her mind a long time.

Fifth month 7th. This morning I received intelligence of the death of
that deep and extraordinarily gifted minister and servant of Christ,
Ann Jones, of Stockport, England.
She visited this country about the period of the separation, in 1827-8,
and was a sharp threshing instrument in the hand of the Lord,
against the spirit of infidelity, then making fearful inroads upon many,
under the name of Friends, who knew very little of their principles,
or of the sanctifying power of Divine Grace, ruling in their hearts.
Her controversy was with the leaders and principals, who were working in the dark,
to draw away ignorant and unwary members, into the mazes of unbelief,
and into contempt for the unyielding advocates of Christ`'s gospel,
and his authority in the church.
She was one of the most fearless soldiers in the Lamb`'s army,
and by his wisdom and strength,
was often instrumental in discomfiting the enemies of Christ;
while she infused courage and firmness into the
hearts of the little flock in different places,
on whose shoulders rested with weight,
the support of the principles and discipline of the Society.

When she informed the Yearly Meeting of Ministers and Elders,
that she felt liberated to return home, Wm. Jackson, of West Grove,
expressed his unity with her, and said,
she had come among us in the same power and spirit
with which Samuel Fothergill visited this country,
whom he had heard in the ministry.

Thus one after another of the Lord`'s anointed servants
are gathered to their everlasting rest in Christ;
which is felt to be a great trial in this day of scattering,
and of rebellion against the law and the testimony;
the number of valiant and unflinching soldiers seeming to be few in every place.
But the Lord is strong and mighty,
and in his time will give the victory to his tribulated people,
who hold fast their integrity to Him; trusting in his mercy and power,
and not in their own understanding.

10th. I attended Germantown Meeting.
Being first-day, I was pleased to see the number who came;
many of them in the prime of life, and younger.
I was enabled to plead with some, for greater devotion to the Lord`'s will;
and to show to others that however humble their lot,
or of little importance they might feel themselves to be in the world,
there were duties for them to fulfill; and if they were faithful,
they would be regarded by Him who watches over his people;
they would grow from stature to stature,
and their example would tend to draw others to the blessed Truth:
they would be preachers of righteousness,
and qualified to stand as witnesses to the doctrines
and testimonies which Friends are called to support.
Their afflictions would be sanctified to them, and through their faithfulness,
there would be ground to hope, that a seed would be preserved in that place.
The compassion of our blessed Savior, as portrayed by the parable of the householder,
who went out at different hours of the day and hired men to labor in his vineyard,
even to the eleventh hour, was held up to the view of some,
who had been wasting their precious time until the day is far spent.
When he settled with the laborers, he began at the last and went on to the first,
giving each the same reward.

Showing that while we ought not to presume upon Divine mercy,
so we ought not to attempt to limit, or to despair of it,
when He condescends to place before us, as the handwriting on the wall,
our true condition;
and to invite us to leave all and enter with Him
into the vineyard of the heart and labor.
I thought Divine mercy was near, and that some hearts were contrited,
under a fresh and living sense of it.
I returned home with feelings of peacefulness.

14th. Was at the Arch Street week-day meeting.
The meekness and gentleness of Christ,
and the patient and unresisting endurance of suffering, of which He set us an example,
were much upon my mind.
The prophet declared that He will not break the bruised reed.
He shall not strive nor cry, neither shall any man hear his voice in the streets;
yet He will finally bring forth judgment unto Truth.
He was led as a lamb to the slaughter, and as a sheep before her shearers is dumb,
so He opened not his mouth.
He suffered for our sins, the just for the unjust.
It pleased the Father, in bringing many sons to glory,
to make the Captain of their salvation perfect through sufferings.
And the more we are brought to be like Him, the better it will be for us.
Whatever is going on around us,
it is needful to remember that there is a work
for every one to be engaged in within himself.
It is here we are to know Christ Jesus to be our Savior,
and to give us strength to carry on that work.

This is what is greatly lacking within our own religious Society.
Many who take part in its concerns, are greatly involved in the world and its pursuits.
"`The love of money is the root of all evil; which, while some covet after,
they have erred from the faith, and pierced themselves through with many sorrows;
erred from that faith which is the saints`' victory, and of which Christ is the author.

16th. My dear wife feeling drawn to attend the meeting at West Chester,
we left home this morning and reached the village about eleven o`'clock.
The weather was fine on first-day;
and a pretty large company collected at the meeting-house.

She had acceptable service among them.
We were taken to West-town School towards evening.
Vegetation is now in its most luxuriant state; the grass, shrubbery and trees,
in the boys`' and girls`' walks, present a freshness and foliage,
which make the premises a delightful scene,
and contribute to healthfulness and exhilaration of spirits;
of no small advantage in the hours of relaxation from study.

18th. From here we went to Concord, where we attended the Quarterly Meeting,
and had some service.

Sixth month 16th. Feeling a gentle pointing to the North Meeting,
I went there this morning.
My mind was opened on the preciousness and necessity of unity;
that unity of the Spirit which our Lord spoke of in his prayer to the Almighty Father,
for his disciples; "`That they all may be one; as you, Father, are in me and I in you;
that they also may be one in us.`"
This unity subsists among those who are born of the Spirit,
the incorruptible Seed and Word of God, which lives and abides forever.
I felt very desirous that Friends might keep on the watch,
against everything that tends to alienate from one another;
not being ready to take up unfavorable apprehensions about each other;
but to stand still in the Light,
that they may have those things which may grow into a barrier between them, removed;
and their hearts more and more sweetened by Divine love.
Samuel Bettle, Sr., closed the meeting with supplication.

21st. Being first-day.
At our meeting,
I was led to extend a renewed call to those who were
taking their ease and enjoyment in the comforts of life,
and in great danger of forgetting their Heavenly Father,
the bountiful Giver of all we have.
Some who had set out, with very humble views and desires,
in relation to earthly possessions, may let go their exercise when things,
through industry, grow lighter,
and they are released from the anxiety they once felt about the means of subsistence.

When this takes place, the eye which once saw, may be again blinded,
and the lively sense they once had of the importance of the cause of Christ,
above everything else, may be gradually blunted;
and then when we meet for the solemn act of Divine worship,
the things of the world bring a stupor over the meeting,
and the great object of coming together is almost altogether frustrated in some.
I hoped that through the tender mercy of the Shepherd of Israel,
there was a little of his quickening power felt.
The warning, and yet confiding language of the apostle was brought into view,
"`Oh death, where is your sting?
Oh grave, where is your victory?
The sting of death is sin, and the strength of sin is the law.
But thanks be to God who gives us the victory through our Lord Jesus Christ.`"
The awful period will arrive to every one, when, above everything else,
it will be of the utmost consequence to be able in truth, and in our own experience,
to adopt that language.
But only through obedience to the Lord Jesus, can we know this victory,
and be enabled to thank God for it.

29th. Our beloved friend Hannah L. Smith, a minister, who, previous to her marriage,
was a member of the Southern District Monthly Meeting,
died last week and was buried today.
Attending the burial, I felt impelled to preach Christ crucified and glorified,
and also appearing by his Spirit in the heart.
I reminded the company, that the period would arrive to them, when,
if they had a right understanding,
it would be the most desirable thing to realize the testimony of the beloved disciple,
that those who had come out of great tribulation, and washed their robes,
and made them white in the blood of the Lamb, should hunger no more,
neither thirst any more, neither shall the sun light on them, nor any heat.
"`For the Lamb which is in the midst of the throne, shall feed them,
and shall lead them unto living fountains of waters,
and God shall wipe away all tears from their eyes.`"
This would be of the greatest importance to us at the day of account,
whether rich or poor; and we must all stand before the judgment seat of Christ,
to give an account of the deeds done in the body.
Then, all the riches and gratification, the honor and pomp of this world,
would be lighter than a feather,
in comparison with that exceeding and eternal weight of glory,
which would be revealed to the saints in light.
I declared that Christ took upon Him the body prepared of the Father, to do his will in,
and offered Himself a most holy and satisfactory sacrifice for the sins of the world;
that He suffered for our sins, the just for the unjust; that He might bring us to God.
But it was only as we opened the door of our hearts and let Him come in;
and witnessed Him to sit as a refiner`'s fire, and as a fuller with soap,
removing all impurity, washing us in the laver of regeneration,
and renewing us by his Holy Spirit,
that we could know our garments made white in his precious blood,
and experience our past sins to be blotted out; having on the wedding garment,
and being accepted in Him, the Beloved.
I spake from the necessity laid upon me; my mouth being opened almost before I was aware.

Seventh month 5th. I felt drawn to attend the Western Meeting,
which considering the season, was a pretty large meeting.
Through Divine condescension, my mind was early brought into a waiting state;
and the expression of our dear Lord was presented before me:
"`Where I am, there shall my servant be also.`"
This appeared to me applicable to all who serve Him,
whatever place they occupy in the church of Christ.
"`If any man serve me, him will my Father honor.`"
It is a great favor to be with Christ, whether in suffering or rejoicing;
but to experience this, we must serve Him daily,
by obeying his will manifested unto us by his Spirit.
I was favored to accomplish the service that appeared to be required,
with comfort to myself, and I trust to some who were present.

11th. The Monthly Meeting of Upper Evesham occurring on the 11th,
my wife and myself went to Medford in the stage.
We found the spirits of many of the rightly exercised members
depressed with the distressing condition of our Society,
and with the fathers and mothers among them being few,
to watch over and to strengthen those who love the Truth.
We were introduced into sympathy with them, both the older and the middle rank;
and through holy help, were enabled to minister to them, in the openings of Divine life.
We were refreshed, and rejoiced at the present favor;
they that watered being watered themselves.

The 12th, being first-day, we attended the meeting again;
some not belonging to Friends coming in.
My wife first ministered to them; and after waiting some time in silence,
I was led to hold up the necessity of inward, heart-changing religion,
and to caution some against supposing that this work was finished,
by yielding to the first visitation;
and against the disadvantage of talking away the heavenly impressions.
After being grafted in the Vine, and become fruit-bearing branches,
we require frequent purging, to prepare for bringing forth more fruit.
We returned home on the 14th, well satisfied with the visit.

Eighth month 3rd. Today was held our Quarterly Meeting.
A religious weight and solemnity were spread over us,
and several Friends were engaged in the ministry.

13th. My wife having gone to Woodbury to attend the Quarterly Meeting there,
I went down this morning and joined her.
It is a small company, but there are some honest, well-concerned Friends,
who feel the depressed condition of the church,
and mourn over the lack of a greater number of lively laborers in the good cause.
My wife and Rachel Thornton appeared in testimony, and I followed them;
bringing to view some of the exhortations of Christ to
enter into labor for the bread and the water of life,
individually.
Many are willing to be fed who are not willing to work; they are fond of the honey, but,
like the drones in the hive, do not endeavor to gather it.
This easy, lethargic disposition, is robbing the Society of strength,
and landing those who are overtaken with it, in spiritual death,
and alienation from the Lord of life and glory.
My wife closed the meeting with solemn supplication,
that our Heavenly Father would grant some token of his
love and remembrance of his suffering children;
and renew and strengthen their faith, which seems at times to be greatly reduced.
In the afternoon, we visited our friend Joseph Whitall,
who is in such a reduced state of health as not to be able to go to meeting.
We returned to our peaceful home next morning.

18th. Was at the North Meeting; in which great weakness was the clothing of my mind,
for some time after sitting down with them.
But the Lord condescended to my low estate and out of weakness I was enabled,
by his strength, to declare his goodness and mercy to them that love and serve Him.
The testimony of David was revived, "`The Lord is my Shepherd, I shall not want.
He makes me to lie down in green pastures He leads me beside the still waters.
He restores my soul; He leads me in the paths of righteousness for his name sake.
Yea, though I walk through the valley of the shadow of death, I will fear no evil,
for you are with me your rod and your staff they comfort me.`"
It was a good day.

19th. Having a gentle draft to the Western Quarterly Meeting,
my friend J. S. took me to London Grove.
On our way we called at West-town School, took tea, and rode to B. S.`'s,
where we were kindly received.

20th. Fifth-day morning.
The Select Meeting was a small body,
having but one man and one woman acknowledged as ministers.
There was a word of encouragement for the upright but tried few, among them.
Being quite unwell, the humbling hand of the Lord seemed to be upon me,
yet patience and strength were granted to bear up.
In the meeting, next day,
David Cope delivered a testimony to the unchangeable
character of the conditions of salvation.
That through Grace, man may comply with them, and partake of the blessings of the gospel.
If he refuses, the truth will remain the same,
and he must take the consequences of his disobedience.
The great spread and influence of the spirit and principles of infidelity,
and the danger of living in its atmosphere, came before me.
Great subtlety and sophistry are used by some of talents,
to lay waste the Holy Scriptures,
and into a fearful pit of death and darkness they sometimes plunge themselves.
But they cannot destroy or change the truth of God;
the consequences of their willful unbelief will fall on themselves.
Living among such people is dangerous;
their example and their dark spirits tend to produce indifference to religion;
and some who turn their back upon the Truth,
go into the politics and policies of the world;
others into the love and pursuit of money;
others into the pleasures and gratifications of time and sense.
In this way we are surrounded by dangers of various kinds,
out of which nothing can preserve us,
but obedience to the secret illuminations of the Spirit of Christ;
showing us what we are, and what we are to forsake,
that we may be made by Him what He would have us to be.
As we follow Him,
our example will be a constant protest against
the unbelief and the lethargy surrounding us;
and thus we shall be more likely to put a stop to its progress,
than by any arguments we can advance against the principles of the infidel,
or the mere man of the world.
I thought some renewed ability was given to speak to the states of the people,
and solemnity spread over the meeting.

Ninth month 8th. I have passed most of our meetings for months in silence;
and not infrequently without much evidence of the stirrings of Divine life,
and the mantle of sorrow and mourning has been the covering of my spirit.
Last fourth-day it seemed to be my duty to say some close
things to those who were laying up treasures for themselves,
and making use of the outward blessings of a beneficent Providence,
to gratify and exalt themselves;
that they might appear grand and be highly thought of by others;
instead of looking upon themselves as stewards,
and accountable for the right appropriation of their earthly substance.
Such were advised to put away their jewels and their ornaments out of sight,
and repair to Bethel, to renew their covenants with the Lord.
Little relief, however, seemed to follow, but if it is of the Lord,
He will reward for faithfulness.

13th. A day of inward conflict and of mourning,
on account of the absence of the Beloved of souls.
In the afternoon, there was some ability to look towards the Lord`'s holy temple,
with hope that his sustaining power was not withdrawn.

14th. I had thought of Haddonfield Monthly Meeting yesterday,
but with no expectation of going to it; yet this morning, on rising,
it came before me with some quickening effect; and after breakfasting,
feeling afraid to put from me what seemed to be a pointing to that meeting,
I crossed the river, and took stage for the place,
and got there while Friends were convening.

After a season of inward waitings upon the Lord,
I was drawn forth to speak of the trial of faith, which is more precious than gold,
that perishes, though it be tried in the fire;
that we may experience everything opposed to heavenly purity removed,
and after the refinement for the time is passed through,
witness the lifting up of the light of the Glorious Countenance upon us.
Encouragement was communicated to exercised members among them,
to put their trust in Him, in whom there is everlasting strength,
and follow Him faithfully.

Others were warned against engaging in any cause under
a religious profession which is not the Lord`'s cause;
and those who, at times,
are brought under conviction by the internal discoveries of the Light of Christ,
were affectionately and fervently solicited to give up to the heavenly vision,
which is not at their command.
These days of the Son of Man, in which by his grace, He brings salvation to us,
and calls on us to deny ungodliness and the world`'s lusts, and to live soberly,
and righteously, and godly in the world, the Father has reserved in his own hand.
I felt constrained to bow the knee, and to commemorate the Lord`'s goodness,
in visiting and bringing us out of darkness into his light,
and to implore the continued extension of his
protecting power to the end of our earthly pilgrimage;
that through the blood of Christ, and the sanctification of the Spirit, we might,
in the end, be permitted to enter the glorious kingdom of everlasting rest.
Some hearts were touched and comforted; and though I felt empty,
I hoped it was in the way of duty.
Returned home in the evening.

Tenth month 1st. My wife, my sister H. Rhoads, and myself,
attended Goshen Monthly Meeting; it was a solid meeting,
in which the spring of gospel ministry was opened in several,
to our mutual comfort and strength.

19th. The Friends appointed by the Meeting for Sufferings,
to examine certain doctrinal works,
which have given the Society much uneasiness and disturbance,
convened at three o`'clock this afternoon.
They were favored with a covering of religious weight and solemnity;
and after a time of silent waiting, the minute of their appointment was read.
Friends deliberately expressed their views, of the course proper to be taken,
in the investigation, in which there appeared and was felt much harmony; after which,
some Friends were named to enter upon the work,
and draw up such a document as would show the disagreement of many parts of those works,
with the doctrines ever held by the Society.

29th. Went to Newtown Meeting, where I found a small company assembled,
for the purpose of Divine worship; and having been for many days in a low state,
I was prepared by the good band of the Lord, to enter into sympathy with them.

They appeared to need encouragement,
and also to be stirred up to a more fervent travail of spirit,
that they might know the work of regeneration to be progressing in themselves.
Through the humbling, quickening power of Him, who is the resurrection and the life,
I was enabled to visit the precious seed, kept down in some hearts,
and not enough cherished in others; and I believe it was in some of them,
raised into dominion in good degree.
We were humbled and tendered together,
and thanksgiving was secretly offered for the favor vouchsafed.

Eleventh month 1st. Was opened our evening meeting for the winter.
I was engaged towards the close, to warn our young people, in the love of the gospel,
of the many snares which the enemy is spreading to entangle them;
and to persuade them to yield to the convictions of the grace of their Redeemer;
that they might escape the remorse which the
disobedient and impenitent bring upon themselves.

2nd. The Quarterly Meeting for Discipline was a season of much inward conflict.

3rd. Feeling an impression of religious duty to
attend Stanford Quarterly Meeting in New York,
I mentioned the subject to the Monthly Meeting, which gave me a minute of its unity,
to visit that and the meetings composing it.
My dear friend Joseph Snowden, agreeing to accompany me, we took passage to New York;
but owing to the fog on the Delaware, we were detained nearly two and a half hours,
and did not get into the city much before one o`'clock in the morning.
Lodged at a public hotel, and took the seven o`'clock boat on the North River.
We landed at Poughkeepsie, a little before one o`'clock; dined,
and towards evening left for S. Upton`'s.

On the 5th we went to the Select Meeting, which in some respects,
was rather a trying time.

6th. Attended the Meeting for Discipline.
After several communications and a time of silence,
I believed it my place to call the attention of some to the inward work of religion,
inviting the young and the middle-aged to come under the yoke of Christ;
and encouraging the tribulated ones who had experienced the work in good measure,
to look to the Lord alone, who would preserve all such in their deepest trials,
and in his time make a way for them, and for his church to surmount them all.
It was laborious at first, but the life rose finally into some good dominion.

In the second meeting, towards the close,
I felt engaged to exhort the upright-hearted to support the discipline,
and our testimonies and doctrines, in the wisdom and strength which Christ alone gives.
Returned to S. Upton`'s, and next day visited two Friend`'s families;
having religious opportunities in both.

8th. First-day morning we went to the Creek Meeting,
where a pretty large company assembled.
For some time I sat under fear, that some were more disposed to hear words,
than to get the mind withdrawn from things without, and centered upon the Lord alone.
I was led to remind them that the great object of our thus assembling,
was to feel after Him, as the apostle expresses, if haply we may find Him,
who is not far from every one of us, for in Him we live, and move, and have our being.
Many subjects were gradually opened before me;
among which was the conscientious strictness which the Lord requires,
even from the earliest visitations of his love and power,
to perform our moral duties justly, and uprightly, as in his presence.

This I could testify from experience, after I was brought to submit to his grace.
The humbling power of the Lord came over us,
so that some were tendered by its heavenly influence.
Dined at Paul Upton`'s, and a meeting being appointed at three o`'clock, at Stanford,
we rode over, but were a little belated.
There were a number of persons not professing with us, besides Friends,
who were assembled.
The importance of a careful education of their children,
imbuing their minds with a love for the truths of Holy Scripture, enforced by example,
and a solid concern for their everlasting welfare, presented to my mind,
with the instance of Timothy.
The apostle mentioned to him the unfeigned faith which dwelt in his grandmother Lois,
and his mother Eunice, and he was persuaded at that time, in him also.
They had been, no doubt, watchful over him from early life.
From a child, says the apostle, you have known the Holy Scriptures,
which are able to make you wise unto salvation through faith, which is in Christ Jesus.
This shows the benefit which godly parents, who are in the true faith themselves,
may be to their offspring, in bringing them up in the right way of the Lord,
and be instrumental in guarding them from many evils.
One very serious danger arises from the society of those who undervalue,
and endeavor to destroy the authority of the Holy Scriptures,
and to poison the young people with their sophistry.
I felt bound to warn parents and guardians solemnly against
permitting the children entrusted to them to mingle with such society;
from which they might suffer irreparable injury.
It is not often I have felt more sensibly,
the necessity of closely watching against the
insidious approaches of the spirit of infidelity;
which is like the poison of asps under the tongues of some hardened, darkened people;
and that the elderly part of society may be
instrumental in leading the young people to Christ;
that they may be preserved, and through the operation of his Divine power on their minds,
may grow up in good liking before Him, and in their day,
be fitted for and engaged to advocate his precious cause on the earth.

We lodged at our ancient friend J. F. Hull`'s hospitable residence,
where we had the company of some Friends,
and a religious opportunity before retiring to rest.

9th. Second-day.
Our beloved friend Paul Upton, took us to North East, where we had an appointed meeting,
which my companion thought was a good time;
the meeting ending in supplication for the little flock,
and our mutual preservation to the close of our earthly pilgrimage.

10th. Attended a meeting appointed at the Creek, by a Friend from Vermont,
in which I was silent.
In the afternoon, Smith Upton took us to visit several Friends,
with two of whom we had religious opportunities.

11th. Went to S. M.`'s, near Hudson, where we lodged,
and were very kindly and comfortably accommodated.
Next day, were at their usual week-day meeting.
After a Friend traveling with a minute, had relieved his mind,
I felt drawn to encourage the few mourning, and often desolate ones there,
to individual faithfulness, in the work of their soul`'s salvation;
by which they would be prepared to lead others in the right way;
and to uphold the doctrines and testimonies held by Friends,
by consistent lives and conversation.
Some who were deeply immersed in the spirit and pursuit of the world,
its riches or its applause, were pleaded with to come out of those things.
They were reminded of the uncertainty of all earthly gratifications,
by the instance which our blessed Savior gives, of the man who,
after building storehouses and barns, to contain his goods, said,
"`Soul, you have much goods laid up in store for many years;
take your ease, eat, drink, and be merry.
But God said unto him, you fool, this night your soul shall be required of you,
then whose shall those things be which you have provided.`"
It appeared to me there were those present who
had great need to lay these things to heart,
and to seek the Lord while the day of mercy lasts, lest the night overtake them,
in which no man can work.
J+++.+++ W. knelt and supplicated,
that the word preached might not return void of the purpose whereunto it was sent.

13th. This morning, S. M. took us to Hudson, and crossing the river at Athens,
we found our friend L. B., waiting for us; with whom we rode to his house at Coemans.
His residence is on elevated ground, from which we have a very extensive prospect;
the Catskill Mountains in the south,
farms and villages on the North River for several miles, and a part of Massachusetts,
and I believe, of Connecticut, in the east.
We had an interesting visit there,
and on the following morning a religious opportunity with the family;
and then rode over to his father`'s.

On our way there we made a visit to two aged Friends;
the man is in his eighty-seventh year, and his wife, in her eighty-eighth;
but her faculties appeared clear; they have been married sixty-five years.
She is a minister, lively in spirit, and expressed that she was glad to see us,
and considered it an evidence she was not forgotten of her Heavenly Father.
After dinner, and before we came away, I mentioned the satisfaction it afforded,
to meet with one who kept her integrity, and her interest in the great cause,
to so late a period of life.
It was clear to me, that the covenant of life, and of peace,
with such dedicated and innocent spirited ones, would not be broken;
but the tender regard, of their Heavenly Father, would be extended to them to the end.
I attended their meeting, and being first-day, it was large.
I was, after a time, enabled to stand up,
and to show there was much profession of religion, and much talk about it,
without knowing the power of it ruling in the heart.
Many things relating to this internal work, the offers of Divine mercy,
through our Lord Jesus Christ; the possibility of out-living the day of grace,
and the awful consequences of dying in sin, were opened to the people,
and the meeting ended satisfactorily.
From there we were taken to Coxsackie,
where we went on board one of the Albany steamboats, and got to New York in the night.
It rained hard, but we went to the Philadelphia steamer, between five and six o`'clock,
and reached our own homes about twelve o`'clock; thankful for preservation,
and the peace I was favored with;
finding my beloved family in health and comfort of mind.
