== Chapter XIV

[.chapter-synopsis]
* 1846--1847. Yearly Meeting of 1847
* Work about Home
* Second Religious Visit to North Carolina.

1846, Twelfth month 21st.
I have been let down into a low state, so that faith seemed ready to fail.
These dispensations of the withdrawing of all sense of Divine good,
have a very reducing effect upon self-importance;
and teach us true charity and tenderness towards those who are in affliction,
and those who may be wrong.
I was brought to cry for mercy,
and then to examine whether I had desired that mercy might be showed to others,
as I desired it shown to myself.
I believe I have craved it even for many, who I apprehended,
had neither been nor done what they ought.
But this state of seemingly entire desertion by our Heavenly Father,
is a bitter cup to drink.
May I be more humble, more steadily fearful of getting off the watch unto prayer,
and more constant in resisting a light spirit,
which would take its ease and indulgence on the sabbath day.
We cannot pray when we please, but it is our duty to watch,
and to wait for the pouring forth of the spirit of supplication,
which produces a broken heart, and a contrite spirit;
and enables us to cry availingly to God for mercy, and for help to keep us from falling,
through his dear Son, our Lord and Savior Jesus Christ.

1847, First month.
Some things have arisen, increasing the difficulties of the present time,
and the weight which the burden-bearers have to support.
Some are actuated by party feelings,
and seem little to regard what affliction they add to those
who stand for the cause and the testimonies of Christ.
The number who heartily devote themselves to service and to sufferings,
in these perilous times, is comparatively few.
Many are afraid of their name among men,
and of being identified with the despised suffering seed.
All qualification for the ministry has been much withdrawn, and when I had some secret,
yet almost obscure intimation of the kind, I felt afraid of standing forth,
lest I should fail; and when I did give up, in fear,
I was as one who had attempted to walk, and was in danger of falling,
but I had some reason to believe, that in this season of weakness and timidity,
the sense which some others had of it, tended to contrite and humble them.
Strength and confidence in that everlasting Arm,
which is the unfailing support of the Lord`'s baptized and devoted servants,
were gradually restored; and the spring of the ministry was again opened,
and things new and old, given me to declare to others,
in the fresh authority and power of the unchanging Truth.

10th. In our evening meeting,
the essential importance of knowing the Lord Jesus revealed in our own hearts,
and not only believing in the record of the Holy Scripture,
in relation to his coming and suffering in the flesh,
but also receiving Him in his spiritual, inward appearance, to break every yoke,
and prepare the soul for the Lord God, by his spirit, to dwell in,
was opened and enforced.
Many can say much respecting Him, and what He has done for us, without us,
who yet seem determined to keep Him without them;
while they judge and condemn those who plead for the
inward and spiritual knowledge of God and Christ,
as well as for a full belief of all that He has done for us, in the prepared body;
and as our Mediator and Intercessor with the Father.

15th. Was held our Meeting for Sufferings,
in which a memorial addressed to both Houses of Congress, against war, was adopted,
and the committee nominated to prepare it, was directed to have it presented;
which was accordingly done.

26th. This morning in the silence, after reading to my family in the New Testament,
the Master, in tender mercy, drew near, and renewed my faith in Him,
and in his unfailing goodness;
so that I was enabled to adopt in secret the language of his disciples,
"`Now we believe and are sure that you are that Christ, the Son of the living God.`"
Hereby we know that He is the author of all true
and saving faith when He manifests Himself to us,
after seasons of great desertion, and clothes us afresh with it;
so that we are made sure that it is He and not another;
the immutable Rock which will sustain all who are built up by Him on it.
Oh that I may be favored so to live as to continue to be a
partaker of such marks of Divine mercy and kindness.

Second month 1st. Our Quarterly Meeting was a season of inward suffering;
the spring of Divine life not being felt to flow among us,
to the solacing and cheering of the hearts of the burden-bearers.

3rd and 4th. My wife and myself attended Abington Quarterly Meeting, held at Germantown,
which is a small company, particularly the select meeting.
To the members who compose this small body, the language of encouragement was extended;
and in the meeting for discipline of the general meeting,
I was enabled to invite the young men to be faithful to
the manifestations of the Light of Christ,
and they would feel themselves bound to maintain the
doctrines and testimonies of the gospel held by Friends,
wherever they went, both great and small.

Hereby they would be prepared for service in the church,
and be constrained in our meetings for discipline,
to speak a word in the authority of Truth, at the Master`'s bidding,
to the business before their meetings.
They would feel it a religious duty to support the discipline,
and to stand for the blessed cause, entrusted to our Society to uphold in the world.

Third month.
On the 28th, being first-day, I went to the Northern District Meeting,
feeling a particular draft there;
and was led to treat upon the beginning and growth of true religion in the heart;
which is through obedience to the requisitions of the blessed Savior, made known there.
Also to show the benumbing, stupefying effects of a constant pursuit of riches;
in which the extraordinary talents bestowed upon man,
by an all-wise and beneficent Creator, are prostituted to inferior objects;
so that he finally loves and serves the creature, himself and his temporal acquisitions,
instead of the Creator.
Thus the great and noble purpose for which he was made, to glorify God, is lost sight of,
and altogether neglected.
There was also a cup of consolation and encouragement to the sincere in heart,
to keep their trust in the Lord alone, who never was foiled in battle;
but whose omnipotent arm is round about to preserve,
and will carry through and over all opposition, those who look to and confide in,
and follow Him faithfully to the end.

31st. I attended the Western District Meeting; and after some time of silent waiting,
it opened to me, to show the way by which we come to obtain peace with God,
through our Lord Jesus Christ; namely, by denying ourselves, taking up the cross,
and obeying his commands, as He makes them known to us by his Spirit.
No device of ours will be taken as a substitute.

God will not give his glory to any other, but to his well-beloved Son,
whom He has given for salvation to the end of the earth; and if we are saved,
it will be by Him, and that by doing his will.
To these He gives the reward of true peace, for every sacrifice and service,
which is performed by his direction.

The Lord helped me, by his saving strength, to preach the gospel of life and salvation,
through Christ Jesus, both in the flesh as He walked among men, and in the Spirit,
as He appears in our hearts by his light and grace, to the tendering of some present,
and to my own peace and comfort.
Blessed forever be his great and glorious name and power!
He still condescends to the low estate of his poor unworthy creatures;
lifts them up at times out of their depressed conditions;
gives them the oil of joy for mourning, and shows to them,
that He has not forgotten to be gracious;
unworthy as they are of the least of his mercies.

Fourth month 12th. Yesterday morning my wife and myself went to Wilmington,
to attend the funeral of our late beloved friend John Bullock,
who died suddenly with apoplexy.
He had of latter years become increasingly valuable to his friends,
and to religious society; his removal is a great affliction to his relatives,
and trial to the meeting there.
We felt deeply for them, and in much sympathy, believed it right to be at their meeting,
on first-day, as well as to pay the last respect to the memory of our worthy friend.
Both morning and afternoon meetings were favored opportunities;
many hearts being humbled and contrited,
under a renewed sense of the Lord`'s mercy and tender compassion,
even towards the rebellious.
The honest, exercised remnant there, on whom much weight rests,
for the sake of the cause and testimony of their God, were comforted,
and a little strengthened in the hope that He will not cast them off,
or forsake his people,
though He permits them to be closely proven in the removal of dear fellow helpers.
We had cause to bless his holy name, for the evidence which He gave,
that He grants the immediate help and strength of his Spirit,
and puts words into the mouths of his servants, to speak to the people, in his authority,
and to their refreshment;
attended with the conviction that they are handed from the Lord`'s treasury.

26th. Our Yearly Meeting was held last week.
I believe the Lord wrought for his faithful, dedicated children,
and brought them through, to his honor, and to their comfort and humiliation.
The reading of the document containing an exposition of
erroneous passages from the works of two writers in England,
with the other minutes of the Meeting for Sufferings,
occupied all third-day and part of fourth-day morning.
Soon after finishing, the manifestation of unity commenced,
and a large number expressed their satisfaction with the document.
Opposition to it was, however, made by some; to which little reply was offered,
except so far as to explain some facts, which were misstated,
in order to make clear the right of the Meeting for Sufferings,
to prepare the exposition; and that it was called for,
in defense of our religious principles, and in defense of our own Yearly Meeting;
inasmuch as we had been frequently calling the
attention of Friends in England to those writings,
as containing sentiments inimical to the faith of Friends.
Much patience and deliberation were manifested by those who united with the document.
Many, as they had opportunity, seriously gave their voices in favor of it,
after listening to the objections which were made.
Friends in favor of the meeting sanctioning it, spoke in a decided and serious manner;
and evidence was given, that it was the prevailing, solid sense of the meeting,
it should be adopted; and a minute to that effect was made; to which, at the last,
little opposition was offered; and the meeting, in a short time,
settled down in a quiet and peaceful feeling;
which satisfied many that it was owned by the Head of the church.
To those who have been long burdened with the unsound opinions in these books,
it was a great relief that the meeting was enabled to come to this decision;
and they believed it was to be attributed to the superintendence and
controlling power of the Blessed Head of the church;
and humble gratitude clothed their spirits.
The remaining business of the meeting was conducted with solidity,
and brought to a close, under feelings of solemnity.

Fifth month 13th. I attended Salem Quarterly Meeting,
and felt my mind clothed with very affectionate desires,
that all might be kept under a fervent travail of spirit,
and thereby become fruit-bearing branches of the true Vine,
to the praise of the Great Husbandman.
The language of sympathy and encouragement flowed to the true burden bearers,
whose faith is proved, and great poverty of spirit their portion.
And the young people were addressed in the language of persuasion,
to obey the requirings of the Shepherd of the sheep,
and turn their backs to the temptations of Satan, take up the cross and follow Christ;
who would prepare them to shine as lights,
and to exalt and honor his name and glorious cause in the earth.
It was a time of favor from the Lord, whose mercies are new every morning;
though we are often withheld from perceiving them.

I returned home on sixth-day morning, the 14th, with a peaceful mind,
replenished with a fresh sense of the benefits of
mingling with our distant friends at the Lord`'s bidding;
in which the invisible fellowship is strengthened and revived.
Since this visit,
I have been wading along under discouraging prospects of the condition of the Society,
and with but little ability administered, to draw near to the inexhaustible Fountain,
either in or out of meeting.
This has excited desires for increasing watchfulness, and solid demeanor before all.

Sixth month 1st. My wife and myself went early this morning to Woodbury,
and attended their Monthly Meeting; in which both of us had some service.

8th. After calling at the recent residence of our cousin Ann Scattergood,
who died the preceding evening; I went to the Northern District Meeting,
and sitting under much poverty of spirit,
even while a dear Friend was engaged in the ministry;
there seemed finally to be a little quickening virtue felt,
under which I was engaged to bear testimony to the sufficiency
of the everlasting Shepherd and Captain of salvation,
to carry on the work, in and through his faithful children,
to the end of their heavenly journey.
"`Oh that +++[+++my people]
were wise, that they understood this, that they would consider their latter end!
How should one chase a thousand, and two put ten thousand to flight,
except their Rock had sold them and the Lord had shut them up.`"
The daily consideration of our latter end,
tends to give us a proper estimate of things under the sun;
even the comforts and accommodations with which we are surrounded; and at the same time,
to centre our thoughts and affections upon that eternal weight of glory,
which is to be hereafter revealed to the steadfast followers of the Lamb.
I thought the Lord mercifully granted a little fresh ability to advocate his cause;
which is dignified with immortality, and crowned with eternal life,
and to hand a morsel of bread to comfort some weary travelers.

29th. This morning my dear wife and myself left for Greenwich, New Jersey.
The weather was warm, but being in a fast-moving boat, we had a pleasant breeze;
and from the upper deck, the view of the islands,
and the scenery along the shores of Delaware and New Jersey,
with the great expanse of water below Reedy Island,
made the trip very pleasant and refreshing.

Our beloved cousins, George and Naomi Bacon, with other Friends,
received us with much cordiality.
We attended their Monthly Meeting on fifth-day.
In the meeting we had some service to the exaltation of the name,
and goodness of our God; who watches over,
preserves and provides for those who give themselves up to his requirings;
both in temporals and spirituals.
The hearts of some were contrited and comforted,
in a reverent sense of the Lord`'s mercy and kindness, still extended to us,
an unworthy people; though there are, perhaps, in every meeting,
those preserved alive in the Truth, and, I hope, growing in it.

On first-day, we attended the meeting at Salem; in which my dear wife was drawn forth,
in fellow feeling with some who were partaking of bitter trials, so as, at times,
to feel life almost a burden, and to desire a release;
but she said she believed if their sufferings were rightly borne, they would,
under the Divine blessing, prove a means for the sanctification of the soul.

The language of sympathy and encouragement, through her, had a tendering effect;
and I have no doubt, met with an answer of, so be it, in some hearts.
I was engaged to call the attention of some to the
importance of showing their love to Christ Jesus,
in whom we profess to believe, by keeping his word, and the commands He gives us to obey.
It seems to be an easy matter, in this day of great biblical knowledge,
to make a high profession of belief in Christ;
and for people to think themselves justified by this belief;
but it will avail little to those who do not keep his word in their hearts,
and bring forth the fruits thereof, to the praise of our Heavenly Father.
"`If a man love me,`" said our blessed Lord, "`he will keep my words;
and my Father will love him, and we will come unto him, and make our abode with him.`"
It is thus only that we can witness the love of God shed abroad in our hearts;
and through the Holy Spirit, hold communion with the Father, and with his dear Son,
our Lord Jesus Christ.
My beloved wife concluded the meeting with solemn supplication.
In the afternoon we visited two aged Friends, to one of whom she spoke encouragingly.

Seventh month 5th. We took the steamboat for home,
feeling satisfied with the little visit,
and hoping that although what was done was in weakness and fear,
it would tend to the strengthening of the good in some.

13th. Was at the North Meeting; in which Ezekiel`'s vision of the dry bones in the valley,
which were very dry, was brought before me.
It seemed not only to represent the state of many of the house of Israel,
who were very destitute of the love and life of God in their hearts,
but also the condition of those who were baptized for the dead, and who, at times,
such was their stripped and destitute condition,
as to the sensible feeling of the life-giving presence of the Lord,
were ready to doubt whether they would ever again experience it,
and be enabled to stand before Him with acceptance.
Yet He, who is the resurrection and the life,
can and does breathe on bones whose energy is departed,
clothe them as with sinews and flesh, and breathe into them the breath of life,
and raise them up as an army for his service.
I hope a little of his quickening virtue was felt among us this day.

16th. Our Meeting for Sufferings having adjourned to this time,
forty-seven members convened; and the committee to whom had been referred,
by the Yearly Meeting, the document upon the unsound doctrines,
now reported a few alterations, which were read to the meeting, and adopted.
None of them abated the force,
or varied the character of this testimony for the truth of our ancient doctrines.
There was a very united and solemn feeling over the meeting;
but two members dissenting from the publication of it.
Christopher Healy and Ezra Comfort bore lively testimonies to
the sweetness of the covering spread over us;
and though one of them seemed to foresee further close trials awaiting the church,
they both believed as Friends kept steadfast to the Truth,
victory would finally be obtained over that spirit
which is seeking to lay waste our precious faith.
I hope that the Appeal put forth for the Ancient Doctrines will be blessed,
to the comfort and settlement of many in the right way of the Lord.

Eighth month 18th. Of latter time being under much exercise,
and at seasons clothed with many fears,
I have had little call openly to speak in the assemblies of the Lord`'s people;
and when I have believed myself constrained to stand forth on
behalf of my gracious Lord and Master and his cause,
it has been in but few words, yet attended with the evidence of being rightly authorized,
by his peace shed abroad in my mind.

Today I felt called on to bear testimony, that He,
who gave his disciples power over all the power of the enemy,
so that nothing should by any means offend or harm them, was still with his faithful,
devoted children; and according to their respective conditions,
growths and services in the church,
would give them power over all the power of the enemy,
in the various assaults and temptations with which he may be permitted to buffet them;
if on their part they keep faithful to Him.
Christ only knows the depth of baptism needful for the
humiliation and refinement of his disciples;
and if they hold fast the grain of faith, which will never be entirely taken from them,
in his time, He will appear to them, as the resurrection and the life; renew their faith,
and grant an evidence, that their feet are upon the Rock of ages, the sure foundation,
against which the gates of hell cannot prevail.

19th. I went to Haddonfield, and attended that meeting;
in which I was drawn forth to say close things to some,
who were doing despite to the offers of Divine love and mercy to them:
who had become like the heath in the desert, in a dry and barren soil;
not partaking of the water of life, by which alone the soul can be kept alive unto God;
and such is their insensibility, that they know not when good comes.
These were pleaded with, to lay these things solemnly to heart;
for the time was fast approaching, when the awful message would be sounded in their ear,
"`Steward, give an account of your stewardship, for you may be no longer steward.`"
Also the fearful, trembling followers of Christ, were encouraged to keep the faith;
for in his time He would shed abroad his peace in their hearts,
and grant an evidence of his acceptance and approbation.
Called upon a few Friends, and returned home in peace.

26th. My wife and myself attended Plymouth Meeting;
in which the Master employed us in his work,
both for the warning of those who are in danger of
being swallowed up with the spirit of the world,
and in comforting and strengthening the feeble and weary, who love the Truth,
and desire its prosperity more than anything beside.

Ninth month 17th. The Meeting for Sufferings, which met today, was large.
The exposed condition of the free colored population of our State, was considered,
and referred to a committee on slavery.
The meeting agreed to stereotype Robert Barclay`'s
Apology for the true Christian Divinity,
as believed by Friends.

26th. First-day.
I went to meeting this morning,
humbled under a sense of the many snares and dangers which surround all,
especially young people; and my soul was poured forth in mental,
fervent supplication to the Lord,
that He would be pleased to preserve my dear children in purity,
and in a state of acceptance with Him.
I renounced all desire for riches or worldly greatness,
and craved that He would make them his by adoption, and prepare them for his kingdom.

Tenth month 2nd. In consequence of using an expression undignified,
and betraying a lack of watchfulness, mortification and abasedness were my clothing.
There is nothing pertaining to us to glory in--nothing we can
glory in--save in the cross of our Lord Jesus Christ,
by which we are crucified to the world, and the world unto us;
and when every wrong thing in us,
is crucified and made subject to the dominion of Christ,
then we have good cause to give glory to the power and
goodness by which we are subjected to Him.

10th. Friends and others are returning from their country residences,
by which our meeting is enlarged.
That love, which leads to desire the everlasting welfare of souls,
covered the hearts of some,
and a renewed qualification was granted to invite all to faithfulness,
in obeying the clear requisitions of our Heavenly Father,
made known by his spirit in the heart.
It is this which will dignify and make men truly honorable;
a blessing to their fellow creatures;
and prepare them for the society of saints and angels, and the church of the first-born,
whose names are written in heaven.

24th. First-day morning, at our meeting,
I was engaged to call upon some to embrace the offered gift of repentance,
that they may receive strength to "`work while it is called today;
for behold the night comes wherein no man can work.`"
No man can command these offers of mercy and help.
It is then his highest wisdom and interest,
to lay hold of them when he is favored with them,
lest the awful period come when he may be called
to appear in the presence of his Almighty Judge,
and he be unprepared for the solemn event.
Next day,
a well-concerned Friend told me that what was said was his exercise reduced into words.
It is pleasant, when the day laborers are favored to see eye to eye,
and to bring forth good fruit.

26th. Through much doubt and discouragement, I went to the North Meeting.
Dear Rachel Thornton was there, and had a consoling testimony to those, deeply proved.
My mind was turned to the dear young people,
who were exposed to the evil insinuations of the wicked one;
both by the fluctuations in the Society,
and his attempts to captivate them with the fashions of a corrupt world.
The Lord`'s presence was with us, and solemnized and tendered some hearts.
It showed me the need of walking by faith, when there is little sight;
and when the grand deceiver would prevent us from doing our duty;
thereby robbing the church, and losing the reward of Divine approbation and peace.

Eleventh month 1st. Having obtained a minute of the unity of
the Monthly Meeting to attend North Carolina Yearly Meeting,
and to visit some meetings belonging to it,
I left home this morning under feelings of desire for preservation.
My beloved friend Henry Cope, who also obtained a minute, accompanied me.
I had for many months felt affectionately drawn towards some meetings there;
and light seemed to shine on some places particularly.
Love warmed and softened my heart towards dear Friends in that country;
and the pointing was so strong, that it appeared to be unsafe to disregard it;
and I had accordingly opened it to the Monthly Meeting,
and a free expression of unity followed.
We left by railroad about eight o`'clock; and in passing through Baltimore,
called on a few Friends; and reached Washington after dark, where we lodged.

2nd. Took the steamer on the Potomac; landed at Aquia Creek,
and from there proceeded in the cars to Richmond and Petersburg.
On the way I had conversation with two slaveholders;
one of whom I found afterwards was Governor of Virginia.
He argued that our Savior never forbade slaveholding;
but I replied that the spirit and principles of his religion were against it;
and that the precept, "`All things whatsoever you would that men should do unto you,
do you also unto them;`" would put an end to it.
But they were hardened against everything that would oppose their favorite system;
and to me they appeared to hold in light estimation the
authority of the christian religion.
On the subject of war, they were equally in the dark.
One of them strove to cast a slur on Friends; saying,
that they would fight in cases of great emergency.
But I referred him to the seventy years government of Friends in Pennsylvania,
during which no war took place there; and also the firm constancy of Friends in Ireland,
during the civil war there, in which but two of the Society lost their lives,
and they because they took up arms.
This man finally admitted the many corruptions inseparable from slavery,
and its disadvantageous influence wherever it exists.
I believe there are seasons in which such are brought under conviction,
that the holding of slaves is wrong, and that it is a curse upon the country.

Supped at Petersburg, between eight and nine o`'clock;
and after arranging our baggage in the burden car, for Raleigh,
set out and travelled all night; changing cars twice,
in which we found poor accommodations for sleeping.
Got to Raleigh near noon on the 3rd. Took the mail stage,
and had a wearisome ride through the night; the stage being crowded, and heavily laden.
We reached Greensborough between one and two o`'clock, dined, and in the afternoon,
went in the Salem stage to the Boarding School at New Garden.
Here we met our friend Dougan Clark, who invited us to put up with him,
and we accordingly walked to his house, being about one and a quarter miles,
and felt ourselves agreeably accommodated with himself and valuable wife.

5th. We were taken to Deep River, to attend the Meeting for Sufferings.
The business consisted principally in endeavoring, through committees,
to secure the freedom of colored people,
placed by slaveholders under the charge of Friends;
to have them transferred to other parts of the Union, where they can enjoy their freedom,
unmolested by the cruel and unjust laws, which the State has passed,
to bind the shackles on the poor down-trodden slave,
and to discourage and prevent the holders from giving them their liberty.

6th. Attended the Meeting for Ministers and Elders,
in which I was engaged to hold up the importance of maintaining our testimony to
the spiritual nature of Divine worship under the gospel dispensation.
It requires devotedness to the Truth,
and a willingness to endure mortification before the people, at times,
in a steadfast waiting for the Master`'s life-giving presence;
not daring to put forth a hand to any work,
until He appears and gives strength and authority for it.
If this precious testimony, by which we are much distinguished from other denominations,
is not preserved, the Society must go down.
After meeting, we rode back to New Garden.

7th. The meeting for worship this morning was crowded, and for a long time much disturbed.
I felt impressed with the necessity of advocating the
doctrine of the universality of the Light of Christ,
as it shines at times in the hearts of all men.
It gives man a sight of his fallen condition, alienated from God by sin;
and by obedience to it,
he is gradually led out of darkness into the marvelous light of the Lord,
and thus witnesses, as he perseveres faithfully,
a growth and an establishment in the Truth.
Christ Jesus is the author and finisher of the saints`' faith.
True faith is not a faculty of the human mind; but a firm belief and confidence,
produced by the operation of his Spirit on the heart,
that what He requires of man to forsake or to perform,
is the revealed will of our Heavenly Father; and leads us to put our trust in Christ,
the Captain of salvation.
He came to save us from our sins, not in them; and we must be separated from sin,
before we can experience complete justification and redemption.

8th. Second-day morning, the meeting for business commenced.
Towards the close, the importance of rightly holding a Yearly Meeting, coming before me,
and of Friends conducting, during the recess, at their respective lodging places,
in a manner consistent with the object of their coming together,
I felt drawn affectionately to call their attention,
particularly that of the young people, to it;
and to mention a remark made to me in my early going out on religious visits,
by an elder in the church of Christ;
that he always found it best to keep under religious exercise.
This is a state of inward watchfulness; keeping the fear of the Lord before our eyes,
lest we should do anything that would be
inconsistent with the object of our leaving home.
For lack of this, how will Satan rob us and wound us,
and deprive us of the benefit intended by these opportunities.
The young people were invited to guard against
everything of a light and frivolous nature,
by which they would suffer loss.
Friends expressed their unity with it, and wished it might have proper place with them.

9th. The Queries and Answers were read; which exhibited many deficiencies,
in various branches of our christian testimonies.

Individual responsibility, and the proper home education of children,
claimed my attention; and I was led to open the importance of examining our own conduct,
the influence of which, either for evil or for good, may be greater than we imagine.
George Fox mentions, that if but one man or woman lived in the Spirit,
which the prophets and apostles lived in, who gave forth the Scriptures,
he or she would shake the country for ten miles round.
Their influence would extend in many cases further than that.
The Holy Spirit can bring to remembrance the example of righteous men and women,
and thereby convict the evil-doer; and incite him to forsake wrong things,
and come into the way of holiness, and steadfastly persevere in it.
Heads of families were earnestly exhorted to watch over their own conduct,
that they might not say or do anything which they could not approve in their children.
Committed to our care, in the wilderness of this world,
we are bound to do all that is in our power to bring them to Christ;
and to do nothing that would lead them into the spirit and customs of the world.
In the awful day of account, it will be of unspeakable importance,
that the blood of others is not found upon our garments.

The practice of frequently reading the Holy Scriptures in their families,
was also pressed upon Friends; and that it be done in a serious manner,
with hearts turned to the Lord; in which, at times,
the spirit of supplication is poured out upon such,
and they enabled to pray in spirit for themselves, and their beloved offspring.

10th. Fourth-day.
Attended the Meeting of Ministers and Elders;
in which was pointed out the necessity of elders coming under a
measure of the same Divine anointing imparted for the ministry,
to qualify them to discern and judge between thing and thing.
Between that ministry which comes from the true gospel spring,
and that which originates in the activity and imagination of the natural mind;
that while they properly encourage and cherish the timid and fearful,
in the exercise of the gift committed to them,
they may discourage forward spirits that run into words without life and authority.
Dined at the schoolhouse; attended the adjourned sitting of the Meeting for Sufferings;
and returned to our lodgings.

11th. Fifth-day. The business of the Yearly Meeting was concluded.
