== Chapter XX

[.chapter-synopsis]
* 1847--1848. Continuation of Visit in North Carolina
* Trials at Home, and Services in its Neighborhood
* Extract from a Letter
* Views on Separations.

1847, Eleventh month 12th. We remained until near evening,
with our dear friends D. and A. Clark,
and then were taken by their son to a Friend`'s house, where we lodged.
Next morning, he took us to Centre, where we attended the Western Quarterly Meeting.
Here the Lord gave me renewed ability to preach the gospel of Christ Jesus;
showing that every member of his body is prepared for his place therein,
by knowing the working of the Lord`'s mighty power,
in his own regeneration and sanctification, in the first place.
When his service is assigned, he must rely for wisdom and strength to do it,
upon Him who taught him obedience to his will,
in resisting and overcoming the assaults of the enemy; and, from time to time,
delivered him as out of the paw of the lion and of the bear.
The examples of Moses and David, in the wilderness, when,
in the care of their father`'s sheep, they were divinely instructed in solitude,
and prepared through obedience to the Divine voice,
and in that saving faith with which the Lord inspired them,
for more public and extensive usefulness among his people, were opened to the meeting.
The young people were earnestly entreated to come under the government of Christ,
that they might occupy the stations designed for them,
and reap the reward of his sweet peace.

14th. First-day.
Rode several miles to Springfield, where many, not professing with us,
attended the meeting.
The state of those, who like the Jews,
were pleasing themselves with being Abraham`'s children,
but whose works do not prove them to be in the faith of Abraham, came before me.
Outward advantages increase our responsibility, but unimproved,
will not recommend us to the Divine regard;
nor will the disadvantages under which many are placed, deprive them of the Lord`'s favor,
if they do not bring them upon themselves by wrong doing.

"`Of a truth,`" says the apostle, "`I perceive that God is no respecter of persons;
but in every nation, he that fears Him and works righteousness, is accepted with Him.`"
All outward distinction will avail nothing,
unless we are walking in the footsteps of Christ`'s companions,
working righteousness in the fear of God.
The awfulness of being found without oil in our vessels, with our lamps,
when the midnight cry is heard, was solemnly held up to view.
Some were warned of losing the spirit of discernment, with which they had been favored,
and by keeping to which alone, they can distinguish the voice of the true Shepherd,
from that of the stranger.
The sheep of Christ know his voice, and they follow Him.

The meeting ended with supplication for the continued mercy,
and preserving power of our Heavenly Father, extended to his church and his people;
that He would regard our infirmities, forgive our sins,
and enable us to ascribe unto Him, to whom alone it belongs,
with the Lamb who sits on the throne, all glory and honor, salvation and strength,
through the eternal Spirit, now and forevermore.
Amen.

On the 16th, we went to New Salem,
where we had a meeting with the few Friends residing near, and in the village;
also some other persons who had been invited.
The nature of Divine worship,
the necessity of being brought off from all dependence upon man,
and coming to an inward acquaintance with the Lord Jesus,
relying upon Him as our teacher and minister, were set before them.
All the efforts of man, in his will and time, to comprehend the truths of the gospel,
or to teach others the way of religion, will be fruitless.
Man, in his natural condition, may set himself to work, and conclude he knows much;
yet proceeding from his own spirit it will not work the righteousness of God,
or promote the Redeemer`'s kingdom.
I felt much for the young people,
and warned them of the machinations of wicked men and women,
who were trying to draw unsuspecting young people into their evil practices.
For those who were striving to do right, I was prostrated in vocal prayer,
that they might be strengthened, and that the visitations of the Lord`'s love and mercy,
might be extended to the young people;
bringing them to submit to bear the yoke and cross of Christ,
and preparing them to uphold the standard of pure righteousness where they dwell.
We put up with a son of Dougan Clark`'s,
where we were very comfortably and agreeably entertained.

17th. This morning, he took us over to Marlborough, about five miles,
where we attended their regular meeting; which was a pretty large gathering,
notice of our intention of being there, having been spread.
Here I was enabled to relieve myself in the love of the gospel, towards Friends,
of which the meeting chiefly consisted.

18th. We had a rough, tedious ride to Holly Spring,
the route being over roads not much used, and in bad repair.
The land was very poor, and thinly populated.
I thought I should soon wish to be released from this world`'s concerns,
if I was fixed in some places through which we rode.
It was the time of their Preparative Meeting, and the company was nearly all Friends;
to whom I was led to speak of the importance of
being under a daily travail and watchfulness,
that we may be favored with a discerning spirit,
so as to detect the insinuations of Satan, in his various attempts to deceive;
whether in our individual capacity, or in the church.
By faithfulness to the Divine Word, who is a discerner of the thoughts,
and intents of the heart,
a qualification is received to judge righteous judgment in the church.
We dined at Enoch Barker`'s, who, with his children,
appear to be acquainted with the cross.
The company of such Friends is animating.

Rode about two miles, and lodged.
In the night it commenced raining, and continued most of the morning,
which made traveling, over bad roads, but little frequented,
quite disagreeable and tedious.
In one place, we were obliged to get out of the carriage, and keep it from overturning.
We reached our friend John Newlin`'s, near the Spring meetinghouse, towards evening,
and were received and entertained by him and his family, in a kind and hospitable manner.
At New Garden, he told us, "`If you come to my house, you will get to Raleigh,
which we found to be about forty-seven miles distant.
Accordingly preparation was made, and the following morning, the 20th, we got off,
and rode about thirty-seven miles; parts of the road being very hilly;
and put up for the night at a private house of entertainment.

Before leaving John Newlin`'s,
I felt drawn to acknowledge the kindness of Friends in providing for us,
and to express my desire, that as some of us were descending the hill of time,
while it is a duty to attend to our necessary worldly avocations,
we may keep in view the importance of preparing for that city which has foundations,
whose builder and maker the Lord of Hosts is.
We parted with feelings of respect and affection for the parents and children,
not knowing but that it might be the last time we should visit their habitation.

21st. After taking breakfast, we rode into Raleigh; directing our course,
when reaching the suburbs, to the house of a free colored man, who keeps a livery stable,
and carriages to hire, with whom we contracted to be taken to Rich Square.
Being desirous of reaching the meeting held there on fourth-day, we set off,
after taking dinner at the colored man`'s table, and rode twenty miles, to Foster`'s,
a private house, where we supped and lodged.

22nd. Rose early, and rode twelve miles to Crenshaw`'s, to breakfast.
Rode about thirty-five miles, between breakfast and night,
and put up at another private house, in which we had little comfort,
the views and habits of the inmates being very different from congeniality with our own.
Here we fell into conversation with a young man upon the poverty of their farms,
and the very reduced value of the land; which he told us,
would not bring much more than two dollars an acre, with all the buildings and fencing.
We suggested that the cause was keeping slaves, which he could not deny;
and when we informed him of the worth of land in Pennsylvania,
and the steady advance in quality, improvements, and price, he seemed surprised,
and thought he should like to travel through those parts where
such cultivation and its fruits are to be found.

We retired early, but were disturbed by their music and dancing;
rose before any of the family were moving, having paid our fare over night,
and rode eight miles to breakfast, at Enfield.
Here we obtained directions respecting the road to Pollock`'s Ferry, on the Roanoke,
and set out.

On the Roanoke, where we crossed, are fine farms,
owned by a person of the name of Devereux, a large slaveholder.
The soil is rich, and his crops are said to be very great and profitable;
but the fact that they are produced and gathered by the toil and sweat of men and women,
who have no more interest in them, than the cattle by which the land is worked,
detracts altogether from the satisfaction we should
otherwise have in viewing such flourishing farms.
Getting directions respecting the road, we found our way to T. and E. P.`'s,
through miles of timbered land.
They received us with much cordiality; which was truly pleasant,
as we had looked towards this place with apprehensions
of difficulty in timely reaching it,
and fearing, if we did accomplish the journey,
we might not find any conveyance to Piney Woods,
where the Quarterly Meeting is held at this time; about seventy miles ride.
But on enquiry, we found provision had been made for us in that respect also;
which was cause of thankfulness to our Heavenly Father,
as well as gratitude to our friends;
strengthening us in the belief that we were under his guidance and protection.
We spent the evening in interesting conversation with our friends.

24th. It was a favorable circumstance that we had dry weather,
on our journey from Raleigh here, as our carriage was small and exposing.
Last night it rained, and this morning had a very unfavorable appearance;
but being provided for, we went to Rich Square,
the meeting to which Richard Jordan belonged, when he resided in North Carolina.
The company was small, some having gone to Piney Woods.
I felt low and weak, and fearful of making any mistake;
but being impressed with the great importance of purity of heart,
that man may be prepared to hold communion with his Heavenly Father,
and beholding with an eye of faith,
the secret travail of spirit which the visited obedient
soul is brought under to attain to this purity,
I believed it right to rise with these impressions, and to deliver in a simple way,
what might be given me.
As I went on, in singleness of heart to the Lord, the gospel stream rose a little,
to the tendering of some, and I hope to the instruction of others.

After meeting, taking leave of our friends with feelings of sincere affection,
we went with J. C. to his house, and lodged.
The afternoon being rainy, we deferred setting off for Piney Woods until morning.
In the evening, two or three young Friends being also there,
we collected around the fire, and fell into silence; and unexpectedly to myself,
I felt drawn towards the heads of the family,
with affectionate solicitude that they might keep the world and its necessary concerns,
in their proper places; so that all their duties to their Heavenly Father,
and to each other, might be rightly performed;
that the cumbers and cares of this life might not interfere with that devotion of spirit,
which is essential to a growth in the Truth,
and the performance of the services which the Head of the church calls for;
which I was engaged to communicate to them.

25th. We set off pretty early, crossed the Chowan River in a flat,
and on its bank refreshed ourselves with some food brought in the carriage.
Then proceeded on our way, riding often through water,
sometimes a fourth of a mile at a time,
which flowed over the road from surrounding swamps,
making traveling often laborious for the horses.
We called at two private houses, before we obtained accommodations for the night,
there being no taverns on the road, and were grateful to find one willing to take us in;
night coming on and we pretty well fatigued.

We paid the landlord freely, though he seemed unwilling to take the full price.
In the Southern States, the people are noted for their hospitality,
without making charge for food and lodgings; and, therefore,
willingly receive the same kindness gratuitously, which they have bestowed on others.
But being strangers, I did not feel satisfied to receive entertainment without pay,
from those on whom we had no claim, and to whom we could make no similar return,
and therefore insisted on the landlord receiving more than he proposed;
which was not adequate to the comforts of which we partook.

26th. One of the swamps being much filled with water, and the road being under repair,
by the erection of a bridge, we had to drive five miles further, to get to David White`'s;
whose residence we reached by half-past ten o`'clock.
We went to the Select Quarterly Meeting; in which the stream of Divine life seemed low,
and little was felt for communication.
Returned to David White`'s, and remained there till the following morning.

27th. The Quarterly Meeting was attended, during the first sitting,
by many persons not of our profession.
The necessity of being born again; of being converted and becoming as little children,
as inculcated by our blessed Lord, was brought before me;
and He who opens and hands out of his treasury to his disciples, things new and old,
was pleased, in his goodness and condescension, to enable me to preach his gospel,
in the demonstration of the Spirit and power.
I hoped his great name was exalted.

28th. I was at the first-day meeting,
which was a large collection of people of various characters and professions.
I endeavored to do what appeared to be my duty, but felt little comfort,
though I believe some Divine aid was extended, and some hearts contrited.
I strove to leave it all to the Lord, and bear my own burden.
Such dispensations of the sense of unprofitableness, are in wisdom;
and when properly borne, tend to humble,
and lead us to acknowledge that we are unprofitable servants;
and that if at any time we have done any good, it has been the Lord`'s work,
to whom all praise and dominion belong.

We rode twelve miles in the afternoon, to William Wilson`'s, where we lodged.
Rose early, and after taking some breakfast,
W+++.+++ Wilson kindly conveyed us in his carriage to Elizabeth City,
to meet the stage for Norfolk.
We barely secured our passage, so many were going.

We rode about forty-five miles to Portsmouth,
which we reached some little time before the Baltimore steamer crossed from Norfolk,
on board of which we took our passage.
It was rendered unpleasant by the improper
conduct and language of an intoxicated young man;
but I felt thankful we were permitted to land safely, in the morning;
the passage up the Chesapeake Bay being long, and the wind pretty strong ahead,
and the water sufficiently rough to cause sickness in some.
Breakfasted at the hotel, took seats in the Philadelphia car,
and arrived at our beloved homes in the afternoon;
thankful to be again united to our dear companions and children.

It is cause of gratitude to the God and Father of all our sure mercies,
to be preserved from danger and serious accident; and to believe that He provided for us,
and was our guide, so as to perform the work He assigned us to do.
May I be favored with his continual providence in my outward and spiritual concerns;
so as to be kept obedient to his will, and sanctified and fit for his use,
through the cleansing, quickening efficacy of his Divine Word in the heart,
unworthy as I am of the least of all his mercies; to whom, with his dear Son,
our Lord Jesus Christ, be ascribed all glory and honor, thanksgiving and praise,
world without end.
Amen.

1848, First month 11th. Soon after my return,
a young man who had been in my employ several years, left me,
to commence business for himself.
This made it necessary for me to confine myself much at my store.
I had several offers of assistants,
but could not feel easy in my own mind to employ any of them;
there being something in their appearance, and the feeling I had respecting them,
which deterred me from taking them.

Under these circumstances, I seemed, at times, let down to the bottom of the mountains;
there being little to console from without, and the spring much shut up within.
But I waded along, and the Lord gave me some tokens of his continued mercy,
and the word of command to tell it to others.
Some of our evening meetings were solid and encouraging.
In due time, the way satisfactorily opened to employ a person,
who served his apprenticeship in the same store I did.
His age and stability, and his knowledge of the business, made it easy for me to leave,
when necessarily absent, on appointments, or any religious engagement;
which I esteem a favor from the hand of my heavenly Caretaker and Protector.
It appeared to me there was an evidence in it of providential regard.

31st. I was brought low last week,
in consequence of a remark which I made applicable to another,
though not of great moment, yet inexpedient, at least for one in my station.
It renewed strong desires to be favored with more watchfulness,
and care over my words and actions; so that no offense may be given to Jew or Gentile,
nor the children turned aside from the right path.
What a blessing to be favored with a monitor in our own breast,
that swiftly condemns for wrong, or for an unguarded expression,
and by which we are led into fervent intercession, that we may not be left to ourselves,
nor suffered to lose the standing we may have, through mercy, attained in the Truth.
Yesterday morning (first-day,) it was a struggling time through the meeting,
with little obtained; but in the afternoon,
something of the communion of the Holy Spirit was granted;
by which faith and hope were renewed.
In the evening meeting, I felt constrained to revive the testimony of the prophet,
"`You will keep him in perfect peace whose mind is stayed on you,
because he trusts in you.`"
This peace surpasses everything in this world,
and is the gift of the Savior to his children.
If they keep faithful to Him, there will be seasons in which He will cause it to flow,
as a gentle stream, into their souls;
but if we do not experience it to be dispensed at times,
we may be assured that we are not in the right way of the Lord.
The meeting closed under a covering of solemnity.

Second month 1st. My wife and myself went to Germantown,
and attended Frankford Monthly Meeting held there.
We were both engaged in the ministry;
she in encouraging the tried and fearful ones to hold on their way,
keeping fast hold of the shield of faith, and not casting it away; for on Mount Gilboa,
where the shield of the mighty was vilely cast away,
David desired there might be neither dew, nor rain, nor fields of offering;
the language of consolation to the mourners flowed, to their comfort and strength.
I was engaged to warn some,
of the danger of suffering any temptation to draw them away from that travail of spirit,
which they had been brought under by the Shepherd of the sheep, in his early visitations,
lest they might part with their birthright for a mess of pottage.
If any man love anything more than Christ, he will not be worthy of Him.
"`If any man love the world, the love of the Father is not in Him.`"

5th. Was held our Select Quarterly Meeting.
There seemed to be some exercise that the ancient
simplicity might be maintained among us;
and some Friends thought there was an increased feeling of unity,
which it was pleasant to contemplate.

7th. The Quarterly Meeting for business was an unusually solid time.
My dear wife spoke in a clear, searching manner,
going to show that adversity is by the Lord set over against prosperity,
and we shall not escape it.
There was a great solemnity over the people, and when separated,
it continued in both meetings,
and a little ability was granted to search Jerusalem as with candles.

15th. My wife and my sister Hannah Rhoads,
having a draft to Shrewsbury and Rahway Quarterly Meeting, we left home this morning,
and arrived in Rahway, about seventy miles, in three hours and a half.
Our friends kindly met us at the depot, and conducted us to J. P.`'s.

16th. We were provided with a conveyance to Plainfield;
where we put up at the house of J. and M. S.; the latter a minister,
and a firm supporter of the ancient doctrines and testimonies of our religious Society.
Attended the Select Quarterly Meeting, in which we had some service.

17th. We were at the meeting for business.
In the first sitting, my wife and myself were called forth in the ministry of the gospel.
I have seldom felt more divinely helped than on this occasion.
There was a Baptist preacher, and a Methodist preacher at the meeting.
The universality of Divine grace, and the indispensable need of regeneration,
in order to be made full partakers of the mercy and forgiveness of God,
through Jesus Christ our Lord, so as to be thereby saved with an everlasting salvation,
were preached.
Friends expressed in the second meeting,
their satisfaction with our company and services; and, I believe,
some were brought into feelings of renewed tenderness.
It was an evidence of the Lord`'s merciful regard to us, poor, unworthy creatures,
in thus granting a little fresh ability to labor in his heritage.

22nd. This evening a person called at my store for a portion of medicine,
which I put up for her, charging her a small price for it;
she expressed some acknowledgment;
and then asked if I remembered a little girl
getting a prescription put up some time before,
which I gave her without charge.
I told her I did.
She then added,
the money the child brought to pay with was the
last half dollar that her mother possessed;
and when she found that you had not charged for the medicine,
she prayed for you all night, that the Lord would bless you.
From my first entering into business,
I have made it a practice to furnish poor people with medicine,
when satisfied they needed it; and though this was of little moment,
as regards the value bestowed, and in itself nothing new,
yet it was pleasant to think that I had the prayers of a poor,
distressed fellow creature.
"`Blessed is the man that considers the poor;
the Lord shall deliver him in time of trouble.`"
It is but little we can do; but it becomes the followers of a suffering,
yet victorious Savior, to live under the influence of his Spirit, who did so much for us;
and then He will teach us and lead us to feel for the suffering,
depressed condition of our fellow creatures, and to minister to their necessities,
as it is proper for us.

Last first-day and yesterday, the latter being our Monthly Meeting, I was much shut up;
feeling deeply exercised, at times,
on account of the present state of our religious Society.
Many are unwilling to keep under suffering, and with their loins girded,
to watch for the coming of the Master of the house;
whose house are we if we hold fast the beginning of our confidence firm unto the end;
waiting to see what He will order to be done, and then to act under his direction.
There is great danger in putting forth a hand unbidden,
to attempt to steady or to support the ark; both from doing an injury to the cause,
and bringing death upon ourselves; with the query,
"`Who has required this at your hand?`"

24th. To a letter which I wrote to a Friend about this time, I appended the following:
"`In the present unsettled state of our religious Society,
I am persuaded that the place of safety is individual watchfulness unto prayer;
that we may do nothing to create excitement,
by which any may be stirred up to do what will not make for peace,
and receive the Divine approbation.
John Woolman, I think, says, if the church gathers to the place of true prayer,
her habitation is safe.
In that condition alone,
can she be prepared to wait for and to receive the
direction of her all-wise and omnipotent Head.
And if we stand still, waiting for the salvation of God,
we shall have good ground to hope that He will take his cause into his own hand,
and carry the church through all its difficulties, to its further refinement,
and the praise and glory of his great name.
It is a great mistake to grow impatient under suffering; and in order to procure relief,
as we imagine, rush into any measure, incompatible with the order of the discipline.
If others do wrong, bear a righteous testimony against it;
and if it seem to avail nothing, then leave it and them to the Lord,
to do what seems to Him good.

27th. Our evening meetings closed for the season.
They have been mostly solid opportunities,
in which we have had cause to believe that the Master of all
rightly gathered assemblies has been present with us.
The gospel has been at times preached, tendering and solemnizing the hearts of many.
The young people have been especially desirous to have these meetings held,
and their deportment has been becoming the occasion.

May the blessing of the Shepherd of the sheep rest upon them;
bring them forward in their various allotments, to his praise, the comfort of the church,
and their everlasting salvation, is my sincere desire for them.

Third month 1st. At our mid-week meeting, we had several ministers from other parts,
who all kept silence.
My mind was favored with some lively feelings and openings on the
preciousness of keeping the faith and patience of the saints,
even when surrounded by darkness,
and there seems little to lead the truly baptized disciple to believe,
that Truth will gain the victory.
I kept from speaking, not knowing but it might go off,
and some others might be put forth; but when it was near time to close the meeting,
I was afraid to suppress what appeared to be the
putting forth of the Shepherd of the sheep,
and accordingly delivered upon the subject,
what the Master gave me, as I believed, to communicate;
showing that it was Christ alone who can clothe the soul with this faith and patience,
and through which He will make every faithful one victorious.
The same faith by which the holy ancients quenched the violence of fire,
stopped the mouths of lions, and out of weakness were made strong.

Through this faith, we shall be kept relying upon Christ in our lowest state of weakness,
and in his time witness Him to be to us the resurrection and the life.
So that from season to season, we shall be enabled to adopt the language of the apostle,
"`Thanks be to God who gives us the victory through our Lord Jesus Christ.`"
There was a covering of solemn silence spread over the meeting;
in which the tribulated seed rejoiced a little together, in spirit,
and I believe took a little fresh courage to hold on the way.

11th. This afternoon I went with my wife to Springfield;
and next morning attended their meeting, being first-day,
where we had the company of a large number of young men and young women,
most of whom are sober, exemplary Friends.

We attended their meeting on fifth-day;
in which it appeared right for me to labor in the love of the gospel,
to stir up the easy, lukewarm ones,
to a lively zeal on account of the work of their own salvation,
the present and eternal interests of their children, where they were entrusted with them,
and as they were prepared for it, to come under the weight of the ark of the testimonies.

Fifth month 24th. I thought there was a religious
weight over our Monthly Meeting this morning,
under which, desires were raised that we might be seasoned with salt;
experiencing every root of bitterness eradicated,
and put shoulder to shoulder in the Lord`'s work;
so that we might become a body more compacted together,
and be made to realize the blessings designed by being associated as a religions society.

28th. First-day.
This has been a season of poverty, and destitution of any lively,
quickening sense of the Master`'s presence.
Doubts and fears have spread over me,
whether the same degrees of Divine energy and power, will be again vouchsafed to us;
whether so many favors, slighted and neglected by many,
will not occasion the Lord to withhold his visitations very much from us.

Sixth month 1st. My wife and myself went, this morning, to Plymouth Monthly Meeting.
It seemed to be our place to encourage the devoted ones, and the visited young people,
to hold on, in the good old way, in which our fathers in the Truth walked.
The enemy is busy at work to draw us away from close watchfulness over our hearts,
and to persuade us that there is little or nothing in
our testimony to simplicity and self-denial,
and that continual exercise of spirit, in which the outgoings of the mind after ease,
is detected.
And when he has persuaded us that the gentle convictions of Divine Grace are imaginary,
or that it is not necessary to be so strict as our fathers were;
then the way will be opened to inculcate doctrines that our Society never believed; as,
that immediate revelation has ceased;
and thus the indispensable duty of waiting upon the Lord,
that we may hear and know his voice, and be instructed immediately,
as the sheep of Christ, and led along safely by Him, would be forsaken.
It is those who are giving heed to the manifestations of his Spirit in their hearts,
that will be prepared to make a right use of the Holy Scriptures.
These are not afraid to believe and to receive the testimony of the Holy Scriptures;
for they are redeemed from the penalties which they denounce against sin;
and they will be made partakers of the precious promises contained in them.
"`There is now no condemnation to them that are in Christ Jesus,
who walk not after the flesh, but after the spirit;
for the law of the spirit of life in Christ Jesus has
made them free from the law of sin and death.`"
We dined at the residence of our late friend Hannah Williams.

The calmness and sweetness of spirit we felt there,
was like the state of her mind in life, and which, we were informed,
was remarkably shown at the hour of death;
having nothing to do but to wait the coming of her Lord to take her to Himself;
whom she had served faithfully, with her loins girded and light burning;
being an example to the believers in watchfulness of spirit, and purity,
and circumspection in word and deportment.
She was a woman of excellent judgment;
being taught in the school of experience under the
discipline and instruction of her Divine Master.
As she was devoted to Him, and his blessed cause,
He endued her with a measure of his wisdom and strength,
by which she was enabled to discern between thing and thing; spirit and spirit;
and to stand firmly on Christ, the Rock, upon which faithful Friends have ever stood.

15th. My wife feeling her mind drawn to attend Haddonfield Quarterly Meeting,
held this time at Evesham, we were taken there by a friend.
A pretty large company assembled.
Ann Bishop spoke early.
My mind was arrested with the importance of keeping under
suffering for the sake of the blessed Master and his cause,
and for our own benefit and preservation.

The expression of the apostle was brought before me, "`For unto you it is given,
in the behalf of Christ, not only to believe in Him, but also to suffer for his sake.`"
It seemed to me, that inward suffering, in a state of close watchfulness,
was greatly needed; and that much loss would be sustained,
if we were to become a self-active, talking people; and not experience those humbling,
preparing baptisms into our own conditions, needed to fit us for usefulness,
and to bring us in sympathy with Christ who as the Seed,
is pressed down in the hearts of the people, by their worldly thoughts,
and desires after things of a perishing nature.

21st. Having concluded to spend a few weeks with our brother and sister Rhoads,
we shut up our house, and rode to their pleasant dwelling this afternoon,
about twelve miles from Philadelphia.

28th. In calling upon a Friend today,
I was much distressed in hearing him express the opinion,
that in the present divided feeling in our Society, a separation must take place;
because I believe the Head of the Church does
not design it should be split and scattered.
It appears to me to be a device of the enemy; and cannot take place,
unless Friends get off the right ground.
If we are willing to suffer for the Truth, and to wait the Lord`'s time,
we shall not only be benefited and deepened by the trials of our day,
but He will make away for the Society to rise above the workings of the cruel enemy,
and to exalt the precious testimonies He has called us
to bear before the nations of the earth;
in the purity and dignity of the gospel of Christ.

Oh the need there is for patient,
faithful suffering! being willing to go down to the bottom of Jordan,
and abide under the weight of deep concern for the ark,
and for the preservation of the people;
that they may not be scattered from under the wing of the Shepherd and Bishop of souls.

Seventh month 6th. At meeting (Springfield) today,
we were favored with the Master`'s presence, baptizing a number together by his Spirit;
in which a qualification was received to show the necessity of keeping upon the watch,
with our loins girded and lights burning, waiting for the coming of the Master,
so as to open to Him immediately.
Such will know Him to gird himself, cause them to sit down to meat, and serve them.
It was a tendering, uniting season with some; for which we were thankful.
Dined and took tea with our brother, Joseph Evans and his wife;
where we felt our spirits at ease, in sweet fellowship with them;
they being of those who are living in and under
the government and preserving power of Christ.

12th. Attended our own meeting,
which is much reduced by great numbers leaving the city during the warm season;
it was rather a barren time.
Returned to Springfield in the afternoon.

22nd. Went with my wife, and brother J. Rhoads and wife to Birmingham.

23rd. In the meeting at Birmingham,
I felt impelled to open the feelings which had come over me,
of the famished condition that some were in; yet acknowledging that in times of famine,
little benefit might arise from finding fault with one another.
Nevertheless, it was at times needful to remind some,
that if but a small proportion of the labor bestowed,
in laying up the meat that perishes,
was exerted to procure that which endures unto everlasting life,
which the Son of man will give, for Him has God the Father sealed,
professing christians would be in a different condition from what they now are.
Our Savior declared, that "`Except you eat the flesh of the Son of man,
and drink his blood, you have no life in you;`" and if there is no life in us,
we must be dead; in which state, a profession of religion will avail nothing.
It is those who are grafted into Christ, and abide in Him,
that partake of the Divine life and virtue which is in Him;
these eat of his flesh and drink his blood.
But if those who have once been partakers of the good word of life,
and of the powers of the world to come,
through the blessed operations of Divine grace in their hearts,
by unwatchfulness and the influence of the things that perish,
have become like dead branches, they cannot bring forth fruit,
to the praise of the Great Husbandman.

It is our duty to provide for these tabernacles of clay,
as well as to labor for the bread and the water of life;
and the great matter is to keep those duties performed in their proper place.
The heavens are to be kept above the earth; and this true religion will enable us to do.
Many are very industrious in ploughing their fields, sowing, harrowing,
or in gathering in the crops with which a bounteous Creator has blessed them;
but how is it with the field or the vineyard of the heart?
Is the fallow ground there broken up,
and the plant of renown flourishing and bringing forth fruit?
Does that lively concern which they felt in the beginning of their christian pilgrimage,
to know the Divine will to prevail over all in them, day by day,
still warm and invigorate their souls to press on in the great work of salvation?
It is not once in grace, always in grace; for some are spoken of,
who had made shipwreck of faith, and of a good conscience; which they must once have had;
and others, who turned the grace of God into lasciviousness, must have felt its power,
or they could not be said thus to have fallen away from the grace received.

There were other things opened, under a feeling of my own weakness,
and frequent sense of destitution;
and with much brotherly tenderness towards those who
may have suffered worldly things to dim their vision.
My dear wife was enabled, under the spirit of supplication,
to plead with the Father of mercies, to renew the extendings of his love and mercy,
to those who, in days past,
knew his fire to descend and consume the sacrifice upon the altar of their hearts,
but which has become nearly smothered;
that He would be pleased to fan the spark yet left into a flame;
that so there may be a remnant preserved, and a band raised up in this place,
to stand for the cause of Christ, and the spreading of his kingdom.
