== Chapter XXI

[.chapter-synopsis]
* 1848--1849. Religious Exercises at Home, and in different Meetings within Philadelphia Yearly Meeting.

1848, Seventh month 31st. Went to Middletown this morning,
and was at the Monthly Meeting held there.
My dear wife spoke to some convicted ones, before whom the Lord had set an open door,
and invited them to come out of their thralldom to sin,
and enter with the Bridegroom into his rest, from their evil ways and bondage;
warning them as they could not open that door, if they rejected the invitation,
at a future period when He had risen up and closed it, the answer to their knocks,
may be, "`I never knew you.
Depart from me, you that work iniquity.`"
It appeared right for me to follow her, with the language of encouragement,
to those who had taken up the cross,
and entered through the strait gate into the narrow way,
to yield themselves to further baptisms and requisitions;
that they may be prepared for their showing to Israel, more openly in the Lord`'s work.

I believed there were those whom He would dignify and make vessels of honor in his house,
if they were not marred on the wheel, through their unfaithfulness.
My wife appeared in solemn supplication.

Eighth month 1st. It is a precious thing to be
brought entirely out of the spirit of revenge;
returning good for evil, and seeking the present and everlasting welfare of all.
"`Vengeance is mine, I will repay, says the Lord.`"
Endeavor to convince people of their error in the spirit of restoring love,
and if they are not converted from the evil of their way, leave them to the Lord.

4th. Returned to our own habitation, and on the 5th,
attended our Select Quarterly Meeting.

7th. Today was held the Quarterly Meeting for discipline.
Two women Friends were acceptably engaged; one in the ministry, and the other in prayer.

9th. Feeling my mind drawn into sympathy with the small
company of Friends composing Abington Select Quarterly Meeting,
my wife and myself went to Germantown, and attended it.
Tenderness of spirit spread over us,
and we were engaged to encourage them to keep the faith,
and in the leadings of the love of God, through our Lord Jesus Christ,
to visit each other in their respective meetings;
which we believed would have a strengthening effect upon visitors and the visited;
and in the ordering of Divine wisdom,
may be a means of bringing forward in the right way, some who have few to look up to,
like fathers and mothers in the Truth.

13th. The morning meeting was silent; but in the afternoon a number of strangers,
of both sexes, coming in, after a time, I felt engaged to revive the statement,
that in certain places, Jesus did not many mighty works, because of their unbelief;
and to declare that to be the cause why there is so little vital
religion among many professors of Christianity in this day.
They do not believe in the manifestations of the Lord Jesus,
by his Spirit in their hearts.
They profess to own Him as their Lord and Savior, but deny Him,
in refusing to do his will and while they continue in sin, they cannot, in truth,
call Him their Savior; seeing no man can call Him Lord but by the Holy Spirit;
and those who are turning, their back upon the convictions of the Holy Spirit,
cannot experience it to give them faith in the Son of God.
Very unlooked for, the spring of the ministry was opened for the benefit of some present.

17th. I went to Woodbury, and was at Salem Quarterly Meeting held there.
Hinchman Haines was present, and preached.
After him,
I felt drawn to open the importance of the young and inexperienced keeping near to Truth,
and the friends of Truth; reviving the expressions in Solomon`'s songs:
"`Tell me, oh You whom my soul loves, where You feed,
and where you make Your flock to rest at noon;
for why should I be as one that turns aside by the flocks of Your companions?
If you know not, go your way by the footsteps of the flock,
and feed your kids beside the shepherd`'s tents.`"
My mind was unusually clothed with fervent desire for young and old.
That the latter might keep under right exercise of spirit,
to draw the young ones to Christ, and that these may keep near to their older Friends;
that thus they may be mutually beneficial to each other;
follow Christ in bearing his yoke, and experience the Lord`'s quickening power,
to revive his work among us.

It appeared to me there were those present who had greatly lost the dew of their youth,
and were not now sensible of the humbling power of Divine love, upon their hearts,
as they once were; and I was engaged to pray for these,
that the visitation might be renewed to them; and that He who saw the harvest was great,
and the laborers few, would, if consistent with his will,
send forth laborers into his harvest field.
In the second meeting,
I was also concerned to incite Friends to increased diligence
in attending their meetings for worship and discipline,
and to be faithful to the gift of God in their hearts therein.
Returned home in the afternoon, wrapt up in inward silence and meditation,
and though poor and unworthy, felt peaceful.

22nd. Much poverty of spirit has been my portion for days past.
Sometimes my mind has been under serious apprehension,
respecting a visit to most of the meetings of our Yearly Meeting;
and just before our Monthly Meeting,
I thought it would be proper to open it to that meeting; but it went off,
and I kept it to myself.
Like the corn of wheat, it must die out of sight, if it be brought forth into ripe fruit.
Those who run without being sent, cannot possibly profit the people.
The work is the Lord`'s. He only has the right to appoint to his servants,
their several positions; and He only can enable them to work,
and prosper it in their hands.

29th. Burlington Quarterly Meeting coming before me,
it appeared to be my place to attend it.
I believe the Lord enabled me to declare the way of life and salvation,
as it is set forth in the New Testament,
and as it is witnessed by all who follow Christ in the regeneration.
May we be preserved in a lowly, humble frame of mind;
taking the cup of suffering cheerfully, and experiencing the Lord, in his tender mercy,
to keep us alive in Him; and to make use of us to arouse transgressors,
and bring them to Christ; that we may turn many to righteousness,
and in the end be favored to hear the welcome language, "`Well done,
good and faithful servant; you have been faithful in a few things,
I will make you ruler over many things: enter into the joy of your Lord.`"
I came home in a peaceful, comfortable state of mind.

Ninth month 15th. Our Meeting for Sufferings was preserved in
much harmony in the transaction of its business.
An epistle to the Meeting for Sufferings in London, was read and adopted.
Close watchfulness against the insidious workings of a suspicious spirit,
which would alienate Friends from each other, and thereby destroy our strength,
is very needful.
Daily approaches to the throne of Grace, with desires that we may be kept humble,
and quick of discerning our own liability to get wrong,
is a very profitable and safe condition.

21st. Feeling a gentle intimation to attend Frankford Meeting, I went there this morning.
The company was small, and the Lord enabled me to hold forth a warning,
to some who had known the work of religion,
that they be not entangled with the cares and love of the world,
lest they lose their first love,
and be found not as willing to forsake all and follow the Lamb whithersoever He leads,
as they were in their first convincement.

To others who were often tried with poverty of spirit, and led to mourn over it,
the language of encouragement flowed, to keep inward;
with their spiritual eye directed to Him whom the heaven of heavens cannot contain,
waiting for his salvation.
And when He sees their faith has been sufficiently proved,
He will preach deliverance to the captive,
the opening of the prison to them that are bound.
He will give beauty for ashes, the oil of joy for mourning,
and the garment of praise for the spirit of heaviness.
Several said they were glad of the visit;
and I thought it was a season of Divine regard and condescension.

28th. I attended the Philadelphia Monthly Meeting.
In that for worship, the designs of the Almighty, respecting individuals,
and the secret workings of his power to prepare them to answer these designs,
came before me;
under which I believed it right to hold forth the language of encouragement to such,
to give up faithfully to his manifested will, and they would be led about,
and instructed, and kept as the apple of his eye.
Souls are as precious now, as in the days of our forefathers;
and as He visited them with the Day-Spring from on high,
and made many as pillars in his church, so, if yielded to,
He would make many now fit for his service,
and to become pillars in his church in their day.

Of latter time the spring of the ministry, in our meeting, as regards myself at least,
has been much shut up; so that I have mourned over myself,
and had fears whether a worldly spirit, or a stupefying lethargy,
was not spreading over us.
It seems, at times, almost impossible to get under a proper travail of spirit,
in which Divine life is felt to arise and quicken the soul;
qualifying it to bow in reverence before the Father of mercies,
and to put up prayer to Him,
in the Spirit that helps the infirmities of those who devotedly wait upon Him.
May we be enabled to keep hold of the shield of faith,
and to press onward through the difficulties that are to be contended with;
looking for the renewed manifestations of the light of the Lord, and keeping the faith,
that He will again visit his people,
and lift up their heads above the afflictions of this day of secret and sore conflict.

Tenth month 8th. This morning I had an intimation to go to Newton Meeting,
which I have had no concern to visit for a long time.
It appeared to me while sitting with them, that all the inventions of man,
out of the Truth, would fail to produce solid happiness, and a holy serenity to the soul.
Nothing could give this state of mind to any, but obedience to the will of God,
made known by the clear in-shining of the Light of Christ.
I felt a strong and affectionate solicitude for all,
that they might entirely yield to its convictions,
and be thereby brought out of darkness and cruel bondage,
into the liberty of the children of God.
A fresh qualification was administered to set before them,
many of the truths of salvation, and to labor fervently with them,
in the language of persuasion, to give up to the Lord`'s manifested will.
I came home peaceful, poor and empty.

14th. What a sweet feeling spreads over the mind,
when through the ever-watchful Shepherd,
we are enabled to maintain a steadfast guard over our spirit under provocation,
and to stifle the rising disposition to anger and resentment;
to suppress even an unkind remark; and to bear,
in the meek spirit which the Lord alone can give, whatever is calculated to irritate,
even in the small incidents of life.
"`He that rules his own spirit, is better than he that takes a city.`"
It is only through humble watchfulness, and secret breathing for preservation,
from day to day, that we gain the victory.

16th. I received a letter from a Friend in Great Britain,
giving a view of the state of the ministry among Friends there,
and the great defection from the life and power of religion among many.
It is mournful to reflect upon the state of things in this country and in England,
among the members of our religious Society.
How the will and contrivance of man, are at work, to manage its concerns, and to govern,
instead of the Head of the church.
Those who cannot act without the renewed putting forth of the Divine hand,
are borne down in some places, and obliged to submit to silent, secret suffering,
because they see no way to obtain relief.
But surely as they keep a single eye to the Lord,
in the faith and patience of the saints, He will hear their cry,
sustain them under deep affliction, for his name and cause sake, and in his time,
grant deliverance when the horse and his rider will be thrown into the sea.
And it will be found, sooner or later,
a fearful thing to have been withstanding the Lord`'s suffering children,
turning judgment backward, and exalting that which He has not ordained to be set up.

22nd. In some of our meetings for worship, of latter time,
the world seemed to absorb the minds of very many,
so that we are in danger of being left by the Head of the church;
and without his life-giving presence, what will all our assembling together avail us?
A few years ago, we had many exercised, experienced Friends,
who were thoroughly acquainted with the nature of true, spiritual worship,
and the labor that is indispensable in our meetings,
that the spirit and things of the world may be kept out,
and the bubblings up of the well of Divine life may be known in every heart.
Figuratively speaking, they dug as with their staves in their hands,
while the secret breathing of their souls was, "`Spring up, oh well, sing unto it.`"

We, who were then much their juniors, did not so much feel the weight of the exercise,
while we were favored by the Lord, and partook of the help and travail of their spirits.
I have felt engaged to invite the attention of the people to the
nature of the worship which our Lord opened to the woman of Samaria,
which is to be performed in spirit and in truth;
and which must consequently be between God, who is a Spirit, and the soul of man.
And if we are a worshipping assembly,
every one must be engaged for himself in this worship.
It does not consist in meeting together, and sitting in silence,
though these are necessary preparatives to public, spiritual worship;
but every one must wait upon the Lord, to experience Him to come into the heart,
and give ability to ask aright for living bread, and for those things we need,
in the way of Divine instruction and help;
and thereby be prepared to return thanksgiving and praise,
for his condescension and goodness.
A word of warning was also given to the young people, to keep the watch wherever they go,
that they may not lose the little strength they have gained by faithfulness;
for Satan is constantly seeking to destroy the good work.
It is a source of grief to the laborers, to behold plants dwindling,
and not bearing fruit, over whom they had watched; and whom they had secretly desired,
might become fellow-helpers in the Lord.

24th. Attended the Northern District Monthly Meeting.
Some have need to be more emptied of themselves, and of their own imaginary wisdom,
and understanding in spiritual things;
so that they might be prepared to be filled with the
Lord`'s riches and strength out of the true treasury.
In emptiness there is fulness, and in nothingness the possession of all things.
"`As poor,`" said an eminent apostle,
"`yet making many rich; as having nothing, and yet possessing all things.`"
And to his immediate disciples, our Lord said,
"`Blessed be you poor; for yours is the kingdom of God.`"
May we all be more and more willing to abide under the Lord`'s hand, in these stripping,
emptying dispensations, which He knows are necessary for us;
that we may be made and preserved vessels, sanctified and fit for the Master`'s use.

25th. We had hope, in answering the Queries in our Monthly Meeting,
that unity is not upon the decline among us,
and that the evil practice of carrying tales from house to house, in a detracting way,
does not subsist among us to any great degree;
yet were we individually kept under a right exercise of mind,
there would be more true fellowship experienced.
It was thought to be an interesting meeting.
The sentiments of several were called forth respecting the caution,
that ought to be maintained, on entering into business,
not to put at hazard the property of others.
The Truth led our fathers to labor with their own hands, in some instances,
to procure the means to purchase even the tools they needed in their business,
and to move on slowly,
that they might not enter into contracts which they could not comply with;
and thereby bring reproach on their religious profession.
If people are honest and industrious, they can obtain, without improper risks,
what is necessary for their comfortable subsistence; and they will prove,
that "`Godliness is profitable unto all things,
having promise of the life that now is, and of that which is to come.`"

29th. A silent meeting this morning.
In the afternoon some of James Nayler`'s expressions, near the close of his life,
were revived; respecting the spirit that outlives all wrath and contention;
that takes its kingdom by entreaty, and keeps it by lowliness of mind.
This is the spirit of the Lamb, who takes away the sin of the world,
and gives strength to keep the faith and patience of the saints.
He that rules his own spirit, is better than he that takes a city;
he will have peace in himself, and spread it among those who are about him.

30th. The committees appointed by the several Monthly Meetings in this city,
on the subject of reopening meetings, to be held during the approaching winter,
on the evening of first-days, met this morning,
and experienced a measure of the cementing fellowship
of the Spirit of the blessed Head of the church;
bringing us under a travail for the promotion of the cause of Truth.
Although we are clothed with weakness, a sincere desire was felt,
that the little strength we have; may be used in the Lord`'s fear and under his direction,
that we may experience an increase thereof; and the feet of inquirers after good,
may be turned into the way to Zion.
With much unanimity, we agreed to propose the holding of such meetings,
and Friends rejoiced that they were so united;
considering it as an evidence that Divine regard and kindness were still round about us.

Eleventh month 14th. Last fifth-day, the 9th, my wife and myself, went to Westfield,
New Jersey, and attended their usual mid-week meeting; in which,
after a season of silent waiting, we had some service.
On sixth-day morning, we rode over to Evesham Monthly Meeting;
in which my wife labored to draw some of those present,
off from the inordinate pursuit of the world, into a love of the kingdom of God,
and the righteousness thereof.
Attended the Monthly Meeting of Upper Evesham, on 7th day.
In this, and in that of Evesham, there was no business to claim the attention of Friends,
although the meetings are both pretty large.
We were at their first-day meeting.

In all these, the Seed seemed under oppression,
and there is not that growth in the Truth, which ought to be evident,
where so many temporal and spiritual blessings have been bestowed.
Oh, the benumbing effects of the world,
and the seemingly necessary engagements in lawful business!
Unless some calamity is brought over us,
or the Lord condescends to awaken powerfully the
stupefied and worldly-minded members of our Society,
it looks probable,
that many will be sunk into total unconcern about their soul`'s everlasting welfare,
until the last trump of God shall awaken them to
appear before the judgment seat of Christ.
Woful must then be the state of such pretenders
to belief in the doctrines of Christianity;
whose lives show that they are worshipping and serving the creatures,
instead of the Creator;
who only is blessed and worthy of all adoration and praise forevermore.
We came to Haddonfield in the afternoon, and next-day attended their Monthly Meeting.

26th. Our first-day meeting has been a season of inward exercise in silence.
There was little caught with all our toil; but we remembered Him,
who directed his disciples to give the multitude food,
because He would not send them away fasting, lest they should faint by the way;
and we trusted that He was not unmindful of our needs.

29th. I went this morning to the Western Meeting.
The work of the ministry does not feel to me to be any less fearful to engage in,
than it did in the beginning.
It is a mercy, when we are favored,
to get through with the work to which we are called in any meeting,
without saying what we should not.
The only safe ground to stand and act upon, is humble dedication to the Lord;
not seeking to be put forth in words, but waiting in the quiet habitation,
until the time comes to feel the quickening power,
and the authority or direction to stand up.
The creature and the openings made, are often baptized into death.
But if the Lord has a service for his devoted children, He will prepare,
make the way clear, and give utterance, often to their admiration, and sometimes,
humiliation.

He helped me this day to bear testimony to the
indispensable need of the inward work of religion,
which is begun and carried on in the heart by the Spirit of Christ;
and that this is a daily work, from the beginning of it in early life,
to the close of our earthly pilgrimage.
Buy the truth, by parting with all it calls for, and sell it not.
If any man barter it away, for the friendships of the world,
the last state of that man is worse than the first.
A solemnity spread over the meeting.

Twelfth month 9th. Our meeting this morning was large;
in which the doctrine of immediate Divine revelation,
as the source of a knowledge of the will of God concerning us; of the strength to do it,
and of the true understanding of the Holy Scriptures,
so that we may be really benefitted by them, was held forth;
under the fresh openings and authority of Him who gives gifts to men,
and the qualification to occupy them to his honor.
A Friend, of religious feeling, expressed his unity; there being, he said,
some things to which the doctrine particularly applied, of which I did not know.

25th. Last evening our first-day meeting was not as large as those heretofore held,
probably owing to the dampness of the weather.
Although we had ministers who were strangers, it was held in silence; under, I hope,
some travail of spirit, that the Lord would teach and feed his people Himself.
When He anoints and puts forth in the work of the ministry,
no man or woman has the right to hold back, or to hinder the work but if,
for fear of the people being scattered, or discouraged,
any undertake to prepare and offer in their own will and wisdom,
the life is burdened in the true worshippers,
and the disposition to hear words is fed and strengthened in those who have itching ears,
and whose dwelling is in the outer court.
May those upon whom the cause heavily rests, be kept in the Lord`'s hand,
watching against every device of the enemy;
who is constantly seeking to frustrate the good intended for them,
and to divide and destroy the flock.
How fearful is our situation;
and how needful is constant application to the throne of Grace and Mercy,
for Divine strength and preservation.

1849, First month 11th.
It has seemed to me that our preservation
will consist in being individually obedient in all things,
both to do and to suffer, according to the will of God concerning ourselves;
and as He manifests it to us by his Spirit in the heart.
To look to and rely upon the ever-blessed and all-powerful Head of the church,
to guide and keep us as a people, and to support his own cause Himself.
He alone can do it;
and we have need to be upon our guard that we do
not attempt to take the work into our hands;
thinking that we see exactly how the Society should be delivered out of its difficulties,
and the cause of Christ be carried over all opposition.

I believe it is also very necessary to cherish
feelings of tenderness and much forbearance,
for those who do not see eye to eye with ourselves;
that as we look for mercy at the hand of our Heavenly Father,
we may be careful not to indulge in a spirit of enmity towards them;
but endeavor to bear each other`'s burdens, that we may fulfill the law of Christ;
which is a law of compassion and love.
As we endeavor daily to dwell in this spirit,
there will be seasons wherein we shall be
enabled to draw very near to the throne of Grace,
and pour forth supplications for ourselves, and for the church,
that He will spare his people, and not give his heritage to reproach,
that unbelievers in his goodness and immediate power, may not rule over them.

23rd. I have passed through a state of great strippedness for several weeks past.
Such dispensations are truly humiliating; and though a great trial to endure,
bring those who dare not look for relief from any source than the Lord alone,
to bow very low, and endeavor to draw near to Him,
with their hearts panting after the living God, as the hart pants after the water brook.
How evident to them is it at such seasons, that they are nothing;
that there is no good but what comes from Christ;
no power to do good but what He inspires the soul with,
and that it is not at our will to command the seasons when they shall be dispensed.
This must be waited for in abasement and abhorrence of self;
by which we are taught that Christ alone can carry on the work in us and for us,
and qualify us when He pleases, to hand the bread that He gives, to others.

On first-day morning, the 21st, at our own meeting, for about one hour,
it seemed almost impossible to exclude thoughts on subjects,
which had nothing to do with Divine worship.
When they were cast out, they seemed almost at once to return,
though there was a struggle to overcome.
But after a time, when the Master drew near, deliverance was experienced,
and a little ability was granted, to testify experimentally,
that there is no spiritual life by which the soul is quickened and made alive unto God,
but that which comes from Christ; who is the way, the truth and the life.

At the evening meeting, my mind was introduced into much feeling with the young people,
on account of the many and various temptations to, which they are exposed;
and the sad consequences of quenching the Spirit and its convictions in their hearts.
I was led to remind them that there was no stopping-point in the two ways;
in one or other of which they must be walking; the broad road that leads to destruction,
or the narrow way that leads to everlasting life.
If we keep in the latter, it will, as the just man`'s path,
shine more and more unto the perfect day; but in the former,
we shall wander further and further from the Heavenly Father`'s house,
and grow darker and more hardened in transgression and sin.
They were warned of the inevitable danger, in this way,
of finally slighting and despising religion and serious persons,
and of falling into practices which they had never intended to adopt.
They could not decide beforehand how far they would go;
but might become familiarized with things, which at one time they would have abhorred.
After having come under Satan`'s influence,
they have no power to release themselves from his grasp:
nothing but the almighty arm of the Savior can deliver them;
and should they continue to deny and reject Him,
they would have no ground to hope for his help.
Parents were also reminded that the deviations of the children were, at times,
in part to be attributed to their lack of firmness and faithfulness.
That, like Eli, they might warn, but they had not sufficiently restrained them.
The young people were tenderly expostulated with, and affectionately entreated,
that when favored with the visitations of Divine light, showing them where they are,
and to what they are hastening, to make a stand, turn their back on the tempter,
and follow Christ; who would take them out of the broad road,
and introduce them through the strait gate into the narrow way;
where they would enjoy peace and substantial happiness; grow in grace;
and in their language and conduct, invite others to follow them as they followed Christ.
We had good reason to bless his holy name, for regarding our low estate,
and lifting up once more the light of his countenance upon us.
I hope there were impressions received, which will not be soon effaced.

24th. The wing of ancient goodness was mercifully
spread over us today in our Monthly Meeting,
both in that for worship and for discipline.
It felt to me that the Lord in mercy drew near to his suffering,
and often disconsolate children, and gave renewed evidence, that, as they were faithful,
He would not forsake them; but would turn their captivity as the streams of the south;
and by the might of his power, raise them up above their enemies.
They were encouraged to keep to their exercises,
and they would be strengthened and bound together;
every one having his station allotted him by the Captain of salvation.
It was the time for answering all the Queries,
and the meeting was preserved under a very solid and gathered feeling; and, I trust,
some experienced it to be good for them to be there.
Robert Scotton was with us, and had a word of encouragement for us in the first meeting;
also our beloved friend Margaret Hutchinson,
who feelingly exhorted us to be faithful unto death,
and the Lord would give us a crown of life.

29th. To two young Friends who called at our house, I felt drawn, in tender affection,
to hold up the great importance of being brought into and walking in that path,
which the vulture`'s eye has not seen, nor the lion`'s whelp trodden therein;
neither shall any ravenous beast go up thereon;
it shall be called a way--a way of holiness,
and the ransomed and redeemed shall walk therein; and as they are faithful to Him,
who casts up and leads into this way, they shall come to Zion, with songs,
and everlasting joy shall be upon their heads.
They were invited to be obedient to Him who anoints the spiritual eye to see this path,
that they might experience Him to take up his abode with them,
and to join Himself to them in a perpetual
covenant that would never be broken on his part,
while they kept faithful to their Lord and Master.
May they be brought into this covenant, and be made preachers of righteousness,
in the midst of a crooked and perverse generation.

Second month 3rd. Our Select Quarterly Meeting was a time of inward affliction.
Oh! that self may be made of no reputation;
and that a fervent travail of soul may be maintained before the Lord,
that everything that would wound the hidden life, and mar the unity which should prevail,
may be kept out of our hearts.
There are seasons in which we feel peculiarly left to ourselves,
no doubt for the trial of our faith, and to make us sensible of our nothingness;
and if we rightly endure these dispensations, they will prepare us,
like vessels emptied and cleansed,
to be again filled with riches from the Lord`'s storehouse.

5th. Our Quarterly Meeting for business was rather a favored time;
I think there was an exercise in the second meeting for the welfare of the members,
and that the authority of Christ was measurably maintained.

11th. This has been a day of deep, inward conflict, without being able to attain much,
to comfort the tossed mind.
If in our religious meetings we are not unitedly engaged to
labor for the meat that endures unto everlasting life,
the spirit of antichrist will have the ascendency in many,
who will be far from performing that worship which is in spirit and in truth.
Individual travail of soul is indispensable to the life of a meeting,
and to the preservation of the members as branches of the true Vine.
Although man, by his own efforts merely, cannot keep himself under this exercise,
yet he is bound to seek for Divine help,
to enable him to wait upon the Lord for the appearance of his life-giving presence,
and to believe that it is indispensable to his life and growth in the Truth.
When we are permitted to toil all night, and to feel, at last,
as if we had taken nothing, and fears assail us,
whether we shall not be altogether left by the Master,
it is a favor to remember that there is a portion of
suffering to be filled up for the body`'s sake:
and if in this way, we are participating in it, to a small degree, it is enough;
that in this travail of spirit, we may be made ministers of life to other seeking ones.

28th. The great contrast between the legal and gospel dispensations, was a little opened.
One says, "`An eye for an eye, and a tooth for a tooth.`"
The other, "`Love your enemies; bless them that curse you; do good to them that hate you,
and pray for them that despitefully use you and persecute you.`"
If in time of peace, we are seeking to lay waste our friends,
how are we to love enemies in time of war?
The whisperer, who is going about like an insidious serpent, will separate very friends.
Where any are thus seeking, without any foundation,
to whisper something against a friend, to destroy his standing and usefulness,
how can they love enemies, and bless them that curse them,
or do good to them that hate them?
Where the gospel and its nature are brought into the heart,
our Lord will enable his children to follow his example, in doing good,
and when any are seeking to injure us, to say in sincerity,
"`Father, forgive them; they know not what they do.`"
It is only as this spirit is lived in,
that we can experience the love of God to flow in our souls;
and as it prevails and sweetens our hearts,
the true love for the brethren and the precious fellowship
which has often subsisted in our religious Society,
will be restored; the bones that have been broken will rejoice.

Third month 28th. B. H. and J. S. of Ohio, were at our Monthly Meeting today.
Friends were comforted by their company, and B. H.`'s services.
We have had silent meetings for several weeks.
This morning the spring of the ministry, was a little opened in some others also,
and warning was sounded in the ears of those who
are putting their trust in outward things,
and turning the back upon the clear manifestations of the Holy Spirit in their own souls.

Fourth month 1st. Pretty soon after rising this morning,
I felt a pointing to go to the Arch Street Meeting, being first-day;
where I think I have not been, on that day of the week, for several years.
Before I left my chamber,
the declaration recorded in the Psalms was brought very livingly to my remembrance:
"`Ask of me and I shall give you the heathen for your inheritance,
and the uttermost parts of the earth for your possession.
You shall break them with a rod of iron;
you shall dash them in pieces like a potter`'s vessel.`"
It appeared clear to me, that the Almighty Father would, in his time,
give to his beloved Son, the kingdoms of this world, and Satan would be put under foot;
and a cloud of discouragement was in some degree dispersed.
At the meeting, I was led to speak of the doctrine and duty of inward, reverent,
silent waiting before the Lord,
as of essential importance to the growth of the true believer.
That no man can be a true follower of Christ without it;
for if he be one of his disciples, he will feel bound, day by day, and oftener,
to wait upon the Lord for the renewal of his strength.
It was practiced by the holy ancients; who sat upon their watch-tower,
and waited to see what the Lord would say unto them,
and what they should answer when they were reproved.

In this humble, reverent frame, He often condescends to show us our weakness,
or something wherein we are not coming up to the pattern of perfection,
which our Lord set before us.
Friends were invited into this state;
wherein they would be raised above the wrath of their enemies,
and be enabled to condemn every tongue that rises up in judgment with them.
