== Chapter XXII

[.chapter-synopsis]
* 1849+++.+++ Philadelphia Yearly Meeting
* Causes of Discouragement
* Visit at the Seashore, and Reflections on the Dangers attending Visits at such places
* Visits to different Meetings
* Death of Sarah Emlen
* State of our Religious Society
* Margaret Hutchinson
* Visit to Muncy.

1849, Fourth month 14th. Our Yearly Meeting of Ministers and Elders was held this morning.
Several strangers attended, but said little.
After the answers to the Queries on the ministry were read,
it came weightily and very unexpectedly upon me,
that the ministry of the gospel of Jesus Christ was one
of the most important services we could be engaged in:
that one of his ancient apostles speaking of his ministry, said,
"`I neither received it of man, neither was I taught it,
but by the revelation of Jesus Christ;`" and that this remained to be
the only source and authority of all true gospel ministry,
down to this day.
However unlooked for the motion was, I felt constrained to rise,
and as I might be enabled, to speak upon this weighty subject.
It came before me, also, that nothing in the form of a religious duty,
could be of much more prejudice to the church, than a ministry of mere words,
without the putting forth of the Head of the church.
That persons who had once received the gift from Him who ascended up on high;
and in the beginning, had exercised it in the life and power of Christ,
might gradually fall into a habit of uttering words,
that were not a savor of life to the living;
and some who never had been entrusted with a gift,
might undertake to officiate in this way.
Such a ministry seems as if it would strike down to the ground the living members,
and clothe them with mourning; instead of comforting and strengthening them.
Some of us had lived long enough, to remember many living and deeply baptized ministers,
who knew what it was to go down into suffering with their Lord,
and to remain there his appointed time; until they knew Him,
who is the resurrection and the life,
to quicken and enable them to bring up stones of memorial.
These were a comfort to the church,
and the living gathered as round about them in spirit,
supporting their hands in the work; and thus all were strengthened together.
But what a change has taken place among this people.
The importance of having discerning elders,
who can distinguish between the true and the false;
and under the influence and authority of the spirit of sound judgment,
are led to give the living child to the right mother, was also spoken to.

Where such go to a brother, in the meekness of wisdom, and the gentleness of Christ,
and under a right exercise for his preservation, unburden their minds,
when they feel that a minister is losing in life and power, it is a great favor to such;
for which, if they are in a proper spirit, they will feel thankful.
It is also important that true elders be faithful in opening to those who,
having received no gift in the ministry, mistake their services in the church,
and burden Friends with their communications;
not only that such may be prevented from bringing the ministry into disrepute,
but that they may be turned into the channel of service which the Lord designs them for.
Our friend Samuel Bettle, Sr., said,
that the care of elders and the proper hearing of them by ministers,
was a practice that the Society had always observed;
and that it was in this way the different members of the church edified one another.
Several other Friends expressed their unity with what was delivered,
and the authority of Truth prevailed in good measure over the meeting.

On the 16th, the Yearly Meeting for the general affairs of the church began,
and continued until the close of the 20th. The business was conducted with harmony,
excepting the discussion which arose on a report prepared by the Meeting for Sufferings,
on the division that had taken place in New England Yearly Meeting,
which was objected to by some of the members.
But the more solid and experienced part of the meeting, united with it;
and it was finally concluded to adopt it, and to furnish each body,
in that Yearly Meeting, with a copy.
Many Friends thought that the meeting was much favored with the
overshadowing of the good presence of the Head of the church.
When a proposition from New York Yearly Meeting,
to hold a conference of "`representatives of the Society,`" came up for consideration,
the meeting decided with great quietness,
that the way did not open to join in with the measure.
Nothing authorizes a man to speak to the weighty matters of the church,
but the putting forth of the blessed Head of the church.
There must be a proper exercise to prepare to speak in
the humble spirit and authority of Truth.
If this ground is not kept,
our religious meetings will become mere debating associations; and learning,
wit and worldly influence will finally govern and decide;
and thus the character of a church of Christ will be lost.
We shall not be of his sheep, who know his voice, and follow Him,
and who refuse to follow the voice of a stranger,
because they know not the voice of strangers.

Fifth month 6th. May the Lord never forsake us as a people, but if needful,
by the revelation of his righteous judgments, bring us down,
make us and keep us his humble, devoted followers; that we may be under his government,
and made use of by Him, to spread his blessed and glorious kingdom in the earth.

20th. Our meetings for worship have often been laborious;
in silent waiting and struggling to keep the mind from wandering.
Yet at seasons, a little hope and consolation, as from the nether springs,
have been secretly furnished; and sometimes through the ministry.
In the morning, being first-day, I was constrained to testify,
that where the eye was kept single to Christ, the whole body would, at times,
be full of light.
This could only be known as we are obedient to whatever He requires.

Light, and love to God, are increased by faithfully following Christ;
until it becomes easy to do his will; which is then our meat and drink.
Satan stands at our right hand, to tempt and to destroy;
but these humble followers of the Lamb, are immediately warned against his temptations;
and if their eye is single to Christ, and they resist the devil, he flees from them;
and thus they obtain the victory.

Sixth month 10th. This has been a day of discouragement;
little being obtained that gave direct evidence of Divine approbation and regard;
and there are now very few who can speak a word of comfort to those that are weary.
Such dispensations administer the sentence of death, not to trust in ourselves,
or in others; but teach us to look to and wait for his appearance, who raises the dead.
I read several letters contained in a collection of Sarah Lynes Grubb`'s,
lately published in England.

They show the workings of a spirit that is drawing Friends from the inward,
spiritual experience of the religion of the Lord Jesus,
and transferring the thoughts to that which He did for us, without us,
and to a literal study and knowledge of the Holy Scriptures.
We have always believed in the truth and Divine authority of the Scriptures,
and that no doctrine or practice, which is incompatible with them, is to be received:
that it is through the sacrifice of Christ on Calvary,
pardon and reconciliation are obtained, and the gift of the Holy Spirit procured;
yet all will avail comparatively little,
unless we cooperate with his Spirit in our hearts;
experiencing Him to prepare them by his baptism of the Holy Ghost and fire,
to be tabernacles, sanctified for Him to dwell in.
Thus only can we know Him to be in us,
"`The hope of glory,`" the Author and finisher of our faith, and of every good thought,
word and work, that is brought forth in us.

15th. We had a large Meeting for Sufferings,
in which the business that claimed our attention, was conducted with much satisfaction.
The consideration of slavery, and the African slave trade,
afresh impressed the minds of Friends, with a sense of the cruelties,
and great violation of the spirit of Christianity,
and of the unquestionable rights of men,
attending this horrible and most iniquitous system;
and the committee having these subjects in charge,
were encouraged to renew the consideration whether there is
any step that could be now advantageously taken,
to support and spread our testimony against these great evils.

Seventh month 4th. The Asiatic cholera has been in our city about two weeks.
Some appear to feel alarm, and fear it may spread; but it has visited so many places,
in the villages particularly along or near water courses,
that but few comparatively are leaving the city on account of it.
The instances of persons dying with but few hours illness,
and of course with little warning, are indeed fearful, and, at times,
bring sensations of awfulness over the mind.

I have found it my place, very much, of latter times, to keep silence in our meetings;
but this morning, the impulse was felt to invite the members to closer watchfulness,
that they might escape the temptations of the enemy; and not only on that account,
but also because the pestilence that walks in darkness, was abroad in the world,
and none knew what a day or an hour might bring forth.
If all were engaged to prepare a habitation for the mighty God of Jacob to dwell in,
we should be prepared to meet whatever trials might be permitted to overtake us.

8th. The lack of that unity, by which the exercised members are made a strength,
and an encouragement to one another, has been much felt.
The Society is now suffering great loss from this cause;
and until the unity of the Spirit, which it has known in time past, is restored,
weakness will be our lot.
The various members of the body are designed to be helpful to each other;
but if they are disjointed, there will be much suffering,
and the work which the church is called to perform, will be impeded.

What inconceivable injury is inflicted,
by influential persons getting out of their places,
and undertaking to do what the Head never directed them to do.
We cannot restore the precious harmony as soon as we may see the need of it.
The Lord alone can do it, and we must wait upon Him,
and bear the suffering which is our lot, until in mercy, He again arises,
and commands deliverance for Jacob, his suffering, travailing seed.

10th. My brother Thomas having gone to Cape Island, on account of his infirm health,
and it being necessary that one of his brothers should be with him,
I came down this morning.

12th. Living with a class of people,
whose habits and opinions are very different from those of Friends, is trying.
There being nothing like seriousness among most of them,
we seem to be in each other`'s way.
Unless Friends keep steadily upon their watch in such places,
they are in danger of being leavened with the spirit such persons live in,
and gradually falling into their manners,
and imitating their changeable fashions in dress.
The amusements which are prepared for the light spirits here,
are a strong temptation to young people; especially,
when they are not watched over by consistent parents,
under a proper religious concern themselves,
and who would restrain them from resorting to such entertainments.
It seems as if some felt themselves freed from proper restraint,
and at liberty to indulge in frivolity.
In this way they crucify to themselves the Son of God afresh,
and put Him to an open shame.
Such are evil examples to others.
The kingdom of Satan is gaining ground in this land,
and if those who consider themselves lovers of religion, slacken their watchfulness,
and their resistance to wrong things,
the tide of corruption must gain a powerful ascendency
over the morals of the people at large.
I consider it dangerous for religious people, to be long mingled with irreligious,
or light persons, on terms of courtesy and familiarity.
They are in danger of being leavened with their spirit, of losing their strength,
and then falling in with something that will grieve the Holy Spirit,
and wound their own souls; and when once wounded, they may never recover,
but go halting all their days.
Very many are ashamed of the simplicity of the cross.
Some who may be pretty stayed among their friends at home,
and yet not very firm against the current of fashion, and libertinism,
may be thus drawn into it; and at such places,
lay aside the Quaker character and manners, almost altogether;
thereby bringing reproach upon the name and cause of Christ.

Those who are enemies to religion, and ready to disseminate their poisonous opinions,
are often found in these places of public resort; where they put on great politeness,
and blandness of manner,
to insinuate themselves more effectually into the esteem of strangers.
They often carry an exterior of great kindness,
and interest in the accommodation of others; by which,
unwary young people may be attracted to them, and led to think,
that where such apparently disinterested good-will exists,
the principles cannot be dangerous.
To send young people where they will mingle with such,
exposes them to receive a hurtful bias, which it may be extremely difficult to eradicate,
and which may be used by Satan to destroy their faith in the christian religion,
or hinder them from giving up to walk in the path of self-denial.
We cannot expect, while in this world,
to avoid all interaction with men who have little or no religious scruples;
but the less of it, the better.
Many parents who have permitted their children
to associate with the gay and the frivolous,
have finally found their sons and daughters had a total
disrelish for plain and unfashionable company.
The gay world, which lies in wickedness, has stolen away their hearts from their Savior;
they become dissatisfied with that which is serious, and restrictive,
and are soon prepared to leave the Society, of which they were birthright members,
to become votaries of the world.

17th. I have passed some of the time here in
reading the letters of that extraordinary woman,
the late Sarah Lynes Grubb.
She was an instrument peculiarly prepared by the Lord Almighty,
to uphold and to spread the doctrines and testimonies of the christian religion,
as promulgated by George Fox, R. Barclay, and other Friends,
in the rise of our religious Society.
The reliance of some, among Friends, upon human talents, without waiting upon the Lord,
to receive from Him ability and authority for every good word and work,
occasioned her much suffering and anxiety; especially,
in relation to its effect on the true welfare of the Society,
and the blessed cause given it to uphold.
In this exercise, she appears to have labored much alone for several years;
but when called upon to advocate the cause of her Divine Master,
she was plain and thorough in her testimony; especially,
against all the efforts used by some to change the faith of Friends;
often expressing the belief, that such would, in time, be scattered;
and that a righteous seed would be preserved, that shall again flourish.

18th. Another brother coming down to stay with Thomas, I returned home.

22nd. The cholera has been in our city several weeks,
twelve to thirty dying daily with the fearful disease.

26th. In the night season, I lay sometime awake, under mournful feelings;
death being abroad, summoning many to their everlasting home.
But as I looked towards the Lord Almighty, in his holy temple,
endeavoring to rely upon Him, the language was sweetly revived:
They that trust in the Lord, shall not be confounded, but they shall be as Mount Zion,
that cannot be removed;
and ability was mercifully granted to put my trust in my blessed Heavenly Father,
and safely to repose upon his goodness, and unfailing compassionate regard towards me,
a poor unworthy creature.

31st. I received information of the decease of Sarah Emlen.
This dear Friend was an acceptable minister,
and had been much dedicated to the Lord`'s service.
She, and her ministerial labors, will doubtless be much missed in the church.
The removal of faithful laborers at this day of close conflict and proving,
adds to the mournful feelings with which many are now clothed;
but it is no time to cast away our confidence in Boundless Mercy and compassion.
The Lord`'s arm is not shortened, nor his ear grown heavy;
but I believe we may safely conclude, that after purging and humbling his people,
He will arise in his might, dissipate the clouds,
and again give precious gifts to sons and daughters.

Eighth month 6th. Mary Carpenter, a member of Philadelphia Monthly Meeting,
having deceased, I felt my mind drawn in sympathy to go to the house,
and sit with the connections and friends.
The expression,
"`Precious in the sight of the Lord is the death of his saints,`" came before me;
and under the constraining influence of Heavenly Love, I was led to testify,
that it was a blessed gathering of the sanctified in Christ Jesus,
to their everlasting mansion among the saints in light; and to declare my belief,
that if those who are left in this state of probation,
follow them as they followed Christ, walking by the same rule and minding the same thing,
they will be also prepared by the Holy Spirit, to receive precious gifts;
and the doctrines and testimonies of the gospel given Friends to support,
will not be permitted to fall to the ground in this city.
It was a tendering, comforting opportunity, that ended in peace.

Our Quarterly Meeting, which met this day, was held in solemn silence;
which led me to think,
that while we can hold our religious meetings under such solemnity,
we are not deserted by the Gracious Head of the Church.
May we be preserved in reverent, humble waiting before Him,
and with loins girded and lights burning, do his blessed will on all occasions.
A concern for the welfare of members of the meeting on the other side of the mountains,
spread over us, and a few Friends were separated to make them a visit,
in the love of the gospel, for their strength and encouragement.

15th. Went with my dear wife to Salem Select Quarterly Meeting, held at Woodbury;
which is in a very reduced state.
Several of the members were absent today, occasioned by the death of Mary Shepard,
of Greenwich, who had been but a few years acknowledged as a minister,
and was well esteemed by those who were acquainted with her, in the exercise of her gift.
Our condition as a religious body calls for deep indwelling with the Master,
and serious enquiry what He would have every one to do;
that each may know the work of salvation to be going on with the day,
and receive ability to build up the waste places.

16th. In the forepart of the Quarterly Meeting, our beloved friend Sarah Hillman,
was engaged in acceptable testimony to the unfailing
goodness of our Heavenly Father towards his children,
even when their faith may seem ready to fail.
He changes not.
It was reviving and strengthening to the tribulated followers of Christ.
Although I felt low, yet after a time of waiting,
I was constrained to arise with the query, "`When the Son of man comes,
shall he find faith on the earth?`"
When He comes into the hearts of many who profess his holy religion,
will He find that living faith, which is the saints`' victory over the world,
the flesh and the devil?
A mere belief in the doctrines of the New Testament,
without obedience to the inwardly revealed will of God, will avail but little.
There is a faith that overcomes the world,
and there is a faith that is overcome by the world.
Many who have a plain outside, are seeking to become rich,
and straining all their powers to accumulate wealth, that they may be great in the world,
and receive honor from men;
but these are stumbling blocks in the way of serious enquirers after the Truth;
and they are burdens to the living members of the Church of Christ.

Even worldly people can often discover where the substance and life are lacking;
and such bring our religious profession into disrepute.
They were solemnly called upon to renounce the world,
and make ready for the period when the cry will be sounded in their ear,
"`Behold the Bridegroom comes, go out to meet him.`"
The gospel was preached to the poor,
and the dear young people called upon to yield to the visitations of Divine love,
and give up their hearts wholly to the government of their Savior.

Ninth month 30th. This has been a day of serious
thoughtfulness upon the state of our Society;
so great change has taken place in the number of aged, experienced members,
through removal by death.
The unsettlement produced by the promulgation of unsound principles,
has prevented growth in the Truth in many,
and it seems as if the labor which has been bestowed,
has done little more than contribute to keep some young
plants from entirely dwindling and falling away.
Comparatively few show themselves on the Lord`'s side,
by taking an active part in the affairs of the church, under his constraining power;
and this makes heavy work for those who are bound to the law of their God,
and his testimony to the life and spirituality of the gospel dispensation.
The unity and true fellowship which pertain to membership in the body
of Christ do not subsist among Friends as they once did.
It seems as if nothing but dying daily,
and waiting in resignation of soul before the Lord, for him to arise,
and work by his mighty power, can do away the divided feelings.
We cannot remove them ourselves; and some must be given up to reproach,
who may be employed as between the living and the dead, for staying the plague.
If the love of Christ did really abound in us;
that love in which He laid down his precious life for the salvation of souls,
we should be willing to enter into suffering and sympathy one with another;
and there would be no disposition to listen to, nor to spread reports,
unfavorable to those who are standing for the faith of the gospel.

That true heavenly love would lead us to pray for each other;
to keep close in spirit to the servants of the same Lord; holding up their hands,
and encouraging them in the work whereunto He has appointed them.
Hereby Satan would be disappointed in his efforts to destroy the flock;
and Friends being banded together in a united
and living travail for the prosperity of Zion,
every member keeping his and her place in the body,
the Lord would not only bless the provision of Zion, and satisfy her poor with bread,
but his work would prosper in our hands,
and sons and daughters would be brought from the east and the
west to sit down in the kingdom of the dear Son of God;
and thereby the enlargement of our borders would take place;
by which the burden-bearers and standard-bearers would be increased.

The removal of our aged and beloved friend, Margaret Hutchinson,
who has long stood as a lively, acceptable minister in our meeting,
has left a blank at the head of it, which is sensibly felt.
Her communications were mostly short, uttered with fear and trembling;
but raising the life among us.
Her appearances in supplication were much of the same character; solemn and impressive;
proceeding from the constraining power of Christ,
and under reverence and awfulness in approaching the Divine Majesty of heaven and earth.
How fathers and mothers in the unchangeable Truth have
been taken from us in the last forty years!
How soon the same merciful and long-suffering Head may see fit to supply their places,
we cannot foresee.
None can do it but Himself, by his wonder-working power.
But it is our duty to wait upon Him in faith, and when qualified therefor,
put up our prayers that He will restore judges as at the first,
and counsellors as at the beginning.

Tenth month 1st. This afternoon I attended the burial of Wm. Cooper,
from his late residence, near Camden, N. J. After some time of silence,
I felt engaged to preach the doctrine of life
and salvation through our Lord Jesus Christ;
both as he is a Mediator, glorified at the right hand of the Father,
with the glory which he had with him before the world was,
and as he is appearing by his Spirit in the hearts of all mankind;
to give every one a sense of his fallen state,
while living according to the lusts and appetites of the carnal mind;
and inciting them to repentance and the forsaking of sin.
To those who receive Him, he will give power to become the sons of God;
their sins being forgiven and washed away,
for the sake of that most satisfactory sacrifice, which he offered of Himself,
without the gates Jerusalem.
As they follow him faithfully, bearing the daily cross, and despising the shame,
they will be made partakers of the Divine nature; putting on the Lord Jesus Christ,
and no longer making provision for the lusts of the flesh;
and having confessed Him before men, they will be accepted in Him the Beloved,
and acknowledged by Him in the presence of his Father and the holy angels.

12th. Our Quarterly Meeting having appointed a committee to visit Muncy Monthly Meeting,
and its branches, four of them left Philadelphia in the cars for Pottsville,
near the head of the Schuylkill River, about ninety-one miles from the city,
which we reached about one o`'clock; dined there, and took stage for Danville,
on the north branch of the Susquehanna, about thirty-six miles from this place.
The road crosses several mountainous ridges, very much through a coal and woody country,
from the mines in which, thousand of tons of the former,
are sent annually to Philadelphia.
We got into Danville about twelve o`'clock at night, and being fatigued,
we soon retired to bed.

13th. Rose refreshed, and after breakfasting and walking in the town, we set out,
with carriage and horses, procured here for our accommodation, and rode to Greenwood,
where we put up at our friend D. M.`'s. The weather was fine, and the road good,
and we were kindly received and entertained.

14th. First-day.
Some notice having been spread, a pretty large company,
composed of the few Friends belonging to the meeting, and their neighbors, assembled;
and although it did not feel to me to be a very quickening time,
yet through Divine kindness,
ability was received to preach Christ crucified without the gates of Jerusalem,
as the way to the Father; the only name under heaven, given among men,
whereby we must be saved, now glorified with the Father, and appearing by his light,
grace or good spirit, in the heart, to destroy the works of Satan in man,
and to bring in everlasting righteousness in place thereof.
The meeting was solid, and I hope good impressions were made.

In the afternoon we had a pleasant ride over the Muncy hills, the road being very good;
and near dusk got to the residence of J. Haines,
where we met with a hospitable reception.
I had occasional conversation with Jesse Haines, his father, a minister,
now in his ninety-fourth year; whose faculties appear to be strong,
and his religious sensibility quick and clear.

16th. In the morning, while sitting by Jesse Haines,
he remarked that he expected we had been sent here by a
higher power than the Quarterly Meeting,
and my desire is, he said, that the people may receive the engrafted word.
I replied, our desire was that the quickening power might be renewedly felt,
and something known of being raised into newness of life.
We set out pretty early for Elklands;
some part of the mountain road was rough and fatiguing,
but we reached the settlement before it was quite dusk,
and were made welcome at J. McCarty`'s, by several of his children, who reside with him.

17th. Rode five miles to their Preparative Meeting.
The weather was wet; and the stirrings of Divine life were low.
Feeling the spirit of supplication, petitions were vocally put up to the Lord our God,
that in mercy and compassion, He would regard the conditions of all present.
There appeared to be some concerned Friends among them, and we had hope,
they would be more fully awakened to a sense of the necessity of
being withdrawn from the improper pursuit of the things of time,
and cherish a more fervent concern for the prosperity of truth,
than it is to be feared most are now sensible of.

18th. Before leaving the next morning,
we had a religious opportunity with the Friends where we stayed.
In the evening, being at the house of Jesse McCarty, we had a meeting with some Friends,
in which the advantage and duty of waiting upon the Lord, were in some measure set forth;
and those present were warned against being
swallowed up with the pursuit of lawful things;
and encouraged to devote themselves to the Lord`'s service,
out of meetings as well as in them.
Were this their labor and experience,
there are some among them who would become lights in that place,
and helpers in the church of Christ.
The importance of rightly maintaining the discipline,
under the guidance of the Holy Spirit, was also laid before them.

19th. We rode back to Muncy,
and were thankful to be again landed among our friends there, in safety.
Visited several families of Friends, in two of which, we had religious opportunities,
laboring to arouse them from their lukewarmness,
and pressing upon them the necessity of knowing the work of salvation to be accomplished,
while the day of mercy lasts.

21st. Attended the first-day meeting.
I felt drawn to hold forth a word of encouragement,
to those who were honestly endeavoring to stand for the Truth.
Also to show to others, that if any man be in Christ, he is a new creature;
old things are passed away, and all things become new, and all things of God.
That however valuable a belief of the truths of the gospel undoubtedly is,
it will not be sufficient, where it is only literal or educational.
We must know the new creation; the heart sanctified,
so as to be prepared as a temple for the Lord to dwell in.
He will not dwell in a defiled heart.
I felt his humbling power, softening my heart towards the people,
especially the younger part of the company; and under its heavenly influence,
the spring of the gospel was opened, and the Lord gave the word for the different states;
some of which, I believed, were tenderly reached;
and we had cause to return thanks to Him for his renewed aid, and Divine presence.
In the afternoon, we rode to Greenwood, the weather being wet;
it became dark before we reached the house of our friends D. M. and wife,
by whom we were kindly received.

22nd. In the Preparative Meeting, adjourned to this day at our request,
a qualification was again furnished to preach the gospel;
holding forth the doctrine of Christ, to place the kingdom of heaven,
and the righteousness thereof, above all other pursuits in this world.
After dining, we called upon several families,
in most of which we were engaged to labor for their encouragement,
and faithfulness to their religious duties.
True zeal is greatly lacking, and the number of Friends is now small.

23rd. Returned to Muncy this morning.
Their Select Preparative Meeting being held this afternoon, we attended it.

24th. We were at Muncy Monthly Meeting this morning.

We sat a long time in silence.
Though clothed with fear of speaking without it was required,
I also felt afraid to omit what was my duty to do.
In this state, the language of our blessed Redeemer, "`Whosoever will be great among you,
let him be your minister; and whosoever will be chief among you,
let him be your servant,`" was brought before me; accompanied with the belief,
that some had need of being humbled and reduced,
to prepare them for his government and kingdom,
and to be made use of by Him in his household.
And Jesus called a little child unto him, and set him in the midst of them, and said,
"`Verily I say unto you, except you be converted, and become as little children,
you shall not enter into the kingdom of heaven.`"
The indispensable need of self-reduction,
and laying aside all reliance on our own wisdom and strength,
that we may be fitted for membership in the church of Christ, was held forth among them.
// lint-disable person-mismatch "you seems"
"`If any man among you seems to be wise in this world,
let him become a fool that he may be wise.`"
We cannot enter the sheepfold but by Christ, the door; nor into the narrow way,
but through the strait gate; and those who thus enter, will be prepared,
as they keep obedient to Him, to receive gifts,
and to know their services appointed to them, by the Great Head of the church.
I believe He was with us and carried home to some,
the important truths declared among them.

In the Monthly Meeting, the minute of the Quarterly Meeting, appointing the committee,
was recorded; and it was a satisfaction to the committee,
to feel that their efforts among them, were well received;
and we hoped the bond of christian love and fellowship, was a little strengthened.

After dining, we set out for Danville, which we reached about eight o`'clock; the road,
though part of it mountainous, was generally good,
and the evening was clear and moonlight.
Lodged there, and early the following morning, took stage for Pottsville;
arrived there before two, and before seven o`'clock in the evening,
were landed at our beloved homes, a distance of one hundred and fifty miles from Muncy.

Poverty of spirit, and the absence of all ability to do anything in the Lord`'s work,
has been my clothing for days, since our return;
all in mercy and great condescensions from Him who alone can strip,
and humble man into the dust; that no flesh may attempt to glory in his presence.

30th. I accompanied my beloved wife to Frankford Monthly Meeting,
before which she laid a concern to visit their families,
and received the cordial unity of the meeting with her prospect.

In the first meeting we were both strengthened to declare the gospel.
That there is no new doctrine to preach;
no new way found out to the everlasting kingdom of rest and peace;
but that Christ is the way, the truth, and the life, and it is through obedience to Him,
under the daily cross, that He brings any to the Father.
The dear young people were affectionately warned against disobedience,
and pleaded with to yield to the visitations of Divine love.
Friends were kind and loving, and we returned home in peace.

Eleventh month 3rd. Was our Select Quarterly Meeting,
from which several members were absent.

5th. We had a very large Quarterly Meeting for worship.
It was quiet and held under a degree of solemnity.
This was the case with the Meeting for Discipline also.
When the Queries were gone through,
I felt constrained to encourage Friends to keep to all our religious meetings;
also to warn some against supporting any cause that is adverse to the cause of Christ,
and which He raised Friends up to support;
or to attempt to support his cause in an unchristian spirit; either of which,
will create disunity.
The time is coming when all will he judged,
and no party combination can come between such, and Him who searches the heart,
and shows unto man what his thoughts are;
and will reward every man according to his deeds.

11th. Some temporal concerns have pressed upon me pretty heavily for several days;
in which the heavens also seemed wrapped in darkness, and faith,
to enable me to look to and trust in the Preserver of men, reduced low.
In the forepart of our meeting, this morning,
it was difficult to withdraw the mind from those distracting, worldly things,
which brought me under distress.
Our friend Robert Scotton was opened, in a lively manner,
upon the states of outside professors,
who were striving to satisfy themselves with their own doings,
while the precious seed of the kingdom was oppressed,
and choked by the love and pursuit of worldly gratifications;
and in the midst of which they were ignorant of the
resurrection of the life and power of godliness into dominion.
He also ministered to those who were suffering with this oppressed seed,
and encouraged them to faithful endurance,
though the Lord might try them long with hiding his face from them;
but as they kept patient under his dispensation, He would cause the clouds to disperse,
and again appear for their comfort.
The Lord`'s humbling hand was laid upon me, constraining me to bow before Him,
and publicly petition that in his unutterable and unmerited mercy,
He would continue to be round about his children, older and younger,
and defend them from the jaws of the devourer.
You know all the trials of those, who are travailing for the arising of the seed of life;
be with them, we humbly pray you, and string their bow in the day of battle;
and with your ministers; Oh! be unto them, mouth and wisdom, tongue and utterance.

Watch over, we beseech you, the dear children,
when out from under the eye of their parents and friends,
and keep them from doing anything that will grieve your Holy Spirit,
or bring dishonor upon themselves and your precious cause.
In this manner my spirit was poured out, in brokenness and contrition,
before the Lord and his people; which brought solemnity over the meeting; and praise,
might, majesty and dominion, were ascribed unto the Lord God, and to his dear Son,
our Lord Jesus Christ, who only are worthy.
Many were tenderly bowed under the merciful extension of Divine regard to us,
poor unworthy creatures.
The load upon me was lightened, and I went on my way rejoicing.
