== Chapter XXIII

[.chapter-synopsis]
* 1849--1850. Religious Engagements in Philadelphia
* Attendance at neighboring Meetings
* Religious Visit to the Meetings in New Jersey
* Services at and near Home
* Reflections respecting the Mexican War.

1849+++.+++ Eleventh month 13th. This day I attended the North Meeting,
and found a very large collection of Friends and
others convened on account of a marriage.
After some time of silence,
in which I believe some were brought under exercise
that the meeting might be held with solemnity,
I felt drawn to mention that marriage is a Divine ordinance; and where entered into,
in the fear of the Lord,
and the parties are concerned to do His will to the end of their days,
it conveys many blessings; not only in things of an earthly nature,
in which they are helpmeets to one another; but,
each following their Lord and Master in the work of regeneration,
they are made a strength and encouragement to each
other in the holy way to everlasting blessedness.
Many things were opened to the people;
a considerable part of whom did not appear to be Friends, and great stillness,
and I hope solemnity, prevailed.

15th. Went to the Arch Street meeting under an apprehension of religious duty.
I felt constrained to speak of the continued preservation from
the power of the tempter to lead into sin,
which is extended, in great mercy, to those who mind the Light of Christ,
in its convictions and leadings in the heart.

Those who are the Lord`'s workmanship, created anew in Christ Jesus,
He will not desert nor overlook, but they will be kept by Him from youth to old age;
and being faithful, will become pillars in his house that shall go no more out.
To those who are slighting the pleadings of his Spirit,
and joining the friendships and maxims of the world,
a pressing invitation was given to examine their
condition in that light which cannot deceive.
For what will all the gold they can accumulate,
avail in that day when they are summoned to appear before the judgment seat of Christ?
It cannot procure Divine approbation, or an entrance into heaven.
While such are disregarding the repeated calls to holiness,
and seeking their satisfaction elsewhere, they will become darkened,
and be deceived with false pretensions to peace.

22nd. My dear wife having been engaged about ten days
in visiting the families of Frankford Monthly Meeting,
I went to meet her at Grermantown Meeting this morning.
We were favored with the breaking of heavenly bread,
through the great condescension of the Lord; the alone Succorer and Helper of his people.

25th. During the forepart of the meeting this morning, the power of darkness,
through various insinuations of the enemy, so strove in me,
that there seemed little hope of gaining the ascendency over it;
but after a season of conflict, the Master condescended to appear, when Satan fled,
and a great change was experienced;
and ability was afforded to testify to the blessedness of waiting for,
and looking to Christ, who is over all the power of the enemy.
He it is, who will give to the thirsty, panting soul, the living water,
of which those who drink, will desire no other.

Twelfth month 10th. Several late occurrences of a distressing nature,
in which I was not concerned, have tended to produce depression;
which was increased by a remark that I made on a certain
occasion under the influence of a little excitement,
which although the motive was good, gave me no little uneasiness.

This morning the language of the Savior passed through my mind,
"`Why are you so fearful, O you of little faith?`"
I was afraid to attempt to banish fear,
lest the affliction should not have all the effect which it should produce;
but the language of the compassionate High Priest gave me comfort and hope,
that no evil resulted from my remark,
and through the day my mind has been calm and peaceful.
Oh what poor, weak creatures we are; and the Lord has his means to make us sensible of it.
These dispensations humble us, and increase our charity for others.

11th. This morning I felt an unexpected intimation to go to the North Meeting.
The striking and encouraging character given of the Savior by the prophet,
was feelingly brought before my mind, representing his gentleness and tenderness.
"`He shall not strive nor cry; neither shall any man hear His voice in the streets.
A bruised reed shall He not break, and smoking flax shall He not quench,
till He send forth judgment unto victory; and in his name shall the gentiles trust?`"
Dear E. Pitfield knelt, early in the meeting, in humble, tender supplication;
which brought a good savor over the meeting.
After some time, it seemed proper for me to revive the above passage,
and to set forth a little the great compassion of Him,
who knows our infirmities better than we know them ourselves.
The bruised heart, which feels like a reed for strength, He will not break;
but in his time will bind it up;
and though there may seem to be little of Divine life in the soul, comparable to fire,
no more than sufficient to create a smoke, yet He will not quench it,
where there is a secret prayer and desire, to be made what He would have us to be.
He will regard the cries of his tribulated seed;
and where any have transgressed his Divine law, and are brought to feel their condition,
if they abide under his judgments, He will open the prison to them that are bound,
and grant deliverance to the afflicted soul.
Friends were exhorted not to cast away their shield,
as though they had never quenched with it, the fiery darts of the wicked;
for one of the devices of the enemy, is to tempt us to despair of the Lord`'s mercy,
and of preservation to the end.

23rd. Our Meeting for Sufferings was held on the 21st;
in which there was a comfortable feeling of fellowship among
those who are travailing together for the faith of the gospel.
The business was transacted in much harmony, and I hoped the unity of the Spirit was felt.
May it increase and bind us together, that we may be of one heart and of one mind.
This afternoon in our meeting there was a comfortable hope,
that the Lord would not desert us; but if we kept steadfastly upon the watch,
the Spirit of prayer would be granted,
and in his time He would cause his light and life to break forth among us;
and seeking ones, beholding our stability in Christ, would become united to us,
as the soul of Jonathan was knit to David`'s.

I had a short testimony to the Lord`'s power,
and to the necessity of those who are seeking a people who live in the Truth,
to look within and not without them; that they may have the spiritual eye anointed,
and be made instrumental themselves in exalting the kingdom of the Savior.

26th. My wife and myself went out to Springfield
on a social visit to our brothers and sisters.
Attended their week-day meeting.
I was reminded of the language,
"`The ways of Zion mourn, so few come to her solemn feasts,`"
and mentioned it in the men`'s Preparative Meeting; expressing the hope,
that the overseers and other Friends would look into the state of the members,
whether the neglect of their religious meetings was not growing upon some,
and endeavor to stir them up to greater diligence in
performing this solemn and profitable duty.

30th. This morning, before setting out to their first-day meeting,
as we did not expect to return, my dear sister Hannah Rhoads informed us that,
for several years, she had been impressed with the belief it would, at some period,
be required of her,
to pay a religious visit to Friends in some parts of Great Britain and Ireland;
and that for the last eight months, it had rested upon her with such weight,
day and night,
she believed it would be right to lay it before their Monthly Meeting for its judgment.
We encouraged her to do so, not doubting it was a right concern; and that,
if set at liberty to prosecute it, He who put her forth,
would strengthen and qualify for the work He engaged her in.

31st. Was held Chester Monthly Meeting,
which passed a memorial of our late beloved friend Sarah Emlen.
The concern of my sister H. Rhoads, brought a weight over the meeting,
and was seriously and feelingly considered and spoken to and the calm
and serene feelings which overspread the minds of Friends,
appeared to me to be evidence that the Master owned it by the church.
After the expression of unity,
a committee was separated to prepare a certificate to be ready for next month.

1850, First month 23rd. Yesterday I attended the Northern District Monthly Meeting.
Several Friends spoke in the first meeting.
In the second,
I felt drawn to encourage Friends to stand firm
in the support of our christian testimonies,
and to come into the practical experience of
what is contained in the evangelical prediction:
"`In that day shall the Lord of hosts be for a crown of glory and for a diadem of beauty,
unto the residue of his people;
and for a spirit of judgment to Him that sits in judgment,
and for strength to them that turn the battle to the gate.`"
In Christ, who is the Head of the church,
are hid all the treasures of wisdom and knowledge; He knows every child in his family,
and as we humbly wait upon Him, He will, by the touches of his finger,
quicken us for service, and give strength and wisdom to perform it.

We had the company of several Friends at our Monthly Meeting today,
whose services were acceptable.
I thought we had good evidence that the meeting was
gathered and held under the authority of Truth,
and the business transacted in the fear of the Lord.
The tendering power of the Holy Spirit was felt, renewing our faith a little,
and leading us to trust that it might be regarded as a token of Divine kindness,
and that the blessed Head had not forsaken us.

Second month.
Our Quarterly Meeting, held on the 4th, was one of the largest I have seen in that house,
or anywhere else, and was covered with much solemnity;
a qualification being received to search into
some of the departures from our testimonies,
and to stand firmly for their importance and right support.

15th. Went down to Woodbury, on the 13th, and attended the Select Quarterly Meeting.
Our aged, exemplary and experienced friend Hinchman Haines, was also there,
and was engaged in testimony, to the tendering and comfort of my spirit.
He recited part of the conversation between our Lord and Philip, when the latter said,
"`Show us the Father and it suffices us.`"
Christ replied, "`Have I been so long time with you, and have you not known me, Philip?`"
Hinchman Haines went on to speak of his own infirmities,
and the concern he often felt, to enquire whether he was in the right path,
under which faith was proved when light was withheld;
but he believed that though the Lord hid his face from us,
and He might not see fit to appear as soon as we desired,
yet as we maintained the watch and the struggle, He would manifest Himself,
to our consolation.
This, he said, was his belief;
and his frequent desire was to know whether he was in the right path,
though he was a poor creature.

It was a comfort to hear doctrine so applicable to my condition,
and the frequent exercise of my mind, from an old disciple,
now more that four score years of age.
I hoped it was an evidence the Lord had turned my feet to this place,
to be thus ministered unto.
I was broken down into tears under it, in such manner, as is not very common for me,
and I desired to return thanks to the Lord for his mercy.

Next day we were at the meeting for business.
Though unworthy,
it appeared to be my duty to bend the knee in
vocal supplication to the Father of mercies,
that He who knew all our weaknesses and infirmities,
would look down upon us in tender compassion,
and renew that blessed faith which He gave us in the beginning of our heavenly journey;
and by his Spirit and power,
strengthen us to keep the watch and maintain the holy warfare;
so that nothing might be permitted to cause us to slide from the true foundation,
and thereby bring any reproach upon the profession we have made before many witnesses.
Also that He would lay his hand upon the children,
and draw them to take the yoke of his well-beloved Son upon them,
and follow Him in the way of his leading.
That thus a multitude might be brought to support the doctrines and
testimonies which He gave our forefathers to bear before the world;
be made instrumental in spreading his kingdom; and ascribe thanksgiving and praise,
might, majesty and dominion, to Him, the Lord God and the Lamb; to whom alone it belongs,
now and forevermore.
This afforded me some relief, and a little hope,
that Divine regard and mercy were continued.

20th. Having for some time felt a concern to pay a religious
visit to the meetings of Friends in New Jersey,
I spread the subject before the Monthly Meeting which was held
this day a minute was granted me expressive of its unity,
and encouraging me to pursue the prospect as Truth may direct.

On first-day, the 24th, I came over to my friend S. N.`'s,
who had agreed to take me to some of the meetings, and attended that at Haddonfield.
After a season of silent waiting, the expressions of the apostle came before me,
"`As it is appointed unto men once to die, but after this the judgment:
so Christ was once offered to bear the sins of many;
and unto them that look for Him shall He appear
the second time without sin unto salvation.`"
The way opened to preach Christ crucified, without the gates of Jerusalem,
as the propitiatory sacrifice for the sins of all mankind;
as our glorified Mediator and Intercessor, at the right hand of the Father;
and in his spiritual appearance in the heart, as the refiner`'s fire,
and as a fuller with soap, to purify the soul and prepare it for Him,
the Lord of life and glory, to dwell in, by his Spirit;
and having destroyed the works of the devil there,
He puts an end to sin in the sanctified believer, and in the room thereof,
brings in everlasting righteousness.

25th. We left pretty early for Burlington, and put up with our kind friend Margaret Smith.
I left home under feelings of depression,
not knowing how I should get along with my proposed visit;
but I kept it quietly to myself,
looking to and relying upon the Lord alone for help and preservation.
The Select Quarterly Meeting was passed by me in silence.
I went to the meeting next morning in a low frame of mind.
After a season of inward retirement before the Lord,
my mind became impressed with the importance of
keeping to the original ground of our profession,
and of all vital religion;
a reliance on the immediate teaching of Christ Jesus in the heart, by his Spirit.

A living gospel ministry has often been a great blessing;
but the design of it is to bring people to Him,
who alone can open to them their conditions, and give dominion over sin,
and prepare for the reception of those gifts which are to be occupied in his church.
Many eminent men and women +++[+++of this place.]
have been gathered to their everlasting reward, and the gifts which they occupied here,
have been withdrawn from the militant church.
Only as we are prepared by the cleansing power of Divine grace,
which made them what they were,
will the present members of the Society be brought into
a situation to be entrusted with spiritual gifts.
Under a view of the great falling away from the travail of soul,
and the lively zeal which have heretofore characterized faithful servants,
and qualified them to stand for the good cause,
the Lord enabled me to lay open the state of the church, and to labor with those present,
for a restoration of primitive zeal for the support of the great cause,
that He raised up our Society to uphold, and to spread in the earth.
I was humbly thankful for the Divine aid and authority vouchsafed;
and that peace and satisfaction clothed my spirit in the work.
The glory belongs to the Lord alone, who condescended to our low, unworthy states.
In the afternoon, after enjoying the company of several dear friends, we left Burlington,
with a Friend, who offered to pilot us to Barnegat,
and rode six or seven miles to our lodging-place.

27th. Our journey to this village was through a piney wilderness;
some of it mere barrens, and few dwellings on the road; the distance about forty miles.
We got to J. C.`'s, in the afternoon; and notice was spread that evening and next morning,
of a meeting to be held there.
In meeting with this family, I felt a nearness and desire for their best welfare;
situated as they are, with little opportunity for interaction with Friends,
but few of whom visit them from a religious concern.

28th. Went to a small school-house, where the Friends hold their meetings for worship;
but few people came until we had been there half an hour;
when the house was filled by the inhabitants,
who were returning from the burial of a young man who had died after a short illness.
It was some time before the company became settled, and then they sat in a proper manner.
The word of life was preached to them, and some things opened,
concerning the temptations to which man is exposed, and the means of salvation,
through our Lord Jesus Christ;
and the opportunity closed with supplication for the
people and the little remnant of Friends in this place.
We had a short, tendering opportunity with J. C.`'s family;
endeavoring to strengthen them to greater dedication; and parting affectionately,
rode to Tuckerton, twelve miles.

Third month 1st. During the night, it rained hard,
and the wind was very high in the morning, but clearing off,
a pretty large collection of persons, and some Friends, came together.

It seemed as if nearly all were carried away by a strong current,
into the spirit and fashions of the world;
so that there appeared little hope that a succession will come up among Friends.
The sensation was affecting,
in beholding plain men and women fallen into such indifference to the cause of Truth,
and the preservation of their children in plainness,
conformably with our religious testimony; and some marrying with those who are not of us.
I endeavored to discharge myself faithfully on the
pernicious effects of the love and pursuit of wealth;
absorbing the time and talents bestowed on us for nobler purposes,
and giving indulgence to the carnal propensities of old and young.

The Friends here appeared to suffer loss,
from the lack of the beneficial influences of religious society,
from which they are much separated;
and probably from the absence of faithful laborers and watchmen,
who lived formerly in these parts,
or travelled among them in the love and service of the gospel.
This class is greatly diminished, and the love of ease and the comforts of home,
may be insidiously binding to their temporal enjoyments, the small number left;
and hindering them from that devotion and zeal in the Lord`'s cause,
which our predecessors felt, and manifested by their fervent, painful labors.
We dined with an elder, few of whose children looked like Friends,
and lodged at the house of another member, whose children had no appearance of Friends.

2nd. We rode round Little Egg Harbor River, to a tavern, nineteen miles; fed our horses,
and took some dinner.
Then obtaining directions respecting the road, S. N. and I set off,
and got to J. L.`'s at Leed`'s Point, between three and four o`'clock,
where we were kindly received and entertained.
The number of members being few, and the meetinghouse small,
and not in very good repair,
often they are much discouraged from attempting to hold a meeting for worship;
but latterly, through the visits of a committee of the Quarterly Meeting,
the number assembling is larger than it was a few years ago.

3rd. The morning was rainy and discouraging; but notice having been spread of our coming,
the men`'s side of the meetinghouse was pretty well filled;
the number of women about twelve.
The Lord furnished ability to preach the gospel among them;
and humble prayer and thanksgiving were offered to Him, for his goodness and mercy to us.
In the afternoon, it snowed and rained, with a high wind,
the storm coming from the north-east; but in the night it cleared up cold,
and froze pretty hard before morning.
We passed the remainder of the day with our friends,
and had a little religious opportunity with them before retiring to our chamber.

4th. Rose pretty early, and after breakfasting, we set out westward,
and rode over a rough road, frozen hard in some places, about eighteen miles,
to a tavern near Pleasant Mills.
Here we obtained directions respecting the way, which lies much through a piney country,
not thickly settled, along the east side of the west branch of Egg Harbor River,
to Atsion Furnace, and from there through Medford to J. E. E.`'s;
the whole distance from the Point being about forty-three miles.
The latter part of the road being much cut up with heavy wagons, made rough traveling,
so that when I alighted I could hardly stand.
Our Friend sent over to B. E.`'s, at Easton,
requesting him to spread notice for a meeting among them next day.
I felt satisfied and comfortable,
after the accomplishment of the visit to the shore meetings,
and hoped to be preserved watchful and inward to the Master,
through the remainder of the work.

5th. A pretty full meeting, but a laborious time among them,
on the subject of the love of the world.
It is much more desirable to be commissioned to speak peace to the faithful,
tribulated disciples,
than to have to warn the worldly-minded of their
inordinate attachment to the things of time,
and the pernicious influence it has, in destroying the love for heavenly things, and,
consequently, the work of the soul`'s salvation.
Dined with B. R., and in the afternoon, visited a sick Friend.
Went to D. W.`'s, at Rancocas, and put up with them.

6th. Attended their week-day meeting, which was pretty large,
although the weather was wet.
Soon after sitting down with them, some expressions of the evangelical prophet,
which prefigure the great change wrought in the temper, and appetites of the natural man,
as he comes under the renovating power of Divine Grace, came before me,
together with some of the expressions of James Nayler, when near the close of his life.
"`There is a spirit that I feel, which delights to do no evil, nor to revenge any wrong;
but delights to endure all things, in hope to enjoy its own in the end.
In God alone it can rejoice, though none else regard it.
It never rejoices but through suffering, for with the world`'s joys it is murdered.
It takes its kingdom by entreaty, and not with contention,
and keeps it by lowliness of mind.`"
The prophet says, "`The wolf shall dwell with the lamb,
and the leopard shall lie down with the kid, and the calf, and the young lion,
and the fatling together; and a little child shall lead them.`"
Again, "`Every valley shall be exalted, and every mountain and hill shall be made low,
and the crooked shall be made straight, and the rough places plain.`"
I felt raised up in the Lord`'s power, to show that the humbling operation of his Spirit,
as submitted to, brings down the lofty spirit and the strong passions,
and softens the rough nature of man, so that he is brought into the Lamb-like nature;
and a little child, regenerated by the same grace, shall lead him.
Here there is a harmonious walking together in the heavenly fellowship of the gospel;
and the happiness of families, and of religious society, is truly promoted,
where this blessed change is witnessed.
Help was mercifully granted through the fresh openings of the Holy Spirit,
to preach the gospel in its authority; to my own relief, and I hope, to the comfort,
and the conviction of some, of the truth of what was delivered.

Dined at A. W.`'s, and made a short visit to Granville Woolman, a minister,
and nephew of that humble, tribulated follower of Christ, John Woolman.
Took tea with H. W.. Before leaving their house,
I felt constrained to hold up to them the responsibility of bringing up children;
the necessity of laying a restraining hand upon them,
and of setting them such an example,
that nothing may appear in their own conduct unsuitable for the children to copy after.
Returned to D. W.`'s after dark, the weather still wet.

7th. In the morning, when about time to set off for Mount Holly,
we sat down with our friends,
and I had a word of consolation and peace to the dear aged grandfather,
and of caution and entreaty to the parents and daughter,
to come more and more out of the spirit and pursuit of the world,
and to devote themselves to the love and service of their Heavenly Father.
It was like a gentle shower, softening our hearts before the Lord,
and causing tears to drop from all eyes.
My companion and I left them, with feelings of reciprocal regard and affection.
The company convened at the meetinghouse was small, being chiefly members;
but the preaching of the gospel, adapted to their states, was no less important,
than in great congregations, and I hope heavenly help was granted to divide the word;
so that I was favored to relieve myself in love, among them,
without daubing with untempered mortar, and came away in peace;
thankful to the Master for his condescending goodness.
B+++.+++ E. and his wife, kindly met us at Mount Holly,
with whom we re turned to their house and dined.
Set out for the residence of our beloved, aged friend Hinchman Haines, at Evesham;
with whom I wished to spend some time,
as it might not be long that such an opportunity would be afforded.
He was free and open in conversation, chiefly upon the welfare of the Society,
which occupies much of his thought and concern.

8th. Went to Evesham Monthly Meeting; in which I was again favored,
through the unmerited condescension of the Shepherd of Israel, to such a poor,
weak creature, to hold forth the spiritual nature, and inward efficacy of the gospel.

"`The king`'s daughter is all glorious within; her clothing is of wrought gold.`"
This is figurative of the robes of righteousness,
with which the members of the body and church of Christ are clothed by Him,
as He is known to cleanse the heart, and divest us of the filthy garments of sin.
There was a word of encouragement to those who had long known this work, and who,
through the Lord`'s mercy, were built upon the Rock, and were as pillars;
or if they persevered in well-doing, would be made pillars,
that should go no more out of his house.
I had cause, gratefully to return thanks for the free supply of things, new and old,
which the Master granted me this day.
The business of the Monthly Meeting was conducted in a pretty satisfactory manner.

9th. Was held the Monthly Meeting at Medford, which was large,
being mostly composed of exemplary Friends;
among whom I labored in gospel love to awaken some, who have lost ground,
through unfaithfulness,
and suffering their minds to be absorbed by the pursuit of worldly things;
endeavoring to persuade them to turn away from that which hinders a growth in the Truth,
and to yield to the fresh visitations of Divine Grace,
that they may be restored to that tenderness of spirit,
and fervent desire after holiness, which they once knew.
Encouragement was also held out to the humble followers of Christ, to keep to Him,
and under a daily travail for themselves, and the flock around them.
The sitting closed with supplication for those classes, and for the visited children.
We went to a Friend`'s house to dine, where we met with our dear friend Lydia Stokes,
a pillar, and an exercised member in the church.

In the evening we rode to Joseph Evans`', of Cropwell, where we lodged.
They entertained us very pleasantly, being lovers of the truth, and the friends of truth.

10th. The morning was fine, and it being first-day,
a pretty large company convened at Cropwell;
to whom the doctrine of the law written in the heart, according to the new covenant,
promised through Jeremiah, was opened.
When Christ came, He said, "`My sheep hear my voice.`"
After his ascension, one of his apostles declared,
"`You have an unction from the Holy One, and you know all things:`" and,
"`You need not that any man teach you;
but as the same anointing teaches you of all things, and is truth and is no lie,
and even as it has taught you, you shall abide in Him.`"
These show the nature of the gospel religion;
and it is only by yielding to the law made known in the inward parts,
by this Divine Teacher, that we can become the sheep of Christ,
and members of his church.
There seemed to be those present,
who had need to be taught the first principles of the gospel,
and to be brought to the beginning point of all saving knowledge.
It was not a very animating season to me.

We dined at J. H.`'s, where we had the company of several Friends; drawn together,
in part, from sympathy with him and his wife, who had lately lost their only daughter,
whose end was precious.
Before leaving them, we had a religious opportunity,
in which resignation to the will of Providence,
and an earnest engagement to come up in our respective allotments, to the Lord`'s honor,
were affectionately pressed upon all present.
Rode to the home of my companion, and was kindly received by his dear wife.

11th. Attended Haddonfield Monthly Meeting in silence, during the first sitting.
There is need of more religious depth and feeling in many,
to qualify them for service in the church.
There appear to be few, comparatively, who live in that daily exercise,
and walk in the Spirit, which would fit them to judge a right judgment.
The present state of the Society, calls for a more fervent travail,
on the part of those who are sensible of it,
and a more united application to the Great Head of the church,
for wisdom and strength to labor for a reformation among us.
But the benumbing effect of the love of this world on some,
seems to render such reformation, in their cases, almost hopeless.

I was very low in spirit throughout the day;
no doubt needful to renew a fresh sense of the nothingness of man,
however he may have been divinely favored.
In the afternoon, sat with the few select members in their Preparative Meeting,
which was held at the home of Elizabeth Redman,
in consequence of her inability to leave the house.
It was rather a comforting opportunity, and grateful to her,
as she had been but little at meeting, since the last Quarter.

12th. Went to Moorestown, and attended Chester Monthly Meeting there.
The humbling feelings I had passed through,
prepared me for the reception of some openings into the states of those present;
and the Lord gave matter, and understanding, and authority, to hand it to them,
in meekness and true charity; dividing the word to different conditions.
It was his own work, and I was thankful for his condescending goodness and mercy to me,
a poor creature; and to others also, who were present.
Several expressed their unity and satisfaction when my minute was read.

13th. Was the Select Quarterly Meeting, which was less in number than usual.

14th. In the first meeting today, it opened before me,
that to be a watchman on the walls of Zion, had a double meaning.
First, to have our loins girded and light burning, watching over ourselves;
waiting for the coming of our Lord to show us his will,
and to give strength to perform it.
Secondly, being thus disciplined in the school of Christ,
so as to distinguish his voice from that of the stranger,
we are prepared to watch over others,
and to receive the command to warn the flock of surrounding dangers.
Many things, in reference to a growth in Divine Grace, were handed to the people;
and backsliders were persuaded to forsake their evil ways, and turn to the Lord;
and old and young were encouraged to keep to the guidance of the Captain of salvation.
If obedience is yielded to his blessed will, by the younger members of our Society,
we may safely hope that gifts will be dispensed to them;
that the waste places will be restored, and the revival of that Divine life and power,
experienced among us, which has been the strength,
the dignity and authority of the living members,
and which rendered the Society a bright example
of the christian virtues to other professors.
There appeared to be a warm feeling of unity and kindness among Friends.
After dining at S. N.`'s, I returned to my own habitation,
being satisfied with the visit so far as accomplished.

15th. My object in coming to the city at this time,
was to attend the Meeting for Sufferings, which convened this day.
An attempt having been made, in the Pennsylvania Legislature,
to repeal several important sections of the law of 1847, enacted to prevent kidnapping,
etc., the subject was taken under deliberation by the meeting,
and referred to a committee, to ascertain what was likely to be done by the legislature;
and if they believed it necessary, to prepare a remonstrance against the proposed repeal.

Memorials for our dear friends, Margaret Hutchinson and Sarah Emlen, were received,
and placed under the inspection of a committee.
The reading of them brought comfortable feelings over the meeting,
and it was a satisfactory sitting.

17th. At our own meeting on first-day,
I felt bound to testify to the continued presence of the Savior with his disciples,
down to this day, as they kept their faith in Him;
even when their eyes might be withholden from discovering his presence;
as those of his disciples formerly were, at times,
when He was with them in the prepared body.
After He has proved us, He will show Himself to the longing soul,
and satisfy it with his goodness,
and clothe with fresh strength to do his will in all things.

22nd. The Meeting for Sufferings was again convened,
to consider a draft of a memorial to the State Legislature against
the proposal to rescind parts of the law to prevent kidnapping.
It was twice read, and after a few alterations was adopted,
and the committee directed to present it to both branches;
also to furnish every member of the Legislature with a printed copy.

24th. Being first-day, I went to Newtown meeting,
notice having been spread of my intention of being there.
It was an exercising meeting to me;
the life of religion being but little in dominion in the hearts of many who were there.
But after a time of silent waiting, I endeavored to discharge myself,
in warning them of the fearful consequences of continued
rebellion against the visitations of the Holy Spirit,
which, if persisted in to the end, must separate the soul from the Divine harmony,
to mingle with the lost and fallen spirits, in a state of endless misery.
The joys of an inheritance among the saints in lights were also pointed to,
as the blessed reward of the righteous; as well as the sweet, sustaining peace,
from obedience to Christ, in our passage through life.

25th. Went to my beloved friend`'s G. and M. Mickle,
and next day attended Woodbury Monthly Meeting, which was small.
Renewed ability was furnished to labor, in the love and authority of the gospel,
to draw Friends to greater faithfulness to Christ.
In the afternoon rode down to Salem with Geo.
Mickle, where we were kindly received by our worthy friend Martha Wistar,
and next day were at the Monthly Meeting; which is also a small company.
After dinner, the weather being wintry, George and I rode to Greenwich,
and put up with my cousins, George and Naomi Bacon.

28th. Went to their Monthly Meeting; which was rather exercising to me,
yet not without comfort.
There are rightly concerned Friends belonging to it, who desire the prosperity of truth.
Called afterward at our aged and afflicted friend`'s John Sheppard,
now confined by a complication of diseases.
Sitting in his chamber, the way opened to hold forth the doctrine,
of becoming as a little child,
preparatory to experiencing the kingdom of heaven to be set up in the heart,
and an entrance into it administered in the world to come.
When we are humbled into a sense of our nothingness, and receive the gift of repentance,
though our past transgressions may, at times, seem to come before us as a cloud,
or even as a thick cloud, yet having loved the Lord and his cause,
we have ground to hope that he will regard us in our low, humble condition,
and forgive them, for his name and his dear Son`'s sake.
It was a contriting opportunity to nearly all present.
The snow made traveling slavish for the horse,
so that we were about three hours going twelve miles, to Alloways Town,
where we put up with a Friend for the night.

29th. Accompanied by our friends, we rode to Woodstown,
and attended a meeting appointed to be held in a Friend`'s house.
The company was small, the former members having very generally gone with the separatists.
I had much to communicate, on the fruits of obedience to Divine grace,
and on some of the doctrines of the gospel;
warning them against the spirit of infidelity, that is stalking abroad in the country.
The meeting closed with prayer for our preservation from the temptations that surround us.
Dined with S. L. and several other Friends, and before we left,
I endeavored to encourage them to keep to their religious meetings, though small,
both for their own benefit, and that of the young people.
Set off for Woodbury, and called to see our aged friend Rebecca Hubbs;
confined from the effects of paralysis.
She is an extraordinary instance of the power of Divine grace,
in preparing one of little knowledge, who has been faithful to its teachings,
for usefulness in the church; and having received a gift in the ministry,
enabling her at times to exercise it in an extraordinary manner.
Though her voice was affected by disease,
she spoke of the many favors that had been conferred upon her;
for which she said she was afraid she had not been sufficiently thankful.
I had a little encouragement for her; expressing the belief that the covenant of life,
and of peace, would be with the Lord`'s faithful children, which He would give them,
for the fear wherewith they feared Him, and were afraid before his name.
And though she might pass through much weakness and stripping, I trusted that He,
who had been with and supported her in days past, would mercifully grant the evidence,
before the end came, that a mansion was prepared for her.
She was comforted by our visit.
We went on our way pleasantly, the road from Swedesborough being good,
and got to G. Mickle`'s towards evening, which is an agreeable tarrying place.
Next morning I went in the stage to Red Bank, and taking the steamboat,
reached home well and peaceful.

Fourth month.
As our Yearly Meeting draws on, my mind has been clothed with sadness;
leading me to anticipate suffering and danger, unless the Master, by his invisible power,
interpose to defeat the insidious workings of the unwearied enemy,
who is watching to destroy our Society.
Our refuge is in the mercy and goodness of the Lord Almighty;
who only can preserve his church, and exalt his own Name and power,
enabling his people to praise Him for his wonderful works to the children of men.

12th. Was held our Meeting for Sufferings, which was satisfactory,
largely attended by the members, and some Friends from other Yearly Meetings.

13th. The Yearly Meeting of Ministers and Elders was small,
showing the gradual diminution of this class among us.
My sister, Hannah Rhoads, was liberated for the purpose of visiting Friends,
in some parts of Great Britain and Ireland,
with which a good deal of unity was expressed.
I was low, mourning over the desolated state of the Society,
and the thinness of our ranks;
as well as the lack of that degree of life and spiritual strength,
which have characterized faithful, experienced Friends in former days.

15th. Our Yearly Meeting was opened today, and was very large.

Fifth month 23rd. Crossed the river and went to Haddonfield,
and attended their week-day meeting, which was small.
It came before me pretty soon, that there were many up and down, who,
though they made little noise in the religious world, are sincere seekers of the truth;
sitting often at the feet of Jesus,
and craving for themselves heavenly bread and preservation, from Him.
I believed that His gracious eye regarded these in their solitary dwellings,
and He answered their sincere petitions; and that of this description,
there were those present, whose encouragement and strength in the way of their duty,
I desired.
Although the support of their religious meetings may often be felt to be laborious,
and they are sometimes disappointed in receiving the spiritual comfort they desire,
yet as they keep faithful, the Lord would send them help from his sanctuary.
I believe the poor in spirit were a little cheered by the unexpected call of a visitor,
and they were hearty in their salutations at the close.
Dined with S. N.,
and made agreement with him to accompany me to the remaining meetings in New Jersey.

27th. Went to S. N.`'s, and next morning we rode to Burlington,
and attended the Quarterly Meeting, which I sat through in silence.
There being but little business in the second meeting, it closed with a short sitting.
In the afternoon we rode to John Bishop`'s and lodged.

29th. Notice having been given at the Quarterly Meeting, we had a meeting at Mansfield;
in which ability was given to preach the gospel,
and to invite the people to believe in the Lord Jesus Christ,
not only as He is our glorified Redeemer and Intercessor,
at the right hand of the Father, but also as He appears in the heart, by his Spirit;
to purge away sin by the administration of judgment, and his refining fire,
so as to prepare man to hold communion with his Maker,
and to follow Him in all his requirings.
The meekness and lowliness of Christ,
and the gentleness with which He deals with those who are brought to obey Him,
and our duty to follow his example, were a little set forth.
After dining, we rode to Crosswicks, and put up with J. M. and wife.

30th. Attended their usual mid-week meeting; at which some not members were present.
I was led to open the spiritual, practical nature of the religion of the Lord Jesus;
which is not designed to amuse the head, but to change the heart;
and that some had need of experiencing this effect upon them,
rather than indulge in speculation in relation to religion,
while they keep aloof from its heart-changing power.
There were serious persons present,
to whom I hoped the opportunity would be strengthening, as well as to those,
upon whom chiefly rested the weight of keeping up a meeting there.
On our way to Trenton, we called on a Friend who had recently lost his wife.
The circumstance reminded me of the similar trial through which I passed,
and which preceded, a short time, my first appearance in the ministry.
We had a tendering opportunity just before leaving;
in which the great importance of making a right use of
the talent the Great Creator has endowed us with,
for his glory, the good of our own souls and of his people, was, in love and sympathy,
spread before them; particularly directed to the bereaved husband.
They appeared satisfied with the little opportunity, and we parted in mutual affection.
We went on our way peacefully, and got to our friend Ann Kaighn`'s at Trenton before dusk,
and were kindly received.

31st. Had an appointed meeting at Trenton this morning,
with the members and a few others; in which,
under feelings of tenderness and sympathy towards the little company,
who are endeavoring to maintain the standard of truth and righteousness in this city,
I was led to hold up the necessity of keeping the watch
against the snares of an insidious enemy;
and to warn them of the liability of losing a good condition, without it.
I was also bowed in supplication for them,
that through all the trials of this uncertain life,
they might know the Divine arm to be underneath,
and their faith renewed from season to season, and in the end,
through the Lord`'s preserving power and goodness,
we might be gathered into a mansion of rest,
where we may unite with the sanctified of all generations,
in ascribing thanksgiving and praise to the Lord God and the Lamb, world without end;
who are forever worthy.
It was a solemn opportunity, and I hope profitable.

After dining, we went in company with some Friends to Stony brook,
and had a meeting at four o`'clock, with Friends and others who usually meet there.
The number of the former was very small, few bearing the appearance of Friends.
The condition of some, who had once known the Day-Spring from on high,
and been brought into the love of Christ, but were now in a different state,
was spoken to.
The impossibility of anything that man could invent and substitute,
giving life to the soul,
and bringing it to the saving knowledge of God and of his son Jesus Christ,
not even the Scriptures, but Christ himself,
by the immediate operation and revelation of his own Spirit,
were clearly declared unto them.
The doctrine of the Savior, that to enter the kingdom of heaven,
we must become as a little child; in which state we are prepared to be taught of Him,
and in which true greatness consists, was enforced.
It was not a season of much rejoicing,
though I trust some were brought under religious feeling;
and I left them with a quiet mind.
The next morning we set out for Rahway, which we reached early in the afternoon,
and took up our lodgings at Joseph D. Shotwell`'s.

Sixth month 2nd. Attended their first-day meeting;
in which there was a qualification vouchsafed, to search Jerusalem as with candles,
and to warn some of the danger they were exposed to,
through an eager pursuit of the world,
and being drawn into an alliance with its fashions and customs;
as well as from the influence of other spirits,
who are at enmity with the cross of Christ, while professing a respect for religion.
They were reminded, that while we might be courteous, as a Christian is bound to be,
that love without obedience is of little more worth than faith without works.
Our Lord declared, "`If a man love me, he will keep my words,
and my Father will love him, and we will come unto him, and make our abode with him.`"
It is only by obedience to the grace of Christ Jesus,
that the heart can be changed and sanctified, and thus prepared for the Lord,
to dwell in, by his Spirit.
The matter being furnished, flowed freely,
and many truths of the everlasting gospel were clearly opened.
The spirit of supplication being felt, prayer was put up.
The minds of some were tenderly wrought upon; but a few of the worldly young men,
though respectful, appeared to cast off or lightly esteem the obligations of religion,
and the simplicity of its character and requirings.

We returned to J. D. Shotwell`'s, and before leaving, several Friends being there,
a little opportunity presented, to remind some,
of the responsibility of the stations they occurred.
To them the young people looked for examples, and the need there is,
to draw them to Christ, by their conduct and spirits, that they too may learn of Him.

3rd. Word having been sent for a meeting at Plainfield, on second-day afternoon,
H+++.+++ W. piloted us there.
We dined at our very kind and hospitable friend`'s, New York.
The meeting, composed chiefly of persons not Friends, was not a very lively one to me;
yet I endeavored to discharge what appeared to be my duty.

4th. The weather, after being cool for the time of year, was fine today; and though warm,
we got to Trenton about one o`'clock, and crossed the Delaware.
Next morning, riding to Bristol, we crossed in a steamboat to Burlington,
and proceeded to our friend Henry Warrington`'s, at Westfield.
Here we were received with his usual kindness;
there being few who are more thoroughly sincere in their attentions to their friends,
than he is.
He is a true lover of the truth, and of the friends of truth,
and heartily devoted to serve them and the blessed cause of the Redeemer.
I regard him as a pattern of Christian politeness and humility,
without ostentatious display.
In the afternoon, he took us to see our friend Samuel Leeds,
with whom we had cheerful religious converse.

6th. Attended the usual mid-week meeting.
The language passed through my mind pretty early after sitting down,
Is there any growth in the Truth among you?
I hoped that among so many goodly looking Friends,
it might be answered in the affirmative,
yet felt a fear it was not so fully the case as ought to be.
The Master, I trust, qualified to enter a little into the state of the meeting,
and to show that those who are faithful in a little, will be made rulers over more;
and will be favored to see the beauty, order and strength of the church of Christ,
the Lamb`'s wife; and as they persevere,
receive gifts to be occupied in their respective places, to his honor,
and the benefit one of another.
The exercise of parents for the everlasting welfare of their children, on whose account,
as they rightly value the salvation of their own souls,
their prayers and tears will often be poured forth, was spread before them,
and the tendering power of the Holy Spirit appeared to be over some.
Samuel Leeds closed the opportunity with supplication for Divine preservation for us all,
and with thanksgiving to our Heavenly Father,
for the renewed visitation of his goodness at this time.
I was clothed with weakness, and a sense of unworthiness,
yet hoped the pure mind was stirred up in not a few.

We returned to our friend H. Warrington`'s; and after dinner,
my kind and attentive companion S. N. took me down to Camden, where we parted,
with increased affection for each other.
I then crossed the Delaware to my own home,
where I found my beloved wife and family in good health, and glad to receive me.
The feeling of sweet peace clothed my mind,
with gratitude to the Lord for his preserving power,
and the ability which He furnished for the work whereunto I believed He had called me.

9th. First-day morning we had our friend Samuel Bettle, Sr. to minister to us.
Parts of his communication were particularly instructive, and of a practical nature.
My dear wife followed him in fervent supplication,
and I hoped the Truth did not lose ground among us.

12th. Emptiness and poverty have been my portion,
accompanied with mournful reflections upon the state of our religious Society.
Will not the Lord have compassion upon us, and turn our hearts more to one another,
with unfeigned love, and prayer for defense from the stratagems of the enemy;
whereby he constantly lying in wait, to beguile from the innocency of the Truth,
that he may lay us waste individually and as a people!
Arise, O Lord, you and the ark of your strength.
Let your priests be clothed with righteousness;
and cause your saints once more to shout for joy,
because you have taken the government into your hands, and rebuked the enemy,
and brought us to see eye to eye in your light.

23rd. Went to our son-in-law`'s, near Germantown, and lodged;
and next morning my wife and myself went with them to G. S.`'s,
and attended Abington Monthly Meeting.
They are a small company, but mostly sincerely attached to our testimonies,
and in their lives show their desire to support them.
The spring of the ministry was opened for their comfort and admonition;
that they might not be deterred from faithfully pursuing their duty,
either through discouragement, or the attractions of worldly things.
They were reminded of Friends being a small company at their commencement;
but waiting patiently upon the Lord, they grew in the Truth,
and received gifts to edify one another, and gather many to the fold of Christ.
The visit appeared to be acceptable, and we rode back to Germantown.

26th. Our Monthly Meeting was held today;
at which I returned the minute furnished for visiting the meetings of New Jersey,
and informed Friends the service had been accomplished,
to the peace and satisfaction of my own mind; having been at all the meetings but one.
In the evening we again went to Germantown, and next morning were taken to Gwynedd,
where we attended the Monthly Meeting.
A committee of the Quarterly Meeting was there, appointed,
in consequence of their reduced state, to aid them in the management of the business.
The women`'s meeting is much larger than the men`'s, and they were without such aid.
I thought a fresh qualification was granted for preaching the gospel to them.
The business was conducted suitably, though but few to speak to it.
We dined with J. S.`'s widow, and two sisters,
who received and entertained us with much cordiality.

28th. My dear sister H. Rhoads came to town, in order to proceed to New York,
to embark for Liverpool, on her religious visit to Friends.
In the evening after taking tea with her and others, at my brother Charles`',
several Friends came in;
which furnished an opportunity for feelings of sympathy with her,
and of imparting to one another the word of comfort and caution, in which Samuel Settle,
Sr., and several others participated.
We hoped the retrospect would be satisfactory to her in a distant land,
as it was grateful to us, to part under such feelings.

29th. H. Rhoads, and Elizabeth Peirson, her companion,
with several of their relatives and friends, went in the early morning line to New York,
where the ship lay in which they were to sail for England.
We were disappointed in finding she had fallen below the city,
so that we could not see them on board, without going down the bay,
and not return until after night.
J+++.+++ Rhoads and T. Evans accompanied them, taking the risk of being detained in the night.
They got back to New York in the evening, leaving our friends pretty cheerful;
and the rest of the company reached Philadelphia about nine o`'clock the same evening.
The ship got under weigh, we suppose, next morning.

Seventh month 4th. This morning, before rising,
there seemed to be a gentle pointing to the Arch Street Meeting,
where I had not been since the Quarterly Meeting.
When there the life was low, and I felt borne down with discouraging thoughts;
but finally the necessity of daily and hourly living in the fear of the Lord,
and maintaining the watch,
that we might be delivered from the various snares and
temptations with which we are surrounded,
came before me, with the intimation to rise with it.
The importance of young people beginning early in life to cherish this fear,
and the daily practice of watching against and resisting temptation,
by the aid of the Lord`'s Holy Spirit, was spread before them.
The apostle exhorted the believers to resist the devil and he would flee from them;
which was found to be true by the Lord`'s children and servants, down to the present day.
The declaration concerning Levi was, "`My covenant of life and peace was with him,
which I gave unto him for the fear with which he feared me,
and was afraid before my name.`"
As this holy fear is kept, the Captain of salvation will keep us,
and establish us upon the immovable foundation; give us the testimony that we are his,
and when the end comes, receive us into the arms of everlasting mercy,
which will be of more value than all the world can give, could we possess it.

9th. From an apprehension of duty, I went to the Northern District Meeting;
and in the course of our silent waiting,
the peace and safety of being brought to feel
ourselves as the least of the Lord`'s children,
came before me, with the testimony of the apostle Paul,
that he was less than the least of all saints.
It felt to me there was great sweetness of spirit enjoyed at times in this humble state.
We were enabled in it, to bear being trampled on, if it was the Lord`'s will to permit it;
while others may seem to reign as kings without us.
Here we experience Divine support;
and when we are let down into baptism and suffering for our own sakes, and the body`'s,
our Lord will be with us; and when our faith has been tried,
He will show Himself to be the resurrection and the life;
giving renewed qualification to speak to the praise of his excellent name.
The language of encouragement was held out to some who had their peculiar trials to bear,
that they might humble themselves as a little child, and thereby,
according to our Lord`'s doctrine, be great in the kingdom of heaven.
For if there is anything pertaining to us, that will bear the name of greatness,
it is in being constantly clothed with the garment of humility.

This afternoon a fire commenced in a store on the wharf, a little below Vine Street,
partly occupied with bales of hay; and either in that or the adjoining building,
it is said, a quantity of saltpeter was stored.
After the fire had progressed some time, one or two explosions took place,
which did not create much alarm; but the fire spreading and the heat increasing,
a tremendous burst followed, throwing down the walls, and carrying high up into the air,
a large quantity of ignited matter,
which was carried by the wind on to the neighboring houses.
It proved to be the most extensive and destructive
conflagration our city has ever suffered from.
How suddenly and unlooked for,
have a large number of families been turned into the streets,
dependent upon their friends, and the public,
to provide them with temporary accommodations.
Instruction ought to be sealed upon our minds,
of the uncertainty of everything we now possess;
and of our duty to look to our Heavenly Father for protection,
with reliance upon Him for all we have and need.
We should thus, at least, be in the best condition of mind, to meet such a calamity,
were it permitted to overtake us; not having to charge ourselves with self-confidence,
or with forgetfulness of what we owe to our great and gracious Benefactor.

28th. This morning, as we sat at the breakfast table, being first-day, our beloved,
absent sister H. Rhoads, was brought into view.
Our sympathies were drawn forth towards her;
accompanied with sincere desires that she may be favored of the Lord,
to see the path of duty which He assigns, and with wisdom and authority,
to pursue it to his praise and the good of the people.

This morning I went to Germantown, in order to be at the meeting there;
having a secret drawing to be with them.
I got in a little after the Friends had generally convened.
The testimony was raised, that the Lord`'s tender mercies are still over all his works;
extended even to the rebellious, and to those who love and serve Him.
I was enabled to declare of the new and living way,
that was opened by the blood of Jesus, and of the gift of grace purchased by Him;
by obedience to which, all may come to have access to God by this new way,
and to worship Him in spirit, and pour forth their prayers to Him.

To the rebellious, the danger of neglecting the proffered salvation,
by suffering the day of visitation to pass away unimproved, was held out.
Those who have given up and made sacrifices,
but from whom the Beloved of souls had hid his face,
were encouraged to keep fast hold of their faith, however much reduced, and He would,
when the dispensation had accomplished its purpose,
again cause his face to shine upon them,
show them with clearness their duties in his church,
and give wisdom and strength to fulfill them.
The aged who held fast their integrity to the Lord,
when the powers of body and mind were weakening,
would know Him who took them in his arms in the day of their espousals,
to renew their strength as the eagle;
enabling them to rise above the tribulations of time,
and animate them with holy hope and confidence,
that in the end an admittance would be granted into the
everlasting kingdom of our Lord and Savior Jesus Christ.
I hoped there were some serious and cheering feelings brought over the different classes.

30th. Our city has been in a state of tumult today, by a great procession,
in honor of the late deceased President.
Such parades are opposed to the spirit of Christianity,
both in the unwarrantable expense of money for mere display;
drawing off many people from their business, whose means do not admit of it,
and paying such adulation to a poor fallible being,
cut off suddenly in the midst of the honors which were being heaped on him.
It seemed to me that such mockery of mourning was more
likely to call down upon us Divine judgment,
in some form, than the approbation of Him, who is a God judging in the earth.
The Mexican war, in which Z. Taylor was one of the chief actors,
was a war of great atrocity, undertaken to enlarge the Slave States,
and their influence in our government.
The territory wrested from Mexico has proved a source of great and bitter contention,
between the Free and Slave States, threatening the dissolution of our Union,
and failing to secure the object for which it was undertaken.
The number of disasters and calamities,
involving the destruction of the lives of many of our own citizens,
and the loss of much property, by fires and otherwise, has been very striking,
and leads the watchful, reflecting mind, to the apprehension,
that inasmuch as the United States, by their armies,
have wantonly destroyed the lives of hundreds of unoffending people,
Divine Providence has, in part, withdrawn his protecting power,
and suffered these things to overtake us,
as retribution for our great sins against the Mexicans, and against the poor negro;
for whom, the slaveholder was preparing a market,
that he might enrich himself by the sale of his fellow man.
The confusion in which our Congress has been placed,
for the eight months of this session, is a further evidence,
that the Lord has deprived them of the wisdom,
ability and harmony which enabled them to dispatch their business in sessions back;
and it may be still more withdrawn,
to show us that our government is not so permanent as we have imagined.
"`Pride goes before destruction, and a haughty spirit before a fall.`"
