== Chapter XXIV

[.chapter-synopsis]
* 1850--1851. Various Religious Engagements within Philadelphia Yearly Meeting
* Liberated to pay a Religious Visit within Indiana Yearly Meeting.

1850, Eighth month 14th.
We shut up our house and went to stay a few days with our beloved brothers,
and families, at Springfield.

15th. Attended their meetings; in which we both had some service,
I hope to the encouragement of the right-minded.

19th. We went to Concord and attended the Select Quarterly Meeting;
in which the way opened to encourage all, to keep on the watch tower,
waiting for the coming of their Lord,
even if they must remain in their ward whole nights.
The dispensations of the withdrawing of the Heavenly countenance are for our good,
and if properly endured, prepare us to receive the Lord at his coming,
and a qualification to testify of his power and goodness;
and to labor to gather others into the love of Christ.

20th. Attended the Quarterly Meeting for Discipline under great weakness;
there seeming to be little ability to advocate the good cause.
In the second meeting there was a concern felt,
to call Friends to greater degrees of true fellowship,
in that love which the apostle alludes to, when he said,
"`It is in our hearts to live and to die with you.`"
As we are clothed with this love, we shall keep a guard over our tongues,
and take care not to speak of others,
in connection with anything that will lay waste their religious standing.
Our brother, Joseph Rhoads, concluding to accompany us to the Western Quarterly Meeting,
we set out after dinner.

23rd. Rode to London Grove, and when the Meeting convened,
we found it much larger than we expected, many Friends from Concord,
and some from Cain Quarter being there.
My dear wife was engaged in vocal supplication,
that He who breathed upon the dry bones in the valley,
would condescend to work by his mighty power upon many,
and prepare them to stand as an army for his cause; and also for the dear children.
P+++.+++ E. followed her in testimony.
Afterwards I was constrained to bear testimony to the Messiah, the Prince of Peace,
the Shiloh of God, to whom the gathering of the people is to be.
Who, when He came in the flesh, declared,
that as Moses lifted up the serpent in the wilderness,
so shall the Son of Man be lifted up; and, that when He was lifted up,
he would draw all men unto Him.
The people were invited to come to Christ in his spiritual appearance in the heart,
and to obey his Divine requisitions as made known there;
that they may be brought out of their earthly conditions,
and qualified to promote the spreading of his kingdom,
by turning others to righteousness.
The business of the meeting was transacted in a becoming spirit;
the importance of waiting upon the Lord for wisdom and
right direction in the Meetings for Discipline,
was affectionately spread before them.
In the afternoon we accompanied our dear friends, J. and S. W. to their habitation.
Parts of the road being through a luxuriant country,
beautifully diversified with hills and valleys, woods and grass fields,
we enjoyed the ride.
In the following morning,
we had a religious opportunity with our friends and some young people.

26th. Was held Chester Monthly Meeting at Springfield,
and a pretty large company gathered.
I was fervently engaged to warn Friends of the danger of making idols
of the temporal blessings with which we are so abundantly surrounded;
forgetting and neglecting the duties and the gratitude which we owe to the Great Giver.
For all these things, we must give account in the day of judgment.
If we are delighting and aggrandizing ourselves with them,
and growing in self-importance, the language from one of the holy watchers may go forth,
"`Hew down the tree, and cut off the branches`" and awful will be the condition of such.
Such were called upon to come again to Bethel, and through holy help,
renew their covenants with the Lord that so they may
again experience that humility and tenderness,
which they were once favored with.
It was a solemn opportunity, in which I hoped the Truth had the dominion;
and Friends parted with feelings of near affection.
We rode back into the city.
It was pleasant to get again under our own roof,
where the feelings of peace and comfort are so often enjoyed.

Ninth month 10th. Went to the North Meeting; which, for the middle of the week,
was quite large.
I sat, perhaps, nearly an hour, during which many presentations passed before me.
Finally the happy condition of those who were brought as children into the Lord`'s family,
and were preserved in it to the end, even to old age, came livingly before me;
and through the blessed openings of the Key of David,
I was enabled to enlarge upon the progress, baptisms,
preservations and deliverances of these, to the comfort and strength, I hope,
of some present.
To those who had been often called, yet turned the back upon the heavenly visitant,
a voice of solemn warning went forth;
and the mourners were encouraged to hold fast their confidence firm to the end.
I came away with a peaceful, cheered mind.

18th. Went to Germantown, and the next morning being the meeting day there, I attended it.
The danger of swerving from the path of holiness, after being brought into it,
and the indispensable necessity of giving up all that is called for,
that a growth and an establishment in the Truth may be attained,
were held forth among them.
Some unstable ones, who at one time are made sensible of Divine convictions,
and then are turning away,
and forgetting what manner of persons they have seen themselves to be,
and taking delight in things not according to the requirements of the Holy Spirit,
were tenderly entreated to renew their covenants with the Lord in the day of visitation,
and seek for strength to keep them faithfully unto the end.
I believe that holy help was present, qualifying to search into the states of some.

Tenth month 5th. I am sixty-three years old this day.
Thoughts of the race being nearly run;
and the possibility of its being brought to a close earlier than I may anticipate,
produce feelings of a serious kind,
and desires to be making ready for the solemn moment of death.

6th. First-day morning.
Our meeting still reduced.
After sitting an hour, and feeling much poverty, I was constrained to testify,
that a manifestation of the Holy Spirit was given to every man,
to enable him to work out his salvation.
That it reveals sin in the heart,
and affords the strength which alone can deliver from it.
This grace and truth come by Jesus Christ; who not only was offered upon the cross,
a propitiatory sacrifice for the sins of all mankind, but also purchased for all,
this Divine Grace, which teaches us to deny all ungodliness, and the world`'s lusts,
and to live soberly, righteously, and godly in this present world.
As it is obeyed, it regenerates the dark heart, and gives true faith in the Son of God,
and prepares us to receive a Divine understanding of the Scriptures;
which were written by holy men under the guidance of the Spirit of Christ.
It alone can give a true sense and belief of them.

It felt to me that there were some present who had fallen into a state of unbelief,
through the despite which they had committed against this grace;
and by trampling under foot the blood of the covenant,
by which alone they can be sanctified,
they were nigh to denying the Lord that bought them.
The great change that had been wrought in many unbelievers,
who were brought to receive Christ into their hearts and to obey Him,
so that they experienced, like the man out of whom the devils were cast,
what it is to be clothed and in their right mind;
and who then desired and loved nothing so much as to sit at Jesus`' feet,
was laid before them.
He who appeared in the midst of his disciples, the doors being shut,
and called on Thomas to put his fingers into the print of the nails,
and thrust his hand into the hole in his side, made by the soldier`'s spear,
and be not faithless, but believing, and when Thomas had done so, and said,
my Lord and my God; is an omnipresent, as well as omnipotent Savior.
Not only all the treasures of wisdom and knowledge are hid in Him;
but all power in heaven and in earth is given unto Him; and He alone can give true faith,
and enable, us to believe in Him, and give power to become the sons of God.
Many things connected with the work of salvation,
until we come to be established upon Him, the Rock and Foundation,
against which the gates of hell cannot prevail, were opened.

12th. My dear wife, in company with S. C, and my brother Joseph Evans,
left home to visit the meetings of Exeter, Maiden Creek, Greenwood, Muncy and Elklands.
The weather was very fine, and if no accident befall them,
everything seemed to bid fair for a prosperous journey,
if the Lord be their guide and blessed helper
which it is my hope for them will be the case.

13th. At our first-day meeting, the company was a little increased.
A warning was sounded among them against a light, scoffing spirit,
on the subject of religion,
and respecting the conscientious scruples of men and women who fear God,
and endeavor to walk according to his will.
Friends were called to the work of religion in themselves;
that everything of a light and chaffy nature might be destroyed,
and a solid and weighty frame of mind might take the place of it,
so that they may be examples of purity and self-denial,
and a standing protest against the wickedness and
abominations that run like a torrent through our land.
They were warned against countenancing the vain
exhibitions and amusements that evil men and women,
strolling up and down, were inviting the people to.
Many people who make a profession of religion,
make no scruple in frequenting such places,
and by their example encourage others to do the same.

How can such be clear of the blood of their fellow men,
while leading them into the paths of wickedness,
and away from the footsteps of Christ`'s companions?
But those who turn their back on all the temptations of Satan,
and follow the great Captain of salvation,
will know Him to give power over all the powers of the enemy;
and that he can deliver those who sincerely desire to come unto God by him.
I left the meeting under a sense of Divine sweetness and peace,
in having given up to do what I believed the Lord called for,
though I had shrunk from it, lest I might act without my guide.

17th. My brother-in-law, J. Rhoads, having been indisposed, I was drawn,
in sympathizing with him in his lonely feelings,
on account of the absence of his valuable wife, to make him a visit,
and to attend their meeting.
The meeting was small.
Unexpectedly, the subject of the growth of trees presented to me.
Planted, when like small switches, yet if properly cared for, and defended from injury,
gradually growing, and finally becoming valuable for fruit, or for shade and beauty.
So it appeared to me to be with trees of the Lord`'s planting.
As they are cherished and preserved from the enemies they are exposed to,
they experience a growth in grace; their root strikes downward in the heavenly soil,
and they bring forth fruit to the praise of the Great Husbandmen,
and finally they are established in the house of the Lord,
and flourish in the courts of our God.
He beautifies and dignifies such in his church,
and enables them to glorify Him in their generation.
They become pillars in the house of our God, that shall go no more out;
and He writes upon them the name of our God, and the name of the city of our God,
which is New Jerusalem; and He will write upon them his new Name.
It was a day of favor; in which the hearts of some of the mourners were made glad,
and the dear young people cheered to hold on their way.

28th. The unsettled state of almost all the governments in Christendom,
and the excitement among Protestants,
in consequence of the attempt of the pope to
resuscitate the Roman Catholic hierarchy in England,
showing the unextinguished craving in that corrupt and anti-christian church,
for universal dominion, have a depressing effect on those,
who travail in spirit for the more glorious breaking
forth and spreading of Christ`'s kingdom in the earth.
The bold effort made there, may have been permitted,
to rouse up Protestants to examine how near they approach that degenerate body,
in their reverence of the beggarly elements and superstitious ceremonies,
that have no relation to the spiritual, regenerating religion of our Lord Jesus Christ.
A further consequence may be the more open exposure of
the abominations committed by the Romish church,
and thereby pave the way for its downfall,
and the arising of the light of the glorious gospel of Christ;
before which all ceremonial rites and practices will fade away.

I have a secret hope that the Lord is at work to bring
about a more settled state of our religious Society;
to bring forth some whom He has been preparing to stand
more openly and boldly for its christian doctrines,
testimonies and discipline; and to rebuke the spirit that has been at work,
to divide and scatter,
by upholding those who have attempted to bring in unsound opinions,
and giving liberty to go into things which the Truth is against.

After enduring much secret suffering,
in which there seemed few to sympathize and to strengthen, as I sat in my parlor,
waiting upon the Lord, there was a secret, undeniable sense granted,
that the Lord beheld me in my trials and fears, on account of our poor Society;
and my heart was comforted, and my faith renewed,
that his gracious eye is constantly beholding his tribulated children.
May we not hope, that the clouds with which we have been so long surrounded,
are preparing to break away.

This morning, I felt an intimation to go to the Arch Street Monthly Meeting,
where I had not been for many months.
The advantage and safety in being brought into a humble, lowly condition of mind,
in which the strength of man is turned as into weakness and nothingness,
was opened before me; and after a Friend had spoken, I believed it required of me,
to stand up with this matter.
Though our faith may be reduced very much,
yet as we do not wrest ourselves from under this dispensation,
to seek relief from some outward source, the Lord in his time would appear,
and by the testimony of his Spirit, enable us to say, "`You, God, see me.`"
The precious stream of the ministry rose a little, and flowed forth,
to the refreshing of not a few.
The dear school children were also called upon,
to obey the tender convictions of their Savior`'s spirit.
The business of the meeting was transacted with weight,
and a proper feeling of its importance;
and I hope we were a little cheered with the
present evidence of Divine good in the midst;
and with the renewal of faith, that the light which first visited the members,
and gathered our religious Society, would yet break forth in thousands;
and the precious cause be spread by us in the earth.
I came away with the feeling of heavenly peace, and lowliness of mind before the Lord;
and therein desire to be preserved, and to give unto Him at all times,
the glory and honor which are his due alone.

Twelfth month 2nd. It will be a great favor if Divine Power rises into dominion among us,
so as to animate and strengthen right-minded Friends,
to come out boldly on the Lord`'s side, and on behalf of our testimonies;
that so the self-denial, the humility, the simplicity, and the inwardness of spirit,
which characterized our first Friends, may be revived, and shine forth conspicuously.
There is an enmity against the lowliness, which Christ leads his humble followers into;
and a desire, in some, to make a show in the world; that we may be like others,
and thereby the reproach of the cross caused to cease.
As that takes place, our locks will be shorn; we shall become weak like other men;
spiritual vision will be lost, and worldly professors will vaunt over us.
But may the Lord in mercy, kindle up fresh zeal among us;
bring us near to one another in the covenant of life,
and enable us to put shoulder to shoulder in the support of his cause,
and send forth fresh laborers into his harvest field.

18th. Poverty of spirit, and the reduction of faith have been my portion many days past.
If it is of the Lord`'s dispensing, to lay low the creature, it is enough.
He will not cast off those whom He condescends to purge, and prostrate,
if they give themselves, and all they have, into his hand.
There can be no higher favor, than being objects of his mercy and preserving power;
and this is as truly shown to be the case, in his emptying and stripping dispensations,
which bring man to feel his own nothingness, as when His candle shines upon his head,
and he is filled with a heavenly sense of the Divine fulness.

1851, First month 8th. I have been renewedly confirmed in the opinion,
that the pointing of the Divine finger is needful to
lead us safely in visits to other meetings.
Friends in every meeting,
have their rights in the disposal of the business of that meeting, and any interference,
in man`'s will and wisdom,
not only may give an improper direction of subjects under deliberation,
but wound the feelings of the members.
It is evident that nothing but the wonder-working power of Divine love and kindness,
can heal the breaches,
and restore to us the paths of peace and heavenly unity to dwell in.
This we must suffer and travail for in the patience of the saints,
and the Lord will bring it about to his own honor and the great comfort of his people.

20th. A dear friend and his wife, called in this evening,
with whom we had sweet converse upon the things
concerning the spreading and power of truth,
which lie nearer to our hearts than anything else.
He was under a concern that Friends might more frequently visit the members,
who have little opportunity of mingling with rightly concerned Friends;
and encourage them to faithfulness.
He thought the Society was still blessed with a living ministry;
that many acknowledged it in their hearts, and he could not think it would be lost,
but in time fruits would appear.
He expressed a fervent and sincere desire, that Friends who felt the weight of service,
and of our responsibilities, might be encouraged.
I united with his views in relation to the advantage of
Friends more generally visiting one another in a right spirit;
and we may hope that the time is drawing on for it.

22nd. Having felt my mind turned to the Western Meeting for a few days,
I went there and attended the Monthly Meeting.
I was brought low, and the matter which opened before me, seemed of such close nature,
I felt afraid almost to look at it.
After a time it was taken away:
when the great importance of watchfulness and daily prayer,
that we may be preserved from losing ground and falling short in the end,
came livingly over my mind, and had a humbling effect.
Under a degree of tenderness, I believed it right to rise with this subject,
and to express what might be presented for others, as well as myself,
on the unspeakable blessing of Divine preservation in a blessed growth in the Truth,
and an establishment in it unto the end.
He who loved us before we loved Him,
and of his mercy and power brought us out of darkness, sin, and corruption,
will not forsake us, if we do not turn our back upon Him;
but in the same lovingkindness and tender mercy, will warn of danger.
He will, as we submit and bear his dispensations, strip us from time to time,
of all we have known, plunge us into a sense of our nothingness,
and in this way keep us lowly and dependent, and enlarge our hearts,
and knowledge of Divine things.
The language of the beloved and aged apostle, "`Little children,
keep yourselves from idols,`" revived, with the liability man might be exposed to,
if he left a lowly watchful state, to idolize his natural talents, acquirements,
spiritual gifts, and religious experience; and getting lost as in a mist, Satan,
who can transform himself into the appearance of an angel of light,
may set him to work in things which the Lord never called him to do;
and finally the wrong spirit get into dominion in him,
which had in good measure been cast out.
I was opened and led, I believe, by the good hand into these things, for my own benefit,
and also as a renewed warning to some,
who had quite enough of the creature at work in them, under the garb of religion,
and promoting the kingdom of Christ.
It was of the Lord`'s goodness that the clothing of Divine charity was felt;
earnestly desiring the present and everlasting welfare of every one in the meeting.

28th. For several days my mind has been under fear, and some discouragement,
on account of the Society.
Some overzealous ones, who are more willing to talk than to suffer,
appear to have too little regard for the excellent
church government which the Lord instituted among us.
They do not rightly value the preservation of the Society, a united body;
but throw out opinions, that indicate too little sensibility, respecting separation;
as though it would be attended with little inconvenience,
and no disadvantageous consequence.
To me it is a source of deep sorrow, when I perceive men and women,
in stations in the Society, feel and talk in this manner.
Surely they know not what they do.
But at times, I have a secret hope that the Lord Almighty,
who raised us up a people for his honor, will mercifully hear and answer the prayers,
which He begets in the hearts, I trust, of many exercised servants;
and put a bit in the mouth of the enemy, who would destroy his heritage,
and turn him backward.
And when He sees our sufferings are, at this time, enough,
grant deliverance from the snare,
and renew our strength and courage to lift up the voice,
for the precious testimonies and doctrines, He raised Friends to support.
That so the dear young people may be comforted,
and strengthened to give up their names fully to serve the Lord;
and "`Instead of the thorn shall come up the fir tree, and instead of the briar,
shall come up the myrtle tree; and it shall be to the Lord for a name,
for an everlasting sign, that shall not be cut off.`"

29th. In answering the Queries at our Monthly Meeting, held this day,
there prevailed a uniting spirit,
under which more than a usual travail for one another`'s welfare, was felt;
and Friends were lively in speaking to the different subjects that came before us.
If the Lord would bring down all wrong things, and clothe us more entirely with his love,
so that without any dissimulation, we were one another`'s helpers,
it would be like balm to the wounded spirit,
and the bones which seem to have been broken, would rejoice.

Second month 3rd. Having passed some days with little sensible evidence of Divine good,
I went to the Quarterly Meeting for business much discouraged,
and with little hope that the quickening power of Christ would be felt by me.
Over the men`'s meeting, a feeling of renewed exercise was spread;
and I thought Samuel Bettle, Sr.,
was strengthened to call Friends back from the violations of our testimonies,
which not a few had fallen into,
by their conformity to the changeable fashions of the world.
They were calling plainness in dress and language, the reading of fictitious books,
and others calculated to poison the mind with unsound principles,
and to spoil it through philosophy and vain deceit, little things;
he believed the testimonies maintained by Friends respecting them,
were the fruits of primitive Christianity.
Departures from them created false taste; excited and unsettled the feelings;
and these led to the dislike of our silent meetings; and a desire to go where preaching,
and vocal or instrumental music, could be heard;
which men were induced to think they could use as the worship of Almighty God.
But it could have no effect, except on the animal feelings, to arouse and excite them.
He opened several of our testimonies,
and pleaded with the young people to prize the privileges which they had offered them,
in such a Society as ours, that watched over them for good.

My brother Thomas also spoke to several points, as well as some other Friends,
with which others united.
I thought it my place to say,
I hoped we should profit by the exercise spread over the meeting;
it was an evidence that He who raised us up had not forsaken us.
How fearful were we in the beginning of our heavenly journey,
of doing anything against the Truth; and how desirous to know the Divine will,
and to receive strength to do it.
Was there not now a danger, after experiencing a little prosperity,
of putting forth the hand, and appropriating the blessings of a kind Providence,
to purposes, of which we should have been afraid in those days;
especially in the furniture of our houses, and in our mode of living?
Entering into our own condition, and being favored to search Jerusalem with candles,
after having been so long contending against error without, and among others,
made this meeting additionally satisfactory,
and raised the hope that the Lord was beginning to work for and among us.

9th. First-day.
A low time, nearly throughout morning and afternoon.
Towards the latter part of the day,
there was a little sensation of Divine notice and regard,
by the merciful Shepherd of his afflicted people.
At the evening meeting, I was led to refer to the suggestion of some,
that the Society would go down; which I believed would not be permitted,
but through unfaithfulness and disregard of the many offers of Divine help.
"`There is a river the streams whereof shall make glad the city of God,
the holy places of the tabernacles of the Most High;`" the
sanctified hearts that have become temples of the Holy Ghost.
"`God is in the midst of her, she shall not be moved; God shall help her,
and that right early.`"

12th. At our meeting today, there was a larger attendance of children from two schools,
colored and white, than is common.
I felt the revival of concern for them,
and was led to warn them of the dangers and temptations that await them;
encouraging them to mind the convictions of the Holy Spirit in their own hearts;
to shun evil company, and to keep clear of profanity,
and of taking the Lord`'s name in their mouths improperly.

Went down to Woodbury in the afternoon,
and stopped at William and Mary Mickle`'s. We had
the agreeable company of a few Friends there;
and today, the 13th, attended their Quarterly Meeting.
I was engaged among them, to warn some of the deadening effects of the love of the world;
and to invite others to be obedient to the clear discoveries of the Divine will,
to some of whom, the language may be applicable,
"`Arise, shine; for your light is come, and the glory of the Lord has risen upon you.`"
Were those who are thus visited by the illuminations of the Spirit of Christ,
faithful to its requisitions, there would be raised among us, judges as at the first,
and counsellors as at the beginning;
and ministers to declare to others of the mercy and power of the Lord extended to them.
What loss individuals and the church sustain,
in consequence of disobedience and neglect of duty!

On the 15th, in company with our beloved friends S. and B. N.,
my wife and myself went to West-town School.
We attended their first-day meetings.
In the morning, I was led to open the doctrine of Divine preservation;
and to refer to the case of Joseph, whom his brethren, at one time,
appeared to be determined to destroy, but finally sold him to a company of Ishmaelites,
who sold him to the captain of Pharaoh`'s guard.
Here he was thrown into prison without just cause; and maintaining his integrity,
he was there kept by the Lord,
and qualified to interpret the dreams of Pharaoh`'s butler and baker;
and eventually to experience the fulfillment of the dreams he had in his youthful days;
by being made ruler in Egypt under Pharaoh.
Some present were tenderly entreated to keep the faith
and confidence in the Lord`'s preserving power,
they had been favored with, which would be their support and defense,
to the end as their eye was singly directed to Him.
The dear children were also affectionately persuaded,
to mind the warning voice of their dear Savior; by yielding to which,
they would be preserved from the insidious snares and allurements of a cruel enemy;
grow up in good liking before Him, and in his time be prepared for service in his church.

On second-day morning, the 17th, we rode over to Concord,
and attended the Quarterly Meeting of Ministers and Elders.

Third-day were at the Quarterly Meeting for discipline;
in which we both had some service, to our own relief, and, I hope,
the comfort and strength of others.
In the afternoon, the mail brought me a letter from my dear sister H. Rhoads,
dated the 6th and 7th of this month, at Croydon, near London;
conveying satisfactory accounts of her movements.
It was pleasant to find,
that amidst the trials attendant on the work in which she is engaged,
there are seasons of Divine consolation,
and evidences of the merciful regard of her Heavenly Father, strengthening her therein.

23rd. Throughout most of this day, I have felt little to cheer in the heavenly journey;
though in the morning meeting, I did not see I should do right,
without reviving the expressions of our Lord,
"`Except you eat the flesh of the Son of man, and drink his blood, you have no life in you;`"
"`He that eats my flesh, and drinks my blood, dwells in me and I in him;`"
endeavoring to set forth how little outside profession and appearance will do,
without the internal communion and participation of the life and substance.

Third month 2nd. First-day morning I was drawn to hold up to view,
that we are placed here in a state of probation;
to prove the Lord`'s love and mercy to us,
and to be proved whether we will obey his discoveries and requisitions,
and thereby glorify Him that created us, so as to be ready,
having on the wedding garment, to enter the everlasting abodes of blessedness;
in which I was somewhat encouraged.

10th. It is a period that calls for close watchfulness, and sincere prayer to the Lord,
that the spirit of division may not be permitted to lay the Society waste.
Those who advocate or enter into separation, know not what they do.
I believe it is a delusion; and were self baptized into death,
we would prefer suffering anything, but a sacrifice of our faith,
rather than break up the excellent order of church government,
which the Lord blessed the Society with, in the beginning; and which He placed around us,
as a hedge, and a defense of our testimonies against the inroads of the enemy,
and the allurements of the world.

21st. Our Meeting for Sufferings was held this day;
in which selections from authentic documents on the African slave trade,
made by a committee on the subject, were read;
and directions given to print in a pamphlet,
and disseminate it among the officers of the General and State Governments,
and the members of the different legislatures, as well as to others.
An epistle to the Meeting for Sufferings in London, was adopted,
and directed to be forwarded to that body.

23rd. First-day afternoon, I felt much for the poor in spirit;
the young visited ones who had but few to look up to like fathers and mothers in Christ,
and yet have to encounter the temptations of a watchful destroyer.
Also for those of further experience,
who are surrounded with discouraging views of the state of the Society,
and at times may be ready to give out and cast away their shield.
A little matter arose in my mind, as I thought for these different ones; and in weakness,
and fear of doing without right authority, or of leaving undone that which was a duty,
I arose, and matter was furnished which, though very small at first, expanded,
and I hope, contributed to the strength of some, as well as to my own encouragement.

30th. This has been a day of clouds.
What can poor, feeble man do for the visible church,
when conflicting spirits and views are arrayed against it?
He can do little more than pour out his feelings,
in sighs and groans that cannot be uttered in words; and strive to hope against hope,
and to keep hold of the least shred of faith that may be left,
that Divine mercy will not be withdrawn; but that in the hour of extremity,
He who is called the Everlasting Father and Prince of Peace,
will rend and disperse the clouds, and give rest to the weary spirit;
often tossed as with a tempest, and not comforted;
and bring us into a state of firmer unity, and purer love towards each other.
I had some satisfactory conversation with a Friend, respecting our Yearly Meeting,
and the spirit of division abroad in other parts of the Society.
We were united in the belief, that our place is to stand still,
and maintain the ground which we have taken, against unsound opinions and practices.

Fourth month 1st. Our beloved aged friend Sarah Churchman, being very unwell,
and doubts felt of her recovery, I went to Germantown, to see her daughters.
After sitting awhile at her house, I called to see Abraham Keyser,
now near ninety years old.
He spoke of his first attendance of Friends`' meetings on first day,
which were then mostly held in silence.
After he was convinced that it was his duty to join the Society,
he was satisfied it was right to go to the meeting in the middle of the week;
and he had not suffered his business to keep him from meeting, at any time since.
This is a good testimony, and what every true Friend, who lives and walks in the Truth,
will feel bound to keep faithfully to.
He also mentioned that while he was laboring under much mental exercise,
Thomas Scattergood came out to the meeting, and spoke as plainly to his state,
as if he had it all written down before him.
This settled him in the conviction of what it was right for him to do,
and he gave up to do it.

2nd. Today was our fourth-day meeting.
After a long silence, in which I had many fears of speaking,
I felt afraid to depart without reviving the expostulation of the Lord of the vineyard,
"`Why stand you here all the day idle?
Go also into the vineyard, and whatsoever is right, that shall you receive.`"
That there is a work for every one to do in the vineyard of his own heart,
which no man or woman can do for us, was held forth.
It is they who labor that receive wages, and gather fruit unto life eternal.
The weeds in the garden of our own heart are to be first eradicated,
that the ground may be prepared for the Seed of the kingdom to grow in it.
To be employed in finding fault with others, while our own hearts are unattended to,
and the work of sanctification and redemption not going on in us,
will be of no benefit to ourselves.
But whatever may be our trials and discouragements,
if we are faithful to the clear discoveries of the Divine will,
we shall lay up treasure in heaven; and keeping our lights burning and loins girded,
watching for the coming of the Master, He will in his time appear, spread a table for us,
and come forth and serve us.

6th. On first-day afternoon, the essential benefit of silent waiting upon the Lord,
in meeting and out of it, that our spiritual strength may be renewed,
and we kept alive in the Spirit, was opened, under a feeling of the quickening power;
and the humble, honest travailers for the circulation of Divine life,
were encouraged to hold on, keeping the faith,
and they would grow and deepen in the root.

8th. Went out to Grermantown to attend the burial of
our worthy friend and helper in the Lord,
Sarah Churchman.
"`Blessed are the dead that die in the Lord, from henceforth; yes, says the Spirit,
they rest from their labors, and their works follow them.`"

18th. Our Meeting for Sufferings convened this morning;
and among other subjects which received its attention,
was an interesting report from the Book Committee,
showing the sale and distribution of Friends`' books in the past year.
The demand appears to increase yearly;
and we may hope that the circulation of the sound gospel views which these books contain,
will be beneficial, especially to seeking minds.
More zeal and diligence in this good work are greatly needed.
We know not where conviction may be carried home by these writings;
and we ought therefore to spread them far and wide, among all classes.
A few pamphlets written by George Fox, brought from the north of England into London,
had a powerful influence upon many,
and no doubt opened the way for the ministers of the gospel who came to that city,
with a message of salvation, and who were favored to gather multitudes,
to the truth as it is in Jesus.

19th. The Yearly Meeting of Ministers and Elders was held this morning,
where we had the company of an unusual number of strangers from other Yearly Meetings.

21st. The general Yearly Meeting convened, and was a large collection of Friends.
Epistles from all the Yearly Meetings, except New England, were read,
and a committee appointed to prepare replies.
The Yearly Meeting closed on sixth-day noon.
It was held in much solemnity and order, and to the great comfort of Friends.
We had cause to return thanks to our Heavenly Father,
for his mercy and goodness in preserving us a united body;
laboring in harmony and the spirit of condescension;
which had not been so fully experienced for several years.
May it increase and rule among us in our future comings together.

My anticipations of this Yearly Meeting had been of a painful character;
and whether such feelings are permitted to humble,
and remove all confidence in everything but in the extension of Divine mercy and power,
for our deliverance, or not,
it was a great favor that those apprehensions were not realized;
but that the controlling power of the invisible Shepherd and Bishop of souls,
kept us in steadfast reliance upon Him.

30th. Our Monthly Meeting was held today, by appointment;
and having had revived on my mind, at different times, in the last two years,
a concern to visit some of the meetings of Indiana Yearly Meeting,
particularly on the western side of it,
although feelings of discouragement on account of the state of the Society attended,
I believed it best to lay it before Friends for their consideration and judgment.
They spoke pretty freely to it, and a certificate addressed to Friends,
expressive of the unity of the Monthly Meeting with me as a minister,
and with the concern, was prepared and directed to be signed by the clerk.

Fifth month 5th. This morning our dear friend Robert Smith departed this life.
He was a man of a chastened and pure spirit, and of dignified manner and deportment.
As he was a man of peace, very much subdued in his temper,
so he went down to the grave in peace; speaking of himself a little before the close,
with great modesty, yet giving proof, so far as he could be understood,
that his hope in the Lord`'s mercy and forgiveness, was as an anchor to his soul.
With a short sickness, and but little suffering, he passed away,
nearly eighty-one years old, to an inheritance, we humbly trust, that is incorruptible,
undefiled, and fades not away, eternal in the heavens.

The weather this morning was wet and chilling, and the Quarterly Meeting,
on the women`'s side of the house, was less than usual;
but I thought the men`'s a large meeting.
After the extracts from the Yearly Meeting minutes were read,
and recommended to the subordinate meetings, I mentioned the concern I was under,
to visit meetings in Indiana Yearly Meeting, from which, at times, I was ready to shrink;
but believed it right to submit it to the consideration and judgment of the meeting.
The weight and unity which appeared, I thought was more than usual; it was unlooked for,
and was received by me with gratitude.
A suitable minute was made,
and directed to be endorsed on the certificate of the Monthly Meeting.
There was a covering of solemnity over us throughout.

Sixth month 2nd. Yesterday and first-day week were seasons of Divine favor;
in which my Lord and Master enabled me to preach his gospel
with that authority which gave evidence it was not of man;
and I trust it found its way into the hearts of some goodly seeking ones,
and was a renewed call to some others.

On fourth-day last was our Monthly Meeting; in which my friend Joseph Elkinton informed,
that he felt drawn to accompany me in the proposed visit in Indiana Yearly Meeting;
which was united with, and I hope will prove a relief and comfort to me.

5th, Was at the Arch Street Meeting;
in which I felt my own weakness and unfitness to approach Him, who is immaculate purity.
As the time drew near for closing the meeting,
I remembered the prophet regarded himself as a man of unclean lips;
and that he was commissioned to hand forth the language of
encouragement to some among the degenerate children of Israel;
and his language, on one occasion, was brought before me, "`Comfort you, comfort you,
my people, says your God.
Speak comfortably to Jerusalem, and cry unto her that her warfare is accomplished;
that her iniquity is pardoned;
for she has received of the Lord`'s hand double for all her sins.`"
This was applied to those who submit to the Lord`'s fire in Zion,
and his furnace which is in Jerusalem.
When they have passed through the administration of his judgments,
the baptism of the Holy Ghost and fire, so as to have the filth purged away,
and to be no longer as reprobate silver;
they know all their iniquities pardoned through the blood of the everlasting covenant.

They are prepared to partake of the cup of suffering for the body`'s sake, the church;
which at times they seem to drink as to the dregs;
so that they may feel as if they received double for all their sins.
But it is all for a moment;
and when the blessed reward at the end of the race is granted,
it is no doubt felt as light affliction,
in comparison with the eternal weight of glory which the saints in light partake of.
The least and lowest place in his kingdom will be enough for the tribulated spirit.
I thought holy help was mercifully near, qualifying for a little service,
which would be the last before setting out on the proposed journey.
