== Chapter XXV

[.chapter-synopsis]
* 1851+++.+++ Religious visit to Meetings in Iowa, and other Meetings within Indiana Yearly Meeting.

1851, Sixth month 10th. Left home this morning, accompanied by my friend Joseph Elkinton,
under feelings of much nearness of affection and
solicitude for my dear wife and children,
and a deep seriousness at the extent of the prospect before me.
A visit to Iowa, and intermediate meetings, is an undertaking of importance,
and produces, at times,
sensations of sadness at the thought of the separation from my beloved family,
and the liability to sickness or accident, to which we may be exposed;
yet accompanied with the hope,
that the Lord`'s preserving power and goodness will go with us,
helping me through without hurting the cause of Christ;
and it may be to the comfort of some weary ones.
We rode to George Malin`'s, twenty-three miles, and dined with them,
where we were cordially received and sympathized with for the work before us.
Rode to Aaron Cooper`'s, in Sadsbury, before sunset,
where we were kindly entertained and lodged.

11th. The weather fine, we left our friends about seven o`'clock;
dined at a tavern two miles beyond Lancaster, rested two hours,
and by evening got to a tavern near York; having passed through Columbia,
and crossed the Susquehanna on a bridge, about one and a quarter miles long;
the distance forty miles.
Wrote home to inform our friends how we got along;
and being much fatigued went to bed early, and sleeping well, was much refreshed.

12th. We had a rough ride, after leaving York about three miles,
through several small towns, and in the afternoon,
crossed the South Mountain to the cold springs; where we found tolerable entertainment.
The temperature of the water, as it issues from the spring, we were told,
is forty-eight degrees, and when it gets to the baths, about fifty-one degrees.
They are resorted to by invalids from various places; and the use of the water,
and the exercise taken in the mountain atmosphere, are often very invigorating.

13th. Rose early in the morning, and rode eleven miles to breakfast, at Chambersburg;
from there over the Cove Mountain, to McConnelsburg, twenty-two miles.
It took about two and a half hours to cross the mountain,
from Loudon to the latter place; they are eight miles apart.
Rode to Reamer`'s, at the bottom of Sideling Hill.
This mountainous country presents scenery that is grand
and impressive to those who are not familiar with it.
The people in general, so far as we discover, live in a rough manner.
Some have good dwellings and farms,
but many appear to obtain barely the means of subsistence.
This was not an agreeable stopping place to us;
but we have been favored to travel with much satisfaction,
the weather being cool and dry.

14th. Rode over Sideling Hill to Snell`'s, six miles, and breakfasted;
from there up the Juniata River, eighteen miles, to Bedford.
The road along the river was good, the water on one hand, and the hills on the other,
of bold ascents; some of them presenting rocky fronts,
imparted a romantic character to the scenery,
softened by the flowing of the beautiful stream at our feet.
We were glad to find ourselves at Bedford about one o`'clock.

We rode to Dunning`'s Creek, the road rough and hilly.
In one place, where it had been dug on the side of a precipitous hill, it was so narrow,
that we thought it safest to lead the horses, as a little variation from the track,
might have precipitated us over a steep bank.
Our friends received and accommodated us kindly.

15th. Being first-day,
and notice having been spread of our intending to be at the meeting,
a larger number of persons assembled than is customary.
There seemed for some time but little of that religious exercise and feeling,
which ought to be found among true worshippers, in this gospel day;
and yet I believe the Shepherd of the sheep was not unmindful of us.

After sitting some time under a state of barrenness,
the importance of every one being daily engaged in the work of their own salvation,
came before me, with the intimation to stand on my feet;
and the way gradually opened to lay before them the nature and need of this work;
which is of more consequence than anything else in this world.
A degree of solemnity spread over us,
and some were brought into tenderness on the occasion.

Went to the house of a young Friend to dine, and in the afternoon,
had a religious opportunity with the children, and several others;
in which they were invited to increased dedication to the Lord, and his cause,
both for their own soul`'s sake, and for the sake of those around them.
Lodged at a Friend`'s, to whom, and his parents, our visit appeared to be acceptable,
and I trust comforting and cheering.

16th. He piloted us to Shellburgh, and put us in the way to get on, what they term,
the mud pike, which we supposed was made by throwing up the earth from each side,
to make a good clay road.
But our disappointment was great,
at finding ourselves upon one of the stoniest and roughest roads,
in this part of the country.
Rode about thirty-seven miles today.

17th. Rode to Lexington, from there crossing Laurel Hill,
we continued on over Chestnut Ridge, a high and tedious range,
and withal so stony and rough, that we feared our carriage would be broken.
It was indispensable, for the relief of the horses,
that we should walk over many of the hills; which made the journey laborious.
Within the last thirty years, much clearing of the forest has been done,
in some of these mountainous districts, and in fifty more, it is probable,
this will be made a beautiful and productive country,
as the means of the inhabitants increase, and the mode of farming is improved.
Large droves of cattle and flocks of sheep, are driven on these roads,
to the eastern markets, and the pasturage in summer, and the feed on grain in the fall,
afford a market for the farmers on the road.
After dining, we rode to Connelsville on the Youghiogheny River,
and from there to a place of private entertainment,
which afforded tolerable accommodation.

18th. Rose early, and made our way to Brownsville,
part of the way on the National turnpike, which was in good order,
and during the day travelled forty miles.

19th. Travelled the same distance, to St. Clairsville, in Ohio.

20th. Got to our friends B. and M. Hoyle, near Barnesville.
Here we were visited by several Friends, whose society and conversation were cheering.

21st. Got some repairing done to the carriage, and made some calls.

22nd. We attended the first-day meeting at Stillwater, which was a pretty large company.
We seemed to sit in a dry place, for a long time, under the feeling of which,
I feared the people were not sufficiently engaged in travail of soul for themselves,
but were looking to be fed or satisfied through others.
Such a state was spoken to,
and the indispensable need of this labor for their own salvation, pressed upon them.
The honest travelers were encouraged to keep to their Lord,
and to be faithful to their gifts, and they would finally receive a crown of life.
What avails the mere practice of coming to meeting,
and holding the principles of Christianity,
if we are swallowed up with worldly thoughts and pursuits,
and have forgotten the dew of our youth; going after the perishing things of time;
which I was afraid was the case with some.

In the afternoon, B. H. and wife, and J. B., accompanied us to a Friend`'s house,
near Smyrna, intending to pilot us to Owl Creek.
Here we were told that E. S. H., who had frequently appeared in the ministry,
spoke that morning for some time in their meeting, acceptably to Friends.
Soon after sitting down, he was taken with apoplexy, and about five o`'clock died.
This solemn event affected me, leading to serious reflections on the uncertainty of life;
but as I had left all that is dear to me, under the belief of religious duty,
I was kept from desponding of the mercy and protection of the Lord Almighty,
and endeavored to keep an eye to Him, and to the work before me.

23rd. Took leave of our dear friends, and rode to Coshocton;
parts of the road over mountainous hills, which made traveling tedious and wearisome.

24th. Having rested well, we drove on to Millwood;
most of the way on the banks of Whitewoman River and Owl Creek; the road good.
That night we got to a Friend`'s house in the settlement, near the meeting-house.

25th. Attended Alum Creek Preparative Meeting of Ministers and Elders held at this place;
in which I was led to make some observations on a case before it,
touching the care to be observed towards persons appearing as ministers;
both as to hastening their reception into these meetings, or in too long delaying it,
when Friends are satisfied that a gift in the ministry has been bestowed.
The discernment and sense which the Holy Spirit
gives to those who humbly wait for its guidance,
is the ground of right decision; and that is to be looked, for by those,
whose duty it is to judge in these cases.
It appeared to me, that the desire to fill the ranks of ministers and elders,
at this day, arising in part from the idea,
that the cause of Christ depends mainly for its support on much activity; and also,
it is to be feared, from a change of opinion, in not a few,
respecting inward spiritual religion and worship,
is involving the Society in great danger.

26th. After the Scriptures had been read this morning, by one of the parents,
I felt drawn to speak on the importance of rightly discharging their duty.
The need there is of watchfulness and prayer,
that they may be endued with wisdom to govern the children, and to example them,
so as to do nothing we would deem improper in them.
Like Abraham, to command our house, and our children after us, to keep the Divine law.
The children were reminded of the serious responsibility which attaches to them,
for the right occupancy of the measure of grace, purchased for them by the Savior;
and for the advantages of membership in the Society of Friends;
and they were affectionately invited to faithfulness to that precious gift,
and the improvement of the privileges they had.

Attended the Monthly Meeting; in the first meeting,
I was let down under a view of my own weakness, and unworthiness,
and I believe all ability for vocal service was withheld in Divine wisdom,
for my own sake, as well, it may be, as for others.
In that for discipline, after some Queries were answered,
I was led to advert to the nature of our testimony to silent worship,
and the spirituality of the gospel dispensation;
and endeavored to encourage Friends to maintain
right exercise in their religious meetings;
and though the number may be small, who are thus faithfully engaged,
yet the declaration of the Savior would be realized,
"`Where two or three are met together in my name, there am I in the midst of them.`"
In the afternoon, we rode to W. H.`'s, Jr., but the young man who undertook to pilot us,
having missed the way, part of which was through woods,
we did not arrive there until after dark.
The family received us very kindly, which was the more grateful,
as we had been under some uncertainty whether
they were the Friends we were inquiring for,
and whether we should succeed in finding their residence.

27th. Notice was sent over this morning to Weston, appointing a meeting at three p.m.;
which was held to some satisfaction,
though the number of exercised members appeared to be small.
It scorned to me, that Friends were in danger of substituting a verbal profession,
and activity in some benevolent objects, in place of that daily,
inward travail of soul for the bread and water of life,
which can alone keep it alive unto God,
and qualify to fill up the measure of service the Lord designed us for in the world,
and in the church.
I was impressed with the belief, that the Lord would send forth messengers,
as in the rise of the Society,
to gather the members back to practical obedience to the Light of Christ in the heart.
We took tea with A. S., and lodged at J. M.`'s, near neighbors,
who appeared to be sincere-hearted Friends, and glad of our company.

28th. Piloted by W. H., we rode to Gilead; and in the afternoon,
attended the Quarterly Meeting of Ministers and Elders.
I sat among them in emptiness; but towards the close,
felt engaged to hold up to their view the great
importance of the stations which they occupied,
both to themselves and to the flock.
There are dispensations meted out by the Head of the church, for our renewed humiliation,
to strip us of what we have been entrusted with,
to let us see and feel our own nothingness,
and to prepare for further service when He sees meet.
In this condition, we are to abide the Lord`'s time,
not daring to stir up or awake our Beloved until He pleases.
When we have waited his time, we come to know Him, by his quickening power,
to be unto us the resurrection and the life.
It is a great favor to be kept, from the beginning to the end of our heavenly pilgrimage,
in this lowly, travailing state, and to see greenness in old age.
It was to be feared,
that for lack of being willing to endure the baptisms of the Holy Spirit,
some have trusted in themselves and their early experiences, and have lost ground,
and not attained that establishment in the Truth which they would have been favored with,
had they continued as when in the child`'s state.
There are right hand as well as left hand errors,
and it is needful to guard against the insinuations of Satan,
who sometimes seeks to destroy the good work, by persuading that we are unfit for it;
even when the pointing of the Divine finger is felt, to engage in it.
But we are to lay hold of the degree of faith furnished;
and moving at the Lord`'s bidding, we shall know Him to be mouth and wisdom unto us.
I thought the little service made its way into
the hearts of some and opened them towards us.
After meeting, we accompanied our elderly friends, W. G. and his wife,
to their humble dwelling, where we were kindly entertained.

29th. First-day.
At Alum Creek Meeting; in which the doctrine of humility was held up to view,
as inculcated by our Savior, when the disciples had come to Him saying,
"`Who is the greatest in the kingdom of heaven;`"
and "`He called a little child unto Him,
and set him in the midst of them, and said, verily, I say unto you,
except you be converted, and become as little children,
you shall not enter into the kingdom of heaven.`"
And when the mother of Zebedee`'s children desired that her sons might sit,
one on his right hand and the other on his left, in his kingdom; He replied,
You know not what you ask;
and let them know that it was only to be given
to them for whom it was prepared of the Father.
The desire for eminence and notoriety, either in the world, or in the church,
cannot be indulged by the truly devoted follower of Christ.
His concern is, to be made and kept what the Lord would have him to be;
and if he perseveres steadily, he will be brought to see more and more clearly,
that his safety depends upon constant resignation and obedience to the Divine will.
I was very unusually and unlooked for, led to treat on this momentous subject;
and the meeting closed with prayer for the diffident, honest-hearted ones among them,
that they might be strengthened with might in the inner man,
to hold on their way faithfully; and for the young people,
that they might open their hearts to the King of glory.
Dined, and in the afternoon returned to Gilead.

30th. Was held Alum Creek Quarterly Meeting.
In the meeting for business, many spoke to the subjects brought before it.
After they were pretty much through the business, I felt drawn to revive the prediction,
"`In that day the Lord of hosts shall be for a crown of glory, and a diadem of beauty,
unto the residue of his people;
and for a spirit of judgment to him that sits in judgment,
and strength to them that turn the battle to the gate.`"
I observed, that if this prophecy is fulfilled at the present time,
it ought to be in our religious Society.
Our early Friends were brought off from all human dependence,
to wait on the Lord for ability to act in his cause and his church;
and they knew Him to preside among them,
and allot to his servants their respective portions of the labor.
One of them said, "`In Babylon there is the likeness of everything that is in Zion.`"
They saw the deception, and rejecting the mere image, they sought for the substance.
I felt afraid that some, even in the appearance of love and unity,
were in danger of mistaking the show of it for the reality,
which is only known by the truly baptized members of the church of Christ.
The young men, many of whom were possessed of good talents,
were invited to wait for Divine direction,
to enable them to take their proper places in the church; some to be mouth,
and others as ballast, to keep all steady; every one minding the Pilot,
that the bark may be guided safely.

Proposing to go into the women`'s meeting, a Friend was named to accompany me,
and the Master qualified me to preach the gospel of salvation by Christ,
to the young people; who were pleaded with to yield to the calls of his grace,
and come to Him.

Faithfulness in the discharge of their duties, was pressed upon the mothers,
that as far as in their power,
they may prepare the children to receive the Seed of the kingdom;
and that when the end came,
whether the children regarded the entreaties and exercise of their parents or not,
they may be clear; having the testimony of the Lord`'s spirit,
that they had done what they could.
It was a tendering time with some.
In the afternoon, rode eleven miles, and lodged.

Seventh month 1st. Rode forty miles to Lewisburg; and on the 2nd,
had an appointed meeting there; which was a season of favor,
some disconsolate ones being encouraged to resignation, and to believe that He,
who can bind up the brokenhearted, will remember them,
sanctify their afflictions to their benefit, and as they give up to Him,
will in his time, lift up their heads in hope.
An elderly woman Friend rose, and said with some fervor,
that she could set her seal to the truth of the testimony just borne.
Dined with H. W., and in the afternoon rode eleven miles to Goshen.

3rd. We had a pretty large meeting,
composed of persons who appeared to be much strangers to the inward life of religion;
which makes hard work for the poor servant, without obtaining much relief.
In the afternoon, we had another at Westland, about three miles distant.
The doctrine of salvation, through the coming of Christ in the flesh,
and by his Spirit in the heart, was enforced; and a dependence on a mere profession,
without this inward work of sanctification, was warned against.
The people were affectionately invited to come into the
living experience of this heart-changing work;
that being partakers of that saving faith, of which Christ is the author,
they may be made witnesses of his power and goodness, in setting them free from sin,
and bringing them into that state of perfection, which the gospel inculcates.
Divine help was extended, enabling me to relieve my mind and to depart in peace.

4th. Rode to Garmel.
The meeting was small.
After waiting some time, the language presented,
"`Blessed are they that hunger and thirst after righteousness, for they shall be filled.`"
I was enabled to speak to such a state,
recurring to the poor widow in the time of the famine,
who was gathering some sticks to bake for herself and her son, the last pittance of meal,
expecting to die after it was partaken of; but obeying the direction of the prophet,
to prepare a cake for him first, she experienced the supply to be continued,
until the Lord sent rain on the earth; and so it would be in a spiritual sense.
The obedient soul would not be suffered to perish;
but keeping the faith in those low seasons,
renewed supplies of heavenly bread would be furnished,
as it is patiently waited and labored for.
My mind was then turned to those who were full of business, in providing for the body,
neglecting the work of their salvation, living as without God in the world,
and striving to collect much about them.
But all their earthly possessions could not procure for them one crumb of heavenly bread,
or a drop of living water.
And what will they do when the pale messenger is sent to their habitation?
Prepared or unprepared, they must go to their everlasting reward.

Although it was distressing to enter into the condition of such worldlings,
yet it seemed right to warn them of their danger; and such were called upon,
if it was even the eleventh hour, to enter into the vineyard of their own hearts,
and labor to have everything removed that was choking the good seed,
and obstructing its taking root and growing there.

5th. Set out pretty early this morning, and rode forty-seven miles to West Branch,
in Miami county.
We dined, and fed our horses at a farm-house on the road,
but did not reach the Friend`'s house to which our guide took us, until sundown.

6th. Attended West Branch Meeting, being first-day.
The weather being wet, and no notice spread of our intention of being there,
the company was small.
The necessity of living in the fear of the Lord, in order to experience preservation,
was inculcated.
It is not beginning and running well for a time, that will do for the true christian,
but by dwelling in humility, asking preservation of the Lord,
and minding his warning voice when temptation is presented, that safety can be known.

Notice having been spread for a meeting at Mill Creek, at four o`'clock,
distant about four miles, we went there.
Found a company collected, few of whom were Friends, but they sat in a becoming manner.
It is a trial to be the means of convening those who are expecting words,
little acquainted with silent waiting on the Lord,
to receive ability to offer spiritual worship; but keeping still,
with a single eye to Him,
He qualified me to preach the gospel of life and salvation through Christ,
in his outward appearance in the prepared body,
and his spiritual manifestation in the heart, as the great Baptizer of his children;
bringing to remembrance many passages of scripture in
support of the practical efficacy of that religion,
of which He is the author, and will be the finisher, in the obedient soul.
It was to my admiration and the solemnizing of the people.
Thanksgiving for his mercy and condescension to us, poor unworthy creatures,
and prayer for continued preservation, were offered up to the Lord Almighty;
and I humbly hope, under the puttings forth of his Spirit.
We went home with W. D. J., who received and took care of us,
in a kind and affectionate manner; which is very grateful to travelers,
far from their connections and home friends.

7th. Stayed with this aged Friend to get our horses`' shoes attended to;
the top of the carriage painted; the dry, hot weather having cracked the paint,
so that it leaked; also to refit ourselves a little.
This Friend told us he was once a member of Bush River, in South Carolina;
and within a few years had travelled there in a wagon,
to bring away some colored people who had been freed from slavery; and in going,
they slept out in the woods most of the time.
He brought away three, with their certificates of manumission.
In a town of Kentucky, they were surrounded, he said, by thirty men, who, probably,
supposed the negroes were runaway slaves; but the proof of their legal freedom was such,
as to deter the men from stopping them.
I thought it was a striking instance of devotion to the cause of the injured African.
After his parents came into Ohio, then a wilderness country,
he was employed in wagoning produce to Cincinnati, on the Ohio River,
and bringing away store goods.
There being few or no bridges across the rivers, they had to ford them,
or to swim their horses and wagon through.

In the latter case, there being several teams in company, he said,
they tied down the body to the axle-trees, to prevent it from floating off;
and attaching six or eight horses to a wagon, with a rider to each span of horses,
they would swim the whole through the river, and in this way cross those streams.
It was their practice to lie out at night, carrying their food,
cooking utensils and bedding with them.
He stated that at one time, he was out,
when the snow was from one and a half to two feet deep;
in which with their loaded wagons,
they could make but from four and a half to eight miles a day.
When evening came, they selected a suitable place to encamp;
and after unharnessing and feeding the horses, leaving them to lie down in the snow,
they cleared a place for themselves, kindled a fire of bushes and small timber,
took their suppers around the fire, and then spreading out their bedding,
they lay with their feet to the fire,
the heavens and the earth being their covering and their bed.
He thought it was a very healthy way of sleeping.
When the weather was rainy and the ground wet, they cut branches and bushes,
to raise them from the water on the ground, and placed their bedding on them.
The Friend appeared to be a healthy, hardy old man.

8th. Had an appointed meeting at Concord; which was small;
chiefly made up of the few Friends residing there.
I endeavored to do what appeared to be required, but it was rather a laborious time.
Several Friends dined where we did, and the man being a large farmer,
we had conversation on the influence which much business has in
drawing the mind away from the great object of our creation;
preventing us from performing the duties which the Lord requires of us,
and filling the sphere He designs us to occupy,
so that we may become the salt of the earth and lights in the world.
The education of children in a guarded manner,
attending to the proper cultivation of their minds,
so as to prepare them for usefulness in the world, was enforced;
as well as the great importance of parents setting them
a right example by religious lives and conversation;
instances of the effect of which were mentioned.
One Friend present told my companion he thought
it was not lost time that had been spent there.
Went to J. C.`'s, about six and a half miles; not far from Uniontown.

9th. Attended Union Meeting, being the Preparative Meeting, which was large.
The state of some, whose faith was closely proved, was impressed on me;
and after waiting for a time, under the fear of over-acting,
or suffering the meeting to pass without doing what I ought, I rose with the expressions,
"`Many are the afflictions of the righteous,
but the Lord delivers him out of them all,`" and
dwelt on the benefits derived from our trials.
"`Whom the Lord loves He chastens, and scourges every son that He receives.`"
After entering into the necessity of these dispensations,
for man`'s refinement and preservation,
I was led to those who knew nothing of these chastenings; who were without their changes,
and were living in ease and indifference; and those who are without chastisement,
are not the sons and daughters of the Lord.
Many of these go into the earth, and are covered as with thick clay;
so that they are in danger of entirely losing the tenderness
and sensibility which they knew in the days of their youth.
It appeared to me, that the inordinate pursuit of the things of the world,
had brought a cloud over our religious Society,
as well as over other parts of Christendom generally.
We were planted a noble vine, wholly a right seed, in the beginning;
but were now in danger of becoming the degenerate plant of a strange vine.
Some were solemnly warned of the consequences of worshipping Mammon,
and reminded of the testimony of Christ, that we cannot serve God and Mammon;
and of all that we can collect of this world`'s goods, we can carry nothing out with us.

I was enabled to declare the truth in the authority thereof,
expostulating with the worldly professors,
and in entreating the young people to serve the Lord.
Two Friends confirmed what had been said.

After the meeting we went to the house of a Friend,
where we remained until the following morning,
and found his home an agreeable stopping place;
there appearing to be more mental culture in his family than in some others,
judging from their reading and deportment.
Where we meet with those who are religiously exercised,
however simple their habits may be, our hearts are united to such, and their humility,
and the innocency of their spirits, render their society agreeable.

10th. Was at Lick Branch, which was small, owing in part to its being harvest time,
and the weather frequently wet, so as to make getting their grain housed,
very precarious.
It was a good meeting to me, and to some others.
One elderly Friend said he was glad I was there.
Lodged at J. H.`'s, who, with his wife, appear to be concerned Friends.
They expressed their gladness of our visit.

11th. We took an affectionate leave of our friends, and rode five miles to South Fork,
where we held an appointed meeting; chiefly made up of persons not members,
and a few Friends part of them from other places.
It was not a very animating time to me, though some manifested their satisfaction,
for whose strength and preservation intercession had been made to the Father of mercies.
This evening a Friend came from Lick Branch, to pilot us to New Garden.

12th. Set out pretty early for New Garden, in Indiana.
Some parts of the way being flat,
and the ground peculiarly liable to be cut in
very deeply by traveling on it in wet weather,
the inhabitants have been in the practice of covering them in some places, with logs,
not hewed, which makes extremely rough riding.
We reached F. T.`'s a little before sundown, and were frankly received;
I having been there about eight years before.
We found him an intelligent Friend,
concerned for the maintenance of our religious principles;
and he appeared to be alive in the Truth.
I felt much distressed on entering Indiana, not knowing how we should get along,
yet desiring to be Divinely guided in the way the Lord would have me to go.

13th. Attended New Garden Meeting in the morning;
to which I walked in the feeling of great poverty,
yet in hope we should meet with a body of lively, spiritual worshippers,
with whom we could take comfort.
In sitting with them, the life of religion was felt to be low;
but after a time of struggling after good,
it appeared right to address the language of encouragement to
those who were sensible of their condition,
and oppressed with the indifference around them.
Then the state of these worldly ones, coming before me,
warning and entreaty were extended to them.
I left the meeting under feelings of depression, thinking that little good had been done;
but I endeavored to keep patient and resigned.
In the afternoon, we had a meeting at Newport, about a mile distant;
where we found a number of Friends, who appeared to be tender-spirited,
and with whom I had a relieving opportunity,
and parted from some of them with feelings of interest and affectionate regard.
We rode that evening to W. B.`'s, at Lynn, accompanied by two agreeable, kind Friends.

14th. Had an appointed meeting at Lynn, which was largely attended;
I thought by some who were seeking after good;
to whom I was enabled to minister in the openings of the Holy Spirit;
and to hold up to some, who had entered into covenant in their early setting out,
that if the Lord would give them bread to eat and raiment to put on,
He should be their God, and they would serve Him,
that now having increased in their estates,
they were in danger of being caught with the snare of the fowler,
and to love their possessions, instead of the great Giver.
But He was watching over them, and secretly warning them;
and they were exhorted to go to Bethel, like Jacob, and renew their covenants,
that they may be delivered from the snare,
and be preserved from losing their standing in the Truth.
I was thankful for the supply of matter,
and the ability to communicate it in the gentleness of Christ.
There appeared to be a tender feeling produced in some, who I hope, were comforted.

Returned to W. B.`'s, dined, and remained here to attend the burial of a woman Friend.
The company went into the meeting-house; and I felt drawn to labor to impress on them,
the solemnity of such events, and the necessity of laying them to heart,
that each one may be prepared for the close of life when it comes to them.
But how easily do such impressions pass away!
The indifference shown by many, to the subjects of religion,
and the importance of preparing for death, is very distressing;
and almost induces the thought,
that little benefit results from all the labor we pass through.

15th. Rode over this morning to Cherry Grove, where we had an appointed meeting;
in which I was enabled to set forth the nature of spiritual worship,
which stands in communion with the Father and Son;
not only when assembled to perform the duty publicly,
but also in daily waiting upon the Lord for the renewal of our strength.
The inward work of religion is greatly lost sight of by many among us;
and the testimony of our early Friends, that the professors of their day,
acknowledged some of the truths of the gospel, while they lived as they listed;
and how Friends were brought to forsake all, and wait upon the Lord,
by which they were enabled to hold up the ancient gospel in life and precept,
were opened in this meeting.
Friends were called upon to examine,
whether there was not a danger of going back
into the condition of those formal professors,
instead of advancing in the spiritual and Divine life.
They were pleaded with, in the love and gentleness of Christ,
to search into their condition, and come back into the inward, daily waiting upon,
and communion with God, for the renewal of their strength,
by the bread and water of life, which come from Him.
It was a day of favor, and the truths delivered could not be gainsayed.
A Friend piloted us to Economy.

16th. Attended Springfield Preparative Meeting, held at Economy.
Notice of our being in the neighborhood having been spread, some strangers came in,
and I had rather a laborious time,
in opening the doctrine of obedience to the Divine will, revealed in the heart,
as the ground of preparation for acceptance with God;
and the way by which the work of sanctification is carried forward,
and we become acknowledged by Christ, as He owned his disciples;
"`Whosoever shall do the will of my Father, which is in heaven, the same is my brother,
and sister, and mother.`"
Afterwards I was brought to bend the knee in prayer for the poor in spirit;
for the rebellious, whose souls are also precious, and for the dear young people.
I hoped the truth gained some entrance; but oh,
the lifelessness of very many who go under our name.
We dined in the village, with a doctor and his wife, who were very kind,
and in the afternoon, piloted us twelve miles to Flat Rock.
At the first house where we stopped, and had expected to put up,
we found they had scarlet fever; and thinking it not proper to add to their cares,
or to expose ourselves to the liability of taking the disease,
we went to a neighbor`'s who took us in.

17th. Attended Flat Rock Preparative Meeting; in which for a time,
it seemed to me there was so little life among them,
that I thought I had scarcely experienced such feelings of discouragement.
But finally it appeared necessary to sound an alarm among them,
and leave them to the Lord.
This afternoon it rained and blew hard, with lightning and thunder, very heavy;
but being desirous of getting on our journey, we set off,
and got to the house of a Friend, near Spiceland,
about dusk where we were refreshed by the kind entertainment of his family.

18th. This morning we were piloted to the National road, and then set out,
without a guide, westward.
The road was softened by the rain, which made the traveling heavy,
until we reached the plank road, east of Greenfield.
We were disappointed in the appearance of the country, which was but little improved,
in many parts, and to us, presented rather a dreary aspect.
Dined, and fed our horses at this village; and after suitable rest,
set out on the plank road; over which we moved faster than we were aware,
so that we got to Indianapolis before six o`'clock.
Here we received letters from home which were cheering,
giving good accounts of the health of my family.
It appearing too early to put up for the night, we went on and stopped near Bridgeport,
and lodged.

19th. Rode to Plainfield, and dined, then went to E. W. H.`'s,
who had been at my house a few years since, with J. H.,
then on a religious visit in our city.
It was pleasant to see him in his own habitation, where we were comfortably accommodated;
he and his wife being Friends of religious experience.

20th. Attended Spring Meeting, to which they belong; which was a pretty large collection,
but noisy and unsettled, by fretful children, and persons running out and in.
It was a laborious time,
but little entrance seeming to be made into the hearts of the people.
We went home with A. H., and stayed with him, and his kind attentive daughters,
until the next morning.
It was a house, where I thought the Son of Peace was to be found.

In the afternoon, our friends E. W. and C. H., came over to see us,
with whom we passed the time in agreeable converse.
The country here has been heavily timbered; so that some farms surrounded by the forest,
seemed to be enclosed with wooden walls; obstructing any distant prospect,
especially where the surface is pretty flat; and, consequently, creating in a stranger,
the feeling of loneliness; there being little or no improvement within view,
beyond the farm we may be on.

21st. A religious young man having offered to accompany us to Rockville, in Park county,
we set out, and rode to a suitable place for dining, and feeding the horses.
The weather being cool, it made traveling pleasant; the road pretty good,
except where they had covered it with logs over wet, flat land.

Our stopping-place was a house of private entertainment, the residence of a farmer,
where they had plenty of wholesome provision,
and he served us with politeness and respect.
"`We reached S. A.`'s, near sunset, having travelled about forty-one miles.
He and his wife received us very frankly.
We had conversation with him, respecting the traveling through Illinois,
and found that at this season of the year, he apprehended there would be no difficulty;
and he offered to accompany us the next afternoon to the Vermillion settlement,
on the west side of the Wabash River; which we gladly accepted.
We were now getting very many miles from our beloved families and homes,
and the prospect of soon entering upon the prairies,
brought over me sensations of loneliness, as I walked out into the woods,
and there recurred to the countenances of those I held most dear to me in this world;
and to the risk of accident and disease, to which we might be exposed.
But there was a secret support,
and a trust raised in the merciful and compassionate Shepherd,
who sees us wherever we are; and as we have nothing in view but to do his will,
He will renew our faith, and defend and carry through all, to his honor and praise,
and our sweet peace.

22nd. This afternoon we crossed the Wabash River in a scow,
where we saw evidence of a recent freshet, which had spread over the flats; and,
we understood, had made crossing very difficult.
A few miles from the river we came to an arm of one of the great prairies.
Viewing the expanse appeared like looking out to sea;
there being no object in the distance to rest the eye on, for miles, but grass.
The thought of being out on such an extensive plain, which seemed to have no limit,
and the possibility of missing our way, was rather dreary.
Towards evening, we got to W. H.`'s, within the limits of Hopewell Meeting.

23rd. Attended their Preparative Meeting;
in which I was brought into sympathy with some tried ones,
who had difficulties to contend with; and was favored to speak,
in the humbling openings of the Holy Spirit, as I believed, to the states of such.
I was also led to call on some others,
to examine whether they had the same tender feelings and desires,
to walk in obedience to the manifested will of God,
which they felt in the days of their early beginnings;
or whether the enemy was not working as behind a screen,
to immerse them in the pursuit of the world,
and thereby destroy their growth in the life of righteousness.
I was thankful for the Lord`'s condescending regard to me, a poor creature.
I thought their answers to the Queries were prepared in a suitable manner,
on those subjects, and was comforted with the meeting.

24th. Attended Vermillion Meeting.
Notice having been spread, a pretty large company collected.
It appeared right to hold up to them the distinction
between works of benevolence and kindness,
which unregenerate man can perform,
and a submission to the baptism of the Holy Ghost and fire, by which man is made free,
and kept free from the spots of the world.
Divine help was present, qualifying to enforce the necessity of this spiritual,
inward work,
as the only way by which we shall come to the
knowledge of God and of his Son Jesus Christ,
which is life eternal.

Dined at I. S.`'s, and found it a pleasant stopping-place;
his wife appearing to be a mother in Israel.
In the afternoon, we rode through the prairies four and a half miles, to Pilot Grove;
so called from its being seen across the flat country, several miles,
from certain points, and serving as a beacon to travelers to steer their course by.
Here we had a pretty large meeting of Friends and others;
to whom was set forth the fruits of the religion of Christ;
in subduing and regulating the passions and evil propensities of fallen man;
and the blessed results of kindness and tenderness for one another,
and the purity and righteousness, which are produced by religion, were shown to them.
The people generally seemed to be such as needed to be
taught the first principles of the gospel of Christ.
The weather was extremely warm and oppressive, which exhausted me much;
but it was a comfort to have the day`'s work peacefully accomplished.
We stopped a short time near a Friend`'s house, who, with his wife,
proposing to accompany us, had to call at home before setting out;
we then rode seven miles to Ellwood, where we lodged.

25th. We had an appointed meeting here; which was quite large on the men`'s side.
After a season of patient waiting, the Lord gave ability to open the doctrine of Friends,
on the subject of Divine worship; the necessity for all to be gathered,
when thus assembled, into a humble, inward waiting for Christ;
to know Him to prepare our offerings; which, if only a broken heart,
and a contrite spirit, will be regarded by our Heavenly Father.
These humble, struggling ones, will be at times baptized by one Spirit into one body,
and made to drink into one Spirit;
and if two of them shall agree touching anything they shall ask, in the name of Christ,
it shall be done for them, said our Lord, by my Father;
for "`where two or three are met together in my name, there am I in the midst of them.`"
The discouraged and mournful ones were exhorted to keep the faith, and to struggle on,
and they will be helped, and see of the travail of their soul.
I thought the hearts of some were comforted;
and the meeting was closed with prayer for Divine support and preservation;
and for the renewal of the faith of the lowly ones; and for the dear young people,
that the Lord would visit them by his blessed Spirit,
and defend them from the power of temptation;
that there may be a band raised up to support our principles and testimonies.
We dined with two Friends who had removed from Ohio and now lived near this meeting;
and in the afternoon were conducted to L. D.`'s, near Georgetown.

26th. This morning we set out on our lonely journey across the State of Illinois,
and were shown over some prairie land to the western road, at Butler`'s Point, by L. D.;
where we parted from him, and pursued the most open track.
Through the morning, we got along pleasantly; the road being generally plain and good;
dined at a poor tavern, in a village called Homer.

After giving the horses proper rest, rode through a strip of woods;
crossed the Big Vermillion Creek twice, once on a bridge and once we forded it;
and in the prairie, which we then entered, we had several sloughs to go through,
where the draft is hard for the horses.
When coming to those soft, muddy places,
it is usual to turn towards the head of the marsh, and drive on the high grass,
which keeps the carriage and horses from miring;
and thus they get round the deepest and most swampy part.
This seemed very uncertain work to us, being entire strangers to such traveling;
in a boggy country, where we cannot discover to what depth we may sink; and where,
at times, the horses had to put forth great effort to draw us through.
After crossing that piece of prairie, we stopped at the first house; and while there,
a man came up with a cart and pair of oxen,
and soon inquired how we had got through the sloughs; saying,
he supposed that he had drawn with his oxen, fifty vehicles out of them, this spring.
We were not aware of our danger of being set fast,
this being our first day`'s travel alone there.
Going on our way, we felt our lonely situation, exposed to difficulties,
when no house might be within several miles; but endeavored to do the best we could,
and put our trust in our Heavenly Father; in the belief we were in the way of our duty,
and He would enable us to go through.
Reached Urbana by sundown, having ridden about thirty-seven miles;
and put up at a good tavern; kept by an Ohio man, who treated us respectfully,
and provided well for us.

27th. We left soon after breakfast; at once entering a prairie,
in which the road was good; forded the Sangamon Creek, at a piece of woods;
a clear beautiful stream.
On coming out of the timber, we entered a prairie, said to be fourteen miles over; which,
in some directions was like looking over an ocean of grass;
nothing to be seen in the horizon.
We made slow progress; some of the surface being rolling, and others marshy,
which we crossed, with considerable effort on the part of the horses;
and a little after twelve o`'clock, reached an inn on the western edge of the prairie;
a good deal overcome with the heat.
By driving slowly the horses bore it very well; but the sun shining with great fervor,
and it being first-day, we were best satisfied to remain at the tavern,
until the next day, which would afford us rest.

It was distressing to find the low condition of many,
in relation to their religious and moral obligations.
Foolish jesting and idle conversation fill up much of their time.
They are idle in their habits and disregard the duty of public worship.
To be compelled to mingle with persons of little education,
and rather low standing in other respects, is a trial we have to submit to,
in some of these places of public entertainment;
and it requires care to avoid joining in with their frothy conversation,
or in any way strengthening them, in their irreligious feelings and habits.
Our sobriety, at least, should bear a testimony to the excellency of our holy,
undefiled religion, and against their loose spirits and practices.

28th. Rose pretty early,
and got our landlord to take his horse and lead us round through the grass,
where there was no road, to avoid getting swamped in some bad sloughs, which, he told us,
lay between his house and the next village.
It was quite a relief, and we got to breakfast at Le Roi, thirteen miles;
dined at Bloomington, and supped and lodged at Concord, forty-one miles altogether;
a poor place for entertainment.
Here we made inquiry of two men,
at which ferry on the Illinois River we had better cross; but they differed in opinion;
both, however,
giving very discouraging accounts of the state of the roads near the river,
so that we were much at a loss to decide.

29th. Rain fell in the night, and the road was muddy, and the morning very dull.
Rode to Lilly`'s, six miles, and roused them up to get us breakfast.
Dined at Groveland,
where we met with a young man who had crossed the Illinois River this morning,
and who gave us an accurate description of the course we must take,
when coming in sight of the river.
After dining, we travelled about eight miles to a bridge,
which had been partly swept away by a great flood this spring;
and had we not been furnished with explicit directions, it did not appear probable,
we should have driven safely through the terrible sloughs,
or avoided the impassable places; in which we were told travelers had become swamped,
and broken their carriages; from whom, exorbitant sums had been extorted,
by men concealed there, to be called on in such emergencies.
When we arrived there, we saw horses saddled, and wagons standing,
but no one in view except a boy, looking out of the bushes,
as though he had been placed there to watch if any one should get into difficulty.
It seemed like wreckers looking out for plunder; and I considered it providential,
we had met with a person who could direct us how to act,
so that we were enabled to follow a track, which took us safely through,
though in miry and deep holes, and led to the water edge;
and that we reached the boat safely,
after driving into the river perhaps sixty or one hundred feet.
We landed at Peoria; rode through the town, and obtaining directions,
got to a brick tavern, six miles farther on,
where we were pretty comfortably entertained.

30th. Set out about half-past four in the morning, and breakfasted at Travoli,
twelve miles; dined at Fairview, sixteen miles; the road wet,
and in some places cut into deep holes.
Rode eight miles to Spoon River; crossed it in a flat,
which was short for the wagon and horses; but we got over safely.
The ferrymen on these rivers are mostly rude and profane.
It was affecting to hear their bad language; giving the impression,
that they are regardless of religion, and the necessity of the work of salvation.
Rode to a place called Virgil, about five miles;
where we were pretty comfortably accommodated.

31st. Set out early this morning with the assurance that the road was good;
but we found it far otherwise.
The small bridges were in bad condition,
and many of the marshy places were difficult for the horses to draw through.
On a prairie ten miles over, there was a space two miles wide, we were told,
very much covered with water, and no road visible in many places,
so that we could not be certain we were in the right track; but, by the compass,
we kept a west course, and finally got through the swampy ground, into a plain road,
much to our relief.
We procured tea and bread and meat, at one of the log cabins on the prairie,
but were so long detained, that we did not reach La Harpe, until near supper time.
We met two carriages, just as we entered the swamp,
and asking the men what kind of road ahead, they replied, "`As bad as it can be.`"
Our horses had a hard draft, through the mud and high grass;
and if any accident had happened us, we should have been in great difficulty,
as there was no house within several miles.
It was cause of gratitude, that we were favored to escape in safety,
from such a dreary place; where we could not see what we were driving into,
whether holes or inextricable sloughs.
Lodged at La Harpe.

Eighth month 1st. Rose early and got to Pontousac, fourteen miles;
on the river Mississippi; where we were furnished with a good breakfast,
and then rode six miles to the ferry opposite Fort Madison, in Iowa.
The ferrymen detained us several hours, on the bank,
waiting their time to cross the great stream.
We regretted the loss of time,
as we wanted to reach a settlement of Friends this afternoon, but could not; and,
getting directions in Madison, we went five miles to a farmer`'s,
and found some difficulty in prevailing on the people to take us in;
we supposed from what passed, on account of the cholera, of which, we were informed,
there had been several deaths in Madison; but finally they consented;
and except the lodging, we were made pretty comfortable.

2nd. After breakfast we travelled about eighteen miles to J. B. H.`'s, at East Grove,
and put up with him and his wife, who were truly kind to us.

3rd. Being first-day we attended New Garden meeting, four miles distant, in the morning;
where we met with some Canada Friends at whose house we had stayed when in that country.
They were truly glad to see us in this western land.
O+++.+++ S., an elderly man, also from Canada, but now belonging to Salem, was here,
and said a little after me; enforcing the doctrines delivered.
In the afternoon had an appointed meeting at East Grove.
In both these holy help was extended, enabling me to preach the Word to the people;
several of whom showed their unity,
by the cordial manner of greeting us after the opportunities.

4th. Rode to Salem; where our horses were left, in order to rest and recruit;
one having been lamed.
Others were attached to our carriage, and J. P. drove us out to Chestnut Hill,
where we had an appointed meeting;
to which was brought the largest number of infants that
I think I ever saw in a meeting of the same size.
Returned to Salem and lodged at J. H.`'s.

5th. We were taken out to Cedar Meeting, which was a large company,
who sat in a sober manner,
but I felt for a long time as if we might hold the meeting in silence;
remembering the advice of the apostle, "`That they should seek the Lord,
if haply they might feel after Him, and find Him,
though He be not far from every one of us; for in Him we live, and move,
and have our being.`"
The way was finally opened,
for showing that this was the object of our thus assembling together;
not to deliver lectures, nor to hear them delivered;
for no man can do anything to promote his own salvation, or that of others,
independent of Divine aid.
Our business is to gather to Christ, that we may know Him to minister to our condition.
Afterwards the necessity of the new birth was opened,
and of being clothed with the righteousness of Christ;
which He brings forth in us by the effectual workings of his Spirit; and of our final,
complete justification by the washing away and pardoning of our sins by his blood.
The effect of the doctrines preached, must be left to the Lord;
but I believe there were those present who drank in and united with them.
Dined at S. H.`'s, near the meetinghouse,
and after a religious opportunity with his family and some others, we rode to J. P.`'s,
who resides about half a mile out of Salem.

6th. This morning a Friend attached his horses to our carriage,
and set out with us for Richland;
which is about thirty-five miles northwesterly from Salem.
When about eight miles short of the town, he drove into a deep prairie slough, of tough,
black mud, nearly up to the hubs of the front wheels, and in endeavoring to draw it out,
the force of the horses broke one of the swingle-trees,
without removing the carriage from the slough.

We then fastened a rope and straps to the axletree, and hitched the traces to them,
and had the horses been true to the draft, they would, we thought, have drawn it out;
but they threw themselves into another hole, and finally broke the tongue.
It was mortifying, after having travelled so many hundred miles,
without any material difficulty, to have our carriage thus broken;
and to be placed where we could not extricate ourselves about three miles from any house,
and evening coming upon us.
Had not a man and his wife, the latter a Friend, whom we had seen at Cedar,
come in sight, we must have been obliged to leave our carriage,
and walk a considerable distance, before getting under any roof.
Their coming seemed quite providential,
as they had intended to remain two or three days on a visit to their friends;
but the wife mentioning to her husband a desire to be at their Monthly Meeting,
he assented to it, and they set out the same day with ourselves.
He secured our carriage to the hind axletree of his wagon, and having good horses,
when we had pried up the wheels, to loosen them from the mud,
they drew the carriage out with ease.
The Friend with us mounted one of his horses, Joseph got into the wagon,
and I was seated in our carriage,
and between nine and ten o`'clock we reached J. H.`'s. It was cause of gratitude to
our Heavenly Father that we were thus brought safely to the house of kind friends.
We expressed our gratitude to the man, and our desire to compensate him,
but he was glad to be the means of rendering us such acceptable service.

7th. Attended Richland Monthly Meeting,
which had been lately established as a Monthly Meeting, and was a pretty large company.
I felt low and discouraged; far from home, and among strangers of various character;
but after a woman Friend had spoken, the language was brought before me,
"`The foundation of God stands sure, having this seal,
the Lord knows them that are his;`" and waiting in fear before Him,
I believed it right to revive it,
and to show that whatever may be the trials of the faithful,
those who are built on this foundation, are known of the Lord,
and will experience his sustaining power to be underneath.
I had to treat on the importance of keeping with Christ in his temptations;
being willing to suffer with Him, as the Seed in the hearts of the children of men,
both for our own humiliation, and for the sake of others.
I believe the humbling power of Christ was over the meeting,
and touched the hearts of some.
Friends conducted their business in a solid manner, which was a comfort to me,
as they had held but few meetings before; having been set off from Pleasant Plain.
We stayed another night at J. H.`'s.

8th. Notice having been given for a meeting at Rocky Run, four miles distant,
to be held at nine o`'clock; and our carriage being repaired,
we set off and had a satisfactory time with Friends and others, who met there;
chiefly in the way of encouraging the sincere ones, to be faithful to their Lord;
by which they would prove that godliness is profitable to all things,
having promise of the life that now is, and of that which is to come;
keeping the duties of religion uppermost,
and the things of the world in their proper place.
Here substantial happiness is enjoyed, by walking with God in this life,
and when the end comes, the full fruition of it in the world to come.
Went to a Friend`'s house near by,
where we were comforted with the appearance of the children,
and a feeling of peacefulness.
After leaving we rode to Pleasant Plain, over a rough road, washed in many places,
and attended a Select Preparative Meeting.
Went to J. A.`'s; a pleasant stopping place.

9th. Attended Pleasant Plain Monthly Meeting, throughout which I was silent,
until just at the close of that for business.
The Friends where we lodged treated us very kindly,
and we felt it a comfort to be thus cared for, when far from home.

10th. We went to meeting this morning.
I endeavored to keep inward, with my eye to the Lord alone, and after some silence,
the expressions of our Lord in his address to the Father were presented to my mind:
"`And this is life eternal, that they might know you, the only true God,
and Jesus Christ whom you have sent,`" attended by the impression to rise with them;
and I was enabled to preach the gospel in Divine authority;
that this saving knowledge of God and of his dear Son,
is only received through the revelation and operation of his Spirit, in the heart of man.
Our Lord declared that, "`Except a man be born again, he cannot see the kingdom of God.`"
No one can give himself a true sense and sight of his condition, as he stands in the fall.
It is the Lord from heaven, the quickening Spirit, who is the resurrection and the life,
that alone can quicken man, and make him rightly feel his lost and sinful state.
As man submits to Him, He opens the blind eye,
enabling him to see himself in the true light; gives him the power to turn from sin;
to repent of his past evil deeds; destroys the kingdom of Satan in him,
and sets up his own everlasting kingdom in place of it.
It is thus man is brought to see the kingdom of God, being made a new creature;
old things are done away, and all things are made new.
The new heavens and the new earth, wherein dwells righteousness, are brought forth in him.
In this heart-changing work, he livingly knows God and Christ,
by the powerfully redeeming and sanctifying operations of the Holy Spirit.
This is the knowledge that is life eternal to the soul.
Some of the exercises which the redeemed soul passes through,
in its heavenly pilgrimage were further opened; and the meeting closed with humble,
reverent prayer to the Lord, for his continued mercy and preservation,
in the trials to which we are subjected,
and wherein Satan seeks to destroy the blessed work which the Lord had begun in us.
It was a solid time; and we returned to our lodgings,
humbled and thankful that the Lord had owned his cause.

11th. Before leaving our comfortable sojourning place,
we had a little opportunity with the parents and children; in which they were reminded,
that here we have no continuing city,
and of the importance of seeking one that is to come; laying up treasure in heaven.
The children were entreated to mind the convictions of the Spirit of Christ,
that they may be preserved from temptation,
and become what the Lord would have them to be; and in conclusion, with tender feelings,
I was led to express the desire, that the blessing which makes truly rich,
may rest on the heads of the parents, and upon their beloved offspring;
which had a melting effect on all of us.
After taking an affectionate leave, we set off for Salem;
where we arrived in the latter part of the afternoon,
some parts of the road being very bad.
It was pleasant to take up our residence again at our friend J. P.`'s.
