== Chapter XXVI

1851

Continuation of Visit in Iowa, etc.

1851, Eighth month 12th. Was held a Select Preparative Meeting at this place;
in which I was drawn to speak of the authority
and qualification for true gospel ministry.
That every one who had received the gift, was to speak as the oracles of God,
and to minister the same in the ability that God gives;
and no man takes this honor unto himself, except he be called of God, as was Aaron.

13th. Attended the Monthly Meeting here, in which I was silent,
except a few remarks in that for discipline.

14th. Went to East Grove Monthly Meeting; the forepart of which was silent.
In the latter,
I said a little on home education--the necessity
of restraining the children from wrong things.
When the meeting had gone through the business,
I was led to hold forth the language of encouragement to some exercised ones;
and to persuade those who had not submitted to the restraints of the cross,
to yield to Him who is represented as a refiner`'s fire and as a fuller with soap,
that they may partake of the blessed result, as described in the prophetic address:
"`Comfort you, comfort you, my people, says your God.
Speak you comfortably to Jerusalem, and cry unto her that her warfare is accomplished,
that her iniquity is pardoned; for she has received of the Lord`'s hand,
double for all her sins.`"
Dined at J. D. H.`'s, with a considerable number of Friends,
and in the afternoon rode to J. T.`'s, at New Garden,
who had accompanied us to Richland and Pleasant Plain.

15th. Returned to Salem, and attended the Quarterly Meeting of Ministers and Elders,
in which I was silent.

16th. Went into the town, and was at the Quarterly Meeting, which was large.
After a season of silent waiting, and several had spoken,
the simplicity of the means which the Lord makes use of, to carry on his purposes,
was presented to my mind, and though clothed with weakness, and my faith low,
I believed it right to stand up, and say what the Lord furnished me with.
The simple means by which the leprosy of Naaman was cleansed,
and the clay by which the blind man`'s sight was restored, were brought to view;
and that without obedience to the command given in those cases,
neither the leprosy nor the blindness would have been removed.
So in the work of grace in the heart,
obedience to the little requirings of the Holy Spirit must be yielded,
or we cannot be cleansed from the leprosy of sin,
or receive spiritual sight to discern our fallen condition, and the way out of it.
Submission to the washing of regeneration is indispensable to the salvation of the soul,
and without it we cannot be prepared for usefulness in the church of Christ.
We must be changed men ourselves, before we are prepared to aid in changing others.
Divine kindness was extended, enabling me to open some things,
relating to the efficacy and spirituality of the gospel,
and the way by which alone we can be partakers of it.
The meeting sat about six hours, which was rather wearing;
we returned to our lodgings and rested.

17th. Being first-day, many, not members, came to the meeting, which was large.
Several spoke pretty early.
A feeling of sympathy with the honest-hearted, exercised ones,
and with those who have outward trials, was brought over me;
and I was led to remind Friends,
that our Savior did not promise his disciples
freedom from suffering in this state of being;
but He said to them, "`In the world you shall have tribulation; but be of good cheer,
I have overcome the world.`"
It may be safely inferred, that He designed to encourage them to believe,
that as they persevered in following Him, they also should be made overcomers,
through his Spirit and power.
It was a season of mercy, in which help was renewed,
to open many things pertaining to the faith and patience of the christian;
for which I was humbly thankful, and the meeting closed under a solemn feeling;
many Friends showing their unity in taking leave of us.

In the afternoon, we attended a meeting here, appointed for the young people,
by a stranger.
Returned to our quarters,
took an affectionate farewell of our kind friends J. P. and wife, and rode to S. H.`'s,
on our way to Cedar County.

18th. Rode forty-two miles, and put up at a house of private entertainment.

19th. We were up pretty early, and drove to a poor tavern to breakfast.
The landlady offered as an excuse for her provision,
that a large number of Indians passed that way, a short time before,
and consumed nearly all they had in the house.
On setting out, two carriages in company with us,
we were told the road to Iowa City was good; but to us it was very disagreeable.

We drove through ponds of water,
out of one of which it was with great effort our horses drew us and the carriage,
slipping and falling, as they attempted to rise up on the banks, which was alarming.
The sloughs were wet and numerous; but we got safely through.
Dined at a Friend`'s house at Iowa City; which has a few brick houses,
but is located where it is difficult to foresee how it will ever rise to much magnitude.
It is, however, remarkable,
that so much progress has been made in some towns in this new State, as we have found.
Today we rode about forty miles, and put up near where Friends hold their meeting.

The residences of the settlers in this place, scattered over prairie land,
are chiefly log buildings; the settlement being several miles in extent.
In the summer season, while the grass is green, the country,
with the cabins and little surrounding improvements dotted over it,
has a picturesque appearance; yet to a stranger, it gives a sensation of lonesomeness.

Whether it has been the design of Divine Providence,
that Friends should be pioneers in the settlement of new States is, on some accounts,
doubtful to me; persons, who generally take the lead,
being often of the description which need the care of religious society,
instead of being really qualified to set up and hold meetings, to the honor of Truth.
Yet there have been instances,
of meetings being gradually collected and settled by Friends of religious experience,
which have prospered.
In some places, it is to be feared, that the spirit of discernment has been lacking,
and persons have been acknowledged as ministers,
who have not had the gift bestowed upon them.
These have fed the people with words, that have not been with the Spirit,
and with the understanding also; and thereby, that which ought to be slain,
has been fed and kept alive; and the people loving to have it so,
they have exalted and idolized such preachers, to their great hurt,
and the injury of the flock.
What a deplorable effect has this had upon the Meetings,
and how different from the heart-searching and baptizing
ministry that has been known in parts of our Society.

20th. Attended Red Cedar Meeting, composed of middle-aged and young people,
settled here within a few years.
I did not feel that exercise among them, so generally,
as might have been expected from those, whose living and habits are simple.
There were some, who, I believe, are under a religious concern for themselves,
and the cause we profess to be called to uphold;
but they lack fathers and mothers to take them by the hand;
and unless great watchfulness is maintained,
will be in danger from the snares which may be placed in their way.
I had some service, but it did not yield the relief experienced in some places,
yet hoped it was from the right source.
We went to S. S.`'s, and dined, with whom we had comfortable feelings,
from the persuasion they were honest-hearted Friends.
In the afternoon, he and M. O., set out with us as pilots,
and to aid us on our way to and beyond the Mississippi.
We rode twelve miles, and put up at a tavern, near Cedar River.

21st. Crossed the river in a flat;
the owner of the ferry was not willing to take any fare from us; we went to J. C.`'s,
to breakfast, about eight miles.
Just before leaving them, we had a little opportunity with him and his wife,
to press on them the necessity of attending to the great business of life,
the salvation of their own souls;
and to bring up their children in the nurture and admonition of the Lord.
Rode to Muscatine, a town on the bank of the Mississippi, where we crossed the river.
We found the road and bridges, along the flat bottoms on the east side of the river,
had been torn up by recent freshets; and though somewhat repaired,
it was disagreeable traveling on them,
and we were disappointed in finding the road so obscure as it was in some places.
We got dinner at a private house in the prairies, and as soon as it was suitable,
went on for Millersburg,
which proved to be about six miles further than stated to be on some of the sign-boards.
Towards evening we came to a creek, where the bridge had been swept away,
by a fall of rain ten days before, causing a terrible freshet; and turning back,
we got a boy to show us where they forded the stream.
We succeeded in driving through, and up on the bluff,
where a temporary road turned so abruptly among the timber,
that it was difficult to drive, and we did not reach Millersburg until dusk;
where we had to put up at a mean tavern, with poor accommodations;
the fare for the horses, and supper and lodgings for ourselves, being hardly bearable.

22nd. Rose pretty early, but were detained in getting shoes on one of the horses;
breakfasted at a farmer`'s, five miles on the way.
Set out under some discouragement, from the accounts we had of the streams,
and rode five miles round, to cross on a bridge over Edwards Creek.
Forded Pope Creek, where it was difficult for the horses to rise up the bank out of it,
and about noon reached a dining place;
where we got further instructions respecting the road.
We had many sloughs to pass, and after riding about two miles,
were detained nearly an hour,
while one of the company went in search of a private bridge,
over which to cross a stream, in our course.
Towards sunset, we reached a brick farm house, in the edge of a wide prairie,
and put up for the night; being weary with riding,
and the anxiety produced by the many disagreeable, miry places; from which the horses,
when they find themselves sinking, spring forward,
as if they would break the carriage or harness.
The people here were kind, and made us welcome and comfortable;
and the head of the family appeared to be better
informed than most we meet with in this new country.

23rd. When breakfast was prepared,
our host told us it was their practice to have family devotion or prayers,
but perhaps it would delay us too long.
We made no reply, not wishing to interfere.
He got the bible, and read a chapter in the Revelations, in which it is said,
they that keep his commandments, shall enter in through the gates into the city.
When he stopped,
I felt engaged to express my approbation of the practice of reading the Holy Scriptures,
but that it was also necessary to put in practice the commands contained in them.
That although we had not as great measure of the Holy Spirit,
as the prophets and apostles, who wrote them,
yet the same spirit that inspired them to write, was given to us,
to teach us to deny ungodliness, and the world`'s lusts, and to live soberly,
righteously and godly, in this present world.
I desired the parents might remember, that here we have no continuing city,
and the importance of walking in the fear of Almighty God;
setting their children an example of holiness;
and that they might come under the government of their Savior.
That they should keep his commands, as made known in their hearts;
and when the end of all things here arrived to them,
the fear of death would be taken away, and through the mercy of God in Christ Jesus,
the gates into that glorious city, and the arms of everlasting Love,
would be open to them.
When I closed, the old man said, "`Will you join us in prayer?`"
I answered, we believe it is our duty to pray continually,
by the help of the Holy Spirit;
but we also believe it requires a special intimation of the Spirit,
to place ourselves on our knees in vocal prayer.
He made no reply, went on his knees, and the family with him; but we kept our seats.

In the course of his prayer, he petitioned that the lecture, as he termed it,
might be blessed; asked the aid of the Holy Spirit to enable them to resist temptation;
prayed for our preservation;
and that if they and the strangers should not meet again in this world,
we might meet in heaven to part no more.
He appeared to be a man of some religious understanding.
We sat down to breakfast, and he made some enquiry respecting the faith of Friends,
particularly on the divinity of our Savior; to which I gave him answers;
and we regretted that we had left all our tracts in Iowa,
and so were not able to give him a printed account of our principles.
We parted with friendly feelings.
Our faithful friends continuing with us, much to our comfort,
we rode through Henderson to Knoxville, dined, and fed our horses.
There the road being good and plain,
so that there appeared no difficulty in getting on alone,
we took an affectionate leave of them and rode to Tucker`'s,
a private house for entertainment of travelers; where we obtained good lodgings.

24th. After breakfasting, and receiving directions respecting the road,
we travelled twenty-four miles, to another farm house, where they give entertainment.
These people were from Pennsylvania.
From there we rode to Peoria, and crossed the Illinois River,
on the bridge that had been repaired;
but the road through the bottom on the east side of the river,
was still in a bad condition, so that it was difficult and unpleasant driving through it.
Glad we were to be leaving it behind,
and that the space between us and our beloved families was gradually narrowing.
Eight miles from the river we put up for the night at Groveland.

25th. Hearing that Mackinaw River was raised,
and could not be forded where we had passed it on our way out,
we rode down the stream three miles round, to a miserable bridge,
that looked ready to tumble down, and by twelve o`'clock got to Concord,
a cluster of half dozen houses, and dined.
In the afternoon passed Bloomington, and reached Bishop`'s, a private house;
where we found good accommodations for ourselves and horses.

26th. Rose early and went to Le Roy, nine miles, to breakfast.
The wind came out of the north, in the night, and it was cold riding this morning.
Between breakfast and dinner, we crossed two wide prairies; one fourteen miles,
and the other eight or nine miles; in which we had some large sloughs to pass;
which made traveling, in some places, disagreeable;
the water and mud under the wild grass being deep and laborious to the horses.
Dined at a decent house near the Sangamon River,
and having eleven and a half miles to ride to Urbana,
set off and got to our quarters before sundown.
It was cheering to be brought safely back to the inn, where we lodged,
the first night after beginning our prairie journey without pilot or company.
We were well received by the innkeeper, who seemed anxious to please his customers.

27th. We had forty miles to ride, in order to reach I. S.`'s,
and finding the sloughs a good deal dried, we pushed on, and got to his house by sundown.
His valuable wife came out to us as we drove up before the door, saying,
"`I am glad to see you;`" I replied,
"`I am glad to hear you say so--we are thankful for the kind reception of Friends,
and that the Lord has brought us back safely thus far.`"

28th. Being their week-day meeting, and fatigued with steady traveling,
we concluded to rest with them until tomorrow morning.
The meeting was not so large as when we were with them before; but unexpectedly,
it was a time of comfort and encouragement to the sincere travailers.
We dined at J. H.`'s;
and in the afternoon went with I. S. and wife to their widowed daughter`'s,
who resides with two little children on the prairie, about two miles from her parents.

Passed the afternoon peacefully, though under feelings of sadness,
at the lonely situation of this young woman, who appeared to be an exemplary Friend.
After taking tea, as we sat together, a word of sympathy and encouragement arose,
and was handed to her.
When we returned, we pleaded with the parents, to remember her lonely condition,
and if way opened for it, to get her nearer to them before winter.
But while we were at Richmond, attending the Yearly Meeting,
we were informed she had been attacked with disease,
prevailing in that part of the country, and was removed, I trust, to a better world.
It seems mournful, that such good examples, of whom we stand in great need,
are taken from us by death, as they are apparently preparing for service in the church.
Yet we are poor, shortsighted creatures,
and know not what she and her friends may be spared,
by her being gathered beyond the reach of temptation and danger.

29th. Before leaving these kind and hospitable Friends, this morning,
for the east side of the Wabash River, the family sat down with us,
and the Lord furnished me with matter for their different states;
so that we had a tendering time together, and parted under feelings of mutual,
affectionate regard.
Rode over to W. H.`'s and dined, and on leaving,
had to deliver some counsel to the parents and children.
Then set out with him, as pilot, to S. A.`'s, which we reached a little before evening,
and remained there during next day; needing a little rest and some re-fitting.

31st. Attended their first-day meeting;
in which it seemed to me the life of religion was low, among many who made a show,
and were active in some things of an outward nature.
The necessity of partaking of spiritual food, and spiritual drink,
and laboring for it individually, was brought before them,
as that alone which can sustain and nourish up the soul unto everlasting life.
There is great danger of relinquishing this
labor for the bread which comes down from heaven;
which the Son of Man only can give,
and trusting in a mere acknowledgment of the truths of the gospel;
leading a life of morality; reading a chapter in the Scriptures daily,
and attending religious meetings.
I felt distressed among them,
and came away without feeling that there were many true travailers in the meeting.
Dined at T. M.`'s, who took us to D. N.`'s, at Poplar Grove,
where we had notice spread for a meeting on second-day.
The Friends were kind, and entertained us heartily in their simple, comfortable way.

Ninth month 1st. The weather clear and very warm;
went to the meeting under feelings of depression.
The company was about double the size of their usual meeting, and they sat very quietly.
I felt drawn to stand up with the prayer of one formerly: "`Lord, make me to know my end,
and the measure of my days what it is,
that I may know how frail I am,`" and I labored
among them according to the ability received,
endeavoring to strengthen the sincere-hearted in faithfulness;
warning the young people of the dangers of evil company,
and inviting them to receive the visitations of their Savior,
and to follow Him in the way of the cross.
Returned to D. N.`'s and dined;
and in the afternoon he and his wife accompanied us to D. H.`'s, at Rush Creek,
which is a woody country, some parts of the road passing through the wilderness;
in which we should not have supposed there were many persons settled.
We forded Sugar River, a little above the place where a Friend, a physician,
was drowned a few weeks before, during a high freshet;
the river running with great force.
We were kindly received by the Friend and his wife,
and felt comfortable in spirit under their roof.

2nd. We had a meeting at Rush Creek, which was large.
It seemed difficult to conceive where all the people came from,
so much of the land being yet covered with timber.
The warm weather relaxed me much, and feeling exceedingly empty, and my faith low,
I was discouraged from attempting to engage in the work of the ministry;
but I was constrained to stand up; many things were brought before me,
and utterance given of matter I had not thought of; even to my admiration,
and to the solemnizing and tendering of some present.
So that I had reason to rejoice a little, in the midst of poverty,
and the apprehension that few have ears to hear, and hearts to understand;
but the testimony of Truth is to be borne under Divine authority, and left with them.
We dined near the meeting-house, and then rode back over Sugar River to N. N.`'s,
at Bloomfield, and put up.
He told us he was in his eighty-fourth year,
and when the notice of our intended meeting at Rush Creek came to him,
he mounted his horse and rode seven miles to D. H.`'s, and delivering it,
returned home without taking dinner.
On a previous occasion he delivered the notice
for a meeting to another person to forward,
and it miscarrying, he was determined to take this himself to the right place.

3rd. Attended the regular meeting at Bloomfield;
in which I was much borne down with a lifeless, formal spirit,
trusting in creaturely performances, and greatly neglecting the inward,
spiritual work of religion.
It appeared to me there was a disposition in some,
to despise the sanctification of the soul, by the cleansing,
baptizing power of the Holy Spirit, and to adopt, in its place,
a mere literal belief of the truths of Christianity,
as explained by their own wisdom and learning;
and to lead people away from the hope of
deriving the true and saving knowledge of Christ,
by the operative power of his Spirit in the heart.

That dark and subtle spirit was felt to be at work in this place,
with great deceivableness; and after speaking of the favor it is to have humble,
lowly travailers preserved among us,
who are brought to mourn over themselves and the degeneracy among us as a people,
I was led and enabled to bring to view the deceivable workings of this spirit,
and to contrast, with its erroneous imaginations,
the purity and powerful efficacy of the inward, regenerating religion of Christ,
where He is received as the teacher, and feeder, and captain of his people.
It is only in His school that we are livingly taught the truths of the gospel;
know them to be applied to our state by Him;
and receive from Him that faith which gives the victory,
and by which we truly believe the testimony of the Holy Scriptures,
and experience Him to become our Savior and Redeemer.
It felt to me there are those of our Society, who dislike this spiritual doctrine,
and hold it in contempt.
Such will turn away others from the truth, and if they persist,
will fall themselves into increasing darkness.
But the time will come, when the worm that dies not, and the fire that is not quenched,
will bring them into deep distress, unless they are favored to repent,
and turn their back on all their delusions.

Our carriage requiring some repair, we lodged the second night at N. N.`'s,
and had some conversation with the old Friend;
in which he took occasion to express his fears, that changes were taking place,
unfavorable to the support of the ancient views and practices,
that prevailed among Friends in former times.

4th. Set out early this morning to meet our kind friend, D. N.,
who had consented to pilot us over to Mill Creek.
He was detained, and the weather being warm, and the road rough and hilly,
we got on slowly, so as to be in the evening before we reached our lodgings.
Just before dusk, one of our horses got a hind foot fast between two logs,
on a rough bridge; which threw him down,
and though he made two or three violent efforts to extricate it,
which we feared would have broken his leg, we were obliged to hold him down,
while one pried the logs apart, before it was loosed;
and glad we were to find that he walked without limping.
We were alarmed at the prospect of losing our valuable creature,
and considered it a favor that he was not ruined.
It occurred about half a mile from our friend A. H.`'s, to whose house we led our horses,
and he and D. N. went back with his horses, and brought the carriage.
It was a fatiguing day`'s journey of forty miles;
but being received with cordiality by our kind friend and his attentive daughters,
we were refreshed and compensated for our wearisome travel.
I mentioned my desire to hold a meeting at Mill Creek tomorrow,
and our friend offered to go over at once to one or two members,
and enlist them in spreading notice in the morning; which showed his goodwill,
as it had then become late in the evening.

5th. We went to meeting.
The query put to the children of Israel, was brought before me, "`Your fathers,
where are they; and the prophets, do they live forever?`"
I thought there was among them too little concern, that inward,
spiritual worship should be performed and maintained.
I endeavored to do my duty; but the feeling that rested upon me,
respecting the low state of the meeting, was depressing.
As we rode from it,
I asked A. H. whether they had any minister or elder belonging to the meeting?
He said none, except an old woman in the station of elder,
who lived part of her time here, and part within the limits, of a distant meeting;
so that it might well be said, Your fathers and mothers, where are they?
What a condition for a large meeting to be in?
What have the young people around them, to animate them to make choice of true religion,
and to come up in the footsteps of the flock of Christ`'s companions?
We dined at a Friend`'s house, about a mile towards our stopping place;
where we had the company of E. W. Hodson and wife, who belong to Spring Meeting.
In the afternoon returned to A. H.`'s, and lodged.

6th. At Springtown, we were met by E. W. H., and went with him to their home; dined,
and in the afternoon, one of his sons piloted us over to West Union, about twelve miles,
where we lodged.

7th. Attended their meeting, which was large, being first-day.
The subject of spiritual worship came before me, and rested on my mind some time,
but I could not see my way clear to attempt any public communication.
The meeting was continued about the usual length of time, in silence,
and I felt very peaceful in leaving it; with a heart clothed with love to the people;
trusting there was a reason for it,
and that it would be a benefit in showing our testimony to spiritual, silent worship.

Dined at a Friend`'s house, and went to Highland Meeting at three o`'clock.
Here I passed through some fear of speaking, or of keeping silence,
from the suggestions of Satan, that there was not sufficient motion to speak;
which brought me into some conflict of spirit; but finally I believed it right,
to stand up, with the blessings pronounced by the Savior, upon the poor in spirit;
upon the mourners, and those who hunger and thirst after righteousness;
and to show that they apply to the Lord`'s poor, those whom He strips and empties;
who mourn over their condition; and as they abide under his humbling, baptizing hand,
will hunger and thirst after the bread and water of life.
These are very different from the rich and the full;
full of their attainments and ability to judge and act for themselves.
The life rose into some dominion, and gospel truths were a little opened, I hope,
to the benefit of some.
We went to a Friend`'s, and lodged.

8th. Had an appointed meeting at Bethel, a newly established meeting.
The testimony that a man`'s life consists not in the abundance of that which he possesses,
was revived; neither does the strength of a people, or a society,
depend upon their numbers.
There is no substantial peace or happiness, but in living and walking in the Truth,
neither is there any other ground of strength in a religious body,
but in living under the government of the blessed Head of the church.
Here only are we preserved amidst the trials and temptations of time;
enabled to keep the outward blessings in their proper place,
and to witness a growth and an establishment in Christ, the Shepherd,
Rock and Foundation of his people, individually, and as his church.
The dangers of being swallowed up in a worldly spirit, were plainly spoken to;
and the importance of being solid, grave, exemplary christians; not light and frivolous,
talking about trifling things, so as to turn the young people away from Christ,
instead of drawing them to Him, when they are brought under his convicting power.
Some appeared to be brought under religious feeling, and were tendered.

9th. Had a meeting at White Lick, which was an unexpectedly large company.
The house is a brick building, put up to accommodate the Quarterly Meeting,
and has a neat appearance, very creditable to the members.

After a season of waiting upon the Lord,
the temptations and dangers to which even the believer,
who has attained to some steadfastness and experience in Christ,
is exposed,--like standing upon a sea of glass,
mingled with fire,--were a little opened to their view.
Though the Lord`'s tender mercies are over all his works,
we cannot expect preservation without watchfulness and prayer,
walking in lowliness of mind before Him.
All self-sufficiency, and relying on past attainments, must be relinquished,
and a willingness lived in to be emptied and stripped, by Him who knows our infirmities,
and what baptisms and reductions are needful for
our refinement and growth in Divine Grace.
Some things relating to the work of regeneration and sanctification,
were brought before them;
and the meeting was concluded with vocal prayer for Divine regard,
and for the Lord`'s sustaining power in Our trials.

Went back to our lodgings and dined.
Just before we left, two Friends coming in, we fell into silence,
and the departure of a large proportion of our members from that inward
exercise for themselves and for the right support of the cause of Christ,
which every one ought to experience, was alluded to;
and the desire expressed that those present might keep to it.
Where are those travailing ones, the mourners in Zion, the burden-bearers among us?
Many seem not to understand the doctrine of regeneration, and daily suffering;
such a state of ease has come over us.
A Friend, being provided for guide, we rode to A. B.`'s, near Easton, and lodged.

10th. Attended their usual meeting here;
in which I thought there were some who are sensible of poverty of spirit,
and were longing for the appearance of their Lord,
that they might partake of the comfort of his presence,
and see the prosperity of Truth spring forth among them.
To these a word of encouragement was held out.
Returned to A. B.`'s and dined.
In the afternoon went to Fairfield, and held an appointed meeting,
at half-past three o`'clock.

The company that came into the house was a mixed one, and unexpectedly large.
The expressions of the prophet, "`He has shown you, O man, what is good,
and what does the Lord require of you, but to do justly, to love mercy,
and to walk humbly with your God,`" came before me,
and after endeavoring to try the fleece, I stood up with the passage.
The opening of several subjects to this mixed assembly was unexpected; and, I hope,
that useful impressions were made on some minds.
After the meeting, A. B. and wife took us to M. S.`'s,
at Sugar Grove whom we found an open, pleasant Friend, glad to have us at his house.
The cordiality which this Friend manifested, was grateful to our feelings.

11th. We were at Sugar Grove Preparative Meeting;
in which the indispensable work of inward sanctification,
and daily waiting upon the Lord, for strength and preservation, were enforced;
and the danger of relying upon a literal,
or educational assent to the truths of the christian religion, without the inward work,
was declared among them.
I was fearful that some were too self-confident,
and not acquainted with daily walking in the path of humility before the Lord.
Returned to M. Stanley`'s, and dined.
Before leaving,
we had a religious opportunity with the parents and some of their children;
in which the sense of true fellowship was felt, I believe, on both sides.

12th. Had an appointed meeting at Lick Branch, which filled the house.
I labored among them in the love of the gospel,
that they might experience an entire redemption from the world,
its delights and treasure; and was enabled to pray for old and young;
that the Lord would renew his work in some of the former; that they might be brought in,
even at the eleventh hour of the day,
and at last be favored with a true hope of
admission into his glorious kingdom in the end;
and that the young people might be gathered from the many snares which surround them.

We went home with D. W., an aged member, and dined.
A son-in-law died in the house a few weeks before; and on leaving them,
I thought it my duty,
to remind them that such a dispensation not only called the one from time to eternity,
but should warn survivors of the business of life; which is, to glorify their Creator,
and to prepare for their solemn end.
As we were to have no meeting tomorrow,
and were expecting to find letters from home at Indianapolis,
we concluded to ride there this afternoon, being about nine miles, and on a good road,
and put up for the night at a suitable hotel;
a member of Richland having agreed to meet us there next day, on his way home,
and pilot us to the house of Z. C, residing at Richland.
To my great relief, I received letters,
which gave information of the health of my dear wife and children,
and strengthened me to try to hold on to the end of the service,
as it might be required of me.

13th. The Friend calling for us as he had engaged to do, we set out for Richland;
the road being very dusty and the weather warm.
About noon, we stopped on the bank of White River, fed our horses, and took some food,
which the Friend and his wife had brought with them.
We got to Z. C.`'s, about the middle of the afternoon,
being sixteen miles north of Indianapolis;
and found him and his wife to be very kind and pleasant Friends.
Two of the sons and their wives being there on a visit, and the house not large,
we were afraid of incommoding them; but where there is a willing heart,
apparent difficulties can often be accommodated, and true enjoyment felt on all sides,
which we proved to be the case here.

14th. During the night the weather changed; being cloudy and blustering,
with lightning and distant thunder,
so that the mercury in the thermometer fell many degrees.
We concluded to have notice spread at Richland this morning, being first-day,
of our intention to hold a meeting there, in the afternoon;
including Friends composing a small meeting recently set off from this,
a few miles distant; and at a suitable time, we left for Westfield,
about five miles further north.
No notice being sent of our coming to this meeting, and the weather being chilling,
it was less than usual, as we were informed.
Endeavoring to cast myself upon Him, who cares for us, He was, after a time of waiting,
pleased to furnish with ability to preach the everlasting gospel;
showing the necessity and importance of being baptized into Christ,
and witnessing the fellowship of his sufferings; preparatory to rising with Him,
into newness of life.
Also pleading with the young people to take his yoke upon them, and learn of Him,
who is meek and lowly of heart.

We dined, on the way back, with two Friends; and E. E., a Friend from New Jersey,
with whom I had been acquainted, belonging to this meeting, came with us.
Then rode to Richland, and attended the appointment there.
The notice had drawn a large company, like a Quarterly Meeting.
Unexpectedly to myself, my gracious Master furnished fresh openings of several subjects,
relating to the change which He works by his
power in the hearts of those who submit to Him;
and also the purity He requires, and clothes the soul with.
Christ Jesus being the author and the finisher of the saints`' faith,
those who have this faith and keep it, must be sanctified, and therefore holy men,
freed from sin and the commission of sin.
I was also favored with the spirit of supplication for
the sincere travailing ones and others.
It was a good meeting; in which holy help was vouchsafed,
and the spirits of many bowed and united together.

We were again pleasantly received at Z. C.`'s; and the following morning, at parting,
a few words arose for the young, recently married couple, and for the parents,
which tendered their spirits, and we took leave of each other in nearness of affection.

A+++.+++ H. having offered to accompany us, we rode to Indianapolis;
and about six miles further east, on the National road, we stopped at an inn, dined,
and fed our horses.
Towards evening we discovered that one of them was sick,
and we were obliged to stop and take some measures for his relief.
A little before dark, we got to a Friend`'s, at Westland, where we lodged.
They made us comfortable, and appeared glad to have us with them.

16th. Had an appointed meeting at this place.
The company was small, yet there seemed to me to be humble-minded ones among them,
who were acquainted with the path that no fowl knows,
which the vulture`'s eye has not seen, but in which the wayfaring man,
though a fool as to worldly wisdom, shall not err,
as the eye is kept single to the Shepherd and Bishop of souls.
We were piloted to S. P.`'s, near Raysville, ten miles;
where we felt ourselves heartily received; he and his wife being open and free.

17th. Attended Raysville Preparative Meeting.
In the first sitting, the great importance of inward, vital religion impressed my mind;
and the testimony of the apostle, that "`He is not a Jew who is one outwardly;
neither is that circumcision which is outward in the flesh;
but he is a Jew who is one inwardly, and circumcision is that of the heart,
in the Spirit, and not in the letter,
whose praise is not of men but of God,`" was revived;
and the hatred which Satan has to genuine Quakerism,
as striking at the root and fabric of his kingdom, was adverted to.
He cares not by what means he can destroy us, and our religious profession.
If he cannot induce those who hold it, to deny the principles with the tongue,
but succeeds in drawing them into the friendships of the world,
and the love of its profits and delights;
and thereby they lose the inward life and power of godliness, it answers his purpose.
Of this, there appeared to me, to be great danger; the love of ease,
and the flatteries of worldly men, lying so near the natural inclination;
which shrinks from the baptism of the Holy Spirit,
and those dispensations which purge the branches, and keep them alive in the Vine.
It was a season of rather close exercise;
and yet Divine love and fervent desire for my brethren and sisters covered my heart;
that we might all become more what the Lord would make us,
were we entirely given up to Him.
We dined at S. P.`'s; after which we were conducted to Carthage,
where we put up for the night.

18th. Attended the Preparative Meeting, held in a good house,
at the south end of the village.
It was not a large meeting; but I hoped there was a remnant of the suffering seed,
who are acquainted with the hidden life; keeping at the feet of Jesus,
where they are instructed in the faith and patience of the saints.
These are the salt among us; and though the unregenerate man,
whose eyes are not anointed with the eye salve of the kingdom,
cannot discern their safe abiding, yet it is in Christ;
and even the worldlings are compelled to confess to their firm and upright standing.
The dear young people were affectionately pleaded with, to bow to the yoke of Christ,
and in the obedience of faith, serve Him;
that they may know Him to become the chief of ten thousands,
and altogether lovely to their souls;
and He would qualify them for service in his church.

I hoped it was a time of renewed visitation and encouragement to some.
In the afternoon went to a Friend`'s near Pleasant View Meeting-house,
and had a meeting appointed to be held there tomorrow.
This day it has felt as if my exercise in this Yearly Meeting was abating,
and the work drawing to a close.
We were very kindly received by the Friends where we lodged;
who appeared to wish to make us feel comfortable with them.

19th. We had a pretty good sized meeting, made up of a class which loves ease,
in relation to the performance of religious duty, some unfaithful ones,
and some who hold back through fear and diffidence.
I was enabled to enter into their condition;
bringing to their notice the parable of the wedding feast of the king`'s son; to which,
though provided without expense or trouble to those who were invited,
they refused to come; pleading various excuses.
So in this day, many neglect the offers of Divine regard,
excusing themselves from obeying his requirings;
and thus they fail to be brought to the feast of fat things,
and of wine well refined on the lees.
Some on the ground of their unfitness,
desiring to put upon others what the Lord calls on them to do,
and from this cause never come to the growth in Christ, and that standing in his church,
they would be brought to, were they faithful in the day of small things.
Here is one of the causes of weakness,
and why our Society does not shine with that brightness it should appear in.
There was a renewed call extended to some, old and young,
to obey the drawings of the Savior,
that they may become servants and pillars in the Lord`'s house.
The meeting closed with solemn supplication for their help and strength.
It was a favored, good meeting; in which holy help was extended to me, a poor creature,
and for which I was humbly thankful.
In the afternoon went to J. P.`'s, at Walnut Ridge, who with his wife received us kindly.

20th. We attended Walnut Ridge Monthly Meeting, held in a large building,
near the Friend`'s dwelling.
The company was very large for a Monthly Meeting;
and I was enabled to preach the gospel among them with good authority and weight;
and to encourage the tribulated traveler,
to bear all the refining dispensations of Him who knows what we need,
and how to administer his baptisms for our purification;
by which we shall be fitted to bear fruit to the praise of the great Husbandman.

Many Friends saluted us at the close of the meeting affectionately,
who I believe were glad of our company.
After dining, we rode to Kaysville; where we stopped to see an afflicted woman.
She was directed to look to the Savior,
who could show her her transgressions and shortcomings; give her the gift of repentance,
and blot out all her sins, as she gave herself into his hands.
We then rode to S. P.`'s, where we were kindly received by his wife and children.

21st. Accompanied by these kind Friends,
we set out and rode to a Friend`'s near the village of Spiceland,
where my companion and I had lodged on our way out westward;
who appeared pleased with our safe return to their habitation.
We walked over to the meeting-house, standing at the west end of the town;
where we found some Friends and others collecting, it being first-day.
When we were all seated, the company was quite large.
I felt much emptied, and thought it might be my place to set an example of silence;
but after waiting a long time, the passage was revived,
with an intimation to stand up with it: "`The light of the body is the eye; if,
therefore, your eye be single, your whole body shall be full of light;
but if your eye be evil, your whole body shall be full of darkness.
If, therefore, the light that is in you be darkness, how great is that darkness?`"
The subject was gradually opened, and the Lord enabled me to warn some,
of the danger of relying upon their own wisdom and understanding,
substituting them for the guidance of the light of Christ in the heart;
by obedience to which alone,
the work of regeneration and sanctification can be experienced.

Without this, all educational faith and knowledge;
all that man may do in his own strength, will avail nothing in the work of salvation.
He may think to do good, by talking of the truths of the gospel,
and making much display of them before men; but without the inward,
heart-changing work of Divine grace, all this will be no better than fig-leaf coverings;
our own righteousnesses, which are as filthy rags.
All classes were encouraged to come under the
operation of the Spirit of Christ in the heart,
that they may know the work of salvation to be going on with the day.
To the fathers and mothers in the Truth,
the language of sympathy and consolation was addressed, with the expression of faith,
that as they persevered in watchfulness,
the Lord`'s covenant with them would not be broken,
but they would know preservation to the end.
They would be made a blessing to the dear young people;
who were also tenderly invited to take the yoke of Christ upon them,
for which they would receive the reward of sweet peace,
and never have cause to regret serving so gracious a Master.
I thought it was a day of Divine condescension, and of unmerited favor to us,
poor unworthy creatures.

Returned to E. E.`'s and dined,
and in the afternoon he walked with us to the residence
of our dear aged friends Wm. and Anne Hobbs,
at the east end of the village; with whom we took tea, and had a pleasant conversation.
He appears to be an innocent-spirited Friend;
honestly concerned for the support of the good cause,
and for the welfare of his brethren.
As we came out of his door, the good old Friend said, "`I am willing to say this much,
I am glad you have been with us today.`"
Though not very pointed, it was a comfort to have this testimony of approbation.

22nd. Notice having been sent to Rich Square, for a meeting to be held at three o`'clock,
in the afternoon, we rode there and dined; and then went to the school-house,
where they hold their meetings.
We were told their meeting-house and school-house were burned down in the same night.
Both buildings, now nearly finished, are very suitable for the respective purposes.
I had some painful labor in the meeting,
in endeavoring to awaken them to the danger of being swallowed up in worldly things,
and in persuading them to turn to the Lord and to his service.
The meeting was closed with supplication on their behalf and for ourselves.

23rd. Had an appointed meeting at Hopewell.
I was impressed in this meeting with the great importance of an early,
faithful dedication to the Lord;
such being often made instrumental in quickening others
to a serious consideration of their day`'s work,
and by their solid example inciting them to engage in it.
On the contrary, the neglect to mind the Divine requirings,
clearly manifested to the soul, places a stumbling block before others,
and may turn aside visited ones from following their Lord.
I feared much, there were those of this description present,
whose prejudicial influence was closely spoken to; and the great benefit pointed out,
that dedicated servants and handmaids of the Lord are to their fellow members.
The labor among them brought solemnity over the meeting, which I hoped might be useful.
But we have to hope against our feelings, and leave it all to the Lord,
after having endeavored to do the best we could.
After dining, we were accompanied about eight miles to a Friend`'s house,
on our way towards Fairfield Meeting.
It was an agreeable lodging place; where we passed the evening in conversation,
on the testimonies and discipline of the Society, and other appropriate subjects.
Two Friends were visiting there, who were young in the ministry; intelligent and solid,
and inward in spirit, which made the company interesting and cheering.

24th. Went to Fairfield meeting.
Being their usual weekday meeting, and no notice of our coming having been sent,
the company consisted of eight or nine men and six or seven women,
and it was rather a laborious time.

25th. We were directed on our way to West Grove Meeting.
The company that assembled there was small,
no notice having been sent them of our intention to be present.
A plain and unequivocal testimony against the habit of sleeping in meeting,
was delivered among them;
in which they were reminded of the fervor of blind Bartimeus to have his eyes opened,
when he cried out to the Master, "`Jesus, you Son of David, have mercy on me.`"
Were we livingly engaged in our religious meetings to wait upon, and cry unto Him,
our eyes would be opened to see wondrous things in His law,
and we should be raised above this drowsy spirit.

27th. Being seventh-day, we attended the Monthly Meeting at Milton.
I was enabled to labor with the young people,
to induce them to give up in early life to the will of their Heavenly Father,
inwardly revealed in their hearts;
by which alone they can be fitted for usefulness in the church,
and experience a growth from stature to stature in the blessed Truth.

28th. This morning, being first day, we attended Bethel Meeting.
We sat with the company quite a long time before anything was said,
when a woman Friend had a short communication.
I was engaged to draw Friends into an individual examination,
whether the life and power of Christ reigned in them,
that they might be made and kept branches of the living Vine,
and by their spirits and example,
show forth the efficacy of the religion of our Lord Jesus Christ.
I felt afraid the strong man had not come down into the state of a little child;
but that some were judging and acting too much in their own wisdom and understanding,
by which the Seed of the kingdom was borne down, and did not rise into dominion.

29th. Rode down to Richmond, about sixteen miles, and put up with Elijah Coffin.

Tenth month 7th. Attended the Yearly Meeting held at this place,
which I thought was not as large a company as when I was here before.
Much time was consumed in discussing subjects in
which the expenditure of money was concerned;
which has the effect to keep the attention occupied with outward things,
instead of a travail of spirit for the welfare of the members,
and the advancement of the cause of Christ, by a life of religious exercise,
and showing forth the fruits of the Holy Spirit.
So many concerns of an outward nature, all of which are reported upon,
and long discussions entered into, it appeared to me, kept the mind so afloat,
that the meeting did not experience that inward feeling after
the solemnizing presence of the Head of the church,
and the pointing of the Divine finger, which would give sound judgment,
and tend to the edification of the body, in the life and power of the Holy Ghost.
To get the great number of these subjects, with others of a different nature,
disposed of, the business was crowded on the meeting.
I wish not to judge uncharitably,
but I did fear that the great object for which the church is brought together annually,
is not, under these circumstances, as fully answered as it should be.
There is some danger of such a Yearly Meeting becoming
like a great philanthropic or benevolent association;
and the minds of the members being much absorbed by these objects,
as if they constituted the work of religion;
and by which the activity of the natural man may be substituted for
the leadings and direction of the Head of the church.

8th. Having sold our carriage, we left Richmond this morning, in a stage for Hallowell,
forty-two miles; and then took the cars for Cincinnati, Ohio,
which we reached a little after eight o`'clock.

9th. Arose about three o`'clock, took a little breakfast,
and were taken to the car office for Cleveland; and about five o`'clock got on our way,
reached that town on Lake Erie, near that hour in the afternoon,
and went on board the steamboat Alabama for Dunkirk.
The evening and the lake were placid, the moon shining brightly,
which afforded the prospect of a pleasant passage; and after taking supper,
we soon retired to our berths, where I slept pretty well until daylight,
and about five in the morning we found ourselves at Dunkirk.

10th. Left this town at six o`'clock, in the cars for Jersey City, on the North River;
which we reached before twelve o`'clock that night, being less than eighteen hours,
traveling four hundred and sixty-nine miles on this road;
in which time they allowed ten minutes each for breakfast and supper,
and twenty minutes for dinner;
making over twenty-five miles an hour throughout the whole route.
It seemed a favor to get through without accident.
Retired to bed at the hotel, and rose next morning about five o`'clock.

11th. Took the Philadelphia cars, at six o`'clock, and found ourselves at Camden,
a little after eleven; from which we crossed the Delaware,
and I was soon embraced by my dear wife and children,
with several other of our near connections, who were at my house;
all of whom showed their joy to have me restored to them again,
after a journey involving so many liabilities to accident and disease.

Under a sense of the goodness and protection of the Lord, our holy Helper,
in preserving us from dangers, furnishing ability from time to time, to do his will,
and bringing us safely home to our dear families, gratitude many times warmed my heart;
with the desire to ascribe unto Him, thanksgivings and praise,
and to bless his ever-adorable name.
Many Friends greeted me very warmly on being restored to them.

At our Monthly Meeting, held in this month, and the Quarterly Meeting,
early in the Eleventh month, I returned the certificates with which I had been furnished,
for the western journey;
with the minutes of several Monthly and Quarterly Meetings of Indiana Yearly Meeting,
expressing their satisfaction with the visit and services.

Since getting home, I have passed through seasons of great stripping and desertion,
which have been followed by the renewal of Divine good,
and some ability to testify to others,
of the faithfulness of the Lord to his poor creature, in raising him up,
and renewing his faith in his unchangeable power and goodness.

In our evening meetings, this winter,
we have had much solemnity and deep ingathering of spirit;
and the gospel has been preached to the softening of the hearts of many,
to whom I have no doubt, these opportunities have been beneficial,
and it may be a permanent blessing to some.
