== Chapter XXVII

[.chapter-synopsis]
* 1852+++.+++ Sources of Trial
* Renewal of Religious Labors in different Meetings about Home
* Yearly Meeting
* Value of a right of Membership among Friends.

1852, Second month.
The present state of our religious Society has a strong opposing influence
to the effectual working of the measure of grace in every part of the body,
to edify itself in love, and promote the real welfare of one another.
Yet there is preserved a body of exercised members,
who travail for the support of the cause of Truth,
and for the gathering of the children to Christ Jesus, their Savior and Shepherd.
Our Quarterly Meeting for discipline, held this month, was very large,
and comparatively but little was said in it.

4th. Went to the Quarterly Meeting of Ministers and Elders, held at Germantown;
in which my wife and myself had some service.
Next day we were at that for discipline, and were both engaged in the ministry,
to encourage the sincere ones, and to warn those who had been divinely visited,
but had grown indifferent and neglectful of the all-important work of their day;
the salvation of the soul, and their duties to the church and to one another.

25th. The proper holding of our approaching Yearly Meeting, is a subject of great weight;
and, at times, it seemed as if I should be willing to be released,
and gathered away from it.
But the exercise must be borne by some,
if the cause of Christ is upheld by our religious Society.
When we consider the awfulness of eternity,
and that we have individually a work to perform,
we have need to resign ourselves unto the Divine hand,
and ask of the Lord strength to endure our trials, and to follow him faithfully,
so that the work and the wedding garment may be finished by the time the end comes.

In looking at the divided state of Friends,
I have had many thoughts on the subject of separation,
talked of by some restless members.
I have been fully convinced that Friends cannot go into separation,
but they should patiently bear the difficulties which we have to encounter,
and their testimony against the cause of division, as the Lord qualifies them.
We have no right to break down the hedge which He has placed around us;
and if we stand firm, He will make his own cause victorious.
Opposing spirits will be removed, and a generation raised up,
that will be enabled to exalt the glorious standard of gospel truth,
and the christian testimonies we were and are called to spread in the earth.
It appears to me to be a snare of the enemy, to divide and scatter,
under the plausible plea of terminating our afflictions,
but which would destroy our strength, and plunge us into inextricable difficulty.
When another trial came, the same pretext would present, to divide again;
and thus our destruction as a religious body would be inevitable.
The church is never more alive to the cause of its adorable Head,
than when under suffering;
and the present afflictions will be sanctified and made
a blessing to us if we rightly profit by them.

Third month 17th. Feeling my mind drawn to sit with Friends, I went to the North Meeting;
where we had the company of Hinchman Haines, who was a little engaged in the ministry,
to comfort the discouraged ones.
After him, I felt moved to utter the language of the prophet,
"`O you afflicted, tossed with tempest, and not comforted,
behold, I will lay your stones with fair colors,
and lay your foundations with sapphires.
And I will make your windows of agates, and your gates of carbuncles,
and all your borders of pleasant stones.`"
"`In a little wrath I hid my face from you for a moment;
but with everlasting kindness will I have mercy on you,
says the Lord your Redeemer;`" and to say, that under the clothing of peace,
which had spread over my mind, from the early part of the meeting,
I was prepared to bear testimony that our God is a God nigh at hand and not afar off;
and that He who joined himself to his sorrowing disciples,
after they had seen their Lord crucified, dead and buried, would also join himself to us,
as we walked by the way, and would satisfy us, that it was He,
and would sustain us by his power.

29th. Rode with J. and H. Rhoads to Middletown, where we attended their Monthly Meeting.
Encouragement was offered to trust in the Lord Jehovah,
in whom there is everlasting strength.
If every one was engaged to do his own work,
witnessing the hewing and squaring by the Lord`'s hand,
the unity and baptism of the Spirit into one body, would be known more fully,
and spiritual sacrifices, acceptable to God,
would be offered through Jesus Christ our Lord.
And the true love and fellowship would prevail;
cheering and comforting one another in the work to which all are called.
My dear wife was also engaged to call upon all to
search whether the spirit of Christ dwells in them;
for if any man have not the spirit of Christ he is none of his.
We may be contending for sound christian doctrine,
which is proper under Divine authority; but the main thing--the one thing needful,
is to know Christ to dwell in our hearts, ruling and reigning there;
putting off the old man with all his corrupt deeds,
and clothing us with his heavenly nature.

Fourth month 4th. My wife was enabled to hold forth a word of encouragement,
this morning, to the tribulated members; and afterwards it seemed to be my duty,
to bend the knee, and vocally implore the compassionate Shepherd,
to remember mercy in the midst of judgment; to renew the faith of the fearful,
disconsolate ones,
and to defend his heritage from the attempts of the cruel enemy to destroy it.
I hope we had a little renewed evidence that the Lord was with us,
the meeting closing with much solemnity.

6th. My exercises returned, on account of the approaching Yearly Meeting;
but as the meeting drew on, they abated, and hope, at times, sprang up,
that Divine mercy would be extended for our health and preservation.

16th. Our Meeting for Sufferings convened and was held to our satisfaction.

17th. The Yearly Meeting of Ministers and Elders was held this morning;
the number of strangers was not large.

18th. Our meetings for worship, held at the Orange street house, were satisfactory,
particularly that in the afternoon.
It appeared to me to be a time of renewed visitation.
The ministry was sound and baptizing, which confirmed the hope that the Lord had not,
and would not forsake us, if we kept faithful to Him.

19th. Our Yearly Meeting was opened, I hope,
under feelings of abasedness before the Lord;
and the morning sitting was conducted with religious weight and dignity,
giving reason to believe that we should be helped to get through safely.
The replies to the Queries, brought Friends under much concern,
particularly in regard to the neglect of our meetings for worship; respecting which,
a minute was made to go down to the Monthly Meetings.
The reading of a circular epistle,
addressed by London Yearly Meeting to the Yearly Meetings in America,
advising us to support the order and discipline of the Society,
and to guard against separations, called out some remarks.

A minute was made of the reception of such an epistle.

Deputations from North Carolina and Baltimore, selected from their conference committees,
attended, with the Conference Address,
and produced minutes of their authority to present it to our Yearly Meeting;
which minutes were read, being direct from those +++[+++two]
Yearly Meetings;
but the meeting declined reading a document
prepared by committees of other Yearly Meetings,
in which this meeting had decided not to participate.
No other subject created any discussion, attended with contrary sentiments;
and the meeting closed on sixth-day morning,
under the most impressive silence and solemn feeling, that we have known for a long time.
I believe that many hearts were bowed with gratitude,
and thankfulness to the Father of mercies,
that his preserving power had been secretly extended,
enabling us to transact the business in his fear, and with much harmony.

Fifth month 16th. For the last two weeks I have been much shut up, as in a prison house.
These are humiliating dispensations;
under which we are often unable to believe they are designed to purge the soul,
and to prepare the creature to know the life preserved in the root;
that when the Lord`'s month comes again, the tree that is of his planting,
may bring forth fresh fruit to his praise.

26th. Was held our Monthly Meeting, which had but little business.
In the preceding sitting, I felt constrained to hold up the nature,
source and object of true and saving faith.
Christ being the author and the finisher of it, its nature,
efficacy and object are the same in all ages,
as set forth by the apostle in his epistle to the Hebrews;
where he recites many acts and deliverances,
experienced by prophets and holy men in ancient time.

Sixth month 9th. The meeting of the general committee
having the oversight of West-town School,
was very satisfactory; a concern being revived,
that this Seminary may continue to be conducted on the original ground, the religious,
guarded education and control of the children.
It appears to be in a satisfactory state; and Friends were much united,
in the same religious exercise; which comforted many present,
who have long had its welfare at heart;
desiring that the simplicity and propriety which become our profession,
may be steadily maintained.
I hoped it was a little token for good.
The young members of the committee, lately introduced,
were particularly interested and encouraged,
by the solid covering with which we were favored, and the remarks of several Friends.
We returned to the city in the afternoon.

10th. Went to the Arch Street Meeting, at which a marriage was accomplished.
I felt weak and low, and doubting whether I had better go.
After sitting some time,
I was forcibly impressed with the conviction
that the right path for every one to walk in,
is that which the Lord casts up for the ransomed and redeemed ones;
both as regards our movements among men, our worldly pursuits,
and the religious duties we have to perform in the Society.
We may, at times, be enveloped as in clouds, but if we keep a single eye to the Lord,
with sincere desire to be preserved from missing our way, light will, in his time,
break forth out of obscurity, and our darkness become as the noon-day.
I was also somewhat enlarged on the subject of steadfast
faithfulness to the openings and leadings of the Holy Spirit;
by which our faithful forefathers glorified God in their day,
and knew Him to be their hope and confidence in
the end and are now equal with the angels,
praising the mercy and great name of their Savior.
My sister H. Rhoads, followed in a strain of encouragement to the married couple,
and to the young people generally.
She believed the Son of Peace was with us, who appeared to the disciples,
the doors being shut, and breathed peace upon them.
My dear wife knelt in fervent supplication,
especially for those whose faith was often closely proved;
and the meeting was held and closed under a solemn covering,
and the name of the Lord was secretly praised for the manifestation of his goodness,
to his poor unworthy creatures.

As I walked towards the door, a young man, a stranger, met me, and said to me,
"`The Lord spoke through you today.`"
I making no reply, he asked if I was not the person who spoke?
which I answered in the affirmative.
He then added, he did not feel satisfied to leave the meeting,
without bearing testimony to the Lord being with us;
we had the Holy Spirit with us this morning.
I replied, that was the source of all true gospel ministry.
It was encouraging to find that the heart of one, not professing with us,
had been touched.
If but one soul is helped and encouraged on its heavenly journey,
we ought to be thankful,
and humbled that we are made use of in the Divine hand in any way,
whatever proving we may have to pass through.

30th. This morning a concern came over me, to go to the Western Meeting.
I felt calm and peaceful in sitting down among them.
The sweetness and preciousness of the Truth came over me,
to speak of and to testify that the only way to grow in grace,
and in the saving knowledge of our Lord and Savior Jesus Christ,
was by obedience to the manifestations of his Spirit in the heart.
The subject of the inward work, the danger of turning back after being enlightened,
and having made some sacrifices, and the certainty of being made victorious,
through steadfastly following Christ,
and the precious reward and Divine support and
consolation which the obedient ones are blessed with,
were opened.

Seventh month 1st. S. B. M., being under appointment to attend Gwynedd Monthly Meeting,
I felt inclined to accompany him;
and the Lord gave a word of encouragement to the little
company who are striving to keep up that meeting.
They were glad of our attendance,
and were refreshed with the dew which the Lord diffused over us.

27th. Attended the Monthly Meeting of Frankford;
in which I was drawn to hold forth the language of encouragement;
in the belief that there are young Friends, who are giving themselves up to the Lord;
and who, if faithful, will be made shining examples,
and become as pillars in the Lord`'s house.

Eighth month 11th. Our meeting, being fourth-day, was small,
as they have been this summer,
owing to many members having taken their residence in the country.
The warmth of the weather seemed to produce a stupefying effect on some,
so that towards the close I felt constrained to testify
that however we may be tried with drowsiness,
it is our duty to strive against it, through that Divine help,
which will finally enable us to gain the ascendency, and will be extended,
if we seek for it;
and then a qualification will be granted to praise the
Lord for his regard to us in our weakness,
and that He had quickened us by his immediate power.

15th. Many who attend our first-day morning meetings,
seem to think it is a sufficient part of their time to
devote to the worship of their Almighty Creator,
and our afternoon as well as mid-week meetings, are consequently small;
but there are those in every place who feel bound to keep them up,
both for their own good, and the support of our testimony to the duty of public worship.

17th. I went to the North Meeting, which was small.
I was engaged to bear testimony to the continued goodness of our Heavenly Father,
in regarding his children, and defending them from the power of the enemy,
under all the trials which He permits to assail them,
as their eye and trust are directed to Him.
Although some of the cups of suffering they partake of,
are like the wormwood and the gall, and their souls recoil from them,
when their faith seems ready to fail, yet in his tender mercy,
He sees and secretly sustains them.
When Elisha prayed the Lord to open the eyes of his servant,
at the time the city was besieged, he saw the mountains full of chariots and horsemen,
round about Elisha, so that those with the prophet,
were discovered to be more than their enemies.
The same invisible defense is still present with the Lord`'s church and people,
though they may not always be able to behold it.

19th. Attended the fifth-day meeting at Haddonfield, held in a new meeting-house;
one of the most neat, plain buildings for that purpose,
that we have within our Yearly Meeting.
The company was larger than I expected to see,
and afforded encouragement to believe there was a power secretly at work,
drawing the people to assemble for the solemn purpose of Divine worship.
I was raised up in a close appeal to some,
who were wasting time and talents in earthly pursuits,
in which they could not find substantial settlement and peace of mind.
Nothing can procure these but giving to the fire, those things that are for the fire,
to the sword that which is for the sword,
and to the hammer those things which are to be broken to pieces and removed,
that a way may be made for the kingdom of the Son of God to be introduced and set up.
Some might put on a fair outside, while they kept back that which is to be given up; but,
however they might deceive man,
they could not conceal their condition from the Searcher of hearts.
All the possessions and comforts, with which they surrounded themselves,
would not yield the solid peace which Christ gives to his children.
The young man who came to Christ, and enquired what he should do to inherit eternal life,
went away sorrowful, when he was told to sell all that he had, and give to the poor,
and come follow Him.
He had great possessions, and loved them more than his Savior, or his own salvation;
and we have no account that any other offer was made to him.
But however some had turned their back upon the convicting power of Divine grace,
and had no foundation to stand upon, the Lord, at seasons,
brings them to feel their destitute condition, and to look back at their waste of time,
and their resistance of the Divine calls;
and now they were unable to command those feelings of tenderness which they once had,
but hardness was coming over them, and the work of the soul`'s salvation not begun.
They cannot repent of their transgressions when they please;
repentance and the power to amend our lives are both in the Divine hand.
But I believed mercy was following them, and if they gave up to the Lord`'s call,
though at the ninth or the eleventh hour,
and went into the vineyard of their own hearts and labored faithfully,
they would receive the penny at last,
with others who had borne the burden and heat of the day; and before the close,
might be made examples and standard-bearers to draw others to Christ.
It was a good day.
It was the Lord`'s work, my mind having been particularly drawn to attend that meeting.

25th. Was held our Monthly Meeting;
by which my wife was furnished with a minute to attend Ohio Yearly Meeting.

30th. My sister Hannah Rhoads, having her mind drawn to attend Ohio Yearly Meeting, was,
with her husband, liberated by their Monthly Meeting, for the visit.
They and S. and B. Nicholson came to the city this afternoon,
and early the following morning, they, with my wife, met at the depot,
and I saw them comfortably seated in the car, and started for Pittsburg;
the weather being very fine for traveling.

9th month 1st. Our meeting today was refreshing to me,
under the belief that the Lord`'s tender mercies are round about us;
and that He is secretly sustaining his children by his omnipotent arm.
Many parts of the meeting were contriting to my spirit,
and I thought it required of me to encourage Friends to faithfulness,
and to keep their trust in the Lord`'s unfailing goodness,
and also to keep near to one another in spirit.

2nd. Though I had a humbling view of myself,
and fears of being mistaken in what I apprehended to be my duty, yet this morning,
I went to the Arch Street Meeting, and sometime after Samuel Bettle, Sr.,
had delivered a short testimony,
I felt engaged to speak to the states of those who had
been often favored with the visitations of Divine love,
showing them their condition, and what the Lord required them to do or to leave undone;
but who, from negligence and disobedience,
were sensible at times that they were not what they ought to be,
and that the work of salvation was not going on in them.
They were warned that the day of account was drawing on,
and urged to examine what ground they have for hoping for acceptance,
should they be called to appear before the judgment seat of Christ in this condition.
They profess to believe in Him, and hope for the forgiveness, and pardon of their sins,
through his precious blood; but it is those who live and walk in the light,
as He is in the light, that experience his blood to cleanse them from all sin.
Men may live what the world esteems moral lives,
and yet be gratifying their own will and carnal propensities;
having their household idols, and their heart`'s beloveds, which they worship;
but it is as their will is nailed to the cross,
and the life they have in things which the Lord`'s controversy is with, is slain,
and they baptized into death, that they can know Him,
who is the resurrection and the life, to quicken their souls,
and make them alive unto God.
Those who were neither cold nor hot, were warned of their danger;
for He declared to a church formerly, that He would spew such out of his mouth.

It is by the washing of regeneration and the renewing of the Holy Ghost,
that we can be prepared for communion with the Father of lights and spirits;
and to those who give up all, and seek Him daily, He condescends to manifest Himself;
humbling their hearts before Him, and enabling them, as with their mouths in the dust,
to put up their petitions to Him; which He will hear and answer from heaven,
his high and holy dwelling place.
The doctrine of christian purity and perfection, as delivered to Abraham,
and enjoined by our Lord upon his disciples, was held up.
It seemed as if the Lord gave fresh access to his treasury, opened by Him,
and qualified to warn and to persuade all, to mind the day of their visitation;
that they may be prepared in the end,
for an admission into the everlasting kingdom of our Lord Jesus Christ,
among saints and angels, and the spirits of just men made perfect;
whose employment it is, to ascribe unto Him that sits upon the throne, and to the Lamb,
glory and honor, thanksgiving, might, majesty, dominion, and praise,
to whom alone it belongs.
I returned to my dwelling with feelings of quiet peacefulness.

The absence of my dear wife, laboring in a country,
where disease prevails in many places; and a concern for the preservation of Friends,
who have taken the ground of defense of our religious principles,
against the attempted innovations of some in the present day,
have caused me to walk in secret mourning; yet not without the belief,
that the Lord beholds our afflictions,
and will support and make way for our final deliverance, in his time.
Faith is at seasons renewed in his unfailing mercy, and evidences are granted,
that He has not forsaken his afflicted church.

8th. While sitting in our meeting today, the injunction of our Lord was brought over me,
"`Take no thought for the morrow,
for the morrow shall take thought for the things of itself.
Sufficient unto the day is the evil thereof.`"
We are not to become indifferent in relation to the future;
because we are exhorted to lay up a good foundation against the time to come.
But the more faithful we are to the Lord, in performing our daily duties,
the more we shall be relieved from all unavailing anxiety about the future;
and enabled to cast our care upon Him,
who will care for and sustain us through all our troubles.
I thought Divine help was present to comfort some anxious ones in our little meeting.

I rode out to Germantown in the afternoon, and next day, the 9th,
attended the meeting there; in which I was unexpectedly drawn,
to show the distinction between the religion of mere education,
and the religion of regeneration.
The first is that of opinion and habit;
the other of conviction and submission to the heart-renovating power of Divine grace.
We may lose the latter through unwatchfulness; as being once in grace,
is no surety for being always in grace.
However valuable a sound education,
by the example and precepts of religious parents and friends, may be,
and for which we are responsible, yet if the work of regeneration is not experienced,
we shall be mere formalists; and it will be evident that the life of religion is lacking.
There seemed to be a warning for some, who may be correct in the eye of their fellows,
and yet are in an indolent state;
regardless of that exercise of mind and daily prayer for heavenly food,
by which the immortal soul is nourished, and enabled to do the Divine will,
and to bear fruit to the praise of the great Husbandman,
and to the benefit of the church.
I thought there was evidence that the Lord`'s power was present,
to arouse and quicken some to greater diligence in their day`'s work.

15th. This morning my dear wife got home from Ohio;
having attended the Yearly Meeting at Mount Pleasant, which, in some respects,
was closely proving; yet throughout,
Friends believed that Divine protection was round about them.

25th. By appointment of the School Corporation,
I visited several applicants for the admission of children of those not Friends,
gratuitously, into the schools under its care.
The destitute condition of some, their exposure to the evil company of other children,
who live much in the streets, and the incompetency of their parents or caretakers,
to train and example them in a religious and moral life, were truly affecting to me.
Were it not for the watchful care of the unslumbering Shepherd,
over the souls He has made, it seems as if destruction must inevitably overtake such.
We cannot be too sensible of the blessings we partake of,
as members of a religious Society, professing the principles of the gospel of Christ;
and which feels bound to extend a restraining influence over old and young,
to guard them against the seductive power of temptation,
as it is presented in the world at large,
and in the private associations of men and women, who reject all religious control.
How grateful and consistent in our conduct, ought we to be,
for the salutary provisions and influences we have around us; associated as we are,
or may be, with solid christian friends, whose sentiments and deportment are like salt,
to preserve, or as the dew upon the tender grass, to nourish and feed the good in us.
In relation to forming connections for life,
it is of great importance to have part in such a Society,
where purity of principle and practice is inculcated.
There is great safety in dwelling, like the Shunamite woman, among our own people;
and if it be our lot to enter into a married life, to make choice of one,
whose training has been within our own pale, or who has been brought in by conviction,
under the regenerating power of Divine grace.
In such training, the minds of the members receive a similar bias and stamp.
Thus they need not break up nor forego the sentiments
of their education on religious points,
in order to conform to each other.
A union in this respect has already existed;
and when bound together in the most tender and endearing ties of human life,
the way will be open to be constant helpmeets in their heavenly pilgrimage,
as well as to aid and cheer one another,
in the difficulties that pertain to their temporal duties.

What a sad loss is sustained by those young people, who despise their birthright,
and part with it, as Esau, for a mess of pottage.
If they are not favored with repentance in time, so effectual as to return,
they will wander from the path of safety,
and confusion and embarrassment in some way will follow.
I believe that forsaking a Society,
where there are many means for spiritual help and preservation,
and where the true nature of vital religion has been clearly unfolded,
will be attended by serious disadvantages;
and that very generally such are swallowed up by the world and its corrupting spirit.

28th. Attended the North Meeting, which I sat in peaceful silence.
What a blessing it would be,
were every obstacle to the prevalence of sincere christian fellowship,
removed from among us, and we loved one another unfeignedly.
It would greatly contribute to our strength and the disposition to aid and
encourage one another in the performance of all our religious duties.
We should mourn with those that mourned, and rejoice when one was exalted,
in the occupancy of his or her gift.

Tenth month 14th. Felt an inclination to go to the Arch Street Meeting,
where Samuel Leeds ministered in an acceptable manner to me.
After him, it appeared to be my place,
to address the scholars and the caretakers of the Select Schools;
encouraging the dear children to love and mind the Savior, who took the little ones,
in his arms, laid his hands upon them, and blessed them.
He still regards these, though He is exalted above all principalities and powers;
and by his Holy Spirit, He draws them from sin; and when they obey Him,
leads them in the paths of righteousness, and rewards them with his peace.
In all the trials which their caretakers endure, if they look to Him,
they would know the everlasting arm of the same blessed Savior to be underneath,
supporting and strengthening them for the work of their day;
and as they discharge faithfully their religious duties to their interesting charge,
many of them, I believed, in after life would call them blessed.
As the children gave up to the visitations of their Savior, He would show them the bride,
the Lamb`'s wife, adorned in garments of purity and brightness,
the righteousness of saints; which represents the holiness and christian perfection,
to which all the members of the mystical body are called and attain,
through the power of Christ`'s spirit.

23rd. The mind is often influenced by the state of the body.
But whatever cause may act, I believe the Lord does lead us at times into low places,
and veils his countenance from us, to reduce and humble the creature,
and to draw us to seek to Him in our humiliation;
that He would in mercy preserve us from falling away,
and help us to maintain the watch and the warfare against the cruel devices of the enemy.
I feel the need of such dispensations,
that I may be quickened to watch against every improper thought,
and set a closer guard at the door of my lips.

27th. Was our Monthly Meeting, in which some of the Queries were answered,
and we were in some degree introduced into the state of the members.
Oh for a more united and heartfelt travail for one another`'s growth in the Truth,
and more willingness to hold up and strengthen
the hands of the laborers in the Lord`'s vineyard.
There is great strength in true unity,
and a sincere desire for each other`'s religious welfare.

30th. Today was held our Select Quarterly Meeting, which was satisfactory.

Eleventh month 1st. In the meeting for worship, which was attended with solemnity,
E+++.+++ Pittfield and E. Evans ministered in a weighty, feeling manner.
The evidences of the condescension and forbearance of
the Shepherd of Israel to his creatures,
many of whom are forgetful of their greatest interests, are encouraging,
and raised desires that we might be more devoted to Him and his cause.
When the gospel is preached in the love and authority of Christ,
we have reason to believe that the good Shepherd is
caring for the lambs and the sheep of his pasture,
and seeking to draw others into his fold;
and we ought to receive with gratitude these evidences of his merciful regard,
and be incited to more fervent and full dedication of
our time and talents to his service.

3rd. Having for some time, had our minds drawn to make a visit to our beloved,
aged friend and mother in Israel, Hannah Gibbons, my wife and myself,
went there this afternoon.
The faculties of our aged friend are remarkably preserved;
the staidness and solidity of her spirit are peculiar,
and the constant exercise of her mind, trained in the school of Christ,
and ornamented with the garment of humility,
makes her a striking example to the believers; showing the efficacy of Divine grace,
and the fruits of long dedication to her Lord,
in the path of self-denial and daily watchfulness unto prayer.
We felt nearly united to her,
and esteemed it a favor to have such a pillar
and watch-woman continued in the militant church,
to so late a period of life.

4th. Attended their meeting, which was unusually large,
many of the inhabitants coming in to see a marriage, in Friends`' mode.
It was conducted in a solemn and appropriate manner,
which I thought commended our practice in making this solemn covenant, before all others.

7th. This has been a day of little spiritual enjoyment;
but if these seasons tend to abase the creature,
and drive to the Fountain of all good to ask for preservation,
they will prove blessings in disguise.
This evening commenced the united meetings for all the members in the city who can attend.
The company was large and very quiet, to whom my wife ministered in a short testimony,
addressed chiefly to the young people.
All our ministers in the city were present except one.

14th. Though the weather was cold and blustering, and threatening rain,
our evening meeting was quite large, and a solemn covering spread over us.
A Friend had a short communication; after which, we sat some time in silence,
during which, the dealings of the Lord with his children in hiding his face from them,
and permitting Satan to buffet them, so that they are afraid of becoming cast away,
were brought before me; and I believed it was my duty to stand up,
with a testimony to the great importance in such seasons,
to keep the faith and patience of the saints.
Our Lord said to his disciples,
"`You are they which have continued with me in my temptations;
and I appoint unto you a kingdom, as my Father has appointed unto me.`"
It is of the utmost importance to keep near to Him in all trials and temptations,
that we may know his kingdom established in us, where He rules and reigns over all.
They tend to humble us into the state of a little child, in which only,
we can enter that kingdom.
The Christian`'s progress, and his establishment on the sure foundation,
through the grace that comes by Jesus Christ, were declared;
showing how we are made preachers of righteousness in life and conversation,
and a living protest against sin and iniquity.
