== Chapter XXIX

[.chapter-synopsis]
* 1853--1854. Religious Services at and about Home.

1853, Ninth month 25th. We have had a good meeting this morning at Orange Street.
My dear wife addressed those who were brought under conviction for their empty,
fruitless manner of life, and were now favored to see the need of a change.
Near the close, I underwent the humiliating service of vocal supplication,
in much brokenness,
for the deliverance of such souls out of bondage and Egyptian darkness;
and that during the Divine administration of judgment,
they might know the Spirit of the Lord lifted up, as a standard against the enemy,
who would seek to frustrate his work in them.
Also, for the Lord`'s children: that as He knew the trials,
fears and buffetings they passed through, He would not forsake them;
but renew their faith, and keep them in the hollow of his Omnipotent hand,
that so they may show forth the efficacy of the religion of the Son of God,
for the sake of those among whom they dwell, and for generations yet to come:
that from the rising of the sun, to the going down of the same, his great name,
and the name of his dear Son, may be glorified and magnified, and through mercy,
salvation may be granted to us in the end.
The difficulty of utterance was very abasing;
but I thought it was good to be made a fool, if it were for Christ`'s sake,
and the good of others as well as myself.

Tenth month 9th. I felt impelled to bring to
view the great difference there is between those,
who, according to the apostolic injunction, pray without ceasing,
and in everything give thanks, and those who rarely pray,
and who feel thankful for none of the blessings they partake of;
which is truly a fearful condition.
It appeared to me, if we live in the element of prayer and thanksgiving,
there will be Divine life,
and a fervent concern for the support and promotion of the cause and kingdom of Christ.
But when he that rides on the pale horse, whose name is death, is sent to our habitation,
what hope can those have who neglect true prayer,
but have been wrapped up in their own selfishness and the things of time,
without gratitude for favors;
and have turned the back on the convicting power of Divine Grace?
They may cry, if they have the time granted to do it, Lord,
have mercy upon me! but how can they expect mercy,
seeing they have rejected the calls of the Lord,
when He visited and extended to them the offers of his mercy,
and they refused to receive and obey Him.
Another class was also present,
who are concerned to dwell in the spirit of prayer for strength and preservation;
and to give thanks in the fire and in the waters,
which are not permitted to kindle upon or to overwhelm them.
I thought Divine help was extended, and that the power of Christ was felt among us.

19th. This morning,
under a humbling sense of the many mercies which have been extended to me,
I was contrited to tears before my gracious Heavenly Father,
and enabled to breathe to Him fervent prayer, that He would be pleased in his mercy,
to preserve me from doing anything that would grieve his Holy Spirit, wound my own soul,
or the precious cause which he has called us to support before the world.
Secret desires were also raised for our religious Society, that He would defend it,
and the tribulated sufferers in it,
from the enemy that is seeking to divide and scatter us,
and prevent us from exalting the doctrines and testimonies of the gospel,
as they have been opened unto us by the power of the Holy Spirit.

2nd. At our meeting,
after a time of struggling against the inroads of things
foreign to the great object for which we assembled,
the subject of being met in the name of Christ,
and the efficacy of united prayer to the Father of mercies, came with weight before me;
which I believed it required of me to open to the meeting.
The worship that is accepted by Him, which is in spirit and in truth,
must be performed individually;
through the quickening power of the great Minister of the sanctuary and true tabernacle,
which God has pitched and not man.
But if the prayers of two or three, offered in the name of Christ, shall be answered,
how much greater cloud of incense will arise,
if the whole congregation is brought to unite in
fervent aspirations to the throne of Grace,
for the bread of life, to nourish the immortal soul.
He knows how long to try our faith before He appears in the heart; but when He comes,
to those who open the door, He will enter and sup with them, and they with Him.
This is the Lord`'s supper; which is inward and spiritual;
in which the bread that comes from Him, and the wine of the kingdom, are partaken of,
to the refreshment and strength of the patient, waiting soul.
For this we are not dependent upon any man, however great his gifts, or his experience;
he has no more command over this heavenly food, than any other;
but all must wait upon the Lord for it, in sincerity and truth;
and all may partake of it at his table,
if they are prepared by Him to be made recipients of it.

My wife closed the meeting with supplication, in a solemn, impressive manner.
I thought Divine goodness was extended to us, and that his power spread over the assembly.
There were present a number of strangers.

Eleventh month 7th. For many days I have been shut up,
and all ability to preach the gospel has been withdrawn,
as though I should never more be called into the work.
I have been almost destitute of any sense of the quickening power;
and I saw that no former openings or favors would give the least ability or
authority to put forth a hand in this solemn and weighty work.
I have endeavored to keep inward, and looking to the Lord,
though I could not see or feel Him present;
yet I believed it was the only place of safety,
and the right way to be profited by these stripping dispensations.
None know the feelings of destitution, produced by the absence of the Beloved of souls,
but those who have been bound to Him in the everlasting covenant,
and can be satisfied with nothing but the balm which He gives,
and the fresh arisings of the Sun of Righteousness, with healing in his wings.
Here is exercised and known the faith and the patience of the saints.
As these are steadily kept,
these dispensations purge man from all confidence in his own wisdom and strength,
and bring him to see that he is nothing;
and that nothing but the renewed visitation and putting
forth of the blessed and compassionate Savior,
can ever qualify for the work of the ministry;
or any other religious service in the church.

10th. This morning, my wife and myself, went to Evesham Monthly Meeting, New Jersey.
My wife spoke to those present, in a sympathizing and encouraging manner,
and inviting them to increasing dedication and faithfulness.
The expressions of our Lord to his disciples, saluted my mind with quickening virtue,
"`One is your Master, even Christ, and all you are brethren;`" and after a time,
I felt a motion to revive them, with those He addressed to them at another time,
"`You call me Lord and Master, and you say well, for so I am.
If I then, your Lord and Master, have washed your feet,
you ought also to wash one another`'s feet.`"
I was led to treat on the importance of being baptized and washed by Him,
and then to be employed in promoting the work of sanctification in others.
As we come into this blessed experience, being born alike of the Spirit,
we shall be brethren, knowing the unity and fellowship of the gospel to prevail among us.

12th. Attended Upper Evesham Monthly Meeting, held at this place,
in which we were both engaged in the ministry of the gospel;
I believe to the solemnizing of some present, whose hearts were open to receive it.

13th. Went to Cropwell Meeting, being first-day, which, it was said, was large for it.
After sitting some time,
and feeling the indifference which prevails in many on the subject of religion,
I was led to advert to the circumstance,
that persons engaging in any business to obtain a livelihood,
must be aware that it could not be advantageously
conducted without steady attention and diligence.
Valuable crops could not be expected from their farms,
if they work industriously for a short time, and then leave it;
proper system and diligence are necessary to insure good returns;
everything being done in its season, and carefully looked after.
So in the great work of salvation,
which is of far greater moment than the provision for these tabernacles of clay.
No advancement can be expected by those, who for a short time,
give up to the convictions of duty, and then conclude they may forbear,
and let the work drop for awhile; perhaps they think until they have more leisure,
or have accomplished some worldly project.
They may suppose religion can be taken up when they please;
but it is out of our power to command one of the days of the Son of Man,
by whom alone the work is begun and perfected.
None know whether He will ever again renew those heavenly visitations.
There is a day granted in which man may work; but he may out-sin that day.
It will then be impossible for him to work,
and the things that belong to his peace will be hid from his eyes,
as it was declared respecting the people of Jerusalem.
They were earnestly labored with to persuade every one deeply to consider these things,
and to lay hold of the offers of Divine Grace; that they may glorify God in their day,
and be made partakers of the hope of the gospel, even the salvation of the soul.

The retrospect of this little turn-out, afforded a peaceful feeling,
in the belief that the Lord was mercifully with us, preserved us on the watch,
so that nothing was said or done to cause uneasiness;
and in his goodness renewedly qualified, by his quickening power,
to visit the lowly seed, to sound an alarm to some, and to comfort them that mourn.

17th. Today we went to Germantown, and were present at a marriage.
A large number of strangers, not of our Society, were there;
to whom the work of sanctification, and the faithfulness of Him,
who begins and carries it on to the end, as we keep near to Him, was preached, I trust,
in the authority of the Divine anointing.

20th. The meeting this morning at Orange Street,
was a solemn time of ingathering before the Lord, producing contrition,
and raising in the soul feelings of humble thanksgiving, prayer and praise,
as in the presence of the Searcher of hearts,
and the compassionate Shepherd of the sheep.

23rd. Our Monthly Meeting was held today.
The subject of purchasing a piece of ground out of the city for a graveyard,
was before us, and the proposition to do so adopted.
I felt drawn to express the desire, that if it should be accomplished,
we might keep to our plain way of interring the dead, without any kind of ornament,
or monument about the graves.
If a proper place is procured, safely and substantially enclosed,
and put in charge of a suitable, trusty caretaker, and the bodies decently interred,
it is all we need.
The dust shall return to the earth as it was, and the spirit unto God who gave it.
But if we depart, by little and little,
from our religious testimonies to the purity and simplicity of the gospel of Christ,
in our humble manner of living, or our plain way of laying out and burying the dead,
we shall fall by little and little,
and gradually lose the character we have once had as a body of humble,
spiritually minded Christians.
Several Friends expressed their full unity with the remarks I made on the occasion.

Having felt a religious concern to attend Buck`'s Quarterly Meeting,
I got my son-in-law to take me; and we set out in time to reach Fallsington before dusk,
a distance of about twenty-seven miles, the roads being good and the weather mild.

24th. During the night the wind changed into the northwest,
and the morning being clear and cool, I walked out for exercise,
and passing around the old meeting-house, its venerable and plain appearance,
reminded me of former days, when Friends were a united body of people;
among whom there were many substantial ministers and elders, loving one another,
and the precious cause of Truth,
and zealously concerned to uphold and promote it in the earth.
Now there are two meeting-houses, and two distinct societies, calling themselves Friends,
who assemble on this ground, but holding, in several essential points,
different doctrinal views.
What a stumbling effect, it seemed to me, this must have upon tender-spirited persons,
whose minds may be drawn to look towards Friends; who,
from their rise have made profession of the inward,
heart-changing religion of our Lord Jesus Christ.
I felt sorrowful as I walked over the grounds,
and reflected on the devastation which the world, and the enemy of all righteousness,
has effected among us.

The meeting convened at eleven o`'clock.
The impression came over me, that in every age of the church,
the Lord has had his witnesses, who maintained their love and allegiance unto Him.
Noah and his family bore testimony against the wickedness of the people,
when it was said that all flesh had corrupted its way upon the earth.
Lot was preserved in Sodom, when their evil deeds vexed his righteous soul;
and so I believed there were those preserved at this day,
who mourn over the degeneracy that has spread through our borders,
and are looking for better days.
But it appeared to me, that it would not do to be looking without, for this restoration.
When the Pharisees asked our Lord when the kingdom of God should appear, He told them,
"`The kingdom of God comes not with observation; neither shall they say,
Lo here! or Lo there! for behold the kingdom of God is within you.`"
It is in the heart we must witness it to come.
We have been long contending, and in the authority of Christ,
for the doctrines of the gospel, and necessarily testifying against error;
but it is needful to guard against transferring our religion from the heart to the head,
and acting in our own zeal.

It is the inside of the cup and the platter that is first to be cleansed,
and then the outside will be clean also.
We may receive our principles by education;
but some were asked what they knew of Christ sitting in their hearts as a refiner`'s fire,
and as a fuller with soap, to purify them by his baptism of the Holy Ghost and fire,
and to prepare them as temples for the Lord God by his Spirit, to dwell in.
At the rise of Friends,
many believed in the fundamental doctrines of the christian religion,
but were little acquainted with the work of regeneration;
and Friends were sent forth to gather them to the Light and Grace
with which Christ enlightens every man that comes into the world;
that they might experience this change of heart, wrought by it in them.
This is what we need to be brought back unto.
One of the principal men told George Fox,
that if he had not been sent to preach this Light and Grace,
the country would have run into ranterism.
I was led to show Friends the danger of being drawn away by anything,
from this Divine guide and preserving power, as manifested in the heart;
but by keeping faithful to it, the snares of the enemy, whatever they were,
would be detected, and power given us over them all.

Then the word of comfort for the secret travailing ones sprang in my heart,
whom I was led to address in the language of sympathy,
and assurance that the Lord would not suffer the
principles and testimonies given Friends to bear,
to fall to the ground; but they would yet spread from sea to sea,
and from the rivers to the ends of the earth,
until the kingdoms of this world become the kingdom of our Lord and his Christ;
and from the rising of the sun to the going down of the same, praises as incense,
would ascend from prepared, humbled hearts,
before the throne of the Lord God and of the Lamb, for his mercy,
and goodness to the children of men.

Twelfth month 4th. Was held our first evening meeting this winter;
a part of which was laborious; but before the close, a more inward,
solemnizing covering was experienced.

6th. Went to West-town, and attended the Quarterly Meeting of the committee held there.
In the meeting of the committee on fourth-day, after getting through with the business,
Samuel Bettle, Sr., remarked,
there was something of importance which money could not purchase.
It was, that Friends should be preserved under a right exercise,
that the institution may be conducted in such manner,
as to support the primitive doctrines and testimonies of Friends,
and educate the children in them.
This was the original concern, and it had been blessed; and he believed,
as Friends kept to this ground, a blessing would continue to rest upon the school.
He spoke in a feeling manner; and being now in his eightieth year,
it seemed like a legacy left to the younger members, who might survive him,
to bear in mind in the future management of the seminary.
It was responded to, and had a good effect upon the feelings of many.
Returned home in the evening.

7th. Was at the Arch Street Meeting,
which was held in as deep silence as I have almost ever known;
though there was a large number of children present.
I was contemplating my own imperfections,
and felt unworthy to be employed in the Lord`'s work;
yet was a little comforted in the belief,
that the condescending mercy and goodness of the everlasting Shepherd were round about,
and hovering over us.
It is as necessary to keep silence when it is the Lord`'s will,
as to speak under his authority.
There were children present, who should be taught by solemn silence,
the nature of spiritual worship, as well as by vocal testimony.

21st. Having my mind drawn to the Western Meeting,
which I had not attended for a long time, I believed it right to give up to go there.
A solemn silence spread over the meeting, under which we sat a considerable time,
and the blessedness of having begotten in us a true
hunger and thirst after the bread and water of life,
came before me, attended with the conviction, that however strong our desires may be,
Divine nourishment must be waited for.
It is out of our power to command it.

The Lord knows how long to keep us in this waiting state,
and He alone can and will supply it in his time.
No imaginary enjoyment, produced by creaturely excitement or activity,
is to be compared with the love of God shed abroad in the heart by the Holy Spirit.
This dependent state has been the ground on which the true disciple of Christ has stood;
and whatever may be our gifts, experience or growth in the Truth,
it will always remain to be the ground on which we must stand,
to receive ability to worship God in spirit, partake of the supper of the Lord,
and rightly to engage in promoting the kingdom of the Redeemer.
Under the clothing of true charity,
and the desire that we might be brought to a living experience of the substance,
I was enabled to invite all to gather to Christ, in his inward appearance in the soul,
not depending on any other; for the Lord will not give his glory to another,
nor his praise to any graven image.

Also warning against expecting salvation without obeying Him, forsaking their sins,
and confessing Him before men.

27th. Calamities of different kinds are assailing men.
The Turks and Russians are now at war;
and today we hear of a naval engagement in which many war ships were destroyed,
and no doubt hundreds of immortal souls launched into an awful eternity.
A great fire in New York, this morning, burnt several large ships;
one of them said to be the largest merchant vessel in the world, entirely new,
and loaded with a valuable cargo.
These commotions, and the destruction of property, represent the affairs of the world,
as affording little evidence of the stability of property,
or the enjoyment which is expected to be derived from it.

1854, First month 8th. The weather cold.
Our evening meeting was large,
and the silence that spread over us was such as might be felt,
giving reason to believe that the good Master was with us.
There were, however, fears of a disposition in some, to look for words,
instead of gathering to the Master in themselves, and laboring to wait for his arising,
to administer to their states.
Looking out to others,
creates apprehensions that the design of these meetings is not answered;
and perhaps some of us in the station of ministers, may be more anxious than is proper,
that the people may not be dissatisfied, so as to forsake them.

18th. After sitting in our week-day meeting,
until near time to go to the business of the Preparative Meeting,
I felt afraid to depart without reviving the circumstance of our Divine Master,
the Son of the Highest, washing his disciples`' feet,
and wiping them with the towel with which He was girded.
Herein He set us a striking example of humility.
He told them,
"`You ought also to wash one another`'s feet;`" indicating that
we should labor for one another`'s purification and welfare.
It is in this spirit that we shall feel the unity and
fellowship of the gospel to extend to one another,
as we have been washed ourselves, and are kept clean by the Word which He speaks to us.

22nd. The evening meeting today was smaller than they were at the first,
but it was quiet and solid.
It felt to me, that Divine mercy and compassion were round about the afflicted seed;
and that the Lord would help and deliver these,
though the dragon may cast floods out of his mouth, to sweep them, if he could,
from the foundation.
But the Lord will lift up his Holy Spirit as a standard against him.
The meeting closed under a feeling of solemnity.

Second month 3rd. My brother Thomas and myself having
undertaken to print a new edition of Piety Promoted,
comprising all the volumes up to the year 1828,
I have been much engaged for a few days in reading proofs.
I have been struck with the great proportion of those faithful
men and women,--some of whom attained great experience in the
Truth,--who died at a much earlier age than mine.
Though I have endeavored to perform what the Lord has called me to do,
it seems but little, and my growth small, compared with many of them;
but if we have the testimony of Divine acceptance in the end, it will be enough.

An attempt is now making to pass a law in Congress, allowing the Nebraska Territory,
which is a larger country than all the Free States together, except California,
to be settled by slaveholders with their negroes.
It lies north of thirty-six degrees thirty minutes, north latitude,
and is part of what was ceded by the French government to the United States,
then called Louisiana.
At the time Missouri was taken into the Union as a State,
there was an agreement entered into between the
Northern and Southern members of Congress,
that slavery should be forever excluded from all the United States,
north of that latitude; which agreement was called the Missouri Compromise,
and was acceded to as one of the terms,
of admitting slavery to be introduced into the State of Missouri.
At the prospect of such a gross violation of the faith of the nation,
then solemnly pledged;
and the spreading of the horrible system of unconditional bondage
over many hundred thousands of square miles of new country,
the Committee of the Meeting for Sufferings,
appointed to watch the movements of legislative bodies,
prepared an essay of a memorial to Congress,
remonstrating against the iniquitous measure,
and also reviving our testimony against the slavery of the colored people.

At a special meeting held today, the subject was duly considered,
and the essay united with; a committee being appointed to present it to the President,
and both Houses of Congress,
and to have printed a sufficient number to
supply every member of both Houses with a copy;
also the Governors of the respective States;
and for such farther circulation as may be judged needful.

It is mournful to reflect upon the lack of principle manifested my many,
who have no scruple against enlarging the area of the abominable crime of slaveholding,
if their popularity can be promoted, so as to gain offices in the government,
and partake of the public funds, by the aid of the Southern people; whose interest,
in this case, they would be thought to serve.

What will become of our country, if we are to be ruled by men,
who disregard the principles of justice and truth,
and sacrifice the best interests and the rights of the people,
to their own aggrandizement.
Friends have been industriously engaged in obtaining
signatures to another short remonstrance,
opposing the violation of the Compromise, and forwarding them to Washington.

5th. We had a large meeting this evening at the Arch Street house.
A solemn silence, for nearly one hour, was over the assembly;
and feeling my mind moved towards the young people,
who had been drawn into covenant with the Lord,
I was led to address them in the language of the Psalmist,
"`The Lord God is a sun and a shield to all them who
walk uprightly,`" and the declaration to Abraham,
"`I am your shield, and your exceeding great reward.`"

6th. Was held our Quarterly Meeting, which was very large.
The testimonies of the Society were advocated, during the time of answering the Queries,
and some thought it was a lively and strengthening opportunity.
At the close of the meeting, I was informed of the decease of our friend Wm. Forster,
of England, in Tennessee, at a house of entertainment, about twelve miles from Knoxville.
He had been sick from four to five weeks,
and his life terminated on the 27th of last month.
The death of such a Friend, so far from his native home, among people not Friends,
and where probably many things necessary to make him comfortable, could not be procured;
after having been engaged more than fifty years in the service of the cause of religion,
has very much affected me.
But if we are prepared to be carried by angels, into the realms of ineffable bliss,
it matters little what becomes of the tabernacle of clay.
Yet such are the tender feelings of near connections and friends,
they would desire to have every comfort extended to body and mind in the last conflict,
that it would be in their power to bestow;
and that the sufferer might be spared the peculiar trial and anxiety,
he would be likely to feel under those circumstances,
of far separation from his near and dear relations.
But the Lord can support, and make up every deficiency.
He was buried, we have been informed, in the graveyard at Newberry, belonging to Friends.

9th. The remonstrance of the Meeting for Sufferings, has been presented to both Houses,
and published in several newspapers.
Some writers express the opinion that the bill will be passed into a law;
but the Lord can defeat all their evil designs, if He sees meet.

14th. I went to Quarterly Meeting for business, at Concord, without purse or scrip,
expecting to occupy a low seat before the Master.
After several others had spoken, I was led to address some,
who had departed from the law written in the heart, and yet at times were met with,
as in a narrow place, under the convicting power of Truth; by which they were condemned,
and brought to see that their ways do not please God,
and that they needed a change of their course.
These were pleaded with in the love of Christ, to yield to the heavenly vision;
or the day may come, when in the prospect of eternity,
they would mourn over their misspent time, and their slighted mercies,
when it would be too late;
and wish they could go back and recall those merciful visitations,
for which they then would be willing to part with all they possessed;
but it would be out of their power.
Now, instead of selling all to purchase the pearl of great price,
they were selling their time, the Lord`'s gifts, and his calls,
to purchase the world and the riches and honors of it.
The power of the Lord appeared to be present, to heal some, and to gather them,
from the improper pursuit of the world, unto himself;
and a deep solemnity spread over the meeting, tendering the hearts of not a few.
It was the Lord`'s doings,
and I trust that thanksgivings were secretly offered to
Him for his mercy and condescending goodness to us,
poor unworthy creatures.

When the Queries and Answers respecting pernicious books were read,
I felt an intimation to mention the great danger of reading novels,
or any work designed to invalidate the christian faith.
I had been enabled to hold such works in detestation; but at one time,
a package of goods sent to the store, where I was an apprentice,
was wrapped in a printed sheet, containing poisonous sentiments,
and having read a few lines, Satan beset me many times afterwards, with them,
so that I had much difficulty to entirely discard their impression.
I mentioned it as a warning to the young men, not to tamper with such books;
for they knew not the dangerous consequences that may result from them;
advising them to keep to the Holy Scriptures, the writings of Friends,
and works conveying useful information.

On the 20th, it commenced snowing, and continued about twenty-four hours,
with a strong east wind.
So great were the drifts, particularly in some of the east and west streets of our city,
that in some business parts of the town,
the merchants hired persons to cart the snow to the river.
We have not had so great a fall of snow for several years.

Third month 5th. This has been a peaceful day to me.
At supper this evening, during the precious silence,
I felt my heart clothed with reverence and thankfulness,
to our gracious heavenly Benefactor, for his many blessings, temporal and spiritual.

Several of our father`'s grand-children, and my sister H. Rhoads,
sitting around the table, we adverted to the days of our youth,
and felt as if we had the near unity and approbation of our dear
parents--long since entered the enjoyment of an everlasting,
glorious reward.

28th. My wife and I attended the first-day meeting at Springfield,
and next day their Monthly Meeting at Middletown.
To me it was pleasant to see so many Friends convene to
transact the business of the Monthly Meeting.
It gave the impression, that there was an honest concern among them,
to support our religious testimonies; and I felt united to some who offer willingly,
and desired they might increase in fervent devotion to
the good cause we are called to advocate in the earth.
So many have grown cold in their love to the blessed Truth,
that a concern was felt that a remnant may be kept, through faith and obedience,
who shall act nobly in the Lord`'s service;
and that many more may be drawn to join themselves to Him and to his cause.
Thus, from generation to generation,
a constant succession of living witnesses to his power, in themselves and in the church,
may be raised up, who shall be clothed with a lively zeal for the Lord`'s honor,
and to lift up the banner of Truth and righteousness,
in the clearness and authority with which our
first Friends displayed it before the people.

Fourth month 15th. Our Yearly Meeting of Ministers and Elders convened today,
and was smaller than I ever witnessed it, since I have been a member;
but it was a season of ingathering to the Master,
and I hope strengthening to the faith of some.
Some considered it one of the most favored opportunities they had experienced for years,
resembling seasons of instruction before the troublous times we have, in latter years,
endured.

24th. Our Yearly Meeting for business commenced on the 17th,
and was smaller than usual on that day, owing to the snow,
which had obstructed the roads in some places,
so as to detain some Friends from getting into the city;
and probably delicate persons may have been discouraged
from turning out by the inclement weather.

While reading the Queries and Answers on third-day morning and afternoon,
there was shown strong religious interest in the support of our christian testimonies.
Several Friends spoke pertinently to various departures from them,
manifested by the answers;
and a covering of solemnity and religious weight spread over us;
in which I believe the value of those distinguishing testimonies was felt by many;
and we may hope, through the illuminating power of the Holy Spirit,
their excellency may have been felt, in an increased degree,
and the true zeal stirred for living up to them more faithfully.
The younger part of the meeting had the opportunity of hearing the
instructive and persuasive remarks of some of their elder brethren,
whose services, no doubt, made deep and salutary impression on their minds.

A few Friends were verbally appointed to draft a minute on the
modern expensiveness and show in laying out the dead,
burying in grounds not under the care of Friends, and against monuments of wood or stone.
In the afternoon,
the same Friends were directed to prepare a
minute against a hireling or man-made ministry;
and admonishing Friends to abstain from going to
places where such a ministry is exercised;
thus acting contrary to the repeated advice given by the Yearly Meeting.

Throughout the week, the business was conducted with religious weight and much harmony;
every one, with little exception, acting with much propriety and decorum,
and showing a serious feeling of the importance of holding such a meeting,
and that all should conduct themselves as becomes the church of God.
The meeting closed on the 21st, in deep and solemn silence; under which,
many Friends parted in the tendering conviction,
that we had great cause reverently to bow before the Lord,
and to return thanks to his great Name,
for his mercy and kindness to us poor unworthy creatures,
in uniting and solemnizing us together, as we had been.

Fifth month.
I thought we had a solid Quarterly Meeting;
the extracts brought over it a solemnity that was felt.

20th. I have been several days closely employed at my store, assisting in the business,
and also in sending to distant subscribers, copies of Piety Promoted,
which my brother Thomas and myself, have recently printed.
While engaged in the labor,
the reflection that the valuable matter contained in this work,
will be thereby placed in the hands of many young people,
and through the Divine blessing,
may be the means of awakening sons and daughters to the work of their soul`'s salvation,
compensates for all the trouble, and raises the hope,
it may be instrumental in drawing them to the love of the Truth;
that by it they may be prepared for service in the church of Christ.
The hope of being made use of by the Lord, in turning many to righteousness,
sweetens the labor, and gives the feeling of not living merely for pecuniary gain,
but at the same time, contributing to the spread of the Redeemer`'s kingdom.

25th. I attended the Arch Street Monthly Meeting, which was very small,
especially on the women`'s side, the weather being wet.
In the first sitting, my mind was drawn into sympathy with some, who feel discouraged,
by the many evils which stand in the way of maintaining the cause of Truth,
and are ready to conclude, at times, they would lay us waste.
They were referred to our individual experience of the absence of the Beloved of souls,
and to his return, as we keep inward in faith and patience;
by which we are confirmed in his faithfulness to us.
We may then safely hope and trust that He will continue to visit us as a people,
and to raise up standard and testimony bearers;
and that the principles of the gospel given us to support,
will not be permitted to fall to the ground.
I believed there were those living, who would see the day,
though I was neither prophet nor prophet`'s son, when gifts will be given,
to be occupied in the church; by which the Lord`'s name will be glorified among us.
Those members who trample on our testimonies, and despise those who keep to them,
will find it a heavy burden, when laid on a death bed,
to have turned any aside from the faithful acknowledgment of them.

28th. First-day morning, we had a large meeting at our house in Orange Street.
The language of the apostle, "`It is a faithful saying and worthy of all acceptation,
that Jesus Christ came into the world to save sinners,
of whom I am chief,`" had been on my mind from the early part of the meeting.
The impression continuing, I ventured to hold forth the preciousness of this doctrine,
when brought home with living faith,
to a soul borne down with the weight of sin and transgression.
Such should remember, that a mere belief of these truths,
as recorded in the New Testament, would avail nothing,
unless they were brought to realize them in themselves,
by receiving Christ into their hearts.
It was testified, before He came in the prepared body,
"`You shall call his name Jesus, for He shall save his people from their sins.`"
If He is received in the heart, He will pull down the kingdom of Satan,
bind him and cast him out, spoil all his goods,
and make the heart a fit temple for Himself, by his Holy Spirit, to dwell in.
He will not dwell in a defiled heart, though He causes his light to shine there at times,
to show man his lost condition;
but this is not by way of union with him or taking up his habitation there;
that is experienced only as man is changed, and becomes a partaker of the Divine nature.
The doctrine of christian perfection, or freedom from sin, was also held forth.
It was a good meeting, and I hope tended to the strength of the right-minded,
and to the awakening of some.

Sixth month 4th. Feeling my mind very unexpectedly turned to the North Meeting,
I went there this morning.
The company was large, especially on the women`'s side.
I was favored to keep inward in a waiting state,
when the very important testimony to spiritual worship was brought before me;
also the great loss which is sustained by living to the world.
None can grow in the Truth, without experiencing the worship of God,
which is in spirit and in truth.
It is the christian`'s life, wherein he keeps the watch, maintains the warfare,
and receives ability to pray for daily food, and for preservation,
and to return thanks and adoration before the
Father of mercies for all his numerous benefits.
The indispensable necessity of experiencing it, and of attending our religious meetings,
when health permits, was impressed,
and the young men were invited to faithfulness in this respect.

27th. Having for some time felt a draft of affection
towards the little company composing Galloway Meeting,
at Leeds`' Point, in New Jersey, my wife and myself met our friends S. and B. N.,
at Haddonfield, on seventh-day morning, the 24th,
and proceeded in the cars about half the distance, when we took a stage,
and reached J. L.`'s before dusk.
He and his kind wife gave us a pleasant reception.
On first-day morning the weather was fine, which made walking to the meeting-house easy.
We understood the company was larger than usual, and appeared to be a sober people;
many were watermen, who trade from that neighborhood.
They maintained stillness during the silence of the meeting.
We were both engaged in the ministry,
setting forth the work of sanctification in the heart,
and encouraging the sincere christian, to hold on his way,
in following his Lord and Master.
My wife closed with solemn supplication for those who had wandered from the flock,
into the wilderness, and for the afflicted and depressed travelers,
who are longing for their own, and the salvation of others.

Next morning, we rode to Absecom, about six miles, to take the cars,
and reached our own homes before nine o`'clock.
Many calculations of profit are made by the projectors of this railroad,
running across New Jersey.
The enterprise of men furnishes many accommodations and facilities,
to promote the purposes of all classes;
which are highly useful to the great human family.
But it is to be lamented that, in the midst of much usefulness to others,
in a temporal point of view,
so many appear to neglect the "`one thing needful,`"
a daily preparation of the soul for a blissful eternity,
through waiting upon and serving God according to his blessed and holy will,
revealed in the heart.
This dedication to Him, would not interfere with right things,
in the way of our lawful vocations, but it would enable men,
under the power of the Holy Spirit, to keep the world under foot;
holding everything pertaining to it, in a secondary place; and above all,
laboring to exalt the name of our God, and the kingdom of his dear Son,
the Lord Jesus Christ.
In this state, there would be a harmonious walking with Him,
and the true welfare of each other would be sought and promoted.
