== Chapter XXX

1854--1855

Religious Visit to the Yearly Meeting of Ohio,
and some Meetings belonging to it--Resumption of Labors at Home.

1854, Seventh month 26th. Having had a prospect of visiting some meetings in Ohio,
and attending the Yearly Meeting, if the way should open for it,
I mentioned the concern to the Monthly Meeting, which made a minute of its unity,
setting me at liberty to attend to the prospect, as Truth should direct.

Eighth month 6th. First-day morning.
I was strengthened to lay before the young people the blessedness of an
early surrender to the visitations of the Shepherd and Bishop of souls.
He has gracious designs concerning all of us, and if submitted to,
will prepare for a place in his church.
Samuel was called in childhood, and shown the degeneracy of the house of Eli,
and was finally made a prophet, and he judged Israel many years.
Christ compared the kingdom of heaven to a householder,
who went out early in the morning to hire laborers to work in his vineyard.
Young people who are devoted to the Truth, have their trials,
but He who began the work of their regeneration, will carry it on,
sustain and defend them, and when He sees proper,
cheer them with glimpses of the beauty of the bride, the Lamb`'s wife,
the redeemed and sanctified church, and raise fervent desires to be purified,
and made members of it.

7th. My beloved brother Charles came down this morning,
and offered to accompany me through the visit to Ohio,
which was truly acceptable and encouraging.

12th. This morning, on going to my store,
I found a letter from my beloved and honorable friend Hannah Gibbons.
I thought it remarkable that she should feel so much for me,
without knowing the exercise I was passing through.
It was reviving and tendering to my spirit,
and I still hoped the Lord would cast up a safe path for me to walk in.
It is as follows: West Chester, Eighth month 11th, 1854.

My Dear Friend and Brother in the Truth, William Evans:

My mind has been so much in sympathy with you,
since hearing of your present prospect of religious service, that, though feeble in body,
I do not feel quite satisfied without telling you of it;
with desires for your encouragement in the line of religious duty;
well knowing that it is not the path we would choose for ourselves,
but that which leads to peace, far surpassing all mundane enjoyments.
There is an oppressed seed within the compass of Ohio Yearly Meeting; who,
I have no doubt, often go mourning on their way,
when the secret language of their hearts may be, "`Spare your people, O Lord,
and give not your heritage to reproach.`"
These, I believe, will be glad of your company, the aid of your spirit, and, I trust,
gospel labors.

The silent query has more than once arisen in my mind, of latter time,
"`Will not William Evans feel drawn to attend the approaching Yearly Meeting of Ohio?`"
And when I heard you felt an engagement that way,
I may say a feeble tribute of thanksgiving arose,
in believing that the Lord of the harvest is still mindful of his children;
those who are desirous of serving; Him in sincerity and faith;
and is furnishing fellow-helpers, in the arduous field of labor.
Truly there is strength in unity; and where there is a lack of it,
how does weakness prevail!
Yet I do believe the great I Am will be with those whom He has anointed and sent forth,
strengthening them for his work, and feeding them with food convenient for them.
And though you may meet with opposing spirits, dear friend,
yet as the clothing of your mind continues to be that of humility,
I trust you will be enabled, from time to time,
to put the armies of the aliens to flight; and the language of your heart, at seasons,
will be, "`Thanks be to God who gives us the victory, through our Lord Jesus Christ.`"
The encouraging language, recorded in Holy Writ, now arises, "`Fear not,
for I am with you; be not dismayed, for I am your God.
I will strengthen you, yes, I will help you, yes,
I will uphold you with the right hand of my righteousness.`"

My dear friend, your precious wife has a full share of my sympathy;
not doubting that she will be supported during your absence,
by Him whom she desires above every other desire to serve;
and I believe has cause to say, "`Hitherto the Lord has helped me.`"
The foregoing may serve to let you know that you have the sympathy and unity of a feeble,
almost worn-out sister; and in feelings of tenderness and affection,
I remain your friend,

Hannah Gibbons

21st. Second-day morning.
My brother Charles, who had kindly offered to be my companion through Ohio,
met me at the depot, and we left for Pittsburg.
The road through Pennsylvania, along the Susquehanna and Juniata Rivers,
is exceedingly picturesque and interesting; running through a mountainous country,
and many towns and villages, some of them nourishing and fast increasing.
Passing up the railroad, over the Alleghanies, by steam-power,
is a new feature in traveling; and when near the edge of vast precipices,
the idea of the connecting links of the cars breaking, or other causes,
overturning us into the deep ravines,
creates a sensation of fear and shrinking from
the terrible consequences that would follow;
but this is an interesting and expeditious mode of traveling, as well as comfortable,
when preserved to get safely to the end of the journey.
We reached Pittsburg, between twelve and one o`'clock, p.m. After breakfast,
the next morning, we went over to Alleghany City, and took the Cleveland cars for Salem.
We reached the station house there, about eleven o`'clock;
where we found our kind friend Jehu Fawcett, waiting to accompany us to his house.
The hearty manner in which he met us, was cheering.
Sitting in his house, I felt peaceful.

23rd. Salem Monthly Meeting was held here, which we attended; the company was quite large.
After some time of enduring poverty and emptiness,
I was led to hold up the importance of keeping with the seed under suffering,
that we may fill up our measure of it; and in the humbling,
stripping dispensations we have to pass through,
we may experience a growth in the blessed Truth.
After relieving my mind of the subjects that were brought before me,
I felt the spirit of supplication, on behalf of those who were bearing heavy burdens,
and was constrained to bow the knee,
and implore the merciful and tender regard of the Lord, our Holy Helper, on their behalf.
We went out about a mile to our beloved friend David Fawcett`'s;
dined with him and his children, and had a little opportunity with them;
in which the tendering power of the Holy Spirit was felt.

24th. Fifth-day.
Our friend David Fawcett,
inclining to accompany us to the remaining meetings in this neighborhood,
called upon us this morning, and took us over to New Garden.
It was a pretty large collection; among whom I had some service;
and after the Monthly Meeting, we went to a Friend`'s and dined.
A number of Friends came in,
to whom I felt drawn to speak on the importance of bringing up
children in the nurture and admonition of the Lord;
restraining them from evil company and practices.
Were they rightly concerned to fulfill their duties to their beloved offspring,
they and the dear children would reap the benefit of it.
As they come under the yoke of Christ,
they would be united together in the fellowship of the gospel,
and be as marrow to the bones of their religiously exercised parents.
Took an affectionate leave of these dear Friends, and rode about seven miles to E. M.`'s,
near Hanoverton.

25th. Attended Sandy Spring Monthly Meeting; in which the work among them was laborious,
but I endeavored to do what the Master required.

26th. We went to Springfield Monthly Meeting, at Damascoville.
Here I was opened on the declaration of our Savior,
"`By this shall all men know that you are my disciples,
if you love one another,`" and on the importance of
knowing the love of God shed abroad in our hearts.
The nearer we approach a better world, the more earnest we ought to feel,
to be imbued therewith; that we may be prepared for the society of saints and angels,
and the spirits of just men made perfect.
In this world, this Divine clothing would put an end to all animosities,
wars and fightings, and whether present or absent,
we should be as epistles written in one another`'s hearts; not with ink and pen,
but by the Spirit of the living God.
It would draw the children to the parents, and the parents to the children,
and they would unite in going up to the mountain of the Lord,
the house of the God of Jacob, who would teach them his ways,
and strengthen them to walk in his paths.

27th. First-day morning.
Our kind friend Jehu Fawcett, took us to Middletown, about twelve miles;
where we attended the meeting,
and had to feel with some who seemed to have
greatly let fall the daily religious exercise,
which every living member ought to experience.
Some things were set closely home,
in that love and concern which seeks the everlasting welfare of every class;
which I believe had something of an arousing effect.
We believed there were honest-hearted ones preserved amongst them,
who are sincerely concerned for the right support of the cause and testimonies of Christ,
and feel for the low estate of others, and on account of their unfaithfulness.
I had some service there to my own satisfaction and peace.
We dined with our ancient friend William Heald, and the widow of his son Abner Heald,
who was a minister.
The old Friend, between eighty and ninety, has the use of his faculties,
and appears to be desirous of the welfare of the Society,
and the maintenance of its doctrines and testimonies.

28th. Jehu Fawcett having made provision for taking my
brother and myself with him and his wife,
to Mount Pleasant, in the afternoon, we left his agreeable residence,
and rode to our friend E. M.`'s, near Hanoverton, about twelve miles from Salem.

29th. We took an early start, having a long day`'s drive before us; over a hilly country,
the weather warm and very dry, and the roads dusty.
At the tavern where we dined, water was scarce.
Towards evening, we got to a Friend`'s house, not far from Smithfield,
and were kindly received.
Here the drought was so great,
that there was nothing left in the fields that the cattle could subsist on;
and they told us they had been obliged to give them hay, etc, for about three weeks.
Water was also so scarce,
that they had to drive their herds and flocks some miles to get sufficient for them.
The appearance of the country was desolate and mournful;
and I thought should induce a humble consideration of our
dependence on Divine Providence for the means to sustain life;
and also self-examination of our actions, in the light of the Lord,
that we may profit by the dispensations of his chastising hand;
and experience greater redemption from the love of the world,
and devote our time and our talents more constantly to
the work which He would appoint for us to do.

30th. We attended Smithfield Meeting, which was larger than usual,
a marriage being accomplished, which drew some to it.
Feeling a concern gathering over my mind, for some who had known better days,
and on account of the great change that had taken place in the members,
in part produced by the death of some substantial ministers, I was led to advert to it,
and mentioned the language of Scripture, "`Your fathers, where are they;
and the prophets, do they live forever?`"
Those were removed to their everlasting reward;
and there was but one way by which any could be prepared to succeed them,
in these stations in the church, and that was by submitting to the humbling,
regenerating power of the grace of God.
Some were called upon to recur to the kindness of their youth,
the love of their espousals,
how they followed the Lord in his leadings into the wilderness;
and to examine whether the same love and devotedness to Him was now felt,
which they then experienced.
If not, there was nothing in the world that could make up for their loss;
and if in his continued mercy, they were favored with renewed visitations of his love,
and the calls of his Holy Spirit, it would be their highest interest to yield to them,
that they might be favored with the enjoyment of the
true peace and heavenly love they had once known.

31st. Attended the meeting at Harrisville, and returned to N. H.`'s,
where we stayed that night; and next morning were taken by him to Flushing,
where we had an appointed meeting,
which was a favored time in testimony and supplication.

Ninth month 2nd. Seventh-day.
Rode to Mount Pleasant, and put up at the school-house,
and I attended the Yearly Meeting of Ministers and Elders.

First-day.
Two large meetings for worship were held.

9th. The Yearly Meeting was held this week;
but little business being transacted on second and third-days.
Forty-two representatives met; and twelve of them,
contrary to the expressed opinions of the others,
determined to take forward the names of two men, for clerk and assistant,
which the others protested against;
and twenty-eight desired a Friend to report that
the representatives were not able to agree;
which was done.
The existing clerk informed the meeting,
that according to the practice of that Yearly Meeting,
he should make a minute continuing and appointing the present clerks,
B+++.+++ Hoyle and William S. Bates, as clerk and assistant;
with which many Friends expressed their unity.
The two members, nominated by the twelve representatives, being urged by their party,
to take their seats at the table, went up and sat alongside of B. H.;
when he informed them that their attempt was an act of separation.
Their proceeding was spoken against; but being repeatedly called upon to make a minute,
one of them made an entry of their being reported by a
part of the representatives for clerks,
and that they were appointed; Friends, in the meantime, objecting to it.
After sitting between three and four hours, the meeting adjourned,
B+++.+++ Hoyle making the minute.

Previously two women Friends inquired the hour to which men Friends would adjourn,
but the meeting not having decided,
they were requested to adjourn to the same hour at
which the men`'s meeting should decide to convene.
When Friends left the house, the separatists kept their seats,
and adjourned to eight o`'clock; two hours earlier than Friends had agreed to meet.
The separatists met accordingly, and broke up their meeting, just as we were collecting,
which was considerate on their part.

My feelings were mournful at witnessing another separation in that house,
after a lapse of twenty-six years;
yet I could not see that Friends could have acted in any other way,
consistently with order, and the practice of their own Yearly Meeting.
The meeting read the epistles addressed to it; read the Queries and Answers thereto;
decided to establish a new Quarterly Meeting,
to be composed of that part of Stillwater Quarterly Meeting,
which lies on the west side of the Muskingum River;
appointed a committee to visit and aid the subordinate meetings,
in this season of severe trial; with several other subjects,
including epistles to the other Yearly Meetings, and concluded under a solemn quiet.

Our friend H. L., residing near Mount Pleasant,
having offered to take us in his carriage to the
meetings in Stillwater Quarterly Meeting,
we rode out in the afternoon to a Friend`'s, at Plainfield.
The next morning, before leaving this family, I had an opportunity with them,
encouraging the young Friends to greater dedication,
and a deeper indwelling with the Spirit of Christ, that they may be prepared thereby,
to discharge their duties in the church, and to their children.

10th. We reached B. H.`'s about ten o`'clock, and went to their meeting at Stillwater;
which was a pretty large company.
It was a laborious time to me, yet attended, I hope,
with encouragement to the burden-bearers, and the sincere-hearted among them.
In the afternoon, we visited Wm. Green, and his wife and family,
who are rightly concerned and interesting Friends; the visit was to my satisfaction,
a number of young persons coming in.

11th. We set out pretty early this morning, for the Muskingum settlements,
having the company of several Friends returning to their homes beyond that river,
and rode about forty miles, dining at a tavern,
and lodged at a house of private entertainment.
The landlord was a Methodist, and an intelligent man;
with whom I had some conversation on the doctrine of christian perfection,
and being made free from sin in this life.
He thought there was danger of a man thinking himself free from sin,
and trusting to his own righteousness.
I told him the more we were brought to experience the sanctifying power of Divine Grace,
the more humble would be our opinion of ourselves;
and the more we should depend upon the Lord Jesus to make, and to keep us so.
Christ said to the people, "`Be perfect, even as your Father, which is in heaven,
is perfect.`"
He loved the church and gave Himself for it,
that He might present it to Himself a glorious church, not having spot or wrinkle,
or any such thing, but that it should be holy and without blemish.
Also, that He might purify unto Himself a peculiar people, zealous of good works.
He did not deny this, yet did not seem quite ready to receive the doctrine.

Next morning we had further conversation on another point, in which he was at difficulty,
and said he thought the passage I quoted, respecting being perfect,
was designed for the apostles.
I reminded him that it was contained in the Sermon on the Mount,
which was addressed to all his disciples, and was applicable to the multitude,
as well as to us, also, in this day.
We heard afterwards that he expressed much satisfaction with our visit,
to some Friends who called and took breakfast with them after we had gone.
It is always cheering to meet with sincere, religious people,
let their christian profession be as it may,
and to find they have some experience of the work in themselves.

12th. We rode to McConnellsville, crossed the Muskingum,
and put up at our friend John Patton`'s, who belongs to Hopewell Meeting.

13th. Had an appointed meeting here, in which I felt depressed, also not well in health.
But I was raised up to declare the way of salvation, to the disobedient,
and the awful consequences of out-sinning the day of their visitation.
The honest-hearted, and the poor of the flock,
were exhorted to hold fast the grain of true faith, in their lowest seasons;
and the Lord would assuredly come again to them; the meal in the barrel should not waste,
nor the cruse of oil fail,
until He sent forth fresh supplies of temporal and spiritual food.
Some saluted us with much affection,
and their countenances showed they had felt the tendering power of Truth,
to contrite their spirits.
J+++.+++ P. and his wife, met us here, and took us to their house at Pennsville,
where we were kindly and agreeably entertained.

14th. Attended Pennsville Monthly Meeting.
In the first meeting,
I could come at nothing like authority for the work of the ministry,
and at a suitable time, Friends proceeded in transacting the business.
Near the close,
I was impressed with a concern to call Friends
to a closer attention to their religious duties;
that they might show forth the excellent fruits of the Spirit,
by setting the candle on the candlestick, that all might see the light;
not putting it under a bed of ease, or under a bushel,
in the multitude of worldly pursuits.
Christ told his disciples, they were the light of the world,
and that they were to let their light shine, that others, seeing their good works,
may glorify our Father, which is in heaven.
I was also concerned to remind parents of the responsibility of their station,
as shepherds and shepherdesses over the lambs committed to their trust;
of the necessity of setting them a proper example, of restraining them from evil,
and to bring them up in the nurture and admonition of the Lord.

16th. We attended Chesterfield Monthly Meeting; in the first sitting,
I was renewedly helped to preach the gospel of life and salvation,
to comfort the mourners in Zion,
and to stir up the young and the middle-aged to greater faithfulness.
If any good is done, it is from the Lord.
We are unprofitable servants; He can work with or without us.
In the afternoon, T. P. went with us to Plymouth.

17th. Rode down to a meeting called Southland, being first-day.
This was a laborious time to me; it seemed hard to find the stepping stones.

18th. Attended Plymouth Monthly Meeting which was quite large,
many goodly looking young men belonging to it.
I had service among them relating to the occupancy of gifts in the church,
bestowed by our adorable Head, and Minister of the sanctuary,
upon those whom He has prepared, by the washing of regeneration,
and the renewing of the Holy Spirit, to receive them.
I believe there were those in that meeting whom, if they continue faithful,
He would make judges and counsellors, as they steadfastly followed his Divine leadings.
The business was transacted with religious weight,
and sweetness of spirit and manner towards one another.
Several Friends from other meetings were there.
The Friends with whom we took dinner, were truly kind,
in accommodating us with an early start after the meeting,
to enable us to get on that afternoon, so as to reach Somerset by the next evening.
We got a list of the towns to enquire for on our way, and by industrious traveling,
reached a house of private entertainment, about dusk, having crossed the Muskingum,
and ridden about seventeen or eighteen miles.

19th. Rose early, but the tediousness of those who prepared breakfast,
detained us unnecessarily.
We rode about twenty-five miles before we could obtain food for ourselves and horses,
without stopping too early in the day.
The road over which we travelled, was in bad condition, in some places, and very hilly;
there being no place in this half-day`'s drive, in which there was half a mile of level,
plain road continuous.
We set out again, and when we drew near to Somerset, the road improved,
though still crossing a continuation of high hills.
It became so dark that my brother was obliged, in the last three-quarters of a mile,
to walk in the middle of the road, before the horses,
to enable the Friend to decide where to drive; but we got to T. P.`'s safely,
and felt grateful at again reaching the pleasant habitation of our friends,
where we were kindly received and comfortably accommodated.

20th. We had five miles to ride to the place
where their Preparative Meeting was held today.
The company was small, and according to my feelings, the stream of Divine life was low.
I was reminded of the low state of the springs and streams
through the country where we had travelled and referred some
of them to the consideration whether their condition,
in a spiritual sense, might not bear some resemblance to it.
I hope some were aroused to look more seriously into their own condition,
and seek more ardently for the streams of that river which makes glad the city of God;
like David, who said; "`As the deer pants after the water brooks,
so pants my soul after you, O God; my soul thirsts for the living God.`"

We dined in company with a number of Friends, at the house of a widow woman,
and I had conversation with them on the importance of Friends
endeavoring to keep together in near unity with one another.
I advised them, in performing their duties when visiting their divided meetings,
in order to keep Friends from being scattered, to be swift to hear, and slow to speak;
for solidity and inwardness of spirit, would have more effect to convince gainsayers,
than many words.

21st. Went to the Ridge Meeting;
and was there introduced into much sympathy with the burden-bearers;
to whom the language of encouragement flowed freely,
under the humbling power of Divine love, and in the fellowship of suffering;
I hope to the refreshment and strengthening of some,
though I was left under feelings of weakness and poverty.

Towards evening, we took leave of these Friends, rode to B. H.`'s, at Stillwater,
and were cheered in getting under his roof.
Our friend A. G., having agreed to take us, in his carriage, to Brownsville,
had returned home to prepare, and before bed-time met us here;
a further proof of the disinterested kindness of Friends towards dependent travelers,
in carrying us from place to place; our friend H. L., being obliged,
after leaving us at St. Clairsville, to return to his home.
We rose pretty early next morning, and proceeded to that place,
where having dined and fed our horses, we parted with our much esteemed friend H. L.,
of whose kind attentions and assistance, we had so freely partaken,
and for which we expressed our grateful acknowledgments.
We had a pleasant ride of about twenty-six miles, to a little village called Alexandria,
and put up at an inn of tolerable comfort.

23rd. Got away from this place early after breakfast,
passed through a town called Washington, and about four miles beyond,
got a humble dinner at an old worn out inn, and then winded our way over hill and dale,
to the Monongahela River, and crossing it on a fine bridge; opposite to Brownsville,
we reached the residence of our friends W. D. and wife,
who received us with much cordiality.
I had never before been at their house,
but found it a pleasant home for christian travelers on religious errands.
W+++.+++ agreed to release A. G.,
and take us in his carriage to the two meetings we
proposed being at before the finishing of this journey.

24th. Before leaving, on the following morning,
we went into the residence of Wm.`'s aged father;
where I was led to hold up the importance of waiting upon the Lord,
that the work of preparation for a better world, may be perfected,
and Divine refreshment partaken of daily from his hand.
On our return, we dropped into silence,
and a word of counsel and encouragement arose in my heart for those dear Friends,
under their tried situation; brought about by the late separation;
there being but themselves and one other family,
likely to remain with Friends belonging to Ohio Yearly Meeting,
in this particular meeting; as we were informed.

The road to Providence meeting-house is very hilly,
and the distance seven or eight miles,
so that we did not get there until the Friends were nearly all convened.
On sitting with them,
I felt for the little remnant who love the Truth and seek its prosperity,
and now have new difficulties to encounter,
in the prospect of another division of their reduced Quarterly Meeting.
I was led to encourage this class, to labor to draw near to their Lord and Master;
looking to Him for guidance in their religious duties,
and for the renewal of their faith and strength to do his will.
He joined Himself to the two disciples,
as they walked from Jerusalem to Emmaus and were sad, under the loss of their Master,
as they supposed; and He opened to them the Scriptures, in the prophets and the Psalms,
concerning Himself; so that when He disappeared,
after blessing and breaking the bread at the table, they knew it was He, and said,
"`Did not our hearts burn within us, while He talked with us by the way,
and while He opened to us the Scriptures?`"
He is as near to his children, watching over them, at this day as ever;
and He will keep and console them, as they hold fast their love and allegiance to Him.
Some states of a different character were also spoken to.

We had rather a tedious ride to Sewickly;
the hills rising from the different streams being long and high;
yet with diligence we arrived at G. G.`'s, about dusk;
and were glad to find ourselves at the door of kind and hospitable Friends,
willing to take us in, and make us comfortable and welcome.
Enquiry was made if we could get a meeting there next day, at the usual hour,
and being assented to, they sent out word that evening,
to spread notice of it early next morning.

25th. We went to the meeting-house, and found a pretty large company for that place;
with whom we sat in silence for a considerable time, in a low place;
the quickening power of Christ seeming to be much out of sight and feeling.
At length I was enabled to labor among them,
to show the spirit and element in which a true christian lives;
wherein he is enabled to worship God in spirit and in truth,
out of meeting as well as in meeting, to the refreshment and strength of his own soul,
and also for the help of others.
A warning was also held up against the inordinate pursuit and love of lawful things;
by which, even those who have known and loved the Truth, may lose ground,
and become captivated with worldly pursuits.
I felt drawn, though in weakness, to bend the knee,
and to pray for those on whom the support of the ark of the testimonies chiefly rested,
in that place; that their faith and devotion to the cause of Christ might be increased;
and for those who are afar off, wasting their substance;
that they might arise and come to the Father,
and acknowledge they were unworthy to be called his sons,
and ask that He would make them his hired servants; also for all now before the Lord;
that He would keep us through the remaining tribulations of this life,
and prepare us to mingle with the just of all generations,
in praising and glorifying his great Name, with the Lamb, world without end; Amen.
I came away peaceful, though poor and empty; which is a safe state,
and I believe is often dispensed by Him who knows what is in man,
and what is best for our humiliation before Him; that self may be kept in abasement;
and we be sensible that we are unprofitable servants, that all good comes from Him,
and all praise and glory is due to Him alone.
We dined with B. G. and family, where several Friends came.

Just as we were about to come away,
I felt constrained to address the parents and children;
to encourage the former to watch over and restrain the latter from wrong things,
and to live under a proper concern to draw them to Christ,
that He might lay his Divine hand upon them, and bless them.
It had a tendering effect upon the mother and some of the daughters,
for which I was glad, and confirmed that I was in my right place.

26th. A station on the Pennsylvania Railroad,
being about seven miles distant from G. G.`'s, some of the family rose early,
to give us breakfast; and our kind friend took us there in his carriage,
in time to meet the train for Philadelphia.
After taking leave, we started a little after eight o`'clock,
and got to our beloved homes, between one and two o`'clock, next morning.
I found my dear wife and children in usual good health,
and felt thankful in being restored to them in safety,
and in the peacefulness and true comfort,
which the Lord bestows for the performance of his requirings.

Eleventh month 6th. The Quarterly Meeting was held this morning.
There was not much business to occupy the last sitting; and after it was gone through,
I returned the minute furnished me to make the visit in Ohio;
informing that it had been accomplished to my own peace and satisfaction.

14th. My wife and myself went to Salem, to visit our beloved friend Martha Wistar,
and also some of our friends and connections at Greenwich.
In seasons of great discouragement, it is strengthening to them that fear the Lord,
and think upon his name,
to speak to one another of those things that lie nearest to their hearts;
not only because it is declared that a book of remembrance is written before Him,
who hearkens and hears;
but also because in their different conditions
they minister support to the oppressed spirits,
and cheer them at times on their way.

15th. We attended the Quarterly Meeting of Ministers and Elders, at Salem,
in which we were silent.

16th. Was held the Quarterly Meeting for discipline.
In the first meeting, I was engaged to revive the exhortation of the apostle,
"`If we live in the Spirit,
let us also walk in the Spirit;`" and to enforce the
importance of showing by our conduct and conversation,
and the weightiness of our spirits, that we have been with the Lord,
and that He is with us.
It is the lack of bringing forth the fruits of the Holy Spirit,
that keeps the Society in weakness, and impairs its usefulness in the world,
and greatly disables the members from aiding each other towards a growth in the Truth.

At the house of our cousin George Bacon, at Greenwich, the old-fashioned,
sincere hospitality is found; he and his wife being honestly concerned,
and cordial in receiving their friends.
We attended their meeting on first-day; in which we had some service;
the company assembled being larger than usual.
I was led to advert to the negligence of many in making a proper use of the
outward means dispensed by the Head of the church for our benefit,
especially the frequent reading of the Holy Scriptures; the fear attending me,
that very many seldom look into their bibles;
although the Holy Scriptures were given by Divine inspiration,
and are profitable for doctrine, for reproof, for correction,
and for instruction in righteousness, that the man of God may be perfect,
thoroughly furnished unto every good work.

Twelfth month 10th. At our first-day meeting, this morning, after long waiting,
in which many things passed before me,
and the feeling of a disposition to put by the opening,
I was constrained to rise with the expressions used by one of our ancient Friends,
"`There is a faith that overcomes the world,
and there is a faith that is overcome by the world.`"
It is a great favor to be possessed of the knowledge of
the doctrines of the everlasting gospel,
as recorded in the Holy Scriptures, and for which we are bound to be thankful;
but the faith which gives us the victory over the world, the flesh and the devil,
is produced by the operation of the Spirit of Christ in the heart.
This Spirit reveals those things which it requires us to forsake, and gives us,
at the same time, if we receive it,
faith to believe that what is required is the Divine will; and as we are obedient,
brings us out of our fallen condition,
and gradually opens to us the Scriptures according to the Lord`'s will,
and enables us availingly to believe in the Lord Jesus Christ,
and in the authority of the Holy Scriptures, and to profit by them.
By the obedience of faith, we experience a growth in grace,
and are made victorious over Satan and all his temptations;
and participate in the promise of the Son of God, "`To him that overcomes,
will I grant to sit with me in my throne, even as I also overcame,
and am set down with my Father in his throne.`"

The divinity, atonement, intercession and advocacy of our Lord Jesus Christ,
who was crucified without the gates of Jerusalem,
a propitiatory offering for the sin of the world,
and is now glorified at the right hand of the Father,
was also plainly testified to and held forth according to the Scriptures.
These things were delivered in humility, as they were brought before me, I trust,
by the good Remembrancer, and reached the hearts of some present,
to their comfort and satisfaction.
It is good to be faithful to the pointings of the Divine finger, in childlike simplicity,
not knowing what is the Lord`'s design, and the consequences that may grow out of it.

21st. We have had some very cold weather, and so many people being out of employment,
there is reason to apprehend there will be great suffering;
but I hope those who have the means to spare, will be alive to their needs,
and strive to provide for them.
Owing in part to the wars in Europe,
the price of provisions is much above the usual standard;
which increases the difficulties of the poor, and the laboring man,
and lessens the ability of others to aid them.
But if there is a heart to give, in those of moderate means, they will economize,
and find portions to bestow on the poor.

This day, I attended the Arch Street Meeting, in much destitution, and was furnished,
I thought, with strength and authority to encourage others to endure temptation,
and to strive to keep the faith.
The dear children were also invited to yield to their Savior`'s requirings,
that they may be prepared, in his time,
to be made instrumental in turning many to righteousness.
They who do so, shall shine as the brightness of the firmament,
and as the stars forever and ever.

31st. The last day of the year, and the weather now remarkably fine.
Our meeting this morning, at Orange Street, was pretty large for us;
and a time of favor and gracious condescension to our low estate, it proved to be.
The breathing of my spirit was, that the Lord would visit our Society,
and pour out afresh of his Spirit upon sons and daughters,
and prepare many to sound his praise,
and to tell to others his wondrous works in their souls.

1855, Second month 8th. The weather has been extremely cold for several days,
the mercury in some parts of the city, being below zero;
and notwithstanding the severe cold, snow and hail have fallen.
The sufferings of the poor are great,
and much money has been raised and applied for their relief.
I have not heard of any being frozen to death;
but some are reported to have suffered starvation,
being unwilling to let their condition be known.

Went to Abington Quarterly Meeting.
I was enabled to open the great importance of partaking of the Divine life,
which Christ declared He came that his sheep might have,
and more abundantly than under the preceding dispensation.
Those who are united to Him as members of his body,
are kept alive unto God by the life of Christ, that flows from Him into them;
and as they submit to his humbling dispensations and baptisms,
they are prepared to hear his voice, and to distinguish it from all other voices.

In the second meeting, the beauty and excellency of our discipline and order,
were upheld; conforming as they do, to the doctrines of Christ and his apostles;
and which all among us, who are alive in the Truth, will feel bound to support,
as a trust and duty given to us, which is sacred.

26th. Rode out to Springfield, and attended their Monthly Meeting.
I was drawn forth in sympathy with those who love the Lord Jesus Christ,
but are in danger of turning aside, from the discouragements of the day;
as though their forefathers had not drunk as bitter cups,
and it was easier then than now to do the Divine will.
But I was led to declare, that He who called to any duty,
was as compassionate and tender to his children as ever;
and would always make way for them, and give strength to perform it,
as a single eye was kept directed unto Him.

Third month 12th. This day being Haddonfield Monthly Meeting, I rose early,
crossed the Delaware, and by the cars, reached the village about eight o`'clock.
We had a good meeting; in which the call to greater dedication was extended,
and prayer offered for the young people, and the discouraged burden-bearers,
whose hands were ready to hang down.

20th. Went to the Northern District Meeting;
where the necessity of the inward work of religion was opened;
in which the axe is laid to the root of the trees,
and every tree that brings not forth good fruit
is to be hewn down and cast into the fire.
Sound doctrine, held in the head, and on the tongue, will avail but little.
We must submit to Him who baptizes with the Holy Ghost and fire;
who gathers the wheat into the garner and burns up the chaff with unquenchable fire.
In this way only, shall we know the possibility of being made free from sin in this life,
and true witnesses of the Lord`'s saving power,
and of the truth of the doctrines of the everlasting gospel.
I expressed the belief,
that our religious Society would not be permitted to be laid waste;
but from among the pots, and as from the stones of the streets,
the Lord would continue to raise up those whom He would make living ministers,
and discerning elders in the church.

Fifth month 12th. Went out to Springfield,
and spent a short time very cheeringly with our beloved brother and sister,
Joseph and Grace Evans.
We find a little interaction between town and country relations,
revives and animates each other to hold on in the good pathway,
and imparts comfort and strength, in the unity of the Spirit in the bond of peace.

14th. Went with them to the Quarterly Meeting of Ministers and Elders, at Concord.
We sat a long time in silence; and after the Queries were read and answered,
and the business got through,
I ventured to speak on the responsibility of the stations of ministers and elders.
If I know anything of the nature of gospel ministry,
it is that only which is opened in the soul by the great Minister of the sanctuary,
and which He authorizes to be given to the people, as it is given to us;
and the design of it is to gather souls to Christ.
Elders are to receive the gift of spiritual discernment,
and to aid and counsel ministers, under the Lord`'s direction.

15th. Was held the meeting for business;
in which I was engaged to address the younger members.
I felt remarkably peaceful,
in having labored for the encouragement of the young people who love their Lord,
and to awaken the rebellious to their true conditions.

Seventh month 4th. This afternoon, I went to attend, from his late dwelling,
at Westfield, the burial of our friend Samuel Leeds, a minister;
who was taken sick before our Yearly Meeting.
He is reported to have said little throughout his sickness,
appearing to be abstracted from worldly things,
and very much kept in a quiet frame of mind.
The removal of the servants of Christ from among us, one after another,
was very affecting to me, as I stood by the grave,
and saw his remains lowered into the earth.
The spirit that often had been baptized for the dead, and for the living,
tribulated seed, was now gathered unto God, and to his Christ,
among the blessed of all generations.
Will not the Lord have compassion upon his church and people,
and give evidence that He has not forgotten their desolate condition,
by pouring out of his Spirit on sons and daughters,
and giving gifts for the work of the ministry, and the edification of the body of Christ.
Even so, O Lord!
Amen.

20th. For many days, little pleasant bread has been partaken of.
Our religious meetings, now much reduced by many members having removed into the country,
or traveling for pleasure and health,
have often to me felt destitute of the sensible evidence of the Divine presence;
so that fears have prevailed, of being deserted by the everlasting Shepherd.
Then again, I have been afraid to abandon the watch and the struggle,
lest indifference and the total loss of spiritual life may ensue.
Of late, in the midst of many fears,
I have thought the Lord`'s mercy and watchful care were not withdrawn,
by feeling a little ability to look to Him, and to put up secret prayer,
accompanied with contrition of spirit,
that He would continue to regard an unworthy creature, and defend and keep from falling,
one whom Satan seems constantly striving to cast down and destroy.

The trials of this day are hard to bear,
but if they drive us more and more to the Master, and keep out a light spirit,
and deepen us in the blessed Truth,
so that our example will be effectual to draw others to the love of it,
they will be great blessings to us,
and fit us for greater service in the Lord`'s church and vineyard.
We have depended much on one another,
instead of relying upon the Lord alone for guidance, wisdom and strength;
and He has been taking from us fathers and mothers,
and permitting the spirit of separation to get in,
by which many Friends have been alienated from each other.
The unity of the Spirit being greatly lost, the strength which it gives is much withdrawn.
There is no way by which the strength of the church can be restored,
but by the members coming back to the first principle,
of individually waiting upon the Lord,
and seeking to receive from Him the spirit of prayer, that He would return to us,
and show us our real condition; what He would have us to come out of,
and the high and holy way He would have us to walk in.
His mercies are the same from generation to generation;
and when we are rightly humbled and brought back,
He will condescend again to our low estate, and lift us up,
and put songs of praise into our mouths;
and the children will be enabled to join in thanksgiving and
praise to his great and ever-adorable Name.

Eighth month 4th. Our Select Quarterly Meeting was held in silence,
and felt to me to be a low time,
little evidence of Divine consolation stirring amongst us.

5th. First-day morning, at our own meeting, I felt drawn to revive the injunction,
"`Be still, and know that I am God;`" also the gracious declaration, "`I am God,
and change not, therefore you sons of Jacob are not consumed.`"
The indispensable need of this inward stillness and constant waiting upon the Lord,
that we may know Him, through the operation of his own Spirit upon our hearts,
was held up; by which, in prayer to Him,
we shall be delivered from the power of the enemy,
who would destroy us by his temptations,
and lead us to cast away our confidence in the Lord`'s mercy and protecting power.

6th. I went to our Quarterly Meeting, under depression and fear.
There was a season of solid quiet over the meeting; during which, I believe,
souls were brought to hunger and struggle for a blessing.
Communications were delivered which directed to the great work of salvation.
Some were warned of the consequences of being ashamed of Christ before men,
in denying the simplicity which He requires,
though they might confess Him with the tongue.
I rejoiced in the evidence furnished, that the Lord was still mindful of us,
and extended his mercy towards us.
How is this meeting changed by the removal of
substantial and dignified ministers and elders by death;
but I trust others are preparing for service in Christ`'s church.

16th. Having some pointings to Salem Quarterly Meeting,
and feeling tender sympathy with discouraged ones there, I went to Woodbury.
The meeting was about the usual size, and the Lord condescended to give the word,
and authority to declare it.
I felt engaged to press upon all,
the need of being diligent in the work of their soul`'s salvation,
which no man can do for us.
The Lord`'s quickening power, I believe, was felt among us,
and Friends appeared to be glad to have us with them.

21st. I was at the North Meeting;
in which I was led to warn some of the danger of unwatchfulness,
and taking flight in the winter season, or on the sabbath-day.
Man is not to live by bread alone,
but by every word that proceeds out of the mouth of God.
We must endure patiently his appointed means for our refinement,
that we may be prepared for his return to our souls,
and be preserved from losing the little we had already gained.

29th. Many of our friends have been absent from the city this summer,
and though we have enjoyed much peace, the lack of their society,
and the smallness of our meetings,
make a blank that causes us to feel some languor and emptiness, which is depressing.
As the true harmony and fellowship subsist in the Society,
we shall be more one another`'s strength and joy whether present or absent.
But the present sense of weakness may contribute to our humiliation,
and safe keeping on the watch.

Ninth month 12th. Rode up to Medford,
and attended Haddonfield Quarterly Meeting of Ministers and Elders,
in which we felt much with a suffering remnant there,
to whom my wife ministered in a consoling manner.
Went to the mansion of our beloved friend Lydia Stokes.
The society of this aged Friend, as well as of some others,
was attended with feelings of peacefulness and sweet unity.
She is another of the pillars in the Lord`'s house, who has a heavy burden to bear,
and who we cannot expect will be much longer continued in this militant state.

Here we heard the affecting intelligence of the death of our much valued friend,
Sarah Hillman, of the Northern District; a sound minister of the gospel,
and possessing a clear understanding in matters pertaining to the service of the church,
beyond most of her years.
Her removal was quite a shock to me, though I had heard she was very ill;
yet secretly hoped it might be consistent with the Divine will,
to prolong her life to old age, for the church`'s sake,
which feels the need of the help of such exercised ones.

13th. Went to the Quarterly Meeting, under heaviness of heart.
It was a large collection of people,
and a sense that individual concern for their own salvation,
was greatly lacking in a large number, was the prevailing feeling of my mind.

After a time of silence, I believed it right to rise with the testimony,
that religion is an internal work, between the soul and its Almighty Creator;
and was led to open the doctrine, that in his mercy,
He gives every one a sight of his condition in the fallen, transgressing nature,
and if he receives the Lord Jesus in his appearance in the heart,
He not only shows him his sins, but will give him power to forsake them,
and grant repentance and forgiveness.
He breaks down the kingdom of Satan, casts him out, and prepares the soul,
by the baptism of the Holy Ghost and fire, to be a temple for him, by his Holy Spirit,
to dwell in.

Tenth month 1st. The printed minutes of Ohio Yearly Meeting, which have been received,
are comforting,
in the belief that Friends there had been favored with
the presence of the Head of the church,
qualifying them to transact their concerns for the edification of their members,
and the exaltation of the Lord`'s name and honor.
Their trials are great, from having been wrongfully rejected by other Yearly Meetings,
while those who separated from them have been acknowledged as a Yearly Meeting.
I hope the Lord will judge between them,
and grant patience and faith to his afflicted children, to hold on in the right way,
to the support of his cause, and the growth of the members in the Truth.

18th. Feeling drawn to attend the burial of our late beloved friend, Margaret M. Smith,
my wife and myself went up to Burlington for that purpose this morning.
A terrible catastrophe occurred on the New York Railroad, a few miles north of this town,
by which a number were killed, and others wounded.
Many of them were brought to Burlington, and this dear Friend,
whose heart was ever ready to sympathize with the sufferer, had a man and his wife,
in a maimed condition, brought to her house, which she gave up almost entirely to them,
their connections and servants; herself rendering much assistance in nursing them.
A scene so affecting and so different from anything she had participated in,
by which her feelings could not but be powerfully wrought upon,
proved too great a strain for her nervous system;
and in a short time after all were removed from her house, she became indisposed.
Medical skill proving unavailing, she gradually sank away,
beyond the control of human remedies, and departed this life on the evening of the 15th.

She was a woman of remarkable philanthropy and kindness to all,
especially the distressed and the poor; and a humble, self-denying follower of Christ,
shown by her steady, consistent walk through life; one of the pure in heart,
and of the salt of the earth;
possessed of a good understanding and discernment in religious things.
She maintained an undeviating testimony against the attempted
innovations in principle made upon the faith of Friends;
and was a comforter of others who took the same stand.
Her views of the plainness and simplicity which the Truth leads into,
did not admit of making unnecessary display,
while true comfort and abundance were provided by her.
Thus another of the true seed of Christ`'s kingdom,
has been gathered to her everlasting rest in Him,
among the children of the first resurrection;
not by works of righteousness that she had done, but according to the mercy of God,
by the washing of regeneration, and the renewing of the Holy Ghost;
which He has shed on us abundantly, through our Lord Jesus Christ.

I believed it right to bear testimony, at her grave, of the belief,
that she was gone to the multitude that surround the holy throne;
being made a partaker of the salvation purchased for us,
through the precious blood of Christ.
It is not our place to question the right of Him who rules in the armies of heaven,
and among the kingdoms of men, to call away the members of the militant church,
when He pleases; but every one removed, is the taking away of salt from among us,
and should incite us to ponder our true condition, and to ask, in the spirit of prayer,
of Him to supply our needs,
and to raise up others to fill the vacancies made by the transition
of faithful servants to the church triumphant in heaven.

Eleventh month 4th. At our meeting this morning,
(first-day,) I was constrained again to warn some,
that there were but twelve hours in the day, in which men may work,
and then the night comes wherein no man can work.
That their day was passing away,
and it was evident they were neglecting the business of salvation,
in the pursuit and love of the things of the world.
None knew when their day would expire; it may come to a close unexpectedly,
and if laid on a death bed, with the work unaccomplished,
awful must be the prospect of a never-ending eternity.
Many have been landed in that condition,
when they would have given everything for a little time, to do this all-important work.
Some were pleaded with in the love of the gospel,
to give up all that the Lord`'s controversy was with,
and submit to the terms of salvation, while the day lasted.

My dear wife knelt and supplicated, that if any had been drawn to this meeting,
and were made sensible that the shades of the evening had come upon them,
and the great work of salvation was not done,
they might yield to the convicting power of the Holy Spirit, and before it was too late,
show forth the goodness and mercy of God, in plucking them as brands from the burning;
by walking in his fear, and drawing others to glorify God, on their behalf.
It was a solemn, impressive time, and I hoped some were reached.

5th. The meeting for worship, before entering on the business of our Quarterly Meeting,
today, was a solid and instructive season.

18th. I have felt much emptied of Divine consolation and strength, for days past,
both in meeting and out of it.
Refraining from much conversation, and endeavoring to draw near to the Lord in spirit,
I have believed to be the safest place for me; and I trust,
that preservation on the watch has been experienced.
The prospect of religious service is much withdrawn;
and discouragement as to any benefit arising from it, when the fresh anointing is felt,
is often the accompaniment of my mind; but I endeavor to hold on my way,
and to seek for ability to trust in the never-failing Helper of the poor and needy.

20th. My dear wife feeling drawn to attend the Quarterly Meeting at Rahway,
we set off this morning in the cars, and got to our friends,
Joseph and Martha Shotwell`'s, about noon, where we put up.
Next day we were at their Select Meeting; in which we both had some service,
encouraging the few who felt poor in spirit,
and were mourning for the desolations of our Society.
Also holding up the testimony of our blessed Savior, that without Him we can do nothing;
and hence the need of waiting for the arising of his life and power,
to quicken and qualify for the work He would bid us to do.

22nd. The Quarterly Meeting was a very small company;
but few there from Shrewsbury and Plainfield;
all the meetings being in a dwindling condition.

Twelfth month 7th. Having been at West-town, attending the meeting of the committee,
which prevented me from being at our usual week-day meeting,
I went this morning to that in Arch Street; which was small for that large house.
We sat more than an hour in silence,
during which the circumstance of Christ calling his disciples, sheep,
and on commissioning them to go forth, telling them, "`Behold,
I send you forth as sheep in the midst of wolves; be therefore wise as serpents,
and harmless as doves,`" was brought before me.
I felt fearful of speaking, lest I might act without his authority,
and thus injure the good cause;
so that I seemed likely to come away without breaking the silence.
But finally the fear of putting by a right impression,
induced me to stand up with those words, and to show that the true disciples,
who keep in the Spirit of their Divine Master, in times of suffering and persecution,
were like sheep in the midst of wolves; and they were to be wise as,
but not in the serpent`'s wisdom, but in that which comes from Him,
who is the wisdom of God, and the power of God;
and to be clothed with the harmlessness of the dove;
showing the nature of Him who is the Lamb of God, that takes away the sin of the world.
Though not exposed to outward persecution at this day,
yet there is much suffering to be endured; and when the cup that is to be partaken of,
for the body`'s sake, which is the church, is presented,
we are to drink it with resignation to Him,
and it will contribute to our humiliation and preservation in Christ.
When suffering is withdrawn,
how liable are we to take our ease in the comforts with which we are surrounded.

The nearer we draw to the close of our journey,
the more need there is to be clad with the holy,
harmless and undefiled nature and spirit of Christ.
When the disciples returned from the accomplishment of their mission,
and told their Lord that even the devils were subject to them, through his name; He said,
"`Rejoice not that the spirits are subject unto you,
but rather rejoice because your names are written in heaven.`"
This is the all-important object of our lives, to be prepared,
by his power giving us the victory over all the power of the enemy,
to have our names recorded in the Lamb`'s book of life.
Nothing is worthy of competition with this.
No name or fame among men; all that our companions may say in our favor, are nothing.
We must individually stand before the tribunal of Jesus Christ,
and receive a reward according to our deeds;
we can have none of them to plead our cause there.
