== Chapter XXXI

[.chapter-synopsis]
* 1855--1857. Religious Engagements at and about Home

1855, Twelfth month 10th. Feeling drawn to attend Haddonfield Monthly Meeting,
I went over to it this morning.
The company was smaller than usual.
This is discouraging to those who are constrained to
endeavor to keep up their religious meetings,
and to do what their hands find to do, in support of the cause of Christ.
They go through much mental exercise on account of it,
often fearing that their meetings will dwindle away,
and the members become scattered to the world.
For this class, I felt much, while sitting with them,
and was led to show that the Lord`'s people, in many instances,
had passed through much humiliation and bitter suffering
before He saw fit to manifest Himself for their deliverance.
The children of Israel in Egypt, and the Jews in the reign of Ahasuerus,
appeared to be exposed to destruction.
Moses and Mordecai were brought very low,
before they were used as instruments in the Lord`'s hand,
in bringing about the liberation of that people from bondage,
and the murderous designs of Haman; but the Lord made way for them,
and He can do it in this day, for us, when his time comes.
We must learn to bear affliction, and to wait upon Him, and as we are enabled,
pray to Him, to give us faith and patience,
and to extend his compassion to his tribulated children,
for their support and consolation.

21st. For some days past, it seemed out of my power to come at inward,
humble waiting upon the Lord,
or to feel the spirit of prayer in tender cries unto Him for help.
Our Meeting for Sufferings, today,
called forth but little religious feeling and exercise;
the subjects which claimed its attention, being much of an outward character.
I thought the day for my taking part in the services of Society was drawing to a close.
It is like being stripped of all armor and qualification; which,
will no doubt be placed on others, who will be called into the Lord`'s work.
If I can be favored to retire to the inner temple, and partake of the cup of suffering,
for my own purification, more and more experiencing the silence of all flesh,
and keeping steadfastly upon the watch-tower, to see what the Lord shall say unto me,
if He condescend to speak, and what I shall answer when I am reproved,
preservation and greater deepening in the Divine life, I humbly hope,
may be more fully known.

23rd. Having for some time had a draft to Cropwell Meeting, I went there this morning,
first-day.
I was brought into sympathy with those who love the Lord Jesus,
and feel bound to endeavor to hold their meetings
according to our testimony to inward spiritual worship,
and when able to attend, cannot stay from them.
To these, I was led to minister, I hope, a cup of consolation and encouragement;
that they might hold on faithfully, setting a good example to the young people,
that they may be gathered to Christ,
and a band of living witnesses be raised up among them.
Invitation was also extended to the young people,
who are favored with clear convictions of the Holy Spirit,
setting their sins in order before them, to yield to the Divine will,
and let the Lord make them what He would have them to be;
and they would know Him to effect the work of sanctification, to their own peace,
and the comfort of the church.
I was also bowed in thanksgiving to the Father of mercies,
that there were preserved in that place a remnant,
upon whom rested a concern to be found in their allotment; and humble prayer was put up,
that in his mercy, He would sustain these,
and make them instrumental in gathering the
children and the young people to his beloved Son,
that they may be prepared to occupy their places in the church,
and support the cause and testimonies of Truth.

1856,
First month 8th. The great importance of being preserved from the power of the tempter,
came over me with much weight this morning, before I rose;
and I was brought to put up fervent, mental cries to the God of all our sure mercies,
that He would not suffer me to fall into temptation; that in unmerited mercy,
He would forgive and blot out my sins, and remember them no more;
and that whatever He saw meet, to humble and keep me on the watch, He would,
in his tender compassion, administer, for my preservation from evil.
I remembered some who had been highly favored,
and had afterwards slidden from the foundation.
I thought of our beloved friend Thomas Kite,
how he had been taken away before he reached my age, in peace and brightness;
and it was to me more desirable to be removed from this scene,
before anything should dim the character, which through grace,
we may have been favored to attain, than to be continued here to old age,
and lose the life and virtue of religion, which had been our experience to possess.
He who, of his own good pleasure, begins the work of regeneration,
and carries it on to its perfection, can alone keep us from falling,
and in the end present us faultless before the throne of his glory, with exceeding joy.
May it be my experience, though unworthy of the least of all his favors.

20th. We have had very severe weather, at different times,
since the beginning of the year;
the mercury having been several degrees below zero in the city,
and still colder in parts of the neighboring country.
Much snow has fallen, making traveling in many places very difficult,
particularly on some railroads: also encumbering our streets,
which have been covered with an unusual thickness of ice.
Many ways are adopted to meet the necessities of the poor,
though there is not so much street begging as last winter.
It is evident, the more that is done for those beggars, the more importunate they become;
availing themselves of every source of supply they can; by which,
unworthy persons often deprive more deserving objects of what they should receive;
but it would be wrong to allow any to suffer from lack,
however unjustifiable their course may be.

On first-day morning, the 17th, I was again engaged to preach the everlasting gospel,
both concerning the coming of the Son of God in the flesh;
his propitiatory death for the sins of the whole world;
his glorious advocacy at the right hand of the Father,
and as being the Source of all saving knowledge of God,
by the immediate revelation of his Holy Spirit in the heart.
It is the grace that comes by Jesus Christ alone,
that can impart the saving knowledge that is life eternal.
The heart must receive Christ in his spiritual appearance, submit to his will,
forsake all and follow Him, in order to receive this knowledge of God,
and hold communion with Him, through our Lord Jesus Christ.
Many are willing to believe the doctrines of the New Testament,
but refuse to deny themselves, forsake sin,
and follow the Lamb of God whithersoever He leads;
and thus they fail to become partakers of the
fulness of the blessing of the gospel of Christ.
Oh, the lack of the pure and undefiled life of Christ Jesus,
ruling in I he professors of his name!

Third month 12th. The weather this week has been very cold for the time of year;
the mercury in thermometers in the city, being but six to nine degrees above zero,
for one or two days, and in the country, at a degree or two below zero.
There has been much difficulty in opening the navigation of the Delaware.
Vessels which have been at the breakwater many weeks,
have now been towed up by ice-boats; and though it is still quite cold,
it is hoped the channel may be kept open,
and that laboring men may have opportunity to obtain employment,
to keep them from suffering;
of which it is to be feared there have been not a few instances this winter.
It has been throughout a severe winter; long and tedious.

13th. I went to Haddonfield this morning, and attended the Quarterly Meeting held there,
which was large, several Friends from two or three other Quarters being there.
In the second meeting, it appeared to be my place, to call Friends to the quickening,
heart-changing power of the Holy Spirit;
which prepared the early Friends to understand and to open to the people,
the doctrines and the nature of the gospel dispensation.
It is the same Divine life that can open them to us,
and which will bind us conscientiously to maintain them before the world,
and to all people; not in word only, but by consistent lives and conversation.
Returned home in the evening, thankful we were permitted to land safely,
there being much heavy ice in the river.

15th. This evening, near nine o`'clock, the steamboat in which we had crossed the river,
in going to and from Haddonfield, took fire.
Being old, and the timber very dry, the flames spread rapidly,
and the captain not being able to get her through the
canal in the island opposite the city,
on account of the ice, an attempt was made to run her back to the wharf;
but the steersman`'s house was soon enveloped in the flame,
so that he was driven from the wheel; and thus being left to the current,
which turned her from her course, and swept her off again into the stream,
before any could spring to the wharf, which was by some attempted, she drifted away,
and was finally grounded on the bar.
There was said to have been one hundred persons on board,
sixty-two of whom it is supposed were lost, either by being burned to death,
or by being drowned, after jumping into the river.
Boats of different descriptions were put off for their relief, but being night,
and probably but few at hand, the destruction of life was fearful.
Such an awful event has never before occurred on our river, that we have any account of.
Death, overtaking so many, who could have had no apprehension of it,
a few minutes before leaving the wharf, and under such dreadful circumstances,
had much effect upon the public mind,
as well as bringing deep distress on surviving connections and friends.

18th. I went to the North Meeting, under some trial of faith.
It was a large collection, many school children being there.
The circumstance of parents being rebuked by some,
for bringing their children to the Savior,
that He might lay his hand on them and bless them, was presented to my mind;
and after waiting, and trying the fleece wet and dry, the subject was opened;
and the danger alluded to,
of persons placing stumbling-blocks in the way of the children,
whose minds are brought under Divine conviction;
and thereby turning them aside from their Savior.
The mercy and goodness of our Heavenly Father,
in watching over and warning young people of the temptations of Satan,
and the enticements of wicked persons; of which I could testify from experience,
when an apprentice boy, and the Lord`'s defense,
vouchsafed by the horror suddenly brought over me, were referred to;
and all pleaded with to mind the visitations and
requirings of the Most High extended to them.
Ability was graciously granted to preach the gospel,
under the quickening power of the Holy Spirit,
which reached and tendered the hearts of some,
and I came home thankful for the unmerited favor.

23rd. It is not the hearers, but the doers, of the law, that are justified.
As the body without the spirit is dead, so faith without works is dead also.
It is those who do the sayings of Christ, that build upon the rock;
and when the floods beat upon their house, it will not fall,
because it is founded upon a rock.

30th. On fifth-day, the 27th, I was at the Philadelphia Monthly Meeting.
I felt required to mention the fasting, almost to famishing,
which the Lord`'s children had at times to endure;
but that it was a great mercy to have preserved a hunger and thirst after righteousness,
for in his time we shall be filled.
The subject opened so as to show that whatever were our growths, experiences or gifts,
we can do nothing, and are nothing, without Christ.
The goodness of the Lord, in filling my heart with these Divine things, was humbling,
and renewedly manifested his watching care over,
and preserving goodness towards his poor, dependent children.

After so severe a winter, it has been cause of gratitude,
that the great quantity of snow and ice has so gradually dissolved and passed away,
as to produce but little damage.
How merciful is our Father in heaven towards poor, sinful,
rebellious man! and how ought we to lay to heart,
the withholding of his judgments and anger,
for the wickedness that prevails in the land to humble
ourselves and implore his forgiveness of our sins,
and for strength to forsake them, and to walk uprightly before Him;
bringing forth the fruits of holiness, to the praise of his great and glorious Name.

Fourth month 28th. Our Yearly Meeting was held last week;
in which I was again continued clerk,
and I thought I had never passed through so much suffering, from day to day,
as I did through the whole of its sessions.

Accompanying the London epistle,
was a printed statement of the reasons governing that meeting,
in its acknowledgment of the separate meeting in Ohio; which some wished to have read.
After it was deliberately read, Samuel Bettle, Sr.,
expressed his dissent from their conclusion to own that party in Ohio,
and bore a very decided testimony against separations in our religious Society;
as they were no remedy of evils or difficulties.
Our place was to bear, and patiently suffer until the Lord brought relief.
He referred to George Fox`'s epistle, written from Amsterdam,
against a spirit that was seeking to promote divisions and separations in the Society,
at that day.
I think that the manner in which separations, and their consequences, were treated,
had a useful effect upon many minds.

Seventh month 9th. This morning we were favored with
the cheering and strengthening presence of the Lord,
at our fourth-day meeting at Orange street.
I was impressed with the belief that the Lord is at work in the hearts of many,
to prepare them for service in his church, as they dedicate themselves unto Him.
What is lacking, is for every one to look into his own heart;
not to be looking out to see what others are to do.
When Moses was told that Eldad and Meclad prophesied in the camp, Joshua said,
"`My lord Moses forbid them.`"
But Moses said unto him, "`Do you envy for my sake?
Would God that all the Lord`'s people were prophets,
and that the Lord would put his Spirit upon them!`"
Though it is not to be expected that every one
will be made a vocal minister of the Gospel,
yet every submissive soul would be favored with a measure of the spirit of discernment,
and under the Divine influence, would be qualified, at times,
to speak of what the Lord had done for it,
to the instruction and comfort of other seeking ones;
and I believe more ministers would be raised up to preach the everlasting Gospel,
as the visible church was more generally gathered into
obedience to the blessed and adorable Head.

25th. Poverty of spirit,
and the feelings of mourning over the present state of the Society, have been my portion.
The weight of discouragement at times, seems heavy to bear,
so that there is a secret longing for a release.
Oh! for a renewed evidence that Divine regard is not withdrawn,
but that His mercy is lengthened out still.
Nothing seems to sustain the poor, tribulated soul, like a secret,
quickening sense that the Lord is near, watching over and defending us.
The devil is walking about, as a roaring lion, seeking to devour us,
and to prevail on us to cast away our faith and hope,
and no longer to look to the Lord for help; and in these days of darkness and fear, true,
experienced Friends, seem to be few.
But like Job, may we, in the Lord`'s way and time, witness a change,
and our last state be better than it was in the beginning.

29th. For several weeks we have had very warm weather,
the mercury almost daily being from ninety to one hundred degrees in the shade,
and but little rain has fallen within the last three weeks;
so that the ground has become much parched, and vegetation dried; creating fears,
in some places, of the loss of the crops,
and the necessary supply of grass for the cattle.
Such heat, and the rain withheld, show us how dependent we are upon Divine Providence,
and the need of remembering this constant dependence,
and of receiving with more thankfulness, than it is to be feared many do,
the temporal as well as spiritual favors that are bestowed upon us.
How easily could He cut off our supplies of food, and command a famine in the land;
so that life would be in danger.
We have been fed to the full, and it may be, have forgotten,
that all we enjoy is the bounty of heaven;
and have continued to live too much as if there was no danger,
but that we had our blessings at command.
But the Lord`'s mercy is lengthened out to a wicked and gainsaying people.
Today some rain has fallen, and the weather being clouded, we have hope for more.
The little lightning and thunder we have had this season is quite remarkable;
no heavy thunder-gusts have occurred in this part of the country.

Eighth month 3rd. Quite a heavy shower with lightning, this afternoon;
very refreshing to vegetation.

4th. Our Quarterly Meeting was rather a heavy time;
though not without some encouragement, through instrumental labor of others.

20th. This week I went to the Northern District, and the Arch Street Meetings,
feeling the pointing of the Divine finger, under a sense of much weakness and poverty.
When I sat down in the meetings, I was tried with many things rushing into my mind,
producing discouragement, and a sense of great unworthiness,
and incapacity for the Lord`'s work.
What I had to say, which I believe was from the Lord`'s putting forth,
was all brought into my mind, after getting out other things,
by the secret working of the Holy Spirit.
I believe some were brought under serious feelings, and I hope some were comforted,
and others animated to look into their own conditions,
whether their work is going on with the day.
I came away from both meetings, peaceful.

On the 22nd my wife and myself went On a visit to our friends J. B. and wife,
at Columbus, New Jersey.
It proved a pleasant interview, and interchange of sentiment and feeling.
They are honestly concerned for the right maintenance of the cause of Truth,
as our first Friends were bound to support and promulgate it to the world.

On the 24th, rode from there to Rancocas, and attended the weekday meeting; in which,
through condescending goodness and love, we were engaged in the ministry;
and several Friends expressed their gladness at our stopping in with them.
Many of the meetings within our Yearly Meeting, have no minister;
and though the life and growth of true religion are not dependent on ministers;
yet were the members living daily under the subjecting power of Christ,
we may believe that more gifts would be given, both for the ministry and the eldership.
To the primitive church they were dispensed for the building of it up;
for the instruction and feeding of the children, the lambs of the flock;
and they would be continued to be given for the praise and glory of the Great Head,
and for the promotion of his cause, were the members prepared to receive them.
But the things of this fading world, the love of ease and creaturely enjoyments,
absorb the thoughts and affections of many,
whose hearts are not open to let the King of glory come in, and set up his kingdom there.
Thus the all-important work of sanctification is obstructed;
and such remain unfit to receive gifts, and therefore cannot occupy them;
and the glory which would rest upon us as a religious body, were we faithful to the Lord,
does not appear among us as it has in days past.

Tenth month 2nd. This morning I was drawn into a consideration
of the continued mercy and goodness of the Lord,
extended to me from childhood up to this day.
I have been delivered from many temptations and evils,
and provided with everything necessary for my comfort and subsistence through life;
and experienced the Lord to be with me in many trials, and strippings, and baptisms,
in the work of regeneration.
My faith was renewed in his condescending goodness and preserving power;
and that those who hold out to the end shall die in the arms of their Savior.

5th. This day I am sixty-nine years old, and have been remarkably blessed with health,
and with many outward and spiritual comforts;
for which I have great cause to devote myself, and all that I have,
to the Lord`'s disposal and service;
and to return gratitude and thanksgiving to Him for all his mercies,
which are new every morning.
May my dear children, be induced by Divine grace,
to surrender themselves entirely to his blessed will,
and thereby be prepared to take their places in the church of Christ,
in the support and promotion of the great cause of truth and righteousness.
And may He, who began the work of regeneration at an early period of my life,
unworthy as I am of the least of all his favors, continue to be round about,
and preserve me to the end;
that I may never be permitted to do anything to bring the least stain upon the truth,
or its holy cause; but by, and through the Lord`'s power,
be kept in the low valley of humility,
looking to and relying upon Him daily for his guidance,
and the sustaining virtue of his Divine life.

Eleventh month 16th. This morning, (first-day,) the Lord condescended, I believe,
to draw near again; bringing me under exercise for individuals in our meeting,
who are at times brought to feel their undone condition,
and to long for deliverance from spiritual bondage; and in the openings of his Spirit,
I was led to minister to such,
and to point out that there is no way by which we can
be released from the bondage of sin and corruption,
but by coming to Christ Jesus in his appearance in the heart; taking his yoke upon us,
denying ourselves and following Him in the way of regeneration.
I trust the solemnizing power of Christ went over the meeting;
and my dear wife was prostrated in supplication for the children, and the rebellious.
We had cause humbly to thank the Lord for the renewed
manifestation of his Divine regard and condescension,
to us poor unworthy creatures, and to breathe in spirit,
that He would continue his humbling and preserving power,
to keep us in his fear and favor.

27th. Felt drawn to attend the Arch Street Meeting.
Pretty soon after being seated, the expressions of our Lord presented:
"`Except a corn of wheat fall into the ground and die, it abides alone; but if it die,
it brings forth much fruit.`"
The apostle declared that he died daily, and asked the believers,
"`Know you not that so many of us as were baptized into Jesus Christ,
were baptized into his death; therefore we are buried with Him by baptism into death;
that like as Christ was raised from the dead by the glory of the Father,
even so we also should walk in newness of life.`"
The dealings of the Head of the church, with the members of his body,
are a mystery to the natural, unregenerate man, which he cannot understand,
nor believe in.
They are known only through living experience; and those who submit to his humbling,
reducing baptisms into death, as they abide under them in patience,
when they have accomplished his purpose, He will raise them up out of this death,
by his power, into newness of life.
Thus He prepares the creature for his service,
and carries forward the work of sanctification.
These, know Him to be the author and the finisher of their faith,
and can believe and savingly understand the testimony of the Holy Scriptures,
concerning the mysterious operations of the Holy Spirit,
and bear a true declaration concerning them.

Twelfth month 13th. Since my return from attending the School Committee at West-town,
I have been quite unwell, and the apprehension that my day was drawing to a close,
has been much upon my mind.
There are so many trials and distressing feelings
arising from the state of our poor Society,
that sometimes I seem ready to desire to be permitted to depart and be with Christ,
if the right time was come, and through his unmerited mercy,
He would prepare me for the awful change.
Excepting the preciousness of my dear wife and children, and other near connections,
there seems nothing to attach me to the world.
I have been provided with everything necessary for comfort in this life,
but they are only for this life; and when the end comes,
they are of no value to the immortal soul.
To be washed, and sanctified, and justified, in the name of the Lord Jesus,
and by the Spirit of our God, is the one great thing needful.
May this be my blessed experience before the close comes,
so that an entrance may be administered into the
everlasting kingdom of our Lord Jesus Christ,
among the generations of the blessed.

28th. I have been wrapped up in silence for weeks.
Today, there seemed a little opening to point out the necessity of
doing the work which every one is called to perform;
by which our own salvation, and that of others, will be promoted.

1857, Second month 2nd. We had an uncommonly large Quarterly Meeting,
which was held in great stillness to the close.
In that for discipline, our aged friend S. Bettle, Sr.,
advocated some of the testimonies borne by Friends,
and counseled the young people against attending certain lectures, now become numerous,
and which, in his opinion,
were likely to draw the mind from the retirement and religious exercise,
necessary for a growth in the Divine life.
I added the expression of my unity with what be said;
and that I believed every one who had submitted to the power of Divine grace,
if they looked back at their first espousals to Christ,
would see they were then brought under conscientious scruples,
to do nothing that would bring a blemish on their religious profession;
and as they kept to this,
they were preserved out of many temptations they had not foreseen.

9th. Went to Concord, and attended the Quarterly Meeting for Ministers and Elders;
and was exercised on the importance of the duties of elders,
and of their faithful discharge of them.
They were reminded of the advice to watch over one another for good;
to warn those who run into words without life and power,
that we may be helpful to one another; and be united in true love and fellowship.

10th. The Meeting for Discipline was unusually small,
occasioned by the difficulty of getting through some of the roads,
now much obstructed by snow and ice, which probably discouraged many from coming.
I had something to communicate in the second meeting, on the exercise of the discipline,
and the requisite qualification for service in the church,
which is only received from the great Head.
This is to be waited for in reverent silence before Him,
who opens to us our respective duties, and gives ability to perform them.

Third month 8th. Many of the sins of my youth
have been brought into remembrance this day,
producing the question, whether they have been forgiven; under which,
a degree of humiliation was felt, and desires raised before the Lord,
that his mercy may be extended, so that they may be blotted out and cast behind his back.
I remembered that Job was made to possess the sins of his youth,
after the testimony had been pronounced, that he was a perfect, and an upright man;
doubtless to show him his nothingness, and that he had no ground to rest upon,
but the mercies and forgiveness of God.
When he was thoroughly humbled, in the end of this severe dispensation, he said,
"`I have heard of you by the hearing of the ear, but now my eye sees you;
wherefore I abhor myself,
and repent in dust and ashes;`" and
"`The Lord turned his captivity, and gave him twice as much as he had before.`"
May I know again and again the washing of
regeneration and the renewing of the Holy Ghost,
and thereby be enabled to confess my sins unto God,
and receive his forgiveness and pardon, through the blood of his adorable Son,
our Redeemer and Savior, Jesus Christ.

10th. Feeling a draft in my mind, I sat with the Friends of the North Meeting,
being their mid-week meeting.
Sympathy with the burden-bearers, clothed my mind; also for the dear visited children,
who have few fathers and mothers to look up to.
The language of encouragement arose in my heart, "`Thus says the Lord, that created you,
Jacob, Fear not, for I have redeemed you, I have called you by your name; you are mine.
When you pass through the waters, I will be with you, and through the rivers,
they shall not overflow you; when you walk through the fire, you shall not be burned,
neither shall the flame kindle upon you.`"

Fifth month 19th. Was held our Meeting for Sufferings; in which our friend W. G.,
from Ireland, had a little service.
It felt to me that the time was come, for me to be released from the clerkship;
and proposing that a committee be appointed to
bring forward a Friend to serve in my place,
it was done.

21st. This has been a day of poverty, and seemingly striving for bread in vain;
but in the evening, at the close of our reading in the New Testament,
the impression came sweetly over my mind,
it is a blessing to have the Son of Peace to take up his abode in our habitation;
which I felt fresh desires may be more and more known by every one of us,
in our individual experience.
Without it there is no true happiness.

22nd. There seemed to be a renewed qualification to encourage Friends
to hold fast their confidence in the omnipotent Captain of Salvation.
He delivered his people out of the hands of their enemies, in days of old.
He raised up our Society to promulgate anew, the truths of the everlasting gospel,
and He can now deliver us from our trials and difficulties,
and raise up others to declare the same blessed doctrines and testimonies;
as we give up to his holy will, made known in our hearts.

Eighth month 13th. Feeling an intimation to attend the Quarterly Meeting of Salem,
I went to Woodbury this morning, and sat down in the meeting, under a sense of its,
and my own stripped condition;
and the few there are left to visit Friends in different places.
We sat an hour in silence, when it seemed to be my business,
to set forth the inward work of religion upon the heart;
and that where it is submitted to, it leads into retirement before the Lord;
in which the spirit of prayer is at times given, to ask forgiveness for past sins,
and for strength to resist the enemy and his temptations.
The people of the world are looking out for the faults of others, and feeding upon them;
but the Lord`'s visited and faithful children are
concerned to have their own hearts searched,
that everything contrary to his will may be done away,
and they made to bring forth the fruits of his Spirit, to the praise of his great Name.
Their language is, "`Search me, O God, and know my heart; try me and know my thoughts,
and see if there be any wicked way in me, and lead me in the way everlasting.`"
The tribulated seed were encouraged to trust in the Lord, and to look to Him daily,
for the arising of his power to help them in their trials, and to gather the children.
The latter were persuaded to obey the offers of Divine grace and mercy,
which are of more value than anything in this world.
These are the days of the Son of Man to their souls, which we have no power to command,
and if rejected, know not that they will ever be renewed.
I thought the tendering power of Christ was felt by many among them,
for which we have cause to be thankful to the great Lord of the harvest.

Ninth month 14th. Feeling a pointing of the Divine
finger to Haddonfield Monthly and Quarterly Meetings,
I went over the river this morning, and attended their Monthly Meeting.
In the first sitting I was drawn to address them on the
importance of each one laboring in his own vineyard,
while the call was extended.
If any, by the renewed visitations of Divine grace,
were brought to see that their time had been spent without this labor,
and that the eleventh hour of the day was at hand,
it was all important they should obey the call,
to enter into their vineyard and there work,
that they may obtain the reward at the end of the day.
On fourth-day morning, went to Medford,
where the Quarterly Meeting is to be held at this time.

16th. The Meeting of Ministers and Elders was small.
After the Queries and Answers had been read,
I had some remarks to make on the essential need of keeping in the life of Truth.
That a profession however sound, would avail little,
if we were not dwelling in Christ and producing the fruits of his Spirit.

The Quarterly Meeting was larger than any other of those in the country.
We sat long in silence.
When it seemed near time to close the partition, I had an impression to rise,
and though it was rather laborious service, I adverted to the importance of Friends,
in their social circles, putting a guard over themselves, to avoid lightness,
and to abstain from too much conversation.
After this, the way opened to address different states,
and to hold up the importance of not suffering the world,
in its lawful or unlawful concerns,
to hinder us from performing our duties to our Heavenly Father;
that the work of salvation may be carried, on,
and we be filling up the places assigned us in the church of Christ.
I felt peaceful and easy.

29th. For a week past there has been much distress,
owing to the failure of some moneyed institutions, and of men in large business,
and the refusal of our banks to redeem their notes in specie.
For several years some merchants have been borrowing large sums of money,
to enable them to engage in extensive speculations in various ways; in stocks, in flour,
sugars, and in a great expansion of manufacturing establishments.
The price of articles of food, and other necessaries in living,
have been greatly enhanced.
Now, many of the highest standing as merchants, having failed to meet their engagements,
and the banks suspending specie payments, confidence in them has been shaken;
creating embarrassment from the lack of a reliable medium of circulation.
Thus by raising the price of the necessaries of life,
an unwarrantable tax was laid on the people, when there had been no scarcity;
and when the men engaged in these speculations could no longer obtain loans of money,
to maintain their control over those articles, a general breaking up has followed;
manufactures have stopped, mechanics and others have been thrown out of employment,
and money transactions involved in confusion.
It is remarkable that many of those considered the most wealthy,
and the most sagacious and competent as merchants,
have been the first to become embarrassed; by whom, many of the smaller traders,
have been involved in great difficulties, and losses.
We have been going on with high heads,
as if nothing could arrest our progress in excessive trade;
but the Lord has his way in the clouds, and thick darkness,
and He uses the means to bring down the lofty from their great exaltation,
and to chastise the people for their worldly-mindedness, their rebellion,
and their slighting of Him and their duty which they daily owe to Him.

I went this morning to the Northern District Meeting;
and was led to entreat the young people to give
up to the Lord in the day of their visitation,
and they would gradually know a growth in the Truth.
Joseph who was hated of his brethren, was through faithfulness to his God,
prepared to be as a Savior to his father`'s house, and governor over Egypt;
having suffered persecution and imprisonment for standing firm to the Divine will.
He could not foresee that which was afar off, respecting himself,
but by obedience he was kept in purity, and grew in wisdom; so that his father,
on his deathbed, compared him to "`A fruitful bough by a well,
whose branches run over the wall: the archers have sorely grieved him, and shot at him,
and hated him; but his bow abode in strength, and the arms of his hands were made strong,
by the hands of the mighty God of Jacob.`"

While a lad, he was cruelly treated by his brethren,
some of whom would have destroyed him.
But he was preserved in the fear of the Lord, and the Lord watched over him;
and in process of time, made use of him,
when way was to be made to keep the people alive in famine.
He became the instrument in the Divine hand,
of keeping his father`'s family in the great dearth which spread over the country.
Many young people in minding the guidance of their Savior,
have steadily advanced in religious growth, until, as they grew in years,
they have become pillars in the Lord`'s house,
and instruments in his hand to rebuke transgressors, and to draw souls to Christ.

Tenth month.
The pecuniary distress continues to increase, and one failure makes way for another,
so that people are left in uncertainty who shall next come to a stop.
Business has experienced a great check,
even with those whose affairs are in a safe condition;
it being difficult to know whom it would be safe to trust.
Such a week has not been known by the present generation, and well will it be,
if reckless and unprincipled men,
who have too little regarded the law of righteousness and justice,
are brought to a full sense of their wrong doings,
the emptiness of all worldly aggrandizement,
and the paramount importance of working out their
salvation with fear and trembling before God.

5th. This day, I am seventy years old,
and through mercy have been favored with almost continued health;
for which and many other blessings,
I have cause for deep gratitude and thankfulness to the Father of mercies.
May I be still enabled, by the help of his Holy Spirit, to walk humbly before Him;
be kept from bringing any shade upon the blessed truth, but in reverent,
daily prostration, bring forth fruits of righteousness,
to the glory and honor of his great Name.

15th. It was unlooked for to feel my mind turned to the Arch Street Meeting,
this morning; but though things in the outward were dark and gloomy,
I thought the truth and its cause, and the salvation of souls,
remained to be of as great importance as ever;
and the Lord could manifest Himself for our good,
notwithstanding surrounding discouragements.
The nature and efficacy of true faith were brought before me,
and after a time of inward waiting,
the impression was felt to rise with the testimony of the apostle,
that "`By grace are you saved, through faith, and that not of ourselves;
it is the gift of God`';`" also the declaration of the wonderful power of faith,
exemplified in the experiences of the holy ancients, who through it,
wrought righteousness, stopped the mouths of lions, etc.
This faith in God remains to be the same,
and it is dispensed to his children by the Captain of their salvation,
and becomes their victory, as they follow Him in the regeneration.
Mere belief in the truths of the Holy Scriptures, though of inestimable value,
is not sufficient, without coming to Christ and receiving life and power from Him.
Some were invited to examine themselves,
whether anything had drawn them away from the devotion and faithfulness to Christ,
which they had known in years past;
whether their worldly pursuits had suppressed
the love and allegiance they once bore to Him.
The obedient ones were encouraged to keep fast hold of the shield of faith,
and to put their trust in the Lord,
who is as near to his children to preserve and defend them, as He ever was,
though they may not perceive it; but in his time,
He will manifest Himself to their joy and consolation.
I trust the power of Truth was felt to be in good measure over the meeting,
and I came away in peace.

Eleventh month 22nd. Fervent desires have been almost unremitting,
that the Lord would not let me be overcome by
any temptation which the evil one may present.
I feel the necessity of watching over my thoughts and words, as well as actions,
wherever I go; in the street, in the market-house, at the store, at home and in company,
lest anything should slip from me that would injure another, or wound my own soul.

28th. For several days I have had my mind turned
towards Mansfield Meeting and Burlington Quarter,
but labored under concern lest I should be mistaken.
As the time drew near, I felt most easy to set off.
On first-day, I attended Mansfield meeting, which was pretty large for the country.
I was led to address the company,
under feelings of affectionate solicitude for their present and everlasting welfare;
and to bend the knee in supplication to the Father of mercies,
for the extendings of Divine help, to the livingly exercised among them.
I hoped the feeling of the humbling power of Christ was spread over us.

30th. Attended the Select Meeting at Burlington.

Twelfth month 1st. Went to the Quarterly Meeting, under a sense of weakness,
and with desire to be preserved in my place,
not attempting to do anything without the Lord`'s bidding.
I was led to declare,
that whatever might be the difficulties we may have to contend with,
if faithful to our Lord and Master, He will cast up a plain path before us,
and strengthen us to renounce all that He calls us to part with,
though as dear as a right hand or a right eye, and give us his peace;
and through perseverance, under the guidance of his Spirit,
an establishment in Christ will be come to.
He will give us power over all the power of the enemy, as He declared to his disciples;
and as we were bought with a price, even the precious blood of Christ,
a lamb without blemish and without spot,
we are to glorify God in our bodies and in our spirits, which are his.
Throughout this little visit,
I was favored with inward quiet and watchfulness before the Lord; and in the retrospect,
was clothed with peace.

8th. My wife and I went to West-town, and met Friends on the committee.

9th. In the course of its deliberation,
the disposition manifested by some of the scholars,
to bring and wear clothing at the school, which is not suitable, as regards plainness,
engaged our consideration.
It was manifest, that an unabated concern pervaded the committee,
to maintain the testimonies of the Society, in conducting this seminary,
according to their original standard.
The unity and solemnity that spread over us, were comforting and strengthening.
It has generally been the case that Friends have been bound together in sweet fellowship,
in conducting the affairs of this institution,
and in their interest for the best welfare of the children.

13th. This morning we had quite a large meeting, which, through Divine goodness,
was a favored, solemn time.
The faithful occupancy of the gift bestowed upon each one, in whose heart,
the preparing work of sanctification has been carried on, was held forth,
as indispensable to a growth in the Divine life.

"`Feed the flock of God which is among you, taking the oversight thereof,
not by constraint, but willingly; not for filthy lucre, but of a ready mind.
Neither as being lords over God`'s heritage, but being examples to the flock.
And when the chief Shepherd shall appear,
you also shall receive a crown of glory that fades not away.`"
