== Chapter XXXII

[.chapter-synopsis]
* 1857--1859. Religious Engagements at and about Home.

1857, Twelfth month 20th. Very unexpectedly, this morning,
I felt a pointing to go and sit with the few Friends composing Newton Meeting.
There was but little time to get ready, but I had the impression,
that if it was the Lord`'s will for me to go, I should be there in time.
The steamboat was just putting off as I came near the wharf, but they held on for me,
and I reached the meeting-house in good time.
It was mournful to see the reduced state of the meeting,
and I was brought into sympathy with some,
upon whom the weight of holding it mainly rested.
The conviction came over me, that some were, at times,
clearly convinced of the emptiness and insufficiency of worldly possessions,
to give substantial peace;
and also of the calls of the Lord to come away from such enjoyments,
and give themselves up to serve the Lord, who alone can grant peace,
and make them fit to do his will; and as lights in the world,
to glorify Him in their day.
They were spoken to in the persuasive spirit of the gospel, to deny themselves,
take up the cross and follow their dear Redeemer.
The burden-bearers were encouraged to hold on their way
faithfully in the discharge of their religious duties.
Supplication was made to the Lord to renew his
visitations to the rebellious and negligent,
and to comfort and strengthen those who are often cast down and afflicted.

1858, First month 30th. Was held the Select Quarterly Meeting;
in which some remarks were made on the need of a
faithful observance of plainness of dress and manners,
in the bringing up of our children.
Harmony was felt to prevail.
Still there was a feeling of suffering,
on account of the working of a wrong spirit in the Society at large.

Second month 1st. We had a large Quarterly Meeting; many of our young members,
and some Friends from the country being at it.
Great stillness spread over us.
Several ministers from the country attended;
and in the second meeting communicated their exercises on different subjects.
I felt drawn to call the attention of the young people
to the daily reading of the Holy Scriptures,
in a serious manner, with their hearts lifted up to their Heavenly Father,
to open and apply them to their conditions, by his Spirit in their hearts.
The more we are obedient to this Spirit, by which the Lord`'s will is made known,
and by which strength is given to perform it,
the more we shall love to read the Scriptures; which were given by inspiration of God,
and are able to make wise unto salvation, through faith which is in Christ Jesus.
The Holy Spirit will bind us to make use of the means which the Lord
has provided for our help in the way and work of salvation;
requiring the attendance of our meetings for worship and discipline,
and the support of all our testimonies.
The attendance of so many,
I thought was evidence that they continued to feel a
deep interest in the welfare of the Society,
and the maintenance of its principles.

Third month 19th. Was held our Meeting for Sufferings; to which was offered,
An Appeal to the citizens of the United States, on behalf of the colored people;
embracing the slave trade and slavery,
by the committee which had been under appointment several months,
but had been detained from accomplishing the object,
by not receiving the African Reports expected from England.
We were informed that they had arrived;
having been furnished by the officers having them in charge, without expense.
The address was acceptable to the meeting, united with,
and directed to be laid before the Yearly Meeting.
I thought the testimony against slavery, being founded on the commands of our Savior,
as laid down in the Holy Scriptures,
would have a good effect upon many Christians of other denominations.

In the midst of so much attempted defense of slavery,
by those who hold the colored people as property, it was felt to be our duty,
afresh to let the public know,
that we continue to reject and oppose human bondage on Scripture ground,
and a conscientious belief that slavery is a violation of the rights of the African race;
equally with the rest of mankind, the objects of Divine mercy and regard,
and entitled to freedom, and the exercise of their mental and physical powers.

28th. In meeting, this morning, I felt an affectionate draft towards the young people;
that they might not give way to the temptation
to abandon the path of obedience to their Lord,
in the time of close trial.
David`'s testimony was brought to my remembrance:
"`The Lord is my Shepherd, I shall not want.
He makes me to lie down in green pastures; He leads me beside the still waters;
He restores my soul.
He leads me in the paths of righteousness for his name`'s sake.`"
"`Surely mercy and goodness shall follow me all the days of my life;
and I shall dwell in the house of the Lord forever;`"
which I was led to revive for their comfort and strength.
This has been the experience of the Lord`'s children in all ages;
and as they persevered in following their Shepherd, and the Bishop of their souls,
faithfully and in humility, they grew from stature to stature in the Truth;
were blessed from youth to old age, and made useful in his church and household;
and when the end came, they died in peace and hope of everlasting blessedness.

Fourth month 1st.
This morning I went to the Arch Street Meeting, feeling, as I believed,
the pointing of the Divine finger towards it,
yet had some searching of heart to guard against being mistaken.
After a time of silent waiting,
I felt drawn to bear testimony to the peculiar characteristic of the gospel dispensation;
that every member of the body and church of Christ,
has access to the living Spring of consolation and strength, in himself;
and may realize the declaration of Christ,
"`The water that I shall give him shall be in him a well of water,
springing up into everlasting life;`" and thereby is favored
at times with rejoicing in himself and not in another.
The servants of Christ have their trials and seasons of spiritual poverty,
necessary for their humiliation,
and to show them that they can do nothing without their Lord and Master;
but He will never be unmindful of them; and in his time will again come,
with healing in his wings; and they know Him by the quickening virtue of his power,
when He does appear in them.
The eminent servant and prophet of the living God declared,
that "`Although the fig tree shall not blossom, neither shall fruit be in the vines;
the labor of the olive shall fail, and the fields shall yield no meat;
the flock shall be cut off from the fold, and there shall be no herd in the stalls;
yet I will rejoice in the Lord; I will joy in the God of my salvation.`"
This rejoicing was by the immediate, tendering operation of the Holy Spirit in himself;
and this rejoicing will continue to be the experience of the Lord`'s children,
as they abide in Christ, holding fast their confidence firm, by his holy help.

8th. Was at West-town, and found the school pretty satisfactory,
as relates to the advance of the pupils in their studies.
Changes are taking place in the home education of children; the parents, in many cases,
neither look nor act like true Friends,
and their example must draw their children into much liberty,
and turn them away from the humble, plain way of living and dressing,
which they ought to observe.
This defective home education prepares many children to
disregard the regulations of this school,
and the care and authority of the teachers,
and must contribute to disqualify them for the steady pursuit of their studies.
Thus the trouble of the caretakers is greatly increased,
and the benefits are not fully derived from the institution,
which the provisions there made for a liberal and guarded education, would confer.
The unsettled state of our Society,
produced by attempted changes in our religious doctrines and testimonies,
and by the love and pursuit of the world,
doubtless acts unfavorably upon many parents and their offspring;
and which we cannot expect to see corrected,
but by submission to the convicting power of the Lord`'s spirit, operating on the heart;
and the steady faithfulness of the conscientious and religiously-exercised members.
Instead of looking abroad for defects in others,
it is important we should keep inward to the Lord; setting a proper example;
and as we may be enabled, put up our prayers to Him for our own preservation;
and that He would turn the hearts of the people to Himself,
and bring our religious Society out of its present wilderness state.

14th. Our Yearly Meeting is near at hand.
There seem to be comparatively few true standard-bearers and sympathizers.
Some speak of the discipline as being of little importance,
when it conflicts with their disorganizing views,
and thus are ready to set up their imaginations for revelation,
and above the united judgment and wisdom dispensed to the church in its brighter days.
It is not in man to control the winds and waves; the Lord alone can rebuke them.
May all our afflictions drive us nearer to Him,
lead us to put up our prayers for his sustaining help,
and to place our trust in his mercy and goodness.
We can do nothing for ourselves or for others, without Him; and may He renew our faith,
and never withdraw his Holy Spirit from us;
in unmerited lovingkindness keep us together as a body,
travailing in spirit for his cause, and the real welfare of each other.

19th. The Yearly Meeting convened, and was a large body.
It opened with solemnity.
Samuel Bettle, Sr., called our attention to the belief of Friends,
that it was the Lord`'s work for which we were assembled; and exhorted,
to let it be done in his fear, with decency, forbearance, and love of each other.
Though some objections were made, an epistle from Dublin, and a minute from London,
informing they had not written an epistle to us, were read.
In the afternoon, the representatives reported,
that way did not open to propose any change of clerks,
and they were accordingly continued.
The minutes of the Meeting for Sufferings being read,
the address to the citizens of the United States, on the colored races,
embracing a strong testimony against slavery and the slave trade, was adopted,
and the Meeting for Sufferings directed to have
printed a sufficient number for circulation.

While the state of the inferior meetings, as brought before the Yearly Meeting,
by the answers to the Queries, in the different reports, was under consideration,
a good degree of solemnity was over the meeting,
and an interest manifested in the different subjects;
under which Friends spoke suitably to them.
When the business was finished, and the minute of the exercise of the meeting was read,
a deep silence followed, and expression of unity with it; when the meeting closed,
under the covering of this solemnity.
We have cause to return thanks to our Heavenly Father,
for his unmerited condescension to us poor, unworthy creatures.

Fifth month 6th. This being the time of Evesham Monthly Meeting, I attended it.
I was engaged to warn Friends of the enemy`'s temptation, to induce the travailing seed,
to let go their hope and belief that the Lord is near to support and preserve us;
and to persuade them that He is about to forsake and cast off this people;
by giving way to which, they would soon abandon their exercise of spirit,
for their own spiritual welfare, and for the cause`' sake.
The living members of the visible church have been enabled to feel and to mourn
over the degeneracy which from time to time has crept in among its members.
The prophet saw the state of the house of Israel,
under the vision of a valley full of dry bones, and he said,
"`Can these dry bones live?`"
But when he prophesied at the Divine command, there followed a shaking,
and bone came to its bone, sinews and flesh came upon them,
and the breath of life was breathed into them, and they became a living army.
We ought to maintain the faith,
that our Heavenly Father is as merciful and kind to the souls of the children of men,
at this day, as He was to our forefathers;
when He gathered them out of different denominations,
and made them a people to stand for his honor.
He will assuredly visit the children, by his good Spirit;
and if they submit to his will and guidance, will also make them vessels for his use.

20th. This morning, feeling an impression to go to the Arch Street Meeting,
I gave up to it; and after a time of silence,
the efficacy and importance of knowing Divine love to pervade our hearts,
by which only we can experience happiness in this life,
and a hope of blessedness in that which is to come, impressed my mind,
and I rose with it.
As proof of its abiding influence in our hearts, our Savior told his disciples,
"`If a man love me, he will keep my words, and my Father will love him,
and we will come unto him, and make our abode with him.`"
Blessed experience! to know the Lord to tabernacle with us,
and to set up his kingdom in the heart.
When this is the case, we cannot encourage feelings of enmity towards any,
but will be led to desire the redemption of others from all evil,
and to be brought into the same experience of Divine love with ourselves.
God is love, and he that dwells in love dwells in God and God in him.`"
"`Perfect love casts out fear; because fear has torment.`"
A violation of the Divine law produces fear of the presence of our Almighty Judge;
as Adam was afraid when he heard the Lord`'s voice in the garden,
after having transgressed.
"`The wicked flee when no man pursues;`" conscious of his guilt, he is afraid,
and suffers torment.
"`But the righteous is bold as a lion;`" not bold from
reliance on natural energy of body or mind,
but from conscious innocency; perfect love of his Maker,
and obedience to his will having banished all fear.

If we look back to the beginning of the Lord`'s work in us,
we may see how our hearts glowed with love to Him;
and in the heavenly enjoyment which He gave us,
our desires extended to the whole human family,
that all might be brought to partake of the Lord`'s goodness, as we then felt it.
Surely no change has taken place in Him,
or in the power and effects of his Spirit upon the heart;
and if we have changed and lost those precious feelings,
the cause is in and from ourselves.
I expressed the desire for us all, that as we are drawing to our everlasting reward,
we might know this love to increase towards all; that we might, as our first Friends did,
realize the testimony of our Savior,
"`By this shall all men know that you are my disciples,
if you have love one towards another.`"

Sixth month 9th. Having been preparing to take up a summer residence in Marple,
my family moved out on the 7th. My wife`'s health having been for some time impaired,
and the hot weather, and confinement in the city, increasing the symptoms of her disease,
it was very desirable to try what the quiet of
the country and a change of atmosphere would do,
for her comfort and the improvement of her health.

Seventh month 28th. I am convinced, that the vast business into which some enter,
is a great departure from the humility and self-denial which become a christian;
and the disposition to overlook this departure, and frame excuses for it,
is an evidence that the conscientious obligation, which Friends in the beginning,
felt and acted up to, has been much lost among many business men.
But I trust the Lord will preserve faithful Friends, and raise up among the young people,
those who will be brought, by the convicting power of the Holy Spirit,
to keep in moderation, in their trade or business;
and therein show the excellency of the religion of the Lord Jesus,
and that their eyes are directed to a heavenly inheritance,
above everything in this state of being.
How has the desire after riches drawn hundreds away from the work of salvation,
and a steady walking with God.
In this way the glory has departed from many,
and the strength and ancient dignity of our religious Society become greatly eclipsed.

31st. Was held our Select Quarterly Meeting, which was small;
but I felt constrained to encourage Friends in
the discharge of all their religious duties,
looking to the Lord for his blessing to rest upon us.

Eighth month 1st. I went to Germantown Meeting, sensible of poverty and weakness.
After a time of silent waiting,
the Lord opened the way to invite the people to come to Christ;
who when in the prepared body, invited those who labored and were heavy laden,
to come unto Him, take his yoke upon them, and learn of Him,
and they should find rest to their souls.
He alone can grant a sight of our sinful condition, give repentance,
and bring man back into the image of God, which was lost by transgression.
It was a season of unusual openness and freedom
in preaching the gospel of life and salvation,
through our Lord Jesus Christ,
both with reference to his coming and suffering in the flesh,
and now in his spiritual appearance in the heart, to regenerate and sanctify it,
and set up his holy kingdom, in place of the kingdom of Satan.
Much solemnity spread over us,
and there were those thankful for the favor conferred on us by the Lord, at this time.

10th. In the Quarterly Meeting held at Concord, this morning,
I felt much for the young people, who had given up to serve the Lord,
yet were buffeted by the temptations of Satan,
and the floods of discouragement which the dragon was casting out of his mouth,
if possible to destroy the true seed;
and I was led to counsel them to gather inward to the Lord,
and He would lift up a standard against the enemy, defend and deliver them.
It is through tribulation the righteous enter the kingdom in this life,
and in the world to come.
The Lord on high is mightier than the noise of many waters;
and we have a High Priest touched with a feeling of our infirmities,
who knows that without Him we can do nothing.
He constantly watches over his devoted children;
and though at times He hides his face from them,
yet with everlasting kindness and compassion will He have mercy upon them.
There is no new way to the kingdom, nor any new doctrine to be preached.
It is the same strait gate and narrow way which our fathers entered and walked in;
who have been gathered among the spirits of the just made perfect.
As we are faithful in a little, we shall be made rulers over more,
and by the baptism of the Holy Ghost and fire, be prepared like the wheat,
to be gathered into the garner, where none can hurt or annoy us.

Ninth month 13th. We have been at Marple three months;
most of which time we have attended the meeting here with satisfaction;
a number not members generally coming on first-day,
so that the meeting has been larger than is common.
There seems to be a temporary stir on the subject of
religion among other people in several places,
both in England and in this land;
and if the Lord sees fit to work by his own invisible power on their hearts,
He may also make way for his servants to labor with some effect,
to gather in various neighborhoods,
those who have been very indifferent to their soul`'s salvation.
It would be a great comfort to see young and old bending to the yoke of Christ,
and be thereby preparing to join the Lamb`'s army, in spreading his kingdom in the earth.
Helpers may thus be raised up in our Society, to maintain its principles and order,
and to fill the places of those who have fallen away from the Truth,
or have been removed from works to rewards.

30th. After spending about four months at Marple, very agreeably,
we returned to the city, and soon felt ourselves very comfortable under our own roof;
having cause to thank our heavenly Father for the many blessings He has granted us,
both in renewing our health, and giving us to enjoy other temporal and spiritual gifts.
May we, through his pardoning mercy in Christ Jesus our Savior,
and the continued influences of his Holy Spirit, be more and more sanctified,
and made devoted to his service,
that our salvation may be wrought out with fear and trembling;
that our lives may be to his glory, and when the end comes, we may,
through his unmerited mercy,
be admitted among the blessed in the realms of eternal light, peace and joy unspeakable,
and full of glory.

Eleventh month 14th. At our first-day morning meeting,
under a view of the uncertainty of life,
and the great importance of being prepared to meet death,
I felt constrained to revive the language of the prophet,
"`The voice said, Cry. And he said, what shall I cry?
All flesh is grass,
and all the goodliness thereof is as the flower of the field;`"
"`The grass withers, the flower fades; but the word of our God shall stand forever;`"
and to impress upon all the danger of living at ease and in indifference,
in our outward comforts; putting off the work of salvation,
and being thoughtless of the certainty of death, which may be nearer than we imagine;
when wealth, worldly honor and friends, cannot defend us from its stroke.

Twelfth month 12th. In our first-day morning meeting,
my mind was clothed with strong desire,
that the true spiritual nature and power of the gospel dispensation,
might be more generally and deeply felt among us;
bringing all into a fervent travail of soul, to experience the work of regeneration,
and more intimate communion with the Father of spirits,
than is known by the professors of the christian name generally.
It is said,
"`Jesus stood and cried, If any man thirst, let him come unto me, and drink;`"
and on another occasion, He said,
"`Whosoever drinks of the water that I shall give him, shall never thirst;`"
that is, for any other;
"`But the water that I shall give him, shall be in him a well of water,
springing up into everlasting life;`"
and out of the believer in Him, He declared,
"`Shall flow rivers of living water.
He spoke of the Spirit, which they that believe in Him, should receive,
after his glorification.`"
And the same disciple that recorded these sayings of his Divine Master,
further testifies in the Revelations made to him,
"`And the Spirit and the bride say, Come.
And let him that hears, say, Come.
And let him that is athirst, come.
And whosoever will, let him take the water of life freely.`"
I was drawn to show that we are not dependent on man, to obtain the life and spirit,
which alone can nourish the soul unto everlasting life;
but that it is through the mercy and goodness of the Savior,
the Mediator between our Heavenly Father and our immortal souls,
that a measure of his Holy Spirit is granted unto us; by obedience to which,
the work of regeneration is effected in us,
and the soul thereby renewed up into the image of God, which Adam lost by transgression.
Thus we are truly brought into the gospel dispensation; which is a dispensation of life,
and spirit and power; for Christ came, that his "`Sheep might have life,
and that they might have it more abundantly.`"
Hereby we are made members of his mystical body, the church; and as we keep our places,
will be ministers of righteousness and of the Spirit.
It appeared to me very important that all should thus
become worshippers of the Father in spirit and in truth;
and though it might be in silence, we would, at times,
experience mental prayer and praise, like a cloud of incense,
to rise from our assemblies before the throne, which would find acceptance with Him.

17th. In our Meeting for Sufferings held today,
after a beloved Friend had expressed a desire,
that Friends might become a more united body, supporting our principles and testimonies,
and keeping in their tents like Israel of old; where, it was said,
no divination or enchantment can prevail against them;
I felt constrained to add my desire, that we might, individually,
more fully experience a participation of the Divine, inward life,
for which our Savior came, that his sheep might abundantly partake of it.
In this, we should know the unity of the Spirit, in the bond of peace,
and resist all attempted innovations upon our doctrines and testimonies.
Our ancient Friends were raised up to call the people to the
inward participation of the life and power of godliness;
but it is to be feared, that many among us have fallen short of this;
which is the reason they have let those testimonies fall from their hands.

By a letter received from a Friend in Ireland,
I understand there is a probability of London Yearly Meeting so altering its discipline,
as to allow of members marrying those not in membership;
and doing away the Query respecting plainness of speech, behavior and apparel.
The prospect for our Society, should these changes take place,
looks gloomy and discouraging; yet I hope there will be many,
who will be stirred up and strengthened to stand firmly,
in the meekness and constancy of true wisdom,
in the defense and maintenance of all our testimonies, as required of our forefathers,
to hold up to the world.
But it would seem that our trials and sufferings are increasing, rather than diminishing.

1859, First month 9th. First-day, we had a favored meeting this morning.
It was a solemn time, for which we must account.
The administration of poverty and humiliation were the wholesome food dispensed to me.
It is a great favor to be emptied of self,
and renewedly brought to a sense of our nothingness.
There is preservation in it.

16th. We had a pretty large meeting this morning, first-day; in which it felt to me,
there were strangers seeking something On which they might rest their tossed minds.
From these feelings,
I thought the Lord was bringing some sinful persons
under conviction and remorse for their transgressions,
and if they would yield to the administration of condemnation,
He would prepare them for the gifts of repentance and forgiveness of sin;
and by the washing of regeneration and the renewing of the Holy Ghost,
sanctify and make them fit temples for Him, by his Spirit, to dwell in.
I felt impelled to address such a state,
and to labor to persuade them to stand still and wait for the salvation of God.
Not to look abroad for anything to satisfy the mind, or which would stifle conviction,
or act as a substitute for true settlement on the right foundation.
But to keep inward, under the operation of the Lord`'s mighty hand;
turning their back on temptation, and following Christ in the path of holiness;
who would give peace to the troubled spirit, and establish them upon Himself, the Rock;
against which the gates of hell shall never prevail.
He will never permit the powers of darkness to overcome his children,
if they look daily unto Him for preservation, putting up their prayers to Him,
morning by morning.

It seemed to me that the Shepherd of Israel was still round about us,
offering his love and mercy; and were He received into the heart and obeyed,
He would gather many to his fold,
and show others that He had not forsaken us as a people.
Through the power of his Spirit we should be
instrumental in turning many to righteousness,
showing forth his praise.

23rd. Apprehending it to be a pointing of duty,
I went over to Newton Meeting, being first-day.
The company assembled was small.
I felt unfit for public service; but in a feeling of great un worthiness,
I was quickened by the revival of the Master`'s language to his disciples,
"`What I say unto you, I say unto all, Watch;`"
"`Watch and pray, lest you enter into temptation.`"
I was much humbled,
and thereby in a better condition to communicate what opened on my mind;
under a clothing of charity, and sympathy with the little remnant;
some of whom appeared to me to feel their weakness and stripped state;
neither fathers nor mothers in religious experience and weight among them.
Afterwards I was bowed in supplication, that merciful help might be bestowed on all of us.

Second month 20th. Deep inward trials have much attended me for weeks past,
under which strong cries have been put up to the Lord for preservation.
I believe my mental breathings to the Father of mercies have been heard,
and though at times surrounded by clouds, a ray of light would break through,
and tenderness of spirit before the Lord would be felt, creating feelings of gratitude;
and thanksgiving to Him for his mercy, would overflow my heart.
These dispensations, I believe, are designed for my humiliation,
to bring me back to my horn book, as dear William Savery said on his deathbed;
which saying, I had revived in our Quarterly Meeting of Ministers and Elders,
held the forepart of this month.
May the Lord make me more and more willing to submit to,
and abide under all his baptisms, to reduce and keep me in the state of a little child;
constantly looking to Him for preservation, and for daily bread;
and that his Holy Spirit may keep me from being caught by any snare of the cruel enemy.

On the 16th, I attended Salem Quarterly Meeting.
At the reading of the answers to the Queries, the awfulness of a parent,
at the approach of death,
seeing that he had neglected the religious care and restraint of his children,
and had by his own example, led them into the world, instead of bringing them to Christ,
came over me in so serious a manner,
that I was led to open and press the consideration of it upon some present.
The preservation and right training of children often greatly
depend on the religious example of their parents;
and not only their benefit, but the clearness of the parents from condemnation,
at that awful hour, and the belief they had done what they could,
must be of unspeakable importance.

Third month 27th. The Lord can raise up his servants,
and give them power to preach his word, over all the opposing powers of darkness,
and the secret resistance that others may cherish,
who feel coldness and indifference towards them.
True ministers of the gospel have nothing in view, but to comply with the Lord`'s will,
that they may be found clear in the day of account.
The spirit of opposition to such is felt at times in meetings,
and may be permitted to close up the way for gospel service;
but they who indulge it will bring flatness over themselves,
and have to suffer for their wrong opposition to the Lord`'s children and servants.
How different is the state of meetings,
where brethren and sisters draw near to one another in heart and spirit,
like holding up each other`'s hands, travailing together for the arising of Divine life,
and rejoicing when the Lord opens the way for the
current of true baptizing ministry to flow freely.
Elders are appointed to watch over the ministry, to guard and counsel ministers,
when needed; if they have left the gift,
or said anything not according to sound doctrine; but this is not all their duty.
They have as much need as any others, to watch over themselves,
that they may know what spirit rules and actuates them;
and they are to give themselves up to sympathize with the ministers,
and to share in bearing the burdens which they are brought under;
by which they may be preserved from judging in their own will and temper,
and may be made instrumental to help them, and by a harmonious labor and travail of soul,
assist in bringing to the birth the concerns which ministers are brought under.
Hereby they are fellow-helpers in the Lord;
and when ministers are raised up by their Divine Master in his authority,
then a harmonious exercise is again known in the preaching of the gospel,
the great Name is exalted, and the baptizing power goes over the meeting.
Ministers and elders thus fulfill their respective services,
and contribute to each other`'s growth and establishment in the blessed Truth.
The one preaching what the Holy Spirit opens to them,
and the other keeping close to them in spirit, to aid and steady them in their work,
that they may not give out,
nor deviate from the line of service appointed
them by the Great Minister of the Sanctuary.

Fourth month.
Heaviness of spirit has been my portion at times, on account of our poor Society.
There seems little to inspire with hope,
that it will soon rise out of its depressed condition.
Yet, evidence is granted from time to time, that the everlasting Arm is underneath,
and that the Lord sustains and preserves his afflicted children.
I have passed through low places, but have been kept from casting away my confidence,
having in mercy had it renewed.

18th. Commenced the Yearly Meeting for business.
The Meeting for Sufferings having prepared an enlarged edition of the Book of Advices,
first issued about fifty years since,
the Yearly Meeting directed it to be distributed
by the Monthly Meetings among their members;
which I hope will be useful,
in reviving and seriously impressing on their minds the
importance of our christian testimonies.
The consideration of the state of the subordinate meetings,
on reading the Queries and the replies, was solidly gone through,
without much remark being made.

On fifth-day afternoon,
after the consideration of the use of spirituous liquors by the members,
and the school education of the children belonging to the meeting,
the minute on the state of things among us, as exhibited by the replies to the Queries,
was read; and after sitting some time in much quiet and solemnity, the meeting concluded.
We have cause for much thankfulness,
that the meeting was favored with the degree of unity and solid weight that prevailed.

Fifth month 18th. I am afraid there is a disposition in some,
to speak highly of a belief in the sufferings of our blessed Savior,
without inculcating submission to his crucifying power inwardly revealed;
the baptism of the Holy Ghost and fire.
It is by the latter, that the chaff is burnt up, every defilement is removed,
and we are prepared to receive the fulness of the blessings of the gospel of Christ,
and the benefits of his sufferings and death.
The gift of grace comes by Him, by which we are made new creatures,
for if any man be in Christ, he is a new creature; old things are done away,
and all things are become new, and all things of God,
who has reconciled us to Himself by Jesus Christ.

Sixth month 17th. Was held our Meeting for Sufferings;
in which was mentioned the circumstance,
of some young members having inadvertently paid their militia fines,
connected as it had been, with the personal tax, without being specified.
The meeting made a short minute to incite Friends to a
faithful support of our testimony against wars and fightings,
and to put them on their guard against paying such fine.

23rd. A war having broken out in Europe, between the French and Austrians,
occasioning great destruction of life; it produces mournful feelings,
on account of the slaughter of human beings, having immortal souls to be saved or lost;
and for the unenlightened condition of those engaged in it.
To me it is inconceivable, how man can be so lost to the common feelings of humanity,
and the awfulness of rushing souls into eternity, as to destroy wantonly,
without any fear of Divine vengeance, his fellow man; especially,
when we remember the declaration of the apostle,
"`You know that no murderer has eternal life abiding in him.`"
What an unchristian spirit must he have, who can urge men under his command,
to fire into an army, probably striking down thousands,
or placing his army in the position of being
destroyed in the same way by their opponents.
What account can such commanders, and their military subordinates,
give to the Almighty Creator of us all, for the dreadful carnage,
by which suddenly and barbarously,
thousands of their fellow creatures are deprived of life;
over whose existence they have no right of control.
How needful for christians to walk humbly before the Lord, asking of Him,
strength and wisdom to do his will, and to show forth to those around them,
the fruits of his Holy Spirit, that the kingdom of Christ, the Prince of Peace,
may be spread in the earth, by their obedience to Him.

25th. Went to the Arch Street Meeting this morning,
under feelings of sympathy with Friends there, now much reduced in number.
The fear of putting forth a hand unbidden was felt,
and I strove to keep inward before the Lord, waiting to see what He would do;
until the intimation to rise impelled me to stand up, and to say to the fearful ones,
that whatever might be our fears and apprehensions of danger to ourselves,
or to the church and cause of Christ, the foundation of God stands sure,
having this seal, the Lord knows them that are his.
He knows their afflictions, and if they wait upon Him,
He will keep them in the hollow of his Omnipotent hand.
He has always regarded the fears of his trembling children,
and to his immediate followers, Christ said, "`Fear not little flock,
it is your Father`'s good pleasure to give you the kingdom.`"
Friends were encouraged to wait upon the Lord, and put their trust in Him.

28th. Went to the North Meeting this morning, having had, the preceding day,
a pointing to go there, which was revived this morning.
I desired to obey it in simplicity, yet to be preserved from making any mistake.
The importance of daily learning the lesson of
dwelling in our own hearts with Christ the Seed,
that we may be taught of Him, who declared Himself to be meek and lowly of heart,
was brought before me, and opened to the meeting.
It is only while we are thus kept with Him, that we can sympathize with others,
and travail with the Seed for its arising into dominion;
and being made sensible of our own frailties,
and the meekness and gentleness of Christ abounding in us,
the rough Esau nature will be more and more subdued, and the peace of God,
which is substantial happiness, will be enjoyed in ourselves,
and with those of like experience, in whose society we mingle.
We shall be in a state to receive warning of any temptation that awaits us,
and immediately to put up our prayers for preservation,
looking to the blessed Savior for his aid; and He will deliver us.
What harmony and sweet enjoyment prevail among the people,
who are brought into such a case!
Eighth month 7th. At our first-day meeting,
the way opened to hold up the great importance of doing our duty while the day lasts,
both for our own sake and that of others;
for we know not how short the time may be that
will be allotted us to do the Lord`'s work in;
and through his mercy to repent of and forsake our sins and transgressions,
that we may obtain forgiveness, through the propitiatory suffering of the Savior,
and come to know our salvation wrought out by Him.

Ninth month 4th. Attended the first-day meeting at Germantown, which was quite large.
After a time of silent waiting, I was enabled to bear testimony to Christ,
who was given for God`'s salvation to the end of the earth;
whom "`God has highly exalted and given Him a name, that is above every name;
that at the name of Jesus every knee shall bow, of things in heaven, and things in earth,
and things under the earth;
and that every tongue shall confess that Jesus Christ is Lord,
to the glory of God the Father.`"
However his children may be tried, and at times cast down, surrounded by many fears,
He will be near to support them,
and make the humiliating dispensations which they endure, a blessing.
I believed there were those for whom my desire was,
that they would not let go their hope and confidence in Him,
who is emphatically called the Captain of salvation;
who would fight all their battles for them, and carry them through to the end.
He declared that on Himself, the Rock, He would build his church,
and the gates of hell shall not prevail against it.

11th. During the meeting, this morning,
my mind was much occupied with the consideration of the evil heart of
unbelief in those who are departing from the living God,
and violating his law made known to them.
The enemy presents his temptations to induce them to gratify the carnal appetite,
and persuades them it will confer happiness;
and there will be no danger of Divine judgment falling upon them.
But our Savior pronounced him a liar and the father of lies; for there is no truth in him.
We sat a long time in silence, during which some strangers came in.
I was afraid to leave the meeting,
without rising to open the subjects that had been resting on my mind,
and to hold up the continued mercy of Almighty God, in following rebellious man,
and bringing him under compunction for sin and transgression.

15th. We had little business to occupy our attention at our Meeting for Sufferings today.
When it was finished,
the clerk made some observations upon the necessity of every
one coming more under a travail of spirit for his own sake,
and for the cause of Christ.
Much had been rightly said, about doctrines,
but he believed that more of the life was needed;
and it was only as Friends are brought individually to partake of it,
that the Society would be restored to its former condition.
S+++.+++ C. spoke after him, expressing that the design of our Society being raised up,
was to promote the gospel of the grace of God; and its work in the hearts of the people;
corresponding with what had been already expressed.

I adverted to the coming of Friends from England to Pennsylvania and New Jersey,
in the early settlement of this country,
with the view of settling where they could hold and
spread their religious principles and testimonies,
out of the way of persecution;
and that Philadelphia Yearly Meeting had always
supported those principles and testimonies.
I desired that we should firmly hold to our ancient doctrines and testimonies,
under the guidance of the Head of the church,
whatever efforts others might make to introduce changes.
As we keep to our individual exercise, to know the life of the great Head to prevail,
we shall be more and more united to one another,
and still be examples for others to look to and follow.
We sat for a time, under feelings of solemnity and tender fellowship,
when David Cope said, he believed he would not be easy to leave the meeting,
without saying, he united with what had been said,
and added the expression of some similar sentiments.

Friends parted under feelings of unity; one remarking to me, before he left his seat,
that he had not known what the meeting would find to do,
but he loved to have such feelings as he then experienced;
and many others spoke of it as a good meeting.
