== Chapter XXXIII

[.chapter-synopsis]
* 1859--1862. Religious Engagements at and about Home.

1859, Tenth month 5th. This day completes my seventy-second year.
Seldom since the work of religion was begun in me,
have I experienced more humbling dispensations than for several weeks past.
My soul has been, as it were, poured out before the Lord, day and night,
beseeching Him that He would defend me against temptation,
and bring me down into low places; that every impurity may be removed,
and every chaffy thing in me may be burned up with unquenchable fire.
My secret cries have been unto Him, that whatever He may see necessary,
may be administered, to keep me from falling,
or bringing any reproach upon the blessed cause of truth and righteousness,
of which I have made profession, and testified before many witnesses.
I have thought there was evidence that the Lord`'s watchful care and mercy were over me;
and hope and trust have been at times felt, that his everlasting arm, though invisible,
is underneath; supporting and defending a poor creature,
who is unworthy of the least of all his favors;
that I shall be preserved again to behold the light of his glorious countenance,
and be authorized to declare to others of what He has done and
will do for those who call upon Him in sincerity and truth,
and wait for the renewing of that life which is hid with Christ in God.

In the afternoon of first-day, the 6th,
I was very unexpectedly raised up to bear testimony,
to the essential necessity of coming to the inward, living and saving knowledge of God,
and of his dear Son Jesus Christ.
The possession of the Holy Scriptures is an unspeakable favor,
especially to the soul that is obedient to the manifestations of the Holy Spirit;
and we may see that their testimony points to the inward work,
and the indwelling of God with man by his Spirit.
"`If any man love me,`" said Christ, "`he will keep my words,
and my Father will love him, and we will come unto him, and make our abode with him.`"
Again, on another occasion, He said to his disciples,
"`I am the Vine, you are the branches;`"
"`As the branch cannot bear fruit, except it abide in the Vine,
no more can you, except you abide in me.`"
Only as we experience the cleansing operation of the Word, that is quick and powerful,
can we become living branches of the true Vine,
and members of the church of which Christ is the adorable Head,
and know the work of regeneration perfected in us.
In this way we come to the true and saving knowledge of God and of Christ;
and persevering in faith and obedience, witness an establishment in the Truth,
and the Lord Jesus to be the Author and the Finisher of our faith;
fitting the soul for an admittance into one of
the mansions which He prepares for his devoted,
faithful children, in his Father`'s house.

Eleventh month.
Our Select Quarterly Meeting,
held on the 5th was attended with religious exercise
for our own preservation out of all snares,
and that we might be kept inward to the Lord;
waiting steadfastly for his putting forth in the service to which He would appoint us;
that nothing that man can do in his own will, might be substituted for it.

29th. I was at the North Meeting; in which ability was renewed to preach the gospel.
A warning was given against a worldly spirit;
that instead of being faithful stewards of the means entrusted to them,
some may be refraining to dispense for the benefit of others,
that portion which their Lord would require them to give, in supplying their needs.
Some are indulging in luxurious living, and in costly furniture of their houses.
Our Savior and his disciples set the example of using simple fare,
and possessing little earthly treasure.
Inasmuch as we brought nothing into this world, and could carry nothing out,
it was our duty to be faithful in the proper use of what we held in trust.
My mind was clothed with love towards all,
and sincerely desired we might experience a united
travail for the advancement of the cause of Christ,
and for one another`'s good.

Twelfth month 31st. For about a week, I have been affected with dizziness,
to a greater degree than ever before.
The uncertainty of what serious consequences might follow, at this period of life,
has brought over me feelings of solemnity, in the thought that the end may come suddenly,
and how soon, I could not foresee.
It induces self-examination; and the need to be prepared for that awful event,
has dwelt impressively on my mind.
Feelings of resignation to the Divine will, have been experienced,
in the hope that mercy and goodness will attend me; and that when the close comes,
there will be a blessed hope of entering into rest,
and knowing all my sins to have been forgiven, and washed away by the blood of the Lamb;
who died for our sins, and rose again for our justification.

1860, First month 11th. My appearances in the ministry are not frequent,
being mostly silent, in our religious meetings;
often fearing whether we are sufficiently favored in them,
with a living travail of spirit for ability to worship the Father acceptably,
and knowing our Divine Master to be in the midst.

I have been afraid, on my own account, and for some others,
whether the world is properly kept out; and a sufficient exercise steadily maintained,
to draw near to the Lord, so as to feel a true,
harmonious labor to perform spiritual worship,
and to strengthen one another to discharge our respective duties.
But the Lord is merciful to us poor, unworthy creatures, and is still opening, at times,
the spring of gospel ministry.
Today, the deep and weighty testimony of the apostle,
with which he commences his epistle to the Hebrews,
setting forth the Godhead of our Lord Jesus Christ, by whom the worlds were made;
his purging our sins, and his glorification at the right hand of the Father,
opened very impressively upon my mind; but which, from its awfulness,
I felt afraid to communicate.
After a time, however, I was most easy to submit to the impression; desiring to deliver,
in childlike simplicity, what would be gradually opened to me,
without any embellishment or human devising.
I believe the Lord helped me,
and a measure of his baptizing power was spread over the meeting;
and when it was through, I breathed for preservation, in a solemn frame of mind.

28th. For many weeks our country has been kept in agitation by
threats of the Southern members in Congress,
to break up the Union, and their intention to set up a distinct government,
composed of the Slave States.
Political disputation, and bitter charges against one another,
have not only hindered the choice of a Speaker in the House of Representatives,
but they have brought great distress on the minds of many persons in all the States.
All slaveholders are not favorable to a dissolution of the federal compact;
and in the Southern as well as in the Northern States,
serious apprehensions must be entertained respecting such an event,
and of the dreadful consequences that would attend it, accompanied by convulsions,
and probable bloodshed, should the tie that has bound the States together, be dissevered,
and every State left to its own course.
The hearts of men are in the hands of the great Arbiter of nations,
and He only can restrain the wrath of man,
and keep wicked men from breaking down the government.
But all kinds of abominations have gone over the land; in the Free States,
and among slaves and their masters.
Nothing but unmerited mercy can withhold the indignation due to our sins,
and prevent unprincipled men from laying the country waste.
It is hoped that time, and the cool arguments of some influential men,
are working changes in the wishes of inconsiderate, headstrong demagogues,
and that they will be brought to the exercise of their sober senses,
so as to abandon their wicked projects.
The return of harmony, and the prevalence of peace, will be an unspeakable blessing.

Second month 4th. Our Quarterly Meeting of Ministers and Elders was small,
several members being away from indisposition.
There was an exercise in the meeting,
and communications were made in support of our testimony to a living gospel ministry,
and the worship which is in spirit and in truth.

6th. But little was said in the ministry at the Quarterly Meeting for discipline.
We got through with the Queries satisfactorily.

15th. Snow fell;
but feeling an affectionate and sympathetic
draft to the Friends of Salem Quarterly Meeting,
I went to Woodbury, this morning.
In their little Select Meeting,
the spirit of tender feeling went forth for the consolation of
the few tribulated companions of their Lord and Master.
In the meeting for worship, preceding that for business,
I felt impressed to revive the language of our Savior,
"`I am the way, the truth, and the life; no man comes unto the Father but by me;`" also,
"`No man knows the Son but the Father; neither knows any man the Father save the Son,
and he to whomsoever the Son will reveal Him.`"
Showing that it is by the revelation of Christ by his Spirit in the heart of man,
that the saving knowledge of God and of his beloved Son, is communicated and received.
There it is He shows man his condition; what the Divine will concerning him is;
and as He is received, He gives power to come out of all evil, and to do his will,
in following Him in all his requirings.
In this way Christ becomes man`'s Savior and Sanctifier, and leads him along,
step by step, in the way of salvation;
opening to him those things that belong to his peace, building him up,
and establishing him as a member of his church, upon the immutable foundation,
which is Himself.
Thus he is made a partaker of the mercy of God,
and the faith of which Christ is the Author.

The business of the Quarterly Meeting was conducted with religious weight; and, I hoped,
to the strength and encouragement of Friends.
Returned home with feelings of peace, and hoping for preservation out of all evil.
In the latter part of this month, I made a visit to our Springfield brothers and sisters;
attended their meeting on first-day, and their Monthly Meeting on second-day;
in both of which I had some service in the ministry of the gospel;
endeavoring to strengthen all classes,
to greater faithfulness in performing their religious duties,
that the world may be kept under foot, and by laboring in the Lord`'s vineyard,
fruit may be gathered unto life eternal.

Third month 8th. I went to the Arch Street Meeting,
and was engaged in holding up the favor of having a High
Priest that is touched with a feeling of our infirmities,
and was tempted in all points like unto us, yet without sin;
one who is able to succor them that are tempted, and who come unto God by Him.
The more we have partaken of his love and forgiveness, the more we shall feel for others,
and at seasons desire their forgiveness,
and participation of the same love and mercy of God,
in and through our Lord Jesus Christ.
The meeting was still and solemn.

At my own meeting I have been much shut up.
The withdrawing of the sensible flow of Divine life, is doubtless for our good,
and to show us that we have no power to command rain from heaven;
and that the people are to be turned to the Fountain of living water in themselves,
for refreshment and strength.
We all have need to desire to be searched by the Holy Spirit,
that Satan may not be permitted to deceive us in relation to our own state;
but through the continued mercy and condescension of the Lord our God,
we may be bowed in fear and reverence before Him;
and daily put up our prayers for help to fight the good fight of faith;
that we may know Satan to be put down and trodden under foot.

12th. Feeling a draft in my mind to attend Haddonfield Quarterly Meeting,
I crossed the river this morning.
The Select Quarter was small,
only five men and perhaps eight or nine women of their own members, were present.

15th. The meeting held this morning was, I think, unusually large,
many young people attending and sitting in a solid manner.
I felt drawn to speak of the different periods of life,--youth and old age,--
and the unspeakable comfort and peace of being able to look to the close,
with humble trust of being admitted into the everlasting kingdom of the Redeemer.
To be thus favored, it is important to lay the foundation in early life;
and the visitations of the Holy Spirit are extended to young people,
even when they have few opportunities of receiving
instruction from mingling with religious friends.
The Lord condescends to commune with them, and to show them his blessed will,
in relation to those things which are wrong, and his controversy is with.
If they obey, He gives power to resist temptations, and turn the back upon them,
and thus prepares them to perform his will.
It seemed to me, the Lord was regarding our present low state,
and would visit sons and daughters, and bring them out,
to exalt and honor his name and cause; and raise us up as out of the miry clay,
and make his glory to shine among us, as in days of old, as in former generations.

16th. Was held our Meeting for Sufferings;
which united with a concise declaration of the rise and faith of our Society,
designed for insertion in the American Encyclopedia, printing in New York.
Also, a minute, setting forth our disunity with all wars, fightings and bloodshed;
the use of violent means to obtain the freedom of the slaves,
or for putting down or setting up governments;
and also with certain letters and paragraphs, inserted in some newspapers,
which are opposed to our principles on these points,
and which essays were written in the style of Friends; all which we deny.
The minute was directed to be printed and circulated.

Fourth month 8th. The anticipation of our approaching Yearly Meeting, has been, at times,
attended with feelings of much concern.
There has been a great stripping of members of enlarged experience,
and understanding in the management of the affairs of the church,
under the direction of the great Head.
There is a spirit seeking to lay waste Friends,
who cannot unite with new principles and practices, or a dividing,
scattering disposition.
Yet I believe the Lord has not forgotten to be gracious, but as we are brought low,
and keep sensible that we can do nothing without Him, He helps us,
and gives a little renewal of our faith.

This morning, in our meeting, the Master was pleased, by his quickening power,
to renew my faith,
and to raise me up to set forth the doctrine of his immediate guidance, protection,
and regenerating work by his Holy Spirit; both to reprove the world of sin,
of righteousness and judgment; and as it is submitted to, its leading into all truths,
its taking of his mysteries and showing them to his obedient children,
and bringing all things to remembrance, whatsoever He has said unto us.
Our Savior said, "`If you being evil, know how to give good gifts to your children,
how much more shall your Heavenly Father give the Holy Spirit to them that ask Him.`"
I felt particularly for our dear young Friends,
desiring that the things of the world may not be permitted to
separate them from the love of God in Christ Jesus;
but that they may steadily take up the cross, deny themselves,
and follow Christ in the way He would lead them.
The renewed evidence that the Lord`'s mercy and goodness are not withdrawn,
comforted and cheered my mind, and lifted up my head, in holy hope and trust,
that He would continue to help in every time of need.

13th. Our Meeting for Sufferings, held today, was unusually small.
I thought there was a feeling of unity among us, in finishing our business,
preparatory to the Yearly Meeting near at hand.

14th. The Yearly Meeting of Ministers and Elders was also small;
yet we were favored with holy help;
under which I was enabled to set forth the
qualification and authority of a minister of Christ.
Unsound doctrine could not be gospel ministry, nor could sentiments, sound in themselves,
but declared without Divine authority, have a baptizing effect upon the audience,
and be received as the preaching of the gospel of Christ.
While it is needful to guard against creaturely activity,
it is also necessary to be aware of the suggestions of Satan, who would induce the timid,
cautious ones, to hold back from their duty; and thereby lose their strength,
and the meeting be deprived of what the Head of
the church designed for its comfort and help.

16th. The Yearly Meeting convened, which was large, and over the minds of Friends,
the wing of Ancient Kindness was spread.
There was an ingathering to Christ, and solemnity and weight were felt.
The representatives were called; the minutes of their appointment,
and one of the reports were read.

In the afternoon,
the minutes of the Meeting for Sufferings were brought before the meeting,
and much united with.
On the 17th, the meeting entered upon the consideration of the Queries and Answers;
during which, many Friends were led into a lively exercise,
on account of the subordinate meetings and their members;
and ability was given to administer counsel and warning upon many points,
and to encourage Friends to greater dedication to the cause of Truth,
and the discharge of their religious duties.
It was a favored season; so that many thought they had not attended such a sitting;
and others, that it resembled some of former days.
It was cause of thankfulness, that the Master condescended to our low estate,
and showed that He had not forsaken us.
19th of the month the meeting closed.

Fifth month 3rd. I went to the Arch Street Meeting, and sat a good while in poverty.
The danger of being deceived in our estimate of our own condition,
and by the flatteries and good opinions of others, so as to settle down in ease,
and unconcernedness,
under the belief that our spiritual state is better than it is in the sight of the Lord,
was brought before me.
As time was steadily passing away,
and carrying all of as nearer to the end of our pilgrimage, and the eternal world,
it was of the greatest moment we should seriously lay it to heart; and, above all things,
be desirous that the Lord would give us a true sight of ourselves,
and bring us under a fervent concern to have our garments washed,
and the heart cleansed by the baptism of the Holy Ghost and fire;
that it may be prepared for the Lord of life and glory to take possession of.
"`If I wash you not,`" said Christ to Peter, "`you have no part in me.`"
"`He that believes and is baptized, shall he saved.`"
I felt strong desires that every one might be brought to submit to this baptism,
and experience a right sense of his state;
and that the Lord would accomplish his work of sanctification in every one.
I hoped that the awakening power of the Holy Spirit attended,
and raised desires after righteousness; and that when the end comes,
we may be found clothed with the pure, white linen, so as to join the just,
who surround the holy throne.

5th. Our Quarterly Meeting of Ministers and Elders was held.
Through mercy, we were a little helped,
and departed under a sense of the Lord`'s goodness to us,
unworthy as we are of the least of all his favors.

Seventh month 18th. I felt lonely in the midst of company;
which tended to turn my thoughts inward to feel after the Lord,
who in his merciful condescension, gave me a quickening sense of his presence;
which tendered and filled my heart with gratitude to Him for his unmerited,
merciful regard.
How little and low, and as nothing, do we feel when He condescends to appear.
This is the knowledge of God, and of Jesus Christ, through his blessed Spirit,
that is life eternal to the soul, and far beyond all opinions that man forms,
without the immediate manifestation of his Spirit.

22nd. Our meeting at Orange Street is greatly reduced.
After sitting a long time;
the constraining power of Christ led me to break the silence on behalf of those who
at times are brought to long for a knowledge of the right way of the Lord,
and to obtain reconciliation with Him, and a sense of his Divine approbation.
It is He who begets these hungerings after righteousness; and He alone can satisfy them;
and as He is obeyed in all his requirings, He will meet the penitent, humbled soul,
with the reward of sweet peace.

23rd. Our little Select Preparative Meeting was held this morning,
with evidences of fellowship, and desire for the right support of the cause of Christ.

Eighth month 20th. For weeks past the enemy seems to have been let loose upon me;
and at times I greatly desired his presentations might be removed from me.
This dispensation gave me a renewed sense of my own nothingness,
and of the great need of steady watchfulness and prayer to the Lord,
for his merciful regard and preservation.
The case of the Apostle Paul, to whom was given a thorn in the flesh,
a messenger of Satan sent to buffet him, lest he should be exalted above measure,
was lately brought into remembrance; and that he had besought the Lord thrice,
that it might depart from him; but the Lord said unto him,
"`My grace is sufficient for you, my strength is made perfect in weakness;`"
which gave me the hope the present trial had been permitted for my humiliation.

31st. My wife and daughter, who went to Cresson, on the Alleghany Mountain,
about two weeks ago, returned this afternoon.
Their safe arrival, and the improvement of my wife`'s health,
afforded me much satisfaction.
The change to the atmosphere on an elevated point of mountainous country,
seemed to effect a decided alteration in my wife`'s feelings;
which was cause of thankfulness to our Heavenly Father;
both for her release from very distressing sensations,
and for our comfort in the prospect of her health being restored,
so as to enable her to pursue her duties, and contribute to the happiness of her family.
May it please the compassionate Shepherd of his flock,
to continue his blessing to rest upon us, and keep us on every hand.

Ninth month 2nd. Our first-day morning meeting was a favored opportunity;
my wife being engaged in testimony to the continued merciful
visitations of the Lord to the souls He has made,
even to the rebellious.
I was drawn to kneel in vocal supplication to the Father of mercies;
to regard with compassion our low estate, who have no power to keep ourselves;
and when the enemy comes like a flood to destroy the souls which God has made,
He would in renewed mercy lift up his Holy Spirit as a standard against him;
warn us of his temptations, and enable us to resist them;
that we may glorify Him who alone is forever worthy.
These acts are very humiliating to me, and are entered upon with fear and reverence.

Eleventh month 12th. Rode to Concord,
and sat with the Ministers and Elders in their Quarterly Meeting.
Next day the Quarterly Meeting for worship and discipline, was a solid, favored time;
in which the gospel stream flowed impressively upon many hearts.
My sister, H. Rhoads, closed in solemn supplication.
I believe it was a season of the renewal of strength and refreshment
to the livingly exercised and rightly gathered members.
On the 14th, we went to our friend Charles Downing`'s, and lodged,
in order to be at Cain Quarter.

15th. In the select meeting, after the Queries and Answers were gone through,
I felt engaged to speak on the efficacy of faith;
that it was not only the substance of things hoped for,
and the evidence of things not seen, but by it, the Lord`'s children in all ages,
obtained the victory over their enemies within and without; and as we keep this faith,
looking to the Lord alone for preservation and deliverance,
under the many afflictions that may attend us, He will arise and carry us safely through.
Above all, said the apostle, taking the shield of faith.
We have had many extraordinarily gifted men and women among us, and perhaps,
have been confiding improperly in them;
but they have been removed from the church militant,
and our dependance must be turned to, and placed upon the Lord alone.
In his time He can again give gifts to sons and daughters,
and qualify them for his service;
and beautify the house of his glory where his honor dwells.

The Quarterly Meeting convened next day.
I was silent in both meetings.
It was distressing to see so many young people leaving the house,
as the partitions were closing; and some of the members not returning for some time;
even after a messenger had been sent to desire them to come in.
It is discouraging that so little effect seemed to follow the
affectionate labor bestowed upon them by exercised servants,
and ministers of the gospel of Christ.

18th. The different reports of the men sent by Moses to search the land of Canaan,
are descriptive of the different voices there are in Christendom,
on the subject of religion; producing their respective effects upon the people.
Those who made false reports were not permitted to enter the promised land;
by whom the people were discouraged, and though entreated by Caleb and Joshua,
would not go up and take possession of it; but, refusing to obey the will of the Lord,
they were turned into the wilderness, as many now are, in a spiritual sense.
When they found what awaited them for their disobedience,
they determined to go up in their own wills;
but having taken the government into their own hands, many were slain by their enemies,
who met and destroyed them; and the rest were turned back,
to perish in their wilderness abode.
So it seems to me, that such as disregard the voice of the Holy Spirit in their hearts,
and refuse to obey the Lord`'s will, are left in a bewildered condition,
and fail to find the state of rest and peace which
those do who go forward at the Lord`'s bidding.
They are left in a way to be destroyed, if they continue unwilling to receive the Savior,
when He shall again visit their souls with the offers of his mercy and saving light.

Twelfth month 2nd. This has been a day of deep proving, and fears.
In the afternoon meeting, a warning was held forth to those who are at ease;
neglecting their day`'s work, and the calls of Divine grace in the heart.
Our Savior said, "`That many shall come from the east and the west,
and shall sit down with Abraham, Isaac and Jacob, in the kingdom of heaven;
but the children of the kingdom shall be cast out into outer darkness;`"
those who have had many invitations of the Grace of God,
but after having these favors, have put off a compliance with the Divine call,
to a period at which they may think it will suit their convenience;
while they know not at what hour the Son of Man may come to call them to judgment.
Some comfort was handed to the suffering seed, who are bearing heavy burdens;
who are let down into low places; and under a sense of their nothingness,
and the dangers that surround them,
are crying to the Lord for protection against the assaults of the evil one.

17th. After a visit to West-town; I returned with some cold, and have since been unwell;
affected with dizziness, and some oppression.
It seemed like the gradual breaking down of the tabernacle; in which my sight,
and hearing, and nervous system, are giving way;
and my thoughts were directed towards the end of my pilgrimage.
I was brought to a very low estimate of myself;
craving that the Lord`'s mercy might be extended to me, a poor unworthy creature;
and that my sins, even the sins of my youth, might be forgiven,
and washed away by my dear and holy Redeemer; I having nothing of my own to rely upon.
My feelings were peaceful, in the midst of poverty and great unworthiness.

1861, First month 16th.
This morning we have received the affecting
intelligence of the decease of our beloved and honorable brother,
Joseph Rhoads, after about thirty-six hours sickness.
He was a man of remarkable uprightness in his dealings;
showing much consideration for the necessities of those employed by him.
He was possessed of good understanding, and fond of useful reading;
and was strictly careful in his conversation to
avoid saying anything to the prejudice of others;
so that he was more noted for his silence in company, and in meetings for discipline,
than for much speaking.
As an elder,
though his diffidence withheld him from much activity in that important station,
yet he gave evidence that he was sound in principle,
and steadfast in supporting the testimonies and discipline of our religious Society.
He accompanied me in several religious visits, and always maintained much equanimity,
and a solid exemplary deportment, wherever we went;
expressing his comfort when meetings were got through,
under feelings of the authority and help of the Head of the church.

Second month 2nd. Our Quarterly Meeting of Ministers and Elders, was very small;
nine or ten of the members being absent; and though I believe Divine help was with us,
the feeling of the state of the meeting was trying.

4th. The meetings for worship and for discipline, were pretty satisfactory;
some of the ministry being lively.

7th. I attended Abington Quarterly Meeting; which was smaller than I expected,
considering how many citizens have removed to Germantown.
I was brought into near sympathy with some in the meeting,
who are baptized into low places,
and partake of much discouragement on account of the degeneracy in the present day.
I hope the Lord extended a hand of help;
and the meeting was ended with prayer for the
Lord`'s continued mercy and preserving power.
Some exercise prevailed in the second meeting for the support of our testimonies.
I came away with the hope that I had been in my place.

15th. On the 13th and 14th, I attended Salem Quarterly Meeting, held at Woodbury.
There were present at the Select Meeting, three men and four women Friends;
some being kept away by indisposition.
The number of aged, experienced Friends in the stations of minister and elder,
and those truly prepared for those stations,
has become much reduced in our Yearly Meeting; yet among the young people,
we may hope the preparing hand is at work,
to fit them for service in the militant church.
Friends who are rightly exercised for the cause of Truth, are often brought low;
and put up their secret petitions to the Lord of the harvest,
that He would send forth laborers into his harvest field.
I thought the Master of assemblies helped us, and enabled us to minister to the people.
I returned home in the afternoon, with peaceful feelings.

Third month 14th. Attended Haddonfield Quarterly Meeting; in the first part of which,
my wife was engaged in humble supplication to the Lord,
for the extendings of his Divine help for the burden bearers;
and for the gathering of the children.
In the meeting for business,
I thought it right to revive the injunction of our blessed Lord;
"`What I say unto you, I say unto all. Watch.`"
"`Watch and pray, lest you enter into temptation.`"

It is not beginning well, and running well for a time; but those who held out to the end,
that shall be saved.
He also said to one of the churches, "`Because you have kept the word of my patience,
I also will keep you from the hour of temptation, which shall come upon all the world;
to try them that dwell upon the earth.`"
Satan hates this religious Society, and is trying to lay it waste;
but He that sits in the heavens shall laugh;
the Lord shall have them in derision who join in this work.
I encouraged Friends to keep inward, in their tents, with their eye to the Lord.
I believed his hand was stretched out to sons and daughters;
whom He was bringing under exercise, to prepare them for his services;
and reminded them of the importance of keeping near to one another,
and to submit to the work of Divine Grace in the heart;
that so they might be washed and sanctified, and justified,
in the name of the Lord Jesus, and by the spirit of our God.
This would unite us together in the bond of peace.

Fifth month 28th. I went to the Northern District,
where I was exercised on the importance of learning and
practicing patience and resignation to the Divine Will.
That as we quietly bore the afflictions and sufferings that come upon us,
the Lord would sanctify them to us, and finally turn Satan backward;
releasing us from his buffetings and temptations;
and causing his own peace and love to flow into our hearts.
This would keep out all enmity towards others.
And as we were drawing nearer every day to the judgment seat of Christ,
we should strive to have our hearts sweetened by his love;
and herein the unity of the Spirit would increase among us.
We shall never become the Society we were in the beginning,
unless all ill-will is cast out, and we show forth the fruits of the Spirit of the Lamb,
as Friends did then, under contumely, reproach and persecution,
which had a powerful effect to convince others of the truth of their principles;
and draw many to join them.

Sixth month 4th. The weather, almost through the whole Spring, had been very changeable;
about double the usual depth of rain having fallen.
A cloudy, dull atmosphere has been depressing;
and with the mournful state of the country,
makes everything around us give the feeling of sadness.
War with the Southern States has greatly injured trade and commerce;
involving the Government in a great debt;
and bringing lack and distress upon many people.
Engagements between several small bodies of troops,
have been attended with destruction of human life, which administers increased sorrow.
Men shooting or cutting one another down, simply to gain the ascendancy,
and to drive the survivors from their position,
is like the thoughtless cruelty of the beasts;
and shows a total absence of all respect for the value of an immortal soul,
the design of the Great Creator in giving existence to it,
and the inconceivable awfulness of being ushered into his dread presence,
either to join the saints in light,
or to be condemned to everlasting separation from the joys of his salvation.
Civil war has never before been known in this country; how far it may spread,
and in what destruction it may involve the inhabitants, we cannot foresee;
but at the present time there are few indications that
it will be speedily brought to a close.
Our hope and trust can be rightly placed in the Lord alone.
He only can restrain the wrath of wicked men, defeat their evil designs,
and deliver out of their hands his children, who have none in heaven to look to but Him;
and dare not resort to the arm of flesh to defend themselves.
Friends in this part of the country have been free from any apprehensions of danger,
so far; and I think, maintain a state of quietness and watchfulness,
so as not to baulk their testimony to the government of the Prince of Peace.

10th. We are sometimes in danger of overvaluing ourselves and our attainments,
and of being over-estimated by our kindhearted friends;
all of which have their dangerous effects, if not prevented by the daily watch,
in the fear of the Lord.
This morning, I was particularly abased, under a review of some of the sins of my youth,
and the feeling that what I had done in the persuasion of religious duty,
when the candle of the Lord shone about me,
and opened the way to perform what He required of me, was of but little avail.
I felt very much bereft of evidence of Divine regard,
so that it was difficult to believe I was an object of
the Lord`'s continued mercy and approbation.
But as I have often recommended the essential necessity
of experiencing the baptisms of the Holy Ghost and fire,
in order to consume thoroughly every impurity,
I desired to abide under the present humiliating feelings,
and secretly breathed that the Lord would not forsake me;
but would cut short the thread of my life,
rather than permit Satan to bring reproach by me, upon the blessed truth,
as professed by our Society.

It has been a day of close besetment, but this evening secret hope has been felt,
that the everlasting arm is still round about, and will sustain and defend me,
a poor unworthy one, against the assaults of the enemy; and in unmerited mercy,
wash away and pardon my many deviations and shortcomings,
through the spirit of judgment and burning, and by the precious blood of the Lamb.
We are nothing, Christ is all; and without his immediate help,
we can do nothing that is good.

13th. Feeling my mind drawn to the Arch Street Meeting, I went,
and through the condescending goodness of the blessed Shepherd, of the sheep,
I was enabled to hold forth the language of
encouragement to those who love the Lord Jesus;
of whom I believed there were many preserved.
The testimony of the apostle was revived; that "`Tribulation works patience,
and patience experience, and experience, hope; and hope makes not ashamed,
because the love of God is shed abroad in our hearts, by the Holy Ghost,
which is given unto us.`"
Whatever may be our tribulations, as this love abides in us,
we shall not only love God above everything else, but be brought to love all men;
so as to desire their salvation.
This path, as we keep the faith and patience of the saints, is a glorious path,
and will shine more and more unto the perfect day;
in which we shall be made victorious over all the temptations of Satan;
and be kept to the end, through the intercession of Christ,
who bore the cross for our sakes, and is set down at the right hand of the Father,
making intercession for us poor unworthy creatures.

Seventh month 3rd. My brother Joseph took me to Chester Meeting.
We found a larger company convened than I had expected.
My heart was replenished with love, drawing me to visit them;
and the language of the Master, and of his disciple was brought before me,
"`By this shall all men know that you are my disciples, if you have love one to another;`"
"`Little children love one another;`"
"`We know that we have passed from death unto life, because we love the brethren.`"
The essential importance of having our hearts filled with love to our Heavenly Father,
and showing its fruits by keeping his commandments, were opened to the company;
with sincere desires that love might increase more and more, and unite them together.
The qualification for usefulness in the church, and the happiness of individuals,
meetings and neighborhoods, greatly depend upon it.
Prayer was offered to the Father of mercies,
to watch over and defend us against the temptations of Satan;
and enable us to walk in holy fear,
and to be instrumental in spreading the kingdom of the Messiah; by living up to,
and supporting the principles and testimonies of the gospel.

Attended our Select Preparative Meeting on the 22nd, and our Monthly Meeting on the 24th;
in which the usual business of replying to the Queries, was harmoniously attended to.
I also attended the North Monthly Meeting, and that held at Arch Street;
in which a fresh ability was furnished to preach the gospel,
and to labor for the support of our christian testimonies.

Eighth month 11th. At the first-day meeting at Springfield;
which was pretty well attended.
The doctrine of regeneration,
and knowing the Divine influence of the Holy Spirit in the heart, was preached,
to those present.
It was shown that as we live and walk in it,
the heavenly nature of the Spirit of Christ will subdue our passions and propensities;
and enable us to love our enemies,
to pray for them that despitefully use and persecute us;
that so we may be the children of our Father which is in heaven;
who makes his sun to shine on the evil and on the good,
and sends rain on the just and on the unjust.
True christians cannot draw the sword against any, but would seek the good of all,
and to be instruments for spreading the kingdom of Christ in the earth.

12th. With our brother and sister, J. and G. E., my wife and I, left home for Concord,
to attend the Quarterly Meeting; where we stopped at our dear friend`'s N. Sharpless;
and then attended the Meeting of Ministers and Elders.

13th. The forepart of the Quarterly Meeting was silent, except two short communications.
Feelings of distress prevailed over many;
the spring of Divine life being closed by some cause.
The usual business was transacted, and towards the close,
I felt constrained to advert to our testimony to the peaceable reign of the Messiah;
and to show the essential importance of maintaining love and unity among ourselves,
if we desire to bear this testimony faithfully, before the world.
Even under a former dispensation, it was said,
"`Behold how good and how pleasant it is for brethren to dwell together in unity.
It is like the precious ointment upon the head, that ran down upon the beard,
even Aaron`'s beard, that went down to the skirts of his garments.
As the dew of Hermon, and as the dew that descended upon the mountains of Zion;
for there the Lord commanded the blessing, even life forevermore.`"
We have need of individual examination, and watchfulness,
to guard us against giving way to any spirit or practice,
that would lay waste the Society or hurt its members.

22nd. Being prevented from attending my own, I went to the Arch Street Meeting;
which was very small, the weather being wet;
but the comforting influence of Divine Good was spread over us.
"`Why are you cast down, oh, my soul; and why are you disquieted within me!
Hope you in God, for I shall yet praise Him,
who is the health of my countenance and my God.`"
These expressions of the Psalmist were brought before me,
as applicable to the low state of some present; and in simplicity and godly sincerity,
I revived them,
and was led to encourage all to keep the faith which had been given to them;
and the Lord who knows our impotency, will keep us by his invisible power,
and defend us against all the devices of the enemy.
"`As the mountains are round about Jerusalem, so the Lord is round about his people,
from henceforth even forever.`"
A feeling of humble,
childlike tenderness seemed to be spread over us at the close of the meeting,
which had a uniting effect, and was a sweet reward.

Ninth month 9th. This morning, I went to my friends S. and B. Nicholson, at Haddonfield,
and attended their Monthly Meeting.
The necessity of bearing patiently the light afflictions, which are but for a moment,
that we may be humbled, emptied of all self-confidence,
and brought to see that we are nothing, whatever may have been our gifts,
and past experience, was revived in my mind;
and believing that there were those among us, who were enduring suffering,
and watching unto prayer for their own preservation,
and for the spreading of the Redeemer`'s kingdom,
I was induced to address them in the sympathy and fellowship of the gospel;
reminding them, that it had been the lot of the Lord`'s children in all generations.
The "`fathers were under the cloud, and all passed through the sea,
and were all baptized unto Moses in the cloud, and in the sea;
and did all eat the same spiritual meat, and did all drink the same spiritual drink;
for they drank of that Rock that followed them; and that Rock was Christ.`"
As we are baptized by one Spirit into one body, and made to drink into one Spirit,
we experience the love and fellowship of the gospel,
to circulate as from vessel to vessel.
Poverty and emptiness had been my feelings in coming to the meeting,
and in sitting there; but I hoped there was something of the springing up of Divine life,
and that we were a little cheered together.

Eleventh month.
In contemplating the trials and overturnings to which our religious
Society has been subjected for many years in this country,
I was made to believe a few days since, that the gracious Shepherd was still near to us,
and that the time was not very far off, when He would go through his flock,
and renew the visitations of his love to the younger members.
That He would bestow gifts upon them, to be occupied in his church;
and prepare and send forth servants to proclaim and spread the doctrines of the gospel,
and his blessed cause, from sea to sea; and from the rivers to the ends of the earth.
Hereby the beauty, and strength, and influence of our Society, in this Yearly Meeting,
and in this city, will be restored;
and a body of solid and deeply experienced men and women, it appeared to me,
would be again raised up as standard bearers, and watchmen upon the walls of Zion.
May the Lord hasten it in his time and way;
and enable us to continue to bear patiently the sufferings that remain for us to endure;
for our own sakes, and for one another, whatever they may be.

4th. The Quarterly Meeting for Discipline, was a season of favor.
The spring of gospel ministry was afresh opened; in which several were made partakers;
and the open service was closed with prayer, that He,
who in mercy had visited us in early days, and been with us all our life, unto this day,
would continue to watch over us, warn us of surrounding dangers,
and deliver us from them; and that He would visit the young people,
and raise up instruments in his blessed cause;
to join in spreading the kingdom of his dear Son, our Lord Jesus Christ, from sea to sea,
and from the rivers to the ends of the earth.
Much weight and solemn quiet continued throughout both meetings;
and Friends spoke of it to one another as a time of comfort and encouragement.

Having received an invitation from our dear friend, Martha Wistar,
to accompany S. and B. Nicholson, in a visit to her, at her residence,
near Salem, N. Jersey, on the 11th, my dear wife and I went to Haddonfield;
hoping that the ride and visit would be reviving and invigorating to my wife`'s health,
which had been in a precarious state for several years.

On the 12th, we rode down to Martha Wistar`'s; my wife conversed very cheerfully,
appearing to enjoy the ride, and remarking on the beauty of the country,
as we passed through it.

Next day, the 13th,
we all attended the Quarterly Meeting of Ministers and Elders held in Salem;
towards the close of which, after a Friend had spoken to one of the Queries,
my wife made some remarks in unison with what had been said; and then added;
that during the time we had been sitting together, she had dwelt much on the language,
"`Men ought always to pray and not to faint.`"
That while she had no unity with the spirit of activity
that was so much abroad in the present day,
which would lead to the repetition of mere words;
she believed the state of the church called for deep indwelling, and travail of spirit,
before the Lord; to this she encouraged all,
and said she believed there were some struggling ones there who were silently pleading,
as at the Master`'s feet, for preservation; begging for themselves and for the church.
The Lord regards such as these, and would regard them.
They wear their sackcloth underneath, and that is right;
and such were the salt of the earth.
And although discouragement might so abound, that some who were so exercised,
might conclude they were among the hindermost of the flock,
or might even doubt whether they were of the flock of Christ,
yet as they struggled to maintain the warfare, preservation would be experienced.
That it was in the night season, Jacob wrestled with the angel;
and it was declared of him, "`As a prince, have you power with God, and have prevailed.`"
She mentioned what a mercy it was, that we have a High Priest,
who is touched with a feeling of our infirmities; and she wished to encourage all,
to persevere in this deep, inward, fervent prayer.
She did believe,
that as such an exercise was maintained by those who mourned for the desolation of Zion,
judges would be raised up, as at the first, and counsellors as at the beginning:
adding "`It is my firm belief, and faith, that it will be so;
though I may not live to see it, yet it will be so.`"

We returned to Martha Wistar`'s, and dined; and towards evening went to S. D.`'s,
where we took tea, and passed the evening in cheerful conversation,
and then returned to our lodgings.
We retired at usual bed-time,
when my dear wife seemed as well as she had been for some time;
but a little after two o`'clock, she awoke with uncomfortable feelings,
and appeared unable to bear a recumbent position.
Various means were tried to renew the impeded circulation, but in vain;
and she quietly expired without any apparent pain or struggle,
in about an hour after she first showed difficulty of breathing.

To me, the breaking of a tie, that made us one flesh,
and in which we were affectionately united in the one Spirit,
and fellowship of the pure gospel of Christ, was a deeply affecting and unexpected event.
But though deeply afflicted, the Lord was merciful,
in sustaining my poor soul above the billows;
and enabling me to look to Him for support and preservation,
now my most faithful companion, and cheerful,
experienced counsellor and comforter was taken away,
in the ordering of his inscrutable wisdom.

No one who has not had such a valuable and closely united helpmeet,
through many spiritual trials, can be sensible of the loss I sustained,
and the depth of affliction into which I have
been plunged by the removal of my dear wife.
She was a mother in Israel;
a cherisher of the children in the early buddings of the fruits of the Spirit,
in their tender minds; and an encourager and strengthener of the weary traveler,
bearing burdens for Zion`'s sake,
and the support and spreading of the Redeemer`'s
cause of truth and righteousness in the earth,
in our own Society; and also as she came into their company,
among those of other religious denominations.

A messenger was sent to Philadelphia next morning,
to convey the sorrowful intelligence to my brothers, and by them to our beloved children;
to whom it was a great shock.
Several came down to us that evening,
and next morning we accompanied the remains in the steamboat, to the city;
where we met others at our house, clothed with sadness.
On landing at the wharf, I recollected that I went away, as it were, full,
and now returned empty, as to any feeling of earthly enjoyment.
As I rode down the street, loaded with deep affliction, a voice passed through my mind,
as if uttered by one of the heavenly company, "`She is among the glorified in light.`"
This was a most quickening salutation,
and while it gave evidence that the redeemed spirit of my precious, departed one,
was partaking of the joys of God`'s salvation,
with the countless multitude with palms in their hands,
of which she had often borne testimony in her gospel ministry;
it also showed that through the same unmerited mercy and condescension,
I was not overlooked or forgotten in my deep distress.

It raised thanksgiving and praise to the Lord my God,
who had been with me all my life-long; fed me and kept me unto this day;
in the hope that He would still condescend to be with me,
and keep my head above the billows,
and preserve me as in the hollow of his omnipotent Hand,
so that I may be enabled to fill up the measure of suffering and duty that He may allot;
know all my sins to be forgiven,
and my garments washed and made white in the blood of the Lamb,
and be accepted at last through Him, my gracious Redeemer.

The interment took place on second-day the 18th of the Eleventh month.
Great interest and love for her were manifested, in the very large company,
who convened at that time and viewed her placid, sweet countenance,
over which many tears were shed, in the remembrance of her christian spirit,
and fervent labors for the good of souls.
Before the company left the house, several Friends, well acquainted with her,
bore testimony to her religious standing and worth, as a servant of Christ;
who neither turned to the right hand nor to the left,
but faithfully discharged her duty to her Lord and Master, for the good of souls,
and the support and spreading of his blessed cause.

1862+++.+++ Many deep baptisms have I passed through, and feelings of great loneliness,
since the death of my beloved and valuable wife;
who was a great support and comfort to me,
in our united travail for the salvation of our own souls, and of our dear children,
as well as of others.
But though greatly stripped at times,
the Lord`'s mercy and compassion towards a poor creature, have not been withdrawn.
I have been enabled to put up breathings of spirit to Him for preservation to the end.

Our Yearly Meeting held in the Fourth month this year,
was often favored with solemnity and religious weight.
The first sitting was attended with feelings of strong desire
for the restoration of unity through the Yearly Meetings.
Friends were much tendered, particularly the young people;
and one or two expressed their hope of the return of true fellowship.
The presence of the Great Head of the church was remarkably felt over the meeting.

Fifth month.
Feeling my mind drawn into sympathy with Friends of Abington Quarter,
I attended that meeting, and in the love of the gospel,
was enabled to visit the tribulated members; who,
like their brethren and sisters elsewhere,
have to drink of the cup of suffering and fear, for the good cause`' sake.
I believe holy help was extended, and we were baptized by the one Spirit into one body,
and were enabled to thank our Holy Helper, and to take a little fresh courage.
