== Conclusion

The last entry made by my brother in his diary, was that dated Fifth month, 1862.
His sight had been long impaired by cataract in one eye,
and the incipient stage of the same disease in the other.
The loss sustained by the death of his beloved and valuable wife,
though borne with christian patience and resignation,
as the infirmities of old age pressed upon him, was an ever present source of sorrow;
which,
with the irreparable shock given to his nervous
system by her sudden and unexpected removal,
soon greatly affected his general health.
His sight failed rapidly,
and it was not long before he was unable to see to read or to write.
To one whose mind had always been active,
and who had accustomed himself to employ much time in the use of the pen,
or in the perusal of books congenial with the tone of his thoughts and feelings,
this privation was keenly felt.
But as he was thus cut off from some outward sources of mental enjoyment,
his attention was more and more withdrawn from external things,
and in reverent retirement before the Lord,
centered on the inward manifestations of his Spirit.
In this deep introversion, he was often brought into low places,
and close searching of heart; renewing those humiliating views of himself,
of his attainments in the way of holiness,
and of his faithfulness in occupying the gifts,
and making a right return for the manifold mercies bestowed upon him;
of which he often speaks in his Journal.
Not, as he said, that he found any thing laid to his charge,
or that there was any known duty which he had refused to perform;
but such was his sense of the frailty of human nature, and the awfulness of the soul,
when unclothed of mortality,
being ushered into the immediate presence of infinite and immaculate Purity,
that he felt there could be no hope for him, nor for any,
but as in immeasurable condescension, an undoubted assurance was granted of acceptance,
through that Savior who died for poor, lost man,
and whose mercy covered the judgment seat.

Although much restricted by lack of sight, and the continued, though gradual,
decline of strength, from going far from home,
he continued frequently to attend different meetings in the city,
and occasionally visited one or more in the country, at no great distance.
It was always a source of satisfaction to him thus to mingle with his friends,
to unite with them in waiting on the Lord,
and in seeking for ability to render to Him acceptable worship in spirit and in truth.

The Friends of the respective meetings, to which he belonged,
testify respecting him and his services during that period, that, "`His ministry,
though not frequent, continued to be lively and weighty;
sometimes inviting the young to take the yoke of Christ upon them,
so that they might secure the proper enjoyment of the things of this world,
and a well-grounded hope of admittance into the company of saints and angels hereafter,
and calling on his fellow members,
not to rest satisfied with anything short of complete sanctification;
that being grafted into Christ, the living Vine,
they might be made fruit-bearing branches, and through the renewings of the Holy Ghost,
bring forth much fruit, to the glory of God the Father.
In the Sowings of gospel love towards his fellow men,
and especially towards those of the same household of faith,
he often expressed his fervent desire for their
establishment and growth in the unchangeable Truth;
on several occasions remarking, he felt that if he had but bodily ability,
and it was his Master`'s will, he would cheerfully go forth once more through the Society,
to preach the glad tidings of salvation.`"
The last time he got out to meeting,
was in the afternoon of first-day the 30th of the Twelfth month, 1866.
A few days after, he rode to the residence of two women Friends,
members of the same meeting with himself,
who had been sometime confined by indisposition, where he was engaged in the ministry.

This was the last visit he made.
The next morning, First month 6th, 1867,
he was seized with great difficulty of breathing,
and from that time the disease that finally terminated his life, was rapidly developed.
As the circulation became more and more impeded, the difficulty of breathing increased;
and about the middle of the Third month, he became unable to bear a recumbent position,
so that for more than two weeks he remained almost constantly in a sitting position,
enduring great weariness and oppression.
The remedies resorted to were, however,
so far successful in relieving the severity of his symptoms,
as to allow him again to recline in bed.
Though free from acute pain, his suffering was great, and was borne without murmuring,
he often remarking,
that though he found the infirmities of the flesh as much as he could well endure,
they were doubtless permitted in Divine wisdom,
and were intended for his further refinement.

During his long confinement,
he continued to maintain a lively interest in the welfare of our religious Society;
manifesting on different occasions, the earnest travail of his soul,
that Friends might be drawn more nearly together in the fellowship of the gospel,
and be willing faithfully to support the doctrines and testimonies,
which he believed the great Head of the Church had
raised up the Society to exemplify to the world.
He was frequently visited by many of his beloved fellow members, ministers and others,
and many precious opportunities were thus afforded for retirement before the Lord;
and not unfrequently he was clothed with ability to minister to those present;
as were others to speak in the language of comfort and encouragement to him.
On more than one occasion he expressed his earnest desire that
nothing might be said by way of commendation;
nor, unless they felt Divinely authorized,
should any speak as though his salvation was secured;
for he felt that the watch and the warfare must be continued to the end,
if the crown immortal was, through mercy, obtained.
Notwithstanding these humble views of himself,
and the care he manifested not to presume on any past experiences,
he on more than one occasion intimated that his
gracious Master had given him the assurance,
that when done with time, he should be admitted into everlasting rest.

During the time of holding the Yearly Meeting in the Fourth month of 1867,
he was frequently brought under much exercise.
The separation from his friends,
when thus gathered to transact the affairs of the church,
a work which had long been dear and deeply interesting to him, was keenly felt,
but was borne with patience and resignation.
At different times his spirit was bowed in sympathy with his brethren,
earnestly desiring that the different important subjects
before the meeting might be resulted in the authority of Truth;
and rejoicing when he heard of seasons of Divine favor being granted to the assembly.

Two Friends, one of them a minister, having called to see him, after the Yearly Meeting,
he manifested that he still cherished the concern he had long felt,
for the right education of the children of Friends, by addressing one of them,
whom he was told had been appointed on the committee
having the oversight of West-town Boarding School;
encouraging him to bear in mind,
while employed in the business necessary in carrying on the school,
that there was matter of more serious importance connected with it;
and that if he was concerned to seek for Divine counsel in attending to that,
he might himself experience a growth in the Truth;
reminding him of the expression of Thomas Scattergood,
in the early days of the Institution,
"`That if Friends were faithful to their principles in conducting it,
it was a plantation the Lord would bless.`"
The minister having addressed him in an encouraging manner, after a little pause,
he said in a broken voice,
"`May the Lord in his unmerited mercy remove and forgive all
those things which are contrary to his Divine will;
that we may, through mercy, unmerited mercy,
know a preparation for an admittance into his kingdom of rest and peace.`"

During the last few days of his life, he conversed but little;
not only because the oppression made it difficult for him to speak,
but his mind appeared to be fixed in the contemplation of the change that awaited him,
and in being fervently engaged to be found ready when the summons came.

His decease took place on the morning of the 12th of the Fifth month, 1867,
in the 81st year of his age.
"`Blessed are the dead which die in the Lord, from henceforth; yes says the Spirit,
that they may rest from their labors, and their works do follow them.`"
